from django.conf.urls import url

from juloserver.dana.loan.crm import views as DanaCRMViews
from juloserver.dana.repayment.crm import views as DanaRepaymentCRMViews
from juloserver.dana.refund.crm import views as DanaRefundCRMViews
from juloserver.merchant_financing.crm import views as MerchantFinancingCRMViews
from juloserver.dana.dana_lender.crm import views as DanaLenderCRMViews
from juloserver.merchant_financing.web_app.crm import views as MfWebAppCRMViews
from juloserver.partnership.crm import views as PartnershipCRMViews
from juloserver.grab.crm import views as GrabCRMViews
from juloserver.application_flow import views as OnboardingCRMViews
from juloserver.warning_letter.crm import views as WarningLetterCRMViews
from . import views

urlpatterns = [

    # --- role admin full begin ---
    url(r'^all/$', views.bulk_upload_view, name='all'),
    url(r'^merchant-financing-csv-upload/$', views.merchant_financing_csv_upload_view,
        name='merchant_financing_csv_upload'),
    # This endpoint is depricated
    # url(r'^loan-halt-or-resume/$', views.loan_halt_or_resume, name='loan-halt-or-resume'),
    url(r'^grab-loan-restructuring/$', views.grab_loan_restructuring,
        name='grab_loan_restructuring'),
    url(r'^early_write_off/$', views.early_write_off,
        name='early_write_off'),
    url(r'^dana/bulk_update_loan_fund_transfer_ts/$',
        DanaCRMViews.dana_bulk_update_loan_fund_transfer_ts_view,
        name='dana_bulk_update_transfer_fund_ts'),
    url(r'^dana/bulk_update_loan_fund_transfer_ts_history/$',
        DanaCRMViews.dana_bulk_update_loan_fund_transfer_ts_history.as_view(),
        name='dana_bulk_update_transfer_fund_ts_history'),
    url(r'^dana/dana-upload-payment-settlement-file/$',
        DanaCRMViews.dana_upload_payment_settlement_file,
        name='dana_upload_payment_settlement_file'),
    url(r'^dana/dana-upload-payment-settlement-file-history/$',
        DanaCRMViews.DanaPaymentSettlementUploadHistory.as_view(),
        name='dana_upload_payment_settlement_file_history'),
    url(r'^referral_program/$', views.grab_referral_program,
        name='referral_program'),
    url(r'^dana/dana-upload-pusdafil-data/$',
        DanaCRMViews.dana_upload_pusdafil_data,
        name='dana_upload_pusdafil_data'),
    url(r'^dana/dana-upload-pusdafil-data-history/$',
        DanaCRMViews.DanaUploadPusdafilDataHistory.as_view(),
        name='dana_upload_pusdafil_data_history'),
    url(r'^dana/dana-upload-refund-payment-settlement-file/$',
        DanaRefundCRMViews.dana_upload_refund_payment_settlement_file,
        name='dana_upload_refund_payment_settlement_file'),
    url(r'^dana/dana-upload-refund-payment-settlement-file-history/$',
        DanaRefundCRMViews.DanaRefundPaymentSettlementUploadHistory.as_view(),
        name='dana_upload_refund_payment_settlement_file_history'),
    url(r'^dana/dana-upload-repayment-settlement-file/$',
        DanaRepaymentCRMViews.dana_repayment_settlement,
        name='dana_repayment_settlement'),
    url(r'^dana/dana-upload-repayment-settlement-file-history/$',
        DanaRepaymentCRMViews.DanaRepaymentSettlementUploadHistory.as_view(),
        name='dana_repayment_settlement_upload_history'),
    url(
        r'^dana/dana-lender-upload-payment/$',
        DanaLenderCRMViews.dana_lender_upload_payment,
        name='dana_lender_upload_payment',
    ),
    url(
        r'^dana/dana-lender-upload-payment-history/$',
        DanaLenderCRMViews.DanaLenderPaymentUploadHistory.as_view(),
        name='dana_lender_payment_upload_history',
    ),
    url(r'^merchant-financing/register-history/$',
        MerchantFinancingCRMViews.MerchantFinancingRegiserUploadHistory.as_view(),
        name='merchant_financing_register_upload_history'),
    url(r'^merchant-financing/disbursement-history/$',
        MerchantFinancingCRMViews.MerchantFinancingDisbursementUploadHistory.as_view(),
        name='merchant_financing_disbursement_upload_history'),
    url(r'^merchant-financing/adjust-limit-history/$',
        MerchantFinancingCRMViews.MerchantFinancingAdjustLimitUploadHistory.as_view(),
        name='merchant_financing_adjust_limit_upload_history'),
    url(r'^dana/dana-deposit-deduction-upload/$',
        DanaCRMViews.dana_deposit_deduction_upload,
        name='dana_deposit_deduction_upload'),
    url(r'^dana/dana-upload-refund-repayment-settlement-file/$',
        DanaRefundCRMViews.dana_upload_refund_repayment_settlement_file,
        name='dana_upload_refund_repayment_settlement_file'),
    url(r'^dana/dana-upload-refund-repayment-settlement-file-history/$',
        DanaRefundCRMViews.DanaRefundRepaymentSettlementUploadHistory.as_view(),
        name='dana_upload_refund_repayment_settlement_file_history'),
    url(r'^mf-webapp-list-application-document-upload/$',
        MfWebAppCRMViews.ApplicationMFWebAppListApplicationStatusView.as_view(),
        name='mf_web_app_list_documents_upload'),
    url(r'^mf-webapp-application-document-upload/(?P<pk>\d+)$', MfWebAppCRMViews.mf_web_app_upload_documents,
        name='mf_web_app_documents_upload'),
    url(r'^mf-webapp-csv-upload/$', MfWebAppCRMViews.mf_web_app_csv_upload_view,
        name='mf_web_app_csv_upload'),
    url(r'^mf-webapp-csv-upload-data-history/$',
        MfWebAppCRMViews.MFWebAppRegiserUploadHistory.as_view(),
        name='mf_web_app_csv_upload_data_history'),
    url(r'^mf-webapp-csv-loan-upload$', MfWebAppCRMViews.mf_webapp_csv_loan_upload,
        name='mf_webapp_csv_loan_upload'),
    url(r'^mf-webapp-csv-loan-upload-docs$', MfWebAppCRMViews.mf_webapp_csv_loan_upload_docs,
        name='mf_webapp_csv_loan_upload_docs'),
    url(r'^mf-webapp-csv-loan-upload-submit$', MfWebAppCRMViews.MFWebAppCSVLoanUploadSubmitView.as_view(),
        name='mf_webapp_csv_loan_upload_submit'),
    url(r'^mf-webapp-loan-list$', MfWebAppCRMViews.MFWebAppLoanListView.as_view(),
        name='mf_webapp_loan_list'),
    url(r'^mf-webapp-csv-disbursement-upload$', MfWebAppCRMViews.mf_webapp_csv_disbursement_upload,
        name='mf_webapp_csv_disbursement_upload'),
    url(r'^mf-webapp-resend-skrtp$', MfWebAppCRMViews.mf_webapp_resend_skrtp,
        name='mf_webapp_resend_skrtp'),
    url(r'^mf-webapp-repayment-upload$', MfWebAppCRMViews.mf_webapp_csv_repayment_upload,
        name='mf_webapp_csv_repayment_upload'),
    url(
        r'^mf-webapp-repayment-upload-per-loan$',
        MfWebAppCRMViews.mf_webapp_csv_repayment_upload_per_loan,
        name='mf_webapp_csv_repayment_upload_per_loan',
    ),
    url(r'^agent-assisted/pre-check-user-upload/$',
        PartnershipCRMViews.agent_assisted_pre_check_user_upload,
        name='agent_assisted_pre_check_user_upload'),
    url(r'^agent-assisted/pre-check-user-upload-history/$',
        PartnershipCRMViews.AgentAssistedPreCheckUserUploadHistory.as_view(),
        name='agent_assisted_pre_check_user_upload_history'),
    url(r'^agent-assisted/upload-scoring-user-data/$',
        PartnershipCRMViews.agent_assisted_scoring_user_data_upload,
        name='agent_assisted_scoring_user_data_upload'),
    url(r'^agent-assisted/upload-scoring-user-data-history/$',
        PartnershipCRMViews.AgentAssistedScoringUserDataUploadHistory.as_view(),
        name='agent_assisted_scoring_user_data_upload_history'),
    url(r'^agent-assisted/fdc-pre-check-user-upload/$',
        PartnershipCRMViews.agent_assisted_fdc_pre_check_user_upload,
        name='agent_assisted_fdc_pre_check_user_upload'),
    url(r'^agent-assisted/fdc-pre-check-user-upload-history/$',
        PartnershipCRMViews.AgentAssistedFDCPreCheckUserUploadHistory.as_view(),
        name='agent_assisted_fdc_pre_check_user_upload_history'),
    url(r'^agent-assisted/upload-complete-user-data-status-update/$',
        PartnershipCRMViews.agent_assisted_complete_data_status_update,
        name='agent_assisted_upload_complete_user_data_status_update'),
    url(r'^agent-assisted/upload-complete-user-data-status-update-history/$',
        PartnershipCRMViews.AgentAssistedCompleteDataStatusUpdateUploadHistory.as_view(),
        name='agent_assisted_upload_complete_user_data_status_update_history'),
    # Product Financing
    url(r'^product-financing-csv-upload/$',
        PartnershipCRMViews.product_financing_csv_upload_view,
        name='product_financing_csv_upload'),
    url(r'^product-financing-csv-upload/loan-creation-upload-history/$',
        PartnershipCRMViews.ProductFinancingUploadHistory.as_view(),
        name='product_financing_loan_creation_upload_history'),
    url(r'^product-financing-csv-upload/disbursement-upload-history/$',
        PartnershipCRMViews.ProductFinancingUploadDisbursementHistory.as_view(),
        name='product_financing_disbursement_upload_history'),
    url(r'^product-financing-csv-upload/repayment-upload-history/$',
        PartnershipCRMViews.ProductFinancingUploadRepaymentHistory.as_view(),
        name='product_financing_repayment_upload_history'),
    url(
        r'^product-financing-csv-upload/lender-approval-upload-history/$',
        PartnershipCRMViews.ProductFinancingUploadLenderApprovalHistory.as_view(),
        name='product_financing_lender_approval_upload_history',
    ),
    url(
        r'^grab/grab-promo_code-csv-upload/$',
        GrabCRMViews.grab_promo_code_csv_upload_view,
        name='grab_promo_code_csv_upload',
    ),
    # Onboarding/Julocredit
    url(
        r'^onboarding/waitlist-x155/$',
        OnboardingCRMViews.waiting_list_x155_upload,
        name='onboarding_waitlist_155',
    ),
    url(
        r'^grab/fdc-stuck-app-csv-upload/$',
        GrabCRMViews.fdc_stuck_application_upload_view,
        name='fdc-stuck-app-csv-upload',
    ),
    url(
        r'^warning_letter/pwl_delivery_data_csv_upload/$',
        WarningLetterCRMViews.pwl_delivery_data_csv_upload_view,
        name='pwl_delivery_data_csv_upload',
    ),
    url(
        r'^partnership-cancel-loan/$',
        PartnershipCRMViews.partnership_bulk_cancel_loan_view,
        name='partnership_bulk_cancel_loan',
    ),
]
