# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-01-10 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('julo', '0566_update_notification_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanSelloff',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='loan_selloff_id', primary_key=True, serialize=False)),
                ('principal_at_selloff', models.BigIntegerField(blank=True, default=0)),
                ('interest_at_selloff', models.BigIntegerField(blank=True, default=0)),
                ('late_fee_at_selloff', models.BigIntegerField(blank=True, default=0)),
                ('loan_selloff_proceeds_value', models.BigIntegerField(blank=True, default=0)),
                ('loan', models.OneToOneField(db_column='loan_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Loan')),
            ],
            options={
                'db_table': 'loan_selloff',
            },
        ),
        migrations.CreateModel(
            name='LoanSelloffBatch',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='loan_selloff_batch_id', primary_key=True, serialize=False)),
                ('parameter', models.CharField(choices=[('principal', 'principal'), ('principal_and_interest', 'principal_and_interest'), ('total_outstanding', 'total_outstanding')], db_index=True, max_length=100)),
                ('pct_of_parameter', models.FloatField()),
                ('vendor', models.CharField(db_index=True, max_length=200)),
            ],
            options={
                'db_table': 'loan_selloff_batch',
            },
        ),
        migrations.AddField(
            model_name='loanselloff',
            name='loan_selloff_batch',
            field=models.ForeignKey(db_column='loan_selloff_batch_id', on_delete=django.db.models.deletion.DO_NOTHING, to='loan_selloff.LoanSelloffBatch'),
        ),
        migrations.RunSQL(
            "ALTER TABLE loan_selloff ALTER COLUMN loan_id TYPE bigint;"),
    ]
