# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-12-27 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenderinvestment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MintosQueueStatus',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='mintos_queue_status_id', primary_key=True, serialize=False)),
                ('loan_id', models.BigIntegerField(unique=True)),
                ('queue_type', models.CharField(blank=True, choices=[('loan_sendin', 'loan_sendin'), ('payment_sendin', 'payment_sendin'), ('rebuy_loan', 'rebuy_loan')], max_length=50, null=True)),
                ('queue_status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'mintos_queue_status',
            },
        ),
    ]
