# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-01-15 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenderinvestment', '0005_sbmintosbuybacksendin_sbmintospaymentsendin'),
    ]

    operations = [
        migrations.CreateModel(
            name='MintosPaymentSendin',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='mintos_payment_send_in_id', primary_key=True, serialize=False)),
                ('application_xid', models.BigIntegerField(blank=True, null=True)),
                ('loan_id', models.BigIntegerField(blank=True, null=True)),
                ('payment_id', models.BigIntegerField(blank=True, null=True)),
                ('payment_date', models.DateField()),
                ('payment_schedule_number', models.IntegerField(blank=True, null=True)),
                ('principal_amount', models.BigIntegerField(blank=True, null=True)),
                ('interest_amount', models.BigIntegerField(blank=True, null=True)),
                ('total_amount', models.BigIntegerField(blank=True, null=True)),
                ('remaining_principal', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mintos_payment_send_in',
            },
        ),
    ]
