# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-01-20 11:09
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenderinvestment', '0008_mintosloanliststatus_interest_rate_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MintosReport',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='mintos_report_id', primary_key=True, serialize=False)),
                ('filename', models.TextField(unique=True)),
                ('email_date', models.DateField()),
                ('file_content', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mintos_report',
            },
        ),
    ]
