# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-02-04 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lenderinvestment', '0012_change_float'),
    ]

    operations = [
        migrations.CreateModel(
            name='MintosReportDetail',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='mintos_report_detail_id', primary_key=True, serialize=False)),
                ('mintos_loan_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('loan_status', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('loan_originator_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('loan_originator', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('country', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('interest_rate', models.FloatField(blank=True, default=None, null=True)),
                ('schedule_entries', models.IntegerField(blank=True, default=None, null=True)),
                ('initial_term', models.IntegerField(blank=True, default=None, null=True)),
                ('remaining_term', models.IntegerField(blank=True, default=None, null=True)),
                ('listed_on', models.DateTimeField(blank=True, default=None, null=True)),
                ('original_principal', models.FloatField(blank=True, default=None, null=True)),
                ('outstanding_principal', models.FloatField(blank=True, default=None, null=True)),
                ('invested', models.FloatField(blank=True, default=None, null=True)),
                ('invested_in_percent', models.FloatField(blank=True, default=None, null=True)),
                ('repaid_principal_to_investors', models.FloatField(blank=True, default=None, null=True)),
                ('acc_interest_investors', models.FloatField(blank=True, default=None, null=True)),
                ('repaid_interest_to_investors', models.FloatField(blank=True, default=None, null=True)),
                ('acc_interest_lenders', models.FloatField(blank=True, default=None, null=True)),
                ('acc_interest_mintos', models.FloatField(blank=True, default=None, null=True)),
                ('payment_status', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('collateral_value', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('ltv', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('collateral_type', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('listing_status', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('acc_late_payment_fee_investors', models.FloatField(blank=True, default=None, null=True)),
                ('acc_late_payment_fee_lenders', models.FloatField(blank=True, default=None, null=True)),
                ('currency', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('loan_type', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('buyback', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('loan_originator_account_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('total_invested', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('finished_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('repurchased_principal_from_investors', models.FloatField(blank=True, default=None, null=True)),
                ('repurchased_interest_from_investors', models.FloatField(blank=True, default=None, null=True)),
                ('bad_debt', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('buyback_reason', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('mintos_report', models.ForeignKey(blank=True, db_column='mintos_report_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lenderinvestment.MintosReport')),
            ],
            options={
                'db_table': 'mintos_report_detail',
            },
        ),
    ]
