# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-04-06 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenderinvestment', '0014_alter_mintos_report_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mintosloanliststatus',
            name='status',
            field=models.CharField(blank=True, choices=[('Decision', 'Decision'), ('Active', 'Active'), ('Payout', 'Payout'), ('Finished', 'Finished'), ('Declined', 'Declined'), ('Buyback Manual', 'Buyback Manual')], max_length=50, null=True),
        ),
    ]
