# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-04-16 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_refinancing', '0017_update_covid_extension_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrefinancingrequest',
            name='uuid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
