# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-05-13 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_refinancing', '0024_add_new_table_waiverrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrefinancingrequest',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
