# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-05-20 07:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loan_refinancing', '0027_remove_loanrefinancingrequest_expired_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrefinancingoffer',
            name='generated_by',
            field=models.ForeignKey(blank=True, db_column=b'generated_by_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='loanrefinancingoffer_generated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanrefinancingoffer',
            name='selected_by',
            field=models.ForeignKey(blank=True, db_column=b'selected_by_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='loanrefinancingoffer_selected_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
