# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-05-21 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_refinancing', '0028_add_field_generated_by_and_selected_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiverrequest',
            name='is_automated',
            field=models.BooleanField(default=False),
        ),
    ]
