# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-05-20 07:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('loan_refinancing', '0030_add_field_comms_channels'),
    ]
    operations = [
        migrations.AddField(
            model_name='loanrefinancingoffer',
            name='interest_discount_percentage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanrefinancingoffer',
            name='latefee_discount_percentage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanrefinancingoffer',
            name='principal_discount_percentage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
