# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-07-16 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_refinancing', '0038_add_table_collection_offer_extension_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrefinancingrequest',
            name='last_retrigger_comms',
            field=models.DateField(blank=True, null=True),
        ),
    ]
