# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-07-21 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_refinancing', '0039_add_last_retrigger_comms'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrefinancingrequest',
            name='form_viewed_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
