# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-08-21 02:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('loan_refinancing', '0040_add_form_viewed_ts'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRefinancingRequestCampaign',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column=b'loan_refinancing_request_campaign_id',
                                        primary_key=True, serialize=False)),
                ('loan_id', models.BigIntegerField()),
                ('campaign_name', models.CharField(max_length=254)),
                ('principal_waiver', models.BigIntegerField(null=True)),
                ('interest_waiver', models.BigIntegerField(null=True)),
                ('late_fee_waiver', models.BigIntegerField(null=True)),
                ('offer', models.CharField(max_length=50, null=True)),
                ('expired_at', models.DateField(null=True)),
                ('outstanding_principal', models.BigIntegerField(null=True)),
                ('outstanding_interest', models.BigIntegerField(null=True)),
                ('status', models.CharField(default=b'Failed', max_length=50)),
                ('extra_data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('loan_refinancing_request',
                 models.ForeignKey(db_column=b'loan_refinancing_request_id', null=True,
                                   on_delete=django.db.models.deletion.CASCADE,
                                   to='loan_refinancing.LoanRefinancingRequest')),
            ],
            options={
                'db_table': 'loan_refinancing_request_campaign',
            },
        ),
        migrations.AlterField(
            model_name='collectionoffereligibility',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[
                django.core.validators.RegexValidator(message=b'characters not allowed',
                                                      regex=b'^[ -~]+$'),
                django.core.validators.RegexValidator(
                    message=b'mobile phone has to be 10 to 14 numeric digits',
                    regex=b'^08+?\\d{8,12}$')]),
        ),
    ]
