DANA_JOB = {
    "OTHERS": "Karyawan Swasta",
    "MENGURUS RUMAH TANGA": "Mengurus Rumah Tangga",
    "MAHASISWA PELAJAR": "Pelajar/ Mahasiswa",
    "KARYAWAN BUMN": "Karyawan BUMN",
    "KEPOLISISAN RI": "Kepolisian RI",
    "WIRASWASTA": "Wiraswasta",
    "PETANI": "Petani/ Pekebun",
    "KARYAWAN SWASTA": "Karyawan Swasta",
    "KARYAWAN HONORER": "Karyawan Honorer",
    "BURUH": "Buruh Harian Lepas",
    "PNS": "Pegawai Negeri Sipil",
    "SENIMAN": "Seniman",
    "BELUM / TIDAK BEKERJA": "Belum/ Tidak Bekerja",
    "KONSTRUKSI": "Konstruksi",
    "PELAUT": "Pelaut",
    "NELAYAN / PERIKANAN": "Nelayan/ Perikanan",
    "USTADZ / MUBALIGH": "Ustadz/ Mubaligh",
    "MEKANIK": "Mekanik",
    "GURU": "Guru",
    "KARYAWAN BUMD": "Karyawan BUMD",
    "TUKANG KAYU": "Tukang Kayu",
    "SOPIR": "Sopir",
    "PENATA BUSANA": "Penata Busana",
    "TUKANG JAHIT": "Tukang Jahit",
    "TENTARA NASIONAL INDONESIA": "Tentara Nasional Indonesia",
    "PERANGKAT DESA": "Perangkat Desa",
    "PERAWAT": "Perawat",
    "APOTEKER": "Apoteker",
    "DOSEN": "Dosen",
    "PENSIUANAN": "Pensiunan",
    "INDUSTRI": "Industri",
    "KEPALA DESA": "Kepala Desa",
    "PEKERJAAN LAINNYA": "Karyawan Swasta",
    "TUKANG BATU": "Tukang Batu",
    "TUKANG LAS / PANDAI BESI": "Tukang Las/ Pandai Besi",
    "PENGACARA": "Pengacara",
    "DOKTER": "Dokter",
    "TRANSPORTASI": "Transportasi",
    "ANGGOTA DPRD KAB / KOTA": "Anggota DPRD Kabupaten/ Kota",
    "PARANORMAL": "Paranormal",
    "PSIKIATER / PSIKOLOG": "Psikiater/ Psikolog",
    "TUKANG CUKUR": "Tukang Cukur",
    "GUBERNUR": "Gubernur",
    "BIDAN": "Bidan",
    "TIDAK BEKERJA": "Belum/ Tidak Bekerja",
    "PETERNAK": "Peternak",
    "KONSULTAN": "Konsultan",
    "ARSITEK": "Arsitek",
    "PENYIAR RADIO": "Penyiar Radio",
    "PENDETA": "Pendeta",
    "PENYIAR TELEVISI": "Penyiar Televisi",
    "AKUNTAN": "Akuntan",
    "POLRI": "Kepolisian RI",
    "TUKANG SOL SEPATU": "Tukang Sol Sepatu",
    "PENATA RIAS": "Penata Rias",
    "PILOT": "Pilot",
    "PENATA RAMBUT": "Penata Rambut",
    "IMAM MASJID": "Imam Masjid",
    "PIALANG": "Pialang",
    "TUKANG GIGI": "Tukang Gigi",
    "PENELITI": "Peneliti",
    "KEPOLISIAN RI": "Kepolisian RI",
    "TUKANG LISTRIK": "Tukang Listrik",
    "PROMOTOR ACARA": "Promotor Acara",
}
