DANA_PROVINCE = {
    "BANTEN": "Banten",
    "JAWA BARAT": "Jawa Barat",
    "KEPULAUAN RIAU": "Kepulauan Riau",
    "SUMATRA UTARA": "Sumatera Utara",
    "SULAWESI BARAT": "Sulawesi Barat",
    "NUSA TENGGARA BARAT": "Nusa Tenggara Barat",
    "SUMATRA SELATAN": "Sumatera Selatan",
    "RIAU": "Riau",
    "JAMBI": "Jambi",
    "MALUKU UTARA": "Maluku Utara",
    "SULAWESI UTARA": "Sulawesi Utara",
    "SUMATRA BARAT": "Sumatera Barat",
    "KALIMANTAN BARAT": "Kalimantan Barat",
    "SULAWESI TENGAH": "Sulawesi Tengah",
    "LAMPUNG": "Lampung",
    "MALUKU": "Maluku",
    "BENGKULU": "Bengkulu",
    "IRIAN JAYA BARAT": "Papua Barat",
    "PAPUA": "Papua",
    "KEP. BANGKA BELITUNG": "Kepulauan Bangka Belitung",
    "SULAWESI SELATAN": "Sulawesi Selatan",
    "GORONTALO": "Gorontalo",
    "NUSA TENGGARA TIMUR": "Nusa Tenggara Timur",
    "NANGGROE ACEH DARUSSALAM": "Nusa Tenggara Barat",
    "KALIMANTAN TIMUR": "Kalimantan Timur",
    "SULAWESI TENGGARA": "Sulawesi Tenggara",
    "PAPUA BARAT": "Papua Barat",
    "DKI JAKARTA": "DKI Jakarta",
    "BALI": "Bali",
    "KALIMANTAN SELATAN": "Kalimantan Selatan",
    "JAWA TIMUR": "Jawa Timur",
    "JAWA TENGAH": "Jawa Tengah",
    "D I YOGYAKARTA": "DI Yogyakarta",
    "KALIMANTAN TENGAH": "Kalimantan Tengah",
    "KALIMANTAN UTARA": "Kalimantan Utara",
    "PROVINSI JAWA TIMUR": "Jawa Timur",
    "PROVINSI JAWA BARAT": "Jawa Barat",
}

DANA_CITY = {
    "KAB BURU": "Kab. Buru",
    "KAB. ACEH BARAT": "Kab. Aceh Barat",
    "KAB. ACEH BARAT DAYA": "Kab. Aceh Barat Daya",
    "KAB. ACEH BESAR": "Kab. Aceh Besar",
    "KAB. ACEH JAYA": "Kab. Aceh Jaya",
    "KAB. ACEH JEUMPA/BIREUEN": "Kab. Bireuen",
    "KAB. ACEH SELATAN": "Kab. Aceh Selatan",
    "KAB. ACEH SIMEULEU": "Kab. Simeulue",
    "KAB. ACEH SINGKIL": "Kab. Aceh Singkil",
    "KAB. ACEH TAMIANG": "Kab. Aceh Tamiang",
    "KAB. ACEH TENGAH": "Kab. Aceh Tengah",
    "KAB. ACEH TENGGARA": "Kab. Aceh Tenggara",
    "KAB. ACEH TIMUR": "Kab. Aceh Timur",
    "KAB. ACEH UTARA": "Kab. Aceh Utara",
    "KAB. AGAM": "Kab. Agam",
    "KAB. ALOR": "Kab. Alor",
    "KAB. ASAHAN": "Kab. Asahan",
    "KAB. ASMAT": "Kab. Asmat",
    "KAB. BADUNG": "Kab. Badung",
    "KAB. BADUNG, KUTA, PECATU DLL": "Kab. Badung",
    "KAB. BALANGAN": "Kab. Balangan",
    "KAB. BANDUNG": "Kab. Bandung",
    "KAB. BANGKA": "Kab. Bangka",
    "KAB. BANGKALAN": "Kab. Bangkalan",
    "KAB. BANGLI": "Kab. Bangli",
    "KAB. BANJAR": "Kab. Banjar",
    "KAB. BANJARNEGARA": "Kab. Banjarnegara",
    "KAB. BANTAENG": "Kab. Bantaeng",
    "KAB. BANTUL": "Kab. Bantul",
    "KAB. BANYUMAS": "Kab. Banyumas",
    "KAB. BANYUWANGI": "Kab. Banyuwangi",
    "KAB. BARITO KUALA": "Kab. Barito Kuala",
    "KAB. BARITO SELATAN": "Kab. Barito Selatan",
    "KAB. BARITO TIMUR": "Kab. Barito Timur",
    "KAB. BARITO UTARA": "Kab. Barito Utara",
    "KAB. BARRU": "Kab. Barru",
    "KAB. BATANG": "Kab. Batang",
    "KAB. BATANGHARI": "Kab. Batanghari",
    "KAB. BEKASI": "Kab. Bekasi",
    "KAB. BELITUNG": "Kab. Belitung",
    "KAB. BELU": "Kab. Belu",
    "KAB. BENGKALIS": "Kab. Bengkalis",
    "KAB. BENGKAYANG": "Kab. Bengkayang",
    "KAB. BENGKULU SELATAN": "Kab. Bengkulu Selatan",
    "KAB. BENGKULU UTARA": "Kab. Bengkulu Utara",
    "KAB. BERAU": "Kab. Berau",
    "KAB. BIAK NUMFOR": "Kab. Biak Numfor",
    "KAB. BIMA": "Kab. Bima",
    "KAB. BLITAR": "Kab. Blitar",
    "KAB. BLORA": "Kab. Blora",
    "KAB. BOGOR": "Kab. Bogor",
    "KAB. BOJONEGORO": "Kab. Bojonegoro",
    "KAB. BOLAANG MONGONDOW": "Kab. Bolaang Mongondow",
    "KAB. BONDOWOSO": "Kab. Bondowoso",
    "KAB. BONE": "Kab. Bone",
    "KAB. BONEBOLANGO": "Kab. Bone Bolango",
    "KAB. BOYOLALI": "Kab. Boyolali",
    "KAB. BREBES": "Kab. Brebes",
    "KAB. BUALEMO": "Kab. Boalemo",
    "KAB. BULELENG": "Kab. Buleleng",
    "KAB. BULUKUMBA": "Kab. Bulukumba",
    "KAB. BULUNGAN": "Kab. Bulungan",
    "KAB. BUOL": "Kab. Buol",
    "KAB. BUTON": "Kab. Buton",
    "KAB. CIAMIS": "Kab. Ciamis",
    "KAB. CIANJUR": "Kab. Cianjur",
    "KAB. CILACAP": "Kab. Cilacap",
    "KAB. CIREBON": "Kab. Cirebon",
    "KAB. DAIRI": "Kab. Dairi",
    "KAB. DELI SERDANG": "Kab. Deli Serdang",
    "KAB. DEMAK": "Kab. Demak",
    "KAB. DOMPU": "Kab. Dompu",
    "KAB. DONGGALA": "Kab. Donggala",
    "KAB. ENDE": "Kab. Ende",
    "KAB. ENREKANG": "Kab. Enrekang",
    "KAB. FLORES TIMUR": "Kab. Flores Timur",
    "KAB. GARUT": "Kab. Garut",
    "KAB. GAYO LUWES": "Kab. Gayo Lues",
    "KAB. GIANYAR": "Kab. Gianyar",
    "KAB. GORONTALO": "Kab. Gorontalo",
    "KAB. GOWA": "Kab. Gowa",
    "KAB. GRESIK": "Kab. Gresik",
    "KAB. GROBOGAN": "Kab. Grobogan",
    "KAB. GUNUNG KIDUL": "Kab. Gunung Kidul",
    "KAB. GUNUNG MAS": "Kab. Gunung Mas",
    "KAB. HALMAHERA TENGAH": "Kab. Halmahera Tengah",
    "KAB. HULU SUNGAI SELATAN": "Kab. Hulu Sungai Selatan",
    "KAB. HULU SUNGAI TENGAH": "Kab. Hulu Sungai Tengah",
    "KAB. HULU SUNGAI UTARA": "Kab. Hulu Sungai Utara",
    "KAB. INDRAGIRI HILIR": "Kab. Indragiri Hilir",
    "KAB. INDRAGIRI HULU": "Kab. Indragiri Hulu",
    "KAB. INDRAMAYU": "Kab. Indramayu",
    "KAB. JAYAPURA": "Kab. Jayapura",
    "KAB. JAYAWIJAYA": "Kab. Jayawijaya",
    "KAB. JEMBER": "Kab. Jember",
    "KAB. JEMBRANA": "Kab. Jembrana",
    "KAB. JENEPONTO": "Kab. Jeneponto",
    "KAB. JEPARA": "Kab. Jepara",
    "KAB. JOMBANG": "Kab. Jombang",
    "KAB. KAMPAR": "Kab. Kampar",
    "KAB. KAPUAS": "Kab. Kapuas",
    "KAB. KAPUAS HULU": "Kab. Kapuas Hulu",
    "KAB. KARANGANYAR": "Kab. Karanganyar",
    "KAB. KARANGASEM": "Kab. Karangasem",
    "KAB. KARAWANG": "Kab. Karawang",
    "KAB. KARO": "Kab. Karo",
    "KAB. KATINGAN": "Kab. Katingan",
    "KAB. KEBUMEN": "Kab. Kebumen",
    "KAB. KEDIRI": "Kab. Kediri",
    "KAB. KEEROM": "Kab. Keerom",
    "KAB. KENDAL": "Kab. Kendal",
    "KAB. KEPULAUAN MENTAWAI": "Kab. Kepulauan Mentawai",
    "KAB. KERINCI": "Kab. Kerinci",
    "KAB. KETAPANG": "Kab. Ketapang",
    "KAB. KLATEN": "Kab. Klaten",
    "KAB. KLUNGKUNG": "Kab. Klungkung",
    "KAB. KOLAKA": "Kab. Kolaka",
    "KAB. KOTA BARU": "Kab. Kota Baru",
    "KAB. KOTAWARINGIN BARAT": "Kab. Kotawaringin Barat",
    "KAB. KOTAWARINGIN TIMUR": "Kab. Kotawaringin Timur",
    "KAB. KUANTAN SINGINGI": "Kab. Kuantan Singingi",
    "KAB. KUDUS": "Kab. Kudus",
    "KAB. KULON PROGO": "Kab. Kulon Progo",
    "KAB. KUNINGAN": "Kab. Kuningan",
    "KAB. KUTAI BARAT": "Kab. Kutai Barat",
    "KAB. KUTAI KARTANEGARA": "Kab. Kutai Kartanegara",
    "KAB. KUTAI TIMUR": "Kab. Kutai Timur",
    "KAB. LABUHAN BATU": "Kab. Labuhan Batu",
    "KAB. LABUHANBATU SELATAN": "Kab. Labuhanbatu Selatan",
    "KAB. LAHAT": "Kab. Lahat",
    "KAB. LAMANDAU": "Kab. Lamandau",
    "KAB. LAMONGAN": "Kab. Lamongan",
    "KAB. LAMPUNG BARAT": "Kab. Lampung Barat",
    "KAB. LAMPUNG SELATAN": "Kab. Lampung Selatan",
    "KAB. LAMPUNG TENGAH": "Kab. Lampung Tengah",
    "KAB. LAMPUNG TIMUR": "Kab. Lampung Timur",
    "KAB. LAMPUNG UTARA": "Kab. Lampung Utara",
    "KAB. LANDAK": "Kab. Landak",
    "KAB. LANGKAT": "Kab. Langkat",
    "KAB. LEBAK": "Kab. Lebak",
    "KAB. LEMATANG ILIR OGAN TENGAH (MUARA ENIM)": "Kab. Penukal Abab Lematang Ilir",
    "KAB. LEMBATA": "Kab. Lembata",
    "KAB. LIMAPULUH KOTO": "Kab. Limapuluh Kota",
    "KAB. LOMBOK BARAT": "Kab. Lombok Barat",
    "KAB. LOMBOK TENGAH": "Kab. Lombok Tengah",
    "KAB. LOMBOK TIMUR": "Kab. Lombok Timur",
    "KAB. LUMAJANG": "Kab. Lumajang",
    "KAB. LUWU": "Kab. Luwu",
    "KAB. LUWU SELATAN": "Kab. Buru Selatan",
    "KAB. LUWU UTARA": "Kab. Luwu Utara",
    "KAB. MADIUN": "Kab. Madiun",
    "KAB. MAGELANG": "Kab. Magelang",
    "KAB. MAGETAN": "Kab. Magetan",
    "KAB. MAJALENGKA": "Kab. Majalengka",
    "KAB. MALANG": "Kab. Malang",
    "KAB. MALINAU": "Kab. Malinau",
    "KAB. MALUKU TENGAH": "Kab. Maluku Tengah",
    "KAB. MALUKU TENGGARA": "Kab. Maluku Tenggara",
    "KAB. MALUKU TENGGARA BARAT": "Kab. Maluku Tenggara Barat",
    "KAB. MANDAILING NATAL": "Kab. Mandailing Natal",
    "KAB. MANGGARAI": "Kab. Manggarai",
    "KAB. MAPPI": "Kab. Mappi",
    "KAB. MAROS": "Kab. Maros",
    "KAB. MERANGIN": "Kab. Merangin",
    "KAB. MERAUKE": "Kab. Merauke",
    "KAB. MIMIKA": "Kab. Mimika",
    "KAB. MINAHASA": "Kab. Minahasa",
    "KAB. MINAHASA SELATAN": "Kab. Minahasa Selatan",
    "KAB. MOJOKERTO": "Kab. Mojokerto",
    "KAB. MOROWALI": "Kab. Morowali",
    "KAB. MUARO JAMBI": "Kab. Muaro Jambi",
    "KAB. MUNA": "Kab. Muna",
    "KAB. MURUNG RAYA": "Kab. Murung Raya",
    "KAB. MUSI BANYUASIN": "Kab. Musi Banyuasin",
    "KAB. MUSI RAWAS": "Kab. Musi Rawas",
    "KAB. NABIRE": "Kab. Nabire",
    "KAB. NAGAN RAYA": "Kab. Nagan Raya",
    "KAB. NATUNA": "Kab. Natuna",
    "KAB. NGADA": "Kab. Ngada",
    "KAB. NGANJUK": "Kab. Nganjuk",
    "KAB. NGAWI": "Kab. Ngawi",
    "KAB. NIAS": "Kab. Nias",
    "KAB. NIAS SELATAN": "Kab. Nias Selatan",
    "KAB. NUNUKAN": "Kab. Nunukan",
    "KAB. O.K.U  SELATAN": "Kab. Buru Selatan",
    "KAB. OGAN KOMERING ILIR": "Kab. Ogan Komering Ilir",
    "KAB. OGAN KOMERING ULU": "Kab. Ogan Komering Ulu",
    "KAB. PACITAN": "Kab. Pacitan",
    "KAB. PADANG PARIAMAN": "Kab. Padang Pariaman",
    "KAB. PAMEKASAN": "Kab. Pamekasan",
    "KAB. PANDEGLANG": "Kab. Pandeglang",
    "KAB. PARIMO/BANGGAI": "Kab. Banggai",
    "KAB. PASAMAN": "Kab. Pasaman",
    "KAB. PASIR": "Kab. Paser",
    "KAB. PASURUAN": "Kab. Pasuruan",
    "KAB. PATI": "Kab. Pati",
    "KAB. PEKALONGAN": "Kab. Pekalongan",
    "KAB. PELALAWAN": "Kab. Pelalawan",
    "KAB. PEMALANG": "Kab. Pemalang",
    "KAB. PENAJAM PASER UTARA": "Kab. Penajam Paser Utara",
    "KAB. PESISIR SELATAN": "Kab. Pesisir Selatan",
    "KAB. PIDIE": "Kab. Pidie",
    "KAB. PINRANG": "Kab. Pinrang",
    "KAB. POHUWATO": "Kab. Pohuwato",
    "KAB. PONOROGO": "Kab. Ponorogo",
    "KAB. PONTIANAK": "Pontianak",
    "KAB. POSO": "Kab. Poso",
    "KAB. PROBOLINGGO": "Kab. Probolinggo",
    "KAB. PULANG PISAU": "Kab. Pulang Pisau",
    "KAB. PUNCAK JAYA": "Kab. Puncak Jaya",
    "KAB. PURBALINGGA": "Kab. Purbalingga",
    "KAB. PURWAKARTA": "Kab. Purwakarta",
    "KAB. PURWOREJO": "Kab. Purworejo",
    "KAB. REJANG LEBONG": "Kab. Rejang Lebong",
    "KAB. REMBANG": "Kab. Rembang",
    "KAB. ROKAN HILIR": "Kab. Rokan Hilir",
    "KAB. ROKAN HULU": "Kab. Rokan Hulu",
    "KAB. ROTE": "Kab. Rote Ndao",
    "KAB. SAMBAS": "Kab. Sambas",
    "KAB. SAMPANG": "Kab. Sampang",
    "KAB. SANGGAU": "Kab. Sanggau",
    "KAB. SANGIHE": "Kab. Sampang",
    "KAB. SARMI": "Kab. Sarmi",
    "KAB. SAROLANGUN": "Kab. Sarolangun",
    "KAB. SAWAHLUNTO/SIJUNJUNG": "Kab. Sijunjung",
    "KAB. SELAYAR": "Kab. Kepulauan Selayar",
    "KAB. SEMARANG": "Kab. Semarang",
    "KAB. SERANG": "Kab. Serang",
    "KAB. SERUYAN": "Kab. Seruyan",
    "KAB. SIAK": "Kab. Siak",
    "KAB. SIDENRENG RAPPANG": "Kab. Sidenreng Rappang",
    "KAB. SIDOARJO": "Kab. Sidoarjo",
    "KAB. SIKKA": "Kab. Sikka",
    "KAB. SIMALUNGUN": "Kab. Simalungun",
    "KAB. SINJAI": "Kab. Sinjai",
    "KAB. SINTANG": "Kab. Sintang",
    "KAB. SITUBONDO": "Kab. Situbondo",
    "KAB. SLEMAN": "Kab. Sleman",
    "KAB. SOLOK": "Kab. Solok",
    "KAB. SRAGEN": "Kab. Sragen",
    "KAB. SUBANG": "Kab. Subang",
    "KAB. SUKABUMI": "Kab. Sukabumi",
    "KAB. SUKAMARA": "Kab. Sukamara",
    "KAB. SUKOHARJO": "Kab. Sukoharjo",
    "KAB. SUMBA BARAT": "Kab. Sumba Barat",
    "KAB. SUMBA TIMUR": "Kab. Sumba Timur",
    "KAB. SUMBAWA": "Kab. Sumbawa",
    "KAB. SUMEDANG": "Kab. Sumedang",
    "KAB. SUMENEP": "Kab. Sumenep",
    "KAB. TABALONG": "Kab. Tabalong",
    "KAB. TABANAN": "Kab. Tabanan",
    "KAB. TAKALAR": "Kab. Takalar",
    "KAB. TANA TORAJA": "Kab. Tana Toraja",
    "KAB. TANAH DATAR": "Kab. Tanah Datar",
    "KAB. TANAH LAUT": "Kab. Tanah Laut",
    "KAB. TANGERANG": "Kab. Tangerang",
    "KAB. TANGGAMUS": "Kab. Tanggamus",
    "KAB. TANJUNG JABUNG BARAT": "Kab. Tanjung Jabung Barat",
    "KAB. TANJUNG JABUNG TIMUR": "Kab. Tanjung Jabung Timur",
    "KAB. TAPANULI SELATAN": "Kab. Tapanuli Selatan",
    "KAB. TAPANULI TENGAH": "Kab. Tapanuli Tengah",
    "KAB. TAPANULI UTARA": "Kab. Tapanuli Utara",
    "KAB. TAPIN": "Kab. Tapin",
    "KAB. TASIKMALAYA": "Kab. Tasikmalaya",
    "KAB. TEBO": "Kab. Tebo",
    "KAB. TEGAL": "Kab. Tegal",
    "KAB. TEMANGGUNG": "Kab. Temanggung",
    "KAB. TIMORTENGAH UTARA": "Kab. Timor Tengah Utara",
    "KAB. TOBA SAMOSIR": "Kab. Toba Samosir",
    "KAB. TOLITOLI": "Kab. Toli-Toli",
    "KAB. TRENGGALEK": "Kab. Trenggalek",
    "KAB. TUBAN": "Kab. Tuban",
    "KAB. TULANG BAWANG": "Kab. Tulang Bawang",
    "KAB. TULUNGAGUNG": "Kab. Tulungagung",
    "KAB. WAJO": "Kab. Wajo",
    "KAB. WATANSOPPENG": "Kab. Soppeng",
    "KAB. WAY KANAN": "Kab. Way Kanan",
    "KAB. WONOGIRI": "Kab. Wonogiri",
    "KAB. WONOSOBO": "Kab. Wonosobo",
    "KAB. YAHUKIMO": "Kab. Yahukimo",
    "KAB./KOTA LAINNYA": "Kab. Lanny Jaya",
    "KAB.BANGGAI KEPULAUAN": "Kab. Banggai Kepulauan",
    "KAB.TANAH BUMBU": "Kab. Tanah Bumbu",
    "KAB/KOTA LAINNYA": "Kab. Lanny Jaya",
    "KOTA AMBON": "Kota Ambon",
    "KOTA BALIKPAPAN": "Kota Balikpapan",
    "KOTA BANDA ACEH": "Kota Banda Aceh",
    "KOTA BANDAR LAMPUNG": "Kota Bandar Lampung",
    "KOTA BANDUNG": "Kota Bandung",
    "KOTA BANJAR": "Kota Banjar",
    "KOTA BANJARBARU": "Kota Banjarbaru",
    "KOTA BANJARMASIN": "Kota Banjarmasin",
    "KOTA BATAM": "Kota Batam",
    "KOTA BATU": "Kota Batu",
    "KOTA BAUBAU": "Kota Baubau",
    "KOTA BEKASI": "Kota Bekasi",
    "KOTA BENGKULU": "Kota Bengkulu",
    "KOTA BINJAI": "Kota Binjai",
    "KOTA BITUNG": "Kota Bitung",
    "KOTA BLITAR": "Kota Blitar",
    "KOTA BOGOR": "Kota Bogor",
    "KOTA BONTANG": "Kota Bontang",
    "KOTA BUKITTINGGI": "Kota Bukittinggi",
    "KOTA CILEGON": "Kota Cilegon",
    "KOTA CIMAHI": "Kota Cimahi",
    "KOTA CIREBON": "Kota Cirebon",
    "KOTA DENPASAR": "Kota Denpasar",
    "KOTA DEPOK": "Kota Depok",
    "KOTA DUMAI": "Kota Dumai",
    "KOTA GORONTALO": "Kota Gorontalo",
    "KOTA JAKARTA SELATAN": "Kota Jakarta Selatan",
    "KOTA JAKARTA TIMUR": "Kota Jakarta Timur",
    "KOTA JAMBI": "Kota Jambi",
    "KOTA JAYAPURA": "Kota Jayapura",
    "KOTA KEDIRI": "Kota Kediri",
    "KOTA KENDARI": "Kota Kendari",
    "KOTA KUPANG": "Kota Kupang",
    "KOTA LANGSA": "Kota Langsa",
    "KOTA LHOKSEUMAWE": "Kota Lhokseumawe",
    "KOTA LUBUKLINGGAU": "Kota Lubuklinggau",
    "KOTA MADIUN": "Kota Madiun",
    "KOTA MAGELANG": "Kota Magelang",
    "KOTA MAKASSAR": "Kota Makassar",
    "KOTA MALANG": "Kota Malang",
    "KOTA MATARAM": "Kota Mataram",
    "KOTA MEDAN": "Kota Medan",
    "KOTA MENADO": "Kota Manado",
    "KOTA METRO": "Kota Metro",
    "KOTA MOJOKERTO": "Kota Mojokerto",
    "KOTA PADANG": "Kota Padang",
    "KOTA PADANG PANJANG": "Kota Padang Panjang",
    "KOTA PADANG SIDEMPUAN": "Kota Padang Sidempuan",
    "KOTA PAGAR ALAM": "Kota Pagar Alam",
    "KOTA PALANGKARAYA": "Kota Palangkaraya",
    "KOTA PALEMBANG": "Kota Palembang",
    "KOTA PALOPO": "Kota Palopo",
    "KOTA PALU": "Kota Palu",
    "KOTA PANGKAL PINANG": "Kota Pangkal Pinang",
    "KOTA PAREPARE": "Kota Parepare",
    "KOTA PARIAMAN": "Kota Pariaman",
    "KOTA PASURUAN": "Kota Pasuruan",
    "KOTA PAYAKUMBUH": "Kota Payakumbuh",
    "KOTA PEKALONGAN": "Kota Pekalongan",
    "KOTA PEKANBARU": "Kota Pekanbaru",
    "KOTA PEMATANG SIANTAR": "Kota Pematang Siantar",
    "KOTA PONTIANAK": "Kota Pontianak",
    "KOTA PRABUMULIH": "Kota Prabumulih",
    "KOTA PROBOLINGGO": "Kota Probolinggo",
    "KOTA SABANG": "Kota Sabang",
    "KOTA SALATIGA": "Kota Salatiga",
    "KOTA SAMARINDA": "Kota Samarinda",
    "KOTA SAWAHLUNTO": "Kota Sawahlunto",
    "KOTA SEMARANG": "Kota Semarang",
    "KOTA SIBOLGA": "Kota Sibolga",
    "KOTA SINGKAWANG": "Kota Singkawang",
    "KOTA SOLOK": "Kota Solok",
    "KOTA SORONG": "Kota Sorong",
    "KOTA SUKABUMI": "Kota Sukabumi",
    "KOTA SURABAYA": "Kota Surabaya",
    "KOTA SURAKARTA": "Kota Surakarta",
    "KOTA TANGERANG": "Kota Tangerang",
    "KOTA TANGERANG SELATAN": "Kota Tangerang Selatan",
    "KOTA TANJUNG BALAI": "Kota Tanjung Balai",
    "KOTA TARAKAN": "Kota Tarakan",
    "KOTA TASIKMALAYA": "Kota Tasikmalaya",
    "KOTA TEBING TINGGI": "Kota Tebing Tinggi",
    "KOTA TEGAL": "Kota Tegal",
    "KOTA TERNATE": "Kota Ternate",
    "KOTA YOGYAKARTA": "Kota Yogyakarta",
    "KOTA. TOMOHON": "Kota Tomohon",
    "KOTIF KLATEN": "Klaten",
    "WIL. KOTA JAKARTA BARAT": "Kota Jakarta Barat",
    "WIL. KOTA JAKARTA PUSAT": "Kota Jakarta Pusat",
    "WIL. KOTA JAKARTA SELATAN": "Kota Jakarta Selatan",
    "WIL. KOTA JAKARTA TIMUR": "Kota Jakarta Timur",
    "WIL. KOTA JAKARTA UTARA": "Kota Jakarta Utara",
}
