from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^list$', views.LenderProductListView.as_view(),
        name='list'),
    url(r'^add/$', views.add,
        name='add'),
    url(r'^registration$', views.LenderRegistrationView.as_view(),
        name='registration'),
    url(r'^verification/(?P<pk>\d+)$', views.verification,
        name='verification'),
    url(r'^reject/(?P<pk>\d+)$', views.reject,
        name='reject'),
    url(r'^details/(?P<pk>\d+)$', views.details,
        name='details'),
    url(r'^lender_details/(?P<pk>\d+)$', views.lender_details,
        name='lender_details'),
    url(r'^ajax_get_detail/', views.ajax_get_detail,
        name='ajax_get_detail'),
    url(r'^ajax_update_detail/', views.ajax_update_detail,
        name='ajax_update_detail'),
    url(r'^ajax_add_lender_account/', views.ajax_add_lender_account,
        name='ajax_add_lender_account'),
    url(r'^ajax_add_lender_product/', views.ajax_add_lender_product,
        name='ajax_add_lender_product'),
    url(r'^ajax_submit_verification/', views.ajax_submit_verification,
        name='ajax_submit_verification'),
    url(r'^ajax_get_lender/', views.ajax_get_lender,
        name='ajax_get_lender'),
    url(r'^withdrawal_list/', views.LenderWithdrawalListView.as_view(),
        name='withdrawal_list'),
    url(r'^reversal_payment_list', views.LenderReversalPaymentListView.as_view(),
        name='reversal_payment_list'),
    url(r'^ajax_submit_update_transaction/', views.ajax_submit_update_transaction,
        name='ajax_submit_update_transaction'),
    url(r'^ajax_confirm_transaction/', views.ajax_confirm_transaction,
        name='ajax_confirm_transaction'),
    url(r'^repayment_list/(?P<redis_key>\w+)', views.repayment_list,
        name='repayment_list'),
    url(r'^ajax_update_repayment/', views.ajax_update_repayment,
        name='ajax_update_repayment'),
    url(r'^reserve_for_manual_transfer/', views.reserve_for_manual_transfer,
        name='reserve_for_manual_transfer'),
    url(r'^callbacks/xfers-rdl-top-up$', views.XfersRdlTopUpView.as_view(),
        name='xfers_rdl_top_up_callback'),

    # repayment upload statement
    url(r'^repayment_upload/', views.LenderRepaymentUploadView.as_view(),
        name='repayment_upload'),
    url(r'^ajax_repayment_upload/', views.ajax_repayment_upload,
        name='ajax_repayment_upload'),
    url(r'^investment$', views.lender_investment_upload_view,
        name='investment'),
]
