# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-04-30 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv2', '0007_pdincomepredictmodelresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdExpensePredictModelResult',
            fields=[
                (
                    'id',
                    models.BigIntegerField(
                        db_column='pd_expense_predict_model_result_id',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('application_id', models.BigIntegerField(db_index=True)),
                ('customer_id', models.BigIntegerField(db_index=True)),
                ('version', models.PositiveIntegerField()),
                ('value', models.FloatField()),
            ],
            options={
                'db_table': '"ana"."pd_expense_predict_model_result"',
                'managed': False,
            },
        ),
    ]
