from builtins import object

PUSDAFIL_ORGANIZER_ID = "810069"

cities = {
    'TANGERANG': 'e311',
    'BEKASI': 'e282',
    'JAKARTA TIMUR': 'e320',
    'JAKARTA SELATAN': 'e319',
    'JAKARTA BARAT': 'e318',
    'BOGOR': 'e300',
    'DEPOK': 'e305',
    'JAKARTA UTARA': 'e317',
    'BANDUNG': 'e299',
    'JAKARTA PUSAT': 'e316',
    'TANGERANG SELATAN': 'e311',
    'DKI JAKARTA': 'e316',
    'SURABAYA': 'e391',
    'JAWA BARAT': 'e282',
    'SIDOARJO': 'e363',
    'SEMARANG': 'e327',
    'KARAWANG': 'e284',
    'MALANG': 'e373',
    'BANTEN': 'e313',
    'PALEMBANG': 'e515',
    'SUKABUMI': 'e286',
    'SERANG': 'e310',
    'MEDAN': 'e471',
    'BANDUNG BARAT': 'e298',
    'CIREBON': 'e293',
    'BATAM': 'e532',
    'MAKASSAR': 'e634',
    'CIMAHI': 'e304',
    'BANDAR LAMPUNG': 'e545',
    'SLEMAN': 'e323',
    'BADUNG': 'e688',
    'DELI SERDANG': 'e443',
    'PEKANBARU': 'e502',
    'CIANJUR': 'e287',
    'DENPASAR': 'e693',
    'GARUT': 'e291',
    'SUBANG': 'e297',
    'TASIKMALAYA': 'e303',
    'MANADO': 'e648',
    'PURWAKATA': 'e283',
    'GRESIK': 'e362',
    'SAMARINDA': 'e584',
    'BALIKPAPAN': 'e585',
    'SUMEDANG': 'e289',
    'PADANG': 'e486',
    'ELSE': 'e999',
    'KAB. BEKASI': 'e282',
    'KAB. PURWAKARTA': 'e283',
    'KAB. KARAWANG': 'e284',
    'KAB. BOGOR': 'e285',
    'KAB. SUKABUMI': 'e286',
    'KAB. CIANJUR': 'e287',
    'KAB. BANDUNG': 'e288',
    'KAB. SUMEDANG': 'e289',
    'KAB. TASIKMALAYA': 'e290',
    'KAB. GARUT': 'e291',
    'KAB. CIAMIS': 'e292',
    'KAB. CIREBON': 'e293',
    'KAB. KUNINGAN': 'e294',
    'KAB. INDRAMAYU': 'e295',
    'KAB. MAJALENGKA': 'e296',
    'KAB. SUBANG': 'e297',
    'KAB. BANDUNG BARAT': 'e298',
    'KOTA BANDUNG': 'e299',
    'KOTA BOGOR': 'e300',
    'KOTA SUKABUMI': 'e301',
    'KOTA CIREBON': 'e302',
    'KOTA TASIKMALAYA': 'e303',
    'KOTA CIMAHI': 'e304',
    'KOTA DEPOK': 'e305',
    'KOTA BEKASI': 'e306',
    'KOTA BANJAR': 'e307',
    'KAB. PANGANDARAN': 'e776',
    'KAB. LEBAK': 'e308',
    'KAB. PANDEGLANG': 'e309',
    'KAB. SERANG': 'e310',
    'KAB. TANGERANG': 'e311',
    'KOTA CILEGON': 'e312',
    'KOTA TANGERANG': 'e313',
    'KOTA SERANG': 'e314',
    'KOTA TANGERANG SELATAN': 'e315',
    'KOTA JAKARTA PUSAT': 'e316',
    'KOTA JAKARTA UTARA': 'e317',
    'KOTA JAKARTA BARAT': 'e318',
    'KOTA JAKARTA SELATAN': 'e319',
    'KOTA JAKARTA TIMUR': 'e320',
    'KAB. KEPULAUAN SERIBU': 'e321',
    'KAB. BANTUL': 'e322',
    'KAB. SLEMAN': 'e323',
    'KAB. GUNUNG KIDUL': 'e324',
    'KAB. KULON PROGO': 'e325',
    'KOTA YOGYAKARTA': 'e326',
    'KAB. SEMARANG': 'e327',
    'KAB. KENDAL': 'e328',
    'KAB. DEMAK': 'e329',
    'KAB. GROBOGAN': 'e330',
    'KAB. PEKALONGAN': 'e331',
    'KAB. TEGAL': 'e332',
    'KAB. BREBES': 'e333',
    'KAB. PATI': 'e334',
    'KAB. KUDUS': 'e335',
    'KAB. PEMALANG': 'e336',
    'KAB. JEPARA': 'e337',
    'KAB. REMBANG': 'e338',
    'KAB. BLORA': 'e339',
    'KAB. BANYUMAS': 'e340',
    'KAB. CILACAP': 'e341',
    'KAB. PURBALINGGA': 'e342',
    'KAB. BANJARNEGARA': 'e343',
    'KAB. MAGELANG': 'e344',
    'KAB. TEMANGGUNG': 'e345',
    'KAB. WONOSOBO': 'e346',
    'KAB. PURWOREJO': 'e347',
    'KAB. KEBUMEN': 'e348',
    'KAB. KLATEN': 'e349',
    'KAB. BOYOLALI': 'e350',
    'KAB. SRAGEN': 'e351',
    'KAB. SUKOHARJO': 'e352',
    'KAB. KARANGANYAR': 'e353',
    'KAB. WONOGIRI': 'e354',
    'KAB. BATANG': 'e355',
    'KOTA SEMARANG': 'e356',
    'KOTA SALATIGA': 'e357',
    'KOTA PEKALONGAN': 'e358',
    'KOTA TEGAL': 'e359',
    'KOTA MAGELANG': 'e360',
    'KOTA SURAKARTA': 'e361',
    'KAB. GRESIK': 'e362',
    'KAB. SIDOARJO': 'e363',
    'KAB. MOJOKERTO': 'e364',
    'KAB. JOMBANG': 'e365',
    'KAB. SAMPANG': 'e366',
    'KAB. PAMEKASAN': 'e367',
    'KAB. SUMENEP': 'e368',
    'KAB. BANGKALAN': 'e369',
    'KAB. BONDOWOSO': 'e370',
    'KAB. BANYUWANGI': 'e371',
    'KAB. JEMBER': 'e372',
    'KAB. MALANG': 'e373',
    'KAB. PASURUAN': 'e374',
    'KAB. PROBOLINGGO': 'e375',
    'KAB. LUMAJANG': 'e376',
    'KAB. KEDIRI': 'e377',
    'KAB. NGANJUK': 'e378',
    'KAB. TULUNGAGUNG': 'e379',
    'KAB. TRENGGALEK': 'e380',
    'KAB. BLITAR': 'e381',
    'KAB. MADIUN': 'e382',
    'KAB. NGAWI': 'e383',
    'KAB. MAGETAN': 'e384',
    'KAB. PONOROGO': 'e385',
    'KAB. PACITAN': 'e386',
    'KAB. BOJONEGORO': 'e387',
    'KAB. TUBAN': 'e388',
    'KAB. LAMONGAN': 'e389',
    'KAB. SITUBONDO': 'e390',
    'KOTA SURABAYA': 'e391',
    'KOTA MOJOKERTO': 'e392',
    'KOTA MALANG': 'e393',
    'KOTA PASURUAN': 'e394',
    'KOTA PROBOLINGGO': 'e395',
    'KOTA BLITAR': 'e396',
    'KOTA KEDIRI': 'e397',
    'KOTA MADIUN': 'e398',
    'KOTA BATU': 'e399',
    'KAB. BENGKULU SELATAN': 'e400',
    'KAB. BENGKULU UTARA': 'e401',
    'KAB. REJANG LEBONG': 'e402',
    'KAB. LEBONG': 'e403',
    'KAB. KEPAHIANG': 'e404',
    'KAB. MUKO-MUKO': 'e405',
    'KAB. SELUMA': 'e406',
    'KAB. KAUR': 'e407',
    'KAB. BENGKULU TENGAH': 'e408',
    'KOTA BENGKULU': 'e409',
    'KAB. BATANG HARI': 'e410',
    'KAB. SOROLANGUN': 'e411',
    'KAB. KERINCI': 'e412',
    'KAB. MUARO JAMBI': 'e413',
    'KAB. TANJUNG JABUNG BARAT': 'e414',
    'KAB. TANJUNG JABUNG TIMUR': 'e415',
    'KAB. TEBO': 'e416',
    'KAB. MERANGIN': 'e417',
    'KAB. BUNGO': 'e418',
    'KOTA JAMBI': 'e419',
    'KOTA SUNGAI PENUH': 'e777',
    'KAB. ACEH BESAR': 'e420',
    'KAB. PIDIE': 'e421',
    'KAB. ACEH UTARA': 'e422',
    'KAB. ACEH TIMUR': 'e423',
    'KAB. ACEH SELATAN': 'e424',
    'KAB. ACEH BARAT': 'e425',
    'KAB. ACEH TENGAH': 'e426',
    'KAB. ACEH TENGGARA': 'e427',
    'KAB. ACEH SINGKIL': 'e428',
    'KAB. ACEH TAMIANG': 'e430',
    'KAB. GAYO LUES': 'e431',
    'KAB. ACEH BARAT DAYA': 'e432',
    'KAB. ACEH JAYA': 'e433',
    'KAB. NAGAN RAYA': 'e434',
    'KAB. SIMEULUE': 'e435',
    'KAB. BENER MERIAH': 'e436',
    'KAB. PIDIE JAYA': 'e437',
    'KOTA SUBULUSSALAM': 'e438',
    'KOTA BANDA ACEH': 'e439',
    'KOTA SABANG': 'e440',
    'KOTA LHOKSEUMAWE': 'e441',
    'KOTA LANGSA': 'e442',
    'KAB. BIREUEN': 'e778',
    'KAB. DELI SERDANG': 'e443',
    'KAB. LANGKAT': 'e444',
    'KAB. KARO': 'e445',
    'KAB. SIMALUNGUN': 'e446',
    'KAB. LABUHAN BATU': 'e447',
    'KAB. ASAHAN': 'e448',
    'KAB. DAIRI': 'e449',
    'KAB. TAPANULI UTARA': 'e450',
    'KAB. TAPANULI TENGAH': 'e451',
    'KAB. TAPANULI SELATAN': 'e452',
    'KAB. NIAS': 'e453',
    'KAB. TOBA SAMOSIR': 'e454',
    'KAB. MANDAILING NATAL': 'e455',
    'KAB. NIAS SELATAN': 'e456',
    'KAB. HUMBANG HASUNDUTAN': 'e457',
    'KAB. PAKPAK BHARAT': 'e458',
    'KAB. SAMOSIR': 'e459',
    'KAB. SERDANG BADAGAI': 'e460',
    'KAB. BATUBARA': 'e461',
    'KAB. PADANG LAWAS': 'e462',
    'KAB. PADANG LAWAS UTARA': 'e463',
    'KAB. LABUHANBATU SELATAN': 'e464',
    'KAB. LABUHANBATU UTARA': 'e465',
    'KOTA TEBING TINGGI': 'e466',
    'KOTA BINJAI': 'e467',
    'KOTA PEMATANG SIANTAR': 'e468',
    'KOTA TANJUNG BALAI': 'e469',
    'KOTA SIBOLGA': 'e470',
    'KOTA MEDAN': 'e471',
    'KOTA PADANG SIDEMPUAN': 'e472',
    'KOTA GUNUNG SITOLI': 'e779',
    'KAB. NIAS BARAT': 'e780',
    'KAB. NIAS UTARA': 'e782',
    'KAB. AGAM': 'e473',
    'KAB. PASAMAN': 'e474',
    'KAB. LIMA PULUH KOTA': 'e475',
    'KAB. SOLOK SELATAN': 'e476',
    'KAB. PADANG PARIAMAN': 'e477',
    'KAB. PESISIR SELATAN': 'e478',
    'KAB. TANAH DATAR': 'e479',
    'KAB. SIJUNJUNG': 'e480',
    'KAB. KEPULAUAN MENTAWAI': 'e481',
    'KAB. PASAMAN BARAT': 'e482',
    'KAB. DHARMASRAYA': 'e483',
    'KAB. SOLOK': 'e484',
    'KOTA BUKIT TINGGI': 'e485',
    'KOTA PADANG': 'e486',
    'KOTA SAWAH LUNTO': 'e487',
    'KOTA PADANG PANJANG': 'e488',
    'KOTA SOLOK': 'e489',
    'KOTA PAYAHKUMBUH': 'e490',
    'KOTA PARIAMAN': 'e491',
    'KAB. KAMPAR': 'e492',
    'KAB. BENGKALIS': 'e493',
    'KAB. INDRAGIRI HULU': 'e494',
    'KAB. INDRAGIRI HILIR': 'e495',
    'KAB. ROKAN HULU': 'e496',
    'KAB. ROKAN HILIR': 'e497',
    'KAB. PELALAWAN': 'e498',
    'KAB. SIAK': 'e499',
    'KAB. KUANTAN SENGINGI': 'e500',
    'KAB. KEPULAUAN MERANTI': 'e501',
    'KOTA PEKAN BARU': 'e502',
    'KOTA DUMAI': 'e503',
    'KAB. MUSI BANYUASIN': 'e504',
    'KAB. OGAN KOMERING ULU': 'e505',
    'KAB. MUARA ENIM': 'e506',
    'KAB. LAHAT': 'e507',
    'KAB. MUSI RAWAS': 'e508',
    'KAB. OGAN KOMERING ILIR': 'e509',
    'KAB. BANYUASIN': 'e510',
    'KAB. OGAN KOMERING ULU SELATAN': 'e511',
    'KAB. OGAN KOMERING ULU TIMUR': 'e512',
    'KAB. OGAN ILIR': 'e513',
    'KAB. EMPAT LAWANG': 'e514',
    'KOTA PALEMBANG': 'e515',
    'KOTA LUBUK LINGGAU': 'e516',
    'KOTA PRABUMULIH': 'e517',
    'KOTA PAGAR ALAM': 'e518',
    'KAB. PENUKAL ABAB LEMATANG ILIR': 'e783',
    'KAB. BANGKA': 'e519',
    'KAB. BELITUNG': 'e520',
    'KAB. BANGKA BARAT': 'e521',
    'KAB. BANGKA SELATAN': 'e522',
    'KAB. BANGKA TENGAH': 'e523',
    'KAB. BELITUNG TIMUR': 'e524',
    'KOTA PANGKAL PINANG': 'e525',
    'KAB. KARIMUN': 'e526',
    'KAB. LINGGA': 'e527',
    'KAB. NATUNA': 'e528',
    'KAB. BINTAN': 'e529',
    'KAB. KEPULAUAN ANAMBAS': 'e530',
    'KOTA TANJUNG PINANG': 'e531',
    'KOTA BATAM': 'e532',
    'KAB. LAMPUNG SELATAN': 'e533',
    'KAB. LAMPUNG TENGAH': 'e534',
    'KAB. LAMPUNG UTARA': 'e535',
    'KAB. LAMPUNG BARAT': 'e536',
    'KAB. TULANG BAWANG': 'e537',
    'KAB. TENGGAMUS': 'e538',
    'KAB. LAMPUNG TIMUR': 'e539',
    'KAB. WAY KANAN': 'e540',
    'KAB. PESAWARAN': 'e541',
    'KAB. PRINGSEWU': 'e542',
    'KAB. TULANG BAWANG BARAT': 'e543',
    'KAB. MESUJI': 'e544',
    'KOTA BANDAR LAMPUNG': 'e545',
    'KOTA METRO': 'e546',
    'KAB. PESISIR BARAT': 'e784',
    'KAB. BANJAR': 'e547',
    'KAB. TANAH LAUT': 'e548',
    'KAB. TAPIN': 'e549',
    'KAB. HULU SUNGAI SELATAN': 'e550',
    'KAB. HULU SUNGAI TENGAH': 'e551',
    'KAB. HULU SUNGAI UTARA': 'e552',
    'KAB. BARITO KUALA': 'e553',
    'KAB. KOTABARU': 'e554',
    'KAB. TABALONG': 'e555',
    'KAB. TANAH BUMBU': 'e556',
    'KAB. BALANGAN': 'e557',
    'KOTA BANJARMASIN': 'e558',
    'KOTA BANJARBARU': 'e559',
    'KAB. PONTIANAK': 'e560',
    'KAB. SAMBAS': 'e561',
    'KAB. KETAPANG': 'e562',
    'KAB. SANGAU': 'e563',
    'KAB. SINTANG': 'e564',
    'KAB. KAPUAS HULU': 'e565',
    'KAB. BENGKAYANG': 'e566',
    'KAB. LANDAK': 'e567',
    'KAB. SEKADAU': 'e568',
    'KAB. MELAWI': 'e569',
    'KAB. KAYONG UTARA': 'e570',
    'KAB. KUBU RAYA': 'e571',
    'KOTA PONTIANAK': 'e572',
    'KOTA SINGKAWANG': 'e573',
    'KAB. KUTAI KARTANEGARA': 'e574',
    'KAB. BERAU': 'e575',
    'KAB. PASER': 'e576',
    'KAB. KUTAI BARAT': 'e578',
    'KAB. KUTAI TIMUR': 'e579',
    'KAB. PENAJAM PASER UTAMA': 'e582',
    'KOTA SAMARINDA': 'e584',
    'KOTA BALIKPAPAN': 'e585',
    'KOTA BONTANG': 'e587',
    'KAB. MAHAKAM ULU': 'e785',
    'KAB. KAPUAS': 'e588',
    'KAB. KOTAWARINGIN BARAT': 'e589',
    'KAB. KOTAWARINGIN TIMUR': 'e590',
    'KAB. BARITO SELATAN': 'e591',
    'KAB. BARITO UTARA': 'e592',
    'KAB. MURUNG RAYA': 'e593',
    'KAB. BARITO TIMUR': 'e594',
    'KAB. GUNUNG MAS': 'e595',
    'KAB. PULANG PISAU': 'e596',
    'KAB. SERUYAN': 'e597',
    'KAB. KATINGAN': 'e598',
    'KAB. SUKAMARA': 'e599',
    'KAB. LAMANDAU': 'e600',
    'KOTA PALANGKA RAYA': 'e601',
    'KAB. DONGGALA': 'e602',
    'KAB. POSO': 'e603',
    'KAB. BANGGAI': 'e604',
    'KAB. TOLI-TOLI': 'e605',
    'KAB. BANGGAI KEPULAUAN': 'e606',
    'KAB. MOROWALI': 'e607',
    'KAB. BUOL': 'e608',
    'KAB. TOJO UNA-UNA': 'e609',
    'KAB. PARIGI MOUTONG': 'e610',
    'KAB. SIGI': 'e611',
    'KOTA PALU': 'e612',
    'KAB. BANGGAI LAUT': 'e786',
    'MOROWALI UTARA': 'e787',
    'KAB. PINRANG': 'e613',
    'KAB. GOWA': 'e614',
    'KAB. WAJO': 'e615',
    'KAB. BONE': 'e616',
    'KAB. TANA TORAJAH': 'e617',
    'KAB. MAROS': 'e618',
    'KAB. LUWU': 'e619',
    'KAB. SINJAI': 'e620',
    'KAB. BULUKUMBA': 'e621',
    'KAB. BANTAENG': 'e622',
    'KAB. JENEPONTO': 'e623',
    'KAB. SELAYAR': 'e624',
    'KAB. TAKALAR': 'e625',
    'KAB. BARRU': 'e626',
    'KAB. SIDENRENG RAPANG': 'e627',
    'KAB. PANGKAJENE KEPULAUAN': 'e628',
    'KAB. SOPPENG': 'e629',
    'KAB. ENREKANG': 'e630',
    'KAB. LUWU TIMUR': 'e631',
    'KAB. LUWU UTARA': 'e632',
    'KAB. TORAJA UTARA': 'e633',
    'KOTA MAKASSAR': 'e634',
    'KOTA PARE-PARE': 'e635',
    'KOTA PALOPO': 'e636',
    'KAB. MINAHASA': 'e637',
    'KAB. BOLAANG MONGONDOW': 'e638',
    'KAB. KEPULAUAN SANGIHE': 'e639',
    'KAB. KEPULAUAN TALAUD': 'e640',
    'KAB. MINAHASA SELATAN': 'e641',
    'KAB. MINAHASA UTARA': 'e642',
    'KAB. MINAHASA TENGGARA': 'e643',
    'KAB. BOLAANG MONGONDOW UTARA': 'e644',
    'KAB. KEPULAUAN SIAU TAGULANDANG BIARO': 'e645',
    'KAB. BOLAANG MONGONDOW SELATAN': 'e646',
    'KAB. BOLAANG MONGONDOW TIMUR': 'e647',
    'KOTA MANADO': 'e648',
    'KOTA KOTAMOBAGU': 'e649',
    'KOTA BITUNG': 'e650',
    'KOTA TOMOHON': 'e651',
    'KAB. GORONTALO': 'e652',
    'KAB. BOALEMO': 'e653',
    'KAB. BONE BOLANGO': 'e654',
    'KAB. POHUWATO': 'e655',
    'KAB. GORONTALO UTARA': 'e656',
    'KOTA GORONTALO': 'e657',
    'KAB. POLEWARI MANDAR': 'e658',
    'KAB. MAJENE': 'e659',
    'KAB. MAMASA': 'e660',
    'KAB. MAMUJU UTARA': 'e661',
    'KAB. MAMUJU': 'e662',
    'KAB. MAMUJU TENGAH': 'e788',
    'KAB. BUTON': 'e663',
    'KAB. MUNA': 'e664',
    'KAB. KOLAKA': 'e665',
    'KAB. WAKATOBI': 'e666',
    'KAB. KONAWE': 'e667',
    'KAB. KONAWE SELATAN': 'e668',
    'KAB. BOMBANA': 'e669',
    'KAB. KOLAKA UTARA': 'e670',
    'KAB. BUTON UTARA': 'e671',
    'KAB. KONAWE UTARA': 'e672',
    'KOTA BAU-BAU': 'e673',
    'KOTA KENDARI': 'e674',
    'KAB. KOLAKA TIMUR': 'e789',
    'KAB. LOMBOK BARAT': 'e675',
    'KAB. LOMBOK TENGAH': 'e676',
    'KAB. LOMBOK TIMUR': 'e677',
    'KAB. SUMBAWA': 'e678',
    'KAB. BIMA': 'e679',
    'KAB. DOMPU': 'e680',
    'KAB. SUMBAWA BARAT': 'e681',
    'KAB. LOMBOK UTARA': 'e682',
    'KOTA MATARAM': 'e683',
    'KOTA BIMA': 'e684',
    'KAB. BULELENG': 'e685',
    'KAB. JEMBRANA': 'e686',
    'KAB. TABANAN': 'e687',
    'KAB. BADUNG': 'e688',
    'KAB. GIANYAR': 'e689',
    'KAB. KLUNGKUNG': 'e690',
    'KAB. BANGLI': 'e691',
    'KAB. KARANGASEM': 'e692',
    'KOTA DENPASAR': 'e693',
    'KAB. KUPANG': 'e694',
    'KAB. TIMOR TENGAH SELATAN': 'e695',
    'KAB. TIMOR TENGAH UTARA': 'e696',
    'KAB. BELU': 'e697',
    'KAB. ALOR': 'e698',
    'KAB. FLORES TIMUR': 'e699',
    'KAB. SIKKA': 'e700',
    'KAB. ENDE': 'e701',
    'KAB. NGADA': 'e702',
    'KAB. MANGARAI': 'e703',
    'KAB. SUMBA TIMUR': 'e704',
    'KAB. SUMBA BARAT': 'e705',
    'KAB. LEMBATA': 'e706',
    'KAB. ROTE NDAO': 'e707',
    'KAB. MANGGARAI BARAT': 'e708',
    'KAB. SUMBA TENGAH': 'e709',
    'KAB. SUMBA BARAT DAYA': 'e710',
    'KAB. MANGGARAI TIMUR': 'e711',
    'KAB. NAGEKEO': 'e712',
    'KAB. SABU RAIJUA': 'e713',
    'KOTA KUPANG': 'e714',
    'KAB. MALAKA': 'e790',
    'KAB. TIMUR TENGAH UTARA': 'e791',
    'KAB. MALUKU TENGAH': 'e715',
    'KAB. MALUKU TENGGARA': 'e716',
    'KAB. MALUKU TENGGARA BARAT': 'e717',
    'KAB. BURU': 'e718',
    'KAB. SERAM BAGIAN BARAT': 'e719',
    'KAB. SERAM BAGIAN TIMUR': 'e720',
    'KAB. KEPULAUAN ARU': 'e721',
    'KAB. MALUKU BARAT DAYA': 'e722',
    'KAB. BURU SELATAN': 'e723',
    'KOTA AMBON': 'e724',
    'KOTA TUAL': 'e725',
    'KAB. JAYAPURA': 'e726',
    'KAB. BIAK NUMFOR': 'e727',
    'KAB. YAPEN WAROPEN': 'e728',
    'KAB. MERAUKE': 'e729',
    'KAB. PANIAI': 'e730',
    'KAB. JAYAWIJAYA': 'e731',
    'KAB. NABIRE': 'e732',
    'KAB. MIMIKA': 'e733',
    'KAB. PUNCAK JAYA': 'e734',
    'KAB. SARMI': 'e735',
    'KAB. KEEROM': 'e736',
    'KAB. PEGUNUNGAN BINTANG': 'e737',
    'KAB. YAHUKIMO': 'e738',
    'KAB. TOLIKARA': 'e739',
    'KAB. WAROPEN': 'e740',
    'KAB. BOVEN DIGOEL': 'e741',
    'KAB. MAPPI': 'e742',
    'KAB. ASMAT': 'e743',
    'KAB. SUPIORI': 'e744',
    'KAB. MAMBERAMO RAYA': 'e745',
    'KAB. DOGIYAI': 'e746',
    'KAB. LANNY JAYA': 'e747',
    'KAB. MAMBERAMO TENGAH': 'e748',
    'KAB. NDUGA': 'e749',
    'KAB. YALIMO': 'e750',
    'KAB. PUNCAK': 'e751',
    'KAB. INTAN JAYA': 'e752',
    'KOTA JAYAPURA': 'e753',
    'KAB. DEIYAI': 'e792',
    'KAB. HALMAHERA TENGAH': 'e754',
    'KAB. HALMAHERA UTARA': 'e755',
    'KAB. HALMAHERA TIMUR': 'e756',
    'KAB. HALMAHERA BARAT': 'e757',
    'KAB. HALMAHERA SELATAN': 'e758',
    'KAB. KEPULAUAN SULA': 'e759',
    'KAB. PULAU MOROTAI': 'e760',
    'KOTA TERNATE': 'e761',
    'KOTA TIDORE KEPULAUAN': 'e762',
    'KAB. TALIABU': 'e793',
    'KAB. SORONG': 'e763',
    'KAB. FAK-FAK': 'e764',
    'KAB. MANOKWARI': 'e765',
    'KAB. SORONG SELATAN': 'e766',
    'KAB. RAJA AMPAT': 'e767',
    'KAB. KAIMANA': 'e768',
    'KAB. TELUK BENTUNI': 'e769',
    'KAB. TELUK WONDAMA': 'e770',
    'KAB. TAMBRAUW': 'e771',
    'KAB. MAYBRAT': 'e775',
    'KOTA SORONG': 'e772',
    'KAB. MANOKWARI SELATAN': 'e794',
    'PEGUNUNGAN ARFAK': 'e795',
    'KAB. BULUNGAN': 'e577',
    'KAB. NUNUKAN': 'e580',
    'KAB. MALINAU': 'e581',
    'KAB. TANA TIDUNG': 'e583',
    'KOTA TARAKAN': 'e586',
    'LAIN - LAIN': 'e999',
}

provinces = {
    "DI YOGYAKARTA": "34",
    "BANTEN": "36",
    "JAKARTA": "31",
    "JAWA BARAT": "32",
    "JAWA TENGAH": "33",
    "DIY YOGYAKARTA": "34",
    "JAWA TIMUR": "35",
    "ACEH": "11",
    "SUMATERA UTARA": "12",
    "SUMATERA BARAT": "13",
    "RIAU": "14",
    "KEPULAUAN RIAU": "21",
    "BANGKA BELITUNG": "19",
    "JAMBI": "15",
    "SUMATERA SELATAN": "16",
    "BENGKULU": "17",
    "LAMPUNG": "18",
    "KALIMANTAN BARAT": "61",
    "KALIMANTAN TENGAH": "62",
    "KALIMANTAN UTARA": "65",
    "KALIMANTAN TIMUR": "64",
    "KALIMANTAN SELATAN": "63",
    "SULAWESI UTARA": "71",
    "GORONTALO": "75",
    "SULAWESI TENGAH": "72",
    "SULAWESI BARAT": "76",
    "SULAWESI SELATAN": "73",
    "SULAWESI TENGGARA": "74",
    "BALI": "51",
    "NTB": "52",
    "NTT": "53",
    "MALUKU": "81",
    "PAPUA BARAT": "92",
    "MALUKU UTARA": "82",
    "PAPUA": "91",
}

home_statuses = ['Milik sendiri, lunas', 'Milik sendiri, mencicil']

gender = {
    "MALE": "Pria",
    "FEMALE": "Wanita",
}

jobs = {
    'Tidak bekerja': 8,
    'Staf rumah tangga': 7,
    'Pengusaha': 5,
    'Pekerja rumah tangga': 7,
    'Pegawai swasta': 4,
    'Pegawai negeri': 1,
    'Mahasiswa': 6,
    'Lainnya': 7,
    'Ibu rumah tangga': 8,
    'Freelance': 7,
}

job_desc__job = {
    "BELUM/ TIDAK BEKERJA": "Tidak bekerja",
    "MENGURUS RUMAH TANGGA": "Tidak bekerja",
    "PELAJAR/ MAHASISWA": "Mahasiswa",
    "PENSIUNAN": "Tidak bekerja",
    "PEGAWAI NEGERI SIPIL": "Pegawai negeri",
    "TENTARA NASIONAL INDONESIA": "Pegawai negeri",
    "KEPOLISIAN RI": "Pegawai negeri",
    "PERDAGANGAN": "Pengusaha",
    "PETANI/ PEKEBUN": "Pengusaha",
    "PETERNAK": "Pengusaha",
    "NELAYAN/ PERIKANAN": "Pengusaha",
    "INDUSTRI": "Pegawai swasta",
    "KONSTRUKSI": "Pegawai swasta",
    "TRANSPORTASI": "Pegawai swasta",
    "KARYAWAN SWASTA": "Pegawai swasta",
    "KARYAWAN BUMN": "Pegawai negeri",
    "KARYAWAN BUMD": "Pegawai negeri",
    "KARYAWAN HONORER": "Pegawai negeri",
    "BURUH HARIAN LEPAS": "Pengusaha",
    "BURUH TANI/ PERKEBUNAN": "Pengusaha",
    "BURUH NELAYAN/ PERIKANAN": "Pengusaha",
    "BURUH PETERNAKAN": "Pengusaha",
    "PEMBANTU RUMAH TANGGA": "Staf rumah tangga",
    "TUKANG CUKUR": "Pengusaha",
    "TUKANG LISTRIK": "Pengusaha",
    "TUKANG BATU": "Pengusaha",
    "TUKANG KAYU": "Pengusaha",
    "TUKANG SOL SEPATU": "Pengusaha",
    "TUKANG LAS/ PANDAI BESI": "Pengusaha",
    "TUKANG JAHIT": "Pengusaha",
    "TUKANG GIGI": "Pengusaha",
    "PENATA RIAS": "Pengusaha",
    "PENATA BUSANA": "Pengusaha",
    "PENATA RAMBUT": "Pengusaha",
    "MEKANIK": "Pegawai swasta",
    "SENIMAN": "Pegawai swasta",
    "TABIB": "Pegawai swasta",
    "PARAJI": "Pegawai swasta",
    "PERANCANG BUSANA": "Pegawai swasta",
    "PENTERJEMAH": "Pegawai swasta",
    "IMAM MASJID": "Pengusaha",
    "PENDETA": "Pengusaha",
    "PASTOR": "Pengusaha",
    "WARTAWAN": "Pegawai swasta",
    "USTADZ/ MUBALIGH": "Pegawai swasta",
    "JURU MASAK": "Pegawai swasta",
    "PROMOTOR ACARA": "Pengusaha",
    "ANGGOTA DPR-RI": "Pegawai negeri",
    "ANGGOTA DPD": "Pegawai negeri",
    "ANGGOTA BPK": "Pegawai negeri",
    "PRESIDEN": "Pegawai negeri",
    "WAKIL PRESIDEN": "Pegawai negeri",
    "ANGGOTA MAHKAMAH KONSTITUSI": "Pegawai negeri",
    "ANGGOTA KABINET/ KEMENTERIAN": "Pegawai negeri",
    "DUTA BESAR": "Pegawai negeri",
    "GUBERNUR": "Pegawai negeri",
    "WAKIL GUBERNUR": "Pegawai negeri",
    "BUPATI": "Pegawai negeri",
    "WAKIL BUPATI": "Pegawai negeri",
    "WALIKOTA": "Pegawai negeri",
    "WAKIL WALIKOTA": "Pegawai negeri",
    "ANGGOTA DPRD PROVINSI": "Pegawai negeri",
    "ANGGOTA DPRD KABUPATEN/ KOTA": "Pegawai negeri",
    "DOSEN": "Pegawai swasta",
    "GURU": "Pegawai swasta",
    "PILOT": "Pegawai swasta",
    "PENGACARA": "Pegawai negeri",
    "NOTARIS": "Pegawai negeri",
    "ARSITEK": "Pegawai swasta",
    "AKUNTAN": "Pegawai swasta",
    "KONSULTAN": "Pegawai swasta",
    "DOKTER": "Pegawai swasta",
    "BIDAN": "Pegawai swasta",
    "PERAWAT": "Pegawai swasta",
    "APOTEKER": "Pegawai swasta",
    "PSIKIATER/ PSIKOLOG": "Pegawai swasta",
    "PENYIAR TELEVISI": "Pegawai swasta",
    "PENYIAR RADIO": "Pegawai swasta",
    "PELAUT": "Pegawai swasta",
    "PENELITI": "Pegawai swasta",
    "SOPIR": "Pegawai swasta",
    "PIALANG": "Pegawai swasta",
    "PARANORMAL": "Pengusaha",
    "PEDAGANG": "Pengusaha",
    "PERANGKAT DESA": "Pegawai negeri",
    "KEPALA DESA": "Pegawai negeri",
    "BIARAWATI": "Pegawai negeri",
    "WIRASWASTA": "Pengusaha",
    "BURUH": "Pengusaha",
    "PEKERJAAN LAINNYA": "Lainnya",
    "OTHERS": "Lainnya",
}

job__job_industries = {
    "BELUM/ TIDAK BEKERJA": "Tidak bekerja",
    "MENGURUS RUMAH TANGGA": "Staf Rumah Tangga",
    "PELAJAR/ MAHASISWA": "Mahasiswa",
    "PENSIUNAN": "Tidak bekerja",
    "PEGAWAI NEGERI SIPIL": "Service",
    "TENTARA NASIONAL INDONESIA": "Hukum / Security / Politik",
    "KEPOLISIAN RI": "Hukum / Security / Politik",
    "PERDAGANGAN": "Perdagangan",
    "PETANI/ PEKEBUN": "Service",
    "PETERNAK": "Service",
    "NELAYAN/ PERIKANAN": "Pedagang",
    "INDUSTRI": "Pabrik / Gudang",
    "KONSTRUKSI": "Konstruksi / Real Estate",
    "TRANSPORTASI": "Transportasi",
    "KARYAWAN SWASTA": "Service",
    "KARYAWAN BUMN": "Service",
    "KARYAWAN BUMD": "Service",
    "KARYAWAN HONORER": "Service",
    "BURUH HARIAN LEPAS": "Service",
    "BURUH TANI/ PERKEBUNAN": "Service",
    "BURUH NELAYAN/ PERIKANAN": "Service",
    "BURUH PETERNAKAN": "Service",
    "PEMBANTU RUMAH TANGGA": "Staf Rumah Tangga",
    "TUKANG CUKUR": "Service",
    "TUKANG LISTRIK": "Listrik, Gas, dan Air",
    "TUKANG BATU": "Service",
    "TUKANG KAYU": "Service",
    "TUKANG SOL SEPATU": "Service",
    "TUKANG LAS/ PANDAI BESI": "Service",
    "TUKANG JAHIT": "Service",
    "TUKANG GIGI": "Kesehatan",
    "PENATA RIAS": "Entertainment / Event",
    "PENATA BUSANA": "Entertainment / Event",
    "PENATA RAMBUT": "Entertainment / Event",
    "MEKANIK": "Tehnik / Computer",
    "SENIMAN": "Design / Seni",
    "TABIB": "Kesehatan",
    "PARAJI": "Kesehatan",
    "PERANCANG BUSANA": "Design / Seni",
    "PENTERJEMAH": "Pendidikan",
    "IMAM MASJID": "Pendidikan",
    "PENDETA": "Pendidikan",
    "PASTOR": "Pendidikan",
    "WARTAWAN": "Media",
    "USTADZ/ MUBALIGH": "Pendidikan",
    "JURU MASAK": "Service",
    "PROMOTOR ACARA": "Entertainment / Event",
    "ANGGOTA DPR-RI": "Hukum / Security / Politik",
    "ANGGOTA DPD": "Hukum / Security / Politik",
    "ANGGOTA BPK": "Hukum / Security / Politik",
    "PRESIDEN": "Hukum / Security / Politik",
    "WAKIL PRESIDEN": "Hukum / Security / Politik",
    "ANGGOTA MAHKAMAH KONSTITUSI": "Hukum / Security / Politik",
    "ANGGOTA KABINET/ KEMENTERIAN": "Hukum / Security / Politik",
    "DUTA BESAR": "Hukum / Security / Politik",
    "GUBERNUR": "Hukum / Security / Politik",
    "WAKIL GUBERNUR": "Hukum / Security / Politik",
    "BUPATI": "Hukum / Security / Politik",
    "WAKIL BUPATI": "Hukum / Security / Politik",
    "WALIKOTA": "Hukum / Security / Politik",
    "WAKIL WALIKOTA": "Hukum / Security / Politik",
    "ANGGOTA DPRD PROVINSI": "Hukum / Security / Politik",
    "ANGGOTA DPRD KABUPATEN/ KOTA": "Hukum / Security / Politik",
    "DOSEN": "Pendidikan",
    "GURU": "Pendidikan",
    "PILOT": "Transportasi",
    "PENGACARA": "Hukum / Security / Politik",
    "NOTARIS": "Hukum / Security / Politik",
    "ARSITEK": "Konstruksi / Real Estate",
    "AKUNTAN": "Admin / Finance / HR",
    "KONSULTAN": "Service",
    "DOKTER": "Kesehatan",
    "BIDAN": "Kesehatan",
    "PERAWAT": "Kesehatan",
    "APOTEKER": "Kesehatan",
    "PSIKIATER/ PSIKOLOG": "Kesehatan",
    "PENYIAR TELEVISI": "Media",
    "PENYIAR RADIO": "Media",
    "PELAUT": "Transportasi",
    "PENELITI": "Service",
    "SOPIR": "Transportasi",
    "PIALANG": "Perbankan",
    "PARANORMAL": "Service",
    "PEDAGANG": "Pedagang",
    "PERANGKAT DESA": "Hukum / Security / Politik",
    "KEPALA DESA": "Hukum / Security / Politik",
    "BIARAWATI": "Pendidikan",
    "WIRASWASTA": "Pedagang",
    "BURUH": "Service",
    "PEKERJAAN LAINNYA": "Lainnya",
    "OTHERS": "Lainnya",
}

job_industries = {
    'Mahasiswa': 'e00',
    'Pelajar': 'e00',
    'Ibu rumah tangga': 'e01',
    'Tidak bekerja': 'e01',
    'Pabrik / Gudang': 'e12',
    'Listrik, Gas, dan Air': 'e36',
    'Pedagang': 'e40',
    'Perdagangan': 'e40',
    'Sales / Marketing': 'e40',
    'Entertainment / Event': 'e46',
    'Perhotelan': 'e46',
    'Media': 'e47',
    'Transportasi': 'e47',
    'Perbankan': 'e52',
    'Konstruksi / Real Estate': 'e56',
    'Pendidikan': 'e63',
    'Kesehatan': 'e64',
    'Tehnik / Computer': 'e67',
    'Teknologi Informasi': 'e67',
    'Admin / Finance / HR': 'e62',
    'Perawatan Tubuh': 'e70',
    'Service': 'e70',
    'Staf rumah tangga': 'e70',
    'Staf Rumah Tangga': 'e70',
    'Hukum / Security / Politik': 'e71',
    'Design / Seni': 'e72',
    'Lainnya': 'e72',
    'Advertising': 'e46',
    'Information and Technology': 'e67',
    'Telecommunication': 'e67',
    'Transportation': 'e47',
    'Agriculture or Aquaculture': 'e2',
    'Construction': 'e56',
    'Health and Beauty': 'e64',
    'Manufacturing': 'e12',
    'Real Estate': 'e56',
    'Food and Beverage': 'e40',
    'Leisure & Travel': 'e46',
    'Accommodation & Hotel': 'e46',
    'Education': 'e63',
    'Financial Services': 'e62',
    'Services': 'e70',
    'Retail': 'e40',
    'Entertainment & Lifestyle': 'e46',
    'Online Shopping': 'e40',
    'Wholesale': 'e40',
}

marital_statuses = {
    'Cerai': 1,
    'Janda / duda': 1,
    'Menikah': 1,
    'Lajang': 2,
}


class GenderConstant(object):
    GENDER_MALE = 1
    GENDER_FEMALE = 2
    GENDER_LENDER = 3


genders = {
    'Pria': GenderConstant.GENDER_MALE,
    'Wanita': GenderConstant.GENDER_FEMALE,
}


class EducationConstant(object):
    EDUCATION_ELEMENTARY_SCHOOL = 1
    EDUCATION_JUNIOR_SCHOOL = 2
    EDUCATION_HIGH_SCHOOL = 3
    EDUCATION_DIPLOMA = 4
    EDUCATION_S1 = 5
    EDUCATION_S2 = 6
    EDUCATION_S3 = 7

    EDUCATION_LENDER = 8
    EDUCATION_DEFAULT = 9


class RequestDataConstant(object):
    JULO_LENDER_ID = 514133

    SOURCE_OF_FUND_OTHERS = "Lain-Lain"

    DOMICILE_COUNTRY_INDONESIA = 0

    DEFAULT_TOTAL_ASSET = 0

    OWN_HOUSE = 1
    NOT_OWN_HOUSE = 2


class LoanConstant(object):
    INTEREST_RATE_UNIT = 4  # yearly
    INTEREST_TYPE = 1  # flat
    INSTALMENT_FREQUENCY = 3  # monthly
    TENURE_RATE_UNIT = 3  # Monthly
    LENDING_TYPE = 2  # non syariah
    LOAN_PURPOSE_DEFAULT = 'e0'  # from legacy code
    COLLATERAL = 2
    COLLATERAL_DEFAULT = 8
    COLLATERAL_RATIO = 0
    ASSET_RATIO = 0
    PLAFOND = 0
    WAITING_DAY_DEFAULT = 2
    COUNT_DEFAULT = 1


class UserConstant(object):
    LENDER_USER_ID = 2
    REGULAR_USER_ID = 1

    LENDER_IDENTITY_TYPE = 3
    USER_IDENTITY_TYPE = 1

    LENDER_LEGAL_ENTITY_TYPE = 1
    REGULAR_USER_LEGAL_ENTITY_TYPE = 6

    OTHER_RELIGION_ID = 7
    LENDER_RELIGION_ID = 8
    NO_RELIGION_DATA_ID = 9


class ApplicationConstant(object):
    MARITAL_STATUS_MARRIED = 1
    MARITAL_STATUS_NOT_MARRIED = 2
    MARITAL_STATUS_LEGAL_ENTITY = 3
    MARITAL_STATUS_NO_DATA = 4

    JOB_LEGAL_ENTITY = 9
    JOB_NO_DATA = 10

    JOB_INDUSTRY_DEFAULT_ID = "e99"
    CITY_DEFAULT_ID = 'e999'
    PROVINCE_DEFAULT_ID = '99'
    ADDRESS_DEFAULT_VALUE = 'alamat kosong'

    JOB_ONLINE_ID = 3

    MONTHLY_INCOME_FIRST_TIER = '1'
    MONTHLY_INCOME_SECOND_TIER = '2'
    MONTHLY_INCOME_THIRD_TIER = '3'
    MONTHLY_INCOME_FOURTH_TIER = '4'
    MONTHLY_INCOME_FIFTH_TIER = '5'

    MONTHLY_INCOME_DEFAULT_TIER = 'p7'

    WORK_EXPERIENCE_NO_EXPERIENCE = 0
    WORK_EXPERIENCE_LESS_THAN_ONE_YEAR = 1
    WORK_EXPERIENCE_ONE_YEAR_TO_LESS_THAN_TWO_YEAR = 2
    WORK_EXPERIENCE_TWO_YEAR_TO_THREE_YEAR = 3
    WORK_EXPERIENCE_MORE_THAN_THREE_YEAR = 4
    WORK_EXPERIENCE_LEGAL_ENTITY = 5
    WORK_EXPERIENCE_NO_DATA = 6

    LEGAL_ENTITY_IDENTITY_NUMBER = '802965566015000'
    LEGAL_ENTITY_USER_IDS = [514133]
