# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-12-18 04:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_status', '0002_paymentlocked_paymentlockedmaster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentlockedmaster',
            old_name='application',
            new_name='payment',
        ),
    ]
