# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-02-12 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disbursement', '0004_disbursement_disbursement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursement',
            name='name_bank_validation',
            field=models.ForeignKey(db_column='name_bank_validation_id', on_delete=django.db.models.deletion.CASCADE, to='disbursement.NameBankValidation'),
        ),
    ]
