# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-08-23 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disbursement', '0013_disbursement_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursement',
            name='original_amount',
            field=models.BigIntegerField(null=True),
        ),
    ]
