# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-10-23 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disbursement', '0015_disbursementnewflowhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disbursement2History',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='disbursement2_history_id', primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField()),
                ('method', models.CharField(max_length=50)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('idempotency_id', models.CharField(blank=True, max_length=100, null=True)),
                ('disburse_status', models.CharField(blank=True, max_length=50, null=True)),
                ('reason', models.CharField(blank=True, max_length=500, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('attempt', models.IntegerField(blank=True, null=True)),
                ('step', models.IntegerField(blank=True, null=True)),
                ('disbursement', models.ForeignKey(db_column='disbursement_id', on_delete=django.db.models.deletion.CASCADE, to='disbursement.Disbursement')),
            ],
            options={
                'db_table': 'disbursement2_history',
            },
        ),
        migrations.RemoveField(
            model_name='disbursementnewflowhistory',
            name='disbursement',
        ),
        migrations.DeleteModel(
            name='DisbursementNewFlowHistory',
        ),
    ]
