# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-03-30 02:27
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CootekConfiguration',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column=b'cootek_configuration_id', primary_key=True, serialize=False)),
                ('task_name', models.CharField(default=None, max_length=200)),
                ('task_type', models.CharField(default=None, max_length=200, null=True)),
                ('called_at', models.IntegerField()),
                ('time_to_start', models.TimeField()),
                ('time_to_prepare', models.TimeField(blank=True, null=True)),
                ('time_to_query_result', models.TimeField(blank=True, null=True)),
                ('number_of_attempts', models.CharField(choices=[(b'0', b'0'), (b'1', b'1'), (b'2', b'2'), (b'3', b'3')], max_length=200)),
                ('tag_status', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=None, null=True, size=None)),
                ('from_previous_cootek_result', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cootek_configuration',
            },
        ),
        migrations.CreateModel(
            name='CootekRobot',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column=b'cootek_robot_id', primary_key=True, serialize=False)),
                ('robot_identifier', models.CharField(default=None, max_length=200, null=True)),
                ('robot_name', models.CharField(default=None, max_length=200, null=True)),
            ],
            options={
                'db_table': 'cootek_robot',
            },
        ),
        migrations.AddField(
            model_name='cootekconfiguration',
            name='cootek_robot',
            field=models.ForeignKey(blank=True, db_column=b'cootek_robot_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cootek.CootekRobot'),
        ),
    ]
