# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-03-17 07:00
from __future__ import unicode_literals

from django.db import migrations
from juloserver.cootek.models import CootekRobot


def initial_data_for_cootek_configuration(apps, schema_editor):
    CootekConfiguration = apps.get_model("cootek", "CootekConfiguration")

    cootek_configs = [
        {'task_name': 'JULO_T0', 'time_to_start': '08:00:00',  'task_type': 'JULO_T0',  'robot': '3f53ac78e7fea695a164f55a6ff4de21', 'repeat_number': 4, 'called_at': 0, 'intention_filter': [], 'from_previous_cootek_result': False },
        {'task_name': 'JULO_T0', 'time_to_start': '10:00:00', 'task_type': 'JULO_T0',  'robot': '3f53ac78e7fea695a164f55a6ff4de21', 'repeat_number': 3, 'called_at': 0, 'intention_filter': ['B', 'D', 'F', 'G', '--'], 'from_previous_cootek_result': True },
        {'task_name': 'JULO_T0', 'time_to_start': '12:00:00', 'task_type': 'JULO_T0',  'robot': '3f53ac78e7fea695a164f55a6ff4de21', 'repeat_number': 3, 'called_at': 0, 'intention_filter': ['B', 'D', 'E', 'F', 'G', 'H', 'I', '--'], 'from_previous_cootek_result': True },
        {'task_name': 'JULO_T0', 'time_to_start': '14:00:00', 'task_type': 'JULO_T0',  'robot': '3f53ac78e7fea695a164f55a6ff4de21', 'repeat_number': 3, 'called_at': 0, 'intention_filter': ['B', 'D', 'E', 'F', 'G', 'H', 'I', '--'], 'from_previous_cootek_result': True },
        {'task_name': 'JULO_T-1', 'time_to_start': '08:00:00', 'task_type': 'JULO_T-1',  'robot': 'a92093795e0975c03c132633d83bcc13', 'repeat_number': 3, 'called_at': -1, 'intention_filter': [], 'from_previous_cootek_result': False },
        {'task_name': 'JULO_T-1', 'time_to_start': '10:00:00', 'task_type': 'JULO_T-1',  'robot': 'a92093795e0975c03c132633d83bcc13', 'repeat_number': 3, 'called_at': -1, 'intention_filter': ['B', 'D', 'F', 'G', '--'], 'from_previous_cootek_result': True },
        {'task_name': 'JULO_T-1', 'time_to_start': '12:00:00', 'task_type': 'JULO_T-1',  'robot': 'a92093795e0975c03c132633d83bcc13', 'repeat_number': 3, 'called_at': -1, 'intention_filter': ['B', 'D', 'F', 'G', '--'], 'from_previous_cootek_result': True },
        {'task_name': 'JULO_T-1', 'time_to_start': '14:00:00', 'task_type': 'JULO_T-1',  'robot': 'a92093795e0975c03c132633d83bcc13', 'repeat_number': 2, 'called_at': -1, 'intention_filter': ['E', 'H', 'I'], 'from_previous_cootek_result': True },
        {'task_name': 'JULO_T-2', 'time_to_start': '08:00:00', 'task_type': 'JULO_T-2',  'robot': 'a92093795e0975c03c132633d83bcc13', 'repeat_number': 3, 'called_at': -2, 'intention_filter': [], 'from_previous_cootek_result': False },
        {'task_name': 'JULO_T-2', 'time_to_start': '10:00:00', 'task_type': 'JULO_T-2',  'robot': 'a92093795e0975c03c132633d83bcc13', 'repeat_number': 3, 'called_at': -2, 'intention_filter': ['B', 'D', 'F', 'G', '--'], 'from_previous_cootek_result': True },
        {'task_name': 'JULO_T-2', 'time_to_start': '12:00:00', 'task_type': 'JULO_T-2',  'robot': 'a92093795e0975c03c132633d83bcc13', 'repeat_number': 3, 'called_at': -2, 'intention_filter': ['B', 'D', 'F', 'G', '--'], 'from_previous_cootek_result': True },
        {'task_name': 'JULO_T-2', 'time_to_start': '14:00:00', 'task_type': 'JULO_T-2',  'robot': 'a92093795e0975c03c132633d83bcc13', 'repeat_number': 2, 'called_at': -2, 'intention_filter': ['E', 'H', 'I'], 'from_previous_cootek_result': True },
    ]

    for config in cootek_configs:
        CootekConfiguration.objects.create(
            time_to_start=config['time_to_start'],
            task_name=config['task_name'],
            task_type=config['task_type'],
            called_at=config['called_at'],
            number_of_attempts=config['repeat_number'],
            tag_status=config['intention_filter'],
            from_previous_cootek_result=config['from_previous_cootek_result'],
        )


class Migration(migrations.Migration):

    dependencies = [
        ('cootek', '0002_initial_cootek_robot_data'),
    ]

    operations = [
         migrations.RunPython(initial_data_for_cootek_configuration, migrations.RunPython.noop)
    ]
