# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-04-22 03:06
from __future__ import unicode_literals

from django.db import migrations,models

import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cootek', '0004_rename_field_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cootekconfiguration',
            name='partner',
            field=models.ForeignKey(blank=True, db_column=b'partner_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Partner')
        ),
    ]
