# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-06-16 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cootek', '0006_add_new_cootek_robot'),
    ]

    operations = [
        migrations.AddField(
            model_name='cootekconfiguration',
            name='called_to',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'To'),
        ),
        migrations.AddField(
            model_name='cootekconfiguration',
            name='criteria',
            field=models.CharField(
                blank=True,
                choices=[(b'Refinancing_Pending', b'Refinancing Pending (4)')],
                max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cootekconfiguration',
            name='dpd_condition',
            field=models.CharField(
                blank=True,
                choices=[
                    (b'Exactly', b'Exactly on this dpd'),
                    (b'Range', b'Dpd range'),
                    (b'Less', b'Less than this dpd')],
                default=b'Exactly', max_length=200, null=True, verbose_name=b'called_at'),
        ),
        migrations.AlterField(
            model_name='cootekconfiguration',
            name='called_at',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'From'),
        ),
        migrations.AlterUniqueTogether(
            name='cootekconfiguration',
            unique_together=set([('task_type', 'time_to_start')]),
        ),
    ]
