# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-07-18 15:44
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('followthemoney', '0004_add_ftm_config_feature_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationLenderHistory',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='application_lender_history_id', primary_key=True, serialize=False)),
                ('application', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Application')),
                ('partner', models.ForeignKey(db_column='partner_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Partner')),
            ],
            options={
                'db_table': 'application_lender_history',
            },
        ),
        migrations.AddField(
            model_name='lenderbucket',
            name='action_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lenderbucket',
            name='action_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
