# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-10-23 08:37
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('julo', '0516_cootek_robocall_experiment_v3'),
        ('disbursement', '0014_disbursement_original_amount'),
        ('followthemoney', '0010_default_lender_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='LenderBalanceCurrent',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='lender_balance_current_id', primary_key=True, serialize=False)),
                ('available_balance', models.BigIntegerField(default=0)),
                ('outstanding_principal', models.BigIntegerField(default=0)),
                ('outstanding_interest', models.BigIntegerField(default=0)),
                ('committed_amount', models.BigIntegerField(default=0)),
                ('principal_paid', models.BigIntegerField(default=0)),
                ('interest_paid', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'lender_balance_current',
            },
        ),
        migrations.CreateModel(
            name='LenderBalanceHistory',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='lender_balance_history_id', primary_key=True, serialize=False)),
                ('available_balance', models.BigIntegerField(default=0)),
                ('outstanding_principal', models.BigIntegerField(default=0)),
                ('outstanding_interest', models.BigIntegerField(default=0)),
                ('committed_amount', models.BigIntegerField(default=0)),
                ('principal_paid', models.BigIntegerField(default=0)),
                ('interest_paid', models.BigIntegerField(default=0)),
                ('snapshot_ts', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lender_balance_history',
            },
        ),
        migrations.CreateModel(
            name='LenderCurrent',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='lender_id', primary_key=True, serialize=False)),
                ('lender_name', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('business_type', models.TextField(blank=True, null=True)),
                ('company_address', models.TextField()),
                ('company_name', models.TextField()),
                ('npwp', models.TextField()),
                ('poc_email', models.TextField()),
                ('poc_name', models.TextField()),
                ('poc_phone', models.TextField()),
                ('source_of_fund', models.TextField(blank=True, null=True)),
                ('aggrement_letter_number', models.TextField()),
                ('activity_start_date', models.DateTimeField(blank=True, null=True)),
                ('activity_end_date', models.DateTimeField(blank=True, null=True)),
                ('akte_pendirian', models.CharField(max_length=200)),
                ('surat_ijin_usaha', models.CharField(max_length=200)),
                ('tanda_daftar_perusahaan', models.CharField(max_length=200)),
                ('sk_menteri', models.CharField(max_length=200)),
                ('nomor_ijin_berusaha', models.CharField(blank=True, max_length=200, null=True)),
                ('rdl_account_number', models.BigIntegerField(default=0)),
                ('withdrawal_account_number', models.BigIntegerField(default=0)),
                ('withdrawal_account_name', models.TextField()),
                ('withdrawal_bank_code', models.IntegerField()),
                ('disbursement_va_number', models.BigIntegerField(default=0)),
                ('deposit_va_number', models.BigIntegerField(default=0)),
                ('repayment_va_number', models.BigIntegerField(default=0)),
                ('service_fee', models.FloatField()),
                ('auth_user', models.ForeignKey(blank=True, db_column='auth_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lender',
            },
        ),
        migrations.CreateModel(
            name='LenderTransaction',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='lender_transaction_id', primary_key=True, serialize=False)),
                ('transaction_amount', models.BigIntegerField(default=0)),
                ('transaction_status', models.TextField()),
                ('lender', models.ForeignKey(db_column='lender_id', on_delete=django.db.models.deletion.DO_NOTHING, to='followthemoney.LenderCurrent')),
                ('lender_balance_current', models.ForeignKey(db_column='lender_balance_current_id', on_delete=django.db.models.deletion.DO_NOTHING, to='followthemoney.LenderBalanceCurrent')),
            ],
            options={
                'db_table': 'lender_transaction',
            },
        ),
        migrations.CreateModel(
            name='LenderTransactionMapping',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='lender_transaction_mapping_id', primary_key=True, serialize=False)),
                ('disbursement', models.ForeignKey(blank=True, db_column='disbursement_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='disbursement.Disbursement')),
                ('lender', models.ForeignKey(blank=True, db_column='lender_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='followthemoney.LenderCurrent')),
                ('payment_event', models.ForeignKey(blank=True, db_column='payment_event_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.PaymentEvent')),
            ],
            options={
                'db_table': 'lender_transaction_mapping',
            },
        ),
        migrations.CreateModel(
            name='LenderTransactionType',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='lender_transaction_type_id', primary_key=True, serialize=False)),
                ('transaction_type', models.TextField()),
                ('transaction_amount_sign', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'lender_transaction_type',
            },
        ),
        migrations.AddField(
            model_name='lendertransaction',
            name='transaction_type',
            field=models.ForeignKey(db_column='lender_transaction_type_id', on_delete=django.db.models.deletion.DO_NOTHING, to='followthemoney.LenderTransactionType'),
        ),
        migrations.AddField(
            model_name='lenderbalancehistory',
            name='lender',
            field=models.ForeignKey(db_column='lender_id', on_delete=django.db.models.deletion.DO_NOTHING, to='followthemoney.LenderCurrent'),
        ),
        migrations.AddField(
            model_name='lenderbalancecurrent',
            name='lender',
            field=models.OneToOneField(db_column='lender_id', on_delete=django.db.models.deletion.DO_NOTHING, to='followthemoney.LenderCurrent'),
        ),
    ]
