# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-10-23 16:33
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followthemoney', '0012_create_table_loan_writeoff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanwriteoff',
            name='wo_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunSQL(
            "ALTER TABLE loan_writeoff ALTER COLUMN loan_id TYPE bigint ;"),
    ]
