# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-10-24 07:02
from __future__ import unicode_literals

from django.db import migrations
from juloserver.followthemoney.constants import LenderTransactionTypeConst
from juloserver.followthemoney.models import LenderTransactionType


def add_lender_transaction_type_data(apps, schema_editor):
    lender_transaction_types = [
        LenderTransactionTypeConst.DEPOSIT,
        LenderTransactionTypeConst.WITHDRAWAL,
        LenderTransactionTypeConst.DISBURSEMENT,
        LenderTransactionTypeConst.REPAYMENT,
        LenderTransactionTypeConst.PLATFORM_FEE,
        LenderTransactionTypeConst.BALANCE_ADJUSTMENT,
        LenderTransactionTypeConst.TAX_DEDUCTION,
    ]
    lender_transaction_type_arr = []

    for lender_transaction_type in lender_transaction_types:
        data = LenderTransactionType(transaction_type=lender_transaction_type)
        lender_transaction_type_arr.append(data)

    LenderTransactionType.objects.bulk_create(lender_transaction_type_arr)


class Migration(migrations.Migration):

    dependencies = [
        ('followthemoney', '0015_update_lender_table'),
    ]

    operations = [
        migrations.RunPython(add_lender_transaction_type_data)
    ]
