# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-10-25 04:50
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followthemoney', '0017_add_transaction_description_in_lender_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendercurrent',
            name='addendum_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
