# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-10-25 15:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('followthemoney', '0018_add_addendum_number_in_lender_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationlenderhistory',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='loanagreementtemplate',
            name='partner',
        ),
        migrations.AddField(
            model_name='applicationlenderhistory',
            name='lender',
            field=models.ForeignKey(blank=True, db_column='lender_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='followthemoney.LenderCurrent'),
        ),
        migrations.AddField(
            model_name='loanagreementtemplate',
            name='lender',
            field=models.ForeignKey(blank=True, db_column='lender_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='followthemoney.LenderCurrent'),
        ),
        migrations.AlterField(
            model_name='loanagreementtemplate',
            name='body',
            field=models.TextField(blank=True, help_text='For custom parameter text use double bracket         and split using dot(.) for table and field.        i.e: {{partner.name}}', null=True),
        ),
    ]
