# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-10-26 08:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('followthemoney', '0019_change_relation_to_lender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lendercurrent',
            name='auth_user',
        ),
        migrations.AddField(
            model_name='lendercurrent',
            name='user',
            field=models.OneToOneField(blank=True, db_column='auth_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
