# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-10-29 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followthemoney', '0023_update_lender_withdtawal_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendercurrent',
            name='lender_display_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
