# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-11-04 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followthemoney', '0030_add_old_id_in_ltm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanwriteoff',
            name='wo_period',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
