# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-11-21 03:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('followthemoney', '0035_is_signed_bucket_xid'),
    ]

    operations = [
        migrations.CreateModel(
            name='LenderInsurance',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='lender_insurance_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'lender_insurance',
            },
        ),
        migrations.AddField(
            model_name='lendercurrent',
            name='insurance',
            field=models.ForeignKey(blank=True, db_column='lender_insurance_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='followthemoney.LenderInsurance'),
        ),
    ]
