# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-11-22 03:25
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('followthemoney', '0038_lender_disbursement_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='LenderRepaymentTransaction',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='transaction_id', primary_key=True, serialize=False)),
                ('transaction_date', models.DateField()),
                ('reference_id', models.CharField(max_length=20)),
                ('currency_code', models.CharField(max_length=10)),
                ('amount', models.IntegerField()),
                ('beneficiary_account_number', models.CharField(max_length=100)),
                ('beneficiary_bank_code', models.CharField(max_length=20)),
                ('beneficiary_name', models.CharField(max_length=100)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('response_code', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_info', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('lender_transaction', models.ForeignKey(blank=True, db_column='lender_transaction_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='followthemoney.LenderTransaction')),
            ],
            options={
                'db_table': 'lender_repayment_transaction',
            },
        ),
        migrations.RunSQL('ALTER SEQUENCE ops.lender_repayment_transaction_transaction_id_seq RESTART WITH 10000000'),
    ]
