from django.db import transaction
from django.core.management.base import BaseCommand
from juloserver.streamlined_communication.models import (
    StreamlinedCommunication,
    StreamlinedMessage,
    InfoCardProperty,
    InfoCardButtonProperty,
)
from juloserver.julo.models import Image


def create_image(image_source_id, image_type, image_url):
    image = Image()
    image.image_source = image_source_id
    image.image_type = image_type
    image.url = image_url
    image.save()


class Command(BaseCommand):
    def handle(self, *args, **options):
        """
        Command to Retroload JTurbo Info Card For T minus 10 Until T 91.
        """
        jturbo_info_card_retroload_data = [
            {
                "streamlined_communication": {
                    "status_code_id": None,
                    "status": None,
                    "dpd": -2,
                    "communication_platform": "INFO_CARD",
                    "message_id": None,
                    "description": None,
                    "criteria": None,
                    "template_code": "jturbo_card_t-2",
                    "moengage_template_code": None,
                    "ptp": None,
                    "is_active": True,
                    "product": "jstarter",
                    "type": None,
                    "attempts": None,
                    "time_sent": None,
                    "call_hours": [],
                    "function_name": [],
                    "is_automated": True,
                    "time_out_duration": 3,
                    "heading_title": None,
                    "subject": None,
                    "pre_header": None,
                    "exclude_risky_customer": False,
                    "extra_conditions": None,
                    "dpd_lower": None,
                    "dpd_upper": None,
                    "until_paid": False,
                    "expiration_option": None,
                    "expiry_period": None,
                    "expiry_period_unit": None,
                    "show_in_web": True,
                    "show_in_android": True,
                    "partner_id": None,
                    "partner_selection_list": [],
                    "partner_selection_action": None,
                },
                "streamlined_message": {
                    "message_content": "Angsuran Rp {{card_due_amount}} jatuh tempo dalam 2 hari. Bayar sekarang dan dapatkan cashback untuk pembayaran lebih awal.",
                    "parameter": [None],
                    "info_card_property_id": None,
                },
                "infocard_property": {
                    "card_type": "1",
                    "card_action": None,
                    "card_destination": None,
                    "card_order_number": 1,
                    "title": "Bayar sekarang, raih cashbacknya!",
                    "title_color": "#ffffff",
                    "text_color": "#ffffff",
                },
                "infocard_button_property": [
                    {
                        "info_card_property_id": None,
                        "button_name": "R.BUTTON",
                        "text": "Bayar Sekarang",
                        "text_color": "#ffffff",
                        "action_type": "app_deeplink",
                        "destination": "howtopay",
                    }
                ],
                "image": [
                    {
                        "image_source": 111,
                        "image_type": "CARD_BACKGROUND_IMAGE",
                        "url": "info-card/CARD_BACKGROUND_IMAGE_111.png",
                        "thumbnail_url": "",
                        "service": "oss",
                        "image_status": 0,
                        "image": "",
                    },
                    {
                        "image_source": 111,
                        "image_type": "CARD_OPTIONAL_IMAGE",
                        "url": "info-card/CARD_OPTIONAL_IMAGE_111.png",
                        "thumbnail_url": "",
                        "service": "oss",
                        "image_status": 0,
                        "image": "",
                    },
                ],
            },
            {
                "streamlined_communication": {
                    "status_code_id": None,
                    "status": None,
                    "dpd": -1,
                    "communication_platform": "INFO_CARD",
                    "message_id": None,
                    "description": None,
                    "criteria": None,
                    "template_code": "jturbo_card_t-1",
                    "moengage_template_code": None,
                    "ptp": None,
                    "is_active": True,
                    "product": "jstarter",
                    "type": None,
                    "attempts": None,
                    "time_sent": None,
                    "call_hours": [],
                    "function_name": [],
                    "is_automated": True,
                    "time_out_duration": 3,
                    "heading_title": None,
                    "subject": None,
                    "pre_header": None,
                    "exclude_risky_customer": False,
                    "extra_conditions": None,
                    "dpd_lower": None,
                    "dpd_upper": None,
                    "until_paid": False,
                    "expiration_option": None,
                    "expiry_period": None,
                    "expiry_period_unit": None,
                    "show_in_web": True,
                    "show_in_android": True,
                    "partner_id": None,
                    "partner_selection_list": [],
                    "partner_selection_action": None,
                },
                "streamlined_message": {
                    "message_content": "Angsuran Rp {{card_due_amount}} jatuh tempo pada {{card_due_date}}. Jangan lupa bayar supaya dapat terus bertransaksi dengan JULO.",
                    "parameter": ["card_due_date", "card_due_amount", "card_due_amount"],
                    "info_card_property_id": None,
                },
                "infocard_property": {
                    "card_type": "1",
                    "card_action": None,
                    "card_destination": None,
                    "card_order_number": 1,
                    "title": "Angsuran jatuh tempo besok",
                    "title_color": "#ffffff",
                    "text_color": "#ffffff",
                },
                "infocard_button_property": [
                    {
                        "info_card_property_id": None,
                        "button_name": "R.BUTTON",
                        "text": "Bayar Sekarang",
                        "text_color": "#ffffff",
                        "action_type": "app_deeplink",
                        "destination": "howtopay",
                    }
                ],
                "image": [
                    {
                        "image_source": 112,
                        "image_type": "CARD_BACKGROUND_IMAGE",
                        "url": "info-card/CARD_BACKGROUND_IMAGE_112.png",
                        "thumbnail_url": "",
                        "service": "oss",
                        "image_status": 0,
                        "image": "",
                    },
                    {
                        "image_source": 112,
                        "image_type": "CARD_OPTIONAL_IMAGE",
                        "url": "info-card/CARD_OPTIONAL_IMAGE_112.png",
                        "thumbnail_url": "",
                        "service": "oss",
                        "image_status": 0,
                        "image": "",
                    },
                ],
            },
            {
                "streamlined_communication": {
                    "status_code_id": None,
                    "status": None,
                    "dpd": 0,
                    "communication_platform": "INFO_CARD",
                    "message_id": None,
                    "description": None,
                    "criteria": None,
                    "template_code": "jturbo_card_t0",
                    "moengage_template_code": None,
                    "ptp": None,
                    "is_active": True,
                    "product": "jstarter",
                    "type": None,
                    "attempts": None,
                    "time_sent": None,
                    "call_hours": [],
                    "function_name": [],
                    "is_automated": True,
                    "time_out_duration": 3,
                    "heading_title": None,
                    "subject": None,
                    "pre_header": None,
                    "exclude_risky_customer": False,
                    "extra_conditions": None,
                    "dpd_lower": None,
                    "dpd_upper": None,
                    "until_paid": False,
                    "expiration_option": None,
                    "expiry_period": None,
                    "expiry_period_unit": None,
                    "show_in_web": True,
                    "show_in_android": True,
                    "partner_id": None,
                    "partner_selection_list": [],
                    "partner_selection_action": None,
                },
                "streamlined_message": {
                    "message_content": "Bayar tagihanmu Rp {{card_due_amount}} sekarang agar tidak kena denda.",
                    "parameter": [None],
                    "info_card_property_id": None,
                },
                "infocard_property": {
                    "card_type": "1",
                    "card_action": None,
                    "card_destination": None,
                    "card_order_number": 1,
                    "title": "Tagihanmu Jatuh Tempo HARI INI!",
                    "title_color": "#ffffff",
                    "text_color": "#ffffff",
                },
                "infocard_button_property": [
                    {
                        "info_card_property_id": None,
                        "button_name": "R.BUTTON",
                        "text": "Bayar Sekarang",
                        "text_color": "#ffffff",
                        "action_type": "app_deeplink",
                        "destination": "loan_activity",
                    }
                ],
                "image": [
                    {
                        "image_source": 113,
                        "image_type": "CARD_BACKGROUND_IMAGE",
                        "url": "info-card/CARD_BACKGROUND_IMAGE_113.png",
                        "thumbnail_url": "",
                        "service": "oss",
                        "image_status": 0,
                        "image": "",
                    },
                    {
                        "image_source": 113,
                        "image_type": "CARD_OPTIONAL_IMAGE",
                        "url": "info-card/CARD_OPTIONAL_IMAGE_113.png",
                        "thumbnail_url": "",
                        "service": "oss",
                        "image_status": 0,
                        "image": "",
                    },
                ],
            },
            {
                "streamlined_communication": {
                    "status_code_id": None,
                    "status": None,
                    "dpd": 1,
                    "communication_platform": "INFO_CARD",
                    "message_id": None,
                    "description": None,
                    "criteria": None,
                    "template_code": "jturbo_card_t1",
                    "moengage_template_code": None,
                    "ptp": None,
                    "is_active": True,
                    "product": "jstarter",
                    "type": None,
                    "attempts": None,
                    "time_sent": None,
                    "call_hours": [],
                    "function_name": [],
                    "is_automated": True,
                    "time_out_duration": 3,
                    "heading_title": None,
                    "subject": None,
                    "pre_header": None,
                    "exclude_risky_customer": False,
                    "extra_conditions": None,
                    "dpd_lower": None,
                    "dpd_upper": None,
                    "until_paid": False,
                    "expiration_option": None,
                    "expiry_period": None,
                    "expiry_period_unit": None,
                    "show_in_web": True,
                    "show_in_android": True,
                    "partner_id": None,
                    "partner_selection_list": [],
                    "partner_selection_action": None,
                },
                "streamlined_message": {
                    "message_content": "Segera bayar tagihanmu Rp {{card_due_amount}} agar dapat bertransaksi lagi dengan akunmu.",
                    "parameter": [None],
                    "info_card_property_id": None,
                },
                "infocard_property": {
                    "card_type": "1",
                    "card_action": None,
                    "card_destination": None,
                    "card_order_number": 1,
                    "title": "Kamu Terlambat Bayar Tagihan 1 Hari",
                    "title_color": "#f69539",
                    "text_color": "#f69539",
                },
                "infocard_button_property": [
                    {
                        "info_card_property_id": None,
                        "button_name": "R.BUTTON",
                        "text": "Bayar Sekarang",
                        "text_color": "#ffffff",
                        "action_type": "app_deeplink",
                        "destination": "loan_activity",
                    }
                ],
                "image": [
                    {
                        "image_source": 114,
                        "image_type": "CARD_OPTIONAL_IMAGE",
                        "url": "info-card/CARD_OPTIONAL_IMAGE_114_29122022190941.png",
                        "thumbnail_url": "",
                        "service": "oss",
                        "image_status": 0,
                        "image": "",
                    },
                    {
                        "image_source": 114,
                        "image_type": "CARD_BACKGROUND_IMAGE",
                        "url": "info-card/CARD_BACKGROUND_IMAGE_114_29122022190941.png",
                        "thumbnail_url": "",
                        "service": "oss",
                        "image_status": 0,
                        "image": "",
                    },
                    {
                        "image_source": 114,
                        "image_type": "BUTTON_IMAGE",
                        "url": "info-card/inapp_button.png",
                        "thumbnail_url": "",
                        "service": "oss",
                        "image_status": 0,
                        "image": "",
                    },
                ],
            },
            {
                "streamlined_communication": {
                    "status_code_id": None,
                    "status": None,
                    "dpd": 2,
                    "communication_platform": "INFO_CARD",
                    "message_id": None,
                    "description": None,
                    "criteria": None,
                    "template_code": "jturbo_card_t2",
                    "moengage_template_code": None,
                    "ptp": None,
                    "is_active": True,
                    "product": "jstarter",
                    "type": None,
                    "attempts": None,
                    "time_sent": None,
                    "call_hours": [],
                    "function_name": [],
                    "is_automated": True,
                    "time_out_duration": 3,
                    "heading_title": None,
                    "subject": None,
                    "pre_header": None,
                    "exclude_risky_customer": False,
                    "extra_conditions": None,
                    "dpd_lower": None,
                    "dpd_upper": None,
                    "until_paid": False,
                    "expiration_option": None,
                    "expiry_period": None,
                    "expiry_period_unit": None,
                    "show_in_web": True,
                    "show_in_android": True,
                    "partner_id": None,
                    "partner_selection_list": [],
                    "partner_selection_action": None,
                },
                "streamlined_message": {
                    "message_content": "Akunmu diblokir sampai kamu membayar tagihanmu Rp {{card_due_amount}}.",
                    "parameter": [None],
                    "info_card_property_id": None,
                },
                "infocard_property": {
                    "card_type": "1",
                    "card_action": None,
                    "card_destination": None,
                    "card_order_number": 1,
                    "title": "Bayar Tagihanmu, Sudah Telat 2 Hari",
                    "title_color": "#f69539",
                    "text_color": "#f69539",
                },
                "infocard_button_property": [
                    {
                        "info_card_property_id": None,
                        "button_name": "R.BUTTON",
                        "text": "Bayar Sekarang",
                        "text_color": "#ffffff",
                        "action_type": "app_deeplink",
                        "destination": "loan_activity",
                    }
                ],
                "image": [
                    {
                        "image_source": 115,
                        "image_type": "CARD_OPTIONAL_IMAGE",
                        "url": "info-card/CARD_OPTIONAL_IMAGE_115_29122022191524.png",
                        "thumbnail_url": "",
                        "service": "oss",
                        "image_status": 0,
                        "image": "",
                    },
                    {
                        "image_source": 115,
                        "image_type": "CARD_BACKGROUND_IMAGE",
                        "url": "info-card/CARD_BACKGROUND_IMAGE_115_29122022191524.png",
                        "thumbnail_url": "",
                        "service": "oss",
                        "image_status": 0,
                        "image": "",
                    },
                    {
                        "image_source": 115,
                        "image_type": "BUTTON_IMAGE",
                        "url": "info-card/R_BUTTON_IMAGE_WEB190.png",
                        "thumbnail_url": "",
                        "service": "oss",
                        "image_status": 0,
                        "image": "",
                    },
                ],
            },
            {
                "streamlined_communication": {
                    "status_code_id": None,
                    "status": None,
                    "dpd": 3,
                    "communication_platform": "INFO_CARD",
                    "message_id": None,
                    "description": None,
                    "criteria": None,
                    "template_code": "jturbo_card_t3",
                    "moengage_template_code": None,
                    "ptp": None,
                    "is_active": True,
                    "product": "jstarter",
                    "type": None,
                    "attempts": None,
                    "time_sent": None,
                    "call_hours": [],
                    "function_name": [],
                    "is_automated": True,
                    "time_out_duration": 3,
                    "heading_title": None,
                    "subject": None,
                    "pre_header": None,
                    "exclude_risky_customer": False,
                    "extra_conditions": None,
                    "dpd_lower": None,
                    "dpd_upper": None,
                    "until_paid": False,
                    "expiration_option": None,
                    "expiry_period": None,
                    "expiry_period_unit": None,
                    "show_in_web": True,
                    "show_in_android": True,
                    "partner_id": None,
                    "partner_selection_list": [],
                    "partner_selection_action": None,
                },
                "streamlined_message": {
                    "message_content": "Bayar sekarang Rp {{card_due_amount}}. Makin telat bayar, makin besar denda keterlambatanmu. ",
                    "parameter": [None],
                    "info_card_property_id": None,
                },
                "infocard_property": {
                    "card_type": "1",
                    "card_action": None,
                    "card_destination": None,
                    "card_order_number": 1,
                    "title": "Sudah Telat 3 Hari, Bayar Tagihanmu",
                    "title_color": "#f69539",
                    "text_color": "#f69539",
                },
                "infocard_button_property": [
                    {
                        "info_card_property_id": None,
                        "button_name": "R.BUTTON",
                        "text": "Bayar Sekarang",
                        "text_color": "#ffffff",
                        "action_type": "app_deeplink",
                        "destination": "loan_activity",
                    }
                ],
                "image": [
                    {
                        "image_source": 116,
                        "image_type": "CARD_OPTIONAL_IMAGE",
                        "url": "info-card/CARD_OPTIONAL_IMAGE_116_29122022191914.png",
                        "thumbnail_url": "",
                        "service": "oss",
                        "image_status": 0,
                        "image": "",
                    },
                    {
                        "image_source": 116,
                        "image_type": "CARD_BACKGROUND_IMAGE",
                        "url": "info-card/CARD_BACKGROUND_IMAGE_116_29122022191914.png",
                        "thumbnail_url": "",
                        "service": "oss",
                        "image_status": 0,
                        "image": "",
                    },
                ],
            },
            {
                "streamlined_communication": {
                    "status_code_id": None,
                    "status": None,
                    "dpd": 4,
                    "communication_platform": "INFO_CARD",
                    "message_id": None,
                    "description": None,
                    "criteria": None,
                    "template_code": "jturbo_card_t4",
                    "moengage_template_code": None,
                    "ptp": None,
                    "is_active": True,
                    "product": "jstarter",
                    "type": None,
                    "attempts": None,
                    "time_sent": None,
                    "call_hours": [],
                    "function_name": [],
                    "is_automated": True,
                    "time_out_duration": 3,
                    "heading_title": None,
                    "subject": None,
                    "pre_header": None,
                    "exclude_risky_customer": False,
                    "extra_conditions": None,
                    "dpd_lower": None,
                    "dpd_upper": None,
                    "until_paid": False,
                    "expiration_option": None,
                    "expiry_period": None,
                    "expiry_period_unit": None,
                    "show_in_web": True,
                    "show_in_android": True,
                    "partner_id": None,
                    "partner_selection_list": [],
                    "partner_selection_action": None,
                },
                "streamlined_message": {
                    "message_content": "Kamu sudah terlambat 4 hari. Akunmu kami blokir sampai kamu bayar Rp {{card_due_amount}}.",
                    "parameter": [None],
                    "info_card_property_id": None,
                },
                "infocard_property": {
                    "card_type": "1",
                    "card_action": None,
                    "card_destination": None,
                    "card_order_number": 1,
                    "title": "Bayar Tagihanmu Sekarang",
                    "title_color": "#f69539",
                    "text_color": "#f69539",
                },
                "infocard_button_property": [
                    {
                        "info_card_property_id": None,
                        "button_name": "R.BUTTON",
                        "text": "Bayar Sekarang",
                        "text_color": "#ffffff",
                        "action_type": "app_deeplink",
                        "destination": "loan_activity",
                    }
                ],
                "image": [
                    {
                        "image_source": 117,
                        "image_type": "CARD_OPTIONAL_IMAGE",
                        "url": "info-card/CARD_OPTIONAL_IMAGE_117_29122022192158.png",
                        "thumbnail_url": "",
                        "service": "oss",
                        "image_status": 0,
                        "image": "",
                    },
                    {
                        "image_source": 117,
                        "image_type": "CARD_BACKGROUND_IMAGE",
                        "url": "info-card/CARD_BACKGROUND_IMAGE_117_29122022192158.png",
                        "thumbnail_url": "",
                        "service": "oss",
                        "image_status": 0,
                        "image": "",
                    },
                ],
            },
            {
                "streamlined_communication": {
                    "status_code_id": None,
                    "status": None,
                    "dpd": 5,
                    "communication_platform": "INFO_CARD",
                    "message_id": None,
                    "description": None,
                    "criteria": None,
                    "template_code": "jturbo_card_t5",
                    "moengage_template_code": None,
                    "ptp": None,
                    "is_active": True,
                    "product": "jstarter",
                    "type": None,
                    "attempts": None,
                    "time_sent": None,
                    "call_hours": [],
                    "function_name": [],
                    "is_automated": True,
                    "time_out_duration": 3,
                    "heading_title": None,
                    "subject": None,
                    "pre_header": None,
                    "exclude_risky_customer": False,
                    "extra_conditions": None,
                    "dpd_lower": None,
                    "dpd_upper": None,
                    "until_paid": False,
                    "expiration_option": None,
                    "expiry_period": None,
                    "expiry_period_unit": None,
                    "show_in_web": True,
                    "show_in_android": True,
                    "partner_id": None,
                    "partner_selection_list": [],
                    "partner_selection_action": None,
                },
                "streamlined_message": {
                    "message_content": "Bayar sekarang Rp {{card_due_amount}}. Denda keterlambatan akan memperbesar tagihanmu.",
                    "parameter": [None],
                    "info_card_property_id": None,
                },
                "infocard_property": {
                    "card_type": "1",
                    "card_action": None,
                    "card_destination": None,
                    "card_order_number": 1,
                    "title": "Bayar Tagihanmu, Sudah Telat 5 Hari",
                    "title_color": "#f69539",
                    "text_color": "#f69539",
                },
                "infocard_button_property": [
                    {
                        "info_card_property_id": None,
                        "button_name": "R.BUTTON",
                        "text": "Bayar Sekarang",
                        "text_color": "#ffffff",
                        "action_type": "app_deeplink",
                        "destination": "loan_activity",
                    }
                ],
                "image": [
                    {
                        "image_source": 118,
                        "image_type": "CARD_OPTIONAL_IMAGE",
                        "url": "info-card/CARD_OPTIONAL_IMAGE_118_29122022192450.png",
                        "thumbnail_url": "",
                        "service": "oss",
                        "image_status": 0,
                        "image": "",
                    },
                    {
                        "image_source": 118,
                        "image_type": "CARD_BACKGROUND_IMAGE",
                        "url": "info-card/CARD_BACKGROUND_IMAGE_118_29122022192450.png",
                        "thumbnail_url": "",
                        "service": "oss",
                        "image_status": 0,
                        "image": "",
                    },
                ],
            },
            {
                "streamlined_communication": {
                    "status_code_id": None,
                    "status": None,
                    "dpd": 6,
                    "communication_platform": "INFO_CARD",
                    "message_id": None,
                    "description": None,
                    "criteria": None,
                    "template_code": "jturbo_card_t6",
                    "moengage_template_code": None,
                    "ptp": None,
                    "is_active": True,
                    "product": "jstarter",
                    "type": None,
                    "attempts": None,
                    "time_sent": None,
                    "call_hours": [],
                    "function_name": [],
                    "is_automated": True,
                    "time_out_duration": 3,
                    "heading_title": None,
                    "subject": None,
                    "pre_header": None,
                    "exclude_risky_customer": False,
                    "extra_conditions": None,
                    "dpd_lower": None,
                    "dpd_upper": None,
                    "until_paid": False,
                    "expiration_option": None,
                    "expiry_period": None,
                    "expiry_period_unit": None,
                    "show_in_web": True,
                    "show_in_android": True,
                    "partner_id": None,
                    "partner_selection_list": [],
                    "partner_selection_action": None,
                },
                "streamlined_message": {
                    "message_content": "Angsuran Rp {{card_due_amount}} jatuh tempo pada {{card_due_date}} dan terlambat {{card_dpd}} hari.",
                    "parameter": [
                        "card_due_date",
                        "card_due_amount",
                        "card_due_amount",
                        "card_dpd",
                    ],
                    "info_card_property_id": None,
                },
                "infocard_property": {
                    "card_type": "1",
                    "card_action": None,
                    "card_destination": None,
                    "card_order_number": 1,
                    "title": "Bayar untuk dapat bertransaksi",
                    "title_color": "#f69539",
                    "text_color": "#f69539",
                },
                "infocard_button_property": [
                    {
                        "info_card_property_id": None,
                        "button_name": "R.BUTTON",
                        "text": "Bayar Sekarang",
                        "text_color": "#ffffff",
                        "action_type": "app_deeplink",
                        "destination": "howtopay",
                    }
                ],
                "image": [
                    {
                        "image_source": 119,
                        "image_type": "CARD_BACKGROUND_IMAGE",
                        "url": "info-card/CARD_BACKGROUND_IMAGE_119.png",
                        "thumbnail_url": "",
                        "service": "oss",
                        "image_status": 0,
                        "image": "",
                    },
                    {
                        "image_source": 119,
                        "image_type": "CARD_OPTIONAL_IMAGE",
                        "url": "info-card/CARD_OPTIONAL_IMAGE_119.png",
                        "thumbnail_url": "",
                        "service": "oss",
                        "image_status": 0,
                        "image": "",
                    },
                    {
                        "image_source": 119,
                        "image_type": "BUTTON_IMAGE",
                        "url": "info-card/rectangle_1489.png",
                        "thumbnail_url": "",
                        "service": "oss",
                        "image_status": 0,
                        "image": "",
                    },
                ],
            },
            {
                "streamlined_communication": {
                    "status_code_id": None,
                    "status": None,
                    "dpd": 7,
                    "communication_platform": "INFO_CARD",
                    "message_id": None,
                    "description": None,
                    "criteria": None,
                    "template_code": "jturbo_card_t7",
                    "moengage_template_code": None,
                    "ptp": None,
                    "is_active": True,
                    "product": "jstarter",
                    "type": None,
                    "attempts": None,
                    "time_sent": None,
                    "call_hours": [],
                    "function_name": [],
                    "is_automated": True,
                    "time_out_duration": 3,
                    "heading_title": None,
                    "subject": None,
                    "pre_header": None,
                    "exclude_risky_customer": False,
                    "extra_conditions": None,
                    "dpd_lower": None,
                    "dpd_upper": None,
                    "until_paid": False,
                    "expiration_option": None,
                    "expiry_period": None,
                    "expiry_period_unit": None,
                    "show_in_web": True,
                    "show_in_android": True,
                    "partner_id": None,
                    "partner_selection_list": [],
                    "partner_selection_action": None,
                },
                "streamlined_message": {
                    "message_content": "Angsuran Rp {{card_due_amount}} jatuh tempo pada {{card_due_date}} dan terlambat {{card_dpd}} hari.",
                    "parameter": [
                        "card_due_date",
                        "card_due_amount",
                        "card_due_amount",
                        "card_dpd",
                    ],
                    "info_card_property_id": None,
                },
                "infocard_property": {
                    "card_type": "1",
                    "card_action": None,
                    "card_destination": None,
                    "card_order_number": 1,
                    "title": "Bayar untuk dapat bertransaksi",
                    "title_color": "#f69539",
                    "text_color": "#f69539",
                },
                "infocard_button_property": [
                    {
                        "info_card_property_id": None,
                        "button_name": "R.BUTTON",
                        "text": "Bayar Sekarang",
                        "text_color": "#ffffff",
                        "action_type": "app_deeplink",
                        "destination": "howtopay",
                    }
                ],
                "image": [
                    {
                        "image_source": 120,
                        "image_type": "CARD_BACKGROUND_IMAGE",
                        "url": "info-card/CARD_BACKGROUND_IMAGE_120.png",
                        "thumbnail_url": "",
                        "service": "oss",
                        "image_status": 0,
                        "image": "",
                    },
                    {
                        "image_source": 120,
                        "image_type": "CARD_OPTIONAL_IMAGE",
                        "url": "info-card/CARD_OPTIONAL_IMAGE_120.png",
                        "thumbnail_url": "",
                        "service": "oss",
                        "image_status": 0,
                        "image": "",
                    },
                    {
                        "image_source": 120,
                        "image_type": "BUTTON_IMAGE",
                        "url": "info-card/rectangle_1489.png",
                        "thumbnail_url": "",
                        "service": "oss",
                        "image_status": 0,
                        "image": "",
                    },
                ],
            },
            {
                "streamlined_communication": {
                    "status_code_id": None,
                    "status": None,
                    "dpd": 8,
                    "communication_platform": "INFO_CARD",
                    "message_id": None,
                    "description": None,
                    "criteria": None,
                    "template_code": "jturbo_card_t8",
                    "moengage_template_code": None,
                    "ptp": None,
                    "is_active": True,
                    "product": "jstarter",
                    "type": None,
                    "attempts": None,
                    "time_sent": None,
                    "call_hours": [],
                    "function_name": [],
                    "is_automated": True,
                    "time_out_duration": 3,
                    "heading_title": None,
                    "subject": None,
                    "pre_header": None,
                    "exclude_risky_customer": False,
                    "extra_conditions": None,
                    "dpd_lower": None,
                    "dpd_upper": None,
                    "until_paid": False,
                    "expiration_option": None,
                    "expiry_period": None,
                    "expiry_period_unit": None,
                    "show_in_web": True,
                    "show_in_android": True,
                    "partner_id": None,
                    "partner_selection_list": [],
                    "partner_selection_action": None,
                },
                "streamlined_message": {
                    "message_content": "Angsuran Rp {{card_due_amount}} jatuh tempo pada {{card_due_date}} dan terlambat {{card_dpd}} hari.",
                    "parameter": [
                        "card_due_date",
                        "card_due_amount",
                        "card_due_amount",
                        "card_dpd",
                    ],
                    "info_card_property_id": None,
                },
                "infocard_property": {
                    "card_type": "1",
                    "card_action": None,
                    "card_destination": None,
                    "card_order_number": 1,
                    "title": "Segera bayar angsuran ⚠️",
                    "title_color": "#f69539",
                    "text_color": "#f69539",
                },
                "infocard_button_property": [
                    {
                        "info_card_property_id": None,
                        "button_name": "R.BUTTON",
                        "text": "Bayar Sekarang",
                        "text_color": "#ffffff",
                        "action_type": "app_deeplink",
                        "destination": "howtopay",
                    }
                ],
                "image": [
                    {
                        "image_source": 121,
                        "image_type": "CARD_BACKGROUND_IMAGE",
                        "url": "info-card/CARD_BACKGROUND_IMAGE_121.png",
                        "thumbnail_url": "",
                        "service": "oss",
                        "image_status": 0,
                        "image": "",
                    },
                    {
                        "image_source": 121,
                        "image_type": "CARD_OPTIONAL_IMAGE",
                        "url": "info-card/CARD_OPTIONAL_IMAGE_121.png",
                        "thumbnail_url": "",
                        "service": "oss",
                        "image_status": 0,
                        "image": "",
                    },
                ],
            },
            {
                "streamlined_communication": {
                    "status_code_id": None,
                    "status": None,
                    "dpd": 9,
                    "communication_platform": "INFO_CARD",
                    "message_id": None,
                    "description": None,
                    "criteria": None,
                    "template_code": "jturbo_card_t9",
                    "moengage_template_code": None,
                    "ptp": None,
                    "is_active": True,
                    "product": "jstarter",
                    "type": None,
                    "attempts": None,
                    "time_sent": None,
                    "call_hours": [],
                    "function_name": [],
                    "is_automated": True,
                    "time_out_duration": 3,
                    "heading_title": None,
                    "subject": None,
                    "pre_header": None,
                    "exclude_risky_customer": False,
                    "extra_conditions": None,
                    "dpd_lower": None,
                    "dpd_upper": None,
                    "until_paid": False,
                    "expiration_option": None,
                    "expiry_period": None,
                    "expiry_period_unit": None,
                    "show_in_web": True,
                    "show_in_android": True,
                    "partner_id": None,
                    "partner_selection_list": [],
                    "partner_selection_action": None,
                },
                "streamlined_message": {
                    "message_content": "Angsuran Rp {{card_due_amount}} jatuh tempo pada {{card_due_date}} dan terlambat {{card_dpd}} hari.",
                    "parameter": [
                        "card_due_date",
                        "card_due_amount",
                        "card_due_amount",
                        "card_dpd",
                    ],
                    "info_card_property_id": None,
                },
                "infocard_property": {
                    "card_type": "1",
                    "card_action": None,
                    "card_destination": None,
                    "card_order_number": 1,
                    "title": "Segera bayar angsuran ⚠️",
                    "title_color": "#f69539",
                    "text_color": "#f69539",
                },
                "infocard_button_property": [
                    {
                        "info_card_property_id": None,
                        "button_name": "R.BUTTON",
                        "text": "Bayar Sekarang",
                        "text_color": "#ffffff",
                        "action_type": "app_deeplink",
                        "destination": "howtopay",
                    }
                ],
                "image": [
                    {
                        "image_source": 122,
                        "image_type": "CARD_BACKGROUND_IMAGE",
                        "url": "info-card/CARD_BACKGROUND_IMAGE_122.png",
                        "thumbnail_url": "",
                        "service": "oss",
                        "image_status": 0,
                        "image": "",
                    },
                    {
                        "image_source": 122,
                        "image_type": "CARD_OPTIONAL_IMAGE",
                        "url": "info-card/CARD_OPTIONAL_IMAGE_122.png",
                        "thumbnail_url": "",
                        "service": "oss",
                        "image_status": 0,
                        "image": "",
                    },
                    {
                        "image_source": 122,
                        "image_type": "BUTTON_IMAGE",
                        "url": "info-card/R_BUTTON_IMAGE_WEB190.png",
                        "thumbnail_url": "",
                        "service": "oss",
                        "image_status": 0,
                        "image": "",
                    },
                ],
            },
            {
                "streamlined_communication": {
                    "status_code_id": None,
                    "status": None,
                    "dpd": 10,
                    "communication_platform": "INFO_CARD",
                    "message_id": None,
                    "description": None,
                    "criteria": None,
                    "template_code": "jturbo_card_t10",
                    "moengage_template_code": None,
                    "ptp": None,
                    "is_active": True,
                    "product": "jstarter",
                    "type": None,
                    "attempts": None,
                    "time_sent": None,
                    "call_hours": [],
                    "function_name": [],
                    "is_automated": True,
                    "time_out_duration": 3,
                    "heading_title": None,
                    "subject": None,
                    "pre_header": None,
                    "exclude_risky_customer": False,
                    "extra_conditions": None,
                    "dpd_lower": None,
                    "dpd_upper": None,
                    "until_paid": False,
                    "expiration_option": None,
                    "expiry_period": None,
                    "expiry_period_unit": None,
                    "show_in_web": True,
                    "show_in_android": True,
                    "partner_id": None,
                    "partner_selection_list": [],
                    "partner_selection_action": None,
                },
                "streamlined_message": {
                    "message_content": "Angsuran Rp {{card_due_amount}} jatuh tempo pada {{card_due_date}} dan terlambat {{card_dpd}} hari.",
                    "parameter": [
                        "card_due_date",
                        "card_due_amount",
                        "card_due_amount",
                        "card_dpd",
                    ],
                    "info_card_property_id": None,
                },
                "infocard_property": {
                    "card_type": "1",
                    "card_action": None,
                    "card_destination": None,
                    "card_order_number": 1,
                    "title": "Hindari denda bertambah ⚠️",
                    "title_color": "#f69539",
                    "text_color": "#f69539",
                },
                "infocard_button_property": [
                    {
                        "info_card_property_id": None,
                        "button_name": "R.BUTTON",
                        "text": "Bayar Sekarang",
                        "text_color": "#ffffff",
                        "action_type": "app_deeplink",
                        "destination": "howtopay",
                    }
                ],
                "image": [
                    {
                        "image_source": 123,
                        "image_type": "CARD_BACKGROUND_IMAGE",
                        "url": "info-card/CARD_BACKGROUND_IMAGE_123.png",
                        "thumbnail_url": "",
                        "service": "oss",
                        "image_status": 0,
                        "image": "",
                    },
                    {
                        "image_source": 123,
                        "image_type": "CARD_OPTIONAL_IMAGE",
                        "url": "info-card/CARD_OPTIONAL_IMAGE_123.png",
                        "thumbnail_url": "",
                        "service": "oss",
                        "image_status": 0,
                        "image": "",
                    },
                    {
                        "image_source": 123,
                        "image_type": "BUTTON_IMAGE",
                        "url": "info-card/R_BUTTON_IMAGE_WEB190.png",
                        "thumbnail_url": "",
                        "service": "oss",
                        "image_status": 0,
                        "image": "",
                    },
                ],
            },
            {
                "streamlined_communication": {
                    "status_code_id": None,
                    "status": None,
                    "dpd": None,
                    "communication_platform": "INFO_CARD",
                    "message_id": None,
                    "description": None,
                    "criteria": None,
                    "template_code": "jturbo_card_t11-40",
                    "moengage_template_code": None,
                    "ptp": None,
                    "is_active": True,
                    "product": "jstarter",
                    "type": None,
                    "attempts": None,
                    "time_sent": None,
                    "call_hours": [],
                    "function_name": [],
                    "is_automated": True,
                    "time_out_duration": 3,
                    "heading_title": None,
                    "subject": None,
                    "pre_header": None,
                    "exclude_risky_customer": False,
                    "extra_conditions": None,
                    "dpd_lower": 11,
                    "dpd_upper": 40,
                    "until_paid": False,
                    "expiration_option": None,
                    "expiry_period": None,
                    "expiry_period_unit": None,
                    "show_in_web": True,
                    "show_in_android": True,
                    "partner_id": None,
                    "partner_selection_list": [],
                    "partner_selection_action": None,
                },
                "streamlined_message": {
                    "message_content": "Angsuran Rp {{card_due_amount}} jatuh tempo pada {{card_due_date}} dan terlambat {{card_dpd}} hari.",
                    "parameter": [
                        "card_due_date",
                        "card_due_amount",
                        "card_due_amount",
                        "card_dpd",
                    ],
                    "info_card_property_id": None,
                },
                "infocard_property": {
                    "card_type": "3A",
                    "card_action": None,
                    "card_destination": None,
                    "card_order_number": 1,
                    "title": "Hindari resiko denda menumpuk",
                    "title_color": "#db4d3d",
                    "text_color": "#db4d3d",
                },
                "infocard_button_property": [
                    {
                        "info_card_property_id": None,
                        "button_name": "R.BUTTON",
                        "text": "Bayar Sekarang",
                        "text_color": "#ffffff",
                        "action_type": "app_deeplink",
                        "destination": "howtopay",
                    },
                    {
                        "info_card_property_id": None,
                        "button_name": "L.BUTTON",
                        "text": "Hubungi JULO",
                        "text_color": "#db4d3d",
                        "action_type": "app_deeplink",
                        "destination": "contactus",
                    },
                ],
                "image": [
                    {
                        "image_source": 124,
                        "image_type": "CARD_OPTIONAL_IMAGE",
                        "url": "info-card/CARD_OPTIONAL_IMAGE_124.png",
                        "thumbnail_url": "",
                        "service": "oss",
                        "image_status": 0,
                        "image": "",
                    },
                    {
                        "image_source": 124,
                        "image_type": "CARD_BACKGROUND_IMAGE",
                        "url": "info-card/CARD_BACKGROUND_IMAGE_124.png",
                        "thumbnail_url": "",
                        "service": "oss",
                        "image_status": 0,
                        "image": "",
                    },
                    {
                        "image_source": 124,
                        "image_type": "BUTTON_IMAGE",
                        "url": "info-card/R_BUTTON_IMAGE_WEB190.png",
                        "thumbnail_url": "",
                        "service": "oss",
                        "image_status": 0,
                        "image": "",
                    },
                ],
            },
            {
                "streamlined_communication": {
                    "status_code_id": None,
                    "status": None,
                    "dpd": None,
                    "communication_platform": "INFO_CARD",
                    "message_id": None,
                    "description": None,
                    "criteria": None,
                    "template_code": "jturbo_card_t41-70",
                    "moengage_template_code": None,
                    "ptp": None,
                    "is_active": True,
                    "product": "jstarter",
                    "type": None,
                    "attempts": None,
                    "time_sent": None,
                    "call_hours": [],
                    "function_name": [],
                    "is_automated": True,
                    "time_out_duration": 3,
                    "heading_title": None,
                    "subject": None,
                    "pre_header": None,
                    "exclude_risky_customer": False,
                    "extra_conditions": None,
                    "dpd_lower": 41,
                    "dpd_upper": 70,
                    "until_paid": False,
                    "expiration_option": None,
                    "expiry_period": None,
                    "expiry_period_unit": None,
                    "show_in_web": True,
                    "show_in_android": True,
                    "partner_id": None,
                    "partner_selection_list": [],
                    "partner_selection_action": None,
                },
                "streamlined_message": {
                    "message_content": "Angsuran Rp {{card_due_amount}} jatuh tempo pada {{card_due_date}} dan terlambat {{card_dpd}} hari.",
                    "parameter": [
                        "card_due_date",
                        "card_due_amount",
                        "card_due_amount",
                        "card_dpd",
                    ],
                    "info_card_property_id": None,
                },
                "infocard_property": {
                    "card_type": "3A",
                    "card_action": None,
                    "card_destination": None,
                    "card_order_number": 1,
                    "title": "STOP tambah beban cicilan⚠️",
                    "title_color": "#db4d3d",
                    "text_color": "#db4d3d",
                },
                "infocard_button_property": [
                    {
                        "info_card_property_id": None,
                        "button_name": "R.BUTTON",
                        "text": "Bayar Sekarang",
                        "text_color": "#ffffff",
                        "action_type": "app_deeplink",
                        "destination": "howtopay",
                    },
                    {
                        "info_card_property_id": None,
                        "button_name": "L.BUTTON",
                        "text": "Hubungi JULO",
                        "text_color": "#db4d3d",
                        "action_type": "app_deeplink",
                        "destination": "contactus",
                    },
                ],
                "image": [
                    {
                        "image_source": 125,
                        "image_type": "CARD_BACKGROUND_IMAGE",
                        "url": "info-card/CARD_BACKGROUND_IMAGE_125.png",
                        "thumbnail_url": "",
                        "service": "oss",
                        "image_status": 0,
                        "image": "",
                    },
                    {
                        "image_source": 125,
                        "image_type": "CARD_OPTIONAL_IMAGE",
                        "url": "info-card/CARD_OPTIONAL_IMAGE_125.png",
                        "thumbnail_url": "",
                        "service": "oss",
                        "image_status": 0,
                        "image": "",
                    },
                    {
                        "image_source": 125,
                        "image_type": "BUTTON_IMAGE",
                        "url": "info-card/R_BUTTON_IMAGE_WEB190.png",
                        "thumbnail_url": "",
                        "service": "oss",
                        "image_status": 0,
                        "image": "",
                    },
                ],
            },
            {
                "streamlined_communication": {
                    "status_code_id": None,
                    "status": None,
                    "dpd": None,
                    "communication_platform": "INFO_CARD",
                    "message_id": None,
                    "description": None,
                    "criteria": None,
                    "template_code": "jturbo_card_t71-90",
                    "moengage_template_code": None,
                    "ptp": None,
                    "is_active": True,
                    "product": "jstarter",
                    "type": None,
                    "attempts": None,
                    "time_sent": None,
                    "call_hours": [],
                    "function_name": [],
                    "is_automated": True,
                    "time_out_duration": 3,
                    "heading_title": None,
                    "subject": None,
                    "pre_header": None,
                    "exclude_risky_customer": False,
                    "extra_conditions": None,
                    "dpd_lower": 71,
                    "dpd_upper": 90,
                    "until_paid": False,
                    "expiration_option": None,
                    "expiry_period": None,
                    "expiry_period_unit": None,
                    "show_in_web": True,
                    "show_in_android": True,
                    "partner_id": None,
                    "partner_selection_list": [],
                    "partner_selection_action": None,
                },
                "streamlined_message": {
                    "message_content": "Angsuran Rp {{card_due_amount}} jatuh tempo pada {{card_due_date}} dan terlambat {{card_dpd}} hari.",
                    "parameter": [None],
                    "info_card_property_id": None,
                },
                "infocard_property": {
                    "card_type": "3A",
                    "card_action": None,
                    "card_destination": None,
                    "card_order_number": 1,
                    "title": "Hindari blacklist AFPI ⚠️",
                    "title_color": "#db4d3d",
                    "text_color": "#db4d3d",
                },
                "infocard_button_property": [
                    {
                        "info_card_property_id": None,
                        "button_name": "R.BUTTON",
                        "text": "Bayar Sekarang",
                        "text_color": "#ffffff",
                        "action_type": "app_deeplink",
                        "destination": "howtopay",
                    },
                    {
                        "info_card_property_id": None,
                        "button_name": "L.BUTTON",
                        "text": "Hubungi JULO",
                        "text_color": "#db4d3d",
                        "action_type": "app_deeplink",
                        "destination": "contactus",
                    },
                ],
                "image": [
                    {
                        "image_source": 126,
                        "image_type": "CARD_BACKGROUND_IMAGE",
                        "url": "info-card/CARD_BACKGROUND_IMAGE_126.png",
                        "thumbnail_url": "",
                        "service": "oss",
                        "image_status": 0,
                        "image": "",
                    },
                    {
                        "image_source": 126,
                        "image_type": "CARD_OPTIONAL_IMAGE",
                        "url": "info-card/CARD_OPTIONAL_IMAGE_126.png",
                        "thumbnail_url": "",
                        "service": "oss",
                        "image_status": 0,
                        "image": "",
                    },
                    {
                        "image_source": 126,
                        "image_type": "BUTTON_IMAGE",
                        "url": "info-card/R_BUTTON_IMAGE_WEB190.png",
                        "thumbnail_url": "",
                        "service": "oss",
                        "image_status": 0,
                        "image": "",
                    },
                ],
            },
            {
                "streamlined_communication": {
                    "status_code_id": None,
                    "status": None,
                    "dpd": None,
                    "communication_platform": "INFO_CARD",
                    "message_id": None,
                    "description": None,
                    "criteria": None,
                    "template_code": "jturbo_card_t91",
                    "moengage_template_code": None,
                    "ptp": None,
                    "is_active": True,
                    "product": "jstarter",
                    "type": None,
                    "attempts": None,
                    "time_sent": None,
                    "call_hours": [],
                    "function_name": [],
                    "is_automated": True,
                    "time_out_duration": 3,
                    "heading_title": None,
                    "subject": None,
                    "pre_header": None,
                    "exclude_risky_customer": False,
                    "extra_conditions": None,
                    "dpd_lower": 91,
                    "dpd_upper": None,
                    "until_paid": True,
                    "expiration_option": None,
                    "expiry_period": None,
                    "expiry_period_unit": None,
                    "show_in_web": True,
                    "show_in_android": True,
                    "partner_id": None,
                    "partner_selection_list": [],
                    "partner_selection_action": None,
                },
                "streamlined_message": {
                    "message_content": "Angsuran Rp {{card_due_amount}} jatuh tempo pada {{card_due_date}} dan terlambat {{card_dpd}} hari.",
                    "parameter": [
                        "card_due_date",
                        "card_due_amount",
                        "card_due_amount",
                        "card_dpd",
                    ],
                    "info_card_property_id": None,
                },
                "infocard_property": {
                    "card_type": "3A",
                    "card_action": None,
                    "card_destination": None,
                    "card_order_number": 1,
                    "title": "Hindari resiko gagal bayar ⚠️",
                    "title_color": "#db4d3d",
                    "text_color": "#db4d3d",
                },
                "infocard_button_property": [
                    {
                        "info_card_property_id": None,
                        "button_name": "R.BUTTON",
                        "text": "Bayar Sekarang",
                        "text_color": "#ffffff",
                        "action_type": "app_deeplink",
                        "destination": "howtopay",
                    },
                    {
                        "info_card_property_id": None,
                        "button_name": "L.BUTTON",
                        "text": "Hubungi JULO",
                        "text_color": "#db4d3d",
                        "action_type": "app_deeplink",
                        "destination": "contactus",
                    },
                ],
                "image": [
                    {
                        "image_source": 127,
                        "image_type": "CARD_BACKGROUND_IMAGE",
                        "url": "info-card/CARD_BACKGROUND_IMAGE_127.png",
                        "thumbnail_url": "",
                        "service": "oss",
                        "image_status": 0,
                        "image": "",
                    },
                    {
                        "image_source": 127,
                        "image_type": "CARD_OPTIONAL_IMAGE",
                        "url": "info-card/CARD_OPTIONAL_IMAGE_127.png",
                        "thumbnail_url": "",
                        "service": "oss",
                        "image_status": 0,
                        "image": "",
                    },
                    {
                        "image_source": 127,
                        "image_type": "BUTTON_IMAGE",
                        "url": "info-card/R_BUTTON_IMAGE_WEB190.png",
                        "thumbnail_url": "",
                        "service": "oss",
                        "image_status": 0,
                        "image": "",
                    },
                ],
            },
            {
                "streamlined_communication": {
                    "status_code_id": None,
                    "status": None,
                    "dpd": None,
                    "communication_platform": "INFO_CARD",
                    "message_id": None,
                    "description": None,
                    "criteria": None,
                    "template_code": "jturbo_card_t-10_t-3",
                    "moengage_template_code": None,
                    "ptp": None,
                    "is_active": True,
                    "product": "jstarter",
                    "type": None,
                    "attempts": None,
                    "time_sent": None,
                    "call_hours": [],
                    "function_name": [],
                    "is_automated": True,
                    "time_out_duration": 3,
                    "heading_title": None,
                    "subject": None,
                    "pre_header": None,
                    "exclude_risky_customer": False,
                    "extra_conditions": None,
                    "dpd_lower": -10,
                    "dpd_upper": -3,
                    "until_paid": False,
                    "expiration_option": None,
                    "expiry_period": None,
                    "expiry_period_unit": None,
                    "show_in_web": False,
                    "show_in_android": True,
                    "partner_id": None,
                    "partner_selection_list": [],
                    "partner_selection_action": None,
                },
                "streamlined_message": {
                    "message_content": "Angsuranmu sebesar Rp {{card_due_amount}} akan jatuh tempo pada tanggal {{card_due_date}}. Bayar lebih awal untuk dapatkan cashback!",
                    "parameter": [None],
                    "info_card_property_id": None,
                },
                "infocard_property": {
                    "card_type": "2",
                    "card_action": "app_deeplink",
                    "card_destination": "howtopay",
                    "card_order_number": 1,
                    "title": "Yuk, Lunasi Pinjaman Aktifmu",
                    "title_color": "#ffffff",
                    "text_color": "#ffffff",
                },
                "infocard_button_property": [
                    {
                        "info_card_property_id": None,
                        "button_name": "M.BUTTON",
                        "text": "Bayar Sekarang",
                        "text_color": "#ffffff",
                        "action_type": "app_deeplink",
                        "destination": "howtopay",
                    }
                ],
                "image": [
                    {
                        "image_source": 252,
                        "image_type": "CARD_BACKGROUND_IMAGE",
                        "url": "info-card/CARD_BACKGROUND_IMAGE_252.png",
                        "thumbnail_url": "",
                        "service": "oss",
                        "image_status": 0,
                        "image": "",
                    }
                ],
            },
        ]

        for data in jturbo_info_card_retroload_data:
            with transaction.atomic():
                info_card_property = InfoCardProperty.objects.create(**data["infocard_property"])
                for button_property in data["infocard_button_property"]:
                    button_property["info_card_property_id"] = info_card_property.id
                    InfoCardButtonProperty.objects.create(**button_property)
                for image in data['image']:
                    create_image(info_card_property.id, image['image_type'], image['url'])
                data["streamlined_message"]["info_card_property_id"] = info_card_property.id
                message = StreamlinedMessage.objects.create(**data["streamlined_message"])
                data["streamlined_communication"]["message_id"] = message.id
                StreamlinedCommunication.objects.create(**data["streamlined_communication"])
