---

- name: Provision a {{ application_name }} db server
  hosts: dbservers
  become: yes
  become_user: root
  remote_user: ubuntu
  vars:
    - update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/base_secure.yml
    - env_vars/{{ env }}.yml
    - env_vars/{{ env }}_secure.yml

  roles:
    - base
    - db