---

- name: Create a {{ application_name }} virtual machine via vagrant
  hosts: all
  become: yes
  become_user: root
  remote_user: vagrant
  vars:
    - setup_git_repo: yes
    - update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/base_secure.yml
    - env_vars/vagrant.yml
    - env_vars/vagrant_secure.yml

  roles:
    - base
    - db
    - rabbitmq
    - web
    - celery
