# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-04-09 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdistrictlookup',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
