# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-04-15 05:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv3', '0004_auto_20190412_1257'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='citylookup',
            index_together=set([('city',)]),
        ),
        migrations.AlterIndexTogether(
            name='districtlookup',
            index_together=set([('district',)]),
        ),
        migrations.AlterIndexTogether(
            name='provincelookup',
            index_together=set([('province',)]),
        ),
        migrations.AlterIndexTogether(
            name='subdistrictlookup',
            index_together=set([('sub_district', 'zipcode')]),
        ),
    ]
