# coding: utf8
from builtins import str
from django.db import transaction
from django.core.management.base import BaseCommand
from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst


class Command(BaseCommand):
    help = 'load FeatureSetting on feature auto populate expenses.'

    def handle(self, *args, **options):
        try:
            app_names = ["Kredit Pintar",
            "TangBull",
            "Mi Credit",
            "DanaRupiah",
            "Kredivo",
            "Rupiah Plus",
            "DanaCepat",
            "Tunaiku",
            "TunaiKita",
            "Cashcash",
            "GoRupiah",
            "UangTeman",
            "PinjamUang",
            "RupiahPlus",
            "Pinjam Yuk",
            "KTA KILAT",
            "Doctor Rupiah",
            "Uang Cepat",
            "RajaUang",
            "Indodana",
            "GoCash",
            "Easycash",
            "VLoan",
            "Dana Kilat",
            "PinjamanGo",
            "BosPinjaman",
            "angelcash",
            "CashKilat",
            "RupiahNow",
            "Uang Plus",
            "Easy Rupiah",
            "PinjamDuit",
            "Cashtree",
            "Qreditku",
            "Awan Tunai",
            "DanaKu",
            "GoTunai",
            "Uang express",
            "WeCash",
            "WinWin",
            "Cermati",
            "Modalku Dana Usaha",
            "Pinjam Plus",
            "My Home Credit",
            "Pinjaman Rp",
            "Pinjam Gampang",
            "RpNow",
            "Ayo Rupiah",
            "TunaiTunai",
            "Pinjaman",
            "Cashwagon",
            "Dokter Uang",
            "Kredit Plus Mobile",
            "Pinjaman Kilat",
            "masBro",
            "Ngebet Kredit",
            "Uang Cash",
            "Angsuranku",
            "Rupiah Cepat",
            "Kamirupiah",
            "Dana Cash",
            "Pasar Rupiah",
            "Bos Tunai",
            "Pinjamku",
            "MiniRupiah",
            "Sakurupiah",
            "Pinjaman Mudah",
            "TunaiCepat",
            "Rupiah Easy",
            "Go Dana",
            "Uang Kilat",
            "Pinjam Cepat",
            "Asetku",
            "Rupiah Cepat",
            "UUang",
            "UangUang",
            "HaloCash",
            "PnjmnPetir",
            "Pede",
            "Pinjaman Cepat",
            "HaloRupiah",
            "Mesin Uang",
            "NowRupiah",
            "UangMe",
            "Do-It",
            "Dompet Kartu",
            "Cashstore",
            "Uang Saku",
            "RupiahQ",
            "Kasbon",
            "Pinjaman Duit",
            "Pinjaman Flash",
            "Mango Cash",
            "Cashcepat",
            "DompetKilat",
            "RupiahNow(official)",
            "Pinjam Rp",
            "PegadaianDigital",
            "CashRupiah",
            "Pinjam Uang",
            "Pnjmncepat",
            "Ayo Uang",
            "Dana Pintar",
            "Dana Segar",
            "YesKredit",
            "Kreditcepat.id",
            "Go Go Uang",
            "Rupiah Sapi",
            "Tunai Plus",
            "Dompet Kilat",
            "Kredt Pinjaman Tanpa Agunan",
            "UTunai Pro",
            "CashBon",
            "Ruang Tunai",
            "UTunai",
            "Easy Cash",
            "Micromoney",
            "AyoKredit",
            "RupiahKita",
            "UangQU",
            "Pinjam Cash",
            "Uang banyak",
            "SuperPinjam",
            "DuitinAja",
            "UangInstan",
            "UANGKU",
            "TunaiPlus",
            "RupiahCash",
            "SuperCash",
            "DanaBonus",
            "Oklik Cash",
            "BRI Pinjaman",
            "Cicil",
            "Kredit Mart",
            "Pinjaman Uang-KTA",
            "Dana pinjaman",
            "PinjamanCash",
            "DanaDana",
            "Aku Rupiah",
            "dompet ajaib",
            "DanaTeman",
            "Pinjaman Uang",
            "TokoTunai",
            "Home pinjaman",
            "KooRupiah",
            "Rumah Pinjaman",
            "KooCash",
            "Super Uang",
            "Dana Pinjam",
            "UangBagus",
            "Anda rupiah",
            "Uang express versi kilat",
            "Cash Market",
            "Modalku",
            "Danamas",
            "Uang Tunai",
            "Pinjaman Pertama",
            "Pinjaman Cepa",
            "Bos Uang",
            "Rupiah Avenue",
            "Dana Berkat",
            "CashPop",
            "DanaFlash",
            "Rupiah teman",
            "Rupiah Hero",
            "Go Duit",
            "KREDIT CEPAAT",
            "Masskredit",
            "WeCash Partner",
            "Uangrupiah",
            "Pinjaman Online",
            "CashDay",
            "Raja Pinjaman",
            "Danasukses",
            "Pinjaman Kredit Mandiri",
            "Pinjaman KTA",
            "BAJAK DUIT",
            "Pinjam Rupiah",
            "Pinjaman Pro",
            "Cash Affairs",
            "SPEKTRA Kredit",
            "Ahli pinjaman",
            "Cepatcash",
            "Pinjaman Modal Cepat",
            "PinjamanPlus",
            "Pinjaman tunai",
            "Go Uang",
            "Alipinjaman",
            "Dana Pinjaman - BRI Tunai",
            "Rakredit",
            "Easy Pinjam",
            "Pinjamall",
            "GoDuit",
            "haloPinjam",
            "Duit Mudah",
            "RoboCash",
            "Tunaikan",
            "Dapatkan Uang",
            "Danaklik",
            "Casheasy",
            "flash Rupiah",
            "Kredit Nusantara",
            "Tunai Plaza",
            "RAJADANA",
            "Go Pinjaman",
            "Raja Rupiah",
            "Pinjaman Terbuka Indonesia",
            "RupiahOne",
            "Dana Siaga",
            "Rajarupiah",
            "Pinjaman Kredit",
            "Kredit Rupiah",
            "PasarPinjam",
            "RupiahGet",
            "Kredit Pinjaman Cepat",
            "DanaPinjaman",
            "Cash Mart",
            "CariRupiah",
            "Pinjaman Tunai Dana Cepat",
            "kredit KTA",
            "Terbuka Pinjaman Indonesia",
            "Cepat Pinjaman",
            "RupiahMart",
            "Dr Cash",
            "Kredit Akulaku (unofficial)",
            "Pinjaman KUR Online 2018",
            "Bang Kredit",
            "Kredit Pinjaman Uang",
            "PasarKredit",
            "Kredit Kilat",
            "Dana Mudah",
            "Bang Kredit Mobile",
            "Rupiah cash++",
            "Dana Indonesia",
            "CariPinjaman",
            "KreditMart",
            "goKredit",
            "Pinjaman Rupiah",
            "ManTep - PinjaManTepat",
            "Rupiah Zone",
            "KreditMini",
            "Myrupiah",
            "CASHKREDIT",
            "BigCash",
            "eTunai",
            "Kredit Mandiri",
            "Pinjaman Tanpa Jaminan",
            "eRupiah",
            "Kredit Cepat Online",
            "Modalku Dana Cepat",
            "Easy Pinjaman",
            "Duit Plus",
            "Pinjam petir",
            "Gampang Pinjaman",
            "Pinjaman kecil",
            "Cashbac",
            "Pinjaman Pintar",
            "PINJAMAN BANK",
            "Tunai Wallet",
            "DanaCash",
            "Rupiahku",
            "FastRupiah",
            "cashpintar",
            "Dana Cepat",
            "Ali Rupiah",
            "Atur Duit",
            "Pinjamin Uang",
            "Kredit Uang",
            "Kredit cepat",
            "Rupiah Kita",
            "Pinjaman dana tanpa jaminan",
            "Bos Rupiah",
            "Kredit Pinjaman",
            "Pinjam Dana",
            "Duit Instan",
            "PinjamanDanaCepat",
            "Dompet Tunai",
            "Uang Box",
            "Daily Cash- Earn Money Free",
            "Dana Bijak",
            "MangoDana",
            "KuUang",
            "Make Money - Earn Cash",
            "Kreditplus Mobile Collection",
            "Kredit Hp",
            "Kredit_HP",
            "RajaUang Pro",
            "Pinjamanku",
            "Kotak Uang",
            "SuperDana",
            "CASHe",
            "KreditNow",
            "pinjam mart",
            "Pinjam Online",
            "RupiahKilat",
            "Pinjaman Tunai BNI Terbaru",
            "CASH - Pinjaman dana melalui HP",
            "Pinjaman Tunai - Kredit BRI",
            "Danamerdeka",
            "Yes Rupiah",
            "DanaPintar",
            "cashKarma",
            "duitin",
            "PinjamSaja",
            "CashForApps",
            "Pinjaman Uang Tanpa Jaminan",
            "KreditKita",
            "Pinjaman dana tanpa jaminan memudahkan transaksi pinjaman dana",
            "KREDIT TANPA AGUNAN.",
            "Uang saya",
            "Pinjam Tunai",
            "Tuan Pinjaman",
            "Pinjaman Dana",
            "Pinjaman Tunai Mandiri Dana Cepat",
            "CASHKREDIT.ID",
            "HaiUang",
            "Pinjaman Syariah",
            "GO Kredit",
            "gettunai",
            "Kur online pinjaman dana cepat",
            "UangPlus",
            "Kredit_Multiguna",
            "KreditUp",
            "Meminjam uang cepat",
            "Daily Cash",
            "Pinjaman Cash",
            "bambupinjam",
            "DanaSimas",
            "UangOnline",
            "Rupiah-Ayo",
            "Cashbox",
            "Cash Wagon",
            "CASH LOAN 2 MINUTES",
            "Rupiah Indo",
            "Earn Cash: Make Money Online",
            "Cara Pinjam Uang Online",
            "P-CASH",
            "Pinjaman Express",
            "Pinjaman Tunai Anda",
            "Dana Cepat Mandiri",
            "Kredit Pinjaman BRI",
            "GO Cash - Dana Cepat",
            "DanaNow",
            "Pinjaman Uang Online",
            "Kreditplus MMS",
            "pinjaman tunai online btn",
            "HotDana",
            "Pinjaman KTA OK",
            "Sinakredit",
            "Pinjaman online langsung cair",
            "Cloud Cash",
            "Pinjaman Online Cepat",
            "modal pinjaman",
            "Pinjaman Uang Cepat",
            "Rupiah Kilat",
            "Pinjaman Super",
            "Make money - earn cash free",
            "Cashupp",
            "Rupiah Bijak",
            "CashApp",
            "Agen Pinjam",
            "Pinjam Uang Cepat Cair",
            "Dokter Pinjaman",
            "pinjaman tunai online bca",
            "PinjemDuit",
            "Pinjaman Online Dengan KTP",
            "Meminjam uang",
            "Easypinjaman",
            "Pinjaman uang tunai",
            "GoUang",
            "Rupiah Oke",
            "Yuk Rupiah",
            "DuitDuit",
            "Pinjaman Tunai Cepat",
            "KTA - Dana Tunai",
            "Uang Pinjam",
            "Cari Pinjaman",
            "Kredit Tunai",
            "kredit BPF",
            "TapCash",
            "Cepatuang",
            "pinjaman tunai online bni",
            "Cash App",
            "InsCash",
            "DanaRupiah Pendanaan",
            "SuperUang",
            "Pinjaman Dana Cepat solusi keuangan anda",
            "DanaMudah",
            "Ayopinjam",
            "KUR Pinjaman Modal",
            "UangBox",
            "Dana Teman",
            "Kredit Syariah",
            "DanaKita",
            "Pinjaman Online Kredit Mandiri",
            "Semua pinjaman",
            "Pinjam Aja",
            "Tunai",
            "Pinjaman tanpa Agunan",
            "Get Rupiah",
            "Pinjaman modal usaha membantu usaha tanpa modal menjadi usaha menjanjikan",
            "Cash Online",
            "Pinjaman Mandri",
            "Pinjaman Online Cepat Cair",
            "Pinjaman BRI Tunai",
            "Ubah Pinjaman",
            "Go Tunai",
            "SimpleCash",
            "Kredit Niaga",
            "Pinjaman Online KUR BRI",
            "Pinjaman Online Dengan Cicilan",
            "Kredit tanpa Agunan",
            "Go-go Rupiah",
            "Pinjaman Tanpa Bunga Besar",
            "Free Cash",
            "Dana Simas",
            "Pinjaman Dompet",
            "Pinjaman Online Dengan KTP Susandev",
            "AkUang",
            "Dana Uang",
            "PinjamanMart",
            "Top Kredit",
            "Duit Express",
            "KREDIT POS",
            "Ayo Kredit",
            "Pinjaman BRI",
            "Dana Berkah",
            "PasarCash",
            "Kredit Plus",
            "Super Cash",
            "Pinjaman Bersama",
            "PINJAMAN P2P",
            "Putus asa pinjaman",
            "BNI SMART PINJAMAN",
            "Kredit Pinjaman - KTA",
            "Hujan Rupiah",
            "PayPal Cash",
            "Cicilan Rupiah",
            "Pinjaman Express - Instan",
            "pinjaman online tanpa jaminan",
            "Danain Cepat",
            "Amalan Dana Ghaib Trading Forex Online",
            "Pinjaman mahasiswa",
            "cash loans",
            "ex.cash",
            "NEW PINJAMAN TUNAI BRI KREDIT 2018",
            "Dana Tunai",
            "Pinjaman Uang Rakyat - BRI KREDIT",
            "Pinjaman dan investasi",
            "Payday Loans. Get Fast Cash",
            "Pinjaman dan Tabungan",
            "DanaTunai",
            "Pinjaman tanpa agunan online",
            "pinjaman kredit hp tanpa dp",
            "Dana Saku",
            "KeuanganPribadi",
            "CASH QUIZ",
            "Uang Kita",
            "Mr. Kredit",
            "pinjaman tunai online mandiri",
            "Kwik Cash",
            "PinjamanCepat",
            "ilmu uang gaib",
            "Kredit Usaha Rakyat",
            "Syarat Kredit ACC",
            "HaloRupiah Pinjaman Uang Rupiah Dana Cepat dan Mudah",
            "Danasolusi",
            "Pinjaman Online Tanpa Agunan",
            "CashFlash Pinjaman Dana Tunai dan Cepat",
            "Agent Pinjam",
            "Raja Rupiah cepat",
            "UCASH",
            "QuickCash123",
            "UangExpress",
            "Pinjam Uang Cepat",
            "Wecash ID",
            "maucash",
            "Pinjaman Uang Tunai Dana Mudah dan Cepat",
            "Kredit",
            "KARTU KREDIT",
            "MooCash",
            "We Cash - Earn Real Money",
            "Dunia Pinjaman",
            "OK Cashbag",
            "Pendaftaran Kartu Kredit",
            "Dana Instan Mandiri",
            "Saku Pinjaman",
            "Mafia Kartu Kredit",
            "Cash Receipt",
            "pinjaman online 2018",
            "Dompet Pinjaman",
            "Hitung Kredit Pro",
            "Angsuran pinjaman",
            "Cash Cepat",
            "Halo Cash",
            "KTA Dana Bantuan Sahabat",
            "KantongCash",
            "Jasa Pinjaman Dana Pontianak",
            "Hai Kredit",
            "Pinjam saja pinjaman tunai online",
            "Cara Mudah Pinjaman Cepat Cair",
            "Get Uang",
            "Kredit Syariah tanpa bunga",
            "Pinjaman Asik",
            "Pinjaman tanpa bunga online",
            "LetsGoRupiah",
            "Kredit cepat langsung cair",
            "Cash Robot",
            "TokoRupiah",
            "Ilmu Pesugihan Uang Balik Lengkap Online Forex Trading",
            "Pinjaman Online Dengan Cicilan Susandev",
            "Kredit Uang Cepat-Pinjaman Tanpa Agunan",
            "RupiahBox",
            "Uang Flash",
            "pinjaman tanpa kartu kredit mudah dan cepat",
            "Pinjaman Taktis",
            "KREDIT UANG CEPAT ONLINE",
            "GoGo Cash",
            "CashOn",
            "pinjaman kta tanpa kartu kredit",
            "E Pinjaman",
            "Dana Cepat Online",
            "eKredit",
            "Pinjaman Sahabat",
            "Kur pinjaman Online 2018",
            "Pinjaman Uang Tunai Cepat",
            "Pengajuan Pinjaman Bank",
            "Kredit petir",
            "Pinjaman dana tunai memudahkan anda mendapat bantuan dana",
            "Pinjaman Online Terkini",
            "KTA Dana Cinta",
            "Pinjaman Uang Cepat KUR BRI",
            "Pinjam Cepat Kilat",
            "Pinjaman online Tanpa jaminan dan kartu kredit",
            "Perlu Duit",
            "Klik Pinjaman",
            "Pinjaman Akad  Pinjaman Uang Dana Mudah dan Cepat",
            "Instant hakika cash loan",
            "Pinjaman Dana Cepat",
            "Tunai Pinjaman",
            "SpeedCash",
            "BRI pinjaman tunai",
            "cari rupiah",
            "Aplikasi Dana Desa",
            "Cara Mudah Kredit HP Murah",
            "Pinjam uang online terbaru",
            "DuitPlus",
            "Bos Tunai Cash",
            "Orange Cash",
            "Cara Dapat Uang",
            "Pinjam uang di bank",
            "899cash",
            "Pinjaman_Personal_Tanpa_Agunan",
            "Cicilan Kredit Rumah",
            "NewRupiah",
            "Dana Bersama",
            "Bantuan pinjaman",
            "Danaxtra",
            "Pinjaman Tunai BRI",
            "KREDIT RUMAH",
            "KREDIT USAHA",
            "Uang Cepats",
            "CashAdvance Mobile",
            "Pinjaman Online EasyKta",
            "AMALAN UANG DIBAWAH SAJADAH",
            "Ilmu Melipagandakan Uang Terampuh Life Insurance And Forex Tranding",
            "Pohon Uang",
            "Pinjaman KTA BRI",
            "Admin goKredit",
            "Kredit dan pinjaman",
            "CashDana",
            "Kredit Tanpa Agunan - KTA Cepat Cair",
            "Aplikasi Pinjaman Bank",
            "Pinjaman - Personal Loan",
            "CASHFIX",
            "Ayo Pinjam",
            "Pengganda Uang",
            "Kredit Medan",
            "Pinjaman Dana Tunai Online Cepat",
            "Dana Tunai Mobile",
            "Cek Rupiah",
            "Sakuku Rupiah",
            "KREDIT MULTI GUNA",
            "CrowdCash",
            "Ahli Dana",
            "Pinjaman KTA-DanaSegar Cepat Cair",
            "Earn Money Cash Wallet",
            "Cicil HP Aplikasi Kredit HP",
            "pinjaman tanpa riba dan jaminan",
            "Cash & Cash",
            "Pinjaman kerah putih",
            "Panduan mudah pinjaman pribadi",
            "CepatRupiah",
            "Uang Pinjaman",
            "Happy Cash",
            "Sahabat Rupiah",
            "CashMagnet",
            "Kredit Hp online",
            "Pesugihan uang gaib cepat cair mujarab terbaik charity california to donate car",
            "Kredito",
            "Pinjaman Tunai Mandiri",
            "KSPS Sumber Dana Barakah",
            "Pinjaman Top",
            "Kredit Finden",
            "KreditPro",
            "Meminjam uang sekarang",
            "Dana Go",
            "Dana.pinjaman",
            "Kredit Mania",
            "Kotak Rupiah",
            "CariDana",
            "SMS Cash And Credit",
            "Pinjaman Dana di Pegadaian ( tutorial )",
            "CashLo",
            "kokho kredit hp online",
            "Amalan uang goib Online Forex Trading",
            "KTA Xtra Dana",
            "Pinjam Uang Bebas",
            "Cash Cash",
            "Tips Kredit Cepat ACC",
            "TunaiInstant",
            "dewancash",
            "Dompet Duit",
            "Cash Calc",
            "Pocong Kredit",
            "Cashplus",
            "Mitra Dana Syariah",
            "Yakinlah pinjaman",
            "Amalan Uang Khodam",
            "Kecepatan pinjaman",
            "Cash Rupiah",
            "Kredit Motor",
            "Info Pinjaman tunai usaha",
            "KTA Dana Instant",
            "Kredit.pinjaman.uang",
            "JURUS LUNAS PINJAMAN BANK",
            "UangWe",
            "Rupiah Loan",
            "AkuRupiah",
            "Pinjaman Online KUR",
            "cashtree mod",
            "Uang Gratis",
            "Pinjaman Online Cepat Cair Susandev",
            "Petik Duit",
            "Mobile pinjaman",
            "Cicilan Uang Cepat-Bunga Rendah",
            "E-Rupiah",
            "Kredit Dana Cepat-Pasti Cair",
            "Cinta Rupiah",
            "kotak Dana",
            "Cara Mendapatkan Uang Di Internet",
            "Tarik Pinjaman",
            "Cash Tiger",
            "Cash Loan In 2 Minutes",
            "Rupiah Elite",
            "Kredit-kredit",
            "Pinjam Uang Online",
            "Pinjam Dana Tunai",
            "Pinjaman Tunaiku Online",
            "Dana Tunai Mandiri Taktis",
            "CASH EXPRESS",
            "PINJAMAN TUNAI BNI",
            "Pinjaman Dana di Pegadaian",
            "Pinjaman uang online five in one",
            "DewaCash",
            "Cash Advance",
            "Gadai BPKB Motor Pinjam Dana",
            "Pinjaman Dana Aman-Kredit Cepat Cair",
            "PINJAMAN TUNAI KEDIT MANDIRI 2018",
            "Halo Dana",
            "AkuDana",
            "go cash",
            "Modal Rupiah",
            "KUR BRI - Pinjaman Online",
            "Kredit Dompet",
            "uuang pro",
            "Pinjaman Keren",
            "KreditHP",
            "Fast Cash",
            "QuickCash",
            "Dana Online-Pinjaman KTA",
            "KreditMobil",
            "Cicilan Rupiah Bunga Ringan Online",
            "Ilmu Mengubah Kertas Atau Daun Menjadi Uang Terbaru Forex Tranding Online",
            "Beritaku Cara mudah pinjam uang di bank",
            "Ponsel angsuran pinjaman",
            "Kredit Tanpa Agunan Mandiri",
            "Cara Cepat Pinjam Uang Online",
            "KartuKredit.Bank",
            "Pinjamanuang.KTAonline",
            "Hujan Duit",
            "Duitku",
            "Kredit Pintar Giri",
            "Cara Menarik Uang Ghaib Ampuh",
            "DanaKu Partner",
            "Cash or Credit",
            "KUR Bri Pinjaman",
            "RupiahDana",
            "Pinjaman Syariah - Pinjam Online Tanpa Riba",
            "Kredit laptop tanpa dp terbaru",
            "Cash Money Online",
            "Kredit Indo",
            "Uanggo",
            "Pinjaman Online - Pinjaman Bersama",
            "Kredit Mobil",
            "kreditmurahbgt",
            "Ping pinjaman",
            "watch to cash",
            "Kartu kredit pinjaman",
            "Cicilan Uang Tunai Cepat",
            "Dana Pinjaman Online-Khusus Wirausaha",
            "Platform pinjaman",
            "Teman Uang Pinjaman Dana Teman",
            "RIZKI KREDIT",
            "Modal Kredit",
            "Modal Dana",
            "Pinjaman Indo",
            "Rupiah Get",
            "Inuka cash Loan",
            "Pinjaman Bank Lengkap",
            "Pinjaman Tunai Mandiri Terbaru",
            "Cara Mendapatkan Uang Dari Internet",
            "Duit-Plus",
            "KreditCepat",
            "Pinjaman KTA Bank",
            "kur bri pinjaman modal",
            "Cari Pinjaman Cepat Cair",
            "Uang Tunai Cepat",
            "Speedy Cash",
            "Rupiah Cow",
            "Awan Tunai Dev",
            "i88Cash",
            "Pinjaman KTA Cepat",
            "Doa Mendatangkan Uang Ghaib",
            "Apk Ladang Duit V.01",
            "Apk Ladang Duit V.1",
            "AGUNAN TUNAI BRI KREDIT 2018",
            "Dana Cash-Pinjaman Ringan",
            "Cara Mendapatkan Uang dari Internet Online Forex Trading",
            "BUMDes Tunai",
            "rupiah ngebut",
            "Magic Cash",
            "Jasa Kredit Dana Cash Online",
            "Pinjaman Tunai BRIANDA",
            "Panduan Kredit Cepat Cair",
            "Tarik Kredit",
            "Dana Pinjaman Tunai",
            "Trik Cara Cepat Dapat Uang",
            "Pinjaman Ajaib",
            "Rupiah On",
            "Kredit Dana-Pinjaman Online",
            "Dunia Kredit",
            "Pinjaman Bro",
            "Pinjaman Microfins",
            "Cash Advance - Payday Loans",
            "Uang Harian",
            "Jepara Raja Kredit",
            "Teman Pinjaman",
            "KREDIT MIKRO",
            "KTA Cepat Cair-Kredit Usaha",
            "Cash Loans Online",
            "Dana Segar Online Cepat",
            "Pinjaman tanpa agunan briliant",
            "KTA Tunai-Cepat Cair",
            "Pinjaman lunak",
            "Cepat Uang",
            "com.infincash.gorupiah",
            "Pinjaman KUR Online",
            "Rupiah Super",
            "Bos Cash",
            "Kredit Pintar 1",
            "Cash Tree",
            "Pinjaman Ikan",
            "Pinjaman KUR BRI",
            "KREDIT PERBANKAN",
            "Kreditku ID",
            "CashCow",
            "Quick Cash",
            "Amalan Uang Di Bawah Sajadah Terlengkap Forex Tranding Online",
            "CASH LOAN IN 30 SECONDS easy cash India",
            "RP CASH",
            "Tunaiku Portal Informasi Keuangan",
            "Kredit Cash-DanaSegar Cepat",
            "Kamus Ekonomi & Keuangan",
            "Tunai angsuran pinjaman",
            "Hutang Dana Segar Online Khusus Ibu Rumah Tangga",
            "Meminjam cash",
            "info lengkap kredit hp bandung",
            "Pinjaman Dana Cepat-Survei Mudah",
            "Easycash 2",
            "Pinjam Mandiri",
            "RajaUang 2",
            "Tunaiku 2",
            "pinjam pulsa xl 2018",
            "UangTeman-Dev",
            "Tiger Cash",
            "com.tl.bostunai",
            "iFreeCash",
            "Jago Kredit",
            "Cash now- Earn Money onlilne",
            "Credit Cash",
            "Super kredit",
            "Kredit Dana",
            "Rupiah Plus Partner",
            "KTA - Cash Online",
            "Cara Mendapatkan Uang dari Sosmed Online Forex Trading",
            "Daftar Pinjaman Online - Cepat Cair",
            "Kredit_HP_online",
            "Pinjaman Syariah Online Tanpa Riba",
            "Uang Gratis Kartu kredit gratis",
            "Dompet kredit pintar—pinjaman uang",
            "AwanTunai",
            "Dana Ghaib Forex Tranding Online",
            "Kredit Bijak",
            "KUR Pinjaman Modal Online",
            "Kredit Kita",
            "Pinjaman Tunai BRI Terbaru",
            "Cash Loan - Instant to Phone Mpesa",
            "Watch & Cash",
            "Rupiah Fast",
            "Cara Membuang Sial Forex Trading Online",
            "KTA Dana Cinta CTBC",
            "Cicilan Dana Segar Online",
            "Tunai Kita Cepat",
            "Pinjaman Tunai-Cair Besar",
            "Uang Mesin",
            "Pinjaman DanaSegar-Survei Cepat",
            "Dimas Kanjeng Gandakan Uang",
            "Tunai app",
            "Online Kredit Deutschland",
            "Angel pinjam uang",
            "Cash On Cash",
            "Brankas Tunai-Pinjaman Online",
            "Pinjaman Kredit-Pinjaman Transaksi",
            "Cicilan Dana Segar Online Khusus Wiraswasta",
            "Dana Rupiah Cair Besar Online-Tanpa Agunan",
            "Pinjaman KUR BRI Online",
            "Ilmu Gendam Mendatangkan Uang",
            "App Cash Online",
            "Easy cazh Dana mudah dan cepat",
            "Pinjaman Ekstra",
            "Kredit iphone tanpa kartu kredit",
            "Kredit Kami",
            "Kredit Pintar 2",
            "Amalan Uang Ghaib",
            "Kredit Pinjaman Online",
            "com.loan.cash.credit.easy.kilat.cepat.pinjam.uang.dana.rupiah",
            "Cicilan Cash-Pinjaman Cepat",
            "Uang Di Bawah Sajadah Forex Tranding Online",
            "Pinjaman Mandiri",
            "MangoCash",
            "Pinjaman KUR BRI Online 2018",
            "Rupiah Danah",
            "Cash Credit",
            "Pinjaman Tunai Mandiri Tanpa Agunan",
            "Cicilan Kredit",
            "danabijak",
            "CashLoan"]
            FeatureSetting.objects.get_or_create(is_active=True,
                                                feature_name=FeatureNameConst.AUTO_POPULATE_EXPENSES,
                                                category="application",
                                                description="https://trello.com/c/ttLEksQg",
                                                parameters={"app_names" : app_names})
        except Exception as e:
            self.stdout.write(self.style.ERROR(str(e)))

        self.stdout.write(self.style.SUCCESS('Done'))
