# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-10-14 07:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collectionbucket', '0004_alter_agent_task_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionagenttask',
            name='actual_agent',
            field=models.ForeignKey(blank=True, db_column='actual_agent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actual_agent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collectionagenttask',
            name='assign_to_vendor',
            field=models.NullBooleanField(),
        )
    ]
