from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^collection_vendor_data',
        views.collection_vendor_data, name='collection_vendor_data'),
    url(r'^collection_vendor_form$',
        views.collection_vendor_form, name='collection_vendor_form'),
    url(r'^collection_vendor_delete',
        views.collection_vendor_delete, name='collection_vendor_delete'),
    url(r'^transfer_account_list',
        views.transfer_account_list, name='transfer_account_list'),
    url(r'^add_new_transfer_account',
        views.add_new_transfer_account, name='add_new_transfer_account'),
    url(r'^collection_retain_data',
        views.collection_retain_data, name='collection_retain_data'),
    url(r'^collection_retain_form',
        views.collection_retain_form, name='collection_retain_form'),
    url(r'^retain_assignment/(?P<application_xid>[0-9]+)$',
        views.get_data_assignment, name='get_data_assignment'),
    url(r'^store_retain_assignment',
        views.store_retain_data, name='store_retain_assignment'),
    url(r'^list_report_vendor',
        views.list_report_vendor, name='list_report_vendor'),
    url(r'^upload_report_vendor',
        views.upload_report_vendor, name='upload_report_vendor'),
    url(r'^submit_report_vendor',
        views.submit_report_vendor, name='submit_report_vendor'),
    url(r'^download_error_information/(?P<upload_vendor_report_id>[0-9]+)$',
        views.download_error_information, name='download_error_information'),
    url(r'^agent_removal',
        views.agent_removal_page, name='agent_removal'),
    url(r'^process_agent_removal',
        views.process_agent_removal, name='process_agent_removal'),
    url(r'^process_agent_transfer',
        views.process_agent_transfer, name='process_agent_transfer'),
    url(r'^recording_detail_list',
        views.recording_detail_list, name='recording_detail_list'),
    url(r'^download_recording_detail_file/(?P<recording_detail_id>[0-9]+)/$',
        views.download_recording_detail_file, name='download_recording_detail_file'),
    url(r'^(?P<task_id>[\w-]+)/$', views.get_bulk_download_progress,
        name='bulk_download_progress_status'),
    url(r'^process_bulk_download_trigger',
        views.process_bulk_download_trigger, name='process_bulk_download_trigger'),
    url(r'^do_bulk_download',
        views.do_bulk_download, name='do_bulk_download'),
    url(r'^bulk_account_transfer',
        views.bulk_account_transfer, name='bulk_account_transfer'),
]
