# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-03-27 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ShortenedUrl',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.AutoField(
                        db_column='shortened_url_id', primary_key=True, serialize=False
                    ),
                ),
                ('short_url', models.TextField(db_index=True, unique=True)),
                ('full_url', models.TextField()),
            ],
            options={
                'db_table': 'shortened_url',
            },
        ),
    ]
