---

# Git settings.
setup_git_repo: yes
git_branch: master
julo_env: staging
domain_name: api-staging.julofinance.com


ssl_crt: "{{ vault_ssl_crt }}"
ssl_key: "{{ vault_ssl_key }}"


# Database settings.
postgresql_name: "{{ application_name }}"
postgresql_user: "{{ application_name }}"
postgresql_password: "{{ vault_postgresql_password }}"
postgresql_host: "{{ groups['dbservers'][0] }}"  # For appserver
postgresql_port: 5432
postgresql_appserver_host: "{{ groups['webservers'][0] }}"
analytic_name: analytic
analytic_user: analytic
analytic_password: "{{ vault_analytic_password }}"

# New database settings
postgresql_ops_name: julodb
postgresql_ops_user: ops_server
postgresql_ops_password: "{{ vault_postgresql_ops_password }}"
postgresql_ops_host: "{{ groups['dbservers'][0] }}"  # For appserver
postgresql_ops_port: 5432
postgresql_ana_name: julodb
postgresql_ana_user: ana_server
postgresql_ana_password: "{{ vault_postgresql_ana_password }}"
postgresql_ana_host: "{{ groups['dbservers'][0] }}"  # For appserver
postgresql_ana_port: 5432

# Gunicorn settings. For the number of workers, a good rule to follow is
# 2 x number of CPUs + 1
gunicorn_num_workers: 3

# Setting this to 1 will restart the Gunicorn process each time
# you make a request, basically reloading the code. Very handy
# when developing. Set to 0 for unlimited requests (default).
gunicorn_max_requests: 0

gunicorn_timeout_seconds: 300


# Nginx settings.
nginx_server_name: "{{ inventory_hostname }}"
ssl_dest_dir: /etc/ssl


# RabbitMQ settings.
rabbitmq_server_name: "{{ inventory_hostname }}"

rabbitmq_admin_user: "{{ application_name }}_admin"
rabbitmq_admin_password: "{{ vault_rabbitmq_admin_password }}"

rabbitmq_application_vhost: "{{ application_name }}"
rabbitmq_application_user: "{{ application_name }}"
rabbitmq_application_password: "{{ vault_rabbitmq_application_password }}"


# Celery settings.
celery_num_workers: 2
flower_admin_password: "{{ vault_flower_admin_password }}"


# Application settings.
django_requirements_path: "requirements/{{ julo_env }}.pip"
django_secret_key: "{{ vault_django_secret_key }}"
django_settings_file: "{{ application_name }}.settings.{{ julo_env }}"

base_url: "https://{{ domain_name }}"
broker_url: "amqp://{{ rabbitmq_application_user }}:{{ rabbitmq_application_password }}@localhost/{{ rabbitmq_application_vhost }}"

run_django_db_migrations: yes
run_django_collectstatic: yes


# GCM settings.
gcm_server_key: "{{ vault_gcm_server_key }}"
google_maps_api_key: "{{ vault_google_maps_api_key }}"


# S3 bucket settings, IAM user: appserver-staging-user.
s3_data_bucket: "julodata-{{ julo_env }}"
s3_logs_bucket: "julologs-{{ julo_env }}"
s3_media_bucket: "julomedia-{{ julo_env }}"
s3_analytics_bucket: "juloanalytics-{{ julo_env }}"
aws_default_region: "us-east-1"
aws_access_key_id: "{{ vault_aws_access_key_id }}"
aws_secret_access_key: "{{ vault_aws_secret_access_key }}"
object_storage_access_key_id: "{{ vault_ostorage_secret_access_key }}"
object_storage_secret_access_key: "{{ vault_ostorage_secret_access_key }}"
object_storage_endpoint_url: http://116.206.196.84:9000

# Sentry settings.
sentry_dsn: "{{ vault_sentry_dsn }}"


# Nexmo settings
nexmo_api_key: "{{ vault_nexmo_api_key }}"
nexmo_api_secret: "{{ vault_nexmo_api_secret }}"
nexmo_sms_url: "https://rest.nexmo.com/sms/json"


# SendGrid settings
sendgrid_api_key: "{{ vault_sendgrid_api_key }}"


# Anaserver settings
anaserver_base_url: https://ana-staging.julofinance.com
anaserver_token: "{{ vault_anaserver_token }}"


# Doku settings
doku_base_url: http://staging.doku.com/dokupay/h2h/
doku_proxy_url: http://dev-no-need-proxy:3128
doku_client_id: 2094
doku_client_secret: "{{ vault_doku_client_secret }}"
doku_shared_key: "{{ vault_doku_shared_key }}"


# Dutamedia settings
dutamedia_api_key_click2call: "{{ vault_dutamedia_api_key_click2call }}"
dutamedia_api_key_robodial: "{{ vault_dutamedia_api_key_robodial }}"
dutamedia_base_url: http://sip.dutamedia.com:7007

# Xendit settings
xendit_api_key: "{{ vault_xendit_api_key }}"
xendit_base_url: https://api.xendit.co
xendit_disbursement_validation_token: "{{ vault_xendit_disbursement_validation_token }}"

# BFI partner settings
bfi_client_id: 1707NC0007
bfi_base_url: http://202.43.183.141/apidigital/api.asmx?wsdl


slack_api_token: "{{ vault_slack_api_token }}"
slack_web_api_token: "{{ vault_slack_web_api_token }}"

# BRI Lender settings
bri_x_key: "{{ vault_bri_x_key }}"
bri_client_id: "{{ vault_bri_client_id }}"
bri_client_secret: "{{ vault_bri_client_secret }}"
bri_code: "{{ vault_bri_code }}"

# Faspay settings
faspay_merchant_name: "JULO"
faspay_merchant_id: "31932"
faspay_user_id: "{{ vault_faspay_user_id }}"
faspay_password: "{{ vault_faspay_password }}"

# One-time password settings
otp_secret_key: "{{ vault_otp_secret_key }}"

#tokopedia settings
tokopedia_client_id: "{{ vault_tokopedia_client_id }}"
tokopedia_client_secret: "{{ vault_tokopedia_client_secret }}"
tokopedia_base_url: "https://api-staging.tokopedia.com/"
