# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-11-16 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poc_nexmo', '0002_nexmo_user2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nexmoconversation',
            name='agent',
            field=models.ForeignKey(blank=True, db_column='nexmo_user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='poc_nexmo.NexmoUser'),
        ),
    ]
