# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-11-19 02:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poc_nexmo', '0004_auto_20181116_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nexmouser',
            old_name='is_online',
            new_name='is_oncall',
        ),
    ]
