# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-01-27 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamlined_communication', '0010_add_onboarding_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamlinedCommunicationParameterList',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='parameter_list_id', primary_key=True, serialize=False)),
                ('parameter_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'streamlined_communication_parameter_list',
            },
        ),
        migrations.AddField(
            model_name='streamlinedcommunication',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
