# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-02-16 15:52
from __future__ import unicode_literals
from django.db import migrations, models
import django.contrib.postgres.fields

class Migration(migrations.Migration):
    dependencies = [
        ('streamlined_communication', '0024_add_columns_stream_lined_communication'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamlinedcommunication',
            name='function_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list,
                                                            size=None),
        ),
        migrations.CreateModel(
            name='StreamlinedCommunicationFunctionList',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='function_list_id', primary_key=True, serialize=False)),
                ('function_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('communication_platform', models.CharField(
                    choices=[(b'EMAIL', b'Email'), (b'WA', b'Whatsapp'), (b'PN', b'Push Notification'),
                             (b'SMS', b'SMS'), (b'IAN', b'In App Notification'), (b'ROBOCALL', b'Robocall')],
                    max_length=50)),
            ],
            options={
                'db_table': 'streamlined_communication_function_list',
            },
        ),
    ]
