from django.test import SimpleTestCase

from juloserver.streamlined_communication.constant import PageType


class TestPageType(SimpleTestCase):
    def test_all_pages(self):
        ret_val = PageType.all_pages()
        expected_pages = {
            'TarikDana',
            'tarik_dana',
            'kirim_dana',
            'pulsa_data',
            'listrik_pln',
            'bpjs_kesehatan',
            'kartu_pasca_bayar',
            'autodebet_bca_welcome',
            'autodebet_bri_welcome',
            'cashback',
            'cfs',
            'education_spp',
            'Home',
            'julo_card_choose_tenor',
            'julo_card_home_page',
            'julo_card_transaction_completed',
            'julo_shop',
            'loan_activity',
            'nav_inapp_product_transfer_other',
            'ovo_tagihan_page',
            'pdam_home_page',
            'product_transfer_self',
            'referral',
            'train_ticket',
            'healthcare_main_page',
            'Loan',
            'activity_loan',
            'dana_link',
            'gopay_linking',
            'gopay_payment',
            'gopay_autodebet',
            'julo_starter_second_check_rejected',
            'julo_starter_eligbility_j1_offer',
            'julo_starter_eligbility_rejected',
            'julo_starter_eligbility_ok',
            'julo_starter_second_check_ok',
            'julo_starter_second_check_ok_full_dv',
            'julo_starter_second_check_j1_offer',
            'julo_starter_full_limit',
            'e-wallet',
            'e-commerce',
            'deeplink_upgrade_form',
            'promo_entry_page',
            'upload_salary_slip',
            'upload_bank_statement',
            'in_app_ptp',
            'to_additional_form',
            'video_webview',
            'autodebet_activation_drawer',
            'tagihan',
            'profile',
            'transaction_status',
            'change_data_privacy',
            'checkout',
            'loyalty_homepage',
            'autodebet_idfy',
            'change_phone_number',
            'julo_financing',
            'qris_main_page',
            'dana_autodebet',
            'bca_autodebet',
            'bri_autodebet',
            'ovo_autodebet',
            'mandiri_autodebet',
            'bni_autodebet',
            'repayment_cashback',
        }
        for x in ret_val:
            self.assertIn(x, expected_pages)
