from django.core.management.base import BaseCommand
from juloserver.loan_refinancing.models import WaiverRecommendation


class Command(BaseCommand):
    help = 'adjustment_waiver_recommendation'

    required_keys = [
        'program_name',
        'bucket_name',
        'is_covid_risky',
        'partner_product',
        'late_fee_waiver_percentage',
        'interest_waiver_percentage',
        'principal_waiver_percentage',
        'total_installments',
    ]
    default_args = [
        {
            "bucket_name": "1",
            "program_name": "R4",
            "is_covid_risky": False,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "1.00",
            "interest_waiver_percentage": "1.00",
            "principal_waiver_percentage": "0.10",
            "total_installments": None,
        },
        {
            "bucket_name": "1",
            "program_name": "R4",
            "is_covid_risky": True,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "1.00",
            "interest_waiver_percentage": "0.50",
            "principal_waiver_percentage": "0.10",
            "total_installments": None,
        },
        {
            "bucket_name": "2",
            "program_name": "R4",
            "is_covid_risky": False,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "1.00",
            "interest_waiver_percentage": "1.00",
            "principal_waiver_percentage": "0.20",
            "total_installments": None,
        },
        {
            "bucket_name": "2",
            "program_name": "R4",
            "is_covid_risky": True,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "1.00",
            "interest_waiver_percentage": "1.00",
            "principal_waiver_percentage": "0.20",
            "total_installments": None,
        },
        {
            "bucket_name": "3",
            "program_name": "R4",
            "is_covid_risky": False,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "1.00",
            "interest_waiver_percentage": "1.00",
            "principal_waiver_percentage": "0.25",
            "total_installments": None,
        },
        {
            "bucket_name": "3",
            "program_name": "R4",
            "is_covid_risky": True,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "1.00",
            "interest_waiver_percentage": "1.00",
            "principal_waiver_percentage": "0.25",
            "total_installments": None,
        },
        {
            "bucket_name": "4",
            "program_name": "R4",
            "is_covid_risky": False,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "1.00",
            "interest_waiver_percentage": "1.00",
            "principal_waiver_percentage": "0.25",
            "total_installments": None,
        },
        {
            "bucket_name": "4",
            "program_name": "R4",
            "is_covid_risky": True,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "1.00",
            "interest_waiver_percentage": "1.00",
            "principal_waiver_percentage": "0.25",
            "total_installments": None,
        },
        {
            "bucket_name": "5",
            "program_name": "R4",
            "is_covid_risky": False,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "1.00",
            "interest_waiver_percentage": "1.00",
            "principal_waiver_percentage": "0.30",
            "total_installments": None,
        },
        {
            "bucket_name": "5",
            "program_name": "R4",
            "is_covid_risky": True,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "1.00",
            "interest_waiver_percentage": "1.00",
            "principal_waiver_percentage": "0.30",
            "total_installments": None,
        },
        {
            "bucket_name": "6",
            "program_name": "R4",
            "is_covid_risky": False,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "1.00",
            "interest_waiver_percentage": "1.00",
            "principal_waiver_percentage": "0.33",
            "total_installments": None,
        },
        {
            "bucket_name": "6",
            "program_name": "R4",
            "is_covid_risky": True,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "1.00",
            "interest_waiver_percentage": "1.00",
            "principal_waiver_percentage": "0.33",
            "total_installments": None,
        },
        {
            "bucket_name": "Current",
            "program_name": "R4",
            "is_covid_risky": False,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "1.00",
            "interest_waiver_percentage": "1.00",
            "principal_waiver_percentage": "0.10",
            "total_installments": None,
        },
        {
            "bucket_name": "Current",
            "program_name": "R4",
            "is_covid_risky": True,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "1.00",
            "interest_waiver_percentage": "1.00",
            "principal_waiver_percentage": "0.10",
            "total_installments": None,
        },
        {
            "bucket_name": "1",
            "program_name": "R5",
            "is_covid_risky": False,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "0.20",
            "interest_waiver_percentage": "0.00",
            "principal_waiver_percentage": "0.00",
            "total_installments": None,
        },
        {
            "bucket_name": "1",
            "program_name": "R5",
            "is_covid_risky": True,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "0.20",
            "interest_waiver_percentage": "0.00",
            "principal_waiver_percentage": "0.00",
            "total_installments": None,
        },
        {
            "bucket_name": "2",
            "program_name": "R5",
            "is_covid_risky": False,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "1.00",
            "interest_waiver_percentage": "0.00",
            "principal_waiver_percentage": "0.00",
            "total_installments": None,
        },
        {
            "bucket_name": "2",
            "program_name": "R5",
            "is_covid_risky": True,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "1.00",
            "interest_waiver_percentage": "0.00",
            "principal_waiver_percentage": "0.00",
            "total_installments": None,
        },
        {
            "bucket_name": "3",
            "program_name": "R5",
            "is_covid_risky": False,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "1.00",
            "interest_waiver_percentage": "0.00",
            "principal_waiver_percentage": "0.00",
            "total_installments": None,
        },
        {
            "bucket_name": "3",
            "program_name": "R5",
            "is_covid_risky": True,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "1.00",
            "interest_waiver_percentage": "0.00",
            "principal_waiver_percentage": "0.00",
            "total_installments": None,
        },
        {
            "bucket_name": "4",
            "program_name": "R5",
            "is_covid_risky": False,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "1.00",
            "interest_waiver_percentage": "0.00",
            "principal_waiver_percentage": "0.00",
            "total_installments": None,
        },
        {
            "bucket_name": "4",
            "program_name": "R5",
            "is_covid_risky": True,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "1.00",
            "interest_waiver_percentage": "0.00",
            "principal_waiver_percentage": "0.00",
            "total_installments": None,
        },
        {
            "bucket_name": "5",
            "program_name": "R5",
            "is_covid_risky": False,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "1.00",
            "interest_waiver_percentage": "0.00",
            "principal_waiver_percentage": "0.00",
            "total_installments": None,
        },
        {
            "bucket_name": "5",
            "program_name": "R5",
            "is_covid_risky": True,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "1.00",
            "interest_waiver_percentage": "0.00",
            "principal_waiver_percentage": "0.00",
            "total_installments": None,
        },
        {
            "bucket_name": "6",
            "program_name": "R5",
            "is_covid_risky": False,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "1.00",
            "interest_waiver_percentage": "0.00",
            "principal_waiver_percentage": "0.00",
            "total_installments": None,
        },
        {
            "bucket_name": "6",
            "program_name": "R5",
            "is_covid_risky": True,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "1.00",
            "interest_waiver_percentage": "0.00",
            "principal_waiver_percentage": "0.00",
            "total_installments": None,
        },
        {
            "bucket_name": "Current",
            "program_name": "R5",
            "is_covid_risky": False,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "0.20",
            "interest_waiver_percentage": "0.00",
            "principal_waiver_percentage": "0.00",
            "total_installments": None,
        },
        {
            "bucket_name": "Current",
            "program_name": "R5",
            "is_covid_risky": True,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "0.20",
            "interest_waiver_percentage": "0.00",
            "principal_waiver_percentage": "0.00",
            "total_installments": None,
        },
        {
            "bucket_name": "1",
            "program_name": "R6",
            "is_covid_risky": False,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "1.00",
            "interest_waiver_percentage": "0.20",
            "principal_waiver_percentage": "0.00",
            "total_installments": 1,
        },
        {
            "bucket_name": "1",
            "program_name": "R6",
            "is_covid_risky": True,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "1.00",
            "interest_waiver_percentage": "0.20",
            "principal_waiver_percentage": "0.00",
            "total_installments": 1,
        },
        {
            "bucket_name": "2",
            "program_name": "R6",
            "is_covid_risky": False,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "1.00",
            "interest_waiver_percentage": "0.30",
            "principal_waiver_percentage": "0.00",
            "total_installments": 1,
        },
        {
            "bucket_name": "2",
            "program_name": "R6",
            "is_covid_risky": True,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "1.00",
            "interest_waiver_percentage": "0.30",
            "principal_waiver_percentage": "0.00",
            "total_installments": 1,
        },
        {
            "bucket_name": "2",
            "program_name": "R6",
            "is_covid_risky": False,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "1.00",
            "interest_waiver_percentage": "0.50",
            "principal_waiver_percentage": "0.00",
            "total_installments": 2,
        },
        {
            "bucket_name": "2",
            "program_name": "R6",
            "is_covid_risky": True,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "1.00",
            "interest_waiver_percentage": "0.50",
            "principal_waiver_percentage": "0.00",
            "total_installments": 2,
        },
        {
            "bucket_name": "3",
            "program_name": "R6",
            "is_covid_risky": False,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "1.00",
            "interest_waiver_percentage": "0.30",
            "principal_waiver_percentage": "0.00",
            "total_installments": 1,
        },
        {
            "bucket_name": "3",
            "program_name": "R6",
            "is_covid_risky": True,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "1.00",
            "interest_waiver_percentage": "0.30",
            "principal_waiver_percentage": "0.00",
            "total_installments": 1,
        },
        {
            "bucket_name": "3",
            "program_name": "R6",
            "is_covid_risky": False,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "1.00",
            "interest_waiver_percentage": "0.50",
            "principal_waiver_percentage": "0.00",
            "total_installments": 2,
        },
        {
            "bucket_name": "3",
            "program_name": "R6",
            "is_covid_risky": True,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "1.00",
            "interest_waiver_percentage": "0.50",
            "principal_waiver_percentage": "0.00",
            "total_installments": 2,
        },
        {
            "bucket_name": "3",
            "program_name": "R6",
            "is_covid_risky": False,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "1.00",
            "interest_waiver_percentage": "0.80",
            "principal_waiver_percentage": "0.00",
            "total_installments": 3,
        },
        {
            "bucket_name": "3",
            "program_name": "R6",
            "is_covid_risky": True,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "1.00",
            "interest_waiver_percentage": "0.80",
            "principal_waiver_percentage": "0.00",
            "total_installments": 3,
        },
        {
            "bucket_name": "4",
            "program_name": "R6",
            "is_covid_risky": False,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "1.00",
            "interest_waiver_percentage": "0.30",
            "principal_waiver_percentage": "0.00",
            "total_installments": 1,
        },
        {
            "bucket_name": "4",
            "program_name": "R6",
            "is_covid_risky": True,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "1.00",
            "interest_waiver_percentage": "0.30",
            "principal_waiver_percentage": "0.00",
            "total_installments": 1,
        },
        {
            "bucket_name": "4",
            "program_name": "R6",
            "is_covid_risky": False,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "1.00",
            "interest_waiver_percentage": "0.50",
            "principal_waiver_percentage": "0.00",
            "total_installments": 2,
        },
        {
            "bucket_name": "4",
            "program_name": "R6",
            "is_covid_risky": True,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "1.00",
            "interest_waiver_percentage": "0.50",
            "principal_waiver_percentage": "0.00",
            "total_installments": 2,
        },
        {
            "bucket_name": "4",
            "program_name": "R6",
            "is_covid_risky": False,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "1.00",
            "interest_waiver_percentage": "0.80",
            "principal_waiver_percentage": "0.00",
            "total_installments": 3,
        },
        {
            "bucket_name": "4",
            "program_name": "R6",
            "is_covid_risky": True,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "1.00",
            "interest_waiver_percentage": "0.80",
            "principal_waiver_percentage": "0.00",
            "total_installments": 3,
        },
        {
            "bucket_name": "5",
            "program_name": "R6",
            "is_covid_risky": False,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "1.00",
            "interest_waiver_percentage": "1.00",
            "principal_waiver_percentage": "0.00",
            "total_installments": 1,
        },
        {
            "bucket_name": "5",
            "program_name": "R6",
            "is_covid_risky": True,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "1.00",
            "interest_waiver_percentage": "1.00",
            "principal_waiver_percentage": "0.00",
            "total_installments": 1,
        },
        {
            "bucket_name": "6",
            "program_name": "R6",
            "is_covid_risky": False,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "1.00",
            "interest_waiver_percentage": "1.00",
            "principal_waiver_percentage": "0.00",
            "total_installments": 1,
        },
        {
            "bucket_name": "6",
            "program_name": "R6",
            "is_covid_risky": True,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "1.00",
            "interest_waiver_percentage": "1.00",
            "principal_waiver_percentage": "0.00",
            "total_installments": 1,
        },
        {
            "bucket_name": "Current",
            "program_name": "R6",
            "is_covid_risky": False,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "1.00",
            "interest_waiver_percentage": "0.20",
            "principal_waiver_percentage": "0.00",
            "total_installments": 1,
        },
        {
            "bucket_name": "Current",
            "program_name": "R6",
            "is_covid_risky": True,
            "partner_product": "normal",
            "late_fee_waiver_percentage": "1.00",
            "interest_waiver_percentage": "0.20",
            "principal_waiver_percentage": "0.00",
            "total_installments": 1,
        },
    ]

    def add_arguments(self, parser):
        parser.add_argument(
            '--recommendations', type=list, help='Pass recommendations data as an argument'
        )

    def handle(self, *args, **options):
        waiver_recommendations = options.get('recommendations') or self.default_args
        for waiver_recommendation in waiver_recommendations:
            try:
                self.stdout.write(
                    "updating partner_product {} program_name {} bucket_name {} is_covid_risky {} total_installments {}".format(
                    waiver_recommendation.get('partner_product', 'undefined'),
                    waiver_recommendation.get('program_name', 'undefined'),
                    waiver_recommendation.get('bucket_name', 'undefined'),
                    waiver_recommendation.get('is_covid_risky', 'undefined'),
                    waiver_recommendation.get('total_installments', 'undefined'),
                    )
                )
                waiver_recommendation = self.update_waiver_recommendation(waiver_recommendation)
            except Exception as e:
                self.stdout.write(self.style.ERROR(str(e)))
            else:
                self.stdout.write(
                    self.style.SUCCESS(
                        "waiver recommendation id {} is updated".format(str(waiver_recommendation))
                    )
                )
        return

    def update_waiver_recommendation(self, data):
        partner_product = data.get('partner_product', 'undefined')
        program_name = data.get('program_name', 'undefined')
        bucket_name = data.get('bucket_name', 'undefined')
        is_covid_risky = data.get('is_covid_risky', 'undefined')
        total_installments = data.get('total_installments', 'undefined')
        if not all(key in data for key in self.required_keys):
            raise Exception(
                "error key not found on partner_product {} program_name {} bucket_name {} is_covid_risky {} total_installments {}".format(
                partner_product,
                program_name,
                bucket_name,
                is_covid_risky,
                total_installments,
                )
            )

        percentages = {
            'late_fee_waiver_percentage': data.get('late_fee_waiver_percentage', '0.00'),
            'interest_waiver_percentage': data.get('interest_waiver_percentage', '0.00'),
            'principal_waiver_percentage': data.get('principal_waiver_percentage', '0.00'),
        }
        waiver_recommendation, created = WaiverRecommendation.objects.get_or_create(
            program_name=program_name,
            bucket_name=bucket_name,
            is_covid_risky=is_covid_risky,
            total_installments=total_installments,
            partner_product=partner_product,
            defaults=percentages,
        )
        if not created:
            waiver_recommendation.update_safely(**percentages)

        return waiver_recommendation
