# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-04-06 13:53
from __future__ import unicode_literals

from django.db import migrations, models
from juloserver.portal.object.product_profile.services import generate_product_lookup


AXIATA_PRODUCT = [{
    'code': 94,
    'name': 'AXIATA1',
    'min_amount': 1000000,
    'max_amount': 10000000,
    'min_duration': 1,
    'max_duration': 1,
    'min_interest_rate': 0.0,
    'max_interest_rate': 0.0,
    'interest_rate_increment': 0.0,
    'min_origination_fee': 0.02,
    'max_origination_fee': 0.02,
    'origination_fee_increment': 0.00,
    'cashback_initial': 0.00,
    'cashback_payment': 0.00,
    'late_fee': 0.00,
    'payment_frequency': 'Monthly',
    'debt_income_ratio': None,
    'is_initial': True,
    'is_active': True
}, {
    'code': 95,
    'name': 'AXIATA2',
    'min_amount': 1000000,
    'max_amount': 10000000,
    'min_duration': 1,
    'max_duration': 1,
    'min_interest_rate': 0.00,
    'max_interest_rate': 0.00,
    'interest_rate_increment': 0.0,
    'min_origination_fee': 0.02,
    'max_origination_fee': 0.02,
    'origination_fee_increment': 0.00,
    'cashback_initial': 0.00,
    'cashback_payment': 0.00,
    'late_fee': 0.00,
    'payment_frequency': 'Monthly',
    'debt_income_ratio': None,
    'is_initial': True,
    'is_active': True
}]

AXIATA_CUSTOMER = {
     'credit_score': ['A-', 'B+', 'B-']
}


def load_axiata_product(apps, schema_editor):
    ProductLine = apps.get_model("julo", "ProductLine")
    ProductLookup = apps.get_model("julo", "ProductLookup")
    ProductProfile = apps.get_model("julo", "ProductProfile")
    ProductCustomerCriteria = apps.get_model("julo", "ProductCustomerCriteria")
    Workflow = apps.get_model("julo", "Workflow")
    try:
        workflow = Workflow.objects.get(name='PartnerWorkflow')
    except:
        workflow = None

    for product in AXIATA_PRODUCT:
        product_profile = ProductProfile(**product)
        product_profile.save()

        # AXIATA customer criteria
        AXIATA_CUSTOMER['product_profile'] = product_profile
        product_customer_criteria = ProductCustomerCriteria(**AXIATA_CUSTOMER)
        product_customer_criteria.save()

        # AXIATA product_line
        product_line = ProductLine.objects.create(
            product_line_code=product_profile.code,
            product_line_type=product_profile.name,
            min_amount=product_profile.min_amount,
            max_amount=product_profile.max_amount,
            min_duration=product_profile.min_duration,
            max_duration=product_profile.max_duration,
            min_interest_rate=product_profile.min_interest_rate,
            max_interest_rate=product_profile.max_interest_rate,
            payment_frequency=product_profile.payment_frequency,
            product_profile=product_profile,
            default_workflow=workflow
        )

        # product lookup
        product_lookup_list = generate_product_lookup(product_profile, product_line)
        for product_lookup_data in product_lookup_list:
            product_lookup = ProductLookup(**product_lookup_data)
            product_lookup.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sdk', '0003_icare_productline'),
    ]

    operations = [
        migrations.RunPython(load_axiata_product, migrations.RunPython.noop),
    ]

2
