# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-07-09 04:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sdk', '0009_pede_new_productline'),
    ]

    operations = [
        migrations.CreateModel(
            name='AxiataCustomerData',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='axiata_customer_data_id', primary_key=True, serialize=False)),
                ('acceptance_date', models.DateTimeField(blank=True, null=True)),
                ('partner_application_date', models.DateTimeField(blank=True, null=True)),
                ('account_number', models.CharField(max_length=100, blank=True, null=True)),
                ('disbursement_date', models.DateTimeField(blank=True, null=True)),
                ('disbursement_time', models.TimeField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True)),
                ('first_payment_date', models.DateField(blank=True, null=True)),
                ('partner_score_grade', models.CharField(blank=True, max_length=50, null=True)),
                ('insurance_fee', models.BigIntegerField(default=0)),
                ('funder', models.IntegerField(default=0)),
                ('partner_product_line', models.CharField(max_length=50, blank=True, null=True)),
                ('fullname', models.CharField(blank=True, max_length=100, null=True)),
                ('ktp', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='characters not allowed', regex='^[ -~]+$'), django.core.validators.RegexValidator(message='KTP has to be 16 numeric digits', regex='^[0-9]{16}$')])),
                ('brand_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('business_category', models.CharField(blank=True, max_length=100, null=True)),
                ('type_of_business', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=50, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('address_street_num', models.TextField(blank=True, null=True)),
                ('shops_number', models.IntegerField(default=0)),
                ('distributor', models.IntegerField(default=0)),
                ('partner_id', models.CharField(blank=True, max_length=10, null=True)),
                ('interest_rate', models.FloatField(default=0)),
                ('loan_amount', models.BigIntegerField(default=0)),
                ('loan_duration', models.IntegerField(default=0)),
                ('loan_duration_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('monthly_installment', models.FloatField(default=0)),
                ('final_monthly_installment', models.FloatField(default=0)),
                ('reject_reason', models.TextField(blank=True, null=True)),
                ('application', models.OneToOneField(blank=True, db_column='application_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Application')),
            ],
            options={
                'db_table': 'axiata_customer_data',
            },
        ),
    ]
