# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-04-06 13:53
from __future__ import unicode_literals

from django.db import migrations


def add_axiata_bank_account_status(apps, schema_editor):
    Workflow = apps.get_model("julo", "Workflow")
    workflow = Workflow.objects.filter(name="PartnerWorkflow").first()
    if workflow:
        WorkflowStatusPath = apps.get_model("julo", "WorkflowStatusPath")
        DATA = [{"status_previous": 148, "status_next": 177}]
        for path in DATA:
            WorkflowStatusPath.objects.get_or_create(
                status_previous=path['status_previous'],
                status_next=path['status_next'],
                type="happy",
                workflow=workflow
            )


class Migration(migrations.Migration):

    dependencies = [
        ('sdk', '0012_axita_change_several_field_type'),
    ]

    operations = [
        migrations.RunPython(add_axiata_bank_account_status, migrations.RunPython.noop),
    ]
