# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-08-14 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdk', '0016_axiatarepaymentdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axiatarepaymentdata',
            name='application_xid',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='axiatarepaymentdata',
            name='payment_number',
            field=models.BigIntegerField(default=0),
        ),
    ]
