# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-04-03 13:01
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paylater', '0003_model_final'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineinvoicedetail',
            old_name='ext_transaction_id',
            new_name='transaction_xid',
        ),
        migrations.AlterField(
            model_name='lineinvoicedetail',
            name='invoice_amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lineinvoicedetail',
            name='items',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='lineinvoicedetail',
            name='line_invoice',
            field=models.ForeignKey(db_column='line_invoice_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoice_details', to='paylater.LineInvoice'),
        ),
    ]
