# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-04-04 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paylater', '0006_set_default_value_line_statement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='type',
        ),
        migrations.AlterField(
            model_name='line',
            name='credit_score',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
