# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-04-05 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paylater', '0009_auto_20190405_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineinvoice',
            name='customer',
        ),
    ]
