# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-04-05 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paylater', '0008_auto_20190404_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linesubscription',
            name='available_limit',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='linesubscription',
            name='limit',
            field=models.BigIntegerField(default=0),
        ),
    ]
