# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-04-07 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paylater', '0017_auto_20190407_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanone',
            old_name='loan_one_status_code',
            new_name='loan_one_status',
        ),
        migrations.RenameField(
            model_name='statement',
            old_name='statement_status_code',
            new_name='statement_status',
        ),
        migrations.RemoveField(
            model_name='paymentschedule',
            name='status_code',
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='status',
            field=models.ForeignKey(blank=True, db_column='status_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.StatusLookup'),
        ),
    ]
