# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-04-09 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paylater', '0019_transactionone_invoice_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanone',
            name='refund_amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
