# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-04-10 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paylater', '0020_loanone_refund_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcreditlimit',
            name='agreement_accepted_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountcreditlimit',
            name='callback_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
