# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-02 08:47
from __future__ import unicode_literals

import string
import secrets
from django.db import migrations
from django.contrib.auth.models import User


def generate_strong_password(length=12):
    characters = string.ascii_letters + string.digits + '#$%&?@'
    password = ''.join(secrets.choice(characters) for _ in range(length))
    return password

def create_bukalapak_dummy_user(apps, schema_editor):
    username = 'dummy_bukalapak_basic_auth'
    #edit with real data by django admin
    if not User.objects.filter(username=username).exists():
        user = User.objects.create(
            username=username,
            email="dummy_basic_auth@bukalapak.com",
            first_name="dummy",
            last_name="paylater_basid_auth",
            password=generate_strong_password(),
        )
        user.save()


class Migration(migrations.Migration):
    initial = True

    dependencies = [('paylater', '0021_auto_20190410_1301')]

    operations = [
        migrations.RunPython(create_bukalapak_dummy_user, migrations.RunPython.noop)
    ]
