# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-04-10 07:17
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paylater', '0022_dummy_bukalapak_callbak_basic_auth_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcreditlimit',
            name='callback_response',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountcreditlimit',
            name='scrap_data_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
