# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-04-15 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disbursement', '0005_auto_20190212_1217'),
        ('paylater', '0023_auto_20190410_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionRefundDetail',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='transaction_refund_id', primary_key=True, serialize=False)),
                ('refund_amount', models.BigIntegerField(default=0)),
                ('disbursement', models.ForeignKey(blank=True, db_column='disbursement_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='disbursement.Disbursement')),
                ('invoice', models.ForeignKey(db_column='invoice_id', on_delete=django.db.models.deletion.DO_NOTHING, to='paylater.Invoice')),
                ('invoice_detail', models.ForeignKey(db_column='invoice_detail_id', on_delete=django.db.models.deletion.DO_NOTHING, to='paylater.InvoiceDetail')),
                ('loan_one', models.ForeignKey(db_column='loan_one_id', on_delete=django.db.models.deletion.DO_NOTHING, to='paylater.LoanOne')),
                ('transaction', models.OneToOneField(db_column='transaction_one_id', on_delete=django.db.models.deletion.DO_NOTHING, to='paylater.TransactionOne')),
            ],
            options={
                'db_table': 'transaction_refund_detail',
            },
        ),
    ]
