# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-04-21 09:02
from __future__ import unicode_literals

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paylater', '0024_transactionrefunddetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementHistory',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='statement_history_id', primary_key=True, serialize=False)),
                ('status_old', models.IntegerField()),
                ('status_new', models.IntegerField()),
                ('change_reason', models.TextField(default='system_triggered')),
                ('changed_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statement_status_changes', to=settings.AUTH_USER_MODEL)),
                ('statement', models.ForeignKey(db_column='statement_id', on_delete=django.db.models.deletion.DO_NOTHING, to='paylater.Statement')),
            ],
            options={
                'db_table': 'statement_history',
            },
        ),
    ]
