# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-04-25 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paylater', '0027_disbursementsummary'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='disbursementsummary',
            unique_together=set([('transaction_date', 'partner')]),
        ),
    ]
