# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-05-01 09:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paylater', '0029_bank_account_init'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursementsummary',
            name='disburse_by',
            field=models.ForeignKey(blank=True, db_column='disburse_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='disbursementsummary',
            name='partner',
            field=models.ForeignKey(blank=True, db_column='partner_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Partner'),
        ),
    ]
