# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-09-06 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paylater', '0047_feature_suspend_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='partner_transaction_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
