# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-10-03 02:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paylater', '0051_data_initialcreditlimit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialcreditlimit',
            name='initial_credit_limit',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(3000000)]),
        ),
    ]
