# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-10-11 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paylater', '0054_add_constraint_disbursement_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursementsummary',
            name='product_line',
            field=models.ForeignKey(blank=True, db_column='product_line_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.ProductLine'),
        ),
    ]
