# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-03-04 10:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('julo', '0375_add_digisign_mode_in_mobile_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanAgentAssignment',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='loan_agent_assignment_id', primary_key=True, serialize=False)),
                ('collect_date', models.DateField(blank=True, null=True)),
                ('assign_time', models.DateTimeField(blank=True, null=True)),
                ('unassign_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('agent', models.ForeignKey(blank=True, db_column='agent_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(blank=True, db_column='application_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Application')),
                ('loan', models.ForeignKey(blank=True, db_column='loan_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Loan')),
            ],
            options={
                'db_table': 'loan_agent_assignment',
            },
        ),
        migrations.RunSQL(
            "ALTER TABLE loan_agent_assignment ALTER COLUMN loan_id TYPE bigint;"),
        migrations.RunSQL(
            "ALTER TABLE loan_agent_assignment ALTER COLUMN application_id TYPE bigint;"),
    ]
