# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-07-01 01:49
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.payment_methods import SecondaryMethodName


def insert_payment_method_settings(apps, schema_editor):
    MobileFeatureSetting = apps.get_model("julo", "MobileFeatureSetting")
    for payment_method in SecondaryMethodName:
        MobileFeatureSetting.objects.create(
            feature_name=payment_method.lower(),
            is_active=True
        )


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0688_alter_field_to_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MobilePaymentMethods',
        ),

        migrations.RunPython(
            insert_payment_method_settings
        ),
    ]
