from __future__ import unicode_literals

from .base import DropDownBase


class BirthplaceDropDown(DropDownBase):
    dropdown = "birthplace"
    version = 1
    file_name = "birthplace.json"

    # Please Always Upgrade Version if there is changes on data
    DATA = [
        "Aceh Barat",
        "Aceh Barat Daya",
        "Aceh Besar",
        "Aceh Jaya",
        "Aceh Selatan",
        "Aceh Singkil",
        "Aceh Tamiang",
        "Aceh Tengah",
        "Aceh Tenggara",
        "Aceh Timur",
        "Aceh Utara",
        "Agam",
        "Alor",
        "Ambon",
        "Asahan",
        "Asmat",
        "Badung",
        "Balangan",
        "Balikpapan",
        "Banda Aceh",
        "Bandar Lampung",
        "Bandung",
        "Bandung Barat",
        "Banggai",
        "Banggai Kepulauan",
        "Banggai Laut",
        "Bangka",
        "Bangka Barat",
        "Bangka Selatan",
        "Bangka Tengah",
        "Bangkalan",
        "Bangli",
        "Banjar",
        "Banjarbaru",
        "Banjarmasin",
        "Banjarnegara",
        "Bantaeng",
        "Bantul",
        "Banyuasin",
        "Banyumas",
        "Banyuwangi",
        "Barito Kuala",
        "Barito Selatan",
        "Barito Timur",
        "Barito Utara",
        "Barru",
        "Batam",
        "Batang",
        "Batang Hari",
        "Batu",
        "Batu Bara",
        "Bau-Bau",
        "Bekasi",
        "Belitung",
        "Belitung Timur",
        "Belu",
        "Bener Meriah",
        "Bengkalis",
        "Bengkayang",
        "Bengkulu",
        "Bengkulu Selatan",
        "Bengkulu Tengah",
        "Bengkulu Utara",
        "Berau",
        "Biak Numfor",
        "Bima",
        "Binjai",
        "Bintan",
        "Bireuen",
        "Bitung",
        "Blitar",
        "Blora",
        "Boalemo",
        "Bogor",
        "Bojonegoro",
        "Bolaang Mongondow",
        "Bolaang Mongondow Selatan",
        "Bolaang Mongondow Timur",
        "Bolaang Mongondow Utara",
        "Bombana",
        "Bondowoso",
        "Bone",
        "Bone Bolango",
        "Bontang",
        "Boven Digoel",
        "Boyolali",
        "Brebes",
        "Bukittinggi",
        "Buleleng",
        "Bulukumba",
        "Bulungan",
        "Bungo",
        "Buol",
        "Buru",
        "Buru Selatan",
        "Buton",
        "Buton Selatan",
        "Buton Tengah",
        "Buton Utara",
        "Ciamis",
        "Cianjur",
        "Cilacap",
        "Cilegon",
        "Cimahi",
        "Cirebon",
        "Dairi",
        "Deiyai",
        "Deli Serdang",
        "Demak",
        "Denpasar",
        "Depok",
        "Dharmasraya",
        "Dogiyai",
        "Dompu",
        "Donggala",
        "Dumai",
        "Empat Lawang",
        "Ende",
        "Ende",
        "Enrekang",
        "Fakfak",
        "Flores Timur",
        "Flores Timur",
        "Garut",
        "Gayo Lues",
        "Gianyar",
        "Gorontalo",
        "Gorontalo Utara",
        "Gowa",
        "Grand Total",
        "Gresik",
        "Grobogan",
        "Gunung Kidul",
        "Gunung Mas",
        "Gunungsitoli",
        "Halmahera Barat",
        "Halmahera Selatan",
        "Halmahera Tengah",
        "Halmahera Timur",
        "Halmahera Utara",
        "Hulu Sungai Selatan",
        "Hulu Sungai Tengah",
        "Hulu Sungai Utara",
        "Humbang Hasundutan",
        "Indragiri Hilir",
        "Indragiri Hulu",
        "Indramayu",
        "Intan Jaya",
        "Jakarta",
        "Jambi",
        "Jayapura",
        "Jayawijaya",
        "Jember",
        "Jembrana",
        "Jeneponto",
        "Jepara",
        "Jombang",
        "Kaimana",
        "Kampar",
        "Kapuas",
        "Kapuas Hulu",
        "Karanganyar",
        "Karangasem",
        "Karawang",
        "Karimun",
        "Karo",
        "Katingan",
        "Kaur",
        "Kayong Utara",
        "Kebumen",
        "Kediri",
        "Keerom",
        "Kendal",
        "Kendari",
        "Kepahiang",
        "Kepulauan Anambas",
        "Kepulauan Aru",
        "Kepulauan Mentawai",
        "Kepulauan Meranti",
        "Kepulauan Sangihe",
        "Kepulauan Selayar",
        "Kepulauan Seribu",
        "Kepulauan Siau Tagulandang Biaro (Sitaro)",
        "Kepulauan Sula",
        "Kepulauan Talaud",
        "Kepulauan Yapen",
        "Kerinci",
        "Ketapang",
        "Klaten",
        "Klungkung",
        "Kolaka",
        "Kolaka Timur",
        "Kolaka Utara",
        "Konawe",
        "Konawe Kepulauan",
        "Konawe Selatan",
        "Konawe Utara",
        "Kotabaru",
        "Kotamobagu",
        "Kotawaringin Barat",
        "Kotawaringin Timur",
        "Kuantan Singingi",
        "Kubu Raya",
        "Kudus",
        "Kulon Progo",
        "Kuningan",
        "Kupang",
        "Kutai Barat",
        "Kutai Kartanegara",
        "Kutai Timur",
        "Labuhanbatu",
        "Labuhanbatu Selatan",
        "Labuhanbatu Utara",
        "Lahat",
        "Lamandau",
        "Lamongan",
        "Lampung Barat",
        "Lampung Selatan",
        "Lampung Tengah",
        "Lampung Timur",
        "Lampung Utara",
        "Landak",
        "Langkat",
        "Lanny Jaya",
        "Lebak",
        "Lebong",
        "Lembata",
        "Lhokseumawe",
        "Lima Puluh Kota",
        "Lingga",
        "Lombok Barat",
        "Lombok Tengah",
        "Lombok Timur",
        "Lombok Utara",
        "Lubuk Linggau",
        "Lumajang",
        "Luwu",
        "Luwu Timur",
        "Luwu Utara",
        "Madiun",
        "Magelang",
        "Magetan",
        "Mahakam Ulu",
        "Majalengka",
        "Majene",
        "Makassar",
        "Malaka",
        "Malang",
        "Malinau",
        "Maluku Barat Daya",
        "Maluku Tengah",
        "Maluku Tenggara",
        "Maluku Tenggara Barat",
        "Mamasa",
        "Mamberamo Raya",
        "Mamberamo Tengah",
        "Mamuju",
        "Mamuju Tengah",
        "Mamuju Utara",
        "Manado",
        "Mandailing Natal",
        "Manggarai",
        "Manggarai Barat",
        "Manggarai Timur",
        "Manokwari",
        "Manokwari Selatan",
        "Mappi",
        "Maros",
        "Mataram",
        "Maybrat",
        "Medan",
        "Melawi",
        "Mempawah",
        "Merangin",
        "Merauke",
        "Mesuji",
        "Metro",
        "Mimika",
        "Minahasa",
        "Minahasa Selatan",
        "Minahasa Tenggara",
        "Minahasa Utara",
        "Mojokerto",
        "Morowali",
        "Morowali Utara",
        "Muara Enim",
        "Muaro Jambi",
        "Muko Muko",
        "Muna",
        "Muna Barat",
        "Murung Raya",
        "Musi Banyuasin",
        "Musi Rawas",
        "Musi Rawas Utara",
        "Nabire",
        "Nagan Raya",
        "Nagekeo",
        "Natuna",
        "Nduga",
        "Ngada",
        "Nganjuk",
        "Ngawi",
        "Nias",
        "Nias Barat",
        "Nias Selatan",
        "Nias Utara",
        "Nunukan",
        "Ogan Ilir",
        "Ogan Komering Ilir",
        "Ogan Komering Ulu",
        "Ogan Komering Ulu Selatan",
        "Ogan Komering Ulu Timur",
        "Pacitan",
        "Padang",
        "Padang Lawas",
        "Padang Lawas Utara",
        "Padang Panjang",
        "Padang Pariaman",
        "Padang Sidempuan",
        "Pagar Alam",
        "Pakpak Bharat",
        "Palangka Raya",
        "Palembang",
        "Palopo",
        "Palu",
        "Pamekasan",
        "Pandeglang",
        "Pangandaran",
        "Pangkajene Kepulauan",
        "Pangkal Pinang",
        "Paniai",
        "Parepare",
        "Pariaman",
        "Parigi Moutong",
        "Pasaman",
        "Pasaman Barat",
        "Paser",
        "Pasuruan",
        "Pati",
        "Payakumbuh",
        "Pegunungan Arfak",
        "Pegunungan Bintang",
        "Pekalongan",
        "Pekanbaru",
        "Pelalawan",
        "Pemalang",
        "Pematang Siantar",
        "Penajam Paser Utara",
        "Penukal Abab Lematang Ilir",
        "Pesawaran",
        "Pesisir Barat",
        "Pesisir Selatan",
        "Pidie",
        "Pidie Jaya",
        "Pinrang",
        "Pohuwato",
        "Polewali Mandar",
        "Ponorogo",
        "Pontianak",
        "Poso",
        "Prabumulih",
        "Pringsewu",
        "Probolinggo",
        "Pulang Pisau",
        "Pulau Morotai",
        "Pulau Taliabu",
        "Puncak",
        "Puncak Jaya",
        "Purbalingga",
        "Purwakarta",
        "Purworejo",
        "Raja Ampat",
        "Rejang Lebong",
        "Rembang",
        "Rokan Hilir",
        "Rokan Hulu",
        "Rote Ndao",
        "Sabang",
        "Sabu Raijua",
        "Salatiga",
        "Samarinda",
        "Sambas",
        "Samosir",
        "Sampang",
        "Sanggau",
        "Sarmi",
        "Sarolangun",
        "Sawah Lunto",
        "Sekadau",
        "Seluma",
        "Semarang",
        "Seram Bagian Barat",
        "Seram Bagian Timur",
        "Serang",
        "Serdang Bedagai",
        "Seruyan",
        "Siak",
        "Sibolga",
        "Sidenreng Rappang",
        "Sidoarjo",
        "Sigi",
        "Sijunjung",
        "Sikka",
        "Simalungun",
        "Simeulue",
        "Singkawang",
        "Sinjai",
        "Sintang",
        "Situbondo",
        "Sleman",
        "Solok",
        "Solok Selatan",
        "Soppeng",
        "Sorong",
        "Sorong Selatan",
        "Sragen",
        "Subang",
        "Subulussalam",
        "Sukabumi",
        "Sukamara",
        "Sukoharjo",
        "Sumba Barat",
        "Sumba Barat Daya",
        "Sumba Tengah",
        "Sumba Timur",
        "Sumbawa",
        "Sumbawa Barat",
        "Sumedang",
        "Sumenep",
        "Sungaipenuh",
        "Supiori",
        "Surabaya",
        "Surakarta",
        "Tabalong",
        "Tabanan",
        "Takalar",
        "Tambrauw",
        "Tana Tidung",
        "Tana Toraja",
        "Tanah Bumbu",
        "Tanah Datar",
        "Tanah Laut",
        "Tangerang",
        "Tangerang Selatan",
        "Tanggamus",
        "Tanjung Balai",
        "Tanjung Jabung Barat",
        "Tanjung Jabung Timur",
        "Tanjung Pinang",
        "Tapanuli Selatan",
        "Tapanuli Tengah",
        "Tapanuli Utara",
        "Tapin",
        "Tarakan",
        "Tasikmalaya",
        "Tebing Tinggi",
        "Tebo",
        "Tegal",
        "Teluk Bintuni",
        "Teluk Wondama",
        "Temanggung",
        "Ternate",
        "Tidore Kepulauan",
        "Timor Tengah Selatan",
        "Timor Tengah Utara",
        "Toba Samosir",
        "Tojo Una-Una",
        "Toli-Toli",
        "Tolikara",
        "Tomohon",
        "Toraja Utara",
        "Trenggalek",
        "Tual",
        "Tuban",
        "Tulang Bawang",
        "Tulang Bawang Barat",
        "Tulungagung",
        "Wajo",
        "Wakatobi",
        "Waropen",
        "Way Kanan",
        "Wonogiri",
        "Wonosobo",
        "Yahukimo",
        "Yalimo",
        "Yogyakarta",
    ]
