from __future__ import unicode_literals
import random
import json

from .base import DropDownBase


class JobDropDown(DropDownBase):
    dropdown = "jobs"
    version = 5
    file_name = "jobs.json"

    # Please Always Upgrade Version if there is changes on data
    DATA = [
        "Admin / Finance / HR,Admin",
        "Admin / Finance / HR,Akuntan / Finance",
        "Admin / Finance / HR,HR",
        "Admin / Finance / HR,Office Boy",
        "Admin / Finance / HR,Sekretaris",
        "Design / Seni,Design Grafis",
        "Design / Seni,Pelukis",
        "Design / Seni,Photographer",
        "Entertainment / Event,DJ / Musisi",
        "Entertainment / Event,Event Organizer",
        "Entertainment / Event,Kameraman",
        "Entertainment / Event,Penyanyi / Penari / Model",
        "Entertainment / Event,Produser / Sutradara",
        "Hukum / Security / Politik,Anggota Pemerintahan",
        "Hukum / Security / Politik,Hakim / Jaksa / Pengacara",
        "Hukum / Security / Politik,Notaris",
        "Hukum / Security / Politik,Ormas",
        "Hukum / Security / Politik,Pemuka Agama",
        "Hukum / Security / Politik,Satpam",
        "Hukum / Security / Politik,TNI / Polisi",
        "Kesehatan,Apoteker",
        "Kesehatan,Dokter",
        "Kesehatan,Perawat",
        "Kesehatan,Teknisi Laboratorium",
        "Konstruksi / Real Estate,Arsitek / Tehnik Sipil",
        "Konstruksi / Real Estate,Interior Designer",
        "Konstruksi / Real Estate,Mandor",
        "Konstruksi / Real Estate,Pemborong",
        "Konstruksi / Real Estate,Proyek Manager / Surveyor",
        "Konstruksi / Real Estate,Real Estate Broker",
        "Konstruksi / Real Estate,Tukang Bangunan",
        "Media,Kameraman",
        "Media,Penulis / Editor",
        "Media,Wartawan",
        "Pabrik / Gudang,Buruh Pabrik / Gudang",
        "Pabrik / Gudang,Kepala Pabrik / Gudang",
        "Pabrik / Gudang,Teknisi Mesin",
        "Pendidikan,Dosen",
        "Pendidikan,Guru",
        "Pendidikan,Instruktur / Pembimbing Kursus",
        "Pendidikan,Kepala Sekolah",
        "Pendidikan,Tata Usaha",
        "Perawatan Tubuh,Fashion Designer",
        "Perawatan Tubuh,Gym / Fitness",
        "Perawatan Tubuh,Pelatih / Trainer",
        "Perawatan Tubuh,Salon / Spa / Panti Pijat",
        "Perbankan,Back-office",
        "Perbankan,Bank Teller",
        "Perbankan,CS Bank",
        "Perbankan,Credit Analyst",
        "Perbankan,Kolektor",
        "Perbankan,Resepsionis",
        "Sales / Marketing,Account Executive / Manager",
        "Sales / Marketing,Salesman",
        "Sales / Marketing,SPG",
        "Sales / Marketing,Telemarketing",
        "Service,Customer Service",
        "Service,Kasir",
        "Service,Kebersihan",
        "Service,Koki",
        "Service,Pelayan / Pramuniaga",
        "Tehnik / Computer,Engineer / Ahli Tehnik",
        "Tehnik / Computer,Penulis Teknikal",
        "Tehnik / Computer,Programmer / Developer",
        "Tehnik / Computer,R&D / Ilmuwan / Peneliti",
        "Tehnik / Computer,Warnet",
        "Tehnik / Computer,Otomotif",
        "Transportasi,Supir / Ojek",
        "Transportasi,Agen Perjalanan",
        "Transportasi,Kurir / Ekspedisi",
        "Transportasi,Pelaut / Staff Kapal / Nahkoda Kapal",
        "Transportasi,Pilot / Staff Penerbangan",
        "Transportasi,Sewa Kendaraan",
        "Transportasi,Masinis / Kereta Api",
        "Staf Rumah Tangga,Babysitter / Perawat",
        "Staf Rumah Tangga,Pembantu Rumah Tangga",
        "Staf Rumah Tangga,Supir",
        "Staf Rumah Tangga,Tukang Kebun",
        "Perhotelan,Customer Service",
        "Perhotelan,Kebersihan",
        "Perhotelan,Koki",
        "Perhotelan,Room Service / Pelayan",
    ]

    LAINNYA_DATA = [
        "Admin / Finance / HR,Lainnya",
        "Design / Seni,Lainnya",
        "Entertainment / Event,Lainnya",
        "Hukum / Security / Politik,Lainnya",
        "Kesehatan,Lainnya",
        "Konstruksi / Real Estate,Lainnya",
        "Media,Lainnya",
        "Pabrik / Gudang,Lainnya",
        "Pendidikan,Lainnya",
        "Perawatan Tubuh,Lainnya",
        "Perbankan,Lainnya",
        "Sales / Marketing,Lainnya",
        "Service,Lainnya",
        "Tehnik / Computer,Lainnya",
        "Transportasi,Lainnya",
        "Staf Rumah Tangga,Lainnya",
        "Perhotelan,Lainnya",
    ]

    def _get_data(self, product_line_code, randomize=False):
        if randomize:
            random.shuffle(self.DATA)

        data = {'version': self.version, 'data': self.DATA + self.LAINNYA_DATA}

        return json.dumps(data)

    def convert_to_dict_format(self):
        data = {}
        for job in (self.DATA + self.LAINNYA_DATA):
            job_industry, job_description = job.split(',')
            current_job_description = data.setdefault(job_industry, [])
            current_job_description.append(job_description)

        return data


class JobDropDownV2(JobDropDown):
    version = 6
    DATA = [
        "Pegawai negeri,Admin / Finance / HR,Admin",
        "Pegawai swasta,Admin / Finance / HR,Admin",
        "Pengusaha,Admin / Finance / HR,Admin",
        "Freelance,Admin / Finance / HR,Admin",
        "Staf rumah tangga,Staf rumah tangga,",
        "Ibu rumah tangga,,",
        "Mahasiswa,,",
        "Tidak bekerja,,",
        "Pegawai negeri,Admin / Finance / HR,Akuntan / Finance",
        "Pegawai swasta,Admin / Finance / HR,Akuntan / Finance",
        "Pengusaha,Admin / Finance / HR,Akuntan / Finance",
        "Freelance,Admin / Finance / HR,Akuntan / Finance",
        "Pegawai negeri,Admin / Finance / HR,HR",
        "Pegawai swasta,Admin / Finance / HR,HR",
        "Pengusaha,Admin / Finance / HR,HR",
        "Freelance,Admin / Finance / HR,HR",
        "Pegawai negeri,Admin / Finance / HR,Office Boy",
        "Pegawai swasta,Admin / Finance / HR,Office Boy",
        "Pengusaha,Admin / Finance / HR,Office Boy",
        "Freelance,Admin / Finance / HR,Office Boy",
        "Pegawai negeri,Admin / Finance / HR,Sekretaris",
        "Pegawai swasta,Admin / Finance / HR,Sekretaris",
        "Pengusaha,Admin / Finance / HR,Sekretaris",
        "Freelance,Admin / Finance / HR,Sekretaris",
        "Pegawai negeri,Design / Seni,Design Grafis",
        "Pegawai swasta,Design / Seni,Design Grafis",
        "Pengusaha,Design / Seni,Design Grafis",
        "Freelance,Design / Seni,Design Grafis",
        "Pegawai negeri,Design / Seni,Pelukis",
        "Pegawai swasta,Design / Seni,Pelukis",
        "Pengusaha,Design / Seni,Pelukis",
        "Freelance,Design / Seni,Pelukis",
        "Pegawai negeri,Design / Seni,Photographer",
        "Pegawai swasta,Design / Seni,Photographer",
        "Pengusaha,Design / Seni,Photographer",
        "Freelance,Design / Seni,Photographer",
        "Pegawai negeri,Entertainment / Event,DJ / Musisi",
        "Pegawai swasta,Entertainment / Event,DJ / Musisi",
        "Pengusaha,Entertainment / Event,DJ / Musisi",
        "Freelance,Entertainment / Event,DJ / Musisi",
        "Pegawai negeri,Entertainment / Event,Event Organizer",
        "Pegawai swasta,Entertainment / Event,Event Organizer",
        "Pengusaha,Entertainment / Event,Event Organizer",
        "Freelance,Entertainment / Event,Event Organizer",
        "Pegawai negeri,Entertainment / Event,Kameraman",
        "Pegawai swasta,Entertainment / Event,Kameraman",
        "Pengusaha,Entertainment / Event,Kameraman",
        "Freelance,Entertainment / Event,Kameraman",
        "Pegawai negeri,Entertainment / Event,Penyanyi / Penari / Model",
        "Pegawai swasta,Entertainment / Event,Penyanyi / Penari / Model",
        "Pengusaha,Entertainment / Event,Penyanyi / Penari / Model",
        "Freelance,Entertainment / Event,Penyanyi / Penari / Model",
        "Pegawai negeri,Entertainment / Event,Produser / Sutradara",
        "Pegawai swasta,Entertainment / Event,Produser / Sutradara",
        "Pengusaha,Entertainment / Event,Produser / Sutradara",
        "Freelance,Entertainment / Event,Produser / Sutradara",
        "Pegawai negeri,Hukum / Security / Politik,Anggota Pemerintahan",
        "Pegawai swasta,Hukum / Security / Politik,Anggota Pemerintahan",
        "Pengusaha,Hukum / Security / Politik,Anggota Pemerintahan",
        "Freelance,Hukum / Security / Politik,Anggota Pemerintahan",
        "Pegawai negeri,Hukum / Security / Politik,Hakim / Jaksa / Pengacara",
        "Pegawai swasta,Hukum / Security / Politik,Hakim / Jaksa / Pengacara",
        "Pengusaha,Hukum / Security / Politik,Hakim / Jaksa / Pengacara",
        "Freelance,Hukum / Security / Politik,Hakim / Jaksa / Pengacara",
        "Pegawai negeri,Hukum / Security / Politik,Notaris",
        "Pegawai swasta,Hukum / Security / Politik,Notaris",
        "Pengusaha,Hukum / Security / Politik,Notaris",
        "Freelance,Hukum / Security / Politik,Notaris",
        "Pegawai negeri,Hukum / Security / Politik,Ormas",
        "Pegawai swasta,Hukum / Security / Politik,Ormas",
        "Pengusaha,Hukum / Security / Politik,Ormas",
        "Freelance,Hukum / Security / Politik,Ormas",
        "Pegawai negeri,Hukum / Security / Politik,Pemuka Agama",
        "Pegawai swasta,Hukum / Security / Politik,Pemuka Agama",
        "Pengusaha,Hukum / Security / Politik,Pemuka Agama",
        "Freelance,Hukum / Security / Politik,Pemuka Agama",
        "Pegawai negeri,Hukum / Security / Politik,Satpam",
        "Pegawai swasta,Hukum / Security / Politik,Satpam",
        "Pengusaha,Hukum / Security / Politik,Satpam",
        "Freelance,Hukum / Security / Politik,Satpam",
        "Pegawai negeri,Hukum / Security / Politik,TNI / Polisi",
        "Pegawai swasta,Hukum / Security / Politik,TNI / Polisi",
        "Pengusaha,Hukum / Security / Politik,TNI / Polisi",
        "Freelance,Hukum / Security / Politik,TNI / Polisi",
        "Pegawai negeri,Kesehatan,Apoteker",
        "Pegawai swasta,Kesehatan,Apoteker",
        "Pengusaha,Kesehatan,Apoteker",
        "Freelance,Kesehatan,Apoteker",
        "Pegawai negeri,Kesehatan,Dokter",
        "Pegawai swasta,Kesehatan,Dokter",
        "Pengusaha,Kesehatan,Dokter",
        "Freelance,Kesehatan,Dokter",
        "Pegawai negeri,Kesehatan,Perawat",
        "Pegawai swasta,Kesehatan,Perawat",
        "Pengusaha,Kesehatan,Perawat",
        "Freelance,Kesehatan,Perawat",
        "Pegawai negeri,Kesehatan,Teknisi Laboratorium",
        "Pegawai swasta,Kesehatan,Teknisi Laboratorium",
        "Pengusaha,Kesehatan,Teknisi Laboratorium",
        "Freelance,Kesehatan,Teknisi Laboratorium",
        "Pegawai negeri,Konstruksi / Real Estate,Arsitek / Tehnik Sipil",
        "Pegawai swasta,Konstruksi / Real Estate,Arsitek / Tehnik Sipil",
        "Pengusaha,Konstruksi / Real Estate,Arsitek / Tehnik Sipil",
        "Freelance,Konstruksi / Real Estate,Arsitek / Tehnik Sipil",
        "Pegawai negeri,Konstruksi / Real Estate,Interior Designer",
        "Pegawai swasta,Konstruksi / Real Estate,Interior Designer",
        "Pengusaha,Konstruksi / Real Estate,Interior Designer",
        "Freelance,Konstruksi / Real Estate,Interior Designer",
        "Pegawai negeri,Konstruksi / Real Estate,Mandor",
        "Pegawai swasta,Konstruksi / Real Estate,Mandor",
        "Pengusaha,Konstruksi / Real Estate,Mandor",
        "Freelance,Konstruksi / Real Estate,Mandor",
        "Pegawai negeri,Konstruksi / Real Estate,Pemborong",
        "Pegawai swasta,Konstruksi / Real Estate,Pemborong",
        "Pengusaha,Konstruksi / Real Estate,Pemborong",
        "Freelance,Konstruksi / Real Estate,Pemborong",
        "Pegawai negeri,Konstruksi / Real Estate,Proyek Manager / Surveyor",
        "Pegawai swasta,Konstruksi / Real Estate,Proyek Manager / Surveyor",
        "Pengusaha,Konstruksi / Real Estate,Proyek Manager / Surveyor",
        "Freelance,Konstruksi / Real Estate,Proyek Manager / Surveyor",
        "Pegawai negeri,Konstruksi / Real Estate,Real Estate Broker",
        "Pegawai swasta,Konstruksi / Real Estate,Real Estate Broker",
        "Pengusaha,Konstruksi / Real Estate,Real Estate Broker",
        "Freelance,Konstruksi / Real Estate,Real Estate Broker",
        "Pegawai negeri,Konstruksi / Real Estate,Tukang Bangunan",
        "Pegawai swasta,Konstruksi / Real Estate,Tukang Bangunan",
        "Pengusaha,Konstruksi / Real Estate,Tukang Bangunan",
        "Freelance,Konstruksi / Real Estate,Tukang Bangunan",
        "Pegawai negeri,Media,Kameraman",
        "Pegawai swasta,Media,Kameraman",
        "Pengusaha,Media,Kameraman",
        "Freelance,Media,Kameraman",
        "Pegawai negeri,Media,Penulis / Editor",
        "Pegawai swasta,Media,Penulis / Editor",
        "Pengusaha,Media,Penulis / Editor",
        "Freelance,Media,Penulis / Editor",
        "Pegawai negeri,Media,Wartawan",
        "Pegawai swasta,Media,Wartawan",
        "Pengusaha,Media,Wartawan",
        "Freelance,Media,Wartawan",
        "Pegawai negeri,Pabrik / Gudang,Buruh Pabrik / Gudang",
        "Pegawai swasta,Pabrik / Gudang,Buruh Pabrik / Gudang",
        "Pengusaha,Pabrik / Gudang,Buruh Pabrik / Gudang",
        "Freelance,Pabrik / Gudang,Buruh Pabrik / Gudang",
        "Pegawai negeri,Pabrik / Gudang,Kepala Pabrik / Gudang",
        "Pegawai swasta,Pabrik / Gudang,Kepala Pabrik / Gudang",
        "Pengusaha,Pabrik / Gudang,Kepala Pabrik / Gudang",
        "Freelance,Pabrik / Gudang,Kepala Pabrik / Gudang",
        "Pegawai negeri,Pabrik / Gudang,Teknisi Mesin",
        "Pegawai swasta,Pabrik / Gudang,Teknisi Mesin",
        "Pengusaha,Pabrik / Gudang,Teknisi Mesin",
        "Freelance,Pabrik / Gudang,Teknisi Mesin",
        "Pegawai negeri,Pendidikan,Dosen",
        "Pegawai swasta,Pendidikan,Dosen",
        "Pengusaha,Pendidikan,Dosen",
        "Freelance,Pendidikan,Dosen",
        "Pegawai negeri,Pendidikan,Guru",
        "Pegawai swasta,Pendidikan,Guru",
        "Pengusaha,Pendidikan,Guru",
        "Freelance,Pendidikan,Guru",
        "Pegawai negeri,Pendidikan,Instruktur / Pembimbing Kursus",
        "Pegawai swasta,Pendidikan,Instruktur / Pembimbing Kursus",
        "Pengusaha,Pendidikan,Instruktur / Pembimbing Kursus",
        "Freelance,Pendidikan,Instruktur / Pembimbing Kursus",
        "Pegawai negeri,Pendidikan,Kepala Sekolah",
        "Pegawai swasta,Pendidikan,Kepala Sekolah",
        "Pengusaha,Pendidikan,Kepala Sekolah",
        "Freelance,Pendidikan,Kepala Sekolah",
        "Pegawai negeri,Pendidikan,Tata Usaha",
        "Pegawai swasta,Pendidikan,Tata Usaha",
        "Pengusaha,Pendidikan,Tata Usaha",
        "Freelance,Pendidikan,Tata Usaha",
        "Pegawai negeri,Perawatan Tubuh,Fashion Designer",
        "Pegawai swasta,Perawatan Tubuh,Fashion Designer",
        "Pengusaha,Perawatan Tubuh,Fashion Designer",
        "Freelance,Perawatan Tubuh,Fashion Designer",
        "Pegawai negeri,Perawatan Tubuh,Gym / Fitness",
        "Pegawai swasta,Perawatan Tubuh,Gym / Fitness",
        "Pengusaha,Perawatan Tubuh,Gym / Fitness",
        "Freelance,Perawatan Tubuh,Gym / Fitness",
        "Pegawai negeri,Perawatan Tubuh,Pelatih / Trainer",
        "Pegawai swasta,Perawatan Tubuh,Pelatih / Trainer",
        "Pengusaha,Perawatan Tubuh,Pelatih / Trainer",
        "Freelance,Perawatan Tubuh,Pelatih / Trainer",
        "Pegawai negeri,Perawatan Tubuh,Salon / Spa / Panti Pijat",
        "Pegawai swasta,Perawatan Tubuh,Salon / Spa / Panti Pijat",
        "Pengusaha,Perawatan Tubuh,Salon / Spa / Panti Pijat",
        "Freelance,Perawatan Tubuh,Salon / Spa / Panti Pijat",
        "Pegawai negeri,Perbankan,Back-office",
        "Pegawai swasta,Perbankan,Back-office",
        "Pengusaha,Perbankan,Back-office",
        "Freelance,Perbankan,Back-office",
        "Pegawai negeri,Perbankan,Bank Teller",
        "Pegawai swasta,Perbankan,Bank Teller",
        "Pengusaha,Perbankan,Bank Teller",
        "Freelance,Perbankan,Bank Teller",
        "Pegawai negeri,Perbankan,CS Bank",
        "Pegawai swasta,Perbankan,CS Bank",
        "Pengusaha,Perbankan,CS Bank",
        "Freelance,Perbankan,CS Bank",
        "Pegawai negeri,Perbankan,Credit Analyst",
        "Pegawai swasta,Perbankan,Credit Analyst",
        "Pengusaha,Perbankan,Credit Analyst",
        "Freelance,Perbankan,Credit Analyst",
        "Pegawai negeri,Perbankan,Kolektor",
        "Pegawai swasta,Perbankan,Kolektor",
        "Pengusaha,Perbankan,Kolektor",
        "Freelance,Perbankan,Kolektor",
        "Pegawai negeri,Perbankan,Resepsionis",
        "Pegawai swasta,Perbankan,Resepsionis",
        "Pengusaha,Perbankan,Resepsionis",
        "Freelance,Perbankan,Resepsionis",
        "Pegawai negeri,Sales / Marketing,Account Executive / Manager",
        "Pegawai swasta,Sales / Marketing,Account Executive / Manager",
        "Pengusaha,Sales / Marketing,Account Executive / Manager",
        "Freelance,Sales / Marketing,Account Executive / Manager",
        "Pegawai negeri,Sales / Marketing,Salesman",
        "Pegawai swasta,Sales / Marketing,Salesman",
        "Pengusaha,Sales / Marketing,Salesman",
        "Freelance,Sales / Marketing,Salesman",
        "Pegawai negeri,Sales / Marketing,SPG",
        "Pegawai swasta,Sales / Marketing,SPG",
        "Pengusaha,Sales / Marketing,SPG",
        "Freelance,Sales / Marketing,SPG",
        "Pegawai negeri,Sales / Marketing,Telemarketing",
        "Pegawai swasta,Sales / Marketing,Telemarketing",
        "Pengusaha,Sales / Marketing,Telemarketing",
        "Freelance,Sales / Marketing,Telemarketing",
        "Pegawai negeri,Service,Customer Service",
        "Pegawai swasta,Service,Customer Service",
        "Pengusaha,Service,Customer Service",
        "Freelance,Service,Customer Service",
        "Pegawai negeri,Service,Kasir",
        "Pegawai swasta,Service,Kasir",
        "Pengusaha,Service,Kasir",
        "Freelance,Service,Kasir",
        "Pegawai negeri,Service,Kebersihan",
        "Pegawai swasta,Service,Kebersihan",
        "Pengusaha,Service,Kebersihan",
        "Freelance,Service,Kebersihan",
        "Pegawai negeri,Service,Koki",
        "Pegawai swasta,Service,Koki",
        "Pengusaha,Service,Koki",
        "Freelance,Service,Koki",
        "Pegawai negeri,Service,Pelayan / Pramuniaga",
        "Pegawai swasta,Service,Pelayan / Pramuniaga",
        "Pengusaha,Service,Pelayan / Pramuniaga",
        "Freelance,Service,Pelayan / Pramuniaga",
        "Pegawai negeri,Tehnik / Computer,Engineer / Ahli Tehnik",
        "Pegawai swasta,Tehnik / Computer,Engineer / Ahli Tehnik",
        "Pengusaha,Tehnik / Computer,Engineer / Ahli Tehnik",
        "Freelance,Tehnik / Computer,Engineer / Ahli Tehnik",
        "Pegawai negeri,Tehnik / Computer,Penulis Teknikal",
        "Pegawai swasta,Tehnik / Computer,Penulis Teknikal",
        "Pengusaha,Tehnik / Computer,Penulis Teknikal",
        "Freelance,Tehnik / Computer,Penulis Teknikal",
        "Pegawai negeri,Tehnik / Computer,Programmer / Developer",
        "Pegawai swasta,Tehnik / Computer,Programmer / Developer",
        "Pengusaha,Tehnik / Computer,Programmer / Developer",
        "Freelance,Tehnik / Computer,Programmer / Developer",
        "Pegawai negeri,Tehnik / Computer,R&D / Ilmuwan / Peneliti",
        "Pegawai swasta,Tehnik / Computer,R&D / Ilmuwan / Peneliti",
        "Pengusaha,Tehnik / Computer,R&D / Ilmuwan / Peneliti",
        "Freelance,Tehnik / Computer,R&D / Ilmuwan / Peneliti",
        "Pegawai negeri,Tehnik / Computer,Warnet",
        "Pegawai swasta,Tehnik / Computer,Warnet",
        "Pengusaha,Tehnik / Computer,Warnet",
        "Freelance,Tehnik / Computer,Warnet",
        "Pegawai negeri,Tehnik / Computer,Otomotif",
        "Pegawai swasta,Tehnik / Computer,Otomotif",
        "Pengusaha,Tehnik / Computer,Otomotif",
        "Freelance,Tehnik / Computer,Otomotif",
        "Pegawai negeri,Transportasi,Supir / Ojek",
        "Pegawai swasta,Transportasi,Supir / Ojek",
        "Pengusaha,Transportasi,Supir / Ojek",
        "Freelance,Transportasi,Supir / Ojek",
        "Pegawai negeri,Transportasi,Agen Perjalanan",
        "Pegawai swasta,Transportasi,Agen Perjalanan",
        "Pengusaha,Transportasi,Agen Perjalanan",
        "Freelance,Transportasi,Agen Perjalanan",
        "Pegawai negeri,Transportasi,Kurir / Ekspedisi",
        "Pegawai swasta,Transportasi,Kurir / Ekspedisi",
        "Pengusaha,Transportasi,Kurir / Ekspedisi",
        "Freelance,Transportasi,Kurir / Ekspedisi",
        "Pegawai negeri,Transportasi,Pelaut / Staff Kapal / Nahkoda Kapal",
        "Pegawai swasta,Transportasi,Pelaut / Staff Kapal / Nahkoda Kapal",
        "Pengusaha,Transportasi,Pelaut / Staff Kapal / Nahkoda Kapal",
        "Freelance,Transportasi,Pelaut / Staff Kapal / Nahkoda Kapal",
        "Pegawai negeri,Transportasi,Pilot / Staff Penerbangan",
        "Pegawai swasta,Transportasi,Pilot / Staff Penerbangan",
        "Pengusaha,Transportasi,Pilot / Staff Penerbangan",
        "Freelance,Transportasi,Pilot / Staff Penerbangan",
        "Pegawai negeri,Transportasi,Sewa Kendaraan",
        "Pegawai swasta,Transportasi,Sewa Kendaraan",
        "Pengusaha,Transportasi,Sewa Kendaraan",
        "Freelance,Transportasi,Sewa Kendaraan",
        "Pegawai negeri,Transportasi,Masinis / Kereta Api",
        "Pegawai swasta,Transportasi,Masinis / Kereta Api",
        "Pengusaha,Transportasi,Masinis / Kereta Api",
        "Freelance,Transportasi,Masinis / Kereta Api",
        "Staf rumah tangga,Pembantu Rumah Tangga,",
        "Pegawai negeri,Perhotelan,Customer Service",
        "Pegawai swasta,Perhotelan,Customer Service",
        "Pengusaha,Perhotelan,Customer Service",
        "Freelance,Perhotelan,Customer Service",
        "Pegawai negeri,Perhotelan,Kebersihan",
        "Pegawai swasta,Perhotelan,Kebersihan",
        "Pengusaha,Perhotelan,Kebersihan",
        "Freelance,Perhotelan,Kebersihan",
        "Pegawai negeri,Perhotelan,Koki",
        "Pegawai swasta,Perhotelan,Koki",
        "Pengusaha,Perhotelan,Koki",
        "Freelance,Perhotelan,Koki",
        "Pegawai negeri,Perhotelan,Room Service / Pelayan",
        "Pegawai swasta,Perhotelan,Room Service / Pelayan",
        "Pengusaha,Perhotelan,Room Service / Pelayan",
        "Freelance,Perhotelan,Room Service / Pelayan",
    ]
    TIPE_PEKERJAAN = [
        'Pegawai negeri',
        'Pengusaha',
        'Freelance',
        'Staf rumah tangga',
        'Pekerja rumah tangga',
        'Ibu rumah tangga',
        'Mahasiswa',
        'Tidak bekerja',
    ]
    LAINNYA_DATA = [
        "Pegawai negeri,Admin / Finance / HR,Lainnya",
        "Pegawai swasta,Admin / Finance / HR,Lainnya",
        "Pengusaha,Admin / Finance / HR,Lainnya",
        "Freelance,Admin / Finance / HR,Lainnya",
        "Pegawai negeri,Design / Seni,Lainnya",
        "Pegawai swasta,Design / Seni,Lainnya",
        "Pengusaha,Design / Seni,Lainnya",
        "Freelance,Design / Seni,Lainnya",
        "Pegawai negeri,Entertainment / Event,Lainnya",
        "Pegawai swasta,Entertainment / Event,Lainnya",
        "Pengusaha,Entertainment / Event,Lainnya",
        "Freelance,Entertainment / Event,Lainnya",
        "Pegawai negeri,Hukum / Security / Politik,Lainnya",
        "Pegawai swasta,Hukum / Security / Politik,Lainnya",
        "Pengusaha,Hukum / Security / Politik,Lainnya",
        "Freelance,Hukum / Security / Politik,Lainnya",
        "Pegawai negeri,Konstruksi / Real Estate,Lainnya",
        "Pegawai swasta,Konstruksi / Real Estate,Lainnya",
        "Pengusaha,Konstruksi / Real Estate,Lainnya",
        "Freelance,Konstruksi / Real Estate,Lainnya",
        "Pegawai negeri,Kesehatan,Lainnya",
        "Pegawai swasta,Kesehatan,Lainnya",
        "Pengusaha,Kesehatan,Lainnya",
        "Freelance,Kesehatan,Lainnya",
        "Pegawai negeri,Media,Lainnya",
        "Pegawai swasta,Media,Lainnya",
        "Pengusaha,Media,Lainnya",
        "Freelance,Media,Lainnya",
        "Pegawai negeri,Pabrik / Gudang,Lainnya",
        "Pegawai swasta,Pabrik / Gudang,Lainnya",
        "Pengusaha,Pabrik / Gudang,Lainnya",
        "Freelance,Pabrik / Gudang,Lainnya",
        "Pegawai negeri,Pendidikan,Lainnya",
        "Pegawai swasta,Pendidikan,Lainnya",
        "Pengusaha,Pendidikan,Lainnya",
        "Freelance,Pendidikan,Lainnya",
        "Pegawai negeri,Perbankan,Lainnya",
        "Pegawai swasta,Perbankan,Lainnya",
        "Pengusaha,Perbankan,Lainnya",
        "Freelance,Perbankan,Lainnya",
        "Pegawai negeri,Sales / Marketing,Lainnya",
        "Pegawai swasta,Sales / Marketing,Lainnya",
        "Pengusaha,Sales / Marketing,Lainnya",
        "Freelance,Sales / Marketing,Lainnya",
        "Pegawai negeri,Service,Lainnya",
        "Pegawai swasta,Service,Lainnya",
        "Pengusaha,Service,Lainnya",
        "Freelance,Service,Lainnya",
        "Pegawai negeri,Tehnik / Computer,Lainnya",
        "Pegawai swasta,Tehnik / Computer,Lainnya",
        "Pengusaha,Tehnik / Computer,Lainnya",
        "Freelance,Tehnik / Computer,Lainnya",
        "Pegawai negeri,Perawatan Tubuh,Lainnya",
        "Pegawai swasta,Perawatan Tubuh,Lainnya",
        "Pengusaha,Perawatan Tubuh,Lainnya",
        "Freelance,Perawatan Tubuh,Lainnya",
        "Pegawai negeri,Transportasi,Lainnya",
        "Pegawai swasta,Transportasi,Lainnya",
        "Pengusaha,Transportasi,Lainnya",
        "Freelance,Transportasi,Lainnya",
        "Pegawai negeri,Perhotelan,Lainnya",
        "Pegawai swasta,Perhotelan,Lainnya",
        "Pengusaha,Perhotelan,Lainnya",
        "Freelance,Perhotelan,Lainnya",
    ]

    def _get_data(self, product_line_code, randomize=False):
        if randomize:
            random.shuffle(self.DATA)

        data = {'version': self.version, 'data': self.DATA + self.LAINNYA_DATA}

        return json.dumps(data)
