from django.conf.urls import url

from loan_app import views as app_views
from . import views
from .views import CannedResponseView
from juloserver.dana.loan.crm import views as DanaCRMViews
from juloserver.partnership.crm import views as PartnerCRMViews

urlpatterns = [

    url(r'^list$', views.ApplicationDataListView.as_view(),
        name='list'),
    url(r'^detail/(?P<pk>\d+)$', views.ApplicationDetailView.as_view(),
        name='detail'),
    url(r'^(?P<status_code>[0-9a-z_.]+)/list$', views.ApplicationDataWSCListView.as_view(),
            name='list_w_status'),
    url(r'^list-0-turbo$', views.OnboardinEligibilityDataWSCListView.as_view(),
            name='list_0_turbo'),
    url(r'^(?P<status_code>\d+)/list_priority$', views.ApplicationDataWSCPriorityListView.as_view(),
        name='list_priority_w_status'),
    url(r'^sphp/(?P<pk>\d+)$', app_views.LoanApplicationSPHPView.as_view(
        template_name='object/app_status/sphp.html'),
        name='sphp'),
    url(r'^sphp_stl/(?P<pk>\d+)$', app_views.LoanApplicationSPHPView.as_view(
        template_name='object/app_status/sphp_stl.html'),
        name='sphp_stl'),
    url(r'^verification_check/(?P<pk>\d+)$', views.verification_check,
        name='verification_check'),
    url(r'^change_status/(?P<pk>\d+)$', views.change_app_status,
        name='change_status'),
    url(r'^change_status_by_customer/(?P<customer_id>\d+)$', views.change_app_status_by_customer,
        name='change_status_by_customer'),
    url(r'^redirect/(?P<pk>\d+)$', views.redirect_application,
        name='redirect'),
    url(r'^sd_sheet$', views.sd_sheet,
        name='sd_sheet'),
    url(r'^disburse_summary', views.DisbursementSummaryView.as_view(),
        name='disburse_summary'),
    url(r'^cs/customer/detail/(?P<pk>\d+)$', views.customer_service_detail,
        name='customer_service_detail'),
    url(r'^dana/dana-list-marital-status/$',
        DanaCRMViews.ApplicationDanaListMaritalStatusView.as_view(),
        name='dana_list_marital_status'),
    url(r'^dana-update-marital-status-detail/(?P<pk>\d+)$', DanaCRMViews.dana_update_marital_status,
        name='dana_update_marital_status_detail'),
    url(
        r'(?P<status_code>[0-9a-z_.]+)/app_status-100-agent-assisted/',
        PartnerCRMViews.ApplicationData100AgentAssistedListView.as_view(),
        name='app_status_100_agent_assisted',
    ),
    url(
        r'^application_form_assist/(?P<pk>\d+)$',
        views.application_form_assist,
        name='application_form_assist',
    ),
    # Ajax
    url(r'^check_priority', views.check_app_priority, name='check_priority'),
    url(r'^check_app_locked', views.check_app_locked, name='check_app_locked'),
    url(r'^set_app_locked', views.set_app_locked, name='set_app_locked'),
    url(r'^set_app_unlocked', views.set_app_unlocked, name='set_app_unlocked'),
    url(r'^image_resubmission', views.image_resubmission, name='image_resubmission'),
    url(r'^voice_resubmission', views.voice_resubmission, name='voice_resubmission'),
    url(r'^update_app_selected_field', views.update_app_selected_field, name='update_app_selected_field'),
    url(r'^voice_records_script', views.voice_records_script, name='voice_records_script'),
    url(r'^check_doku_balance', views.ajax_check_doku_available, name='check_doku_balance'),
    url(r'^doku_disbursement', views.ajax_disbursement, name='doku_disbursement'),
    url(r'^update_checklist', views.ajax_update_application_checklist_collection,
        name='update_checklist'),
    url(r'^calculate_suggested_offer', views.ajax_calculate_suggested_offer,
        name='calculate_suggested_offer'),
    url(r'^ajax_update_courtesy', views.ajax_update_courtesy,
        name='ajax_update_courtesy'),
    url(r'^ajax_courtesy_email', views.ajax_courtesy_email,
        name='ajax_courtesy_email'),
    url(r'^trigger_autodial', views.trigger_autodial, name='trigger_autodial'),
    url(r'^ajax_custom_email', views.ajax_custom_email,
        name='ajax_custom_email'),
    url(r'^ajax_canned_email', CannedResponseView.as_view(),name='ajax_canned_email'),
    url(r'^process_cashback_transfer_request', views.process_cashback_transfer_request,
        name='process_cashback_transfer_request'),
    url(r'^ajax_update_offer', views.ajax_update_offer,
        name='ajax_update_offer'),
    url(r'^ajax_update_application_bank', views.ajax_update_application_bank,
        name='ajax_update_application_bank'),
    url(r'^ajax_update_name_bank_validation', views.ajax_update_name_bank_validation,
        name='ajax_update_name_bank_validation'),
    url(r'^ajax_bank_validation_grab$', views.ajax_bank_validation_grab,
        name='ajax_bank_validation_grab'),
    url(r'^ajax_bank_validation', views.ajax_bank_validation, name='ajax_bank_validation'),
    url(r'^ajax_change_disbursement_method', views.ajax_change_disbursement_method,
        name='ajax_change_disbursement_method'),
    url(r'^mass_move_apps', views.mass_move_apps,
        name='mass_move_apps'),
    url(r'^ajax_update_cashback', views.ajax_update_cashback,
        name='ajax_update_cashback'),
    url(r'^ajax_retry_cashback_transfer', views.ajax_retry_cashback_transfer, name='ajax_retry_cashback_transfer'),
    url(r'^ajax_disburse_summary', views.ajax_disburse_summary, name='ajax_disburse_summary'),
    url(r'^ajax_check_ktp', views.ajax_check_ktp, name='ajax_check_ktp'),

    url(r'^nexmo-call-test/$', views.NexmoCallTesting.as_view(), name='nexmo-call-test'),
    url(r'^ajax_change_email', views.ajax_change_email, name='ajax_change_email'),
    url(r'^ajax_send_reset_pin_email', views.ajax_send_reset_pin_email, name='ajax_send_reset_pin_email'),
    url(r'^ajax_send_magic_link', views.ajax_send_magic_link, name='ajax_send_magic_link'),
    url(r'^ajax_save_fraud_crm_form', views.ajax_save_fraud_crm_form, name='ajax_save_fraud_crm_form'),
    url(r'^ajax_check_if_magic_links_verified', views.ajax_check_if_magic_links_verified, name='ajax_check_if_magic_links_verified'),
    url(r'^ajax_check_reset_pin_status', views.ajax_check_reset_pin_status, name='ajax_check_reset_pin_status'),
    url(r'^ajax_check_email', views.ajax_check_email, name='ajax_check_email'),
    url(
        r'^ajax_verify_grab_phone',
        views.ajax_grab_verify_phone_number,
        name='ajax_verify_grab_phone',
    ),
    url(
        r'^ajax_fraud_reverify_account',
        views.ajax_fraud_reverify_account,
        name='ajax_fraud_reverify_account',
    ),
    url(
        r'^ajax_get_autodebit_bca_webview',
        views.ajax_get_autodebit_bca_webview,
        name='ajax_get_autodebit_bca_webview',
    ),
    url(
        r'^ajax_reset_autodebit_account',
        views.ajax_reset_autodebit_account,
        name='ajax_reset_autodebit_account',
    ),
    url(
        r'^ajax_change_autodebit_deduction_day',
        views.ajax_change_autodebit_deduction_day,
        name='ajax_change_autodebit_deduction_day',
    ),
    url(
        r'^ajax_fraud_show_similar_faces',
        views.ajax_fraud_show_similar_faces,
        name='ajax_fraud_show_similar_faces',
    ),
    url(
        r'^ajax_check_credit_score_status',
        views.ajax_check_credit_score_status,
        name='ajax_check_credit_score_status',
    ),
    url(
        r'^ajax_get_dropdown_data_form$',
        views.ajax_get_dropdown_data_form,
        name='ajax_get_dropdown_data_form',
    ),
    url(
        r'^ajax_get_dropdown_data_form_job/(?P<job_industry>.+)/(?P<job_description>.+)$',
        views.ajax_get_dropdown_data_form_job,
        name='ajax_get_dropdown_data_form_job',
    ),
    url(
        r'^ajax_get_dropdown_data_company$',
        views.ajax_get_dropdown_data_company,
        name='ajax_get_dropdown_data_company',
    ),
]
