from builtins import object
class PAYMENT_EVENT_CONST(object):
    REVERSAL_REASON_OVER_PAYMENT = 'Kelebihan Bayar'
    REVERSAL_REASON_WRONG_PAYMENT = 'Salah Bayar'
    REVERSAL_REASONS = (REVERSAL_REASON_OVER_PAYMENT, REVERSAL_REASON_WRONG_PAYMENT)