# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-07 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('julo', '0003_alter_id_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineOfCredit',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='line_of_credit_id', primary_key=True, serialize=False)),
                ('limit', models.BigIntegerField()),
                ('available', models.BigIntegerField()),
                ('service_fee_rate', models.FloatField()),
                ('late_fee_rate', models.FloatField()),
                ('interest_rate', models.FloatField()),
                ('status', models.CharField(default=b'inactive', max_length=100)),
                ('active_date', models.DateTimeField(blank=True, null=True)),
                ('statement_day', models.IntegerField(blank=True, null=True)),
                ('freeze_date', models.DateTimeField(blank=True, null=True)),
                ('freeze_reason', models.TextField(default='')),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Customer')),
            ],
            options={
                'db_table': 'line_of_credit',
            },
        ),
        migrations.CreateModel(
            name='LineOfCreditNotification',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='loc_notification_id', primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('send_date', models.DateTimeField()),
                ('is_sent', models.BooleanField(default=False)),
                ('is_cancel', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'loc_notification',
            },
        ),
        migrations.CreateModel(
            name='LineOfCreditStatement',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='loc_statement_id', primary_key=True, serialize=False)),
                ('last_billing_amount', models.BigIntegerField(blank=True, null=True)),
                ('last_minimum_payment', models.BigIntegerField(blank=True, null=True)),
                ('last_payment_due_date', models.DateTimeField(blank=True, null=True)),
                ('payment_amount', models.BigIntegerField()),
                ('late_fee_rate', models.FloatField()),
                ('late_fee_amount', models.BigIntegerField()),
                ('interest_rate', models.FloatField()),
                ('interest_amount', models.BigIntegerField()),
                ('purchase_amount', models.BigIntegerField()),
                ('billing_amount', models.BigIntegerField()),
                ('minimum_payment', models.BigIntegerField()),
                ('payment_due_date', models.DateTimeField()),
                ('statement_code', models.CharField(max_length=100)),
                ('is_min_paid', models.BooleanField(default=False)),
                ('line_of_credit', models.ForeignKey(db_column='line_of_credit_id', on_delete=django.db.models.deletion.DO_NOTHING, to='line_of_credit.LineOfCredit')),
            ],
            options={
                'db_table': 'loc_statement',
            },
        ),
        migrations.CreateModel(
            name='LineOfCreditTransaction',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='line_of_credit_transaction_id', primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=100)),
                ('channel', models.CharField(max_length=100)),
                ('line_of_credit', models.ForeignKey(db_column='line_of_credit_id', on_delete=django.db.models.deletion.DO_NOTHING, to='line_of_credit.LineOfCredit')),
                ('loc_statement', models.ForeignKey(blank=True, db_column='loc_statement_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='line_of_credit.LineOfCreditStatement')),
            ],
            options={
                'db_table': 'loc_transaction',
            },
        ),
        migrations.AddField(
            model_name='lineofcreditnotification',
            name='loc_statement',
            field=models.ForeignKey(blank=True, db_column='line_of_credit_statement_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='line_of_credit.LineOfCreditStatement'),
        ),
    ]
