# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-15 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_of_credit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineofcredit',
            name='next_statement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
