# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-18 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('line_of_credit', '0003_auto_20180516_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineofcredit',
            name='customer',
            field=models.OneToOneField(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, to='julo.Customer'),
        ),
    ]
