# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-24 01:19
from __future__ import unicode_literals

from django.db import migrations


def load_product_lookups(apps, schema_editor):
    product_lookups = [

        (1, 'I.180-O.050-L.050-C1.010-C2.010-M', 0.180, 0.050, 0.050, 0.010, 0.010, 'Monthly', True),
        (2, 'I.210-O.050-L.050-C1.010-C2.010-M', 0.210, 0.050, 0.050, 0.010, 0.010, 'Monthly', True),
        (3, 'I.240-O.050-L.050-C1.010-C2.010-M', 0.240, 0.050, 0.050, 0.010, 0.010, 'Monthly', True),
        (4, 'I.270-O.050-L.050-C1.010-C2.010-M', 0.270, 0.050, 0.050, 0.010, 0.010, 'Monthly', True),
        (5, 'I.300-O.050-L.050-C1.010-C2.010-M', 0.300, 0.050, 0.050, 0.010, 0.010, 'Monthly', True),
        (6, 'I.330-O.050-L.050-C1.010-C2.010-M', 0.330, 0.050, 0.050, 0.010, 0.010, 'Monthly', True),
        (7, 'I.360-O.050-L.050-C1.010-C2.010-M', 0.360, 0.050, 0.050, 0.010, 0.010, 'Monthly', True),
        (8, 'I.390-O.050-L.050-C1.010-C2.010-M', 0.390, 0.050, 0.050, 0.010, 0.010, 'Monthly', True),
        (9, 'I.420-O.050-L.050-C1.010-C2.010-M', 0.420, 0.050, 0.050, 0.010, 0.010, 'Monthly', True),
        (10, 'I.450-O.050-L.050-C1.010-C2.010-M', 0.450, 0.050, 0.050, 0.010, 0.010, 'Monthly', True),
        (11, 'I.480-O.050-L.050-C1.010-C2.010-M', 0.480, 0.050, 0.050, 0.010, 0.010, 'Monthly', True),

    ]

    ProductLookup = apps.get_model("julo", "ProductLookup")
    for pl in product_lookups:
        kwargs = {
            'product_code': pl[0],
            'product_name': pl[1],
            'interest_rate': pl[2],
            'origination_fee_pct': pl[3],
            'late_fee_pct': pl[4],
            'cashback_initial_pct': pl[5],
            'cashback_payment_pct': pl[6],
            'payment_frequency': pl[7],
            'is_active': pl[8],
        }
        product_lookup = ProductLookup(**kwargs)
        product_lookup.save()


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0004_load_status_lookups'),
    ]

    operations = [
        migrations.RunPython(load_product_lookups),
    ]
