# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-31 11:13
from __future__ import unicode_literals

import cuser.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def move_notes(apps, schema_editor):
    """
    One time migration procedure to copy all the notes on existing applications
    from the old table to the new table.
    """
    Application = apps.get_model("julo", "Application")
    ApplicationNote = apps.get_model("julo", "ApplicationNote")

    for application in list(Application.objects.all()):

        if hasattr(application, "note"):
            note_text = application.note.note_text
        else:
            note_text = "initial text from migration"

        ApplicationNote.objects.create(
            note_text=note_text,
            application=application,
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('julo', '0014_applicationhistory'),
    ]

    operations = [

        # Adding columns to application

        migrations.AddField(
            model_name='application',
            name='loan_purpose_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='work_kodepos',
            field=models.CharField(
                blank=True, max_length=5,
                validators=[
                    django.core.validators.RegexValidator(
                        message='Kode pos has to be 5 numeric digits',
                        regex='^[0-9]{5}$')
                ]
            ),
        ),
        migrations.AddField(
            model_name='application',
            name='job_function',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='job_industry',
            field=models.CharField(blank=True, max_length=100),
        ),

        # Replacing old table with new table for application notes

        migrations.CreateModel(
            name='ApplicationNote',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(
                    db_column='application_note_id', primary_key=True, serialize=False)),
                ('note_text', models.TextField()),
                ('added_by', cuser.fields.CurrentUserField(
                    editable=False,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='note_takers',
                    to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'application_note',
            },
        ),
        migrations.AddField(
            model_name='applicationnote',
            name='application',
            field=models.ForeignKey(
                db_column='application_id',
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='julo.Application'),
        ),
        migrations.AddField(
            model_name='applicationnote',
            name='status_change',
            field=models.OneToOneField(
                blank=True,
                db_column='application_history_id',
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='julo.ApplicationHistory'
            ),
        ),
        migrations.RunPython(move_notes)
    ]
