# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-10 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0020_auto_20170209_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicescrapeddata',
            name='reports_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
