# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-02 05:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0027_auto_20170301_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerReferral',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='partner_referral_id', primary_key=True, serialize=False)),
                ('partner_code', models.CharField(blank=True, max_length=100, null=True)),
                ('cust_fullname', models.CharField(blank=True, max_length=100, null=True)),
                ('cust_email', models.EmailField(max_length=254)),
                ('address_street_num', models.CharField(blank=True, max_length=100, null=True)),
                ('address_provinsi', models.CharField(blank=True, max_length=100, null=True)),
                ('address_kabupaten', models.CharField(blank=True, max_length=100, null=True)),
                ('address_kecamatan', models.CharField(blank=True, max_length=100, null=True)),
                ('address_kelurahan', models.CharField(blank=True, max_length=100, null=True)),
                ('address_kodepos', models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator(message='Kode pos has to be 5 numeric digits', regex='^[0-9]{5}$')])),
                ('mobile_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True)),
                ('account_tenure_mth', models.PositiveIntegerField(blank=True, null=True)),
                ('past_gmv', models.BigIntegerField(blank=True, null=True)),
                ('past_purchase_count', models.PositiveIntegerField(blank=True, null=True)),
                ('is_android_user', models.NullBooleanField()),
                ('application', models.OneToOneField(blank=True, db_column='application_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Application')),
            ],
            options={
                'db_table': 'partner_referral',
            },
        ),
        migrations.CreateModel(
            name='PartnerTransaction',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='partner_transaction_id', primary_key=True, serialize=False)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('transaction_amount', models.BigIntegerField(blank=True, null=True)),
                ('transaction_type', models.CharField(max_length=50)),
                ('partner_referral', models.ForeignKey(db_column='partner_referral_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='julo.PartnerReferral')),
            ],
            options={
                'db_table': 'partner_transaction',
            },
        ),
        migrations.CreateModel(
            name='PartnerTransactionItem',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='partner_transaction_item_id', primary_key=True, serialize=False)),
                ('item_name', models.CharField(blank=True, max_length=250, null=True)),
                ('item_price', models.BigIntegerField(blank=True, null=True)),
                ('item_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('product_category', models.CharField(blank=True, max_length=100, null=True)),
                ('partner_transaction', models.ForeignKey(db_column='partner_transaction_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_items', to='julo.PartnerTransaction')),
            ],
            options={
                'db_table': 'partner_transaction_item',
            },
        ),
        migrations.RemoveField(
            model_name='ecommercepurchaseitem',
            name='ecommerce_transaction',
        ),
        migrations.RemoveField(
            model_name='ecommercereferral',
            name='application',
        ),
        migrations.RemoveField(
            model_name='ecommercetransaction',
            name='ecommerce_referral',
        ),
        migrations.DeleteModel(
            name='EcommercePurchaseItem',
        ),
        migrations.DeleteModel(
            name='EcommerceReferral',
        ),
        migrations.DeleteModel(
            name='EcommerceTransaction',
        ),
    ]
