# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-03 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0029_auto_20170302_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentevent',
            name='event_due_amount',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
