# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-15 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0033_auto_20170314_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='resubmit',
            field=models.NullBooleanField(),
        ),
    ]
