# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-22 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0041_auto_20170321_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='resubmit',
        ),
        migrations.AddField(
            model_name='image',
            name='image_status',
            field=models.IntegerField(blank=True, choices=[(-1, 'Deleted'), (0, 'Current'), (1, 'Resubmission Required')], default=0, null=True),
        ),
    ]
