# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-26 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0045_auto_20170324_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='app_version',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
