# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-24 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0060_emailhistory_alter_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='smshistory',
            name='delivery_error_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
