# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-05 03:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0061_smshistory_delivery_error_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['payment_number']},
        ),
    ]
