# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-08 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0062_auto_20170505_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='other_income_source',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
