# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-15 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0068_applicationoriginal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='kin_gender',
            field=models.CharField(blank=True, choices=[('Pria', 'Pria'), ('Wanita', 'Wanita')], max_length=10, null=True, verbose_name='Jenis kelamin kerabat'),
        ),
    ]
