# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-18 11:41
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0070_payment_late_fee_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentevent',
            name='event_type',
            field=models.CharField(default='payment', max_length=20),
        ),
    ]
