# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-24 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0073_application_data_check_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='loan_purpose',
            field=models.CharField(max_length=100, verbose_name='Tujuan pinjaman'),
        ),
        migrations.AlterField(
            model_name='applicationoriginal',
            name='loan_purpose',
            field=models.CharField(max_length=100, verbose_name='Tujuan pinjaman'),
        ),
    ]

