# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-24 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0075_auto_20170524_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cashback_earned',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='late_fee_amount',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='late_fee_applied',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_amount',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]

