# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-13 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0085_auto_20170628_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_review_submitted',
            field=models.NullBooleanField(),
        ),
    ]
