# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-13 08:24
from __future__ import unicode_literals

from django.db import migrations, models


def load_new_status_lookups(apps, schema_editor):
    status_lookups = [

        # Application status

        (162, 'Legal agreement resubmission requested'),
        (163, 'Legal agreement resubmitted'),

    ]

    StatusLookup = apps.get_model("julo", "StatusLookup")
    for status_code, status in status_lookups:
        status_lookup = StatusLookup(status_code=status_code, status=status)
        status_lookup.save()


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0087_voicerecord'),
    ]

    operations = [
        migrations.RunPython(load_new_status_lookups),
    ]