# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-02 10:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('julo', '0088_load_new_statuslookup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skiptrace',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='skiptrace_id', primary_key=True, serialize=False)),
                ('contact_name', models.TextField(blank=True, null=True)),
                ('contact_source', models.TextField(blank=True, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True)),
                ('phone_operator', models.TextField(blank=True, null=True)),
                ('effectiveness', models.DecimalField(decimal_places=2, max_digits=15)),
                ('recency', models.DateTimeField()),
                ('frequency', models.IntegerField(blank=True, null=True)),
                ('application', models.ForeignKey(blank=True, db_column='src_application_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Application')),
                ('customer', models.ForeignKey(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Customer')),
            ],
            options={
                'db_table': 'skiptrace',
            },
        ),
        migrations.CreateModel(
            name='SkiptraceHistory',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='skiptrace_history_id', primary_key=True, serialize=False)),
                ('start_ts', models.DateTimeField()),
                ('end_ts', models.DateTimeField()),
                ('agent_name', models.TextField(blank=True, null=True)),
                ('agent', models.OneToOneField(db_column='agent_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('skiptrace', models.ForeignKey(db_column='skiptrace_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Skiptrace')),
            ],
            options={
                'db_table': 'skiptrace_history',
            },
        ),
    ]
