# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-07 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0095_auto_20170807_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skiptrace',
            old_name='src_application',
            new_name='application',
        ),
        migrations.AlterUniqueTogether(
            name='skiptrace',
            unique_together=set([('customer', 'phone_number')]),
        ),
    ]
