# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-09 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0099_auto_20170809_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerreferral',
            name='application',
        ),
        migrations.AddField(
            model_name='partnerreferral',
            name='customer',
            field=models.ForeignKey(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Customer'),
        ),
    ]
