# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-21 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0102_load_doku_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='systrace',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='token',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
