# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-22 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0103_auto_20170821_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='decision',
        ),
        migrations.AddField(
            model_name='loan',
            name='first_installment_amount',
            field=models.BigIntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='sphp_accepted_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='sphp_sent_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_sent_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
