# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-29 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0104_dokutransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokutransaction',
            name='transaction_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
