# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-14 08:44
from __future__ import unicode_literals

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('julo', '0109_auto_20170907_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalExpense',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='additional_expense_id', primary_key=True, serialize=False)),
                ('field_name', models.TextField()),
                ('description', models.TextField()),
                ('amount', models.BigIntegerField()),
                ('group', models.CharField(max_length=5)),
                ('agent', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Application')),
            ],
            options={
                'db_table': 'additional_expense',
            },
        ),
        migrations.CreateModel(
            name='AdditionalExpenseHistory',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='additional_expense_history_id', primary_key=True, serialize=False)),
                ('field_name', models.TextField()),
                ('old_description', models.TextField()),
                ('old_amount', models.BigIntegerField()),
                ('new_description', models.TextField()),
                ('new_amount', models.BigIntegerField()),
                ('group', models.CharField(max_length=5)),
                ('agent', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Application')),
            ],
            options={
                'db_table': 'additional_expense_history',
            },
        ),
        migrations.CreateModel(
            name='ApplicationCheckListComment',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='application_check_list_comment_id', primary_key=True, serialize=False)),
                ('field_name', models.TextField()),
                ('comment', models.TextField()),
                ('group', models.CharField(max_length=5)),
                ('agent', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Application')),
            ],
            options={
                'db_table': 'application_check_list_comment',
            },
        ),
        migrations.CreateModel(
            name='ApplicationCheckListHistory',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='application_check_list_history_id', primary_key=True, serialize=False)),
                ('field_name', models.TextField()),
                ('changed_to', models.BooleanField()),
                ('changed_from', models.BooleanField()),
                ('group', models.CharField(max_length=5)),
                ('agent', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Application')),
            ],
            options={
                'db_table': 'application_check_list_history',
            },
        ),
        migrations.CreateModel(
            name='ApplicationFieldChange',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='application_field_change', primary_key=True, serialize=False)),
                ('field_name', models.TextField()),
                ('old_value', models.TextField()),
                ('new_value', models.TextField()),
                ('group', models.CharField(max_length=5)),
                ('agent', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Application')),
            ],
            options={
                'db_table': 'application_field_change',
            },
        ),
    ]
