# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-19 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0117_load_additional_application_checklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalexpense',
            name='is_deleted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicationfieldchange',
            name='id',
            field=models.AutoField(db_column='application_field_change_id', primary_key=True, serialize=False),
        ),
    ]
