# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-02 03:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('julo', '0124_payment_discretionary_adjustment'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalPassword',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('original_password', models.CharField(max_length=128)),
                ('temporary_password', models.CharField(blank=True, max_length=8, null=True)),
                ('user', models.OneToOneField(db_column='auth_user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'original_password',
            },
        ),
    ]
