# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-23 12:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0138_auto_20171023_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoDialerRecord',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='autodialer_record_id', primary_key=True, serialize=False)),
                ('call_id', models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(message='characters not allowed', regex='^[ -~]+$')])),
                ('time_of_call', models.DateTimeField(null=True)),
                ('call_status', models.CharField(max_length=20)),
                ('call_duration', models.DateTimeField(null=True)),
                ('attempt_number', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'autodialer_record',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='is_robocall_active',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='is_courtesy_call',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='applicationoriginal',
            name='is_courtesy_call',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='autodialerrecord',
            name='payment',
            field=models.ForeignKey(db_column='payment_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Payment'),
        ),
        migrations.AddField(
            model_name='autodialerrecord',
            name='skiptrace',
            field=models.ForeignKey(db_column='skiptrace_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Skiptrace'),
        ),
        migrations.RunSQL(
            "ALTER TABLE autodialer_record ALTER COLUMN autodialer_record_id TYPE bigint ;"
            "ALTER TABLE autodialer_record ALTER COLUMN payment_id TYPE bigint ;"
            "ALTER TABLE autodialer_record ALTER COLUMN skiptrace_id TYPE bigint ;"
        ),
    ]
