# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-27 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0139_auto_20171023_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autodialerrecord',
            name='call_duration',
        ),
        migrations.AddField(
            model_name='autodialerrecord',
            name='call_duration',
            field=models.IntegerField(null=True),
        ),
    ]
