# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-11-03 07:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0141_paymentmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualAccountSuffix',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='virtual_account_suffix_id', primary_key=True, serialize=False)),
                ('virtual_account_suffix', models.CharField(blank=True, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Virtual account suffix has to be numeric digits', regex='^[0-9]+$')])),
                ('is_assigned', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'virtual_account_suffix',
            },
        ),
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='method_name',
            new_name='payment_method_name',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='is_show',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='method_code',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='virtual_number',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='bank_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='payment_method_code',
            field=models.CharField(max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='virtual_account',
            field=models.CharField(blank=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Virtual account has to be numeric digits', regex='^[0-9]+$')]),
        ),
    ]
