# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-11-08 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def db_insert_form_name_validate_status(apps, schema_editor):
    StatusLookup = apps.get_model('julo', 'StatusLookup')
    StatusLookup.objects.get_or_create(status_code=175,
                                       status='Name validation failed')

class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0148_bri_integration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='disbursement_id',
                                        primary_key=True, serialize=False)),
                ('validation_status', models.CharField(max_length=50, null=True)),
                ('validation_id', models.CharField(max_length=250, null=True)),
                ('validated_name', models.CharField(max_length=250, null=True)),
                ('bank_code', models.CharField(max_length=20, null=True)),
                ('bank_number', models.BigIntegerField(null=True)),
                ('disburse_status', models.CharField(max_length=50, null=True)),
                ('disburse_id', models.CharField(max_length=250, null=True)),
                ('disburse_amount', models.BigIntegerField(null=True)),
                ('loan', models.ForeignKey(db_column='loan_id',
                                           on_delete=django.db.models.deletion.DO_NOTHING,
                                           to='julo.Loan')),
            ],
            options={
                'db_table': 'disbursement',
            },
        ),
        migrations.RunSQL(
            "ALTER TABLE disbursement ALTER COLUMN loan_id TYPE bigint;"
        ),
        migrations.RunPython(db_insert_form_name_validate_status, migrations.RunPython.noop)
    ]
