# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-11-15 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from ..payment_methods import PaymentMethodCodes

def update_paymentmethod_exist(apps, schema_editor):
    PaymentMethod = apps.get_model("julo", "PaymentMethod")
    list_data = PaymentMethod.objects.all()
    for data in list_data:
        if data.payment_method_code == PaymentMethodCodes.INDOMARET:
            data.is_shown = False
        else:
            data.is_shown = True
        data.save()

class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0150_auto_20171113_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='FasPayTransaction',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='faspay_transaction_id', primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('amount', models.BigIntegerField(blank=True, null=True)),
                ('is_processed', models.NullBooleanField(default=False)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('status_desc', models.CharField(blank=True, max_length=60, null=True)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'faspay_transaction',
            },
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='is_shown',
            field=models.NullBooleanField(default=True),
        ),
        migrations.RunPython(update_paymentmethod_exist),
    ]
