# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-11-24 04:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0153_otprequest'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='otprequest',
            table='otp_request',
        ),
    ]
