# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-11-29 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0157_retroload_prefix_permata'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditScore',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='credit_score_id', primary_key=True, serialize=False)),
                ('score', models.TextField()),
                ('message', models.TextField()),
                ('products_str', models.TextField()),
                ('application', models.OneToOneField(db_column='application_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Application')),
            ],
            options={
                'db_table': 'credit_score',
            },
        ),
    ]
