# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-01-16 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0178_auto_20180109_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='is_warning',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='applicationoriginal',
            name='is_warning',
            field=models.NullBooleanField(default=False),
        ),
    ]
