# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-01-24 11:15
from __future__ import unicode_literals

from django.db import migrations, models
from ..partners import PartnerConstant

def retroload_partner_type(apps, schema_editor):
    Partner = apps.get_model("julo", "Partner")
    partners = Partner.objects.all()
    for partner in partners:
        if partner.name == PartnerConstant.BFI_PARTNER:
            partner.type = 'receiver'
        else:
            partner.type = 'referrer'
        partner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0180_load_bri_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='type',
            field=models.CharField(blank=True, choices=[('referrer', 'referrer'), ('receiver', 'receiver')], max_length=50, null=True),
        ),
        migrations.RunPython(retroload_partner_type, migrations.RunPython.noop),
    ]
