# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-01-25 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0182_auto_20180205_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='app_version_id', primary_key=True, serialize=False)),
                ('app_version', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('supported', 'supported'), ('deprecated', 'deprecated'), ('not_supported', 'not_supported'), ('latest', 'latest')], max_length=50)),
            ],
            options={
                'db_table': 'app_version',
            },
        ),
        migrations.CreateModel(
            name='CustomerAppAction',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='customer_app_action_id', primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('is_completed', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Customer')),
            ],
            options={
                'db_table': 'customer_app_action',
            },
        ),
    ]
