# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-19 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0186_auto_20180213_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutodialerHistory',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='autodialer_history_id', primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=50)),
                ('call_sequence', models.IntegerField(default=1)),
                ('next_turn', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'autodialer_history',
            },
        ),
        migrations.CreateModel(
            name='AutodialerStatus',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='autodialer_status_id', primary_key=True, serialize=False)),
                ('failed_count', models.IntegerField(default=0)),
                ('next_turn', models.DateTimeField(blank=True, null=True)),
                ('application_history', models.OneToOneField(db_column='application_history_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.ApplicationHistory')),
            ],
            options={
                'db_table': 'autodialer_status',
            },
        ),
        migrations.AddField(
            model_name='autodialerhistory',
            name='autodialer_status',
            field=models.ForeignKey(db_column='autodialer_status_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.AutodialerStatus'),
        ),
        migrations.AddField(
            model_name='autodialerhistory',
            name='call_result',
            field=models.ForeignKey(db_column='skiptrace_result_choice_id', on_delete=django.db.models.deletion.CASCADE, to='julo.SkiptraceResultChoice'),
        ),
    ]
