# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-16 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0194_auto_20180320_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentautodialersessionstatus',
            name='dpd_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
