# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-20 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0200_partnerreportemail_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='disabled_reapply_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='can_reapply_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
