# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-27 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0203_auto_20180322_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
