# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-04-11 08:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0210_auto_20180411_1536'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='workflowstatuspath',
            table='workflow_status_path',
        ),
    ]
