# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-04-11 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0212_add_collection_freelance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeReason',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='change_reason_id', primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('status', models.ForeignKey(db_column='change_reason_status', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.StatusLookup')),
            ],
            options={
                'db_table': 'change_reason',
            },
        ),
    ]
