# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-04-19 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0213_payment_interest_change_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowstatusnode',
            name='id',
            field=models.AutoField(db_column='status_node_id', primary_key=True, serialize=False),
        ),
    ]
