# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-03 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0214_x_application_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_reminder_called',
            field=models.BooleanField(default=False),
        ),
    ]
