# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-04-17 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0214_auto_20180419_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reminder_call_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
