# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-04-20 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0215_workflowfailureaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowfailureaction',
            name='is_recalled_succeed',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='workflowfailureaction',
            name='recalled_counter',
            field=models.IntegerField(default=0),
        ),
    ]
