# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-04-23 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0218_applicationworkflowswitchhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowstatuspath',
            name='type',
            field=models.CharField(blank=True, choices=[('happy', 'happy'), ('detour', 'detour'), ('graveyard', 'graveyard')], max_length=50, null=True),
        ),
    ]
