# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-04-24 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0219_auto_20180423_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationworkflowswitchhistory',
            name='id',
            field=models.AutoField(db_column='application_workflow_switch_history_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workflowfailureaction',
            name='id',
            field=models.AutoField(db_column='workflow_failure_action_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workflowstatusnode',
            name='id',
            field=models.AutoField(db_column='workflow_status_node_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workflowstatuspath',
            name='id',
            field=models.AutoField(db_column='workflow_status_path_id', primary_key=True, serialize=False),
        ),
    ]
