# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-08 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('line_of_credit', '0001_initial'),
        ('julo', '0227_load_loc_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='line_of_credit',
            field=models.ForeignKey(blank=True, db_column='line_of_credit_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='line_of_credit.LineOfCredit'),
        ),
        migrations.AddField(
            model_name='virtualaccountsuffix',
            name='line_of_credit',
            field=models.ForeignKey(blank=True, db_column='line_of_credit_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='line_of_credit.LineOfCredit'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='loan',
            field=models.ForeignKey(blank=True, db_column='loan_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Loan'),
        ),
        migrations.AlterField(
            model_name='productprofile',
            name='max_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productprofile',
            name='max_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productprofile',
            name='min_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productprofile',
            name='min_duration',
            field=models.IntegerField(default=0),
        ),
    ]
