# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-14 03:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('line_of_credit', '0001_initial'),
        ('julo', '0232_auto_20180509_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='sepulsatransaction',
            name='line_of_credit_transaction',
            field=models.ForeignKey(blank=True, db_column='line_of_credit_transaction_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='line_of_credit.LineOfCreditTransaction'),
        ),
    ]
