# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-02 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0240_customerwallethistory_wallet_delayed_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashbackXenditTransaction',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='cashback_xendit_transaction_id', primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_code', models.CharField(max_length=50, null=True)),
                ('bank_number', models.CharField(max_length=50)),
                ('name_in_bank', models.CharField(max_length=250)),
                ('validation_status', models.CharField(max_length=50, null=True)),
                ('validation_id', models.CharField(max_length=250, null=True)),
                ('validated_name', models.CharField(max_length=250, null=True)),
                ('transfer_status', models.CharField(max_length=50, null=True)),
                ('transfer_id', models.CharField(max_length=250, null=True)),
                ('transfer_amount', models.BigIntegerField()),
                ('failure_code', models.CharField(max_length=250, null=True)),
                ('failure_message', models.TextField(null=True)),
                ('external_id', models.CharField(max_length=250, blank=True, null=True)),
                ('retry_times', models.IntegerField(blank=True, default=0, null=True)),
                ('application', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Application')),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Customer')),
            ],
            options={
                'db_table': 'cashback_xendit_transaction',
            },
        ),
        migrations.AlterField(
            model_name='customerwallethistory',
            name='change_reason',
            field=models.CharField(choices=[('loan_initial', 'Earned on Loan Start'), ('loan_paid_off', 'Earned from Loan'), ('payment_on_time', 'Payment on Time'), ('paid_back_to_customer', 'Paid back to Customer'), ('used_on_payment', 'Used on Payment'), ('cashback_over_paid', 'Cashback Over Paid'), ('used_buy_pulsa', 'Used buy pulsa'), ('refunded_buy_pulsa', 'Refunded buy pulsa'), ('used_transfer_xendit', 'Used Transfer Xendit'), ('refunded_transfer_xendit', 'Refunded Transfer Xendit')], max_length=50),
        ),
        migrations.AddField(
            model_name='customerwallethistory',
            name='cashback_xendit_transaction',
            field=models.ForeignKey(blank=True, db_column='cashback_xendit_transaction_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.CashbackXenditTransaction'),
        ),
    ]
