# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-30 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0242_dashboardbuckets_app_cashback_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusLabel',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='status_label_id', primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
                ('label_name', models.CharField(max_length=100)),
                ('label_colour', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'status_label',
            },
        ),
    ]
