# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-06 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0244_devicescrapeddata_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmNavlog',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='crm_navlog_id', primary_key=True, serialize=False)),
                ('page_url', models.TextField(blank=True, null=True)),
                ('referrer_url', models.TextField(blank=True, null=True)),
                ('user', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('element', models.TextField(blank=True, null=True)),
                ('path', models.TextField(blank=True, null=True)),
                ('event', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'crm_navlog',
            },
        ),
    ]
