# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-14 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0246_auto_20180613_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceCallRecord',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='voice_call_id', primary_key=True, serialize=False)),
                ('event_type', models.TextField(blank=True, null=True)),
                ('voice_identifier', models.BigIntegerField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('direction', models.TextField(blank=True, null=True)),
                ('uuid', models.TextField()),
                ('conversation_uuid', models.TextField()),
                ('call_from', models.TextField(blank=True, null=True)),
                ('call_to', models.TextField(blank=True, null=True)),
                ('start_time', models.TextField(blank=True, null=True)),
                ('end_time', models.TextField(blank=True, null=True)),
                ('call_rate', models.TextField(blank=True, null=True)),
                ('call_price', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'voice_call_record',
            },
        ),
    ]
