# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-21 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0248_primodialerrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardbuckets',
            name='app_190',
            field=models.IntegerField(default=0),
        ),
    ]
