# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-07-09 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0254_update_stl_min_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='potential_skip_pv_dv',
            field=models.BooleanField(default=False),
        ),
    ]