# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-07-16 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0257_revert_loc_customer_criteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressgeolocation',
            name='kabupaten',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addressgeolocation',
            name='kecamatan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addressgeolocation',
            name='kelurahan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addressgeolocation',
            name='kodepos',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='addressgeolocation',
            name='provinsi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
