# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-07-27 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0263_applicationscrapeaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbackxendittransaction',
            name='redeem_amount',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
