# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-08-01 05:57
from __future__ import unicode_literals

from django.db import migrations, models
from ..statuses import ApplicationStatusCodes

def load_new_status_lookups(apps, schema_editor):
    StatusLookup = apps.get_model("julo", "StatusLookup")
    StatusLookup.objects.create(status_code=ApplicationStatusCodes.VERIFICATION_CALLS_SUCCESSFUL, status="Verification calls successful")
    status_130 = StatusLookup.objects.filter(status_code=ApplicationStatusCodes.APPLICANT_CALLS_SUCCESSFUL).last()
    if status_130:
        status_130.status = "Applicant calls successful"
        status_130.save()

def update_change_reason(apps, schema_editor):
    ChangeReason = apps.get_model("julo", "ChangeReason")
    StatusLookup = apps.get_model("julo", "StatusLookup")
    status_130 = StatusLookup.objects.filter(status_code=ApplicationStatusCodes.VERIFICATION_CALLS_SUCCESSFUL).last()
    reasons = ChangeReason.objects.filter(status_id=ApplicationStatusCodes.APPLICANT_CALLS_SUCCESSFUL,
                                              reason__in=['PV Employer Verified',
                                                          'Document Verified - Bank Scrape',
                                                          'Document Verified - Income Doc Upload'])
    for reason in reasons:
        reason.status = status_130
        reason.save()

def update_workflow_status_path(apps, schema_editor):
    WorkflowStatusPath = apps.get_model("julo", "WorkflowStatusPath")
    workflow_paths = WorkflowStatusPath.objects.filter(status_next=ApplicationStatusCodes.APPLICANT_CALLS_SUCCESSFUL)
    workflow_paths = workflow_paths.exclude(status_previous=ApplicationStatusCodes.VERIFICATION_CALLS_SUCCESSFUL)
    
    for workflow in workflow_paths:
        workflow.is_active = False
        workflow.save()

class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0267_new_status_164'),
    ]

    operations = [
        migrations.RunPython(load_new_status_lookups, migrations.RunPython.noop),
        migrations.RunPython(update_change_reason, migrations.RunPython.noop),
        migrations.RunPython(update_workflow_status_path, migrations.RunPython.noop),
        migrations.AddField(
            model_name='dashboardbuckets',
            name='app_124',
            field=models.IntegerField(default=0),
        ),
    ]
