# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-08-17 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0277_dashboard_collection_agent_90dpd'),
    ]

    operations = [
        migrations.CreateModel(
            name='BcaTransactionRecord',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='bca_transaction_id', primary_key=True, serialize=False)),
                ('transaction_date', models.DateField()),
                ('reference_id', models.CharField(max_length=20)),
                ('currency_code', models.CharField(max_length=10)),
                ('amount', models.IntegerField()),
                ('beneficiary_account_number', models.CharField(max_length=100)),
                ('remark1', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'bca_transaction_record',
            },
        ),
    ]
