# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-08-24 02:58
from __future__ import unicode_literals

from django.db import migrations, models

def update_event_type_payment_event(apps, schema_editor):
    PaymentEvent = apps.get_model("julo", "PaymentEvent")
    payment_events = PaymentEvent.objects.filter(
        event_type__in=['lebran_prmo_void', 'tokped_0intrst'])
    for payment_event in payment_events:
        if payment_event.event_type == 'lebran_prmo_void':
            payment_event.event_type = 'lebaran_promo_void'
        elif payment_event.event_type == 'tokped_0intrst':
            payment_event.event_type = 'tokped_0interest'
        payment_event.save()

class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0279_alter_bcatransactionrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentevent',
            name='event_type',
            field=models.CharField(default='payment', max_length=50),
        ),
        migrations.RunPython(update_event_type_payment_event, migrations.RunPython.noop)
    ]
