# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-08-31 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0282_new_status_126'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='google_access_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='google_refresh_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
