# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-09-13 03:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0286_reload_guarantor_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilefeaturesetting',
            name='parameters',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
