# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-09-24 08:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0291_auto_20180919_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='close_kin_mobile_phone',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='characters not allowed', regex='^[ -~]+$')]),
        ),
        migrations.AddField(
            model_name='application',
            name='close_kin_name',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='characters not allowed', regex='^[ -~]+$')]),
        ),
        migrations.AddField(
            model_name='application',
            name='close_kin_relationship',
            field=models.CharField(blank=True, choices=[('Orang tua', 'Orang tua'), ('Saudara kandung', 'Saudara kandung'), ('Famili lainnya', 'Famili lainnya')], max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='characters not allowed', regex='^[ -~]+$')], verbose_name='Hubungan kerabat'),
        ),
        migrations.AddField(
            model_name='applicationoriginal',
            name='close_kin_mobile_phone',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='characters not allowed', regex='^[ -~]+$')]),
        ),
        migrations.AddField(
            model_name='applicationoriginal',
            name='close_kin_name',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='characters not allowed', regex='^[ -~]+$')]),
        ),
        migrations.AddField(
            model_name='applicationoriginal',
            name='close_kin_relationship',
            field=models.CharField(blank=True, choices=[('Orang tua', 'Orang tua'), ('Saudara kandung', 'Saudara kandung'), ('Famili lainnya', 'Famili lainnya')], max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='characters not allowed', regex='^[ -~]+$')], verbose_name='Hubungan kerabat'),
        ),
    ]
