# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-09-14 11:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('julo', '0291_auto_20180924_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='created_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customerwallethistory',
            name='change_reason',
            field=models.CharField(choices=[('loan_initial', 'Earned on Loan Start'), ('loan_paid_off', 'Earned from Loan'), ('payment_on_time', 'Payment on Time'), ('paid_back_to_customer', 'Paid back to Customer'), ('used_on_payment', 'Used on Payment'), ('cashback_over_paid', 'Cashback Over Paid'), ('used_buy_pulsa', 'Used buy pulsa'), ('refunded_buy_pulsa', 'Refunded buy pulsa'), ('used_transfer', 'Used Transfer'), ('refunded_transfer', 'Refunded Transfer')], max_length=50),
        ),
    ]
