# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-10-16 04:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0296_robocall_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='dialect',
            field=models.CharField(blank=True, choices=[('Bahasa Jawa', 'Bahasa Jawa'), ('Bahasa Melayu-Indonesia', 'Bahasa Melayu-Indonesia'), ('Bahasa Sunda', 'Bahasa Sunda'), ('Bahasa Madura', 'Bahasa Madura'), ('Bahasa Batak', 'Bahasa Batak'), ('Bahasa Minangkabau', 'Bahasa Minangkabau'), ('Bahasa Bugis', 'Bahasa Bugis'), ('Bahasa Aceh', 'Bahasa Aceh'), ('Bahasa Bali', 'Bahasa Bali'), ('Bahasa Banjar', 'Bahasa Banjar'), ('Lainnya', 'Lainnya')], max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='characters not allowed', regex='^[ -~]+$')], verbose_name='Bahasa sehari-hari'),
        ),
        migrations.AddField(
            model_name='applicationoriginal',
            name='dialect',
            field=models.CharField(blank=True, choices=[('Bahasa Jawa', 'Bahasa Jawa'), ('Bahasa Melayu-Indonesia', 'Bahasa Melayu-Indonesia'), ('Bahasa Sunda', 'Bahasa Sunda'), ('Bahasa Madura', 'Bahasa Madura'), ('Bahasa Batak', 'Bahasa Batak'), ('Bahasa Minangkabau', 'Bahasa Minangkabau'), ('Bahasa Bugis', 'Bahasa Bugis'), ('Bahasa Aceh', 'Bahasa Aceh'), ('Bahasa Bali', 'Bahasa Bali'), ('Bahasa Banjar', 'Bahasa Banjar'), ('Lainnya', 'Lainnya')], max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='characters not allowed', regex='^[ -~]+$')], verbose_name='Bahasa sehari-hari'),
        ),
    ]
