# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-10-09 03:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from ..constants import FeatureNameConst


def add_assign_agent_settings(apps, schema_editor):
    FeatureSetting = apps.get_model("julo", "FeatureSetting")
    FeatureSetting.objects.get_or_create(is_active=True,
                                        feature_name=FeatureNameConst.ASSIGN_AGENT_DPD1_DPD30,
                                        category="agent",
                                        description="https://trello.com/c/sK96QE61"
                                        )
    FeatureSetting.objects.get_or_create(is_active=True,
                                        feature_name=FeatureNameConst.ASSIGN_AGENT_DPD31PLUS,
                                        category="agent",
                                        description="https://trello.com/c/sK96QE61"
                                        )

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('julo', '0297_loan_disbursment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanAgent',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='loan_agent_id', primary_key=True, serialize=False)),
                ('assign_time', models.DateTimeField(blank=True, null=True)),
                ('unassign_time', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('agent', models.ForeignKey(blank=True, db_column='agent_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(blank=True, db_column='loan_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Loan')),
            ],
            options={
                'db_table': 'loan_agent',
            },
        ),
        migrations.RunSQL(
            "ALTER TABLE loan_agent ALTER COLUMN loan_id TYPE bigint;"),
        migrations.RunPython(add_assign_agent_settings, migrations.RunPython.noop),
    ]
