# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-10-31 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0300_auto_20181024_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='application_through_partner',
        ),
        migrations.RemoveField(
            model_name='applicationoriginal',
            name='application_through_partner',
        ),
    ]
