# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-11-26 05:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0307_autodialer122queue'),
    ]

    operations = [
        migrations.CreateModel(
            name='NexmoAutocallHistory',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='nexmo_autocall_history_id', primary_key=True, serialize=False)),
                ('company_phone_number', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='characters not allowed', regex='^[ -~]+$')])),
                ('auto_call_result_status', models.CharField(blank=True, max_length=50, null=True)),
                ('conversation_uuid', models.CharField(blank=True, max_length=150, null=True)),
                ('application_history', models.ForeignKey(blank=True, db_column='application_history_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.ApplicationHistory')),
            ],
            options={
                'db_table': 'nexmo_autocall_history',
            },
        ),
    ]
