# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-11-27 04:17
from __future__ import unicode_literals

from django.db import migrations,models


class Migration(migrations.Migration):



    dependencies = [
        ('julo', '0325_reload_collection_vendor_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='is_shown',
            field=models.NullBooleanField(default=True),
        ),
    ]
