# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-01-08 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0336_auto_20190118_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReminderCallLogs',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='payment_reminder_call_log_id', primary_key=True, serialize=False)),
                ('call_id', models.CharField(blank=True, max_length=300, null=True)),
                ('answer', models.CharField(blank=True, max_length=300, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Payment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunSQL(
            "ALTER TABLE julo_paymentremindercalllogs ALTER COLUMN payment_id TYPE bigint;"),
    ]
