# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-01-18 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0336_paymentremindercalllogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookdatahistory',
            name='application',
            field=models.ForeignKey(blank=True, db_column='application_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='facebook_history_data', to='julo.Application'),
        ),
    ]
