# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-02 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0338_load_PromoJanuary_Experiments'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE payment_experiment ALTER COLUMN payment_id TYPE bigint;"),
    ]
