# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-01-23 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0339_alter_fk_column_paymentexperiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceiphistory',
            name='path',
            field=models.CharField(blank=True, max_length=200, null=True),
        )
    ]
