# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-01-31 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0344_retroload_app_auto_expiration_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentassignment',
            name='unassign_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
