# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-01-30 06:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0347_promo_robocall_template'),
    ]

    operations = [
        migrations.RenameField(
            model_name='robocalltemplate',
            old_name='promo_end_date',
            new_name='end_date',
        ),
        migrations.RemoveField(
            model_name='robocalltemplate',
            name='promo_start_date',
        ),
        migrations.AddField(
            model_name='robocalltemplate',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 30, 6, 31, 36, 238913, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='robocalltemplate',
            name='template_category',
            field=models.CharField(choices=[('PTP', 'PTP'), ('DEFAULT', 'Default'), ('PROMO', 'Promos'), ('ANNOUCE', 'Announce'), ('MISC', 'Misc')], default='DEFAULT', max_length=7),
        ),
    ]
