# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-02-26 09:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import juloserver.julo.models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0359_load_new_path_for_digisign_failed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardbuckets',
            name='app_145',
            field=models.IntegerField(default=0),
        ),
    ]
