# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-04-06 13:53
from __future__ import unicode_literals

from django.db import migrations, models
from juloserver.portal.object.product_profile.services import generate_product_lookup


LAKU6_PRODUCT = [{
    'code': 81,
    'name': 'SILVER',
    'min_amount': 1000000,
    'max_amount': 3000000,
    'min_duration': 12,
    'max_duration': 12,
    'min_interest_rate': 0.24,
    'max_interest_rate': 0.48,
    'interest_rate_increment': 0.12,
    'min_origination_fee': 0.05,
    'max_origination_fee': 0.05,
    'origination_fee_increment': 0.00,
    'cashback_initial': 0.00,
    'cashback_payment': 0.00,
    'late_fee': 0.00,
    'payment_frequency': 'Monthly',
    'debt_income_ratio': None,
    'is_initial': True,
    'is_active': True
}, {
    'code': 82,
    'name': 'GOLD',
    'min_amount': 3000000,
    'max_amount': 4000000,
    'min_duration': 12,
    'max_duration': 12,
    'min_interest_rate': 0.24,
    'max_interest_rate': 0.48,
    'interest_rate_increment': 0.12,
    'min_origination_fee': 0.05,
    'max_origination_fee': 0.05,
    'origination_fee_increment': 0.00,
    'cashback_initial': 0.00,
    'cashback_payment': 0.00,
    'late_fee': 0.00,
    'payment_frequency': 'Monthly',
    'debt_income_ratio': None,
    'is_initial': True,
    'is_active': True
}, {
    'code': 83,
    'name': 'PLATINUM',
    'min_amount': 4000000,
    'max_amount': 6000000,
    'min_duration': 12,
    'max_duration': 12,
    'min_interest_rate': 0.24,
    'max_interest_rate': 0.48,
    'interest_rate_increment': 0.12,
    'min_origination_fee': 0.05,
    'max_origination_fee': 0.05,
    'origination_fee_increment': 0.00,
    'cashback_initial': 0.00,
    'cashback_payment': 0.00,
    'late_fee': 0.00,
    'payment_frequency': 'Monthly',
    'debt_income_ratio': None,
    'is_initial': True,
    'is_active': True
}, {
    'code': 84,
    'name': 'DIAMOND',
    'min_amount': 6000000,
    'max_amount': 8000000,
    'min_duration': 12,
    'max_duration': 12,
    'min_interest_rate': 0.24,
    'max_interest_rate': 0.48,
    'interest_rate_increment': 0.12,
    'min_origination_fee': 0.05,
    'max_origination_fee': 0.05,
    'origination_fee_increment': 0.00,
    'cashback_initial': 0.00,
    'cashback_payment': 0.00,
    'late_fee': 0.00,
    'payment_frequency': 'Monthly',
    'debt_income_ratio': None,
    'is_initial': True,
    'is_active': True
}]

LAKU6_CUSTOMER = {
     'credit_score': ['A-', 'B+', 'B-']
}


def load_loc_product(apps, schema_editor):
    ProductLine = apps.get_model("julo", "ProductLine")
    ProductLookup = apps.get_model("julo", "ProductLookup")
    ProductProfile = apps.get_model("julo", "ProductProfile")
    ProductCustomerCriteria = apps.get_model("julo", "ProductCustomerCriteria")

    for product in LAKU6_PRODUCT:
        product_profile = ProductProfile(**product)
        product_profile.save()

        # laku6 customer criteria
        LAKU6_CUSTOMER['product_profile'] = product_profile
        product_customer_criteria = ProductCustomerCriteria(**LAKU6_CUSTOMER)
        product_customer_criteria.save()

        # laku6 product_line
        product_line = ProductLine.objects.create(
            product_line_code=product_profile.code,
            product_line_type=product_profile.name,
            min_amount=product_profile.min_amount,
            max_amount=product_profile.max_amount,
            min_duration=product_profile.min_duration,
            max_duration=product_profile.max_duration,
            min_interest_rate=product_profile.min_interest_rate,
            max_interest_rate=product_profile.max_interest_rate,
            payment_frequency=product_profile.payment_frequency,
            product_profile=product_profile
        )

        # product lookup
        product_lookup_list = generate_product_lookup(product_profile, product_line)
        for product_lookup_data in product_lookup_list:
            product_lookup = ProductLookup(**product_lookup_data)
            product_lookup.save()


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0360_new_status_145'),
    ]

    operations = [
        migrations.RunPython(load_loc_product, migrations.RunPython.noop),
    ]

