# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-02-26 10:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import juloserver.julo.models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0363_reload_submitting_form_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_success_robocall',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='voicecallrecord',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voicecallrecord',
            name='duration',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voicecallrecord',
            name='conversation_uuid',
            field=models.TextField(db_index=True),
        ),
    ]
