# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-02-26 12:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import juloserver.julo.models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0364_alter_robocall_payment_voicecallresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardbuckets',
            name='payment_Tminus3Robo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboardbuckets',
            name='payment_Tminus5Robo',
            field=models.IntegerField(default=0),
        ),
    ]
