# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-03-01 08:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import juloserver.julo.models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0367_selfie_mobile_feature_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerpurchaseitem',
            name='e_policy_number',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='characters not allowed', regex='^[ -~]+$')]),
        ),
        migrations.AddField(
            model_name='partnerpurchaseitem',
            name='imie_number',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='characters not allowed', regex='^[ -~]+$')]),
        ),
        migrations.AddField(
            model_name='partnerpurchaseitem',
            name='package',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='characters not allowed', regex='^[ -~]+$')]),
        ),
    ]
