# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-03-05 06:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import juloserver.julo.models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0369_load_new_laku6_productline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnerpurchaseitem',
            old_name='item_price',
            new_name='device_price',
        ),
        migrations.RenameField(
            model_name='partnerpurchaseitem',
            old_name='item_to_purchase',
            new_name='device_name',
        ),
        migrations.RenameField(
            model_name='partnerpurchaseitem',
            old_name='package',
            new_name='admin_fee',
        ),
        migrations.RenameField(
            model_name='partnerpurchaseitem',
            old_name='item_to_trade',
            new_name='device_trade',
        ),
        migrations.AddField(
            model_name='creditscore',
            name='credit_limit',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnerpurchaseitem',
            name='insurance_name',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='characters not allowed', regex='^[ -~]+$')]),
        ),
        migrations.AddField(
            model_name='partnerpurchaseitem',
            name='insurance_price',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='characters not allowed', regex='^[ -~]+$')]),
        ),
        migrations.AddField(
            model_name='partnerpurchaseitem',
            name='package_name',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='characters not allowed', regex='^[ -~]+$')]),
        ),
        migrations.AddField(
            model_name='partnerpurchaseitem',
            name='package_price',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='characters not allowed', regex='^[ -~]+$')]),
        ),
    ]
