# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-03-08 06:47
from __future__ import unicode_literals
from django.db import migrations
from ..management.commands import load_workflow


def update_status_145_and_132_for_digisign(apps, schema_editor):
    opts = {'workflow_name': ('cash_loan',)}
    load_workflow.Command().handle(**opts)


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0378_add_filename_in_document'),
    ]

    operations = [
        migrations.RunPython(update_status_145_and_132_for_digisign)
    ]
