# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-12-06 03:33
from __future__ import unicode_literals

from datetime import date
from django.db import migrations
from ..constants import FeatureNameConst


def add_isocollection_settings(apps, schema_editor):
    FeatureSetting = apps.get_model("julo", "FeatureSetting")
    FeatureSetting.objects.get_or_create(is_active=True,
                                         feature_name=FeatureNameConst.ISO_COLLECTION,
                                         category="collection",
                                         parameters={
                                            'start': '2019-03-12',
                                            'end': '2019-03-15'
                                         },
                                         description="hide collection buttons for iso"
                                        )


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0380_add_field_purchaseitempartner'),
    ]

    operations = [
        migrations.RunPython(add_isocollection_settings, migrations.RunPython.noop)
    ]
