# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-03-13 10:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import juloserver.julo.models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0383_add_digisign_mode_to_false'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='payday',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='applicationoriginal',
            name='payday',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
