# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-03-20 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import juloserver.julo.models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0391_load_roboscript_experiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smshistory',
            name='template_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
