# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-03-27 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import juloserver.julo.models

def create_payslip_feature_mobile_setting(apps, schema_editor):
    MobileFeatureSetting = apps.get_model("julo", "MobileFeatureSetting")
    setting = MobileFeatureSetting(
        feature_name="set_payslip_no_required",
        parameters={},
    )
    setting.save()


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0397_add_ptp_amount'),
    ]

    operations = [
        migrations.RunPython(create_payslip_feature_mobile_setting),
    ]
