# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-03-28 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import juloserver.julo.models

def create_birth_place_feature_mobile_setting(apps, schema_editor):
    MobileFeatureSetting = apps.get_model("julo", "MobileFeatureSetting")
    setting = MobileFeatureSetting(
        feature_name="set_birth_place_required",
        parameters={},
        is_active=False
    )
    setting.save()

class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0398_add_payslip_feature'),
    ]

    operations = [
        migrations.RunPython(create_birth_place_feature_mobile_setting),
    ]
