# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-04-01 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import juloserver.julo.models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0402_update_max_length_email_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_xid',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
