# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-04-03 03:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import juloserver.julo.models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0403_auto_20190401_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressgeolocation',
            name='customer',
            field=models.OneToOneField(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('Pria', 'Pria'), ('Wanita', 'Wanita')], max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='characters not allowed', regex='^[ -~]+$')], verbose_name='Jenis kelamin'),
        ),
        migrations.AlterField(
            model_name='addressgeolocation',
            name='application',
            field=models.OneToOneField(blank=True, db_column='application_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Application'),
        ),
    ]
