# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-04-05 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import juloserver.julo.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0404_auto_20190403_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappHistory',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='whatsapp_history_id', primary_key=True, serialize=False)),
                ('status', models.CharField(default='INITIATED', max_length=25)),
                ('error', models.TextField(blank=True, null=True)),
                ('message_content', models.TextField()),
                ('template_code', models.CharField(blank=True, max_length=50, null=True)),
                ('to_mobile_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('application', models.ForeignKey(blank=True, db_column='application_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Application')),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Customer')),
                ('payment', models.ForeignKey(blank=True, db_column='payment_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Payment')),
            ],
            options={
                'db_table': 'whatsapp_history',
            },
        ),
    ]
