# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-04-10 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import juloserver.julo.models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0414_whatsapp_history_bigint'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='can_notify',
            field=models.BooleanField(default=True),
        ),
    ]
