# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-04-24 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import juloserver.julo.models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0420_laku6_contract_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='special_first_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
