# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-15 04:28
from __future__ import unicode_literals
from django.db import migrations

def update_status_label(apps, schema_editor):
    labels = {'Tahap Persetujuan': [141,172],
              'Tahap Surat Perjanjian': [160],
              'Tahap Pencairan': [163, 162, 164, 175]
              }

    StatusLabel = apps.get_model("julo", "StatusLabel")
    for label in labels:
        statuses = labels[label]
        for status in statuses:
            status_label = StatusLabel.objects.get(status=status)
            status_label.label_name = label
            status_label.save()

class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0423_credit_score_added_failed_check'),
    ]

    operations = [
        migrations.RunPython(update_status_label, migrations.RunPython.noop),
    ]