# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-05-06 05:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import juloserver.julo.models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0424_update_status_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_whatsapp_blasted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dashboardbuckets',
            name='payment_whatsapp_blasted',
            field=models.IntegerField(default=0),
        ),
    ]
