# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-05-14 05:26
from __future__ import unicode_literals

from django.db import migrations, models
from ..constants import FeatureNameConst
from django.contrib.auth.models import Group
from dashboard.constants import JuloUserRoles


def load_feature_settings_bucket_collection(apps, schema_editor):
    FeatureSetting = apps.get_model("julo", "FeatureSetting")
    features = [FeatureNameConst.AGENT_ASSIGNMENT_DPD1_DPD15,
                FeatureNameConst.AGENT_ASSIGNMENT_DPD16_DPD29,
                FeatureNameConst.AGENT_ASSIGNMENT_DPD30_DPD44,
                FeatureNameConst.AGENT_ASSIGNMENT_DPD45_DPD59]
    for feature in features:
        FeatureSetting.objects.get_or_create(
            is_active=False,
            feature_name=feature,
            category="agent",
            description="https://juloprojects.atlassian.net/browse/END-259"
        )

def load_split_bucket_collection_role(apps, schema_editor):
    split_bucket_roles = [JuloUserRoles.COLLECTION_AGENT_2A,
                          JuloUserRoles.COLLECTION_AGENT_2B,
                          JuloUserRoles.COLLECTION_AGENT_3A,
                          JuloUserRoles.COLLECTION_AGENT_3B]
    for role in split_bucket_roles:
        Group.objects.get_or_create(name=role)


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0433_auto_20190516_1020'),
    ]

    operations = [
        migrations.RunPython(load_feature_settings_bucket_collection,
                             migrations.RunPython.noop),
        migrations.RunPython(load_split_bucket_collection_role,
                             migrations.RunPython.noop),
    ]
