# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-05-17 06:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import juloserver.julo.models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0436_alter_collection_assignment_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='skiptracehistory',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
