# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-06-12 06:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import juloserver.julo.models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0441_auto_20190529_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_xid',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
