# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-06-13 07:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import juloserver.julo.models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0445_auto_20190617_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerreferral',
            name='reminder_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
