# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-06-21 08:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import juloserver.julo.models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0450_add_agreement_letter_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='application_xid',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
