# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-06-27 05:56
from __future__ import unicode_literals

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import juloserver.julo.models


def add_digisign_configuration_data(apps, schema_editor):
    DigisignConfiguration = apps.get_model("julo", "DigisignConfiguration")
    DigisignConfigurationHistory = apps.get_model("julo", "DigisignConfigurationHistory")
    credit_score_threshold = 0.85
    product_selection = 'STL'

    digisigin_configuration = DigisignConfiguration(
        credit_score_threshold=credit_score_threshold, product_selection=product_selection
    )
    digisigin_configuration.save()

    digisigin_configuration_history = DigisignConfigurationHistory(
        credit_score_threshold=credit_score_threshold, product_selection=product_selection
    )
    digisigin_configuration_history.save()


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('julo', '0454_add_digisign_configuration'),
    ]

    operations = [
        migrations.RunPython(add_digisign_configuration_data)
    ]
