# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-03-27 10:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import juloserver.julo.models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0469_add_new_field_voice_call_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaybackTransaction',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='payback_transaction_id', primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(blank=True, max_length=36, null=True, unique=True)),
                ('payback_service', models.CharField(blank=True, choices=[('faspay', 'Faspay'), ('gopay', 'GoPay')], max_length=10, null=True)),
                ('amount', models.BigIntegerField(blank=True, null=True)),
                ('is_processed', models.NullBooleanField(default=False)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('status_desc', models.CharField(blank=True, max_length=60, null=True)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('virtual_account', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Virtual account has to be numeric digits', regex='^[0-9]+$')])),
                ('customer', models.ForeignKey(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Customer')),
                ('loan', models.ForeignKey(blank=True, db_column='loan_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Loan')),
                ('payment', models.ForeignKey(blank=True, db_column='payment_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Payment')),
                ('payment_method', models.ForeignKey(blank=True, db_column='payment_method_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.PaymentMethod')),
            ],
            options={
                'db_table': 'payback_transaction',
            },
        ),
        migrations.CreateModel(
            name='PaybackTransactionStatusHistory',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='payback_transaction_status_history_id', primary_key=True, serialize=False)),
                ('old_status_code', models.IntegerField(blank=True, null=True)),
                ('new_status_code', models.IntegerField(blank=True, null=True)),
                ('payback_transaction', models.ForeignKey(blank=True, db_column='payment_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.PaybackTransaction')),
            ],
            options={
                'db_table': 'payback_transaction_status_history',
            },
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='payment_receipt',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.RunSQL('ALTER TABLE payback_transaction ALTER COLUMN payment_id TYPE bigint;'),
        migrations.RunSQL('ALTER TABLE payback_transaction ALTER COLUMN loan_id TYPE bigint;'),
        migrations.RunSQL('ALTER TABLE payback_transaction ALTER COLUMN customer_id TYPE bigint;'),
    ]
