# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-08-08 11:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import juloserver.julo.models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0476_run_retroload_bca_va_for_axiata_and_icare'),
    ]

    operations = [
        migrations.AddField(
            model_name='promohistory',
            name='payment',
            field=models.ForeignKey(blank=True, db_column='payment_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Payment'),
        ),
    ]
