# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-09-10 10:22
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import juloserver.julo.models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0488_create_banner_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='data',
        ),
    ]
