# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-09-19 06:27
from __future__ import unicode_literals

from django.db import migrations


def delete_julo_mini_data (apps, schema_editor):
    FaqItem = apps.get_model("julo", "FaqItem")
    julomini_product_question = FaqItem.objects.filter(question = 'Berapa besar suku bunga yang ditawarkan oleh JULO?').last()

    if julomini_product_question is not None:
        description='Besar bunga Pinjaman JULO adalah sbb:<br> <table> <tr valign="top">' \
                    '<td><b>JULO Cicil</b>: 1.5% hingga 4% per bulan, ditetapkan berdasarkan hasil analisa' \
                    ' kelayakan kredit masing - masing nasabah</td></tr></table>'

        julomini_product_question.description=description
        julomini_product_question.save()



class Migration(migrations.Migration):


    dependencies = [
        ('julo', '0493_alter_banner_setting_table'),
    ]

    operations = [
        migrations.RunPython(delete_julo_mini_data),
    ]
