# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-09-18 12:09
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import juloserver.julo.models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0500_cm_v25_database'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppsFlyerLogs',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('log_id', models.AutoField(db_column='appsflyer_logs_id', primary_key=True, serialize=False)),
                ('status_new', models.IntegerField(blank=True, null=True)),
                ('status_old', models.IntegerField(blank=True, null=True)),
                ('appsflyer_device_id', models.CharField(blank=True, max_length=50, null=True)),
                ('appsflyer_log_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'appsflyer_logs',
            },
        ),
        migrations.AddField(
            model_name='AppsFlyerLogs',
            name='application',
            field=models.ForeignKey(blank=True, db_column='application_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Application'),
        ),
    ]
