# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-09-18 12:09
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import juloserver.julo.models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0500_create_appsflyer_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='AppsFlyerLogs',
            name='event_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
