# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-10-14 04:09
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import juloserver.julo.models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0513_create_referee_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='smshistory',
            name='is_otp',
            field=models.BooleanField(default=False),
        ),
    ]
