# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-10-22 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import juloserver.julo.models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0516_cootek_robocall_experiment_v3'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureMethodHistory',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='signature_method_history_id', primary_key=True, serialize=False)),
                ('signature_method', models.CharField(choices=[('-', '-'), ('JULO', 'JULO'), ('Digisign', 'Digisign')], default='-', max_length=50)),
                ('is_used', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'signature_method_history',
            },
        ),
        migrations.AddField(
            model_name='signaturemethodhistory',
            name='application',
            field=models.ForeignKey(blank=True, db_column='application_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Application'),
        ),
    ]
