# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-10-08 04:53
from __future__ import unicode_literals
from decimal import Decimal

from django.db import migrations

def add_product_line_to_digisign_configuration(apps, _schema_editor):
    DigisignConfiguration = apps.get_model("julo","DigisignConfiguration")
    product_selection_arr = []
    product_selections = [
        {
            "product_selection":"CTL",
        },{
            "product_selection":"BRI"
        },{
            "product_selection":"GRAB"
        },{
            "product_selection":"GRABFOOD"
        },{
            "product_selection":"STL"
        },{
            "product_selection":"LOC"
        },{
            "product_selection":"LAKU6"
        },{
            "product_selection":"ICARE"
        },{
            "product_selection":"AXIATA"
        },{
            "product_selection":"PEDEMTL"
        },{
            "product_selection":"PEDESTL"
        },{
            "product_selection":"MTL"
        }

        ]

    for product_selection in product_selections:
        data = DigisignConfiguration(
            product_selection=product_selection['product_selection'],
        )

        if DigisignConfiguration.objects.filter(product_selection=product_selection['product_selection']).exists():
            continue
        product_selection_arr.append(data)


    DigisignConfiguration.objects.bulk_create(product_selection_arr)


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0520_alter_field_digisign_configuration'),
    ]

    operations = [
         migrations.RunPython(add_product_line_to_digisign_configuration, migrations.RunPython.noop)
    ]
