# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-10-24 11:04
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import juloserver.julo.models


class Migration(migrations.Migration):

    dependencies = [
        ('followthemoney', '0011_create_lender_table'),
        ('julo', '0521_add_product_line_digisign_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='lenderbalance',
            name='lender',
            field=models.OneToOneField(blank=True, db_column='lender_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='followthemoney.LenderCurrent'),
        ),
        migrations.AddField(
            model_name='lendercustomercriteria',
            name='lender',
            field=models.OneToOneField(blank=True, db_column='lender_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='followthemoney.LenderCurrent'),
        ),
        migrations.AddField(
            model_name='lenderdisbursecounter',
            name='lender',
            field=models.OneToOneField(blank=True, db_column='lender_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='followthemoney.LenderCurrent'),
        ),
        migrations.AddField(
            model_name='lenderproductcriteria',
            name='lender',
            field=models.OneToOneField(blank=True, db_column='lender_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='followthemoney.LenderCurrent'),
        ),
        migrations.AddField(
            model_name='lenderservicerate',
            name='lender',
            field=models.ForeignKey(blank=True, db_column='lender_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='followthemoney.LenderCurrent'),
        ),
        migrations.AlterField(
            model_name='lenderbalance',
            name='partner',
            field=models.OneToOneField(blank=True, db_column='partner_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='julo.Partner'),
        ),
        migrations.AlterField(
            model_name='lendercustomercriteria',
            name='partner',
            field=models.OneToOneField(blank=True, db_column='partner_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='julo.Partner'),
        ),
        migrations.AlterField(
            model_name='lenderdisbursecounter',
            name='partner',
            field=models.OneToOneField(blank=True, db_column='partner_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='julo.Partner'),
        ),
        migrations.AlterField(
            model_name='lenderproductcriteria',
            name='partner',
            field=models.OneToOneField(blank=True, db_column='partner_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='julo.Partner'),
        ),
        migrations.AlterField(
            model_name='lenderservicerate',
            name='partner',
            field=models.OneToOneField(blank=True, db_column='partner_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='julo.Partner'),
        ),
    ]
