# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-10-24 11:17
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import juloserver.julo.models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0522_partner_to_lender'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailhistory',
            name='lender',
            field=models.ForeignKey(blank=True, db_column='lender_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='followthemoney.LenderCurrent'),
        ),
    ]
