# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-09-09 06:59
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import juloserver.julo.models


class Migration(migrations.Migration):

    dependencies = [
        ('minisquad', '__first__'),
        ('julo', '0539_create_signature_vendor_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='squad',
            field=models.ForeignKey(blank=True, db_column='squad_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='minisquad.CollectionSquad'),
        ),
    ]
