# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-12-10 11:39
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import juloserver.julo.models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0548_add_column_success_threshold_in_voice_call_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='skiptracehistory',
            name='excluded_from_bucket',
            field=models.NullBooleanField(),
        )
    ]
