# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-12-06 00:01
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import juloserver.julo.models


class Migration(migrations.Migration):
    def create_mother_maiden_name_setting(apps, schema_editor):
        MobileFeatureSetting = apps.get_model("julo", "MobileFeatureSetting")
        setting = MobileFeatureSetting(
            feature_name="mother_maiden_name",
            parameters={},
            is_active=True
        )
        setting.save()

    dependencies = [
        ('julo', '0552_loan_product_lookup_data_false_reject_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mother_maiden_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RunPython(create_mother_maiden_name_setting),
    ]
