# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-12-12 13:15
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import juloserver.julo.models
from juloserver.julo.partners import PartnerConstant


class Migration(migrations.Migration):

    def update_partner(apps, schema_editor):
        PartnerOriginationData = apps.get_model("julo", "PartnerOriginationData")
        Partner = apps.get_model("julo", "Partner")
        datas = [0, 9, 12, 13, 14]
        partner_axiata = Partner.objects.get(name=PartnerConstant.AXIATA_PARTNER)
        partners = PartnerOriginationData.objects.filter(pk__in=datas)
        for partner in partners:
            partner.partner = partner_axiata
            partner.save()


    dependencies = [
        ('julo', '0557_seed_product_lookup'),
    ]

    operations = [
        migrations.RunPython(update_partner)
    ]
