# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-12-19 03:47
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import juloserver.julo.models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0576_change_default_date_cootek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cootekrobocall',
            name='duration',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cootekrobocall',
            name='round',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
