# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-12-23 09:13
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import juloserver.julo.models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0579_initial_token_cootek_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='cootekrobocall',
            name='call_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
