# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-12-20 05:57
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import juloserver.julo.models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0580_add_call_status_cootek'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE cootek_robocall ALTER COLUMN payment_id TYPE bigint;"),
    ]
