# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-02-05 07:54
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import juloserver.julo.models


def iti_configuration_seeder(apps, schema_editor):
    ITIConfiguration = apps.get_model("julo", "ITIConfiguration")

    ITIConfiguration.objects.create(
        iti_version=8,
        min_threshold=0.0,
        max_threshold=0.96,
        min_income=0,
        max_income=10000000,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0596_update_fullname_trim_blacklist_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITIConfiguration',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='iti_configuration_id', primary_key=True, serialize=False)),
                ('iti_version', models.IntegerField(unique=True)),
                ('min_threshold', models.FloatField()),
                ('max_threshold', models.FloatField()),
                ('min_income', models.BigIntegerField()),
                ('max_income', models.BigIntegerField()),
            ],
            options={
                'db_table': 'iti_configuration',
            },
        ),
        migrations.RunPython(iti_configuration_seeder, migrations.RunPython.noop)
    ]
