# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-02-12 04:30
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import juloserver.julo.models


class Migration(migrations.Migration):

    def update_sphp_template(apps, _schema_editor):
        with open('juloserver/julo/templates/mtl_sphp.html', "r") as file:
            sphp_mtl = file.read()
            file.close()

        SphpTemplate = apps.get_model("julo", "SphpTemplate")
        SphpTemplate.objects.filter(
            product_name__in=('MTL1', 'MTL2')
        ).update(
            sphp_template=sphp_mtl)

    dependencies = [
        ('julo', '0607_create_fraud_model_experiment'),
    ]

    operations = [
       migrations.RunPython(update_sphp_template)
    ]
