# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-03-09 04:07
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import juloserver.julo.models
from juloserver.julo.constants import FeatureNameConst


class Migration(migrations.Migration):

    def update_description_notification_balance_amount(apps, schema_editor):
        FeatureSetting = apps.get_model("julo", "FeatureSetting")
        feature_setting = FeatureSetting.objects.filter(
            feature_name=FeatureNameConst.NOTIFICATION_BALANCE_AMOUNT).first()
        feature_setting.description = 'Lender Low Balance Notification'
        feature_setting.save()

    dependencies = [
        ('julo', '0619_partner_workflow_163_to_165'),
    ]

    operations = [
        migrations.RunPython(update_description_notification_balance_amount),
    ]
