# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-01-30 07:17
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import juloserver.julo.models

from juloserver.julo.constants import FeatureNameConst

def add_special_event_binary_feature_setting(apps, _schema_editor):
    FeatureSetting = apps.get_model("julo", "FeatureSetting")
    FeatureSetting.objects.get_or_create(
        is_active=True,
        feature_name=FeatureNameConst.SPECIAL_EVENT_BINARY,
        description="Configuration for Special Event Binary that will reject "
                    "several customer that meet criteria",
    )

class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0636_new_table_digital_signature_face_result'),
    ]

    operations = [
        migrations.RunPython(add_special_event_binary_feature_setting, migrations.RunPython.noop),
    ]
