# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-01-30 07:17
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst

def add_affordability_discount_feature_setting(apps, _schema_editor):
    FeatureSetting = apps.get_model("julo", "FeatureSetting")
    FeatureSetting.objects.get_or_create(
        is_active=True,
        feature_name=FeatureNameConst.AFFORDABILITY_VALUE_DISCOUNT,
        description="Configuration for COVID 19 - Affordability Value Discount to reduce capital exposure",
        parameters={'buffer_value': 250000}
    )

class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0638_update_field_iti_config'),
    ]

    operations = [
        migrations.RunPython(add_affordability_discount_feature_setting, migrations.RunPython.noop),
    ]
