# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-03-31 09:40
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import juloserver.julo.models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0647_update_promo_benefit'),
    ]

    operations = [
        migrations.CreateModel(
            name='FDCInquiryCheck',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='fdc_inquiry_check_id', primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False)),
                ('min_threshold', models.FloatField()),
                ('max_threshold', models.FloatField()),
                ('min_tidak_lancar', models.IntegerField(default=0)),
                ('min_macet', models.IntegerField(default=0)),
                ('max_paid_pct', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'fdc_inquiry_check',
            },
        ),
    ]
