# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-04-22 08:25
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import juloserver.julo.models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0658_add_mobile_feature_setting_mock_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_fdc_risky',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='applicationoriginal',
            name='is_fdc_risky',
            field=models.NullBooleanField(),
        ),
    ]
