# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-05-12 07:43
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import juloserver.julo.models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0668_change_end_ts_skiptrace_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPreRefinancing',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='payment_pre_refinancing_id', primary_key=True, serialize=False)),
                ('payment_number', models.IntegerField()),
                ('due_date', models.DateField(null=True)),
                ('ptp_date', models.DateField(blank=True, null=True)),
                ('ptp_robocall_phone_number', models.CharField(blank=True, max_length=18, null=True, validators=[django.core.validators.RegexValidator(message='characters not allowed', regex='^[ -~]+$')])),
                ('is_ptp_robocall_active', models.NullBooleanField()),
                ('due_amount', models.BigIntegerField()),
                ('installment_principal', models.BigIntegerField(default=0)),
                ('installment_interest', models.BigIntegerField(default=0)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('paid_amount', models.BigIntegerField(blank=True, default=0)),
                ('redeemed_cashback', models.BigIntegerField(default=0)),
                ('cashback_earned', models.BigIntegerField(blank=True, default=0)),
                ('late_fee_amount', models.BigIntegerField(blank=True, default=0)),
                ('late_fee_applied', models.IntegerField(blank=True, default=0)),
                ('discretionary_adjustment', models.BigIntegerField(blank=True, default=0)),
                ('is_robocall_active', models.NullBooleanField()),
                ('is_success_robocall', models.NullBooleanField()),
                ('is_collection_called', models.BooleanField(default=False)),
                ('uncalled_date', models.DateField(null=True)),
                ('reminder_call_date', models.DateTimeField(blank=True, null=True)),
                ('is_reminder_called', models.BooleanField(default=False)),
                ('is_whatsapp', models.BooleanField(default=False)),
                ('is_whatsapp_blasted', models.NullBooleanField(default=False)),
                ('paid_interest', models.BigIntegerField(blank=True, default=0)),
                ('paid_principal', models.BigIntegerField(blank=True, default=0)),
                ('paid_late_fee', models.BigIntegerField(blank=True, default=0)),
                ('ptp_amount', models.BigIntegerField(blank=True, default=0)),
                ('change_due_date_interest', models.BigIntegerField(blank=True, default=0)),
                ('is_restructured', models.BooleanField(default=False)),
                ('loan', models.ForeignKey(db_column='loan_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Loan')),
            ],
            options={
                'db_table': 'payment_pre_refinancing',
            },
        ),
        migrations.AddField(
            model_name='paymentprerefinancing',
            name='payment',
            field=models.ForeignKey(db_column='payment_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Payment'),
        ),
        migrations.AddField(
            model_name='paymentprerefinancing',
            name='payment_status',
            field=models.ForeignKey(db_column='payment_status_code', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.StatusLookup'),
        ),
        migrations.AddField(
            model_name='paymentprerefinancing',
            name='ptp_robocall_template',
            field=models.ForeignKey(blank=True, db_column='robocall_template_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.RobocallTemplate'),
        ),
    ]
