# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-05-18 08:44
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import juloserver.julo.models


def create_payment_method_configuration_setting(apps, schema_editor):
    MobilePaymentMethods = apps.get_model("julo", "MobilePaymentMethods")
    feature_names = ['Gopay','ALFAMART','INDOMARET']
    for feature_name in feature_names:
        is_shown = True
        if feature_name == 'Gopay':
            is_shown = False
        MobilePaymentMethods.objects.create(
                payment_method_name=feature_name, is_shown=is_shown)


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0670_alter_table_payment_pre_refinancing'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobilePaymentMethods',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='mobile_payment_methods_id', primary_key=True, serialize=False)),
                ('payment_method_name', models.CharField(max_length=100)),
                ('is_shown', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'mobile_payment_methods',
            },
        ),
        migrations.RunPython(create_payment_method_configuration_setting),
    ]
