# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-06-10 10:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0678_alter_loan_description_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='loan_purpose_description_expanded',
        ),
        migrations.RemoveField(
            model_name='applicationoriginal',
            name='loan_purpose_description_expanded',
        ),
        migrations.AddField(
            model_name='application',
            name='loan_purpose_description_expanded',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='applicationoriginal',
            name='loan_purpose_description_expanded',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='loan_purpose_description_expanded',
            field=models.TextField(blank=True, null=True,
                                   validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
        migrations.AlterField(
            model_name='applicationoriginal',
            name='loan_purpose_description_expanded',
            field=models.TextField(blank=True, null=True,
                                   validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
    ]
