# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-07-06 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0693_update_sphp_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentproductivity',
            name='login_ts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentproductivity',
            name='logout_ts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skiptracehistory',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skiptracehistory',
            name='status_group',
            field=models.TextField(blank=True, null=True),
        ),
    ]
