# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-08-03 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0697_addfield_accounting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditmatrix',
            name='parameter',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='creditmatrix',
            name='priority',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='creditscore',
            name='credit_matrix_id',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
