# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-03-04 05:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackEWABucket',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='slack_ewa_bucket_id', primary_key=True, serialize=False)),
                ('display_text', models.CharField(blank=True, max_length=100, null=True)),
                ('order_priority', models.IntegerField(default=0)),
                ('disable', models.BooleanField(default=False)),
                ('status_code', models.OneToOneField(db_column='status_code_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.StatusLookup')),
            ],
            options={
                'ordering': ['order_priority'],
                'db_table': 'slack_ewa_bucket',
            },
        ),
        migrations.CreateModel(
            name='SlackEWAStatusEmotion',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='slack_ewa_status_emotion_id', primary_key=True, serialize=False)),
                ('condition', models.CharField(max_length=20)),
                ('emoji', models.CharField(max_length=50)),
                ('bucket', models.ForeignKey(blank=True, db_column='bucket_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slack_ewa_emoji', to='utilities.SlackEWABucket')),
            ],
            options={
                'db_table': 'slack_ewa_status_emotion',
            },
        ),
        migrations.CreateModel(
            name='SlackEWATag',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='slack_ewa_tag_id', primary_key=True, serialize=False)),
                ('condition', models.CharField(max_length=20)),
                ('bucket', models.ForeignKey(blank=True, db_column='bucket_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slack_ewa_tag', to='utilities.SlackEWABucket')),
            ],
            options={
                'db_table': 'slack_ewa_tag',
            },
        ),
        migrations.CreateModel(
            name='SlackUser',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='slack_ewa_user_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('slack_id', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'slack_ewa_user',
            },
        ),
        migrations.AddField(
            model_name='slackewatag',
            name='slack_user',
            field=models.ManyToManyField(blank=True, to='utilities.SlackUser'),
        ),
    ]
