# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-05-19 03:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minisquad', '0015_add_new_column_sorted_by_collection_model_for_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorQualityExperiment',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='vendor_quality_experiment_id', primary_key=True, serialize=False)),
                ('bucket', models.TextField()),
                ('experiment_group', models.TextField()),
                ('experiment_setting', models.ForeignKey(db_column='experiment_setting_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.ExperimentSetting')),
                ('loan', models.ForeignKey(db_column='loan_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Loan')),
                ('payment', models.ForeignKey(db_column='payment_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Payment')),
            ],
            options={
                'db_table': 'vendor_quality_experiment',
            },
        ),
    ]
