# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-06-19 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('julo', '0681_create_email_feature_setting'),
        ('minisquad', '0020_add_failed_call_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentToDialer',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(
                    db_column='sent_to_dialer_id',
                    primary_key=True,
                    serialize=False)
                 ),
                ('bucket', models.TextField()),
                ('sorted_by_collection_model', models.NullBooleanField()),
                ('dialer_task', models.ForeignKey(
                    db_column='dialer_task_id',
                    on_delete=django.db.models.deletion.DO_NOTHING,
                    to='minisquad.DialerTask')
                 ),
                ('loan', models.ForeignKey(
                    db_column='loan_id',
                    on_delete=django.db.models.deletion.DO_NOTHING,
                    to='julo.Loan')
                 ),
                ('payment', models.ForeignKey(
                    db_column='payment_id',
                    on_delete=django.db.models.deletion.DO_NOTHING,
                    to='julo.Payment')
                 ),
            ],
            options={
                'db_table': 'sent_to_dialer',
            },
        ),
        migrations.RunSQL(
            "ALTER TABLE sent_to_dialer ALTER COLUMN payment_id TYPE bigint;"
        ),
        migrations.RunSQL(
            "ALTER TABLE sent_to_dialer ALTER COLUMN loan_id TYPE bigint;"
        )
    ]
