# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-07-02 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minisquad', '0022_senttodialer_deleted_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionsquadassignment',
            name='bucket_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
