class BSSDocumentHeaderConst:
    # Document Types
    CIF = 'CIF'
    SCHEDULE = 'SCHEDULE'
    LOAN = 'LOAN'
    COLLATERAL = 'COLLATERAL'
    LIST = (CIF, SCHEDULE, LOAN, COLLATERAL)

    # Constants
    BRANCH_CODE = 'JL1BSS001'

    # Skipped Fields
    SKIP_CHECKER = (
        "admfee",
        "merkcode",
        "modelcode",
        "collateralno",
        "collateraldate",
        "collateraladdress",
        "collateralcityid",
        "collateralname",
        "collateralownerid",
        "collateraldesctype",
        "engineno",
        "chassisno",
        "collateralyear",
        "buildyear",
        "condition",
        "color",
        "collateralkind",
        "collateralpurpose",
        "policeno",
        "stnkexpired",
        "surveydate",
        "bindtypecode",
        "collateraltypecode",
        "sbrankcode",
        "tenorunit",
        "loantype",
        "inscode",
        "inspremi",
        "insonloan",
        "installmenttype",
        "branchcode",
        "typeofuseid",
        "orientationofuseid",
        "debiturcatid",
        "portfoliocatid",
        "credittypeid",
        "creditattributeid",
        "creditcategoryid",
        "fincat",
        "creditdistrib",
        "idcompany",
        "Interestratecust",
        "custtype",
        "title",
        "custrt",
        "custrw",
        "idtype",
        "idexpired",
        "workradius",
        "employeests",
        "contractend",
        "economycode",
        "debiturcode",
        "npwp",
        "homestatus",
        "phonearea",
        "sameidhomeaddr",
        "custrthome",
        "custrwhome",
        "spousebirthdate",
        "spousebirthplace",
        "spouseidtype",
        "spouseidnumber",
        "spousephoneno",
        "spousemobileno",
        "spouseoffice",
        "spouseoffinephone",
        "relativestype",
        "custaddressrel",
        "custrtrel",
        "custrwrel",
        "custkelrel",
        "custkecrel",
        "custcityrel",
        "custprovrel",
        "custziprel",
        "phonenorel",
        "companyaddr",
        "companycity",
        "companyzip",
        "companyphone",
        "deedno",
        "deeddate",
        "corporatetype",
        "jobid",
        "jobtitleid",
        "countryid",
        "branchcode",
        "targetmarket",
        "din",
        "principalpaid",
        "interestpaid",
        "penaltypaid",
        "paidsts",
        "paiddate",
        "paidtxndate",
        "deposit",
        "productcode",
    )
    FUNCTION_MAPPING = {
        "refno": "get_bss_refno_manual",
    }
    # Mappings
    COLLATERAL_FIELD = {
        "refno": "loan",
        "productcode": "000",
        "merkcode": "IDBSS001",
        "modelcode": "IDBSS002",
        "collateralno": "0",
        "collateraldate": "",
        "collateraladdress": "NA",
        "collateralcityid": "0",
        "collateralname": "NA",
        "collateralownerid": "0",
        "collateraldesctype": "",
        "engineno": "NA",
        "chassisno": "NA",
        "collateralyear": "2028",
        "buildyear": "9999",
        "condition": "1",
        "color": "color",
        "collateralkind": "otp",
        "collateralpurpose": "9",
        "policeno": "NA",
        "stnkexpired": "",
        "surveydate": "9999-12-12",
        "bindtypecode": "99",
        "collateraltypecode": "300",
        "sbrankcode": "A3",
        "collateralvalue": "loan.loan_amount",
        "owncollateral": "0",
    }

    LOAN_FIELD = {
        "refnocustid": "loan.loan_xid",
        "refno": "loan",
        "objectvalue": "loan.loan_amount",
        "principaltotal": "loan.loan_amount",
        "tenor": "loan.loan_duration",
        "tenorunit": "3",
        "loantype": "0",
        "effectiverate": "effective_rate",
        "installment": "loan.installment_amount",
        "firstinstdate": "first_payment.due_date",
        "admfee": "0",
        "inscode": "1",
        "inspremi": "0",
        "insonloan": "0",
        "installmenttype": "103",
        "branchcode": "ID0010009",
        "typeofuseid": "3",
        "orientationofuseid": "3",
        "debiturcatid": "99",
        "portfoliocatid": "36",
        "credittypeid": "20",
        "creditattributeid": "9",
        "creditcategoryid": "99",
        "fincat": "000",
        "creditdistrib": "3",
        "idcompany": "JL1BSS001",
        "Interestratecust": "30",
        "disbursedate": "loan.fund_transfer_ts",
        "deposit": "0",
    }
    SCHEDULE_FIELD = {'list_payments': "loan"}
    CIF_FIELD = {
        'refnocustid': "loan.loan_xid",
        'din': "",
        'custtype': "1",
        'fullname': "application.fullname",
        'custname': "application.fullname",
        'title': "00",
        'custaddress': "application.full_address",
        'custrt': "00",
        'custrw': "00",
        'custkel': "application.address_kelurahan",
        'custkec': "application.address_kecamatan",
        'custcity': "application.address_kabupaten",
        'custprov': "application.address_provinsi",
        'custzip': "application.address_kodepos",
        'custdati': "application.address_kabupaten",
        'idtype': "1",
        'idnumber': "application.ktp",
        'idexpired': "2999-12-31",
        'gender': '"1" if application.gender == "Pria" else "2"',
        'maritalstatus': "BSSMaritalStatusConst.LIST[application.marital_status]",
        'birthdate': "application.dob",
        'birthplace': "application.birth_place",
        'birthdati': "application.address_kabupaten",
        'worksince': "application.job_start",
        'workradius': "",
        'employeests': "",
        'contractend': "",
        'lasteducation': "last_education",
        'economycode': "004190",
        'debiturcode': "9000",
        'mmn': "application.customer_mother_maiden_name",
        'npwp': "0",
        'homestatus': "",
        'livedsince': "application.occupied_since",
        'phonearea': "0",
        'phoneno': "application.mobile_phone_1",
        'mobileno': "application.mobile_phone_1",
        'dependent': "application.dependent or 0",
        'grossincome': "application.monthly_income",
        'expenses': "application.monthly_expenses",
        'sameidhomeaddr': "0",
        'custaddresshome': "application.full_address",
        'custrthome': "00",
        'custrwhome': "00",
        'custkelhome': "application.address_kelurahan",
        'custkechome': "application.address_kecamatan",
        'custcityhome': "application.address_kabupaten",
        'custprovhome': "application.address_provinsi",
        'custziphome': "application.address_kodepos",
        'custdatihome': "application.address_kabupaten",
        'spousename': "application.spouse_name",
        'spousebirthdate': "",
        'spousebirthplace': "",
        'spouseidtype': "1",
        'spouseidnumber': "",
        'spousephoneno': "",
        'spousemobileno': "",
        'spouseoffice': "",
        'spouseoffinephone': "",
        'relativestype': "",
        'relativesname': "application.kin_name or application.spouse_name",
        'custaddressrel': "NA",
        'custrtrel': "",
        'custrwrel': "",
        'custkelrel': "",
        'custkecrel': "",
        'custcityrel': "",
        'custprovrel': "",
        'custziprel': "",
        'phonenorel': "",
        'companyname': "application.company_name",
        'companyaddr': "",
        'companycity': "",
        'companyzip': "",
        'companyphone': "",
        'deedno': "",
        'deeddate': "",
        'corporatetype': "",
        'jobid': "099",
        'jobtitleid': "69",
        'countryid': "ID",
        'branchcode': "JL1BSS001",
        'targetmarket': "1",
        'email': "application.email",
    }

    DATI_FIELD = {
        "custdati",
        "birthdati",
        "custdatihome",
    }
    DATE_FORMAT_FIELD = ("birthdate", "worksince", "livedsince", "firstinstdate", "disbursedate")
