# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-01-25 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_status', '0002_applicationlockedmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoDataCheck',
            fields=[
                ('id', models.BigIntegerField(db_column='data_check_id', primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('application_id', models.BigIntegerField(db_index=True)),
                ('check_set', models.CharField(max_length=50)),
                ('data_to_check', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('is_okay', models.BooleanField()),
                ('text_value', models.CharField(blank=True, max_length=150, null=True)),
                ('number_value', models.BigIntegerField(blank=True, null=True)),
                ('latest', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ana"."auto_data_check',
                'managed': False,
            },
        ),
    ]
