# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-03-28 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import juloserver.julo.models

from juloserver.julo.models import MobileFeatureSetting


def failover_digisign_feature_mobile_setting(apps, schema_editor):
    
    setting = MobileFeatureSetting(
        feature_name="failover_digisign",
        parameters={},
        is_active=True
    )
    setting.save()

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(failover_digisign_feature_mobile_setting),
    ]
