# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-04-07 06:11
from __future__ import unicode_literals

from django.db import migrations
from juloserver.streamlined_communication.constant import CommunicationPlatform

from juloserver.julo.constants import VoiceTypeStatus


from juloserver.streamlined_communication.models import StreamlinedCommunication



from juloserver.streamlined_communication.models import StreamlinedMessage



def add_nexmo_robocall_message_mtl_overdue(apps, schema_editor):
    
    


    # MTL + 4
    message_content = '[{"action": "talk","voiceName": "Damayanti","text": "Selamat {{greet}} {{name_with_title}}, ' \
                      'angsuran ke {{payment_number}} JULO Anda sebesar {{due_amount}}. ' \
                      'Segera lakukan pembayaran karena mulai besok, Anda akan terkena denda. Terima kasih"}]'
    robocall_reminder_plus4, _ = \
        StreamlinedMessage.objects.get_or_create(
            message_content=message_content,
            parameter="{greet,name_with_title,payment_number,due_amount}"
        )

    streamlined_communication_for_robocall_reminder_mtl_inplus4 = StreamlinedCommunication.objects.get_or_create(
        message=robocall_reminder_plus4,
        status="this Robocall is send on  dpd=4 for mtl",
        communication_platform=CommunicationPlatform.ROBOCALL,
        template_code="nexmo_robocall_mtl_dpd_4",
        dpd=4,
        type=VoiceTypeStatus.PAYMENT_REMINDER,
        product="nexmo_mtl",
        is_automated=True,
        description="send nexmo robocall mtl payment reminder dpd4",
        function_name="{send_voice_payment_reminder,"
                      "retry_send_voice_payment_reminder1,"
                      "retry_send_voice_payment_reminder2}",
        call_hours="{8:00,10:00,12:00}",
        attempts=3
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_nexmo_robocall_message_mtl_overdue, migrations.RunPython.noop),
    ]
