# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-02-26 08:38
from __future__ import unicode_literals
from django.db import migrations, models
from juloserver.julo.statuses import ApplicationStatusCodes
from juloserver.julo.management.commands import load_workflow, update_status_lookups, load_status_change_reasons


from juloserver.julo.models import Experiment, Workflow



from juloserver.julo.models import WorkflowStatusPath



def create_new_status_path_for_new_bank_validation_flow(apps, schema_editor):
    opts = {'workflow_name': ('cash_loan',)}
    load_workflow.Command().handle(**opts)


def delete_status_path_for_name_banK_validation_flow(apps, schema_editor):
    
    cash_loan_workflow =Workflow.objects.get(name='CashLoanWorkflow')
    deleted_status = [
        {
            # 163 -> 164
            'status_previous': ApplicationStatusCodes.LEGAL_AGREEMENT_SUBMITTED,
            'status_next': ApplicationStatusCodes.NAME_VALIDATE_ONGOING,
        },
        {
            # 175 -> 164
            'status_previous': ApplicationStatusCodes.NAME_VALIDATE_FAILED,
            'status_next': ApplicationStatusCodes.NAME_VALIDATE_ONGOING,
        },
    ]
    for deleted in deleted_status:
        path = WorkflowStatusPath.objects.filter(
            status_previous=deleted['status_previous'],
            status_next=deleted['status_next'],
            workflow=cash_loan_workflow
        ).last()
        if path:
            path.delete()

def change_experiment(apps, schema_editor):
    
    experiment = Experiment.objects.filter(code='AUTO163TO164').last()
    if experiment:
        experiment_change = experiment
        experiment_change.code = 'AUTO163TO165'
        experiment_change.save()
        experiment_action = experiment_change.experimentaction_set.filter(type='CHANGE_STATUS').last()
        if experiment_action:
            experiment_action.value = 165
            experiment_action.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(delete_status_path_for_name_banK_validation_flow),
        migrations.RunPython(create_new_status_path_for_new_bank_validation_flow),
        migrations.RunPython(change_experiment),
    ]
