# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-15 04:20
from __future__ import unicode_literals

from django.db import migrations, models
from juloserver.julo.services import create_application_checklist
from juloserver.julo.models import Application


from juloserver.julo.models import Application



def retroactively_create_application_checklist(apps, schema_editor):
    # 

    applications = Application.objects.filter(application_status__lt=180)
    for application in applications:
        create_application_checklist(application)

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
#        migrations.RunPython(retroactively_create_application_checklist, migrations.RunPython.noop)
    ]
    
