# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-11-08 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


from juloserver.julo.models import StatusLookup



def db_insert_form_name_validate_status(apps, schema_editor):
    
    StatusLookup.objects.get_or_create(status_code=175,
                                       status='Name validation failed')

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE disbursement ALTER COLUMN loan_id TYPE bigint;"
        ),
        migrations.RunPython(db_insert_form_name_validate_status, migrations.RunPython.noop)
    ]
