# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-15 04:28
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.partners import PartnerConstant


from juloserver.julo.models import Partner



from django.contrib.auth.models import Group, User



def load_doku_partner(apps, schema_editor):

    
    group = Group.objects.get(name="julo_partners")

    user = User.objects.create(username='doku', email='doku@example.com', password='dokutest')
    user.groups.add(group)

    
    Partner.objects.create(
        user=user, name=PartnerConstant.DOKU_PARTNER, email='doku@example.com',
        phone='+628121278907')


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(load_doku_partner, migrations.RunPython.noop)
    ]
