# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-12-11 12:31
from __future__ import unicode_literals

from builtins import range
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import juloserver.julo.models
from juloserver.julo.product_lines import ProductLineCodes
from juloserver.julo.models import ProductProfile
from juloserver.julo.models import ProductLine
from juloserver.julo.models import ProductLookup
from juloserver.julo.product_lines import ProductLines

class Migration(migrations.Migration):
    # add value partner origination fee to product lookup table


    def add_value_to_product_lookup_table(apps, schema_editor):
        
        product_line_axiata1 = ProductLine.objects.get(pk=ProductLineCodes.AXIATA1)
        product_line_axiata2 = ProductLine.objects.get(pk=ProductLineCodes.AXIATA2)
        product_profile_axiata1 = ProductProfile.objects.get(pk=product_line_axiata1.product_profile.id)
        product_profile_axiata2 = ProductProfile.objects.get(pk=product_line_axiata2.product_profile.id)
        product_lines = [product_line_axiata1, product_line_axiata2]
        product_profiles= [product_profile_axiata1, product_profile_axiata2]
        origination_fees = [0.01, 0.015]
        # record 4 value to product look table
        for idx in range(2):
            for i, product_line in enumerate(product_lines):
                ProductLookup.objects.create(
                    product_name="I.000-O.{}-L.000-C1.000-C2.000-M".format(origination_fees[idx]),
                    interest_rate=0,
                    origination_fee_pct=origination_fees[idx],
                    late_fee_pct=0,
                    cashback_initial_pct=0,
                    cashback_payment_pct=0,
                    product_line=product_line,
                    product_profile=product_profiles[i]
                )

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_value_to_product_lookup_table)
    ]
