# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-09-23 03:30
from __future__ import unicode_literals

from django.db import migrations


from juloserver.julo.models import WorkflowStatusPath



from juloserver.julo.models import Workflow



def add_work_flow_status_path_129_to_139_for_expire_BFI_leads(apps, _schema_editor):
    
    workflow = Workflow.objects.filter(name="CashLoanWorkflow").first()
    if workflow:
        
        WorkflowStatusPath.objects.get_or_create(
            status_previous=129,
            status_next=139,
            type="graveyard",
            workflow=workflow
        )
class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_work_flow_status_path_129_to_139_for_expire_BFI_leads, migrations.RunPython.noop)
    ]
