# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-11-24 02:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from pyexcel_xls import get_data

from juloserver.julo.models import Mantri


from juloserver.julo.models import StatusLookup


def db_insert_ecode_validation_statuses(apps, schema_editor):
    
    StatusLookup.objects.get_or_create(status_code=176,
                                       status='KYC in progress')


from juloserver.julo.models import Mantri


from juloserver.julo.models import StatusLookup


def load_code_mantri(apps, schema_editor):
    
    list_data = get_data("static/excel/mantri_code.xls")
    for data in list_data['Sheet1']:                           
        Mantri.objects.create(code=data[0])

        
class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(db_insert_ecode_validation_statuses, migrations.RunPython.noop),
        migrations.RunPython(load_code_mantri, migrations.RunPython.noop)
    ]
