# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-03-08 06:47
from __future__ import unicode_literals
from django.db import migrations
from juloserver.loan_refinancing.management.commands import retroload_refinancing_reason


def refinancing_new_reason_retroload(apps, schema_editor):
    retroload_refinancing_reason.Command().handle()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(refinancing_new_reason_retroload)
    ]
