# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-04-13 12:52
from __future__ import unicode_literals

from django.db import migrations, models


from juloserver.julo.models import VoiceRecord



from juloserver.julo.models import Image



def retroload_service_field(apps, schema_editor):
    """
    Populate the service field for existing images and voice recordings to
    S3 as the old cloud storage.
    """
    
    Image.objects.all().update(service='s3')

    
    VoiceRecord.objects.all().update(service='s3')


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            retroload_service_field, migrations.RunPython.noop),
    ]
