# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-21 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from juloserver.julo.partners import PartnerConstant


from juloserver.julo.models import PartnerAccountAttributionSetting



from juloserver.julo.models import Partner



def load_parnter_account_attribution_setting(apps, schema_editor):
    
    

    partner_tokopedia = Partner.objects.filter(name=PartnerConstant.TOKOPEDIA_PARTNER).last()
    partner_doku = Partner.objects.filter(name=PartnerConstant.DOKU_PARTNER).last()
    partner_grab = Partner.objects.filter(name=PartnerConstant.GRAB_PARTNER).last()
    partner_grab_food = Partner.objects.filter(name=PartnerConstant.GRAB_FOOD_PARTNER).last()

    if partner_tokopedia:
        PartnerAccountAttributionSetting.objects.create(
            partner=partner_tokopedia, is_uniqe=True, is_blank=False)
    if partner_doku:
        PartnerAccountAttributionSetting.objects.create(
            partner=partner_doku, is_uniqe=False, is_blank=False)
    if partner_grab:
        PartnerAccountAttributionSetting.objects.create(
            partner=partner_grab, is_uniqe=False, is_blank=True)
    if partner_grab_food:
        PartnerAccountAttributionSetting.objects.create(
            partner=partner_grab_food, is_uniqe=False, is_blank=True)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(load_parnter_account_attribution_setting, migrations.RunPython.noop)
    ]
