# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-15 11:43
from __future__ import unicode_literals
from __future__ import print_function

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from juloserver.apiv1.serializers import ApplicationOriginalSerializer
from django.forms.models import model_to_dict


from juloserver.julo.models import Application



def backup_applications(apps, shema_editor):
    
    for application in Application.objects.all():
        data = model_to_dict(application)
        serializer = ApplicationOriginalSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
        else:
            print("Application {} backup failed ".format(application.id), serializer.errors)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(backup_applications, migrations.RunPython.noop)
    ]
