# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-04-23 05:01
from __future__ import unicode_literals

from django.db import migrations,models
import django.db.models.deletion


from juloserver.julo.models import ExperimentSetting



def add_experiment_setting(apps, schema_editor):
    
    ExperimentSetting.objects.get_or_create(is_active=True,
        code="CootekBLPaylater",
        name="Cootek For Bukalapak Pay Later",
        start_date="2020-04-27 00:00:00+00",
        end_date="2021-04-27 00:00:00+00",
        schedule="",
        action="",
        type="payment",
        criteria={})


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_experiment_setting,
                             migrations.RunPython.noop)
    ]
