# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-02-26 08:38
from __future__ import unicode_literals
from django.db import migrations, models
from juloserver.julo.statuses import ApplicationStatusCodes
from juloserver.julo.management.commands import load_workflow, update_status_lookups, load_status_change_reasons


from juloserver.julo.models import WorkflowStatusPath, Workflow



def create_new_status_path_for_150(apps, schema_editor):
    opts = {'workflow_name': ('cash_loan',)}
    load_workflow.Command().handle(**opts)
    update_status_lookups.Command().handle()
    load_status_change_reasons.Command().handle()

def delete_status_path_160_obsolete(apps, schema_editor):
    
    cash_loan_workflow =Workflow.objects.get(name='CashLoanWorkflow')
    deleted_status = [
        ApplicationStatusCodes.OFFER_ACCEPTED_BY_CUSTOMER,
        ApplicationStatusCodes.APPLICATION_RESUBMITTED,
        ApplicationStatusCodes.ACTIVATION_CALL_FAILED,
        ApplicationStatusCodes.NAME_VALIDATE_FAILED,
        ApplicationStatusCodes.LEGAL_AGREEMENT_SIGNED_AND_DP_PENDING
    ]
    for deleted in deleted_status:
        path = WorkflowStatusPath.objects.filter(
            status_previous=deleted,
            status_next=ApplicationStatusCodes.ACTIVATION_CALL_SUCCESSFUL,
            workflow=cash_loan_workflow
        ).last()
        if path:
            path.delete()

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_new_status_path_for_150),
        migrations.RunPython(delete_status_path_160_obsolete),
    ]
