# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-03-13 04:04
from __future__ import unicode_literals

import itertools

from django.db import transaction

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import juloserver.julo.models


from juloserver.julo.models import ITIConfiguration



def retro_iti_configuration(apps, _schema_editor):
    """remove old credit matrix data and replace with new one"""
    
    premium_area = [True, False]
    salaried = [True, False]
    category = ['julo', 'webapp', 'julo_repeat']
    iti_version = 9
    min_income = 0
    max_income = 10**7
    min_threshold = 0.8
    max_threshold = 0.9
    iti_data = []

    for is_premium_area, is_salaried, customer_category in \
    itertools.product(premium_area, salaried, category):
        iti_data.append(ITIConfiguration(
            is_premium_area=is_premium_area,
            is_salaried=is_salaried,
            customer_category=customer_category,
            iti_version=iti_version,
            min_income=min_income,
            max_income=max_income,
            min_threshold=min_threshold,
            max_threshold=max_threshold,
            is_active=True
        ))

    with transaction.atomic():
        ITIConfiguration.objects.all().delete()
        ITIConfiguration.objects.bulk_create(iti_data)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(retro_iti_configuration, migrations.RunPython.noop),
    ]
