# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-04-06 13:53
from __future__ import unicode_literals

from django.db import migrations, models


from juloserver.julo.models import ProductProfile



from juloserver.julo.models import ProductLookup



from juloserver.julo.models import ProductLine



def load_false_reject_data_product_lookup(apps, schema_editor):
    
    
    

    product_list = [10,11] 
    
    # product lookup
    for product in product_list:
        product_profile = ProductProfile.objects.get(code=product)
        product_line = ProductLine.objects.get(product_line_code=product)
        ProductLookup.objects.create(
            product_name="I.840-O.050-L.050-C1.010-C2.010-M",
            interest_rate=0.84,
            origination_fee_pct=0.05,
            late_fee_pct=0.05,
            cashback_initial_pct=0,
            cashback_payment_pct=0.01,
            product_line=product_line,
            product_profile=product_profile
        )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(load_false_reject_data_product_lookup, migrations.RunPython.noop),
    ]
