# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-06-21 09:52
from __future__ import unicode_literals

from django.db import migrations


from juloserver.julo.models import StatusLookup



def add_status_165_handler(apps, schema_editor):
    
    status_lookup = StatusLookup.objects.get(status_code=165)
    status_lookup.handler = 'Status165Handler'
    status_lookup.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    	migrations.RunPython(add_status_165_handler)
    ]
