# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-29 06:11
from __future__ import unicode_literals

import logging

from django.contrib.auth.models import Group
from django.contrib.auth.models import Permission
from django.core import exceptions
from django.db import migrations


logger = logging.getLogger(__name__)


def add_permission_to_document_verifier(apps, schema_editor):

    group, _ = Group.objects.get_or_create(name='document_verifier')
    codename = 'change_applicationnote'
    try:
        permission = Permission.objects.get(codename=codename)
        group.permissions.add(permission)
    except exceptions.ObjectDoesNotExist:
        # This condition needs to be caught for running unit tests
        logger.warn({
            'permission_codename': codename,
            'status': 'does_not_exist'
        })


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_permission_to_document_verifier),
    ]
