# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-08-21 09:29
from __future__ import unicode_literals

from django.db import migrations, models
from juloserver.julo.statuses import ApplicationStatusCodes


from juloserver.julo.models import StatusLookup



def load_new_status_lookups(apps, schema_editor):
    
    StatusLookup.objects.create(status_code=ApplicationStatusCodes.APPLICANT_CALLS_ONGOING, status="Applicant calls ongoing")


class Migration(migrations.Migration):
     dependencies = [
    ]
     operations = [
        migrations.RunPython(load_new_status_lookups, migrations.RunPython.noop),
    ]
