# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-12-05 00:22
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from juloserver.julo.models import PartnerOriginationData


class Migration(migrations.Migration):




    def partner_origination_data(apps, _schema_editor):
        PartnerOriginationData.objects.create(id=0,
                                      distributor_name='Prima',
                                      origination_fee=0.015)
        PartnerOriginationData.objects.create(id=9,
                                      distributor_name='Dawang',
                                      origination_fee=0.01)
        PartnerOriginationData.objects.create(id=12,
                                      distributor_name='Dawang(1 bio)',
                                      origination_fee=0.01)
        PartnerOriginationData.objects.create(id=13,
                                      distributor_name='Tristar',
                                      origination_fee=0.01)
        PartnerOriginationData.objects.create(id=14,
                                      distributor_name='Boost',
                                      origination_fee=0.01)

    dependencies = [
    ]

    operations = [
        migrations.RunPython(partner_origination_data, migrations.RunPython.noop)
    ]
