# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-04-08 05:02
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def add_disbursement_auto_retry_fdc_feature_settings(apps, schema_editor):
    FeatureSetting.objects.get_or_create(
        is_active=True,
        feature_name=FeatureNameConst.RETRY_FDC_INQUIRY,
        category="fdc",
        parameters={
            "max_retries": 15,
            "inquiry_reason": "1 - Applying loan via Platform",
            "retry_interval_minutes": 5
        },
        description="Configure in ( x ) minute FDC inquiry task should retry")


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_disbursement_auto_retry_fdc_feature_settings,
                             migrations.RunPython.noop)
    ]
