# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-02-16 15:52
from __future__ import unicode_literals

from django.db import migrations

from juloserver.streamlined_communication.models import StreamlinedCommunication


from juloserver.streamlined_communication.models import StreamlinedMessage


def update_message_for_notify_va_bl(apps, schema_editor):
    
    

    bl_streamlined_communication = StreamlinedCommunication.objects.get(
        template_code='sms_bukalapak_notify_va_created'
    )
    bl_sms_content = StreamlinedMessage.objects.get(pk=bl_streamlined_communication.message_id)

    message_content = "Hi {{first_name}}, VA bayar Bukalapak BayarNanti Anda (013) {{virtual_account}},\
                            Total tagihan {{due_amount}}, Tertunggak {{dpd}} hari. Info (021)39509957."
    parameter = "{first_name,virtual_account, due_amount, dpd}"

    bl_sms_content.message_content = message_content
    bl_sms_content.parameter = parameter
    bl_sms_content.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(update_message_for_notify_va_bl,
                             migrations.RunPython.noop)
    ]
