# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-04-06 13:53
from __future__ import unicode_literals

from django.db import migrations, models
from juloserver.portal.object.product_profile.services import generate_product_lookup


ICARE_PRODUCT = [{
    'code': 92,
    'name': 'ICARE1',
    'min_amount': 2000000,
    'max_amount': 8000000,
    'min_duration': 3,
    'max_duration': 6,
    'min_interest_rate': 0.30,
    'max_interest_rate': 0.30,
    'interest_rate_increment': 0.0,
    'min_origination_fee': 0.00,
    'max_origination_fee': 0.00,
    'origination_fee_increment': 0.00,
    'cashback_initial': 0.00,
    'cashback_payment': 0.00,
    'late_fee': 0.00,
    'payment_frequency': 'Monthly',
    'debt_income_ratio': None,
    'is_initial': True,
    'is_active': True
}, {
    'code': 93,
    'name': 'ICARE2',
    'min_amount': 2000000,
    'max_amount': 8000000,
    'min_duration': 3,
    'max_duration': 6,
    'min_interest_rate': 0.30,
    'max_interest_rate': 0.30,
    'interest_rate_increment': 0.0,
    'min_origination_fee': 0.00,
    'max_origination_fee': 0.00,
    'origination_fee_increment': 0.00,
    'cashback_initial': 0.00,
    'cashback_payment': 0.00,
    'late_fee': 0.00,
    'payment_frequency': 'Monthly',
    'debt_income_ratio': None,
    'is_initial': True,
    'is_active': True
}]

ICARE_CUSTOMER = {
     'credit_score': ['A-', 'B+', 'B-']
}


from juloserver.julo.models import Workflow



from juloserver.julo.models import ProductCustomerCriteria



from juloserver.julo.models import ProductProfile



from juloserver.julo.models import ProductLookup



from juloserver.julo.models import ProductLine



def load_loc_product(apps, schema_editor):
    
    
    
    
    
    try:
        workflow = Workflow.objects.get(name='PartnerWorkflow')
    except:
        workflow = None

    for product in ICARE_PRODUCT:
        product_profile = ProductProfile(**product)
        product_profile.save()

        # ICARE customer criteria
        ICARE_CUSTOMER['product_profile'] = product_profile
        product_customer_criteria = ProductCustomerCriteria(**ICARE_CUSTOMER)
        product_customer_criteria.save()

        # ICARE product_line
        product_line = ProductLine.objects.create(
            product_line_code=product_profile.code,
            product_line_type=product_profile.name,
            min_amount=product_profile.min_amount,
            max_amount=product_profile.max_amount,
            min_duration=product_profile.min_duration,
            max_duration=product_profile.max_duration,
            min_interest_rate=product_profile.min_interest_rate,
            max_interest_rate=product_profile.max_interest_rate,
            payment_frequency=product_profile.payment_frequency,
            product_profile=product_profile,
            default_workflow=workflow
        )

        # product lookup
        product_lookup_list = generate_product_lookup(product_profile, product_line)
        for product_lookup_data in product_lookup_list:
            product_lookup = ProductLookup(**product_lookup_data)
            product_lookup.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(load_loc_product, migrations.RunPython.noop),
    ]

