# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-14 08:27
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.statuses import PaymentStatusCodes
from juloserver.julo.statuses import StatusManager

import datetime


from juloserver.julo.models import StatusLookup



def create_new_status_lookups(apps, schema_editor):

    new_statuses = [
        PaymentStatusCodes.PAID_REFUND,
    ]

    
    for new_status in new_statuses:
        status = StatusManager.get_or_none(new_status)
        StatusLookup.objects.get_or_create(status_code=status.code, status=status.desc)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_new_status_lookups)
    ]
