# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-04-03 08:45
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import juloserver.julo.models

from juloserver.julo.models import MobileFeatureSetting


def create_mock_rating_page_c_customer(apps, schema_editor):
    
    setting = MobileFeatureSetting(
        feature_name="mock_rating_page",
        parameters={
            'description': "Config which JULO customer will get mock rating page on x105",
            'score_tags': [
                'c_failed_binary', 'c_low_credit_score', 'C low', 'c_failed_binary', 'c_failed_blacklist_check',
                'C high', None
            ]
        },
    )
    setting.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_mock_rating_page_c_customer),
    ]
