# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-12-06 03:33
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.constants import FeatureNameConst


from juloserver.julo.models import FeatureSetting



def add_autodialersessiondelay_settings(apps, schema_editor):
    
    FeatureSetting.objects.get_or_create(is_active=True,
                                         feature_name=FeatureNameConst.DISBURSEMENT_TRAFFIC,
                                         category="traffic_ratio",
                                         parameters={
                                            'xendit': 0,
                                            'xfers': 1,
                                         },
                                         description="set disbursement vendor traffic"
                                        )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_autodialersessiondelay_settings, migrations.RunPython.noop)
    ]
