# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-09-19 06:27
from __future__ import unicode_literals

from django.db import migrations


from juloserver.julo.models import FaqItem



def delete_julo_mini (apps, schema_editor):
    
    julomini_question = FaqItem.objects.filter(question='Apakah pinjaman JULO Mini itu?').last()
    julomini_product_question = FaqItem.objects.filter(question = 'Apakah pinjaman JULO itu?').last()

    if julomini_question is not None:
        julomini_question.visible=False
        julomini_question.save()
    if julomini_product_question is not None:
        description = 'Pinjaman JULO adalah Kredit Tanpa Agunan (KTA) yang ditawarkan secara ekslusif' \
                      ' kepada pengguna smartphone Android di Indonesia, dengan fitur proses pengajuan mudah,' \
                      ' bunga rendah dan cashback yang bisa dicairkan saat pinjaman telah terbayar lunas.<br><table>' \
                      ' <tr><td><b>JULO Cicil</b></td></tr><tr><td>Pinjaman KTA antara Rp 2 - 8 juta, dengan jangka waktu 3 - 6 bulan, ' \
                      'bunga 1.5% - 4% per bulan dan cashback (uang kembali) sebesar 2%!</td></tr></table>'
        julomini_product_question.description=description
        julomini_product_question.save()


class Migration(migrations.Migration):


    dependencies = [
    ]

    operations = [
        migrations.RunPython(delete_julo_mini),
    ]
