# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-10 07:14
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.product_lines import ProductLineCodes


from juloserver.julo.models import ProductLookup



from juloserver.julo.models import ProductLine



def load_product_lookup_stl(apps, schema_editor):

    
    product_line_stl1 = ProductLine.objects.get(
        product_line_code=ProductLineCodes.STL1)
    product_line_stl2 = ProductLine.objects.get(
        product_line_code=ProductLineCodes.STL2)

    product_lookups = [
        (12, 'I1.200-O.050-L.050-C1.010-C2.010-M',
         1.20, 0.050, 0.050, 0.010, 0.010, True, product_line_stl1),
        (13, 'I1.200-O.050-L.050-C1.010-C2.010-M',
         1.20, 0.050, 0.050, 0.010, 0.010, True, product_line_stl2),
    ]
    
    for pl in product_lookups:
        kwargs = {
            'product_code': pl[0],
            'product_name': pl[1],
            'interest_rate': pl[2],
            'origination_fee_pct': pl[3],
            'late_fee_pct': pl[4],
            'cashback_initial_pct': pl[5],
            'cashback_payment_pct': pl[6],
            'is_active': pl[7],
            'product_line': pl[8]
        }
        product_lookup = ProductLookup(**kwargs)
        product_lookup.save()

    # Create product look ups for MTL2 by copying them from MTL1

    current_count = ProductLookup.objects.all().count()
    product_lookups = ProductLookup.objects.filter(
        product_line=ProductLineCodes.MTL1)
    product_code = current_count + 1
    for pl in product_lookups:
        pl.product_code = product_code
        pl.product_line = ProductLine.objects.get(product_line_code=ProductLineCodes.MTL2)
        pl.save()
        product_code += 1


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(load_product_lookup_stl),
    ]
