# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-12-06 03:33
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.constants import FeatureNameConst


from juloserver.julo.models import FeatureSetting



def update_autodialersessiondelay_settings(apps, schema_editor):
    
    feature = FeatureSetting.objects.get(is_active=True,
                                         feature_name=FeatureNameConst.AUTODIALER_SESSION_DELAY,
                                         category="autodialer"
                                        )
    feature.parameters={122: 3,
                        124: 1,
                        138: 3,
                        140: 1,
                        141: 1,
                        160: 1,
                        180: None,
                        'fu': 12,
                        'colT0': 5,
                        172: 1}
    feature.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(update_autodialersessiondelay_settings, migrations.RunPython.noop)
    ]
