# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-13 18:25
from __future__ import unicode_literals

import logging

from django.db import migrations


logger = logging.getLogger(__name__)


from juloserver.julo.models import PaymentEvent



def fix_late_fee_event_due_amount(apps, schema_editor):
    
    for pe in PaymentEvent.objects.filter(event_type='late_fee'):
        wrong_due_amount = pe.event_due_amount
        due_amount_before = wrong_due_amount + pe.event_payment
        pe.event_due_amount = due_amount_before
        logger.info({
            'payment_event': pe.id,
            'wrong_due_amount': wrong_due_amount,
            'due_amount_before': due_amount_before,
            'status': 'fixing'
        })
        pe.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(fix_late_fee_event_due_amount, migrations.RunPython.noop),
    ]
