# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-02-20 09:30
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import juloserver.julo.models
from juloserver.julo.management.commands import load_workflow, update_status_lookups, load_status_change_reasons

# add workflow status path 131 to 121,122,124,141
def update_workflow_path_131(apps, schema_editor):
    opts = {'workflow_name': ('cash_loan',)}
    load_workflow.Command().handle(**opts)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(update_workflow_path_131)
    ]
