# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-03-06 07:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import juloserver.julo.models

from juloserver.julo.models import MobileFeatureSetting


def create_digisign_mode_mobile_setting(apps, schema_editor):
    
    setting = MobileFeatureSetting(
        feature_name="digisign_mode",
        parameters={},
    )
    setting.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_digisign_mode_mobile_setting),
    ]
