# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-12 07:52
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.payment_methods import PaymentMethods


from juloserver.julo.models import PaymentMethodLookup



def update_payment_method(apps, schema_editor):
    payment_methods = PaymentMethods

    

    for pm in payment_methods:
        payment_method_lookup = PaymentMethodLookup.objects.get(code=pm.code)
        payment_method_lookup.name = pm.name
        payment_method_lookup.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(update_payment_method)
    ]
