# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-21 06:57
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import migrations


def create_default_superuser(apps, schema_editor):
    User.objects.create_superuser('admin', 'admin@example.com', 'changeme')


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_default_superuser),
    ]
