# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-04-06 13:53
from __future__ import unicode_literals

from django.db import migrations


from juloserver.julo.models import WorkflowStatusPath



from juloserver.julo.models import Workflow



def icare_new_status_path(apps, schema_editor):
    
    workflow = Workflow.objects.filter(name="PartnerWorkflow").first()
    if workflow:
        
        DATA = [{"status_previous": 178, "status_next": 180}]
        for path in DATA:
            WorkflowStatusPath.objects.get_or_create(
                status_previous=path['status_previous'],
                status_next=path['status_next'],
                type="happy",
                workflow=workflow
            )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(icare_new_status_path, migrations.RunPython.noop),
    ]
