# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-12-16 00:49
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import juloserver.julo.models
from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting

class Migration(migrations.Migration):


    def add_axiata_multiple_loan_settings(apps, schema_editor):
        
        FeatureSetting.objects.get_or_create(is_active=True,
                                             feature_name=FeatureNameConst.AXIATA_MULTIPLE_LOAN,
                                             category="multiple_loan",
                                             description="axiata mutiple loan config setting"
                                             )

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_axiata_multiple_loan_settings, migrations.RunPython.noop)
    ]
