# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-01-27 04:38
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import juloserver.julo.models
from juloserver.julo.management.commands import load_workflow, update_status_lookups, load_status_change_reasons


class Migration(migrations.Migration):

    def create_new_workflow_path_160_to_150(apps, schema_editor):
        opts = {'workflow_name': ('cash_loan',)}
        load_workflow.Command().handle(**opts)
        update_status_lookups.Command().handle()
        load_status_change_reasons.Command().handle()

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_new_workflow_path_160_to_150)
    ]
