# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-11-15 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from juloserver.julo.payment_methods import PaymentMethodCodes

from juloserver.julo.models import PaymentMethod


def update_paymentmethod_exist(apps, schema_editor):
    
    list_data = PaymentMethod.objects.all()
    for data in list_data:
        if data.payment_method_code == PaymentMethodCodes.INDOMARET:
            data.is_shown = False
        else:
            data.is_shown = True
        data.save()

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(update_paymentmethod_exist),
    ]
