# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-06-11 02:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from juloserver.julo.management.commands import retroload_early_payback_offer_data


def early_payback_offer_retroload(apps, schema_editor):
    retroload_early_payback_offer_data.Command().handle()


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE early_payback_offer ALTER COLUMN loan_id TYPE bigint;"),
        migrations.RunSQL(
            "ALTER TABLE early_payback_offer ALTER COLUMN application_id TYPE bigint;"),
        migrations.RunSQL(
            "ALTER TABLE fdc_risky_history ALTER COLUMN application_id TYPE bigint;"),
        migrations.RunSQL(
            "ALTER TABLE fdc_risky_history ALTER COLUMN loan_id TYPE bigint;"),
        migrations.RunPython(early_payback_offer_retroload),

    ]
