# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-06-03 09:50
from __future__ import unicode_literals

from django.db import migrations
from juloserver.loan_refinancing.management.commands import retroload_recommendation_order


def recommnedation_order_retroload(apps, schema_editor):
    retroload_recommendation_order.Command().handle()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(recommnedation_order_retroload),
    ]
