# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-09-23 12:07
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting, AccountingCutOffDate
from juloserver.julo.constants import FeatureNameConst
from datetime import datetime, timedelta


def add_accounting_date_feature(apps, schema_editor):
    FeatureSetting.objects.get_or_create(is_active=True,
                                         feature_name=FeatureNameConst.ACCOUNTING_CUT_OFF_DATE,
                                         parameters={
                                             'cut_off_date': 8,
                                         },
                                         category='accounting',
                                         description="accounting_cut_off_date_feature"
                                         )


def retroload_accounting_date_data(apps, schema_editor):
    retro_date = datetime(2020, 9, 1, 0, 0)
    accounting_period = (retro_date - timedelta(days=1)).replace(day=1).date()
    cut_off_date = retro_date.replace(day=8).date()
    AccountingCutOffDate.objects.create(
        accounting_period=accounting_period,
        cut_off_date=cut_off_date,
        cut_off_date_last_change_ts=datetime.now()
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_accounting_date_feature, migrations.RunPython.noop),
        migrations.RunPython(retroload_accounting_date_data, migrations.RunPython.noop)
    ]
