# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-09-17 06:05
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import GlobalPaymentMethod, MobileFeatureSetting


def db_insert_payment_method_view(apps, schema_editor):
    payment_method_views = [
        {
            'feature_name': 'BCA',
            'payment_method_code': '014',
            'impacted_type': 'Backup'
        },
        {
            'feature_name': 'Permata',
            'payment_method_code': '013',
            'impacted_type': 'Backup'
        },
        {
            'feature_name': 'BRI',
            'payment_method_code': '002',
            'impacted_type': 'Backup'
        },
        {
            'feature_name': 'Maybank',
            'payment_method_code': '016',
            'impacted_type': 'Backup'
        },
        {
            'feature_name': 'Gopay',
            'payment_method_code': '1002',
        },
        {
            'feature_name': 'Alfamart',
            'payment_method_code': '319322'
        },
        {
            'feature_name': 'Indomaret',
            'payment_method_code': '319237'
        },
    ]
    for payment_method_view in payment_method_views:
        GlobalPaymentMethod.objects.get_or_create(**payment_method_view)


def db_deprecate_payment_method_mobile_feature_setting(apps, schema_editor):
    MobileFeatureSetting.objects.filter(
        feature_name__in=['gopay', 'indomaret', 'alfamart']).delete()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(db_deprecate_payment_method_mobile_feature_setting,
                             migrations.RunPython.noop),
        migrations.RunPython(db_insert_payment_method_view, migrations.RunPython.noop)
    ]
