# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-10-05 00:24
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import Workflow, WorkflowStatusPath, WorkflowStatusNode, ChangeReason


def add_workflow_julo_one(apps, _schema_editor):

    workflow = Workflow.objects.get(
        name="JuloOneWorkflow"
    )
    # WorkflowStatusPath
    WorkflowStatusPath.objects.get_or_create(
        status_previous=124,
        status_next=130,
        type="happy",
        workflow=workflow
    )
    WorkflowStatusPath.objects.get_or_create(
        status_previous=124,
        status_next=175,
        type="unhappy",
        workflow=workflow
    )
    WorkflowStatusPath.objects.get_or_create(
        status_previous=130,
        status_next=141,
        type="happy",
        workflow=workflow
    )
    WorkflowStatusPath.objects.get_or_create(
        status_previous=130,
        status_next=142,
        type="unhappy",
        workflow=workflow
    )
    WorkflowStatusPath.objects.get_or_create(
        status_previous=141,
        status_next=150,
        type="happy",
        workflow=workflow
    )
    WorkflowStatusPath.objects.get_or_create(
        status_previous=142,
        status_next=135,
        type="unhappy",
        workflow=workflow
    )
    WorkflowStatusPath.objects.get_or_create(
        status_previous=150,
        status_next=190,
        type="happy",
        workflow=workflow
    )
    WorkflowStatusPath.objects.get_or_create(
        status_previous=150,
        status_next=145,
        type="unhappy",
        workflow=workflow
    )
    WorkflowStatusPath.objects.get_or_create(
        status_previous=145,
        status_next=150,
        type="detour",
        workflow=workflow
    )
    WorkflowStatusPath.objects.get_or_create(
        status_previous=145,
        status_next=135,
        type="unhappy",
        workflow=workflow
    )
    WorkflowStatusPath.objects.get_or_create(
        status_previous=145,
        status_next=137,
        type="unhappy",
        workflow=workflow
    )
    # WorkflowStatusNode
    WorkflowStatusNode.objects.create(
        status_node=124,
        handler='JuloOne124Handler',
        workflow=workflow
    )
    WorkflowStatusNode.objects.create(
        status_node=150,
        handler='JuloOne150Handler',
        workflow=workflow
    )
    WorkflowStatusNode.objects.create(
        status_node=190,
        handler='JuloOne190Handler',
        workflow=workflow
    )


def add_reason_julo_one(apps, _schema_editor):
    ChangeReason.objects.get_or_create(
        reason='Failed credit limit generation',
        status_id=135
    )
    ChangeReason.objects.get_or_create(
        reason='Credit limit generated',
        status_id=141
    )
    ChangeReason.objects.get_or_create(
        reason='Credit limit generation failed',
        status_id=142
    )
    ChangeReason.objects.get_or_create(
        reason='IPV verified',
        status_id=150
    )
    ChangeReason.objects.get_or_create(
        reason='Credit limit activated',
        status_id=190
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_workflow_julo_one, migrations.RunPython.noop),
        migrations.RunPython(add_reason_julo_one, migrations.RunPython.noop)
    ]
