# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-10-14 09:44
from __future__ import unicode_literals
from juloserver.julo.models import Workflow, WorkflowStatusPath
from django.db import migrations


def pede_new_status_path_failure_registration(apps, _schema_editor):
    workflow = Workflow.objects.filter(name="PartnerWorkflow").first()
    if workflow:
        input_data = [{"status_previous": 160, "status_next": 135}]
        for path in input_data:
            WorkflowStatusPath.objects.get_or_create(
                status_previous=path['status_previous'],
                status_next=path['status_next'],
                type="graveyard",
                workflow=workflow
            )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(pede_new_status_path_failure_registration, migrations.RunPython.noop),
    ]
