# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-10-12 08:29
from __future__ import unicode_literals

from django.db import migrations

from juloserver.collection_vendor.models import SubBucket


def change_bucket_definition(apps, schema_editor):
    bucket_5 = SubBucket.objects.get(bucket=5, sub_bucket=1)
    bucket_5.update_safely(
        sub_bucket=None
    )
    bucket_5_2 = SubBucket.objects.get(bucket=5, sub_bucket=2)
    bucket_5_2.update_safely(
        bucket=6,
        sub_bucket=1,
    )
    bucket_5_3 = SubBucket.objects.get(bucket=5, sub_bucket=3)
    bucket_5_3.update_safely(
        bucket=6,
        sub_bucket=2,
    )
    bucket_5_4 = SubBucket.objects.get(bucket=5, sub_bucket=4)
    bucket_5_4.update_safely(
        bucket=6,
        sub_bucket=3,
    )
    bucket_5_5 = SubBucket.objects.get(bucket=5, sub_bucket=5)
    bucket_5_5.update_safely(
        bucket=6,
        sub_bucket=4,
    )

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(change_bucket_definition, migrations.RunPython.noop),
    ]
