# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-10-22 04:37
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import StatusLookup


def load_new_status_lookups(apps, schema_editor):
    status_lookups = [

        # Application status

        (217, 'Legal agreement expired'),
        (216, 'Loan canceled by customer'),

    ]

    for status_code, status in status_lookups:
        status_lookup = StatusLookup.objects.filter(status_code=status_code).first()
        if not status_lookup:
            StatusLookup.objects.create(status_code=status_code, status=status)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(load_new_status_lookups, migrations.RunPython.noop),
    ]
