# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-10-27 09:23
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import WorkflowStatusPath, Workflow

def add_pede_partner_workflow_status_paths(apps, schema_editor):

    partner_workflow = Workflow.objects.get(name="PartnerWorkflow")
    workflows = [(122, 124), (124, 130), (130, 172)]

    for w in workflows: 
        WorkflowStatusPath.objects.get_or_create(
            status_previous=w[0],
            status_next=w[1],
            type="happy",
            workflow=partner_workflow)
    
    WorkflowStatusPath.objects.get_or_create(
        status_previous=160,
        status_next=135,
        type="graveyard",
        workflow=partner_workflow)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_pede_partner_workflow_status_paths, migrations.RunPython.noop),
    ]
