# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-10-27 05:01
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import MobileFeatureSetting


def update_feature(apps, schema_editor):
    # add new feature settings
    MobileFeatureSetting.objects.create(
        feature_name="concurrency_message",
        is_active=True,
        parameters=dict(
            title="Halo",
            content=("Untuk sementara Anda hanya bisa "\
                "memiliki 1 (satu) pinjaman aktif.\r\n\r\nSegera selesaikan "\
                "pinjaman Anda agar dapat transaksi kembali menggunakan limit."),
        )
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(update_feature, migrations.RunPython.noop),
    ]
