# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-11-04 23:04
from __future__ import unicode_literals

from builtins import str
from builtins import object
from django.db import migrations
from juloserver.julo.statuses import ApplicationStatusCodes, LoanStatusCodes
from juloserver.julo.utils import upload_file_to_oss
from juloserver.streamlined_communication.models import (InfoCardButtonProperty,
                                                         CardProperty,
                                                         InfoCardProperty,
                                                         StreamlinedMessage,
                                                         StreamlinedCommunication)
from juloserver.streamlined_communication.constant import CommunicationPlatform
from juloserver.julo.models import StatusLookup, Image
from juloserver.streamlined_communication.models import StreamlinedCommunicationParameterList
from juloserver.streamlined_communication.services import create_and_upload_image_assets_for_streamlined
from django.conf import settings

L_BUTTON = 'L.BUTTON'
R_BUTTON = 'R.BUTTON'
M_BUTTON = 'M.BUTTON'


class ImageNames(object):
    DESIGNS_REAL_BLUE = 'info-card/designs_real_blue.png'
    DESIGNS_REAL_ORANGE = 'info-card/designs_real_org.png'
    DESIGNS_REAL_RED = 'info-card/designs_real_red.png'
    EXCLAMATION_IMAGE_BLUE = 'info-card/group_3500_blue.png'
    EXCLAMATION_IMAGE_ORANGE = 'info-card/group_3500_org.png'
    EXCLAMATION_IMAGE_RED = 'info-card/group_3500_red.png'
    BUTTON_BACKGROUND_BLUE = 'info-card/rectangle_1489_blue.png'
    BUTTON_BACKGROUND_ORANGE = 'info-card/rectangle_1489_org.png'
    BUTTON_BACKGROUND_RED = 'info-card/rectangle_1489_red.png'
    BUTTON_BACKGROUND_RED_2 = 'info-card/rectangle_1489_2_red.png'


def create_image(image_source_id, image_type, image_url):
    image = Image()
    image.image_source = image_source_id
    image.image_type = image_type
    image.url = image_url
    image.save()


def retroload_cards_data_julo_one(_apps, _schema_editor):
    data_to_be_loaded = [
        {
            'status': None,
            'additional_condition': None,
            'title': 'Informasi Pinjaman',
            'content': 'Hi {{card_first_name}}, Angsuran {{card_due_amount}} '
                       'Anda akan jatuh tempo dalam {{card_dpd}} hari. Bayar sekarang '
                       'dan dapatkan cashback sebesar {{card_cashback_multiplier}}!',
            'button': ['Bayar Sekarang'],
            'click_to': ['howtopay'],
            'template_code': 'card_t-2',
            'template_type': '3B',
            'card_number': 1,
            'text_colour': '#00acf0',
            'title_colour': '#00acf0',
            'button_text_color': ['#ffffff'],
            'button_name': [L_BUTTON],
            'background_url': ImageNames.DESIGNS_REAL_BLUE,
            'additional_images': [ImageNames.EXCLAMATION_IMAGE_BLUE],
            'button_background': [ImageNames.BUTTON_BACKGROUND_BLUE],
            'button_background_type': ['M'],
            'button_url': [],
            'dpd': -2,
            'dpd_lower': None,
            'dpd_upper': None,
            'parameters': '{card_first_name, card_due_amount, card_dpd, card_cashback_multiplier}',
            'until_paid': False
        },
        {
            'status': None,
            'additional_condition': None,
            'title': 'Informasi Pinjaman',
            'content': 'Hi {{card_first_name}}, angsuran {{card_due_amount}} '
                       'Anda akan jatuh tempo besok. Bayar angsuran Anda sekarang '
                       'dan dapatkan cashback sebesar {{card_cashback_multiplier}}!',
            'button': ['Bayar Sekarang'],
            'click_to': ['howtopay'],
            'template_code': 'card_t-1',
            'template_type': '3B',
            'card_number': 1,
            'text_colour': '#00acf0',
            'title_colour': '#00acf0',
            'button_text_color': ['#ffffff'],
            'button_name': [L_BUTTON],
            'background_url': ImageNames.DESIGNS_REAL_BLUE,
            'additional_images': [ImageNames.EXCLAMATION_IMAGE_BLUE],
            'button_background': [ImageNames.BUTTON_BACKGROUND_BLUE],
            'button_background_type': ['M'],
            'button_url': [],
            'dpd': -1,
            'dpd_lower': None,
            'dpd_upper': None,
            'parameters': '{card_first_name, card_due_amount, card_cashback_multiplier}',
            'until_paid': False
        },
        {
            'status': None,
            'additional_condition': None,
            'title': 'Informasi Pinjaman',
            'content': 'Hi {{card_first_name}}, angsuran {{card_due_amount}} '
                       'jatuh tempo hari ini. Bayar angsuran Anda sekarang dan '
                       'dapatkan cashback sebesar {{card_cashback_multiplier}}!',
            'button': ['Bayar Sekarang'],
            'click_to': ['howtopay'],
            'template_code': 'card_t0',
            'template_type': '3B',
            'card_number': 1,
            'text_colour': '#00acf0',
            'title_colour': '#00acf0',
            'button_text_color': ['#ffffff'],
            'button_name': [L_BUTTON],
            'background_url': ImageNames.DESIGNS_REAL_BLUE,
            'button_background': [ImageNames.BUTTON_BACKGROUND_BLUE],
            'button_background_type': ['M'],
            'additional_images': [ImageNames.EXCLAMATION_IMAGE_BLUE],
            'button_url': [],
            'dpd': 0,
            'dpd_lower': None,
            'dpd_upper': None,
            'parameters': '{card_first_name, card_due_amount, card_cashback_multiplier}',
            'until_paid': False
        },
        {
            'status': None,
            'additional_condition': None,
            'title': 'Informasi Pinjaman',
            'content': 'Yth. {{card_first_name}}, angsuran {{card_due_amount}} '
                       'yang jatuh tempo pada {{card_due_date}} sudah terlambat '
                       '{{card_dpd}} hari. Hindari denda, lakukan pembayaran sekarang.',
            'button': ['Bayar Sekarang'],
            'click_to': ['howtopay'],
            'template_code': 'card_t1',
            'template_type': '3B',
            'card_number': 1,
            'text_colour': '#f69539',
            'title_colour': '#f69539',
            'button_text_color': ['#ffffff'],
            'button_name': [L_BUTTON],
            'background_url': ImageNames.DESIGNS_REAL_ORANGE,
            'button_background': [ImageNames.BUTTON_BACKGROUND_ORANGE],
            'button_background_type': ['M'],
            'additional_images': [ImageNames.EXCLAMATION_IMAGE_ORANGE],
            'button_url': [],
            'dpd': 1,
            'dpd_lower': None,
            'dpd_upper': None,
            'parameters': '{card_first_name, card_due_amount, card_due_date, card_dpd}',
            'until_paid': False
        },
        {
            'status': None,
            'additional_condition': None,
            'title': 'Informasi Pinjaman',
            'content': 'Yth. {{card_first_name}}, angsuran {{card_due_amount}} '
                       'yang jatuh tempo pada {{card_due_date}} sudah terlambat '
                       '{{card_dpd}} hari. Hindari denda, lakukan pembayaran sekarang.',
            'button': ['Bayar Sekarang'],
            'click_to': ['howtopay'],
            'template_code': 'card_t2',
            'template_type': '3B',
            'card_number': 1,
            'text_colour': '#f69539',
            'title_colour': '#f69539',
            'button_text_color': ['#ffffff'],
            'button_name': [L_BUTTON],
            'background_url': ImageNames.DESIGNS_REAL_ORANGE,
            'button_background': [ImageNames.BUTTON_BACKGROUND_ORANGE],
            'button_background_type': ['M'],
            'additional_images': [ImageNames.EXCLAMATION_IMAGE_ORANGE],
            'button_url': [],
            'dpd': 2,
            'dpd_lower': None,
            'dpd_upper': None,
            'parameters': '{card_first_name, card_due_amount, card_due_date, card_dpd}',
            'until_paid': False
        },
        {
            'status': None,
            'additional_condition': None,
            'title': 'Informasi Pinjaman',
            'content': 'Yth. {{card_first_name}}, angsuran {{card_due_amount}} yang jatuh '
                       'tempo pada {{card_due_date}} sudah terlambat {{card_dpd}} hari. '
                       'Bayar sekarang agar skor kredit Anda tidak turun.',
            'button': ['Bayar Sekarang'],
            'click_to': ['howtopay'],
            'template_code': 'card_t3',
            'template_type': '3B',
            'card_number': 1,
            'text_colour': '#f69539',
            'title_colour': '#f69539',
            'button_text_color': ['#ffffff'],
            'button_name': [L_BUTTON],
            'background_url': ImageNames.DESIGNS_REAL_ORANGE,
            'button_background': [ImageNames.BUTTON_BACKGROUND_ORANGE],
            'button_background_type': ['M'],
            'additional_images': [ImageNames.EXCLAMATION_IMAGE_ORANGE],
            'button_url': [],
            'dpd': 3,
            'dpd_lower': None,
            'dpd_upper': None,
            'parameters': '{card_first_name, card_due_amount, card_due_date, card_dpd}',
            'until_paid': False
        },
        {
            'status': None,
            'additional_condition': None,
            'title': 'Informasi Pinjaman',
            'content': 'Yth. {{card_first_name}}, angsuran {{card_due_amount}} '
                       'yang jatuh tempo pada {{card_due_date}} sudah terlambat '
                       '{{card_dpd}} hari. Segera lunasi agar skor kredit tidak turun',
            'button': ['Bayar Sekarang'],
            'click_to': ['howtopay'],
            'template_code': 'card_t4',
            'template_type': '3B',
            'card_number': 1,
            'text_colour': '#f69539',
            'title_colour': '#f69539',
            'button_text_color': ['#ffffff'],
            'button_name': [L_BUTTON],
            'background_url': ImageNames.DESIGNS_REAL_ORANGE,
            'button_background': [ImageNames.BUTTON_BACKGROUND_ORANGE],
            'button_background_type': ['M'],
            'additional_images': [ImageNames.EXCLAMATION_IMAGE_ORANGE],
            'button_url': [],
            'dpd': 4,
            'dpd_lower': None,
            'dpd_upper': None,
            'parameters': '{card_first_name, card_due_amount, card_due_date, card_dpd}',
            'until_paid': False
        },
        {
            'status': None,
            'additional_condition': None,
            'title': 'Informasi Pinjaman',
            'content': 'Yth. {{card_first_name}}, angsuran {{card_due_amount}} '
                       'yang jatuh tempo pada {{card_due_date}} sudah terlambat '
                       '{{card_dpd}}. Lunasi sekarang untuk menjaga skor kredit Anda',
            'button': ['Bayar Sekarang'],
            'click_to': ['howtopay'],
            'template_code': 'card_t6',
            'template_type': '3B',
            'card_number': 1,
            'text_colour': '#f69539',
            'title_colour': '#f69539',
            'button_text_color': ['#ffffff'],
            'button_name': [L_BUTTON],
            'background_url': ImageNames.DESIGNS_REAL_ORANGE,
            'button_background': [ImageNames.BUTTON_BACKGROUND_ORANGE],
            'button_background_type': ['M'],
            'additional_images': [ImageNames.EXCLAMATION_IMAGE_ORANGE],
            'button_url': [],
            'dpd': 6,
            'dpd_lower': None,
            'dpd_upper': None,
            'parameters': '{card_first_name, card_due_amount, card_due_date, card_dpd}',
            'until_paid': False
        },
        {
            'status': None,
            'additional_condition': None,
            'title': 'Informasi Pinjaman',
            'content': 'Yth. {{card_first_name}}, angsuran {{card_due_amount}} '
                       'yang jatuh tempo pada {{card_due_date}} sudah terlambat '
                       '{{card_dpd}} hari. Harap hindari risiko beban terus bertambah.',
            'button': ['Bayar Sekarang'],
            'click_to': ['howtopay'],
            'template_code': 'card_t7',
            'template_type': '3B',
            'card_number': 1,
            'text_colour': '#f69539',
            'title_colour': '#f69539',
            'button_text_color': ['#ffffff'],
            'button_name': [L_BUTTON],
            'background_url': ImageNames.DESIGNS_REAL_ORANGE,
            'button_background': [ImageNames.BUTTON_BACKGROUND_ORANGE],
            'button_background_type': ['M'],
            'additional_images': [ImageNames.EXCLAMATION_IMAGE_ORANGE],
            'button_url': [],
            'dpd': 7,
            'dpd_lower': None,
            'dpd_upper': None,
            'parameters': '{card_first_name, card_due_amount, card_due_date, card_dpd}',
            'until_paid': False
        },
        {
            'status': None,
            'additional_condition': None,
            'title': 'Informasi Pinjaman',
            'content': 'Hi {{card_first_name}}, angsuran {{card_due_amount}} '
                       'jatuh tempo pada {{card_due_date}} dan sudah terlambat '
                       '{{card_dpd}} hari. Pertimbangkan beban akibat terlambat bayar',
            'button': ['Bayar Sekarang'],
            'click_to': ['howtopay'],
            'template_code': 'card_t8',
            'template_type': '3B',
            'card_number': 1,
            'text_colour': '#f69539',
            'title_colour': '#f69539',
            'button_text_color': ['#ffffff'],
            'button_name': [L_BUTTON],
            'background_url': ImageNames.DESIGNS_REAL_ORANGE,
            'button_background': [ImageNames.BUTTON_BACKGROUND_ORANGE],
            'button_background_type': ['M'],
            'additional_images': [ImageNames.EXCLAMATION_IMAGE_ORANGE],
            'button_url': [],
            'dpd': 8,
            'dpd_lower': None,
            'dpd_upper': None,
            'parameters': '{card_first_name, card_due_amount, card_due_date, card_dpd}',
            'until_paid': False
        },
        {
            'status': None,
            'additional_condition': None,
            'title': 'Informasi Pinjaman',
            'content': 'Angsuran {{card_due_amount}} Anda jatuh tempo pada {{card_due_date}} '
                       'dan sudah terlambat {{card_dpd}} hari. Lunasi sekarang agar '
                       'denda tidak terus bertambah. ',
            'button': ['Bayar Sekarang'],
            'click_to': ['howtopay'],
            'template_code': 'card_t9',
            'template_type': '3B',
            'card_number': 1,
            'text_colour': '#f69539',
            'title_colour': '#f69539',
            'button_text_color': ['#ffffff'],
            'button_name': [L_BUTTON],
            'background_url': ImageNames.DESIGNS_REAL_ORANGE,
            'button_background': [ImageNames.BUTTON_BACKGROUND_ORANGE],
            'button_background_type': ['M'],
            'additional_images': [ImageNames.EXCLAMATION_IMAGE_ORANGE],
            'button_url': [],
            'dpd': 9,
            'dpd_lower': None,
            'dpd_upper': None,
            'parameters': '{card_due_amount, card_due_date, card_dpd}',
            'until_paid': False
        },
        {
            'status': None,
            'additional_condition': None,
            'title': 'Informasi Pinjaman',
            'content': 'Yth. {{card_first_name}}, angsuran {{card_due_amount}} '
                       'yang jatuh tempo pada {{card_due_date}} sudah terlambat '
                       '{{card_dpd}} hari. Harap hindari risiko akibat terlambat bayar.',
            'button': ['Bayar Sekarang'],
            'click_to': ['howtopay'],
            'template_code': 'card_t10',
            'template_type': '3B',
            'card_number': 1,
            'text_colour': '#f69539',
            'title_colour': '#f69539',
            'button_name': [L_BUTTON],
            'button_text_color': ['#ffffff'],
            'background_url': ImageNames.DESIGNS_REAL_ORANGE,
            'button_background': [ImageNames.BUTTON_BACKGROUND_ORANGE],
            'button_background_type': ['M'],
            'additional_images': [ImageNames.EXCLAMATION_IMAGE_ORANGE],
            'button_url': [],
            'dpd': 10,
            'dpd_lower': None,
            'dpd_upper': None,
            'parameters': '{card_first_name, card_due_amount, card_due_date, card_dpd}',
            'until_paid': False
        },
        {
            'status': None,
            'additional_condition': None,
            'title': 'Informasi Pinjaman',
            'content': 'Angsuran {{card_due_amount}} Anda jatuh tempo pada {{card_due_date}} '
                       'dan terlambat {{card_dpd}} hari. Cek informasi '
                       'program keringanan & hindari resiko denda menumpuk.',
            'button': ['Hubungi JULO', 'Bayar Sekarang'],
            'click_to': ['howtopay', 'contactus'],
            'template_code': 'card_t11-40',
            'template_type': '3A',
            'card_number': 1,
            'text_colour': '#db4d3d',
            'title_colour': '#db4d3d',
            'button_text_color': ['#db4d3d', '#ffffff'],
            'button_name': [L_BUTTON, R_BUTTON],
            'background_url': ImageNames.DESIGNS_REAL_RED,
            'button_background': [ImageNames.BUTTON_BACKGROUND_RED, ImageNames.BUTTON_BACKGROUND_RED_2],
            'button_background_type': ['L', 'R'],
            'additional_images': [ImageNames.EXCLAMATION_IMAGE_RED],
            'button_url': [],
            'dpd': None,
            'dpd_lower': 11,
            'dpd_upper': 40,
            'parameters': '{card_due_amount, card_due_date, card_dpd}',
            'until_paid': False
        },
        {
            'status': None,
            'additional_condition': None,
            'title': 'Informasi Pinjaman',
            'content': 'Angsuran {{card_due_amount}} Anda jatuh tempo pada {{card_due_date}} '
                       'dan terlambat {{card_dpd}} hari. Hubungi JULO untuk solusi & '
                       'informasi program keringanan. ',
            'button': ['Hubungi JULO', 'Bayar Sekarang'],
            'click_to': ['howtopay', 'contactus'],
            'template_code': 'card_t41-70',
            'template_type': '3A',
            'card_number': 1,
            'text_colour': '#db4d3d',
            'title_colour': '#db4d3d',
            'button_text_color': ['#db4d3d', '#ffffff'],
            'button_name': [L_BUTTON, R_BUTTON],
            'background_url': ImageNames.DESIGNS_REAL_RED,
            'button_background': [ImageNames.BUTTON_BACKGROUND_RED, ImageNames.BUTTON_BACKGROUND_RED_2],
            'button_background_type': ['L', 'R'],
            'additional_images': [ImageNames.EXCLAMATION_IMAGE_RED],
            'button_url': [],
            'dpd': None,
            'dpd_lower': 41,
            'dpd_upper': 70,
            'parameters': '{card_due_amount, card_due_date, card_dpd}',
            'until_paid': False
        },
        {
            'status': None,
            'additional_condition': None,
            'title': 'Informasi Pinjaman',
            'content': 'Angsuran {{card_due_amount}} Anda jatuh tempo pada {{card_due_date}} '
                       'dan terlambat {{card_dpd}} hari. Hubungi JULO untuk solusi '
                       '& informasi program keringanan. ',
            'button': ['Hubungi JULO', 'Bayar Sekarang'],
            'click_to': ['howtopay', 'contactus'],
            'template_code': 'card_t71-90',
            'template_type': '3A',
            'card_number': 1,
            'text_colour': '#db4d3d',
            'title_colour': '#db4d3d',
            'button_text_color': ['#db4d3d', '#ffffff'],
            'button_name': [L_BUTTON, R_BUTTON],
            'background_url': ImageNames.DESIGNS_REAL_RED,
            'button_background': [ImageNames.BUTTON_BACKGROUND_RED, ImageNames.BUTTON_BACKGROUND_RED_2],
            'button_background_type': ['L', 'R'],
            'additional_images': [ImageNames.EXCLAMATION_IMAGE_RED],
            'button_url': [],
            'dpd': None,
            'dpd_lower': 71,
            'dpd_upper': 90,
            'parameters': '{card_due_amount, card_due_date, card_dpd}',
            'until_paid': False
        },
        {
            'status': None,
            'additional_condition': None,
            'title': 'Informasi Pinjaman',
            'content': 'Angsuran {{card_due_amount}} Anda jatuh tempo pada {{card_due_date}} '
                       'dan terlambat {{card_dpd}} hari. Cek informasi program '
                       'keringanan & hindari resiko gagal bayar.',
            'button': ['Hubungi JULO', 'Bayar Sekarang'],
            'click_to': ['howtopay', 'contactus'],
            'template_code': 'card_t91',
            'template_type': '3A',
            'card_number': 1,
            'text_colour': '#db4d3d',
            'title_colour': '#db4d3d',
            'button_text_color': ['#db4d3d', '#ffffff'],
            'button_name': [L_BUTTON, R_BUTTON],
            'background_url': ImageNames.DESIGNS_REAL_RED,
            'button_background': [ImageNames.BUTTON_BACKGROUND_RED, ImageNames.BUTTON_BACKGROUND_RED_2],
            'button_background_type': ['L', 'R'],
            'additional_images': [ImageNames.EXCLAMATION_IMAGE_RED],
            'button_url': [],
            'dpd': None,
            'dpd_upper': None,
            'dpd_lower': 91,
            'parameters': '{card_due_amount, card_due_date, card_dpd}',
            'until_paid': True
        },
    ]
    for data in data_to_be_loaded:
        button_1_properties = {'card_type': '1',
                               'title': data['title'],
                               'title_color': data['title_colour'],
                               'text_color': data['text_colour'],
                               'card_order_number': data['card_number']}
        button_2_properties = {'card_type': '2',
                               'title': data['title'],
                               'title_color': data['title_colour'],
                               'text_color': data['text_colour'],
                               'card_order_number': data['card_number']}
        button_3A_properties = {'card_type': '3A',
                                'title': data['title'],
                                'title_color': data['title_colour'],
                                'text_color': data['text_colour'],
                                'card_order_number': data['card_number']}
        button_3B_properties = {'card_type': '3B',
                                'title': data['title'],
                                'title_color': data['title_colour'],
                                'text_color': data['text_colour'],
                                'card_order_number': data['card_number']}
        if data['template_type'] == '1':
            info_card = InfoCardProperty.objects.create(**button_1_properties)
        elif data['template_type'] == '2':
            info_card = InfoCardProperty.objects.create(**button_2_properties)
        elif data['template_type'] == '3A':
            info_card = InfoCardProperty.objects.create(**button_3A_properties)
        elif data['template_type'] == '3B':
            info_card = InfoCardProperty.objects.create(**button_3B_properties)
        button_info_card = dict()
        if data['button']:
            for idx, image_url in enumerate(data['button']):
                button_info_card['info_card_property'] = info_card
                button_info_card['text'] = data['button'][idx]
                button_info_card['button_name'] = data['button_name'][idx]
                button_info_card['action_type'] = CardProperty.APP_DEEPLINK
                button_info_card['destination'] = data['click_to'][idx]
                button_info_card['text_color'] = data['button_text_color'][idx]
                button, _ = InfoCardButtonProperty.objects.get_or_create(**button_info_card)
                # create_image(button.id, CardProperty.IMAGE_TYPE.button_background_image, data['button_url'][idx])
                create_image(button.id, CardProperty.IMAGE_TYPE.button_background_image, str(
                    data['button_background'][idx]))

        data_streamlined_message = {'message_content': data['content'],
                                    'info_card_property': info_card,
                                    'parameter': data['parameters']}
        message = StreamlinedMessage.objects.create(**data_streamlined_message)
        status = StatusLookup.objects.filter(status_code=data['status']).last()
        data_for_streamlined_comms = {'status_code': status,
                                      'status': data['status'],
                                      'communication_platform': CommunicationPlatform.INFO_CARD,
                                      'message': message,
                                      'description': 'retroloaded_card_information',
                                      'is_active': True,
                                      'extra_conditions': data['additional_condition'],
                                      'template_code': data['template_code'],
                                      'dpd': data['dpd'],
                                      'dpd_lower': data['dpd_lower'],
                                      'dpd_upper': data['dpd_upper'],
                                      'until_paid': data['until_paid']}
        streamlined_communication = StreamlinedCommunication.objects.create(**data_for_streamlined_comms)
        # create image for background
        if data['background_url']:
            create_image(info_card.id, CardProperty.IMAGE_TYPE.card_background_image, data['background_url'])

        if data['additional_images']:
            additional_image_url = data['additional_images']
            additional_image_url = additional_image_url[0]
            create_image(info_card.id, CardProperty.IMAGE_TYPE.card_optional_image, str(additional_image_url))

    # upload image
    images_list = (
        'designs_real_blue.png', 'designs_real_org.png', 'designs_real_red.png',
        'group_3500_blue.png', 'group_3500_org.png', 'group_3500_red.png',
        'rectangle_1489_blue.png', 'rectangle_1489_org.png', 'rectangle_1489_red.png',
        'rectangle_1489_2_red.png'
    )
    for image_name in images_list:
        remote_path = 'info-card/{}'.format(image_name)
        upload_file_to_oss(
            settings.OSS_PUBLIC_ASSETS_BUCKET,
            settings.STATICFILES_DIRS[0] + '/images/info_card/{}'.format(image_name),
            remote_path
        )


def add_streamlined_parameters(_apps, _schema_editor):
    data_seeds = [
        StreamlinedCommunicationParameterList(
            parameter_name='{card_cashback_multiplier}',
            description='state the cashback multiplier',
            platform=CommunicationPlatform.INFO_CARD
        ),
        StreamlinedCommunicationParameterList(
            parameter_name='{card_due_amount}',
            description='oldest account payment level due amount',
            platform=CommunicationPlatform.INFO_CARD
        ),
        StreamlinedCommunicationParameterList(
            parameter_name='{card_dpd}',
            description='State the dpd of the oldest account payment of customers',
            platform=CommunicationPlatform.INFO_CARD
        ),
    ]
    StreamlinedCommunicationParameterList.objects.bulk_create(data_seeds)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(retroload_cards_data_julo_one, migrations.RunPython.noop),
        migrations.RunPython(add_streamlined_parameters, migrations.RunPython.noop)
    ]
