# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-11-26 06:57
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import Workflow, WorkflowStatusPath
from juloserver.julo.constants import WorkflowConst


def add_status_path_workflow_132(apps, schema_editor):
    workflow = Workflow.objects.get(name=WorkflowConst.JULO_ONE)
    list_next_statuses = [124, 122, 137, 135, 134, 133, 131]
    for next_status in list_next_statuses:
        WorkflowStatusPath.objects.get_or_create(
            status_previous=132,
            status_next=next_status,
            type="detour",
            workflow=workflow
        )

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_status_path_workflow_132,
                             migrations.RunPython.noop)
    ]
