# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-12-15 17:17
from __future__ import unicode_literals

from django.db import migrations

from juloserver.streamlined_communication.constant import CommunicationPlatform
from juloserver.streamlined_communication.models import StreamlinedCommunicationFunctionList


def add_j1_function_list(apps, schema_editor):
    StreamlinedCommunicationFunctionList.objects.create(
        description="J1 Robocall first attempt",
        function_name="send_voice_account_payment_reminder",
        communication_platform=CommunicationPlatform.ROBOCALL,
        product="nexmo_j1"
    )
    StreamlinedCommunicationFunctionList.objects.create(
        description="J1 Robocall second attempt",
        function_name="retry_send_voice_account_payment_reminder1",
        communication_platform=CommunicationPlatform.ROBOCALL,
        product="nexmo_j1"
    )
    StreamlinedCommunicationFunctionList.objects.create(
        description="J1 Robocall third attempt",
        function_name="retry_send_voice_account_payment_reminder2",
        communication_platform=CommunicationPlatform.ROBOCALL,
        product="nexmo_j1"
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_j1_function_list, migrations.RunPython.noop)
    ]
