# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-12-16 13:53
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import WorkflowStatusPath, Workflow
from juloserver.julo.constants import WorkflowConst


def add_status_path_reupload(apps, _schema_editor):
    workflow = Workflow.objects.get(name=WorkflowConst.JULO_ONE)
    WorkflowStatusPath.objects.get_or_create(
        status_previous=147,
        status_next=150,
        type="detour",
        workflow=workflow
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_status_path_reupload, migrations.RunPython.noop)
    ]
