# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-12-24 01:07
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import SepulsaProduct


def retroload_price_sepulsa_product(apps, _schema_editor):
    sepulsa_products = SepulsaProduct.objects.all()
    for sepulsa_product in sepulsa_products:
        sepulsa_product.update_safely(
            customer_price_regular=sepulsa_product.partner_price,
            is_not_blocked=sepulsa_product.is_active,
        )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(retroload_price_sepulsa_product, migrations.RunPython.noop)
    ]
