# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-01-06 07:57
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import MobileFeatureSetting
from juloserver.loan.constants import LoanJuloOneConstant


def lock_ppob_feature_mobile_setting(apps, schema_editor):
    MobileFeatureSetting.objects.create(
        feature_name=LoanJuloOneConstant.PRODUCT_LOCK_FEATURE_SETTING,
        parameters={LoanJuloOneConstant.PPOB_PRODUCT: {'locked': True, 'app_version': '5.1.0'}},
        is_active=True
    )


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunPython(lock_ppob_feature_mobile_setting),
    ]