# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-01-18 08:53
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def add_valid_for_ever_entered_b5_configuration(apps, schema_editor):
    FeatureSetting.objects.get_or_create(
        is_active=True,
        feature_name=FeatureNameConst.EVER_ENTERED_B5_J1_EXPIRED_CONFIGURATION,
        category="J1_account",
        parameters={
            "entered_b5_valid_for": "90"
        },
        description="How long will the TRUE flag of ever_entered_B5 affect the future loans taken?")


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_valid_for_ever_entered_b5_configuration, migrations.RunPython.noop)
    ]
