# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-01-14 09:11
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import Workflow, WorkflowStatusPath
from juloserver.julo.constants import WorkflowConst


def add_new_status_path_for_privy_expiration(apps, schema_editor):
    workflow = Workflow.objects.filter(name=WorkflowConst.JULO_ONE).first()
    if workflow:
        WorkflowStatusPath.objects.get_or_create(
            status_previous=147,
            status_next=136,
            type="detour",
            workflow=workflow
        )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_new_status_path_for_privy_expiration, migrations.RunPython.noop)
    ]
