# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-01-19 08:06
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst


def create_credit_limit_feature(apps, schema_editor):
    FeatureSetting.objects.get_or_create(
        is_active=True,
        feature_name=FeatureNameConst.CREDIT_LIMIT_REJECT_AFFORDABILITY,
        description="Configuration for limit credit generation",
        parameters={'limit_value': 300000},
        category='application'
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_credit_limit_feature),
    ]
