# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-01-19 04:27
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import Customer
from juloserver.julo.statuses import LoanStatusCodes


def update_ever_entered_250(apps, _schema_editor):
    queryset = Customer.objects.filter(loan__loan_status_id=LoanStatusCodes.PAID_OFF)
    queryset.update(ever_entered_250=True)

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(update_ever_entered_250, migrations.RunPython.noop)
    ]
