# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-02-08 15:22
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import PartnerOriginationData, Partner


def create_new_partner_origination(app, schema_editor):
    data = {
        'id': 4053,
        'distributor_name': 'CV. Mantra Adhi Utama',
        'origination_fee': 0.0,
        'partner': Partner.objects.get_or_none(name='axiata')
    }
    PartnerOriginationData.objects.get_or_create(**data)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_new_partner_origination, migrations.RunPython.noop)
    ]
