# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-02-05 07:15
from __future__ import unicode_literals

from django.db import migrations
from juloserver.whatsapp.models import WhatsappTemplate


def add_initial_whatsapp_text(apps, schema_editor):
    text_content_j1 = (
        "Yth {{ application.gender|bapak_or_ibu|default:'Bpk/Ibu'|safe }}"
        " {{ application.fullname|default:''|safe }}\n"
        "\nMengingatkan kembali bahwa angsuran Anda di JULO akan jatuh tempo pada "
        '{{ payment.due_date|date:"d M Y"|safe|safe}}'
        " sejumlah Rp "
        '{{ payment.due_amount|f_rupiahs:"no_currency"|default:"-"|safe}}'
        
        "\nAnda dapat melakukan pembayaran ke :\n"
        
        "\n{% for payment_method in payment_methods %}"
        '\n- {{payment_method.payment_method_new_name}} a/n JULO dengan nomor Virtual Account {{payment_method.virtual_account|default:"-"|safe}}'
        "\n{% endfor %}\n"
        
        "\nMohon lakukan pembayaran sebelum/tepat waktu untuk menghindari denda keterlambatan dan menjaga skor kredibilitas Anda."
        "\nSetiap pembayaran yang dilakukan tepat waktu akan mendapatkan cashback dan dapat dicairkan ke rekening Anda setelah pinjaman di JULO selesai.\n"
        
        "\nTerima kasih."
        )

    WhatsappTemplate.objects.create(text_content=text_content_j1.decode("unicode_escape"),
                                    type='account_payment_collection_j1')

    text_content_mtl = (
        "Yth {{ application.gender|bapak_or_ibu|default:'Bpk/Ibu'|safe }}"
        " {{ application.fullname|default:''|safe }}\n"
        "\nMengingatkan kembali bahwa angsuran ke "
        "\n{{payment.payment_number|default:''|safe }}"
        " Anda di JULO akan jatuh tempo pada "
        '{{payment.due_date|date:"d M Y"|safe|safe}}'

        " sejumlah Rp "
        '{{payment.due_amount|f_rupiahs:"no_currency"|default:"-"|safe}}'
        
        "\nAnda dapat melakukan pembayaran ke :\n"

        '\n-{{loan.julo_bank_name|default:"-"|safe}}'
        " a/n JULO dengan nomor Virtual Account "
        '{{loan.julo_bank_account_number|default:"-"|safe}}\n'
        
        "\n{% for payment_method in payment_methods %}"
        '\n- {{payment_method.payment_method_new_name}} a/n JULO dengan nomor Virtual Account {{payment_method.virtual_account|default:"-"|safe}}'
        "\n{% endfor %}\n"
        
        "\nMohon lakukan pembayaran sebelum/tepat waktu untuk menghindari denda keterlambatan dan menjaga skor kredibilitas Anda."
        "\nSetiap pembayaran yang dilakukan tepat waktu akan mendapatkan cashback dan dapat dicairkan ke rekening Anda setelah pinjaman di JULO selesai.\n"
        
        "\nTerima kasih."
    )
    WhatsappTemplate.objects.create(text_content=text_content_mtl.decode("unicode_escape"),
                                    type='payment_collection_mtl')

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_initial_whatsapp_text, migrations.RunPython.noop)
    ]
