# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-02-11 06:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE ops.grab_api_log ALTER COLUMN application_id TYPE bigint;"),
            migrations.RunSQL(
            "ALTER TABLE ops.grab_api_log ALTER COLUMN loan_id TYPE bigint;"),
            migrations.RunSQL(
            "ALTER TABLE ops.grab_api_log ALTER COLUMN customer_id TYPE bigint;"),
    ]
