# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-02-25 03:55
from __future__ import unicode_literals

from django.utils import timezone
from django.db import migrations
from juloserver.followthemoney.models import LenderCurrent, LoanAgreementTemplate, LenderApproval


def add_grab_lender_approval_and_sphp_template(apps, schema_editor):
    jtp = LenderCurrent.objects.filter(lender_name="jtp", lender_status="active").last()
    if not jtp:
        return
    jtp_partner = jtp.user.partner

    gfin = LenderCurrent.objects.filter(lender_name="gfin").last()
    if not gfin:
        return
    gfin_partner = gfin.user.partner

    agreement_templates = []
    for agreement_template in jtp.loanagreementtemplate_set.all():
        is_agreement_exists = LoanAgreementTemplate.objects.filter(
            lender=gfin, agreement_type=agreement_template.agreement_type
        ).exists()
        if not is_agreement_exists:
            agreement_template.pk = None
            agreement_template.lender = gfin
            agreement_templates.append(agreement_template)
    LoanAgreementTemplate.objects.bulk_create(agreement_templates)

    if not LenderApproval.objects.filter(partner=gfin_partner).exists():
        LenderApproval.objects.create(
            partner=gfin_partner,
            is_auto=jtp_partner.lenderapproval.is_auto,
            start_date=timezone.localtime(timezone.now()),
            end_date=None,
            delay=jtp_partner.lenderapproval.delay,
            expired_in=jtp_partner.lenderapproval.expired_in,
            is_endless=jtp_partner.lenderapproval.is_endless,
        )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_grab_lender_approval_and_sphp_template, migrations.RunPython.noop),
    ]
