# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-02-25 05:54
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import WorkflowStatusPath, ChangeReason, Workflow
from juloserver.julo.statuses import LoanStatusCodes


def add_new_status_path_and_change_reason(apps, schema_editor):
    legacy_workflow = Workflow.objects.filter(name="LegacyWorkflow").first()
    if legacy_workflow:
        WorkflowStatusPath.objects.get_or_create(
            status_previous=LoanStatusCodes.MANUAL_FUND_DISBURSAL_ONGOING,
            status_next=LoanStatusCodes.CANCELLED_BY_CUSTOMER,
            type="graveyard",
            workflow=legacy_workflow
        )
        change_reasons = ['failed transaction', 'customer requested to cancel']
        for change_reason in change_reasons:
            ChangeReason.objects.get_or_create(
                reason=change_reason,
                status_id=LoanStatusCodes.CANCELLED_BY_CUSTOMER
            )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_new_status_path_and_change_reason, migrations.RunPython.noop),
    ]
