# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-03-09 15:16
from __future__ import unicode_literals

from django.db import migrations

from juloserver.application_flow.models import ApplicationTag, ApplicationPathTagStatus

def retro_application_tag(apps, schema_editor):
    tag_data = [
        'is_hsfbp',
        'is_mandatory_docs',
        'is_dv',
        'is_sonic',
        'is_pve',
        'is_pva',
        'is_ca',
        'is_ac',
    ]
    for tag in tag_data:
        ApplicationTag.objects.create(application_tag=tag)

    application_tag_data = [
        ['is_hsfbp', 0, 'fail'],
        ['is_hsfbp', 1, 'success'],
        ['is_mandatory_docs', 0, 'fail'],
        ['is_mandatory_docs', 1, 'success'],
        ['is_dv', 0, 'fail'],
        ['is_dv', 1, 'success'],
        ['is_dv', 3, 'GPS by agent'],
        ['is_sonic', 0, 'fail'],
        ['is_sonic', 1, 'success'],
        ['is_pve', 0, 'fail'],
        ['is_pve', 1, 'success'],
        ['is_pva', 0, 'fail'],
        ['is_pva', 1, 'success'],
        ['is_ca', 0, 'fail'],
        ['is_ca', 1, 'success'],
        ['is_ac', 0, 'fail'],
        ['is_ac', 1, 'success'],
    ]
    for application_tag in application_tag_data:
        ApplicationPathTagStatus.objects.create(
            application_tag=application_tag[0],
            status=application_tag[1],
            definition=application_tag[2])


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(retro_application_tag, migrations.RunPython.noop),
    ]
