# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-03-24 10:10
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.statuses import LoanStatusCodes
from juloserver.streamlined_communication.constant import CommunicationPlatform
from juloserver.streamlined_communication.models import (StreamlinedCommunication, StreamlinedMessage)


def update_email_streamlined_data(apps, schema_editor):

    data = [
        {
            'template_code': 'email_reminder_ptp_agreed',
            'product': 'mtl',
            'title': 'Janji Bayar Anda Telah Dibuat',
            'ptp' : 'real-time'
        },
        {
            'template_code': 'email_reminder_ptp_-2',
            'product': 'mtl',
            'title': '2 Hari Sebelum Janji Bayar, Lakukan Pembayaran Secepatnya.',
            'ptp' : '-2'
        },
        {
            'template_code': 'email_reminder_ptp_0',
            'product': 'mtl',
            'title': 'Hari Terakhir Janji Bayar Anda.',
            'ptp' : '0'
        },
        {
            'template_code': 'email_reminder_ptp_j1_agreed',
            'product': 'j1',
            'title': 'Janji Bayar Anda Telah Dibuat',
            'ptp': 'real-time'
        },
        {
            'template_code': 'email_reminder_ptp_j1_-2',
            'product': 'j1',
            'title': '2 Hari Sebelum Janji Bayar, Lakukan Pembayaran Secepatnya.',
            'ptp': '-2'
        },
        {
            'template_code': 'email_reminder_ptp_j1_0',
            'product': 'j1',
            'title': 'Hari Terakhir Janji Bayar Anda.',
            'ptp': '0'
        },
    ]

    email_content = {
        '-2' : '<html><head><meta name="viewport" content="width=device-width, initial-scale=1"><style>@import url(https://fonts.googleapis.com/css2?family=Nunito&display=swap);</style><style>.email-body{padding:0;margin:0;font-family:Nunito;font-size:20px;color:#182940;letter-spacing:normal;text-align:left;font-stretch:normal;font-style:normal;width:100%}p{margin:0;float:left;width:100%}a{color:#0077a9}img{max-width:100%}.table_pad{padding-left:1rem;padding-top:1rem;padding-right:1rem;line-height:1.6;font-family:Nunito;font-size:16px;color:#182940;letter-spacing:normal;text-align:left;font-stretch:normal;font-style:normal}.table_pad1{padding-left:25px;padding-top:40px;padding-right:35px}.td_font1{font-size:16px;color:#242424}.td_font4{color:#004c99}.td_pad1{padding-top:16px}.td_pad4{padding-top:24px}.td_pad5{padding-top:16px}.td_bot_pad{padding-bottom:80px}.td_font1_bold{font-weight:700}.td_font1_italic{font-style:italic;font-weight:lighter}.td_line_height{line-height:25px}.borders{border:1px solid #404040}.img_align{vertical-align:middle}.full{width:100%;border-collapse:collapse;border-spacing:0}.title_font{font-size:16;font-weight:800;line-height:1.33}.table_font{color:#666}.th_font{font-weight:600}.email_footer{width:100%;background:#222;padding:0;margin:0;font-family:Nunito;font-size:16px;color:#fff;letter-spacing:normal;text-align:left;font-stretch:normal;font-style:normal;text-align:center;margin-top:80px}.gg_play{width:160px}.email_footer_icon{width:25px}.last_email_footer{padding-bottom:24px}.btn_image{width:225px}.overflow{overflow-x:auto}</style></head><body class="email-body"><div><div><img class="full" src="https://julocampaign.oss-ap-southeast-5.aliyuncs.com/collection/email_ptp_banner_before_after.png"></div><div class="table_pad" ><div class="td_pad1"> Yth {{title}} {{fullname}},<br><br>Masa janji bayar Anda akan berakhir 2 hari lagi, mohon lakukan pembayaran secepatnya sebelum janji bayar berakhir.<br/>Mohon untuk melakukan pembayaran sesuai dengan kesepakatan yang telah dilakukan dengan tim Julo dengan keterangan sebagai berikut: <br/>Tanggal Janji Bayar: <b>{{ptp_date}}</b><br/>Jumlah Janji Bayar: <b>{{ptp_amount}}</b> <br/><br/>Pembayaran dapat dilakukan melalui:<br/>Pembayaran ke: <b>{{primary_va_name}}</b><br/>No Tujuan Pembayaran: <b>{{primary_va_number}}</b><br><br/>Atau klik disini untuk cara melakukan pembayaran: </div><div class="td_pad1"><table cellpadding="4" cellspacing="0" align="center" ><div><div align="center" class="td_font4 td_font1_bold" colspan="2"><a href="https://go.onelink.me/zOQD/epay"><img alt="Bayar Sekarang" height="auto" class="btn_image" src="https://julocampaign.oss-ap-southeast-5.aliyuncs.com/refinancing_integration/bayar-sekarang-button.png"></a></div></div></table></div><div align="left"> Salam,<br/> JULO<br/></div></div><div role="presentation" class="email_footer"><div class="td_pad4">Pinjaman Cerdas Dari Smartphone Anda</div><div class="td_pad5"><a href="https://play.google.com/store/apps/details?id=com.julofinance.juloapp" target="_blank"><img src="https://statics.julo.co.id/juloserver/staging/static/images/email/google-play-badge.png" alt="google-play" class="gg_play"></a></div><div class="td_pad5"><a href="https://www.instagram.com/juloindonesia/" target="_blank"><img alt="instagram" height="NaN" class="email_footer_icon" src="https://www.julo.co.id/images/icon_instagram.png"></a><a href="https://www.facebook.com/juloindonesia/" target="_blank"><img alt="facebook" class="email_footer_icon" src="https://www.julo.co.id/images/icon_facebook.png"></a><a href="https://twitter.com/juloindonesia" target="_blank"><img alt="twitter" class="email_footer_icon" src="https://www.julo.co.id/images/icon_twitter.png"></a><a href="https://www.youtube.com/channel/UCA9WsBMIg3IHxwVA-RvSctA" target="_blank"><img alt="twitter" class="email_footer_icon" src="https://www.julo.co.id/images/icon_youtube.png"></a></div class="td_pad5"><div class="last_email_footer">©2021 JULO | All rights reserved</div></div></div></body></html>',
        'real-time' : '<html><head><meta name="viewport" content="width=device-width, initial-scale=1"><style>@import url(https://fonts.googleapis.com/css2?family=Nunito&display=swap);</style><style>.email-body{padding:0;margin:0;font-family:Nunito;font-size:20px;color:#182940;letter-spacing:normal;text-align:left;font-stretch:normal;font-style:normal;width:100%}p{margin:0;float:left;width:100%}a{color:#0077a9}img{max-width:100%}.table_pad{padding-left:1rem;padding-top:1rem;padding-right:1rem;line-height:1.6;font-family:Nunito;font-size:16px;color:#182940;letter-spacing:normal;text-align:left;font-stretch:normal;font-style:normal}.table_pad1{padding-left:25px;padding-top:40px;padding-right:35px}.td_font1{font-size:16px;color:#242424}.td_font4{color:#004c99}.td_pad1{padding-top:16px}.td_pad4{padding-top:24px}.td_pad5{padding-top:16px}.td_bot_pad{padding-bottom:80px}.td_font1_bold{font-weight:700}.td_font1_italic{font-style:italic;font-weight:lighter}.td_line_height{line-height:25px}.borders{border:1px solid #404040}.img_align{vertical-align:middle}.full{width:100%;border-collapse:collapse;border-spacing:0}.title_font{font-size:16;font-weight:800;line-height:1.33}.table_font{color:#666}.th_font{font-weight:600}.email_footer{width:100%;background:#222;padding:0;margin:0;font-family:Nunito;font-size:16px;color:#fff;letter-spacing:normal;text-align:left;font-stretch:normal;font-style:normal;text-align:center;margin-top:80px}.gg_play{width:160px}.email_footer_icon{width:25px}.last_email_footer{padding-bottom:24px}.btn_image{width:225px}.overflow{overflow-x:auto}</style></head><body class="email-body"><div><div><img class="full" src="https://julocampaign.oss-ap-southeast-5.aliyuncs.com/collection/email_ptp_banner_before_after.png"></div><div class="table_pad" ><div class="td_pad1"> Yth {{title}} {{fullname}},<br><br>Terima kasih atas janji bayar Anda.<br/>Mohon untuk melakukan pembayaran sesuai dengan kesepakatan yang telah dilakukan dengan tim Julo dengan keterangan sebagai berikut: <br/>Tanggal Janji Bayar: <b>{{ptp_date}}</b><br/>Jumlah Janji Bayar: <b>{{ptp_amount}}</b> <br/><br/>Pembayaran dapat dilakukan melalui:<br/>Pembayaran ke: <b>{{primary_va_name}}</b><br/>No Tujuan Pembayaran: <b>{{primary_va_number}}</b><br><br/>Atau klik disini untuk cara melakukan pembayaran: </div><div class="td_pad1"><table cellpadding="4" cellspacing="0" align="center" ><div><div align="center" class="td_font4 td_font1_bold" colspan="2"><a href="https://go.onelink.me/zOQD/epay"><img alt="Bayar Sekarang" height="auto" class="btn_image" src="https://julocampaign.oss-ap-southeast-5.aliyuncs.com/refinancing_integration/bayar-sekarang-button.png"></a></div></div></table></div><div align="left"> Salam,<br/> JULO<br/></div></div><div role="presentation" class="email_footer"><div class="td_pad4">Pinjaman Cerdas Dari Smartphone Anda</div><div class="td_pad5"><a href="https://play.google.com/store/apps/details?id=com.julofinance.juloapp" target="_blank"><img src="https://statics.julo.co.id/juloserver/staging/static/images/email/google-play-badge.png" alt="google-play" class="gg_play"></a></div><div class="td_pad5"><a href="https://www.instagram.com/juloindonesia/" target="_blank"><img alt="instagram" height="NaN" class="email_footer_icon" src="https://www.julo.co.id/images/icon_instagram.png"></a><a href="https://www.facebook.com/juloindonesia/" target="_blank"><img alt="facebook" class="email_footer_icon" src="https://www.julo.co.id/images/icon_facebook.png"></a><a href="https://twitter.com/juloindonesia" target="_blank"><img alt="twitter" class="email_footer_icon" src="https://www.julo.co.id/images/icon_twitter.png"></a><a href="https://www.youtube.com/channel/UCA9WsBMIg3IHxwVA-RvSctA" target="_blank"><img alt="twitter" class="email_footer_icon" src="https://www.julo.co.id/images/icon_youtube.png"></a></div class="td_pad5"><div class="last_email_footer">©2021 JULO | All rights reserved</div></div></div></body></html>',
        '0' : '<html><head><meta name="viewport" content="width=device-width, initial-scale=1"><style>@import url(https://fonts.googleapis.com/css2?family=Nunito&display=swap);</style><style>.email-body{padding:0;margin:0;font-family:Nunito;font-size:20px;color:#182940;letter-spacing:normal;text-align:left;font-stretch:normal;font-style:normal;width:100%}p{margin:0;float:left;width:100%}a{color:#0077a9}img{max-width:100%}.table_pad{padding-left:1rem;padding-top:1rem;padding-right:1rem;line-height:1.6;font-family:Nunito;font-size:16px;color:#182940;letter-spacing:normal;text-align:left;font-stretch:normal;font-style:normal}.table_pad1{padding-left:25px;padding-top:40px;padding-right:35px}.td_font1{font-size:16px;color:#242424}.td_font4{color:#004c99}.td_pad1{padding-top:16px}.td_pad4{padding-top:24px}.td_pad5{padding-top:16px}.td_bot_pad{padding-bottom:80px}.td_font1_bold{font-weight:700}.td_font1_italic{font-style:italic;font-weight:lighter}.td_line_height{line-height:25px}.borders{border:1px solid #404040}.img_align{vertical-align:middle}.full{width:100%;border-collapse:collapse;border-spacing:0}.title_font{font-size:16;font-weight:800;line-height:1.33}.table_font{color:#666}.th_font{font-weight:600}.email_footer{width:100%;background:#222;padding:0;margin:0;font-family:Nunito;font-size:16px;color:#fff;letter-spacing:normal;text-align:left;font-stretch:normal;font-style:normal;text-align:center;margin-top:80px}.gg_play{width:160px}.email_footer_icon{width:25px}.last_email_footer{padding-bottom:24px}.btn_image{width:225px}.overflow{overflow-x:auto}</style></head><body class="email-body"><div><div><img class="full" src="https://julocampaign.oss-ap-southeast-5.aliyuncs.com/collection/email_ptp_notification_banner_on_date.png"></div><div class="table_pad" ><div class="td_pad1"> Yth {{title}} {{fullname}},<br><br>Hari ini adalah hari terakhir janji bayar Anda. Mohon segera lakukan pembayaran sebelum masa janji bayar berakhir.<br/>Mohon untuk melakukan pembayaran sesuai dengan kesepakatan yang telah dilakukan dengan tim Julo dengan keterangan sebagai berikut: <br/>Tanggal Janji Bayar: <b>{{ptp_date}}</b><br/>Jumlah Janji Bayar: <b>{{ptp_amount}}</b> <br/><br/>Pembayaran dapat dilakukan melalui:<br/>Pembayaran ke: <b>{{primary_va_name}}</b><br/>No Tujuan Pembayaran: <b>{{primary_va_number}}</b><br><br/>Atau klik disini untuk cara melakukan pembayaran: </div><div class="td_pad1"><table cellpadding="4" cellspacing="0" align="center" ><div><div align="center" class="td_font4 td_font1_bold" colspan="2"><a href="https://go.onelink.me/zOQD/epay"><img alt="Bayar Sekarang" height="auto" class="btn_image" src="https://julocampaign.oss-ap-southeast-5.aliyuncs.com/refinancing_integration/bayar-sekarang-button.png"></a></div></div></table></div><div align="left"> Salam,<br/> JULO<br/></div></div><div role="presentation" class="email_footer"><div class="td_pad4">Pinjaman Cerdas Dari Smartphone Anda</div><div class="td_pad5"><a href="https://play.google.com/store/apps/details?id=com.julofinance.juloapp" target="_blank"><img src="https://statics.julo.co.id/juloserver/staging/static/images/email/google-play-badge.png" alt="google-play" class="gg_play"></a></div><div class="td_pad5"><a href="https://www.instagram.com/juloindonesia/" target="_blank"><img alt="instagram" height="NaN" class="email_footer_icon" src="https://www.julo.co.id/images/icon_instagram.png"></a><a href="https://www.facebook.com/juloindonesia/" target="_blank"><img alt="facebook" class="email_footer_icon" src="https://www.julo.co.id/images/icon_facebook.png"></a><a href="https://twitter.com/juloindonesia" target="_blank"><img alt="twitter" class="email_footer_icon" src="https://www.julo.co.id/images/icon_twitter.png"></a><a href="https://www.youtube.com/channel/UCA9WsBMIg3IHxwVA-RvSctA" target="_blank"><img alt="twitter" class="email_footer_icon" src="https://www.julo.co.id/images/icon_youtube.png"></a></div class="td_pad5"><div class="last_email_footer">©2021 JULO | All rights reserved</div></div></div></body></html>'
    }

    is_automated = False
    for item in data:
        # Email font-family: Nunito;
        email_reminder_ptp, _ = \
            StreamlinedMessage.objects.get_or_create(
                message_content=email_content[item['ptp']],
                parameter="{title,fullname,ptp_date,ptp_amount,primary_va_name,primary_va_number}",
            )
        time_sent = '' if item['ptp'] == 'real-time' else '14:30'
        streamlined_communication = StreamlinedCommunication.objects.get_or_create(
            message=email_reminder_ptp,
            status='send email reminder when ptp {}'.format(item['ptp']),
            communication_platform=CommunicationPlatform.EMAIL,
            template_code=item['template_code'],
            ptp=item['ptp'],
            product=item['product'],
            subject=item['title'],
            description="this email send in send_automated_comms and have ptp {}".format(item['ptp']),
            is_active=True,
            type='Payment Reminder',
            time_sent=time_sent,
            is_automated=is_automated,
        )


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunPython(update_email_streamlined_data,
                             migrations.RunPython.noop)
    ]
