# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-03-22 04:29
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.loan.constants import LoanJuloOneConstant

def add_feature_setting_to_block_specific_phone_number_sepulsa(apps, schema_editor):
    list_of_phone_number = [
        '085964420190',
        '087711033032',
        '085609567344'
    ]

    blacklist_phone_numnber = {
        'blacklist_phone_numnber': list_of_phone_number
    }

    FeatureSetting.objects.create(
        feature_name=LoanJuloOneConstant.PHONE_NUMBER_BLACKLIST,
        parameters=blacklist_phone_numnber,
        is_active=True,
        description='block specific phone number',
        category='security issue'
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            add_feature_setting_to_block_specific_phone_number_sepulsa, migrations.RunPython.noop),
    ]
