# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-04-05 06:18
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst


def create_feature_setting(apps, schema_editor):
    FeatureSetting.objects.get_or_create(
        is_active=True,
        feature_name=FeatureNameConst.NOTIFICATION_MINIMUM_PARTNER_DEPOSIT_BALANCE,
        description="configuration for sending notification when sepulsa deposit balance "
                    "reach minimum threshold",
        parameters={
            "users": [
                "U5ND8AZBM", "U01NUNAND7E",
                "UBV0WQ0AE", "U015A92Q96W"
            ],
            "balance_threshold": 10000000
        },
        category='disbursement'
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_feature_setting),
    ]
