# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-04-08 12:33
from __future__ import unicode_literals

from django.db import migrations

from django.contrib.auth.models import Group


def load_pm_auth_group(apps, schema_editor):
    Group.objects.create(name="cs_team_leader")


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(load_pm_auth_group, migrations.RunPython.noop)
    ]
