# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-04-02 07:40
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst


def add_clcs_scraped_schedule_feature_settings(apps, schema_editor):
    FeatureSetting.objects.get_or_create(
        is_active=True,
        feature_name=FeatureNameConst.CLCS_SCRAPED_SCHEDULE,
        category="schedule",
        parameters={"days": 7},
        description="Schedule of clcs scraped data from android-side"
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_clcs_scraped_schedule_feature_settings, migrations.RunPython.noop)
    ]
