# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-04-12 12:41
from __future__ import unicode_literals
from builtins import str

from django.db import migrations
from juloserver.application_flow.models import DigitalSignatureThreshold, VoiceRecordingThreshold


def add_initial_values_for_voice_recording_and_digital_signature_config(apps, schema_editor):
    THRESHOLD_VALUES = {
        1: (300000,50000),
        2: (300000,50000),
        3: (150000,50000),
        4: (300000,50000),
        5: (500000,50000),
        6: (500000,50000),
        7: (500000,50000),
        8: (150000,10000)
    }
    for (method_id, thresholds) in list(THRESHOLD_VALUES.items()):
        VoiceRecordingThreshold.objects.create(
            transaction_method_id=method_id,
            parameters={'voice_recording_loan_amount_threshold': str(thresholds[0])}
            )
        DigitalSignatureThreshold.objects.create(
            transaction_method_id=method_id,
            parameters={'digital_signature_loan_amount_threshold': str(thresholds[1])}
            )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_initial_values_for_voice_recording_and_digital_signature_config),
    ]
