# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-04-23 02:47
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.statuses import LoanStatusCodes, StatusManager
from juloserver.julo.models import StatusLookup


def update_status_lookups_215(apps, schema_editor):
    new_statuses = [
        LoanStatusCodes.TRANSACTION_FAILED,
    ]

    for new_status in new_statuses:
        status = StatusManager.get_or_none(new_status)
        StatusLookup.objects.filter(
            status_code=status.code
        ).update(status=status.desc)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(update_status_lookups_215)
    ]
