# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-04-23 09:22
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def add_feature_setting_cashback_delay_limit_threshold(apps, schema_editor):

    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.CASHBACK_DELAY_LIMIT,
        parameters='225000',
        is_active=True,
        description='limit of cashback in CRM (Highest Loan Amount x Highest Cashback Percentage) '
                    '/ Shortest Tenor Available',
        category='cashback setting'
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            add_feature_setting_cashback_delay_limit_threshold, migrations.RunPython.noop),
    ]

