# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-03-22 02:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations

from juloserver.julo.models import MobileFeatureSetting
from juloserver.payment_point.constants import FeatureNameConst
from juloserver.payment_point.models import TransactionMethod
from juloserver.loan.constants import LoanJuloOneConstant


BUCKET_URL = settings.STATIC_ALICLOUD_BUCKET_URL + 'ppobv2/'


def data_seed_for_transaction_method(app, schema_editor):
    TransactionMethod.objects.get_or_create(
        id=9,
        method='qris',
        fe_display_name='Bayar QR',
        background_icon_url=BUCKET_URL + 'qris_background.gif',
        foreground_icon_url=BUCKET_URL + 'qris.png',
        foreground_locked_icon_url=BUCKET_URL + 'qris_locked.png'
    )


def feature_settings_for_transaction_method_highlight(app, schema_editor):
    mobile_feature_setting = MobileFeatureSetting.objects.filter(
        feature_name=FeatureNameConst.TRANSACTION_METHOD_HIGHLIGHT,
    ).last()
    if mobile_feature_setting:
        mobile_feature_setting.parameters[9] = {'is_active': False, 'limit_threshold': 0}
        mobile_feature_setting.save()


def lock_qris_feature_mobile_setting(apps, schema_editor):
    mobile_feature_setting = MobileFeatureSetting.objects.filter(
        feature_name=LoanJuloOneConstant.PRODUCT_LOCK_FEATURE_SETTING
    ).last()
    if mobile_feature_setting:
        mobile_feature_setting.parameters[LoanJuloOneConstant.QRIS] = \
            {'locked': True, 'app_version': '5.10.0'}
        mobile_feature_setting.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(data_seed_for_transaction_method, migrations.RunPython.noop),
        migrations.RunPython(feature_settings_for_transaction_method_highlight,
                             migrations.RunPython.noop),
        migrations.RunPython(lock_qris_feature_mobile_setting),
    ]
