# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-05-11 02:29
import time

from django.db import migrations

from rest_framework.authtoken.models import Token

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting

from juloserver.api_token.constants import EXPIRY_SETTING_KEYWORD
from juloserver.api_token.models import ExpiryToken


def retroload_expiry_token_setting(apps, _schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.EXPIRY_TOKEN_SETTING,
        is_active=False,
        parameters={EXPIRY_SETTING_KEYWORD: 30},
        category='CustomerExpiryToken',
        description='* Updated settings need to wait at least 1 hour'
    )


def retroload_expiry_token(apps, _schema_editor):
    last_token = ExpiryToken.objects.last()
    if last_token:
        token_data = Token.objects.filter(user_id__gt=last_token.user_id).order_by('user_id')
    else:
        token_data = Token.objects.all().order_by('user_id')

    counter = 0
    expiry_token_list = []
    block = 10000
    block_counter = 0

    for token in token_data.iterator():
        counter += 1
        expiry_token_list.append(ExpiryToken(user_id=token.user_id, key=token.key))

        if counter == block:
            block_counter += 1
            ExpiryToken.objects.bulk_create(expiry_token_list)
            expiry_token_list = []
            counter = 0
            print(f'Done for {block_counter}', token.user_id)
            time.sleep(0.2)

    if expiry_token_list:
        ExpiryToken.objects.bulk_create(expiry_token_list)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(retroload_expiry_token_setting, migrations.RunPython.noop),
        migrations.RunPython(retroload_expiry_token, migrations.RunPython.noop),
    ]
