# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-05-11 02:29
from __future__ import unicode_literals

from django.db import migrations
from juloserver.account.models import AccountLookup
from juloserver.julo.constants import WorkflowConst


def fill_moengage_mapping(apps, _schema_editor):
    account_lookups = AccountLookup.objects.all()
    for account_lookup in account_lookups:
        if account_lookup.workflow.name == WorkflowConst.JULO_ONE and not account_lookup.moengage_mapping_number:
            moengage_mapping_number = '1'
            account_lookup.update_safely(
                moengage_mapping_number=moengage_mapping_number)
        elif account_lookup.workflow.name == WorkflowConst.GRAB and not account_lookup.moengage_mapping_number:
            moengage_mapping_number = '2'
            account_lookup.update_safely(
                moengage_mapping_number=moengage_mapping_number)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(fill_moengage_mapping, migrations.RunPython.noop),
    ]
