# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-05-18 08:27
from __future__ import unicode_literals

from django.db import migrations

from juloserver.streamlined_communication.constant import CommunicationPlatform
from juloserver.streamlined_communication.models import StreamlinedCommunicationParameterList


def add_new_parameter_for_sms(apps, schema_editor):
    data_seeds = [
        StreamlinedCommunicationParameterList(
            parameter_name='{{sms_due_amount}}',
            description='account level/oldest unpaid account payment due amount '
                        'using thousands separator .',
            platform=CommunicationPlatform.SMS,
            parameter_model_value={
                'accountpayment': 'model.due_amount',
                'format_value': 'format_number({}, locale="id_ID")',
            }
        ),
        StreamlinedCommunicationParameterList(
            parameter_name='{{sms_due_date}}',
            description='format = d mmm yyyy',
            platform=CommunicationPlatform.SMS,
            parameter_model_value={
                'accountpayment': 'model.due_date',
                'format_value': 'format_date({}, "d MMM yyyy", locale="id_ID")',
            }
        ),
        StreamlinedCommunicationParameterList(
            parameter_name='{{sms_due_date_short}}',
            description='format = d-mmm',
            platform=CommunicationPlatform.SMS,
            parameter_model_value={
                'accountpayment': 'model.due_date',
                'format_value': 'format_date({}, "d-MMM", locale="id_ID")',
            }
        ),
        StreamlinedCommunicationParameterList(
            parameter_name='{{sms_primary_va_number}}',
            description='Should be the va number for '
                        'ops.payment_method.is_primary = True',
            platform=CommunicationPlatform.SMS,
            parameter_model_value={
                'accountpayment': 'model.account.customer.primary_va_number',
                'application': 'model.customer.primary_va_number',
            }
        ),
        StreamlinedCommunicationParameterList(
            parameter_name='{{sms_primary_va_name}}',
            description='Should be the va name '
                        'for ops.payment_method.is_primary = True',
            platform=CommunicationPlatform.SMS,
            parameter_model_value={
                'accountpayment': 'model.account.customer.primary_va_name',
                'application': 'model.customer.primary_va_name',
            }
        ),
        StreamlinedCommunicationParameterList(
            parameter_name='{{sms_payment_details_url}}',
            description='remove the https part to '
                        'shorten the characters used',
            platform=CommunicationPlatform.SMS,
        ),
        StreamlinedCommunicationParameterList(
            parameter_name='{{sms_title}}',
            description='Pria = Bpk Wanita = Ibu',
            platform=CommunicationPlatform.SMS,
            parameter_model_value={
                'accountpayment': 'model.account.customer.bpk_ibu',
                'application': 'model.customer.bpk_ibu',
            }
        ),
        StreamlinedCommunicationParameterList(
            parameter_name='{{sms_firstname}}',
            description='Only takes customer first name '
                        'and using pascal format',
            platform=CommunicationPlatform.SMS,
            parameter_model_value={
                'accountpayment': 'model.account.customer.first_name_only',
                'application': 'model.customer.first_name_only',
            }
        ),
        StreamlinedCommunicationParameterList(
            parameter_name='{{sms_fullname}}',
            description='Using pascal format',
            platform=CommunicationPlatform.SMS,
            parameter_model_value={
                'accountpayment': 'model.account.customer.fullname.title()',
                'application': 'model.customer.fullname.title()',
            }
        ),
    ]
    StreamlinedCommunicationParameterList.objects.bulk_create(data_seeds)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            add_new_parameter_for_sms,
            migrations.RunPython.noop)
    ]
