# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-05-24 09:45
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst


def add_grab_feature_settings(apps, _schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.GRAB_STOP_REGISTRATION,
        is_active=True,
        description="Grab Registeration - On/Off Grab customer Registeration",
        category='grab'
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_grab_feature_settings, migrations.RunPython.noop)
    ]
