# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-06-06 22:32
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst


def add_cashback_expired_feature_settings(apps, schema_editor):
    FeatureSetting.objects.get_or_create(
        is_active=True,
        feature_name=FeatureNameConst.CASHBACK_EXPIRED_CONFIGURATION,
        category='cashback setting',
        parameters={
            'months': 24
        },
        description='cashback expired months configuration'
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_cashback_expired_feature_settings,
                             migrations.RunPython.noop)
    ]
