# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-05-20 08:20
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.loan.constants import LoanJuloOneConstant


def add_feature_setting_to_block_specific_android_id(apps, schema_editor):
    list_of_android_id = [
        '84f4f582c251a0b3',
        '8582e27e013de64a',
        'c8eea41d8b8c86f6',
        '48f1a2a57cd33caa',
        'a063b169521f4e89',
    ]

    blacklist_android_id = {
        'blacklist_android_id': list_of_android_id
    }

    FeatureSetting.objects.create(
        feature_name=LoanJuloOneConstant.ANDRROID_ID_BLACKLIST,
        parameters=blacklist_android_id,
        is_active=True,
        description='block specific android id',
        category='security issue'
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            add_feature_setting_to_block_specific_android_id, migrations.RunPython.noop),
    ]
