# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-05-20 08:20
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.loan.constants import LoanJuloOneConstant


def add_feature_setting_to_block_intelix_traffic(apps, schema_editor):

    FeatureSetting.objects.create(
        feature_name='block_traffic_intelix',
        is_active=True,
        description='block 50% traffic intelix',
        category='intelix'
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            add_feature_setting_to_block_intelix_traffic, migrations.RunPython.noop),
    ]
