# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-06-22 07:00
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import MobileFeatureSetting, FeatureSetting
from juloserver.otp.constants import SessionTokenAction, SessionTokenType


def update_otp_feature_setting(apps, schema_editor):
    MobileFeatureSetting.objects.filter(feature_name='mobile_phone_1_otp').update(
        parameters={
            'wait_time_seconds': 660,
            'otp_max_request': 6,
            'otp_resend_time_sms': 60,
            'otp_resend_time_miscall': 30,
            'otp_max_validate': 6
        }
    )


def add_feature_setting_for_otp_action_type(apps, schema_editor):
    FeatureSetting.objects.create(
        feature_name='otp_action_type',
        is_active=True,
        parameters={
            SessionTokenAction.LOGIN: SessionTokenType.SHORT_LIVED,
            SessionTokenAction.CASHBACK_BANK_TRANSFER: SessionTokenType.SHORT_LIVED,
            SessionTokenAction.CASHBACK_SEPULSA: SessionTokenType.SHORT_LIVED,
            SessionTokenAction.CASHBACK_GOPAY: SessionTokenType.SHORT_LIVED,
            SessionTokenAction.CASHBACK_PAYMENT: SessionTokenType.SHORT_LIVED,
            SessionTokenAction.VERIFY_PHONE_NUMBER: SessionTokenType.LONG_LIVED,
            SessionTokenAction.ADD_BANK_ACCOUNT_DESTINATION: SessionTokenType.LONG_LIVED
        }
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            update_otp_feature_setting, migrations.RunPython.noop),
        migrations.RunPython(
            add_feature_setting_for_otp_action_type, migrations.RunPython.noop),
    ]
