# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-06-29 04:20
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst


def create_feature_setting(apps, schema_editor):
    FeatureSetting.objects.get_or_create(
        is_active=True,
        feature_name=FeatureNameConst.E_COMMERCE_LIMIT_TRANSACTION,
        description="configuration for e commerce limit transaction ",
        parameters=100000,
        category='e_commerce_limit_transaction'
    )

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
