# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-06-29 17:04
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import MobileFeatureSetting


def add_430_refinancing_on_bad_payment(apps, _schema_editor):
    mobilefeaturesetting = MobileFeatureSetting.objects.filter(
        feature_name="bad_payment_message_setting", is_active=True
    ).last()
    if mobilefeaturesetting:
        mobilefeaturesetting.parameters['430 Refinancing'] = {
            "title": "Halo",
            "content": "Limit Anda telah terblokir karena restrukturasi pinjaman. \n"
                       "Bayar semua pinjaman yang telah di restrukturasi dan "
                       "setelah beberapa saat Anda dapat menggunakan limit Anda kembali",
            "button_text": None,
            "button_action": None
        }
        mobilefeaturesetting.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_430_refinancing_on_bad_payment, migrations.RunPython.noop)
    ]
