# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-07-06 10:23
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def add_feature_setting_to_trigger_disbursement_step_1_non_cash(apps, schema_editor):
    FeatureSetting.objects.get_or_create(
        feature_name=FeatureNameConst.DISBURSEMENT_STEP_1_NON_CASH,
        is_active=False,
        description='Trigger disbursement step 1 for non cash transaction '
                    'https://juloprojects.atlassian.net/browse/ENH-1270',
        category='disbursement'
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            add_feature_setting_to_trigger_disbursement_step_1_non_cash, migrations.RunPython.noop),
    ]
