# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-07-19 08:51
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst
from juloserver.face_recognition.models import FaceCollection

def add_face_recognition_configuration(apps, schema_editor):
    
    face_recognition_settings = {
        "max_retry_count": 3,
        "aws_settings":{
            "attributes":["ALL"],
            "quality_filter":"LOW",
            "max_faces":10,
            "face_match_threshold":75,
            "face_comparison_threshold":80
        },
        "face_recognition_settings":{
            "allowed_faces":2,
            "brightness_threshold": 50,
            "sharpness_threshold": 50,
            "crop_padding":0.15,
            "image_dimensions":640,
            "similarity_threshold":80,
            "max_face_matches":4
        }
    }

    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.FACE_RECOGNITION,
        parameters=face_recognition_settings,
        is_active=True,
        description='face recognition config with juloface params',
        category='face recognition config'
    )

    FaceCollection.objects.create(
        face_collection_name="x105",
        status="active"
    )

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            add_face_recognition_configuration, migrations.RunPython.noop),
    ]

