# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-07-19 07:07
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting


def add_fraud_hotspot_list(apps, schema_editor):
    FeatureSetting.objects.create(
        feature_name='fraud_hotspot',
        is_active=True,
        parameters={
            'hotspots': [
                (3.7, 98.65, 1),  # Hari Baskoro Syndicate
                (-3.25, 105.31, 10),  # Ogan Komering Ilir Syndicate
                (-3.42, 105.56, 5)  # Cengal Syndicate
            ]
        },
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_fraud_hotspot_list, migrations.RunPython.noop)
    ]
