# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-07-29 14:58
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import ReferralSystem


def create_referral_system_extra_data(apps, _schema_editor):
    referral_system = ReferralSystem.objects.filter(name='PromoReferral').first()
    if referral_system:
        referral_system.extra_data = {
            "content": {
                "body": "Undang temanmu pakai JULO sekarang, yuk! Dapatkan cashback <b>{}</b> "
                        "untuk setiap satu teman yang kamu ajak pakai JULO. Gunakan kode referal "
                        "di atas!",
                "terms": "Syarat dan Ketentuan:<ul><li>Sudah melakukan transaksi di aplikasi JULO "
                         "minimal 1 kali</li><li>Berlaku jika temanmu belum pernah disetujui "
                         "pinjamannya di JULO</li><li>Pastikan temanmu memasukkan kode referal "
                         "pada kolom kode referal di formulir aplikasi JULO bagian "
                         "\"Keuangan\"</li><li>Kamu akan mendapatkan cashback {} setiap kredit "
                         "limit teman Anda disetujui</li><li>Cashback berlaku "
                         "kelipatan</li></ul>Syarat dan ketentuan promo ini merupakan bagian "
                         "yang tidak terpisahkan dari Syarat dan ketentuan JULO, dan dapat "
                         "berubah sewaktu-waktu tanpa pemberitahuan.",
                "footer": "Untuk penjelasan lebih lengkap nya kamu bisa melihat Syarat "
                          "dan Ketentuan",
                "header": "Undang Teman, Dapat Cashback",
                "message": "Hai, aku mau berbagi pengalaman seru nih! Aku baru aja menggunakan "
                           "aplikasi kredit digital JULO dan menemukan solusi dari berbagai "
                           "masalah keuanganku. Ikutan yuk, kamu bisa dapetin cashback {} "
                           "dengan kode {} atau klik link https://go.onelink.me/zOQD/Referral. "
                           "JULO sudah Berizin dan Terdaftar OJK, lho. Seru, kan? Yuk download "
                           "JULO sekarang!"
            }
        }
        referral_system.referee_cashback_amount = 20000
        referral_system.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_referral_system_extra_data, migrations.RunPython.noop),
    ]

