# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-05-11 02:29

from django.db import migrations

from juloserver.api_token.models import ExpiryToken

from juloserver.grab.models import GrabCustomerData


def retroload_never_expiry_token(apps, _schema_editor):
    #grab
    grab_user_ids = GrabCustomerData.objects.filter(customer_id__isnull=False) \
    .values_list('customer__user_id', flat=True)

    ExpiryToken.objects.filter(
        user_id__in=grab_user_ids,
        is_never_expire=False
    ).update(is_never_expire=True)

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(retroload_never_expiry_token, migrations.RunPython.noop),
    ]
