# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-07-26 16:10
from __future__ import unicode_literals

from django.db import migrations
from juloserver.face_recognition.models import FaceCollection


def add_face_recognition_collection_one(apps, schema_editor):
    FaceCollection.objects.create(
        face_collection_name="fraud_flagged",
        status="active"
    )

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            add_face_recognition_collection_one, migrations.RunPython.noop),
    ]
