# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-08-01 11:42
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst


def add_feature_setting_for_autodialer_logic(apps, schema_editor):
    FeatureSetting.objects.get_or_create(
        is_active=False,
        feature_name=FeatureNameConst.AUTODIALER_LOGIC,
        category="autodialer",
        description="Feature Setting for turning the autodialer logic on/off"
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_feature_setting_for_autodialer_logic,
                             migrations.RunPython.noop)
    ]
