# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-08-05 07:22
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.management.commands import update_status_lookups
from juloserver.julo.models import StatusLookup


def create_julo_one_loan_status_lookup(apps, schema_editor):
    status_lookups = [
        # Loan status
        (241, "Halt"),
    ]

    for status_code, status in status_lookups:
        status_lookup = StatusLookup.objects.filter(status_code=status_code).first()
        if not status_lookup:
            StatusLookup.objects.create(status_code=status_code, status=status)


def update_julo_one_loan_status_lookup(apps, schema_editor):
    update_status_lookups.Command().handle()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_julo_one_loan_status_lookup,
            migrations.RunPython.noop),
        migrations.RunPython(update_julo_one_loan_status_lookup,
            migrations.RunPython.noop),
    ]
