# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-08-15 15:53
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FrontendView


def create_new_labels(apps, schema_editor):
    data_to_be_loaded = [
        {
            'label_name': 'Total pinjaman sejak didirikan',
            'label_value': 'Rp. 2,44 T'
        },
        {
            'label_name': 'Total pinjaman tahun ini',
            'label_value': 'Rp. 1.06 T'
        },
        {
            'label_name': 'Total pinjaman outstanding',
            'label_value': 'Rp. 401 M'
        },
        {
            'label_name': 'Total peminjam',
            'label_value': '337 Rb'
        },
        {
            'label_name': 'Total peminjam aktif',
            'label_value': '104 Rb'
        },
    ]

    for data in data_to_be_loaded:
        FrontendView.objects.create(
            label_name=data['label_name'],
            label_value=data['label_value']
        )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_new_labels, migrations.RunPython.noop)
    ]
