# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-08-08 19:57
from __future__ import unicode_literals
from juloserver.julo.constants import FeatureNameConst

from django.db import migrations


def create_bonza_feature_setting(apps, schema_editor):
    FeatureSetting = apps.get_model("julo", "FeatureSetting")
    FeatureSetting.objects.get_or_create(
        is_active=True, feature_name=FeatureNameConst.BONZA_LOAN_SCORING,
        category="fraud_score", parameters={},
        description="Bonza Loan Scoring Feature")


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_bonza_feature_setting, migrations.RunPython.noop)
    ]
