# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-09-06 07:07
from __future__ import unicode_literals

from builtins import str
from builtins import object
from django.db import migrations
from juloserver.julo.statuses import ApplicationStatusCodes, LoanStatusCodes
from juloserver.julo.utils import upload_file_to_oss
from juloserver.streamlined_communication.models import (InfoCardButtonProperty,
                                                         CardProperty,
                                                         InfoCardProperty,
                                                         StreamlinedMessage,
                                                         StreamlinedCommunication)
from juloserver.streamlined_communication.constant import CommunicationPlatform
from juloserver.julo.models import StatusLookup, Image
from juloserver.streamlined_communication.services import create_and_upload_image_assets_for_streamlined
from django.conf import settings
R_BUTTON = 'R.BUTTON'


class ImageNames(object):
    INAPP_BACKGROUND = 'info-card/inapp_background.png'
    INAPP_BUTTON = 'info-card/inapp_button.png'
    INAPP_ICON = 'info-card/inapp_side_image.png'


def create_image(image_source_id, image_type, image_url):
    image = Image()
    image.image_source = image_source_id
    image.image_type = image_type
    image.url = image_url
    image.save()


def retroload_cards_data_in_app_callback(_apps, _schema_editor):
    data_to_be_loaded = [
        {
            'additional_condition': CardProperty.ELIGIBLE_FOR_INAPP_CALLBACK,
            'title': 'Yuk, tentukan waktu telepon',
            'content': 'Tentukan waktu yang tepat agar JULO bisa menghubungimu',
            'button': ["Atur Waktu Telepon"],
            'button_name': [R_BUTTON],
            'click_to': ["in_app_callback"],
            'card_number': 1,
            'text_colour': '#ffffff',
            'title_colour': '#ffffff',
            'background_url': ImageNames.INAPP_BACKGROUND,
            'additional_images': [ImageNames.INAPP_ICON],
            'button_url': [ImageNames.INAPP_BUTTON]
        },
        {
            'additional_condition': CardProperty.INAPP_CALLBACK_ALREADY_FILLED,
            'title': 'Terima kasih, sudah atur waktu telepon',
            'content': 'Kami akan menelpon kamu di Jam {{selected_time_slot_start}}, '
                       'sesuai dengan waktu yang kamu pilih',
            'button': [],
            'button_name': [],
            'click_to': [],
            'card_number': 1,
            'text_colour': '#ffffff',
            'title_colour': '#ffffff',
            'background_url': ImageNames.INAPP_BACKGROUND,
            'additional_images': [ImageNames.INAPP_ICON],
            'button_url': []
        },
    ]
    for data in data_to_be_loaded:
        info_card_properties = {
            'card_type': '1',
            'title': data['title'],
            'title_color': data['title_colour'],
            'text_color': data['text_colour'],
            'card_order_number': data['card_number']
        }
        info_card = InfoCardProperty.objects.create(**info_card_properties)

        button_info_card = dict()
        if data['button']:
            for idx, image_url in enumerate(data['button']):
                button_info_card['info_card_property'] = info_card
                button_info_card['text'] = data['button'][idx]
                button_info_card['button_name'] = data['button_name'][idx]
                button_info_card['action_type'] = CardProperty.APP_DEEPLINK
                button_info_card['destination'] = data['click_to'][idx]
                button_info_card['text_color'] = data['text_colour']
                button, _ = InfoCardButtonProperty.objects.get_or_create(**button_info_card)
                create_image(button.id, CardProperty.IMAGE_TYPE.button_background_image, data['button_url'][idx])

        data_streamlined_message = {'message_content': data['content'],
                                    'info_card_property': info_card}
        message = StreamlinedMessage.objects.create(**data_streamlined_message)
        # status = StatusLookup.objects.filter(status_code=data['status']).last()
        data_for_streamlined_comms = {
            'status_code': None,
            'status': None,
            'communication_platform': CommunicationPlatform.INFO_CARD,
            'message': message,
            'description': 'retroload_inapp_callback',
            'is_active': True,
            'extra_conditions': data['additional_condition']}
        streamlined_communication = StreamlinedCommunication.objects.create(
            **data_for_streamlined_comms)
        # create image for background
        if data['background_url']:
            create_image(
                info_card.id,
                CardProperty.IMAGE_TYPE.card_background_image, data['background_url'])

        if data['additional_images']:
            additional_image_url = data['additional_images']
            additional_image_url = additional_image_url[0]
            create_image(info_card.id, CardProperty.IMAGE_TYPE.card_optional_image, str(additional_image_url))

    # upload image
    images_list = (
        'inapp_background.png',
        'inapp_button.png',
        'inapp_side_image.png',
    )
    for image_name in images_list:
        remote_path = 'info-card/{}'.format(image_name)
        upload_file_to_oss(
            settings.OSS_PUBLIC_ASSETS_BUCKET,
            settings.STATICFILES_DIRS[0] + '/images/info_card/{}'.format(image_name),
            remote_path
        )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(retroload_cards_data_in_app_callback, migrations.RunPython.noop)
    ]
