# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-09-22 09:24
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import Workflow, WorkflowStatusPath, WorkflowStatusNode, ProductLine


def add_workflow_grab(apps, _schema_editor):

    workflow = Workflow.objects.filter(name='GrabWorkflow').last()
    # WorkflowStatusPath
    WorkflowStatusPath.objects.get_or_create(
        status_previous=130,
        status_next=135,
        type="graveyard",
        workflow=workflow
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_workflow_grab, migrations.RunPython.noop),
    ]
