# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-08-30 08:35
from __future__ import unicode_literals
from juloserver.julo.constants import FeatureNameConst

from django.db import migrations
from juloserver.julo.models import FeatureSetting

def add_feature_settings_campaign_190(app, schema_editor):
    FeatureSetting.objects.get_or_create(
        feature_name=FeatureNameConst.CAMPAIGN_190_SETTINGS,
        is_active=True,
        parameters={
            # these two are testing values, should be changed for production
            'start_date': '2021-08-30',
            'end_date' : '2021-09-21'
        },
        description="Customizable start and end dates for this campaign_190"
    )

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_feature_settings_campaign_190, migrations.RunPython.noop)
    ]
