# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-09-02 06:31
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def add_in_app_callback_feature_setting(apps, schema_editor):
    FeatureSetting.objects.get_or_create(
        is_active=True,
        feature_name=FeatureNameConst.IN_APP_CALLBACK_SETTING,
        parameters={
            'eligible_buckets': [],
            'miss_days_threshold': 3
        },
        category="collection",
        description="Feature Setting for turning determine "
                    "eligible bucket for in app callback"
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            add_in_app_callback_feature_setting, migrations.RunPython.noop)
    ]
