# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-09-07 09:24
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting

def update_feature_setting_otp_transaction_flow(apps, schema_editor):
    feature_setting, created = FeatureSetting.objects.get_or_create(feature_name='otp_action_type')
    parameters = feature_setting.parameters or {}
    parameters.update({
        "transaction_self": "long_lived",
        "transaction_other": "long_lived",
        "transaction_listrik_pln": "long_lived",
        "transaction_pulsa_dan_data": "long_lived",
        "transaction_ecommerce": "long_lived",
        "transaction_dompet_digital": "long_lived",
        "transaction_bpjs_kesehatan": "long_lived",
        "transaction_pasca_bayar": "long_lived",
        "transaction_qris": "long_lived",
    })
    feature_setting.parameters = parameters
    feature_setting.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            update_feature_setting_otp_transaction_flow, migrations.RunPython.noop),
    ]
