# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-09-22 16:51
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst

from juloserver.julo.models import FeatureSetting


def add_magic_link_expiry_feature_settings(apps, schema_editor):
    FeatureSetting.objects.get_or_create(is_active=True,
                                         feature_name=FeatureNameConst.MAGIC_LINK_EXPIRY_TIME,
                                         category="agent",
                                         parameters=60,
                                         description="Magic link expiry time in minutes")


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_magic_link_expiry_feature_settings,
                             migrations.RunPython.noop)
    ]
