# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-09-22 12:08
from __future__ import unicode_literals

from django.db import migrations

from juloserver.application_flow.handlers import MerchantFinancing120Handler
from juloserver.julo.constants import WorkflowConst
from juloserver.julo.models import Workflow, WorkflowStatusNode


def create_workflow_status_node_merchant_financing_120_handler(apps, _schema_editor):
    workflow = Workflow.objects.get(name=WorkflowConst.MERCHANT_FINANCING_WORKFLOW)
    WorkflowStatusNode.objects.get_or_create(
        status_node=120,
        handler=MerchantFinancing120Handler.__name__,
        workflow=workflow
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_workflow_status_node_merchant_financing_120_handler, migrations.RunPython.noop),
    ]
