# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-08-08 19:57
from __future__ import unicode_literals
from juloserver.streamlined_communication.models import StreamlinedMessage
from django.db import migrations


def fix_html_content_for_ptp_emails(apps, schema_editor):
    template_codes = ('email_reminder_ptp_j1_agreed', 'email_reminder_ptp_mtl_agreed', 'email_reminder_ptp_j1_-2',
                      'email_reminder_ptp_mtl_-2', 'email_reminder_ptp_j1_0', 'email_reminder_ptp_0')
    messages = StreamlinedMessage.objects.filter(
        streamlinedcommunication__template_code__in=template_codes).distinct('id')
    for message in messages:
        message_content = message.message_content.replace('©', 'Copyright ')
        message.message_content = message_content
        message.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(fix_html_content_for_ptp_emails, migrations.RunPython.noop)
    ]
