# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-10-11 08:54
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting
from juloserver.sales_ops.constants import SalesOpsSettingConst

SETTING_PARAMETER = {
    SalesOpsSettingConst.RECENCY_PERCENTAGES: '20,20,20,20,20',
    SalesOpsSettingConst.MONETARY_PERCENTAGES: '20,20,20,20,20',
    SalesOpsSettingConst.LINEUP_MIN_AVAILABLE_LIMIT: 500000,
}


def init_sales_ops_feature_setting(app, schema_editor):
    data_create = {
        'feature_name': FeatureNameConst.SALES_OPS,
        'is_active': True,
        'category': 'Sales Ops',
        'parameters': SETTING_PARAMETER,
    }
    feature_setting = FeatureSetting.objects.get_or_none(feature_name=FeatureNameConst.SALES_OPS)
    if feature_setting:
        feature_setting.update_safely(**data_create)
    else:
        FeatureSetting.objects.create(**data_create)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(init_sales_ops_feature_setting, migrations.RunPython.noop),
    ]
