# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-10-11 03:30
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import MobileFeatureSetting


def update_ocr_feature_setting(apps, _schema_editor):
    open_cv_feature = MobileFeatureSetting.objects.filter(
        feature_name='opencv_setting').last()
    open_cv_feature.update_safely(feature_name='ocr_opencv_setting')


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(update_ocr_feature_setting, migrations.RunPython.noop),
    ]
