# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-10-06 02:39
from __future__ import unicode_literals

from django.db import migrations
from juloserver.followthemoney.constants import LenderTransactionTypeConst
from juloserver.followthemoney.models import LenderTransactionType


def add_lender_transaction_type_data(apps, schema_editor):
    LenderTransactionType.objects.bulk_create(
        [
            LenderTransactionType(transaction_type=LenderTransactionTypeConst.CHANNELING),
            LenderTransactionType(transaction_type=LenderTransactionTypeConst.CHANNELING_BUYBACK),
        ]
    )

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_lender_transaction_type_data)
    ]
