# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-10-12 06:41
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import Group, User

from juloserver.application_flow.constants import PartnerNameConstant
from juloserver.julo.models import Partner


def create_j1_partner(apps, schema_editor):
    group = Group.objects.get(name="julo_partners")

    user = User.objects.create(username=PartnerNameConstant.J1, email='cs@j1.co.id')
    user.groups.add(group)

    Partner.objects.create(
        user=user,
        name=PartnerNameConstant.J1,
        email='cs@j1.co.id',
        phone='+628111111111',
        type='referrer',
        company_name='J1',
        company_address='Jl. Iskandarsyah Raya, RT.3/RW.1, Melawai, Kec. Kby. Baru, '
                        'Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12160',
        business_type='Fintech Aggregator',
        is_active=True
    )


def create_99usahaku_partner(apps, schema_editor):
    group = Group.objects.get(name="julo_partners")

    user = User.objects.create(username=PartnerNameConstant.USAHAKU99, email='cs@99usahaku.com')
    user.groups.add(group)

    Partner.objects.create(
        user=user,
        name=PartnerNameConstant.USAHAKU99,
        email='cs@99ushaku.com',
        phone='+628111111111',
        type='referrer',
        company_name='99usahaku',
        company_address='Jl. Tomang Raya No. 38, Jatipulo Palmerah, West Jakarta 11430',
        business_type='Fintech Aggregator',
        is_active=True
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_j1_partner, migrations.RunPython.noop),
        migrations.RunPython(create_99usahaku_partner, migrations.RunPython.noop),
    ]
