# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-11-24 19:17
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst


def create_feature_setting(apps, schema_editor):
    FeatureSetting.objects.get_or_create(
        is_active=True,
        feature_name=FeatureNameConst.PARTNER_ELIGIBLE_USE_J1,
        description="list of partner id eligible to use rentee",
        parameters={
            "partners": {
                'name': "cashbac",
                'is_active': True
            }
        },
        category='whitelabel_paylater'
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_feature_setting),
    ]
