# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-11-23 04:41
from __future__ import unicode_literals

from django.db import migrations

from juloserver.collection_vendor.models import SubBucket
from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def add_feature_setting_for_b4_threshold(apps, schema_editor):
    FeatureSetting.objects.get_or_create(
        is_active=True,
        feature_name=FeatureNameConst.B4_EXPIRED_THRESHOLD,
        category="collection",
        parameters={
            'expired_in_days': 19
        },
        description="for determine how long account belongs to b4 vendor")

    SubBucket.objects.create(bucket=4, start_dpd=71, end_dpd=90)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_feature_setting_for_b4_threshold, migrations.RunPython.noop)
    ]
