# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-11-29 07:44
from __future__ import unicode_literals

from django.db import migrations

from juloserver.merchant_financing.handlers import MerchantFinancing190Handler
from juloserver.julo.constants import WorkflowConst
from juloserver.julo.models import Workflow, WorkflowStatusNode
from juloserver.julo.constants import ApplicationStatusCodes


def create_workflow_status_node_merchant_financing_190_handler(apps, _schema_editor):
    workflow = Workflow.objects.get(name=WorkflowConst.MERCHANT_FINANCING_WORKFLOW)
    WorkflowStatusNode.objects.get_or_create(
        status_node=ApplicationStatusCodes.LOC_APPROVED,
        handler=MerchantFinancing190Handler.__name__,
        workflow=workflow
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_workflow_status_node_merchant_financing_190_handler,
                             migrations.RunPython.noop),
    ]
