# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-12-13 08:08
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst


def create_daily_disbursement_limit_feature(apps, _schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.DAILY_DISBURSEMENT_LIMIT,
        parameters={
            "amount": 2000000000,
            "message": "Akun Anda sedang dalam perbaikkan",
            "pgood": 0.85,
        },
        is_active=False,
        category="disbursement",
        description="Daily disbursement limit"
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_daily_disbursement_limit_feature, migrations.RunPython.noop),
    ]
