# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-12-16 05:08
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def add_feature_setting_efishery_report(apps, schema_editor):
    FeatureSetting.objects.get_or_create(
        is_active=False,
        feature_name=FeatureNameConst.SEND_EMAIL_EFISHERY_ACCOUNT_PAYMENTS_REPORT,
        category="partner",
        parameters={
            'email_cc': ["lutfie.rismawan@efishery.com",
                         "ganda.nugraha@efishery.com",
                         "rizki.ardiansyah@efishery.com"],
            'email_to': ["israbalthazar@julo.co.id",
                         "farandi@julo.co.id",
                         "james.salim@julo.co.id",
                         "finance@julofinance.com",
                         "salsabila.yulianti@julo.co.id",
                         "ray.anjasta@julo.co.id"],
            'dpd': -3
        },
        description="for send email efishery account payment report")


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_feature_setting_efishery_report, migrations.RunPython.noop)
    ]
