# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-12-22 05:27
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst
from juloserver.loan.constants import LoanJuloOneConstant


def loan_duration_default_index(apps, _schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.LOAN_DURATION_DEFAULT_INDEX,
        is_active=False,
        parameters={FeatureNameConst.LOAN_DURATION_DEFAULT_INDEX: LoanJuloOneConstant.LOAN_DURATION_DEFAULT_INDEX},
        category='Loan',
        description='* Default index for loan duration'
    )


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunPython(loan_duration_default_index, migrations.RunPython.noop),
    ]
