# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-12-22 10:21
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst


def create_feature_settings_bss_channeling(apps, _schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.BSS_CHANNELING_RETRY,
        parameters={
            "max_retry_count": 2,
            "minutes": 5,
        },
        is_active=False,
        category="disbursement",
        description="Channeling Loan Retry"
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_feature_settings_bss_channeling, migrations.RunPython.noop),
    ]
