# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-01-11 05:19
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst
from juloserver.application_flow.constants import PartnerNameConstant
from juloserver.julo.partners import PartnerConstant


def add_enhancement_web_app_score_generation_settings(apps, schema_editor):
    FeatureSetting.objects.get_or_create(
        is_active=True,
        feature_name=FeatureNameConst.LEAD_GEN_PARTNER_CREDIT_SCORE_GENERATION,
        category="Partner Lead Gen",
        parameters={'partners': [
            PartnerNameConstant.CERMATI, PartnerConstant.RENTEE,
            PartnerNameConstant.OLX, PartnerNameConstant.CEKAJA,
            PartnerNameConstant.USAHAKU99, PartnerNameConstant.J1
        ]},
        description="List of partners"
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_enhancement_web_app_score_generation_settings, migrations.RunPython.noop)

    ]
