# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-01-04 08:55
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst


def create_new_feature_setting(apps, schema_editor):
    FeatureSetting.objects.get_or_create(
        is_active=False,
        feature_name=FeatureNameConst.LIVENESS_DETECTION_ANDROID_LICENSE,
        category="Temporary",
        parameters=None,
        description="The innovatrics license for android app"
    )


def update_feature_setting(apps, schema_editor):
    feature_setting = FeatureSetting.objects.get(
        feature_name=FeatureNameConst.LIVENESS_DETECTION,
    )
    parameters = feature_setting.parameters
    parameters['app_version_to_skip'] = ''
    feature_setting.parameters = parameters
    feature_setting.save()


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_new_feature_setting, migrations.RunPython.noop),
        migrations.RunPython(update_feature_setting, migrations.RunPython.noop),
    ]
