# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-01-04 04:05
from __future__ import unicode_literals

from django.db import migrations

from juloserver.autodebet.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def create_feature_settings_autodebet_bri(apps, _schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.AUTODEBET_BRI,
        parameters={"minimum_amount": 10000},
        is_active=False,
        category="collections",
        description="autodebet_bri"
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_feature_settings_autodebet_bri, migrations.RunPython.noop),
    ]
