# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-02-16 04:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations

from juloserver.julo.models import MobileFeatureSetting
from juloserver.payment_point.constants import FeatureNameConst
from juloserver.payment_point.models import TransactionMethod
from juloserver.loan.constants import LoanJuloOneConstant


BUCKET_URL = settings.STATIC_URL + 'images/transaction_methods/'
TRX_METHOD_ID= 10


def data_seed_for_transaction_method(app, schema_editor):
    TransactionMethod.objects.get_or_create(
        id=TRX_METHOD_ID,
        method='credit_card',
        fe_display_name='Kartu JULO',
        background_icon_url=BUCKET_URL + 'cdc_animated_back.gif',
        foreground_icon_url=BUCKET_URL + 'cdc.png',
        foreground_locked_icon_url=BUCKET_URL + 'cdc_locked.png'
    )


def feature_settings_for_transaction_method_highlight(app, schema_editor):
    mobile_feature_setting = MobileFeatureSetting.objects.filter(
        feature_name=FeatureNameConst.TRANSACTION_METHOD_HIGHLIGHT,
    ).last()
    if mobile_feature_setting:
        mobile_feature_setting.parameters[TRX_METHOD_ID] = {'is_active': False, 'limit_threshold': 0}
        mobile_feature_setting.save()


def lock_cdc_feature_mobile_setting(apps, schema_editor):
    mobile_feature_setting = MobileFeatureSetting.objects.filter(
        feature_name=LoanJuloOneConstant.PRODUCT_LOCK_FEATURE_SETTING
    ).last()
    if mobile_feature_setting:
        mobile_feature_setting.parameters[LoanJuloOneConstant.CREDIT_CARD] = \
            {'locked': True, 'app_version': '99.0.0'}
        mobile_feature_setting.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(data_seed_for_transaction_method, migrations.RunPython.noop),
        migrations.RunPython(feature_settings_for_transaction_method_highlight,
                             migrations.RunPython.noop),
        migrations.RunPython(lock_cdc_feature_mobile_setting),
    ]
