# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-02-09 04:00
from __future__ import unicode_literals

from django.db import migrations
from juloserver.streamlined_communication.constant import CommunicationPlatform
from juloserver.streamlined_communication.models import (StreamlinedCommunication, StreamlinedMessage)
from juloserver.application_flow.constants import PartnerNameConstant
from juloserver.julo.partners import PartnerConstant
from juloserver.julo.models import Partner

def add_sms_for_partner_streamlined_data(apps, schema_editor):

    data = [
        {
            'template_code': '99usahaku_sms_x105_t1',
            'product': 'j1',
            'status': '105',
            'partner_name': PartnerNameConstant.USAHAKU99,
            'partner_url': 'app.julo.co.id/99usahaku'
        },
        {
            'template_code': '99usahaku_sms_x131_t1',
            'product': 'j1',
            'status': '131',
            'partner_name': PartnerNameConstant.USAHAKU99,
            'partner_url': 'app.julo.co.id/99usahaku'
        },
        {
            'template_code': 'cekaja_sms_x105_t1',
            'product': 'j1',
            'status': '105',
            'partner_name': PartnerNameConstant.CEKAJA,
            'partner_url': 'app.julo.co.id/cekaja'
        },
        {
            'template_code': 'cekaja_sms_x131_t1',
            'product': 'j1',
            'status': '131',
            'partner_name': PartnerNameConstant.CEKAJA,
            'partner_url': 'app.julo.co.id/cekaja'
        },
        {
            'template_code': 'cermati_sms_x105_t1',
            'product': 'j1',
            'status': '105',
            'partner_name': PartnerNameConstant.CERMATI,
            'partner_url': 'app.julo.co.id/cermati'
        },
        {
            'template_code': 'cermati_sms_x131_t1',
            'product': 'j1',
            'status': '131',
            'partner_name': PartnerNameConstant.CERMATI,
            'partner_url': 'app.julo.co.id/cermati'
        },
        {
            'template_code': 'olx_sms_x105_t1',
            'product': 'j1',
            'status': '105',
            'partner_name': PartnerNameConstant.OLX,
            'partner_url': 'app.julo.co.id/olx'
        },
        {
            'template_code': 'olx_sms_x131_t1',
            'product': 'j1',
            'status': '131',
            'partner_name': PartnerNameConstant.OLX,
            'partner_url': 'app.julo.co.id/olx'
        },
        {
            'template_code': 'rentee_sms_x105_t1',
            'product': 'j1',
            'status': '105',
            'partner_name': PartnerConstant.RENTEE,
            'partner_url': 'app.julo.co.id/rentee'
        },
        {
            'template_code': 'rentee_sms_x131_t1',
            'product': 'j1',
            'status': '131',
            'partner_name': PartnerConstant.RENTEE,
            'partner_url': 'app.julo.co.id/rentee'
        },
    ]

    sms_text = {
        '105' : 'Halo {{sms_fullname}}, yuk, selesaikan proses pendaftaran melalui link ini {PARTNER_URL}',
        '131' : 'Halo {{sms_fullname}}, kamu harus upload ulang dokumen di web app JULO, silakan kilk link ini {PARTNER_URL}'
    }

    is_automated = False
    for item in data:
        sms_content = sms_text[item['status']].replace('{PARTNER_URL}', item['partner_url'])
        partner_sms_message, _ = \
            StreamlinedMessage.objects.get_or_create(
                message_content=sms_content,
                parameter="{sms_fullname}",
            )
            
        partner = Partner.objects.filter(name=item['partner_name']).last()
        StreamlinedCommunication.objects.get_or_create(
            message=partner_sms_message,
            description='send sms to partner when status changes to  {}'.format(item['status']),
            communication_platform=CommunicationPlatform.SMS,
            template_code=item['template_code'],
            product=item['product'],
            status_code_id=int(item['status']),
            is_active=True,
            type='Partner Communications',
            is_automated=is_automated,
            partner=partner
        )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_sms_for_partner_streamlined_data,
                             migrations.RunPython.noop)
    ]