# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-02-07 10:35
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def scheduled_retry_fdc_inquiry_feature_settings(apps, schema_editor):
    FeatureSetting.objects.get_or_create(
        is_active=True,
        feature_name=FeatureNameConst.SCHEDULED_RETRY_FDC_INQUIRY,
        category="fdc",
        parameters={"filter_inquiry_reasons": ["1 - Applying loan via Platform"],
                    "delay_interval_milliseconds": 1000},
        description="Configure run_fdc_for_failure_status scheduled task which run every 2 hour")


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(scheduled_retry_fdc_inquiry_feature_settings,
                             migrations.RunPython.noop)
    ]
