# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-02-25 08:42
from __future__ import unicode_literals
from builtins import range
import random
import string

from django.db import migrations
from django.utils import timezone
from django.contrib.auth.models import User
from django.forms.models import model_to_dict
from juloserver.followthemoney.models import (
    LenderCurrent,
    LenderBalanceCurrent,
    LenderBankAccount,
    LoanAgreementTemplate,
    LenderApproval,
)
from juloserver.followthemoney.constants import BankAccountType
from juloserver.julo.models import (
    ProductProfile,
    LenderDisburseCounter,
    LenderCustomerCriteria,
    LenderProductCriteria,
    Partner,
)
from juloserver.julo.constants import ProductLineCodes


def update_ska_lender(apps, schema_editor):
    ska_lender = LenderCurrent.objects.get_or_none(lender_name='ska')
    if ska_lender:
        ska_lender.update_safely(
            is_manual_lender_balance=True,
            is_master_lender=False,
            is_xfers_lender_flow=False,
            is_bss_balance_include=False,
            is_only_escrow_balance=True,
            is_low_balance_notification=True,
            minimum_balance=500000000
        )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(update_ska_lender, migrations.RunPython.noop),
    ]
