# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-02-25 05:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations

from juloserver.payment_point.models import (
    TransactionMethod,
    TransactionCategory
)


BUCKET_URL = settings.STATIC_URL + 'images/transaction_methods/'
TRX_METHOD_ID = 10


def data_seed_for_transaction_method(app, schema_editor):
    replaced_trx_method = TransactionMethod.objects.filter(order_number=7).last()
    if replaced_trx_method:
        replaced_trx_method.update_safely(order_number=10)
    
    trx_category = TransactionCategory.objects.filter(name='belanja').last()
    trx_method = TransactionMethod.objects.filter(
        id=TRX_METHOD_ID,
        method='credit_card').last()
    trx_method.update_safely(
        foreground_locked_icon_url=BUCKET_URL + 'cdc_locked_v2.png',
        foreground_icon_url=BUCKET_URL + 'cdc_v2.png',
        transaction_category=trx_category,
        order_number=7,
        method='credit card'

    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(data_seed_for_transaction_method, migrations.RunPython.noop),
    ]
