# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-03-08 09:22
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def add_feature_setting_fdc(apps, schema_editor):
    fdc_timeout, _created = FeatureSetting.objects.get_or_create(
        feature_name=FeatureNameConst.FDC_TIMEOUT,
    )
    fdc_timeout.parameters = {'0-23': 15}
    fdc_timeout.is_active = True
    fdc_timeout.description = "fdc timeout ex: {'0-10': 10, '11-23': 15}"
    fdc_timeout.category = 'fdc'
    fdc_timeout.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            add_feature_setting_fdc, migrations.RunPython.noop),
    ]
