# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-03-15 06:56
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import StatusLookup


def load_status_lookups_credit_card(apps, schema_editor):
    status_code, status = (516, 'Card Validated')

    StatusLookup.objects.create(status_code=status_code, status=status)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(load_status_lookups_credit_card),
    ]
