# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-03-14 09:12
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import Q

from juloserver.julo.models import AppVersion


def add_android_v7(apps, schema_editor):
    previous = AppVersion.objects.filter(
        Q(app_version__startswith='6.4') | Q(app_version__startswith='6.5')
    )
    previous.update(status='supported')

    if not AppVersion.objects.filter(app_version='7.0.0').exists():
        AppVersion.objects.create(
            app_version='7.0.0',
            status='latest'
        )


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            add_android_v7, migrations.RunPython.noop
        ),
    ]
