# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-03-22 08:35
from __future__ import unicode_literals

from django.db import migrations
from juloserver.streamlined_communication.models import (StreamlinedCommunication)


def update_autodebet_streamlined_comms(apps, schema_editor):
    # SMS
    message_content = "Hi JULOvers! Pastikan saldo rekeningmu minimal Rp {{sms_due_amount}}" \
                      " agar fitur BCA Auto Debit tetap bisa digunakan. Dapatkan CASHBACK 1% " \
                      "dengan pakai Auto Debit!",
    parameter = "{sms_due_amount}"
    streamlined_communication_for_sms_minus_7 = StreamlinedCommunication.objects.filter(
        template_code='j1_sms_autodebet_dpd_-7',
    ).last()
    if streamlined_communication_for_sms_minus_7:
        streamlined_message = streamlined_communication_for_sms_minus_7.message
        streamlined_message.update_safely(message_content=message_content, parameter=parameter)
        streamlined_communication_for_sms_minus_7.update_safely(extra_conditions=None)

    streamlined_communication_for_sms_minus_3 = StreamlinedCommunication.objects.filter(
        template_code='j1_sms_autodebet_dpd_-3',
    ).last()
    if streamlined_communication_for_sms_minus_3:
        streamlined_message = streamlined_communication_for_sms_minus_7.message
        streamlined_message.update_safely(message_content=message_content, parameter=parameter)
        streamlined_communication_for_sms_minus_3.update_safely(extra_conditions=None)

    streamlined_communication_for_sms_minus_1 = StreamlinedCommunication.objects.filter(
        template_code='j1_sms_autodebet_dpd_-1',
    ).last()
    if streamlined_communication_for_sms_minus_1:
        streamlined_message = streamlined_communication_for_sms_minus_7.message
        streamlined_message.update_safely(message_content=message_content, parameter=parameter)
        streamlined_communication_for_sms_minus_1.update_safely(extra_conditions=None)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            update_autodebet_streamlined_comms, migrations.RunPython.noop),
    ]
