# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-03-02 04:04
from __future__ import unicode_literals

from django.db import migrations
from juloserver.streamlined_communication.models import StreamlinedCommunication
from juloserver.streamlined_communication.constant import CommunicationPlatform
from juloserver.julo.models import Partner


def update_j1_comms_to_exlclude_all_other_comms_partners(apps, schema_editor):
    comms_qs = StreamlinedCommunication.objects.filter(
        communication_platform__in=[CommunicationPlatform.SMS, CommunicationPlatform.EMAIL, CommunicationPlatform.ROBOCALL],
        product__in=['j1', 'nexmo_j1'])
    partner_names = ['99usahaku', 'moneyduck', 'finfleet', 'cekaja', 'j1', 'rentee', 'tokopedia', 'olx', 'cermati']
    selected_partners = Partner.objects.exclude(name__in=partner_names).values_list('id', flat=True)
    for comms in comms_qs.iterator():
        comms.partner_selection_list = list(selected_partners)
        comms.save()
    comms_qs.update(partner_selection_action='exclude')


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(update_j1_comms_to_exlclude_all_other_comms_partners, migrations.RunPython.noop)
    ]
