# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-03-28 05:31
from __future__ import unicode_literals

from django.db import migrations

from django.conf import settings

from juloserver.ecommerce.constants import CategoryType
from juloserver.ecommerce.models import EcommerceConfiguration, EcommerceBankConfiguration
from juloserver.julo.models import Bank


class Migration(migrations.Migration):
    
    def add_klar_to_ecommerce_configuration(apps, _schema_editor):
        klar_config, created = EcommerceConfiguration.objects.get_or_create(
            ecommerce_name='KLAR',
        )

        base_url = settings.ECOMMERCE_LOGO_STATIC_FILE_PATH

        updated_info = {
            'selection_logo': f"{base_url}klar/klar_selection_logo.png",
            'background_logo': f"{base_url}klar/klar_background_logo.png",
            'text_logo': f"{base_url}klar/klar_text_logo.png",
            'url': "https://www.klarsmile.com/id",
            'color_scheme': '#052C3C',
            'order_number': 6,
            'category_type': CategoryType.ECOMMERCE,
        }

        klar_config.update_safely(**updated_info)
        bank = Bank.objects.filter(xfers_bank_code='BNI').last()

        EcommerceBankConfiguration.objects.get_or_create(
            ecommerce_configuration_id=klar_config.id,
            bank_id=bank.id,
            prefix=['8808640']
        )

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_klar_to_ecommerce_configuration, migrations.RunPython.noop),
    ]
