# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-03-28 08:23
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import Bank

def reorder_bank_list(apps, schema_editor):
    all_banks_obj = Bank.objects.all()
    max_position = all_banks_obj.filter(order_position__isnull=False).order_by('order_position').last().order_position
    banks_obj = all_banks_obj.filter(order_position=None).order_by('bank_name')
    current_position = max_position + 1
    for bank in banks_obj:
        bank.update_safely(order_position=current_position)
        current_position += 1


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            reorder_bank_list, migrations.RunPython.noop),
    ]

