# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-04-05 04:41
from __future__ import unicode_literals

from django.db import migrations
from juloserver.streamlined_communication.models import (InfoCardProperty,
                                                         StreamlinedMessage,
                                                         StreamlinedCommunication)
hourglass_emoji = '\U000023F3'


def update_wording(_apps, _schema_editor):
    updated_data = [
        {
            'title': 'Dalam proses verifikasi ' + hourglass_emoji,
            'filter': {
            	'extra_conditions': 'CUSTOMER_HAVE_LOW_SCORE_OR_C_WITH_DElAY'
            },
            'content': 'Data pengajuan kamu telah diterima dan sedang '
                       'dalam proses verifikasi. Silakan kembali dalam '
                       'satu hari kerja untuk memeriksa status pengajuanmu.',
        },
        {
            'title': 'Proses Verifikasi telepon 📞',
            'filter': {
            	'extra_conditions': 'CUSTOMER_HAVE_HIGH_SCORE'
            },
            'content': 'Kamu akan segera dihubungi tim JULO '
                       'untuk proses verifikasi. Pastikan telepon '
                       'kamu aktif, ya!',
        },
        {
            'title': 'Informasi',
            'filter': {
            	'template_code__in': ['card_maintenance_1', 'card_maintenance_2']
            },
            'content': 'Aplikasi sedang dalam perbaikan sistem '
                       'pencairan limit. Coba kembali dalam waktu '
                       '1x24 jam. Pastikan tetap melakukan pembayaran '
                       'dengan waktu jatuh tempo bila memiliki tagihan.',
        }
    ]

    for data in updated_data:
    	info_card_ids = InfoCardProperty.objects.filter(
    						title=data['title']).values_list(
    						'pk',flat=True)
    	message_ids = StreamlinedCommunication.objects.filter(
    					**data['filter'],
    					is_active=True
    				  ).values_list('message_id', flat=True)
    	streamlined_messages = StreamlinedMessage.objects.filter(
    							info_card_property_id__in=info_card_ids,
    							pk__in=message_ids
							   ).update(message_content=data['content'])


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(update_wording, migrations.RunPython.noop)
    ]
