# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-04-13 08:06
from __future__ import unicode_literals

from django.db import migrations
from juloserver.streamlined_communication.models import (
    StreamlinedCommunication,
    StreamlinedMessage,
)


def update_stream_lined_message(apps, schema_editor):
    stream_lined_message_content_new = """
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional //EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:v="urn:schemas-microsoft-com:vml"
        xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
    <!--[if gte mso 9]>
    <xml>
        <o:OfficeDocumentSettings>
            <o:AllowPNG/>
            <o:PixelsPerInch>96</o:PixelsPerInch>
        </o:OfficeDocumentSettings>
    </xml>
    <![endif]-->
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title></title>
    <link href="https://fonts.googleapis.com/css?family=Calibri:400,700,400italic,700italic" rel="stylesheet"
          type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">
    <style type="text/css"> body {
        margin: 0;
        padding: 0;
    }

    table, td, tr {
        vertical-align: top;
        border-collapse: collapse;
    }

    * {
        line-height: inherit;
    }

    a[x-apple-data-detectors=true] {
        color: inherit !important;
        text-decoration: none !important;
    }</style>
    <style type="text/css" id="media-query"> @media (max-width: 520px) {
        .block-grid, .col {
            min-width: 320px !important;
            max-width: 100% !important;
            display: block !important;
        }

        .block-grid {
            width: 100% !important;
        }

        .col {
            width: 100% !important;
        }

        .col_cont {
            margin: 0 auto;
        }

        img.fullwidth, img.fullwidthOnMobile {
            max-width: 100% !important;
        }

        .no-stack .col {
            min-width: 0 !important;
            display: table-cell !important;
        }

        .no-stack.two-up .col {
            width: 50% !important;
        }

        .no-stack .col.num2 {
            width: 16.6% !important;
        }

        .no-stack .col.num3 {
            width: 25% !important;
        }

        .no-stack .col.num4 {
            width: 33% !important;
        }

        .no-stack .col.num5 {
            width: 41.6% !important;
        }

        .no-stack .col.num6 {
            width: 50% !important;
        }

        .no-stack .col.num7 {
            width: 58.3% !important;
        }

        .no-stack .col.num8 {
            width: 66.6% !important;
        }

        .no-stack .col.num9 {
            width: 75% !important;
        }

        .no-stack .col.num10 {
            width: 83.3% !important;
        }

        .video-block {
            max-width: none !important;
        }

        .mobile_hide {
            min-height: 0px;
            max-height: 0px;
            max-width: 0px;
            display: none;
            overflow: hidden;
            font-size: 0px;
        }

        .desktop_hide {
            display: block !important;
            max-height: none !important;
        }
    }</style>
</head>

<body class="clean-body" style="margin:0;padding:0;-webkit-text-size-adjust:100%;background-color:#fff"><!--[if IE]>
<div class="ie-browser"><![endif]-->
<table class="nl-container"
       style="table-layout:fixed;vertical-align:top;min-width:320px;border-spacing:0;border-collapse:collapse;mso-table-lspace:0;mso-table-rspace:0;background-color:#fff;width:100%"
       cellpadding="0" cellspacing="0" role="presentation" width="100%" bgcolor="#FFFFFF" valign="top">
    <tbody>
    <tr style="vertical-align:top" valign="top">
        <td style="word-break:break-word;vertical-align:top" valign="top"><!--[if (mso)|(IE)]>
            <table width="100%" cellpadding="0" cellspacing="0" border="0">
                <tr>
                    <td align="center" style="background-color:#fff"><![endif]-->
            <div style="background-color:transparent">
                <div class="block-grid"
                     style="min-width:320px;max-width:500px;overflow-wrap:break-word;word-wrap:break-word;word-break:break-word;Margin:0 auto;background-color:transparent">
                    <div style="border-collapse:collapse;display:table;width:100%;background-color:transparent">
                        <!--[if (mso)|(IE)]>
                        <table width="100%" cellpadding="0" cellspacing="0" border="0"
                               style="background-color:transparent">
                            <tr>
                                <td align="center">
                                    <table cellpadding="0" cellspacing="0" border="0" style="width:500px">
                                        <tr class="layout-full-width" style="background-color:transparent"><![endif]-->
                        <!--[if (mso)|(IE)]>
                        <td align="center" width="500"
                            style="background-color:transparent;width:500px;border-top:0 solid transparent;border-left:0 solid transparent;border-bottom:0 solid transparent;border-right:0 solid transparent"
                            valign="top">
                            <table width="100%" cellpadding="0" cellspacing="0" border="0">
                                <tr>
                                    <td style="padding-right:10px;padding-left:10px;padding-top:10px;padding-bottom:10px">
                        <![endif]-->
                        <div class="col num12"
                             style="min-width:320px;max-width:500px;display:table-cell;vertical-align:top;width:500px">
                            <div class="col_cont" style="width:100%!important"><!--[if (!mso)&(!IE)]><!-->
                                <div style="border-top:0 solid transparent;border-left:0 solid transparent;border-bottom:0 solid transparent;border-right:0 solid transparent;padding-top:10px;padding-bottom:10px;padding-right:10px;padding-left:10px">
                                    <!--<![endif]-->
                                    <div class="img-container center autowidth autowidth" align="center"
                                         style="padding-right:0;padding-left:0"><!--[if mso]>
                                        <table width="100%" cellpadding="0" cellspacing="0" border="0">
                                            <tr style="line-height:0">
                                                <td style="padding-right:0;padding-left:0" align="center"><![endif]--><a
                                                href="https://go.onelink.me/zOQD/93d068ac" target="_blank"
                                                style="outline:0" tabindex="-1"><img class="center autowidth autowidth"
                                                                                     align="center" border="0"
                                                                                     src="https://d15k2d11r6t6rl.cloudfront.net/public/users/Integrators/f7683d20-2948-460f-8f91-a13fe519b593/64VZ60OJU965CUFQ4G2F2Q8Z/Mobile_MTL%20%26%20STL%20dpd%2B4.png"
                                                                                     alt="Image" title="Image"
                                                                                     style="text-decoration:none;-ms-interpolation-mode:bicubic;height:auto;border:0;width:100%;max-width:480px;display:block"
                                                                                     width="480"></a>
                                        <!--[if mso]><![endif]--></div><!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->
                            </div>
                        </div><!--[if (mso)|(IE)]><![endif]--><!--[if (mso)|(IE)]><![endif]--></div>
                </div>
            </div>
            <div style="background-color:transparent">
                <div class="block-grid"
                     style="min-width:320px;max-width:500px;overflow-wrap:break-word;word-wrap:break-word;word-break:break-word;Margin:0 auto;background-color:transparent">
                    <div style="border-collapse:collapse;display:table;width:100%;background-color:transparent">
                        <!--[if (mso)|(IE)]>
                        <table width="100%" cellpadding="0" cellspacing="0" border="0"
                               style="background-color:transparent">
                            <tr>
                                <td align="center">
                                    <table cellpadding="0" cellspacing="0" border="0" style="width:500px">
                                        <tr class="layout-full-width" style="background-color:transparent"><![endif]-->
                        <!--[if (mso)|(IE)]>
                        <td align="center" width="500"
                            style="background-color:transparent;width:500px;border-top:0 solid transparent;border-left:0 solid transparent;border-bottom:0 solid transparent;border-right:0 solid transparent"
                            valign="top">
                            <table width="100%" cellpadding="0" cellspacing="0" border="0">
                                <tr>
                                    <td style="padding-right:0;padding-left:0;padding-top:30px;padding-bottom:30px">
                        <![endif]-->
                        <div class="col num12"
                             style="min-width:320px;max-width:500px;display:table-cell;vertical-align:top;width:500px">
                            <div class="col_cont" style="width:100%!important"><!--[if (!mso)&(!IE)]><!-->
                                <div style="border-top:0 solid transparent;border-left:0 solid transparent;border-bottom:0 solid transparent;border-right:0 solid transparent;padding-top:30px;padding-bottom:30px;padding-right:0;padding-left:0">
                                    <!--<![endif]--><!--[if mso]>
                                    <table width="100%" cellpadding="0" cellspacing="0" border="0">
                                        <tr>
                                            <td style="padding-right:10px;padding-left:10px;padding-top:5px;padding-bottom:0;font-family:'Trebuchet MS',Tahoma,sans-serif">
                                    <![endif]-->
                                    <div style="color:#555;font-family:Montserrat,'Trebuchet MS','Lucida Grande','Lucida Sans Unicode','Lucida Sans',Tahoma,sans-serif;line-height:1.5;padding-top:5px;padding-right:10px;padding-bottom:0;padding-left:10px">
                                        <div class="txtTinyMce-wrapper"
                                             style="line-height:1.5;font-size:12px;color:#555;font-family:Montserrat,'Trebuchet MS','Lucida Grande','Lucida Sans Unicode','Lucida Sans',Tahoma,sans-serif;mso-line-height-alt:18px">
                                            <p style="margin:0;line-height:1.5;word-break:break-word;mso-line-height-alt:18px;margin-top:0;margin-bottom:0">
                                                <strong><span style="font-size:13px;mso-ansi-font-size:14px"><span
                                                        style="color:#333">Yth {{title_long}} {{full_name}}</span><span
                                                        style="color:#333">,</span></span></strong></p></div>
                                    </div><!--[if mso]><![endif]--><!--[if mso]>
                                    <table width="100%" cellpadding="0" cellspacing="0" border="0">
                                        <tr>
                                            <td style="padding-right:10px;padding-left:10px;padding-top:5px;padding-bottom:5px;font-family:'Trebuchet MS',Tahoma,sans-serif">
                                    <![endif]-->
                                    <div style="color:#000;font-family:Montserrat,'Trebuchet MS','Lucida Grande','Lucida Sans Unicode','Lucida Sans',Tahoma,sans-serif;line-height:1.5;padding-top:5px;padding-right:10px;padding-bottom:5px;padding-left:10px">
                                        <div class="txtTinyMce-wrapper letter-content"
                                             style="line-height:1.5;font-size:12px;color:#000;font-family:Montserrat,'Trebuchet MS','Lucida Grande','Lucida Sans Unicode','Lucida Sans',Tahoma,sans-serif;mso-line-height-alt:18px">
                                            <p style="margin:0;line-height:1.5;word-break:break-word;mso-line-height-alt:18px;margin-top:0;margin-bottom:0"></p>
                                            <br>
                                            <p style="margin:0;line-height:1.5;word-break:break-word;font-size:13px;mso-line-height-alt:20px;mso-ansi-font-size:14px;margin-top:0;margin-bottom:0">
                                                <span style="font-size:13px;mso-ansi-font-size:14px">Kamu telah tercatat terlambat 4 hari belum melakukan pembayaran.</span>
                                            </p>
                                            <p style="margin:0;line-height:1.5;word-break:break-word;mso-line-height-alt:18px;margin-top:0;margin-bottom:0"></p>
                                            <br>
                                            <p style="margin:0;line-height:1.5;word-break:break-word;font-size:13px;mso-line-height-alt:20px;mso-ansi-font-size:14px;margin-top:0;margin-bottom:0">
                                                <span style="font-size:13px;mso-ansi-font-size:14px"><strong>Tagihan bulan ini sejumlah: Rp {{account1_due_amount}}</strong><br>*Belum termasuk biaya keterlambatan</span>
                                            </p>
                                            <p style="margin:0;line-height:1.5;word-break:break-word;mso-line-height-alt:18px;margin-top:0;margin-bottom:0"></p>
                                            <br>
                                            <p style="margin:0;line-height:1.5;word-break:break-word;font-size:13px;mso-line-height-alt:20px;mso-ansi-font-size:14px;margin-top:0;margin-bottom:0">
                                                <span style="font-size:13px;mso-ansi-font-size:14px">Jika kamu melakukan pembayaran hari ini, maka JULO akan meniadakan biaya keterlambatan. Segera lakukan pembayaran.</span>
                                            </p>
                                            <p style="margin:0;line-height:1.5;word-break:break-word;mso-line-height-alt:18px;margin-top:0;margin-bottom:0"></p>
                                            <br>
                                            <p style="margin:0;line-height:1.5;word-break:break-word;font-size:13px;mso-line-height-alt:20px;mso-ansi-font-size:14px;margin-top:0;margin-bottom:0">
                                                <span style="font-size:13px;mso-ansi-font-size:14px">Perlu diingat, dengan kamu tidak melakukan pembayaran tunggakan pinjaman, dapat menyebabkan riwayat kredit kamu menjadi buruk, dan kamu berpotensi tercatat dalam daftar hitam Fintech Data Center (<strong>FDC</strong>), yang bergerak di bawah naungan Asosiasi Fintech Pendanaan Bersama Indonesia (<strong>AFPI</strong>) dan Otoritas Jasa Keuangan (<strong>OJK</strong>). Kami berwenang mengirim informasi kredit kamu ke Sistem Layanan Informasi Keuangan (<strong>SLIK</strong>) yang dahulu dikelola oleh Bank Indonesia (<strong>BI</strong>) Checking. Dampaknya, peluang kamu untuk mendapatkan pinjaman, administrasi keuangan, dan hal berkaitan dengan <strong>pengajuan finansial akan sangat rendah di kemudian hari</strong>.</span>
                                            </p>
                                            <p style="margin:0;line-height:1.5;word-break:break-word;mso-line-height-alt:18px;margin-top:0;margin-bottom:0"></p>
                                            <br>
                                            <p style="margin:0;line-height:1.5;word-break:break-word;font-size:13px;mso-line-height-alt:20px;mso-ansi-font-size:14px;margin-top:0;margin-bottom:0">
                                                <span style="font-size:13px;mso-ansi-font-size:14px">JULO juga akan membekukan limit kredit kamu sehingga tidak dapat digunakan sementara waktu hingga kamu melakukan pembayaran.</span>
                                            </p>
                                            <p style="margin:0;line-height:1.5;word-break:break-word;mso-line-height-alt:18px;margin-top:0;margin-bottom:0"></p>
                                            <br>
                                            <p style="margin:0;line-height:1.5;word-break:break-word;font-size:13px;mso-line-height-alt:20px;mso-ansi-font-size:14px;margin-top:0;margin-bottom:0">
                                                <span style="font-size:13px;mso-ansi-font-size:14px">Berikut informasi pembayaran:</span>
                                            </p>
                                            <p style="margin:0;line-height:1.5;word-break:break-word;font-size:13px;mso-line-height-alt:20px;mso-ansi-font-size:14px;margin-top:0;margin-bottom:0">
                                                <span style="font-size:13px;mso-ansi-font-size:14px">> Bank Tujuan: {{va_method_name}}</span>
                                            </p>
                                            <p style="margin:0;line-height:1.5;word-break:break-word;font-size:13px;mso-line-height-alt:20px;mso-ansi-font-size:14px;margin-top:0;margin-bottom:0">
                                                <span style="font-size:13px;mso-ansi-font-size:14px">> Nomor Virtual Account : {{va_number}}</span>
                                            </p>
                                            <p style="margin:0;line-height:1.5;word-break:break-word;font-size:13px;mso-line-height-alt:20px;mso-ansi-font-size:14px;margin-top:0;margin-bottom:0">
                                                <span style="font-size:13px;mso-ansi-font-size:14px">> Total yang harus dibayar : Rp {{account1_due_amount}}</span>
                                            </p>
                                            <p style="margin:0;line-height:1.5;word-break:break-word;mso-line-height-alt:18px;margin-top:0;margin-bottom:0"></p>
                                            <br>
                                            <p style="margin:0;line-height:1.5;word-break:break-word;font-size:13px;mso-line-height-alt:20px;mso-ansi-font-size:14px;margin-top:0;margin-bottom:0">
                                                <span style="font-size:13px;mso-ansi-font-size:14px">Untuk metode pembayaran lainnya, silahkan <a
                                                        href="http://link.julo.co.id/ls/click?upn=b71f3bQKJgoqZAeQsMqX-2BJRZbHM6I6VY6nhGOfL-2BMWe45KbbFQ992c9LHCUiZYbKnyMzUHUm3WmEhO-2Frvh5wuHMgFExgczyFPmk3IQJUNQz-2BHcNJb-2F1PheshMkUJo3xGEU9SLuOZTeYMzLvm2o1DLFF5Z-2Bd4mXMQ2NjqiFuaT0FiAXEPo5uetQBM4IwOSWpIm3T9TrsRCPJ-2F50eN478Q92RBikz6gWwjrFI-2BsjKQ-2BLeKVXkruiqK2TRQnGG8mouhBmRc3hrbSeWpZftDI6Sxbc1e4ZrcCYxbjnHv5YV-2FaIBMJtUshrqzPiE5tS9bqT1gVgXixA414csibh-2FG9VCtzaVAtyeGE8FalRx1VSh2dKT2HtETInge007cmiAd7paW-2BrxB8DCSije0t6aeh-2Fxt5nYhu0YiZRZUjUeLrFwFgfyQe-2FxRto1w5N-2BiJnezDfruTxMIj-2B06VGO1FAW8WjGKHA-2FUKTSrfsw7fkEJYJzVifjMF7huzONlyRVKI8yMRvEEycLo0-2FcIU9vLrAsxeux6NLpWqqGYaA1lvBAD1U-2FYS8uJfzPKB3V1e9Y3ASJ7WO-2BEBRMjFpRYDjSi3IyoizhYHb4uoKNemLktjK17k9zQV07HwfTKw5YuTTfdTW9PWciD-2FnueEaUrJhXnMkPrUjTCKhxQPWfoHWQex9x5kSMaMUCxUWYP-2BmodD4dtvmTlYJYTJGjB4A6n7oO8ClTJjkGZ0JmLiVO-2FM3bRPpkFDilYabLakZ1LFHDZ0Ludl5Kxdpf7YEQtz0CpW-2BFWtLLr-2FePBuQvMCwjAPXOvXKd-2Fyej6Gp37WcZFKtumfvZ2rRLzA8nJQ-2B9Tt7OkIP-2F-2B2VMJCLsVEue-2B-2F5VhyO-2BYNaaAtqhR2JJg5yktq11PZucEEQA8hn6ES8VyQYp7mJrzyWKbVtvTo4lt3NYkkxh0-2BqRPKrjPsOeE-2FPStGOYte3mLkB5Uzl-2BpDVMzCf1YkjmH-2BqF5Snsvy7dmQsphCpWPXEOWkH6atVHOKPtSWSvcCiKPFwL5BHHDhHnl2q3zk5JC52HRVkrp5A-3D-3DlkIt_MTQeFU9OGQYuK17CNM-2FHMJ7Fb2HmH4eyxwH7ImJgXSB3hRp-2BiwAszvutQkiAb1rH-2FOa6WSyzzhE0fm7qVvgs4-2F-2F0-2F-2BndU0DcBpBnqyQGrMtvjPI7Mzj912h88Y4JZfiBbAboimDQvJNL4k4YeWK9IiZW2ZMVsDpcvuai3ZKd6PPZptUuIIhnVl4du2tXxbUEznQPWDLaHkEyfkFor4F-2BKmcpXKIr-2B3aVsYRkkUBy4hKqto5azrVNCxud1GBJlmj-2F3f2VQYSDahjkZV5jLjOe2yUelcQMp0aL14C1pptLW29Xi5aJyR6iNqawIHoOze99fovtin86-2FGIYhdpF9SMXEqFSivFlkN3nvAj-2F0kevv5huy6jXwZdTxF5yz1kQzZaQj2Y-2BSbVlRu-2BHOerYdOporurzG22HRbx5CCBQEQlqTZrbX6qWIgMqoypggl9GlCAfx-2FCqpJaPn11oLk5vjHK1Cr0K0BMwpWlqBp1W6HybZOZyZ5SI9UTQhOmjFrzRYaIkAZwxZlcEg00zZ2-2FrH-2FvLL1Av-2FSsM0ZmS-2BXndQ0QPD7I-3D"
                                                        target="_blank" rel="noopener" style="color:#00f">cek aplikasi Julo</a>.</span>
                                            </p>
                                            <p style="margin:0;line-height:1.5;word-break:break-word;mso-line-height-alt:18px;margin-top:0;margin-bottom:0"></p>
                                            <br>
                                            <p style="margin:0;line-height:1.5;word-break:break-word;font-size:13px;mso-line-height-alt:20px;mso-ansi-font-size:14px;margin-top:0;margin-bottom:0">
                                                <span style="font-size:13px;mso-ansi-font-size:14px">Untuk informasi lebih lanjut, hubungi tim Julo melalui;</span>
                                            </p>
                                            <p style="margin:0;line-height:1.5;word-break:break-word;mso-line-height-alt:18px;margin-top:0;margin-bottom:0"></p>
                                            <br>
                                            <p style="margin:0;line-height:1.5;word-break:break-word;font-size:13px;mso-line-height-alt:20px;mso-ansi-font-size:14px;margin-top:0;margin-bottom:0">
                                                <span style="font-size:13px;mso-ansi-font-size:14px">Email - <a
                                                        href="mailto:collections@julo.co.id" target="_blank"
                                                        rel="noopener"
                                                        style="color:#00f">collections@julo.co.id</a></span></p>
                                            <p style="margin:0;line-height:1.5;word-break:break-word;font-size:13px;mso-line-height-alt:20px;mso-ansi-font-size:14px;margin-top:0;margin-bottom:0">
                                                <span style="font-size:13px;mso-ansi-font-size:14px">Layanan Telepon - <a
                                                        href="tel:02150919036" rel="noopener" style="color:#00f"
                                                        title="tel:02150919036" target="_blank">021-5091-9036</a>, <a
                                                        href="tel:02150919037" rel="noopener" style="color:#00f"
                                                        title="tel:02150919037" target="_blank">021-5091-9037</a>, atau <a
                                                        href="tel:02130433660" rel="noopener" style="color:#00f"
                                                        title="tel:02130433660"
                                                        target="_blank">021-3043-3660</a>.</span></p>
                                            <table border="0" cellpadding="10" cellspacing="0" role="presentation"
                                                   width="100%">
                                                <tbody>
                                                <tr>
                                                    <td>
                                                        <div align="center"><a
                                                                href="http://link.julo.co.id/ls/click?upn=b71f3bQKJgoqZAeQsMqX-2BJRZbHM6I6VY6nhGOfL-2BMWe45KbbFQ992c9LHCUiZYbKnyMzUHUm3WmEhO-2Frvh5wuHMgFExgczyFPmk3IQJUNQz-2BHcNJb-2F1PheshMkUJo3xGEU9SLuOZTeYMzLvm2o1DLFF5Z-2Bd4mXMQ2NjqiFuaT0FiAXEPo5uetQBM4IwOSWpIm3T9TrsRCPJ-2F50eN478Q900O-2FXmSCWpqyOTzMbqsOcsHnjDeTS68eBpItSOhADTGs4bms7CRZcSvEApRjv-2Bkoiqe-2F1awdIUL1xa7iGQhrlbXHl9ChZEbUnDPBNeVHkwOgJSHbinMOvU-2F-2BpDtUxlaGl3GFR7Idt4acEQBaFeMusDcK3cwDRi2Fz-2FIRHM-2Bhb3Y-2FujbYu4d-2FkP2ezM0ofz1eVLZJZ91n570A337WoO4iqVGsLwIWjXiFj2xRaMF7LvEgWVP7dJhTi90PJ8R-2B-2B4KCb-2BmyNL2hABnAjzQgrPV6LyX8rSj4jmcIlHBWY0Iy1oXicAbeX0DsmRgOuF3QavRGtoV2GbxG69CjTD-2BtHO6r5F0SCroQ0F-2B-2Fn4YKvKn3gxEViMu6MWmZnMiAE0OdSi3ooC4ZkY8AX6qiCXAw92uCTvhypy7fQfvXVT4SiV-2BttiASyr4Q4jxZvPialcHJykvE8ZYzdIq-2FN30tpUepHghoAStiDfZkWkKZ-2FwIfCC26xNaQSBqaOf5LN9R0WOt8jYWme2uX4fxlIiZ1XnG-2BnXVKmbnrFXcvqY4ejXr4WDKq8-2BlYG7l1vXDY6AV-2BOOXDpzWn2COc9MJoCkqcnvVc-2FJZW3uUOLnR9PMemQQBplsiXE2oRcp1TITn8y8MX1GE22oWblnZ8tN5eglR4qoYAireoAh9xmC6uFSBe1U82OC332DMv2u0t-2F06SMHe5k4F8KJH-2FHIw6NbQgGSRG1Cxs0PM3PEGC5RQ8-2F-2FQPS9ytj71aG2aAXuM4FYVprQ0aSdklbSWQs6vxFTqH3W3weHa2-2FQfIDFxfn0ue0UIa6KMTNmTpAY0M-2ByRCp4VvRFeDH1NhUJvaIQDX-2BxWeDn9u-2FukTuWbEyfgNGL48pOJalNJox9hhIqUf4aRC8ZTtLK0yHj8MW7gTg-3D-3DzqAO_MTQeFU9OGQYuK17CNM-2FHMJ7Fb2HmH4eyxwH7ImJgXSB3hRp-2BiwAszvutQkiAb1rH-2FOa6WSyzzhE0fm7qVvgs4-2F-2F0-2F-2BndU0DcBpBnqyQGrMtvjPI7Mzj912h88Y4JZfiBbAboimDQvJNL4k4YeWK9IiZW2ZMVsDpcvuai3ZKd6PPZptUuIIhnVl4du2tXxbUEznQPWDLaHkEyfkFor4F-2BKmcpXKIr-2B3aVsYRkkUBy4hKqto5azrVNCxud1GBJlmj-2F3f2VQYSDahjkZV5jLjOe2yUelcQMp0aL14C1pptLW29Xi5aJyR6iNqawIHoOze99fovtin86-2FGIYhdpF9SMXEqFSivFlkN3nvAj-2F0kevv5huy6jXwZdTxF5yz1kQzZaQj2Y-2BSbVlRu-2BHOerYdOporobbfk4vOt5SUACr1pfDoD5LwJBPK195IRH2iIjPEw1mMxOdnRgsSoO9kiISy8HTU1KQX0cQulBa0nnwp04DSTIQC-2FPkh8yKOrlJGbp9iktQ03lmO-2FRZNM2Yz2L9Wi-2B9jsZTgMZyUJL7lDf-2FxvXkKeU-3D"
                                                                style="text-decoration:none;display:inline-block;color:#fff;background-color:#3aaee0;border-radius:4px;width:auto;border-top:1px solid #3aaee0;border-right:1px solid #3aaee0;border-bottom:1px solid #3aaee0;border-left:1px solid #3aaee0;padding-top:5px;padding-bottom:5px;font-family:Montserrat,'Trebuchet MS','Lucida Grande','Lucida Sans Unicode','Lucida Sans',Tahoma,sans-serif;text-align:center;word-break:keep-all"
                                                                target="_blank"
                                                                data-saferedirecturl="https://www.google.com/url?q=http://link.julo.co.id/ls/click?upn%3Db71f3bQKJgoqZAeQsMqX-2BJRZbHM6I6VY6nhGOfL-2BMWe45KbbFQ992c9LHCUiZYbKnyMzUHUm3WmEhO-2Frvh5wuHMgFExgczyFPmk3IQJUNQz-2BHcNJb-2F1PheshMkUJo3xGEU9SLuOZTeYMzLvm2o1DLFF5Z-2Bd4mXMQ2NjqiFuaT0FiAXEPo5uetQBM4IwOSWpIm3T9TrsRCPJ-2F50eN478Q900O-2FXmSCWpqyOTzMbqsOcsHnjDeTS68eBpItSOhADTGs4bms7CRZcSvEApRjv-2Bkoiqe-2F1awdIUL1xa7iGQhrlbXHl9ChZEbUnDPBNeVHkwOgJSHbinMOvU-2F-2BpDtUxlaGl3GFR7Idt4acEQBaFeMusDcK3cwDRi2Fz-2FIRHM-2Bhb3Y-2FujbYu4d-2FkP2ezM0ofz1eVLZJZ91n570A337WoO4iqVGsLwIWjXiFj2xRaMF7LvEgWVP7dJhTi90PJ8R-2B-2B4KCb-2BmyNL2hABnAjzQgrPV6LyX8rSj4jmcIlHBWY0Iy1oXicAbeX0DsmRgOuF3QavRGtoV2GbxG69CjTD-2BtHO6r5F0SCroQ0F-2B-2Fn4YKvKn3gxEViMu6MWmZnMiAE0OdSi3ooC4ZkY8AX6qiCXAw92uCTvhypy7fQfvXVT4SiV-2BttiASyr4Q4jxZvPialcHJykvE8ZYzdIq-2FN30tpUepHghoAStiDfZkWkKZ-2FwIfCC26xNaQSBqaOf5LN9R0WOt8jYWme2uX4fxlIiZ1XnG-2BnXVKmbnrFXcvqY4ejXr4WDKq8-2BlYG7l1vXDY6AV-2BOOXDpzWn2COc9MJoCkqcnvVc-2FJZW3uUOLnR9PMemQQBplsiXE2oRcp1TITn8y8MX1GE22oWblnZ8tN5eglR4qoYAireoAh9xmC6uFSBe1U82OC332DMv2u0t-2F06SMHe5k4F8KJH-2FHIw6NbQgGSRG1Cxs0PM3PEGC5RQ8-2F-2FQPS9ytj71aG2aAXuM4FYVprQ0aSdklbSWQs6vxFTqH3W3weHa2-2FQfIDFxfn0ue0UIa6KMTNmTpAY0M-2ByRCp4VvRFeDH1NhUJvaIQDX-2BxWeDn9u-2FukTuWbEyfgNGL48pOJalNJox9hhIqUf4aRC8ZTtLK0yHj8MW7gTg-3D-3DzqAO_MTQeFU9OGQYuK17CNM-2FHMJ7Fb2HmH4eyxwH7ImJgXSB3hRp-2BiwAszvutQkiAb1rH-2FOa6WSyzzhE0fm7qVvgs4-2F-2F0-2F-2BndU0DcBpBnqyQGrMtvjPI7Mzj912h88Y4JZfiBbAboimDQvJNL4k4YeWK9IiZW2ZMVsDpcvuai3ZKd6PPZptUuIIhnVl4du2tXxbUEznQPWDLaHkEyfkFor4F-2BKmcpXKIr-2B3aVsYRkkUBy4hKqto5azrVNCxud1GBJlmj-2F3f2VQYSDahjkZV5jLjOe2yUelcQMp0aL14C1pptLW29Xi5aJyR6iNqawIHoOze99fovtin86-2FGIYhdpF9SMXEqFSivFlkN3nvAj-2F0kevv5huy6jXwZdTxF5yz1kQzZaQj2Y-2BSbVlRu-2BHOerYdOporobbfk4vOt5SUACr1pfDoD5LwJBPK195IRH2iIjPEw1mMxOdnRgsSoO9kiISy8HTU1KQX0cQulBa0nnwp04DSTIQC-2FPkh8yKOrlJGbp9iktQ03lmO-2FRZNM2Yz2L9Wi-2B9jsZTgMZyUJL7lDf-2FxvXkKeU-3D&amp;source=gmail&amp;ust=1650013062670000&amp;usg=AOvVaw2CffydMcF6EEiAgg0oX5XB"><span
                                                                style="padding-left:20px;padding-right:20px;font-size:14px;display:inline-block;letter-spacing:normal"><span
                                                                style="font-size:16px;line-height:2;word-break:break-word"><span
                                                                style="font-size:14px;line-height:28px">BAYAR SEKARANG</span></span></span></a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                </tbody>
                                            </table>
                                            <p style="margin:0;line-height:1.5;word-break:break-word;font-size:13px;mso-line-height-alt:20px;mso-ansi-font-size:14px;margin-top:0;margin-bottom:0">
                                                <span style="font-size:13px;mso-ansi-font-size:14px">Terima kasih dan salam,</span>
                                            </p>
                                            <p style="margin:0;line-height:1.5;word-break:break-word;font-size:13px;mso-line-height-alt:20px;mso-ansi-font-size:14px;margin-top:0;margin-bottom:0">
                                                <span style="font-size:13px;mso-ansi-font-size:14px">JULO</span></p>
                                            <p style="margin:0;line-height:1.5;word-break:break-word;mso-line-height-alt:18px;margin-top:0;margin-bottom:0"></p>
                                            <p style="margin:0;line-height:1.5;word-break:break-word;mso-line-height-alt:18px;margin-top:0;margin-bottom:0"></p>
                                        </div>
                                    </div><!--[if mso]><![endif]--><!--[if mso]>
                                    <table width="100%" cellpadding="0" cellspacing="0" border="0">
                                        <tr>
                                            <td style="padding-right:10px;padding-left:10px;padding-top:5px;padding-bottom:5px;font-family:sans-serif">
                                    <![endif]--><!--[if mso]><![endif]--><!--[if (!mso)&(!IE)]><!--></div>
                                <!--<![endif]--></div>
                        </div><!--[if (mso)|(IE)]><![endif]--><!--[if (mso)|(IE)]><![endif]--></div>
                </div>
            </div>
            <div>
                <div class="block-grid"
                     style="min-width:320px;max-width:500px;overflow-wrap:break-word;word-wrap:break-word;word-break:break-word;Margin:0 auto;background-color:#444">
                    <div style="border-collapse:collapse;display:table;width:100%;background-color:transparent">
                        <!--[if (mso)|(IE)]>
                        <table width="100%" cellpadding="0" cellspacing="0" border="0" style="background-color:#444">
                            <tr>
                                <td align="center">
                                    <table cellpadding="0" cellspacing="0" border="0" style="width:500px">
                                        <tr class="layout-full-width" style="background-color:transparent"><![endif]-->
                        <!--[if (mso)|(IE)]>
                        <td align="center" width="500"
                            style="background-color:transparent;width:500px;border-top:0 solid transparent;border-left:0 solid transparent;border-bottom:0 solid transparent;border-right:0 solid transparent"
                            valign="top">
                            <table width="100%" cellpadding="0" cellspacing="0" border="0">
                                <tr>
                                    <td style="padding-right:0;padding-left:0;padding-top:25px;padding-bottom:25px">
                        <![endif]-->
                        <div class="col num12"
                             style="min-width:320px;max-width:500px;display:table-cell;vertical-align:top;width:500px">
                            <div class="col_cont" style="width:100%!important"><!--[if (!mso)&(!IE)]><!-->
                                <div style="border-top:0 solid transparent;border-left:0 solid transparent;border-bottom:0 solid transparent;border-right:0 solid transparent;padding-top:25px;padding-bottom:25px;padding-right:0;padding-left:0">
                                    <!--<![endif]-->
                                    <table class="social_icons" cellpadding="0" cellspacing="0" width="100%"
                                           role="presentation"
                                           style="table-layout:fixed;vertical-align:top;border-spacing:0;border-collapse:collapse;mso-table-lspace:0;mso-table-rspace:0"
                                           valign="top">
                                        <tbody>
                                        <tr style="vertical-align:top" valign="top">
                                            <td style="word-break:break-word;vertical-align:top;padding-top:10px;padding-right:10px;padding-bottom:10px;padding-left:10px"
                                                valign="top">
                                                <table class="social_table" align="center" cellpadding="0"
                                                       cellspacing="0" role="presentation"
                                                       style="table-layout:fixed;vertical-align:top;border-spacing:0;border-collapse:collapse;mso-table-tspace:0;mso-table-rspace:0;mso-table-bspace:0;mso-table-lspace:0"
                                                       valign="top">
                                                    <tbody>
                                                    <tr style="vertical-align:top;display:inline-block;text-align:center"
                                                        align="center" valign="top">
                                                        <td style="word-break:break-word;vertical-align:top;padding-bottom:0;padding-right:5px;padding-left:0"
                                                            valign="top"><a
                                                                href="https://www.facebook.com/JULOIndonesia"
                                                                target="_blank"><img width="32" height="32"
                                                                                     src="https://d2fi4ri5dhpqd1.cloudfront.net/public/resources/social-networks-icon-sets/blue/facebook.png"
                                                                                     alt="Facebook" title="Facebook"
                                                                                     style="text-decoration:none;-ms-interpolation-mode:bicubic;height:auto;border:0;display:block"></a>
                                                        </td>
                                                        <td style="word-break:break-word;vertical-align:top;padding-bottom:0;padding-right:5px;padding-left:0"
                                                            valign="top"><a
                                                                href="https://www.youtube.com/channel/UCA9WsBMIg3IHxwVA-RvSctA"
                                                                target="_blank"><img width="32" height="32"
                                                                                     src="https://d2fi4ri5dhpqd1.cloudfront.net/public/resources/social-networks-icon-sets/blue/youtube@2x.png"
                                                                                     alt="YouTube" title="YouTube"
                                                                                     style="text-decoration:none;-ms-interpolation-mode:bicubic;height:auto;border:0;display:block"></a>
                                                        </td>
                                                        <td style="word-break:break-word;vertical-align:top;padding-bottom:0;padding-right:5px;padding-left:0"
                                                            valign="top"><a
                                                                href="https://www.instagram.com/juloindonesia/"
                                                                target="_blank"><img width="32" height="32"
                                                                                     src="https://d2fi4ri5dhpqd1.cloudfront.net/public/resources/social-networks-icon-sets/blue/instagram@2x.png"
                                                                                     alt="Instagram" title="Instagram"
                                                                                     style="text-decoration:none;-ms-interpolation-mode:bicubic;height:auto;border:0;display:block"></a>
                                                        </td>
                                                        <td style="word-break:break-word;vertical-align:top;padding-bottom:0;padding-right:5px;padding-left:0"
                                                            valign="top"><a
                                                                href="https://www.linkedin.com/company/juloindonesia/"
                                                                target="_blank"><img width="32" height="32"
                                                                                     src="https://d2fi4ri5dhpqd1.cloudfront.net/public/resources/social-networks-icon-sets/blue/linkedin@2x.png"
                                                                                     alt="LinkedIn" title="LinkedIn"
                                                                                     style="text-decoration:none;-ms-interpolation-mode:bicubic;height:auto;border:0;display:block"></a>
                                                        </td>
                                                    </tr>
                                                    </tbody>
                                                </table>
                                            </td>
                                        </tr>
                                        </tbody>
                                    </table>
                                    <!--[if mso]>
                                    <table width="100%" cellpadding="0" cellspacing="0" border="0">
                                        <tr>
                                            <td style="padding-right:10px;padding-left:10px;padding-top:10px;padding-bottom:10px;font-family:'Trebuchet MS',Tahoma,sans-serif">
                                    <![endif]-->
                                    <div style="color:#bbb;font-family:Montserrat,'Trebuchet MS','Lucida Grande','Lucida Sans Unicode','Lucida Sans',Tahoma,sans-serif;line-height:1.2;padding-top:10px;padding-right:10px;padding-bottom:10px;padding-left:10px">
                                        <div style="font-family:Montserrat,'Trebuchet MS','Lucida Grande','Lucida Sans Unicode','Lucida Sans',Tahoma,sans-serif;line-height:1.2;font-size:12px;color:#bbb;mso-line-height-alt:14px">
                                            <p style="margin:0;line-height:1.2;text-align:center;font-size:12px;word-break:break-word;font-family:Montserrat,'Trebuchet MS','Lucida Grande','Lucida Sans Unicode','Lucida Sans',Tahoma,sans-serif;mso-line-height-alt:14px">
                                                <a style="text-decoration:underline;color:#c7702e"
                                                   href="https://www.julo.co.id/" target="_blank" rel="noopener">www.julo.co.id</a>
                                            </p>
                                            <p style="margin:0;line-height:1.2;text-align:center;font-size:12px;word-break:break-word;font-family:Montserrat,'Trebuchet MS','Lucida Grande','Lucida Sans Unicode','Lucida Sans',Tahoma,sans-serif;mso-line-height-alt:14px">
                                                <br>Office 88@Kasablanka Tower A,<br>Jl. Casablanca No.Kav 88,
                                                RT.2/RW.12,<br>Menteng Dalam, Tebet, South Jakarta City, Jakarta 12870
                                            </p>
                                            <p align="center" style="line-height:inherit;margin:0;text-align:center">
                                                &nbsp;</p>
                                            <p align="center" style="line-height:inherit;margin:0;text-align:center">
                                                Selalu jaga kerahasiaan<em>password</em>, PIN, dan OTP&nbsp;</p>
                                            <p align="center" style="line-height:inherit;margin:0;text-align:center">
                                                dengan tidak memberikan informasi tersebut kepada
                                                siapapun.<br>Hubungi<em>Customer Service</em>JULO, jika kamu mengalami
                                                masalah dalam bertransaksi.</p>
                                            <p align="center" style="line-height:inherit;margin:0;text-align:center">
                                                Telepon: <a href="tel:02150919036" rel="noopener" style="color:#c7702e"
                                                            title="tel:02150919036" target="_blank">021-5091-9036</a>,
                                                <a href="tel:02150919037" rel="noopener" style="color:#c7702e"
                                                   title="tel:02150919037" target="_blank">021-5091-9037</a>, <a
                                                    href="http://02130433660" rel="noopener" style="color:#c7702e"
                                                    target="_blank"
                                                    data-saferedirecturl="https://www.google.com/url?q=http://02130433660&amp;source=gmail&amp;ust=1650013062671000&amp;usg=AOvVaw2pn6ghHNj-4NMqXqrJ_vaa">021-3043-3660</a>
                                            </p>
                                            <p align="center" style="line-height:inherit;margin:0;text-align:center">
                                                E-mail: <a href="mailto:collections@julo.co.id%C2%A0" rel="noopener"
                                                           style="color:#c7702e" title="collections@julo.co.id&nbsp;"
                                                           target="_blank">collections@julo.co.id</a>&nbsp;</p>
                                            <p align="center" style="line-height:inherit;margin:0;text-align:center">
                                                (Jam operasional Senin - Minggu 08.00-21.00 WIB)<br><br>Klik <a
                                                    href="http://link.julo.co.id/wf/unsubscribe?upn=U7z7oSqRMSwdl2rYt9JJ4x2nCQGTp6Vg-2FqRyFdt-2BIT2L5wWSNbNjH-2Fxln3x6QAbRN407Xs5zP5JH4NdCNQBFPW4GrSIiDIq9IXiTliZ-2FHzMtY4yFKHgqqcGQZA35Gvz7OgjGyAwGuzwg-2FCDsl7371gYj7Cants7CiFmMr98d-2FQpJ1UMcrf1QKXT-2BjW6tpDigxz0kvnT4QnmBBXCZ-2Fyff97d-2Fqaml4AmK35AAIABKwH8KKt0aF-2F5F05eAFU-2FZmsh3BpYIYKHa-2F6U-2B5vQMXOec5d5851D5tGS84plNMEMgNkW1n66HHLsQkYMG-2F7n5q44Cs9OFWNcbb5WYeXkUwhQ5C9mM9QCsvCtAVI-2But5eGnu6QZKaW2bzKET5DP9hQSzCwLplcpk0VlJhT1pbRjXMx-2F9aoi3V-2B4JB-2Fp-2ByYQ-2B4B0qpEtuRjwS3cn7TpP6Rg9crJN-2F9B1bHSiJ5vd98tb71FtNchUwVRD0DIcVXIOGL5Brt5qOgPXdnZjGZvExijz4oEkmFNmIkhfOqLnnrFsmBWZIE3GWjfMJk-2F79yR9dRouxJ1tE49KAbemS0zi6Goh4dA"
                                                    rel="noopener" style="text-decoration:underline;color:#c7702e"
                                                    target="_blank"
                                                    data-saferedirecturl="https://www.google.com/url?q=http://link.julo.co.id/wf/unsubscribe?upn%3DU7z7oSqRMSwdl2rYt9JJ4x2nCQGTp6Vg-2FqRyFdt-2BIT2L5wWSNbNjH-2Fxln3x6QAbRN407Xs5zP5JH4NdCNQBFPW4GrSIiDIq9IXiTliZ-2FHzMtY4yFKHgqqcGQZA35Gvz7OgjGyAwGuzwg-2FCDsl7371gYj7Cants7CiFmMr98d-2FQpJ1UMcrf1QKXT-2BjW6tpDigxz0kvnT4QnmBBXCZ-2Fyff97d-2Fqaml4AmK35AAIABKwH8KKt0aF-2F5F05eAFU-2FZmsh3BpYIYKHa-2F6U-2B5vQMXOec5d5851D5tGS84plNMEMgNkW1n66HHLsQkYMG-2F7n5q44Cs9OFWNcbb5WYeXkUwhQ5C9mM9QCsvCtAVI-2But5eGnu6QZKaW2bzKET5DP9hQSzCwLplcpk0VlJhT1pbRjXMx-2F9aoi3V-2B4JB-2Fp-2ByYQ-2B4B0qpEtuRjwS3cn7TpP6Rg9crJN-2F9B1bHSiJ5vd98tb71FtNchUwVRD0DIcVXIOGL5Brt5qOgPXdnZjGZvExijz4oEkmFNmIkhfOqLnnrFsmBWZIE3GWjfMJk-2F79yR9dRouxJ1tE49KAbemS0zi6Goh4dA&amp;source=gmail&amp;ust=1650013062671000&amp;usg=AOvVaw3Al721Oi1YWOhZWyRuEIqV">unsubscribe</a>
                                                jika kamu ingin berhenti menerima e-mail dari JULO</p></div>
                                    </div><!--[if mso]><![endif]--><!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->
                            </div>
                        </div><!--[if (mso)|(IE)]><![endif]--><!--[if (mso)|(IE)]><![endif]--></div>
                </div>
            </div><!--[if (mso)|(IE)]><![endif]--></td>
    </tr>
    </tbody>
</table><!--[if (IE)]><![endif]--></body>
</html>
    """
    stream_lined_message_parameter_new = "{title_long, full_name, account1_due_amount, va_method_name, va_number}"

    stream_lined_communication = StreamlinedCommunication.objects.get(template_code='j1_email_dpd_+4')

    StreamlinedMessage.objects.filter(id=stream_lined_communication.message_id).update(
        message_content=stream_lined_message_content_new,
        parameter=stream_lined_message_parameter_new
    )


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunPython(update_stream_lined_message, migrations.RunPython.noop)
    ]
