# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-04-04 09:14
from __future__ import unicode_literals

from django.db import migrations
from juloserver.portal.object.product_profile.services import generate_product_lookup
from juloserver.julo.models import (
    ProductLine,
    ProductProfile,
    ProductLookup
)


EF_PRODUCT = {
    'code': 500,
    'name': 'employee financing',
    'min_amount': 1000000,
    'max_amount': 20000000,
    'min_duration': 1,
    'max_duration': 9,
    'min_interest_rate': 0.04,
    'max_interest_rate': 0.05,
    'interest_rate_increment': 0.05,
    'min_origination_fee': 0.05,
    'max_origination_fee': 0.07,
    'origination_fee_increment': 0.00,
    'cashback_initial': 0.00,
    'cashback_payment': 0.00,
    'late_fee': 0.00,
    'payment_frequency': 'Monthly',
    'debt_income_ratio': 0.3,
    'is_initial': True,
    'is_active': True
}


def load_ef_product(apps, schema_editor):
    product_profile = ProductProfile(**EF_PRODUCT)
    product_profile.save()

    # product_line
    product_line = ProductLine.objects.create(
        product_line_code=product_profile.code,
        product_line_type=product_profile.name,
        min_amount=product_profile.min_amount,
        max_amount=product_profile.max_amount,
        min_duration=product_profile.min_duration,
        max_duration=product_profile.max_duration,
        min_interest_rate=0.48,
        max_interest_rate=0.6,
        payment_frequency=product_profile.payment_frequency,
        product_profile=product_profile
    )

    # product lookup
    product_lookup_list = generate_product_lookup(product_profile, product_line)
    for product_lookup_data in product_lookup_list:
        product_lookup = ProductLookup(**product_lookup_data)
        product_lookup.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(load_ef_product, migrations.RunPython.noop)
    ]
