# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-04-28 06:53
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import Workflow, WorkflowStatusPath
from juloserver.julo.constants import WorkflowConst


def add_workflow_credit_card(apps, _schema_editor):

    Workflow.objects.get_or_create(
        name=WorkflowConst.CREDIT_CARD,
        desc="this is a workflow for CreditCard",
        is_active=True,
        handler="CreditCardWorkflowHandler"
    )
    workflow = Workflow.objects\
        .filter(name=WorkflowConst.CREDIT_CARD).last()
    # WorkflowStatusPath
    WorkflowStatusPath.objects.get_or_create(
        status_previous=510,
        status_next=511,
        type="happy",
        workflow=workflow
    )
    WorkflowStatusPath.objects.get_or_create(
        status_previous=510,
        status_next=513,
        type="unhappy",
        workflow=workflow
    )
    WorkflowStatusPath.objects.get_or_create(
        status_previous=510,
        status_next=514,
        type="detour",
        workflow=workflow
    )
    WorkflowStatusPath.objects.get_or_create(
        status_previous=511,
        status_next=512,
        type="happy",
        workflow=workflow
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_workflow_credit_card, migrations.RunPython.noop),
    ]
