# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-05-17 03:08
from __future__ import unicode_literals

from django.db import migrations

from juloserver.cootek.models import CootekConfiguration


def set_true_exclude_autodebet_for_julo_tmin2_to_t0(apps, schema_editor):
    cootek_configurations = CootekConfiguration.objects.filter(
        strategy_name__in=['JULO_T0', 'JULO_T-1', 'JULO_T-2'])

    for configuration in cootek_configurations:
        configuration.exclude_autodebet = True
        configuration.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(set_true_exclude_autodebet_for_julo_tmin2_to_t0, migrations.RunPython.noop),
    ]
