# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-05-11 18:02
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FaqCheckout


def insert_faq_checkout_data(apps, schema_editor):
    description1 = ("<ol><li>Potensial cashback akan kamu dapatkan jika membayar sebelum jatuh tempo."
                    "</li><li>Cashback dapat kamu cairkan setelah pembayaran pinjaman lunas."
                    "</li><li>Jumlah potensial cashback yang kamu dapat beragam setiap bulannya, " 
                    "bergantung dengan total pinjaman dan kapan kamu membayar sebelum jatuh tempo."
                    "</li><li>Cashback akan dikalkulasikan sesuai dengan tanggal sebelum jatuh tempo. " 
                    "> 5 hari sebelum jatuh tempo: 3%<ul><li>5 hari sebelum jatuh tempo: 3%"
                    "</li><li>4 hari sebelum jatuh tempo: 3%</li><li>3 hari sebelum jatuh tempo: 2%"
                    "</li><li>2 hari sebelum jatuh tempo: 2%</li><li>1 hari sebelum jatuh tempo: 1%"
                    "</li><li>Tepat di tanggal jatuh tempo: 1%</li></ul>"
                    "</li><li>Cashback dapat digunakan untuk*<ul><li>Transfer ke rekening Bank kamu</li>"
                    "<li>Beli paket data dan pulsa</li><li>Top up saldo gopay</li>"
                    "<li>Isi ulang token listrik</li>"
                    "<li>Potongan cicilan pinjaman berikutnya</li></ul>"
                    "*Berdasarkan dari level yang kamu peroleh</li></ol>")
    description2 = ("<ol><li>Biaya keterlambatan akan dikenakan jika kamu membayar melewati "
                    "tanggal jatuh tempo</li><li>Total biaya keterlambatan akan dikalkulasi sesuai "
                    "dengan transaksi pinjaman yang kamu gunakan.</li><li>Kamu akan dikenakan biaya "
                    "keterlambatan jika melewati minimal 6 hari setelah tanggal jatuh tempo.</li></ol>")
    description3 = ("<ol><li>Masa tenggang adalah waktu di mana kamu masih diberikan keringanan "
                    "untuk terbebas dari biaya keterlambatan.</li><li>Masa tenggang terhitung dari 5 hari " 
                    "setelah jatuh tempo.</li><li>Jika kamu membayar di dalam masa tenggang, " 
                    "maka kamu tidak mendapatkan cashback.</li><li>Kamu akan dikenakan biaya "
                    "keterlambatan jika masa tenggang sudah habis.</li></ol>")
    data = [
        {
            'title': 'Apa Potensial Cashback?',
            'description':  description1,
            'order_priority': 1,
            'visible': True
        },
        {
            'title': 'Apa biaya keterlambatan?',
            'description': description2,
            'order_priority': 2,
            'visible': True
        },
        {
            'title': 'Apa masa tenggang?',
            'description': description3,
            'order_priority': 3,
            'visible': True
        }
    ]

    for item in data:
        faq_checkout = FaqCheckout.objects.get_or_create(
            title = item['title'],
            description = item['description'],
            order_priority = item['order_priority'],
            visible = item['visible'],
        )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(insert_faq_checkout_data, migrations.RunPython.noop)
    ]
