# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-06-16 08:36
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst


def add_timeout_settings_to_bonza_admin(apps, _schema_editor):
    bonza_feature = FeatureSetting.objects.filter(
        feature_name=FeatureNameConst.BONZA_LOAN_SCORING).last()
    parameters = bonza_feature.parameters
    timeout_params = {
        'inhouse_loan_scoring': 1.1,
        'inhouse_loan_storing': 5}
    parameters['timeout_parameters'] = timeout_params
    bonza_feature.parameters = parameters
    bonza_feature.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_timeout_settings_to_bonza_admin,
                             migrations.RunPython.noop),
    ]
