# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-06-16 08:36
from __future__ import unicode_literals

from django.db import migrations
from juloserver.streamlined_communication.models import InfoCardProperty, StreamlinedCommunication, StreamlinedMessage, CardProperty
from juloserver.streamlined_communication.constant import CommunicationPlatform
from juloserver.account.constants import AccountConstant
from juloserver.julo.models import Image


def add_gotham_soft_reject_info_card(apps, _schema_editor):
    
    info_card_property = InfoCardProperty.objects.create(
        card_type = '2',
        card_order_number = 1,
        title='Akun Terblokir Sementara',
        title_color='#FFFFFF',
        text_color='#FFFFFF')
    Image.objects.create(image_source=info_card_property.id, image_type=CardProperty.IMAGE_TYPE.card_background_image,
        url='info-card/CARD_BACKGROUND_IMAGE_351.png', service='oss', image_status=0)
    message = StreamlinedMessage.objects.create(
        message_content=('Saat ini kamu tidak bisa melakukan transaksi apa pun, '
                          'kamu bisa langsung menghubungi CS JULO di '
                          '021-50919038 untuk mengaktifkan kembali akunmu.'),
        info_card_property=info_card_property)
    StreamlinedCommunication.objects.create(
        template_code='gotham_soft_reject',
        message=message,
        communication_platform=CommunicationPlatform.INFO_CARD,
        status_code_id=AccountConstant.STATUS_CODE.fraud_soft_reject,
        is_active=True,
        description='Gotham Soft Rejected Account')


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_gotham_soft_reject_info_card,
                             migrations.RunPython.noop),
    ]
