# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-07-04 05:28
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def add_new_feature_setting(apps, _schema_editor):
    created_data = {
        'feature_name': FeatureNameConst.EMAIL_OTP,
        'is_active': True,
        'parameters': {"otp_max_request": 3, "otp_resend_time": 60, "wait_time_seconds": 200},
        'category': 'partner',
        'description': 'Email OTP'
    }
    FeatureSetting.objects.create(**created_data)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_new_feature_setting, migrations.RunPython.noop),
    ]
