# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-07-06 13:36
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst

def add_temporary_block_period_feature(apps, schema_editor):
    FeatureSetting.objects.get_or_create(is_active=True,
                                         feature_name=FeatureNameConst.PAYLATER_PARTNER_TEMPORARY_BLOCK_PERIOD,
                                         parameters={
                                             'temporary_blocking_hour': 1,
                                             'temporary_blocking_attempt': 3,
                                         },
                                         category='partnership',
                                         description="paylater_partner_temporary_block_hour_and_attempts"
                                         )

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_temporary_block_period_feature, migrations.RunPython.noop)
    ]
