# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-07-18 03:56
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting
import datetime


def add_ef_pre_approval_feature_setting(apps, _schema_editor):
    created_data = {
        'feature_name': FeatureNameConst.EF_PRE_APPROVAL,
        'is_active': True,
        'parameters': {
            "minimum_income": 2000000,
            "minimum_job_term": 90,  # days
            "minimum_age": 21,
        },
        'category': 'partner',
        'description': 'Employee Financing - Pre Approval'
    }
    FeatureSetting.objects.create(**created_data)


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_ef_pre_approval_feature_setting, migrations.RunPython.noop),
    ]
