# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-08-03 12:13
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def add_new_grab_deduction_feature_setting(apps, _schema_editor):
    data_to_be_created = {
        'feature_name': FeatureNameConst.GRAB_DEDUCTION_SCHEDULE,
        'is_active': False,
        'parameters': {
            "schedule": ["01:00", "04:00", "07:00",
                         "09:00", "10:00", "12:00",
                         "14:00", "16:00", "18:00",
                         "22:00"],
            "complete_rollover": False
        },
        'category': 'repayment',
        'description': 'This configuration is to set the schedule when we should trigger deduction to grab'
    }
    FeatureSetting.objects.get_or_create(**data_to_be_created)


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_new_grab_deduction_feature_setting, migrations.RunPython.noop),
    ]
