# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-09-30 08:56
from __future__ import unicode_literals

from builtins import str
from builtins import object
from django.conf import settings
from django.db import migrations

from juloserver.application_flow.constants import PartnerNameConstant
from juloserver.julo.models import StatusLookup, Image, Partner
from juloserver.julo.statuses import ApplicationStatusCodes, LoanStatusCodes
from juloserver.julo.utils import upload_file_to_oss
from juloserver.streamlined_communication.models import (InfoCardButtonProperty,
                                                         CardProperty,
                                                         InfoCardProperty,
                                                         StreamlinedMessage,
                                                         StreamlinedCommunication)
from juloserver.streamlined_communication.constant import CommunicationPlatform, CardProperty
party_popper_emoji = '\U0001F389'
praying_emoji = '\U0001F64F'
hourglass_emoji = '\U000023F3'
warning_emoji = '\U000026A0'
smile_emoji = '\U0001F642'

L_BUTTON = 'L.BUTTON'
R_BUTTON = 'R.BUTTON'
M_BUTTON = 'M.BUTTON'


class ImageNames(object):
    BACK_190 = 'info-card/CARD_BACKGROUND_IMAGE_WEB190.png'
    BACK_105 = 'info-card/CARD_BACKGROUND_IMAGE_WEB105.png'
    OPT_190 = 'info-card/CARD_OPTIONAL_IMAGE_WEB190.png'
    BUTTON_190 = 'info-card/R_BUTTON_IMAGE_WEB190.png'
    BUTTON_FULL = 'info-card/R_BUTTON_IMAGE_WEB136.png'
    ADDITIONAL_IMAGE_1 = 'info-card/WEBAPP_ADDITIONAL_IMAGE_1.png'
    ADDITIONAL_IMAGE_2 = 'info-card/WEBAPP_ADDITIONAL_IMAGE_2.png'
    ADDITIONAL_IMAGE_3 = 'info-card/ADDITIONAL_IMAGE_LOAN_210.png'
    BACK_ORANGE = 'info-card/WEBAPP_BACKGROUD_ORANGE.png'
    BACK_RED = 'info-card/WEBAPP_BACKGROUND_RED.png'
    BUTTON_ORANGE = 'info-card/WEBAPP_BUTTON_ORANGE.png'
    ADDITIONAL_IMAGE_CASHBACK = 'info-card/WEBAPP_ADDITIONAL_CASHBAC.png'
    ADDITIONAL_IMAGE_ORANGE = 'info-card/WEBAPP_ADDITIONAL_ORANGE.png'
    ADDITIONAL_IMAGE_ORANGE_2 = 'info-card/WEBAPP_ADDITIONAL_ORANGE_2.png'
    ADDITIONAL_IMAGE_ORANGE_3 = 'info-card/WEBAPP_ADDITIONAL_ORANGE_3.png'
    BUTTON_BACKGROUND_RED = 'info-card/rectangle_1489_red.png'
    BUTTON_BACKGROUND_RED_2 = 'info-card/rectangle_1489_2_red.png'
    EXCLAMATION_IMAGE_RED = 'info-card/group_3500_red.png'


def create_image(image_source_id, image_type, image_url):
    image = Image()
    image.image_source = image_source_id
    image.image_type = image_type
    image.url = image_url
    image.save()


def retroload_infocards_for_webapp(apps, _schema_editor):
    linkaja_partner = None
    data = {
            'status': ApplicationStatusCodes.FORM_PARTIAL,
            'additional_condition': CardProperty.PARTNERSHIP_WEBVIEW_INFO_CUSTOMER_WAITING_SCORE,
            'title': 'Formulir Anda sedang dalam proses',
            'content': 'Mohon menunggu, formulir Anda sedang diproses oleh team JULO',
            'button': [],
            'click_to': [],
            'template_type': '2',
            'card_number': 1,
            'text_colour': '#ffffff',
            'title_colour': '#ffffff',
            'background_url': ImageNames.BACK_105,
            'additional_images': [],
            'button_url': [],
            'show_in_web': True,
            'show_in_android': False,
            'partner': linkaja_partner
        }

    button_2_properties = {'card_type': '2',
                           'title': data['title'],
                           'title_color': data['title_colour'],
                           'text_color': data['text_colour'],
                           'card_order_number': data['card_number']}
    info_card = InfoCardProperty.objects.create(**button_2_properties)
    data_streamlined_message = {'message_content': data['content'],
                                'info_card_property': info_card}
    message = StreamlinedMessage.objects.create(**data_streamlined_message)
    status = StatusLookup.objects.filter(status_code=data['status']).last()
    data_for_streamlined_comms = {'status_code': status,
                                  'status': data['status'],
                                  'communication_platform': CommunicationPlatform.INFO_CARD,
                                  'message': message,
                                  'description': 'retroloaded_card_information',
                                  'is_active': True,
                                  'extra_conditions': data['additional_condition'],
                                  'show_in_web': data['show_in_web'],
                                  'show_in_android': data['show_in_android'],
                                  'partner': data['partner']}
    streamlined_communication = StreamlinedCommunication.objects.create(**data_for_streamlined_comms)
    # create image for background
    if data['background_url']:
        create_image(info_card.id, CardProperty.IMAGE_TYPE.card_background_image, data['background_url'])


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(retroload_infocards_for_webapp, migrations.RunPython.noop)
    ]
