# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-08-12 08:40
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst


def create_or_update_feature_setting_autodebet_customer_exclude_from_intelix_call(apps, schema_editor):
    parameters = {
        "dpd_minus": True,
        "dpd_zero": False,
        "dpd_plus": False
    } 
    feature_setting = FeatureSetting.objects.filter(
        feature_name=FeatureNameConst.AUTODEBET_CUSTOMER_EXCLUDE_FROM_INTELIX_CALL
    )
    if feature_setting:
        feature_setting.update(
            parameters=parameters
        )
    else:
        FeatureSetting.objects.create(
            feature_name=FeatureNameConst.AUTODEBET_CUSTOMER_EXCLUDE_FROM_INTELIX_CALL,
            is_active=True,
            description='autodebet customer exclude from intelix call',
            category='intelix',
            parameters=parameters
        )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            create_or_update_feature_setting_autodebet_customer_exclude_from_intelix_call, migrations.RunPython.noop
        ),
    ]
