# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-06-16 08:36
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst


def turn_off_gotham_for_version2_release(apps, _schema_editor):
    bonza_feature = FeatureSetting.objects.filter(
        feature_name=FeatureNameConst.BONZA_LOAN_SCORING).last()
    if bonza_feature:
        bonza_feature.is_active = False
        bonza_feature.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(turn_off_gotham_for_version2_release,
                             migrations.RunPython.noop),
    ]
