# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-07-22 14:00
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import MobileFeatureSetting, FeatureSetting
from juloserver.otp.constants import SessionTokenAction, SessionTokenType


def update_mobile_phone_1_otp_feature_setting(apps, schema_editor):
    MobileFeatureSetting.objects.filter(feature_name='mobile_phone_1_otp').update(
        parameters={
            "otp_max_request": 3, "otp_resend_time": 60, "wait_time_seconds": 300, "otp_max_validate": 3
        }
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            update_mobile_phone_1_otp_feature_setting, migrations.RunPython.noop),
    ]
