# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-08-31 04:06
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def create_feature_setting_j_score_history_config(apps, _schema_editor):
    parameters = {
        "j_score_history_details": {
            "action_points": [
                {
                    "max_value": 999999,
                    "title": "Pinjaman baru",
                    "message": "Kamu berhasil membuat pinjaman baru! Poin kamu bertambah. Tingkatkan lagi poin dengan transaksi di JULO",
                    "min_value": 1
                },
                {
                    "max_value": 0,
                    "title": "",
                    "message": "",
                    "min_value": 0
                },
                {
                    "max_value": -1,
                    "title": "Pembayaran terlambat",
                    "message": "Kamu melakukan pembayaran lewat jatuh tempo. Jangan lupa bayar tepat waktu untuk tingkatkan poinmu.",
                    "min_value": -999999
                }
            ],
            "action_expired": [
                {
                    "max_value": 999999,
                    "title": "Poin kedaluwarsa",
                    "message": "Gunakan poin sebelum masa berlaku habis. Kamu bisa tingkatkan poin dari bertransaksi juga, loh.",
                    "min_value": 1
                },
                {
                    "max_value": 0,
                    "title": "",
                    "message": "",
                    "min_value": 0
                },
                {
                    "max_value": -1,
                    "title": "Poin kedaluwarsa",
                    "message": "Gunakan poin sebelum masa berlaku habis. Kamu bisa tingkatkan poin dari bertransaksi juga, loh.",
                    "min_value": -999999
                }
            ]
        }
    }

    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.J_SCORE_HISTORY_CONFIG,
        is_active=True,
        parameters=parameters,
        category='CFS',
        description='Contains information about month history details',
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_feature_setting_j_score_history_config, migrations.RunPython.noop)
    ]
