# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-09-12 08:24
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.constants import FeatureNameConst

from juloserver.julo.models import FeatureSetting


def add_feature_setting_new_sepulsa_url(apps, _schema_editor):
    data = {
        'is_active': False,
        'feature_name': FeatureNameConst.USE_NEW_SEPULSA_BASE_URL,
        'category': "payment_point",
        'description': "to use or not to use new sepulsa base url"
    }
    feature = FeatureSetting.objects.get_or_none(feature_name=data['feature_name'])
    if not feature:
        FeatureSetting.objects.create(**data) 


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(
            add_feature_setting_new_sepulsa_url, migrations.RunPython.noop
        ),
    ]
