# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-09-01 05:55
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import ChangeReason


def add_reason_julo_card(apps, _schema_editor):
    ChangeReason.objects.get_or_create(
        reason='Resubmit selfie',
        status_id=523
    )
    ChangeReason.objects.get_or_create(
        reason='Address not clear',
        status_id=523
    )
    ChangeReason.objects.get_or_create(
        reason='Resubmit selfie and address not clear',
        status_id=523
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_reason_julo_card, migrations.RunPython.noop)
    ]
