# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-09-05 04:09
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import Onboarding


def onboarding_for_longform_shortened(apps, schema_editor):
    """
    Add new value for longform_shortened
    with ID: 3
    """

    longform_shortened_id = 3
    is_exist = Onboarding.objects.filter(id=longform_shortened_id).exists()
    if not is_exist:
        Onboarding.objects.create(id=longform_shortened_id,
                                  description="Long Form Shortened",
                                  status=True)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(onboarding_for_longform_shortened, migrations.RunPython.noop)
    ]
