# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-09-05 06:17
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import (
    ProductLine, ProductProfile, ProductLookup,ProductLineLoanPurpose,
)
from juloserver.julo.product_lines import ProductLineCodes

def add_product_line_dagangan(apps, schema_editor):
    dagangan_product_profile, _ = ProductProfile.objects.get_or_create(
        name='DAGANGAN',
        code=ProductLineCodes.DAGANGAN,
        min_amount=1000000,
        max_amount=10000000,
        min_duration=14,
        max_duration=14,
        min_interest_rate=0.028,
        max_interest_rate=0.04,
        interest_rate_increment=0,
        payment_frequency='Daily',
        min_origination_fee=0,
        max_origination_fee=0,
        late_fee=0.05,
        cashback_initial=0,
        cashback_payment=0,
        debt_income_ratio=0.3,
    )
    dagangan_product_line, _ = ProductLine.objects.get_or_create(
        product_line_code=ProductLineCodes.DAGANGAN,
        product_line_type='DAGANGAN',
        min_amount=1000000,
        max_amount=10000000,
        min_duration=14,
        max_duration=14,
        min_interest_rate=0.028,
        max_interest_rate=0.04,
        payment_frequency='Daily',
        product_profile=dagangan_product_profile
    )
    ProductLookup.objects.get_or_create(
        product_name="I.386-O.000-L.050-C1.000-C2.000-M",
        interest_rate=0.386,
        origination_fee_pct=0,
        late_fee_pct=0.05,
        product_line=dagangan_product_line,
        product_profile=dagangan_product_profile,
        cashback_initial_pct=0,
        cashback_payment_pct=0
    )
    ProductLookup.objects.get_or_create(
        product_name="I.45-O.000-L.050-C1.000-C2.000-M",
        interest_rate=0.45,
        origination_fee_pct=0,
        late_fee_pct=0.05,
        product_line=dagangan_product_line,
        product_profile=dagangan_product_profile,
        cashback_initial_pct=0,
        cashback_payment_pct=0
    )
    ProductLookup.objects.get_or_create(
        product_name="I.514-O.000-L.050-C1.000-C2.000-M",
        interest_rate=0.514,
        origination_fee_pct=0,
        late_fee_pct=0.05,
        product_line=dagangan_product_line,
        product_profile=dagangan_product_profile,
        cashback_initial_pct=0,
        cashback_payment_pct=0
    )
    ProductLineLoanPurpose.objects.get_or_create(
        product_line=dagangan_product_line,
        loan_purpose_id=1,
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_product_line_dagangan, migrations.RunPython.noop)
    ]
