# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-09-22 02:20
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting
from juloserver.channeling_loan.constants import FeatureNameConst

def add_intereset_setting_on_bss_rac(apps, schema_editor):
    featureSetting = FeatureSetting.objects.filter(
        feature_name=FeatureNameConst.BSS_CHANNELING_RISK_ACCEPTANCE_CRITERIA
    ).first()
    if featureSetting:
        parameters = featureSetting.parameters
        parameters["BSSINTEREST"] = 15
        parameters["DAYSINAYEAR"] = 360

        featureSetting.parameters = parameters
        featureSetting.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_intereset_setting_on_bss_rac, migrations.RunPython.noop),
    ]
