# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-09-13 06:54
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import StatusLookup
from juloserver.julo.statuses import CreditCardCodes


def load_status_lookups_julo_card_584(apps, schema_editor):
    status_code, status = (CreditCardCodes.CARD_BLOCKED_WRONG_PIN,
                           'Card blocked wrong pin')

    StatusLookup.objects.get_or_create(status_code=status_code, status=status)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(load_status_lookups_julo_card_584),
    ]
