# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-09-20 04:44
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.statuses import PaymentStatusCodes
from juloserver.julo.models import StatusLookup


def add_new_status_lookup_for_dpd_4(apps, schema_editor):
    status_lookups = [
        (StatusLookup.PAYMENT_4DPD_CODE, "4dpd"),
        (StatusLookup.LOAN_4DPD_CODE, "4dpd")
    ]
    
    for status_code, status in status_lookups:
        status_lookup = StatusLookup.objects.filter(status_code=status_code).first()
        if not status_lookup:
            StatusLookup.objects.create(status_code=status_code, status=status)

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_new_status_lookup_for_dpd_4,
            migrations.RunPython.noop),
    ]
