# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-09-21 07:06
from __future__ import unicode_literals

from django.db import migrations
from juloserver.grab.tasks import async_update_grab_excluded_old_repayment_loan


def run_retroload_for_grab_excluded_old_repayment_loan(apps, schema_editor):
    async_update_grab_excluded_old_repayment_loan()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(run_retroload_for_grab_excluded_old_repayment_loan, migrations.RunPython.noop),
    ]
