# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-09-30 09:59
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import MobileFeatureSetting
from juloserver.payment_point.constants import FeatureNameConst
from juloserver.payment_point.models import TransactionMethod
from juloserver.loan.constants import LoanJuloOneConstant

def feature_settings_for_transaction_method_highlight(app, schema_editor):
    mobile_feature_setting = MobileFeatureSetting.objects.filter(
        feature_name=FeatureNameConst.TRANSACTION_METHOD_HIGHLIGHT,
    ).last()
    if mobile_feature_setting:
        mobile_feature_setting.parameters[11] = {'is_active': True, 'limit_threshold': 0}
        mobile_feature_setting.save()

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(feature_settings_for_transaction_method_highlight,
            migrations.RunPython.noop
        )
    ]



