# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-10-14 11:08
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting
from juloserver.payment_point.constants import FeatureNameConst

def feature_setting_for_force_customer_train_ticket(app, schema_editor):
    feature_setting = FeatureSetting.objects.filter(
        feature_name=FeatureNameConst.FORCE_CUSTOMER_TRAIN_TICKET,
    )
    if not feature_setting:
        FeatureSetting.objects.create(
            feature_name=FeatureNameConst.FORCE_CUSTOMER_TRAIN_TICKET,
            is_active=False,
            parameters={},
            category="ppob",
            description="Force customer_id for testing purpose"
        )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            feature_setting_for_force_customer_train_ticket, migrations.RunPython.noop
        )
    ]
