# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-10-06 04:03
from __future__ import unicode_literals

from django.db import migrations

from juloserver.ecommerce.models import EcommerceConfiguration
from juloserver.settings.base import STATIC_URL


def add_juloshop_vospay_ecommerce_config(app, schema_editor):
    extra_config = {
        'logos': {
            'bukalapak': {
                'name': 'Bukalapak',
                'url': STATIC_URL + 'images/ecommerce/juloshop/bukalapak_text_logo_updated.png'
            },
            'jd_id': {
                'name': 'JD.ID',
                'url': STATIC_URL + 'images/ecommerce/juloshop/jdid_text_logo.png'
            }
        }
    }

    EcommerceConfiguration.objects.get(ecommerce_name='Julo Shop').update_safely(
        ecommerce_name='Julo Shop',
        selection_logo=STATIC_URL + 'images/ecommerce/juloshop/julo_shop_selection_logo_primary.png',
        background_logo='',
        color_scheme='#39bef3',
        url='https://store.vospay.id/julo?application_xid=',
        text_logo='',
        order_number=1,
        is_active=False,
        category_type='marketplace',
        extra_config=extra_config
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_juloshop_vospay_ecommerce_config, migrations.RunPython.noop)
    ]
