# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-10-19 09:25
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting


def remove_months_from_cashback_expired_config(apps, _schema_editor):
    cashback_expired_config = FeatureSetting.objects.get(feature_name='cashback_expired_configuration')
    cashback_expired_config.parameters.pop('months')
    cashback_expired_config.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(remove_months_from_cashback_expired_config,
                             migrations.RunPython.noop),
    ]
