# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-10-26 14:36
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def add_new_grab_intellix_call_feature_setting(apps, _schema_editor):
    data_to_be_created = {
        'feature_name': FeatureNameConst.GRAB_INTELIX_CALL,
        'is_active': False,
        'parameters': {
            "populate_schedule": "02:00",
            "send_schedule": "05:00"
        },
        'category': 'collection',
        'description': 'This configuration is to set the schedule when we should trigger grab intelix call'
    }
    FeatureSetting.objects.get_or_create(**data_to_be_created)


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_new_grab_intellix_call_feature_setting, migrations.RunPython.noop),
    ]
