# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-10-25 05:00
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting


def add_feature_setting_cashback_dpd30_switch(apps, _schema_editor):
    FeatureSetting.objects.create(
        feature_name='cashback_dpd30_pay_off',
        is_active=False,
        parameters={},
        category='cashback task setting',
        description='Decides if the daily cashback task is run or not'
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_feature_setting_cashback_dpd30_switch,
                             migrations.RunPython.noop),
    ]
