# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-10-25 11:01
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.otp.constants import SessionTokenAction, SessionTokenType


def init_otp_feature_setting_for_phone_register(apps, _schema_editor):
    action_type_setting = FeatureSetting.objects.filter(
        feature_name='otp_action_type').last()
    if action_type_setting:
        parameters = action_type_setting.parameters
        parameters.update({
            SessionTokenAction.PHONE_REGISTER: SessionTokenType.SHORT_LIVED,
        })
        action_type_setting.parameters = parameters
        action_type_setting.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            init_otp_feature_setting_for_phone_register, migrations.RunPython.noop
        ),
    ]
