# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-11-07 10:53
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting

def update_feature_otp_transaction_flow(apps, schema_editor):
    feature_setting, _ = FeatureSetting.objects.get_or_create(feature_name='otp_action_type')
    parameters = feature_setting.parameters or {}
    if 'transaction_pdam' not in parameters:
        parameters.update({
            "transaction_pdam": "long_lived",
        })
    feature_setting.parameters = parameters
    feature_setting.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(update_feature_otp_transaction_flow, migrations.RunPython.noop),
    ]
