# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-10-31 06:40
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst


def add_pin_error_message_setting(apps, schema_editor):
    pin_setting = FeatureSetting.objects.get_or_none(feature_name=FeatureNameConst.PIN_SETTING)
    if pin_setting:
        pin_setting.parameters['response_message'] = {
            'permanent_locked': (
                'Akun kamu diblokir permanen karena salah memasukkan informasi secara '
                'terus menerus. Kamu bisa hubungi CS untuk info lebih lanjut.'
            ),
            'temporary_locked': (
                'Akun kamu diblokir sementara selama {eta} '
                'karena salah memasukkan informasi. Silakan coba masuk kembali nanti.'
            ),
            'cs_contact_info': {
                'phone': ['02150919034', '02150919035'],
                'email': ['cs@julo.co.id']
            }
        }
        pin_setting.parameters['max_wait_time_mins'] = 15
        pin_setting.save()


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            add_pin_error_message_setting, migrations.RunPython.noop)
    ]
