# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-11-10 03:14
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import WorkflowStatusPath, Workflow
from juloserver.julo.constants import WorkflowConst
from juloserver.julo.statuses import ApplicationStatusCodes


def add_new_status_path_105_to_106_merchant_financing(apps, _schema_editor):
    workflow = Workflow.objects.filter(name=WorkflowConst.MERCHANT_FINANCING_WORKFLOW).first()
    if workflow:
        WorkflowStatusPath.objects.get_or_create(
            status_previous=105,
            status_next=106,
            type="graveyard",
            workflow=workflow
        )

class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_new_status_path_105_to_106_merchant_financing,
                             migrations.RunPython.noop)
    ]
