# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-12-02 09:51
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import (
    ProductLine, ProductProfile, ProductLookup, ProductLineLoanPurpose,
)
from juloserver.julo.product_lines import ProductLineCodes

def add_product_line_fishlog_and_koperasi_tunas_partners(apps, schema_editor):
    koperasi_tunas_product_line = ProductLine.objects.\
        filter(product_line_code=ProductLineCodes.KOPERASI_TUNAS).last()
    koperasi_tunas_product_profile = ProductProfile.objects.\
        filter(code=ProductLineCodes.KOPERASI_TUNAS).last()
    if koperasi_tunas_product_profile:
        koperasi_tunas_product_profile.update_safely(
            name='KOPERASI TUNAS',
            code=ProductLineCodes.KOPERASI_TUNAS,
            min_amount=1000000,
            max_amount=20000000,
            min_duration=1,
            max_duration=3,
            min_interest_rate=0.03,
            max_interest_rate=0.05,
            interest_rate_increment=0,
            payment_frequency='Monthly',
            min_origination_fee=0,
            max_origination_fee=0,
            late_fee=0.03,
            cashback_initial=0,
            cashback_payment=0,
            debt_income_ratio=0.3,
        )
    else:
        koperasi_tunas_product_profile, _ = ProductProfile.objects.get_or_create(
            name='KOPERASI TUNAS',
            code=ProductLineCodes.KOPERASI_TUNAS,
            min_amount=1000000,
            max_amount=20000000,
            min_duration=1,
            max_duration=3,
            min_interest_rate=0.03,
            max_interest_rate=0.05,
            interest_rate_increment=0,
            payment_frequency='Monthly',
            min_origination_fee=0,
            max_origination_fee=0,
            late_fee=0.03,
            cashback_initial=0,
            cashback_payment=0,
            debt_income_ratio=0.3,
        )
    if koperasi_tunas_product_line:
        koperasi_tunas_product_line.update_safely(product_line_type='KOPERASI TUNAS',
                                                  min_amount=1000000,
                                                  max_amount=20000000,
                                                  min_duration=1,
                                                  max_duration=3,
                                                  min_interest_rate=0.03,
                                                  max_interest_rate=0.05,
                                                  payment_frequency='Monthly',
                                                  product_profile=koperasi_tunas_product_profile)
    else:
        koperasi_tunas_product_line, _ = ProductLine.objects.get_or_create(
            product_line_code=ProductLineCodes.KOPERASI_TUNAS,
            product_line_type='KOPERASI TUNAS',
            min_amount=1000000,
            max_amount=20000000,
            min_duration=1,
            max_duration=3,
            min_interest_rate=0.03,
            max_interest_rate=0.05,
            payment_frequency='Monthly',
            product_profile=koperasi_tunas_product_profile
        )
    product_lookup = ProductLookup.objects.\
        filter(product_line=koperasi_tunas_product_line, product_profile=koperasi_tunas_product_profile).last()
    if product_lookup:
        product_lookup.update_safely(product_name="I.005-O.0035-L.050-C1.000-C2.000-M",
                                     interest_rate=0.6,
                                     origination_fee_pct=0.035,
                                     late_fee_pct=0.03,
                                     cashback_initial_pct=0,
                                     cashback_payment_pct=0)

    else:
        ProductLookup.objects.get_or_create(
            product_name="I.005-O.0035-L.050-C1.000-C2.000-M",
            interest_rate=0.6,
            origination_fee_pct=0.035,
            late_fee_pct=0.03,
            product_line=koperasi_tunas_product_line,
            product_profile=koperasi_tunas_product_profile,
            cashback_initial_pct=0,
            cashback_payment_pct=0
        )
    koperasi_product_line_loan_purpose = ProductLineLoanPurpose.objects.filter(
        product_line=koperasi_tunas_product_line
    ).last()
    if koperasi_product_line_loan_purpose:
        koperasi_product_line_loan_purpose.loan_purpose_id = 1
        koperasi_product_line_loan_purpose.save()
    else:
        ProductLineLoanPurpose.objects.get_or_create(
            product_line=koperasi_tunas_product_line,
            loan_purpose_id=1
        )
    fishlog_product_line = ProductLine.objects. \
        filter(product_line_code=ProductLineCodes.FISHLOG).last()
    fishlog_product_profile = ProductProfile.objects.\
        filter(code=ProductLineCodes.FISHLOG).last()
    if fishlog_product_profile:
        fishlog_product_profile.update_safely(
            name='FISHLOG',
            code=ProductLineCodes.FISHLOG,
            min_amount=1000000,
            max_amount=20000000,
            min_duration=1,
            max_duration=3,
            min_interest_rate=0.03,
            max_interest_rate=0.05,
            interest_rate_increment=0,
            payment_frequency='Monthly',
            min_origination_fee=0,
            max_origination_fee=0,
            late_fee=0.05,
            cashback_initial=0,
            cashback_payment=0,
            debt_income_ratio=0.3,
        )
    else:
        fishlog_product_profile, _ = ProductProfile.objects.get_or_create(
            name='FISHLOG',
            code=ProductLineCodes.FISHLOG,
            min_amount=1000000,
            max_amount=20000000,
            min_duration=1,
            max_duration=3,
            min_interest_rate=0.03,
            max_interest_rate=0.05,
            interest_rate_increment=0,
            payment_frequency='Monthly',
            min_origination_fee=0,
            max_origination_fee=0,
            late_fee=0.05,
            cashback_initial=0,
            cashback_payment=0,
            debt_income_ratio=0.3,
        )
    if fishlog_product_line:
        fishlog_product_line.update_safely(product_line_type='FISHLOG',
                                           min_amount=1000000,
                                           max_amount=20000000,
                                           min_duration=1,
                                           max_duration=3,
                                           min_interest_rate=0.03,
                                           max_interest_rate=0.05,
                                           payment_frequency='Monthly',
                                           product_profile=fishlog_product_profile)
    else:
        fishlog_product_line, _ = ProductLine.objects.get_or_create(
            product_line_code=ProductLineCodes.FISHLOG,
            product_line_type='FISHLOG',
            min_amount=1000000,
            max_amount=20000000,
            min_duration=1,
            max_duration=3,
            min_interest_rate=0.03,
            max_interest_rate=0.05,
            payment_frequency='Monthly',
            product_profile=fishlog_product_profile
        )
    fishlog_product_line_loan_purpose = ProductLineLoanPurpose.objects.filter(
        product_line=fishlog_product_line
    ).last()
    if fishlog_product_line_loan_purpose:
        fishlog_product_line_loan_purpose.loan_purpose_id = 1
        fishlog_product_line_loan_purpose.save()
    else:
        ProductLineLoanPurpose.objects.get_or_create(
            product_line=fishlog_product_line,
            loan_purpose_id=1,
        )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_product_line_fishlog_and_koperasi_tunas_partners, migrations.RunPython.noop)
    ]
