# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-11-24 12:20
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import WorkflowStatusPath

from juloserver.julo.models import Workflow
from juloserver.julo.constants import WorkflowConst


def add_135_paths(app, _schema_editor):
    """
    Add status path (100,105, 106, 135, ->135 reject application
    """
    workflow = Workflow.objects.filter(name=WorkflowConst.JULO_ONE).last()
    if workflow:
        WorkflowStatusPath.objects.get_or_create(
            status_previous=100,
            status_next=135,
            type="graveyard",
            workflow=workflow
        )

        WorkflowStatusPath.objects.get_or_create(
            status_previous=105,
            status_next=135,
            type="graveyard",
            workflow=workflow
        )

        WorkflowStatusPath.objects.get_or_create(
            status_previous=106,
            status_next=135,
            type="graveyard",
            workflow=workflow
        )

        WorkflowStatusPath.objects.get_or_create(
            status_previous=136,
            status_next=135,
            type="graveyard",
            workflow=workflow
        )

        WorkflowStatusPath.objects.get_or_create(
            status_previous=137,
            status_next=135,
            type="graveyard",
            workflow=workflow
        )

        WorkflowStatusPath.objects.get_or_create(
            status_previous=139,
            status_next=135,
            type="graveyard",
            workflow=workflow
        )


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_135_paths, migrations.RunPython.noop)
    ]