# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-01-06 07:57
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import MobileFeatureSetting
from juloserver.autodebet.constants import MobileFeatureNameConstant


def autodebet_reminder_feature_mobile_setting(apps, schema_editor):
    MobileFeatureSetting.objects.create(
        feature_name=MobileFeatureNameConstant.AUTODEBET_REMINDER_SETTING,
        parameters={
            'interval': 10,
            'title': 'Aktifkan Auto Debit, yuk!',
            'content': 'Nggak perlu khawatir lagi lupa bayar tagihan dan kena denda keterlambatan.\n '
                       'Yuk, nyalakan fitur Auto Debit sekarang!'
        },
        is_active=True
    )


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunPython(autodebet_reminder_feature_mobile_setting),
    ]
