# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-12-07 03:56
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import Onboarding


def add_new_onboarding_for_julostarter(apps, schema_editor):
    """
    Add new onboarding for JuloStarter

    Refer to this ticket:
    https://juloprojects.atlassian.net/browse/RUS1-1501
    """

    target_onboarding_id = 6
    onboarding = Onboarding.objects.filter(id=target_onboarding_id).exists()
    if not onboarding:
        Onboarding.objects.create(id=target_onboarding_id,
                                  description="JULO Starter form experiment",
                                  status=True)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_new_onboarding_for_julostarter, migrations.RunPython.noop)
    ]
