# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-09-22 09:24
from __future__ import unicode_literals

from builtins import range
from django.db import migrations

from juloserver.julo.models import Workflow, WorkflowStatusPath, ProductProfile
from juloserver.julo.models import ProductLine, ProductLineLoanPurpose


def add_workflow_julo_one(apps, _schema_editor):

    workflow = Workflow.objects.get(
        name="JuloOneWorkflow"
    )

    path_data = (
        [120, 133, 'graveyard'],
        [130, 133, 'graveyard'],
        [136, 133, 'graveyard'],
    )

    for old_status, new_status, path_type in path_data:
        WorkflowStatusPath.objects.filter(
            status_previous=old_status,
            status_next=new_status,
            workflow=workflow).update(type=path_type)

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_workflow_julo_one, migrations.RunPython.noop),
    ]
