# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-12-06 17:05
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.channeling_loan.constants import (
    FeatureNameConst,
    ChannelingConst,
)


def revamp_channeling_loan_config(apps, _schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.CHANNELING_LOAN_CONFIG,
        parameters={
            ChannelingConst.BSS: {
                "is_active": True,
                "general": {
                    "LENDER_NAME": "bss_channeling",
                    "BUYBACK_LENDER_NAME": "jh",
                    "EXCLUDE_LENDER_NAME": ["ska", "gfin", "helicap", "ska2"],
                    "INTEREST_PERCENTAGE": 15,
                    "DAYS_IN_YEAR": 360,
                    "CHANNELING_TYPE": ChannelingConst.API_CHANNELING_TYPE,
                },
                "rac": {
                    "TENOR": "Monthly",
                    "MAX_AGE": 59,
                    "MIN_AGE": 21,
                    "JOB_TYPE": ["Pegawai swasta", "Pegawai negeri", "Pengusaha"],
                    "MAX_LOAN": 15000000,
                    "MIN_LOAN": 500000,
                    "MAX_RATIO": 0.3,
                    "MAX_TENOR": 9,
                    "MIN_TENOR": 1,
                    "MIN_INCOME": 2000000,
                    "MIN_WORKTIME": 3,
                    "INCOME_PROVE": True,
                    "HAS_KTP_OR_SELFIE": True,
                    "MOTHER_MAIDEN_NAME": True,
                    "VERSION": 2,
                },
                "cutoff": {
                    "is_active": True,
                    "OPENING_TIME": {"hour": 7, "minute": 0, "second": 0},
                    "CUTOFF_TIME": {"hour": 19, "minute": 0, "second": 0},
                    "INACTIVE_DATE": [],
                    "INACTIVE_DAY": [],
                    "LIMIT": None,
                },
                "force_update": {
                    "is_active": True,
                    "VERSION": 2,
                },
                "whitelist": {
                    "is_active": False,
                    "APPLICATIONS": []
                }
            },
            ChannelingConst.BJB: {
                "is_active": True,
                "general": {
                    "LENDER_NAME": "bjb_channeling",
                    "BUYBACK_LENDER_NAME": "jh",
                    "EXCLUDE_LENDER_NAME": ["ska", "gfin", "helicap", "ska2"],
                    "INTEREST_PERCENTAGE": 14,
                    "DAYS_IN_YEAR": 360,
                    "CHANNELING_TYPE": ChannelingConst.MANUAL_CHANNELING_TYPE,
                },
                "rac": {
                    "TENOR": "Monthly",
                    "MAX_AGE": None,
                    "MIN_AGE": None,
                    "JOB_TYPE": [],
                    "MAX_LOAN": 20000000,
                    "MIN_LOAN": 1000000,
                    "MAX_RATIO": None,
                    "MAX_TENOR": None,
                    "MIN_TENOR": None,
                    "MIN_INCOME": None,
                    "MIN_WORKTIME": 24,
                    "INCOME_PROVE": True,
                    "HAS_KTP_OR_SELFIE": True,
                    "MOTHER_MAIDEN_NAME": True,
                    "VERSION": 2,
                },
                "cutoff": {
                    "is_active": True,
                    "OPENING_TIME": {"hour": 1, "minute": 0, "second": 0},
                    "CUTOFF_TIME": {"hour": 9, "minute": 0, "second": 0},
                    "INACTIVE_DATE": [],
                    "INACTIVE_DAY": ["Saturday", "Sunday"],
                    "LIMIT": 50,
                },
                "force_update": {
                    "is_active": True,
                    "VERSION": 2,
                },
                "whitelist": {
                    "is_active": False,
                    "APPLICATIONS": []
                }
            },
            ChannelingConst.FAMA: {
                "is_active": True,
                "general": {
                    "LENDER_NAME": "fama_channeling",
                    "BUYBACK_LENDER_NAME": "jh",
                    "EXCLUDE_LENDER_NAME": ["ska", "gfin", "helicap", "ska2"],
                    "INTEREST_PERCENTAGE": 14,
                    "DAYS_IN_YEAR": 360,
                    "CHANNELING_TYPE": ChannelingConst.MANUAL_CHANNELING_TYPE,
                },
                "rac": {
                    "TENOR": "Monthly",
                    "MAX_AGE": None,
                    "MIN_AGE": None,
                    "JOB_TYPE": [],
                    "MAX_LOAN": 20000000,
                    "MIN_LOAN": 1000000,
                    "MAX_RATIO": None,
                    "MAX_TENOR": None,
                    "MIN_TENOR": None,
                    "MIN_INCOME": None,
                    "MIN_WORKTIME": 24,
                    "INCOME_PROVE": True,
                    "HAS_KTP_OR_SELFIE": True,
                    "MOTHER_MAIDEN_NAME": True,
                    "VERSION": 2,
                },
                "cutoff": {
                    "is_active": True,
                    "OPENING_TIME": {"hour": 1, "minute": 0, "second": 0},
                    "CUTOFF_TIME": {"hour": 9, "minute": 0, "second": 0},
                    "INACTIVE_DATE": [],
                    "INACTIVE_DAY": ["Saturday", "Sunday"],
                    "LIMIT": 50,
                },
                "force_update": {
                    "is_active": True,
                    "VERSION": 2,
                },
                "whitelist": {
                    "is_active": False,
                    "APPLICATIONS": []
                }
            }
        },
        is_active=True,
        category="channeling_loan",
        description="All channeling_loan configuration"
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(revamp_channeling_loan_config, migrations.RunPython.noop),
    ]
