# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-06-16 08:36
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst


def new_feature_setting_for_lendeast(apps, _schema_editor):
    bonza_feature = FeatureSetting.objects.create(
        feature_name="lendeast_config",
        is_active=False,
        parameters={'minimum_osp': 100600000000, 'page_size': 5}, # 100.600.000.000
        category="lendeast",
        description="config for lendeast",
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(new_feature_setting_for_lendeast,
                             migrations.RunPython.noop),
    ]
