# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-09-22 09:24
from __future__ import unicode_literals

from builtins import range
from django.db import migrations

from juloserver.julo.models import Workflow, WorkflowStatusPath


def add_workflow_path_x120_julo_starter(apps, _schema_editor):

    workflow = Workflow.objects.get(
        name="JuloStarterWorkflow"
    )

    path_data = (
        [120, 135, 'graveyard'],
        [120, 121, 'happy'],
    )

    for old_status, new_status, path_type in path_data:
        WorkflowStatusPath.objects.get_or_create(
            status_previous=old_status,
            status_next=new_status,
            workflow=workflow,
            type=path_type)

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_workflow_path_x120_julo_starter, migrations.RunPython.noop),
    ]