# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-01-06 08:51
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting, FraudHotspot

def add_fraud_hotspot_list(apps, schema_editor):
    feature_data = FeatureSetting.objects.filter(
        feature_name='fraud_hotspot').get()

    bulk_data = [] 
    for hotspot in feature_data.parameters['hotspots']:
        bulk_data.append(FraudHotspot(latitude=hotspot[0], longitude=hotspot[1], radius=hotspot[2]))
    
    FraudHotspot.objects.bulk_create(bulk_data, batch_size=2000)
    feature_data.description = "this feature deprecated please use fraud_hotspot table"
    feature_data.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_fraud_hotspot_list, migrations.RunPython.noop)
    ]
