# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-12-26 14:23
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import WorkflowConst
from juloserver.julo.models import Workflow, WorkflowStatusNode, WorkflowStatusPath


def create_julo_starter_workflow_status_105_handler(apps, _schema_editor):
    workflow = Workflow.objects.get(name=WorkflowConst.JULO_STARTER)
    WorkflowStatusNode.objects.get_or_create(
        status_node=105,
        handler='JuloStarter105Handler',
        workflow=workflow
    )
    WorkflowStatusPath.objects.get_or_create(
        status_previous=100,
        status_next=105,
        type="happy",
        workflow=workflow
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_julo_starter_workflow_status_105_handler, migrations.RunPython.noop),
    ]