# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-01-03 09:42
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import WorkflowConst
from juloserver.julo.models import WorkflowStatusPath, Workflow


def run(apps, schema_editor):
    paths = (
        (131, 'detour'),
        (133, 'graveyard'),
        (135, 'graveyard'),
        (136, 'detour'),
        (137, 'graveyard'),
        (140, 'happy')
    )

    j_starter = Workflow.objects.filter(name=WorkflowConst.JULO_STARTER).last()

    for path, p_type in paths:
        exists = WorkflowStatusPath.objects.filter(
            status_previous=121,
            status_next=path,
            workflow=j_starter
        ).exists()
        if exists:
            continue

        WorkflowStatusPath.objects.create(
            workflow=j_starter,
            status_previous=121,
            status_next=path,
            type=p_type
        )


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunPython(run, migrations.RunPython.noop),
    ]
