# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-01-08 06:17
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def add_new_dana_late_fee_feature_setting(apps, _schema_editor):
    data_to_be_created = {
        'feature_name': FeatureNameConst.DANA_LATE_FEE,
        'is_active': True,
        'parameters': {
            "late_fee": 0.0015
        },
        'category': 'dana',
        'description': 'This configuration is used to adjust dana late fee'
    }
    FeatureSetting.objects.get_or_create(**data_to_be_created)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            add_new_dana_late_fee_feature_setting,
            migrations.RunPython.noop
        ),
    ]
