# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-01-16 07:46
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting


class Migration(migrations.Migration):
    def create_feature_settings_gopay_onboarding_page(apps, _schema_editor):
        FeatureSetting.objects.create(
            feature_name='gopay_onboarding_page',
            parameters=[
                {
                    'benefit_title': '',
                    'benefit_content': '',
                    'benefit_icon': '',
                },
                {
                    'benefit_title': '',
                    'benefit_content': '',
                    'benefit_icon': '',
                },
                {
                    'benefit_title': '',
                    'benefit_content': '',
                    'benefit_icon': '',
                }
            ],
            is_active=True,
            category='repayment',
            description='Gopay onboarding page'
        )
    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_feature_settings_gopay_onboarding_page, migrations.RunPython.noop),
    ]
