# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-01-09 02:21
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting, MobileFeatureSetting

def update_feature_otp_transaction_flow(apps, schema_editor):
    feature_setting, _ = FeatureSetting.objects.get_or_create(feature_name='otp_action_type')
    parameters = feature_setting.parameters or {}
    if 'transaction_train_ticket' not in parameters:
        parameters.update({
            "transaction_train_ticket": "long_lived",
        })
    feature_setting.parameters = parameters
    feature_setting.save()


def update_feature_setting_for_transaction_otp_pdam(apps, schema_editor):
    feature_setting, created = MobileFeatureSetting.objects.get_or_create(feature_name='otp_setting')
    parameters = feature_setting.parameters or {}
    transaction_settings = parameters['transaction_settings'] or {}
    transaction_settings['transaction_train_ticket'] = {
        "is_active": True,
        "minimum_transaction": 0
    }
    parameters.update({
        "transaction_document": "",
        "transaction_settings": transaction_settings
    })
    feature_setting.parameters = parameters
    feature_setting.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(update_feature_otp_transaction_flow, migrations.RunPython.noop),
        migrations.RunPython(
             update_feature_setting_for_transaction_otp_pdam, migrations.RunPython.noop),
    ]
