# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-01-13 08:49
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def create_juloshop_white_list_feature_setting(apps, _schema_editor):
    FeatureSetting.objects.create(
        is_active=True,
        feature_name=FeatureNameConst.JULOSHOP_WHITELIST,
        category='ecommerce',
        description='white list graduation for specific application',
        parameters={
            'application_ids': [],
        }
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_juloshop_white_list_feature_setting, migrations.RunPython.noop),
    ]
