# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-01-26 11:17
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def create_feature_setting_gopay(apps, schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.GOPAY_ACTIVATION_LINKING,
        parameters={},
        is_active=True,
        category="collections",
        description="Gopay activation linking"
    )

    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.WHITELIST_GOPAY,
        parameters={"account_id": []},
        is_active=False,
        category="collections",
        description="Whitelist application who can use Gopay"
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_feature_setting_gopay, migrations.RunPython.noop),
    ]
