# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-02-09 06:44
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst


def run_to_execute(apps, schema_editor):
    """
    Detail can be following this card:
    https://juloprojects.atlassian.net/browse/UND-381
    """

    is_exist = FeatureSetting.objects.filter(feature_name=FeatureNameConst.CONFIG_FLOW_LIMIT_JSTARTER).exists()
    if not is_exist:
        FeatureSetting.objects.create(
            feature_name=FeatureNameConst.CONFIG_FLOW_LIMIT_JSTARTER,
            is_active=True,
            parameters={
                "full_dv": "disabled",
                "partial_limit": "enabled"
            },
            category="application",
            description="Switch flow for getting limit Julo Starter"
        )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(run_to_execute, migrations.RunPython.noop)
    ]
