# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-11-06 10:16
from __future__ import unicode_literals

from builtins import str
from builtins import range

from django.db import migrations

from juloserver.julo.models import MandiriVirtualAccountSuffix



def load_mandiri_virtual_account_suffix(apps, schema_editor):
        batch_size = 1000
        start_range = 1
        end_range = 10001

        va_suffix_objs = (
            MandiriVirtualAccountSuffix(
                mandiri_virtual_account_suffix=str(va_suffix_val).zfill(8)
            ) for va_suffix_val in range(start_range, end_range)
        )
        
        MandiriVirtualAccountSuffix.objects.bulk_create(va_suffix_objs, batch_size)
    

    

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(load_mandiri_virtual_account_suffix),
    ]
