# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-12-23 07:01
from __future__ import unicode_literals

import logging

from django.contrib.auth.models import User

from django.db import migrations
from juloserver.julo.models import Customer, Partner
from juloserver.julo.partners import PartnerConstant
from juloserver.partnership.constants import PartnershipTypeConstant
from juloserver.partnership.models import PartnershipType
from juloserver.partnership.services.services import process_register_partner


logger = logging.getLogger(__name__)


def add_new_partner_juloshop(apps, scheme_editor):
    juloshop_partner = Partner.objects.get_or_none(name=PartnerConstant.JULOSHOP)
    if not juloshop_partner:
        # make a partnership type row
        partnership_type, _ = PartnershipType.objects.get_or_create(
            partner_type_name=PartnershipTypeConstant.JULOSHOP
        )

        # juloshop info, dummy for now for staging
        email = "finance-payment@juloshopgroup.com"
        partner_data = {
            "username": PartnerConstant.JULOSHOP,
            "email": email,
            "partnership_type": partnership_type.id,
            "callback_url": "",
            "callback_token": "",
        }

        # generate rows in ops.auth_user & ops.partner & ops.partnership_config
        process_register_partner(partner_data)

        # create customer for juloshop
        user = User.objects.get(username=PartnerConstant.JULOSHOP)
        Customer.objects.create(user=user, email=email, phone='082222222222')


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_new_partner_juloshop, migrations.RunPython.noop),
    ]
