# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-01-09 02:21
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst

def update_feature_sphinx(apps, schema_editor):
    feature_setting = FeatureSetting.objects.get(
    	feature_name=FeatureNameConst.SPHINX_THRESHOLD
    )
    if not feature_setting:
    	return

    parameters = feature_setting.parameters or {}
    if 'partial_limit_dv' not in parameters:
        parameters.update({
            "partial_limit_dv": 0.3,
        })
    feature_setting.parameters = parameters
    feature_setting.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(update_feature_sphinx, migrations.RunPython.noop)
    ]
