# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-02-13 04:14
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting
from juloserver.education.constants import FeatureNameConst


def add_feature_setting_education_faq(apps, schema_editor):
    faq_parameter = [
        {
            "type": "link",
            "title": "Tambah sekolah baru",
            "content": (
                "Jika sekolah yang kamu cari tidak ada "
                "kamu bisa mendaftarkan sekolah kamu disini"
            ),
            "btn_text": "Request Sekolah Baru",
            "url": (
                "https://docs.google.com/forms/d/e/"
                "1FAIpQLSc4yxclVKOyEL46yVpNbcYzl3fNMP9yTnxK7GSmqqzzShUkoA/viewform"
            )
        },
        {
            "type": "text",
            "title": "FAQ 1",
            "content": "Ini jawaban untuk faq 1",
            "btn_text": "",
            "url": ""
        },
    ]

    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.EDUCATION_FAQ,
        parameters=faq_parameter,
        is_active=True,
        description='FAQ for education',
        category='education'
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_feature_setting_education_faq, migrations.RunPython.noop),
    ]
