# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-02-13 06:20
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import WorkflowConst
from juloserver.julo.models import Workflow, WorkflowStatusPath


def run(apps, schema_editor):
    workflow = Workflow.objects.filter(name=WorkflowConst.JULO_STARTER).last()
    exists = WorkflowStatusPath.objects.filter(
        workflow=workflow,
        status_previous=108,
        status_next=121
    ).exists()

    if exists:
        return

    WorkflowStatusPath.objects.create(
        workflow=workflow,
        status_previous=108,
        status_next=121,
        type="happy",
        is_active=True,
        customer_accessible=False,
        agent_accessible=True
    )


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunPython(run, migrations.RunPython.noop),
    ]
