# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-02-15 18:19
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import MobileFeatureSetting
from juloserver.julo.constants import MobileFeatureNameConst
from juloserver.payment_point.constants import TransactionMethodCode


def feature_settings_for_transaction_method_whitelist(app, schema_editor):
    MobileFeatureSetting.objects.create(
        feature_name=MobileFeatureNameConst.TRANSACTION_METHOD_WHITELIST,
        is_active=True,
        parameters={
            TransactionMethodCode.EDUCATION.name: {"application_ids": []},
        }
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            feature_settings_for_transaction_method_whitelist, migrations.RunPython.noop
        ),
    ]
