# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-02-15 08:25
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import Onboarding


def add_new_onboarding_id_for_julo_360_experiment(apps, schema_editor):
    """
    Add new onboarding for JULO 360 Experiment
    Refer to this ticket:
    https://juloprojects.atlassian.net/browse/UND-533
    """

    target_onboarding_id = 8
    update_value = {'description': "JULO 360 Experiment",
                    'status': True}
    Onboarding.objects.update_or_create(id=target_onboarding_id,
                                        defaults=update_value)


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_new_onboarding_id_for_julo_360_experiment, migrations.RunPython.noop)
    ]
