# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-02-22 04:21
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def create_feature_setting(*args):
    FeatureSetting.objects.get_or_create(
        feature_name=FeatureNameConst.FRAUD_VELOCITY_MODEL_GEOHASH,
        defaults={
            'is_active': False,
            'parameters': {
                'skip_verified_geohash_day': 3,
                'check_period_day': 7,
                'check_period_compare_day': 14,
                'threshold_total_app_in_period': 6,
                'threshold_rate_app_in_period': 2,
                'flag_period_day': 21,
            },
            'category': 'fraud_detection',
            'description': 'Fraud velocity model geohash for Faster fraud hotspot detection.'
        }
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_feature_setting, migrations.RunPython.noop)
    ]
