# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-07-20 07:52
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst


def add_new_feature_settings_order_payment_methods_by_groups(apps, _schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.ORDER_PAYMENT_METHODS_BY_GROUPS,
        is_active=True,
        parameters={
            'bank_va_group': ['bank bca', 'bank bri', 'bank bni', 'bank mandiri', 'permata bank', 'bank maybank'],
            'retail_group': ['indomaret', 'alfamart'],
            'e_wallet_group': ['gopay', 'gopay tokenization', 'ovo'],
            'autodebet_group': ['autodebet bca', 'autodebet bri'],
            'new_repayment_channel_group': {'end_date': '25-07-2023', 'new_repayment_channel': []}
        },
        category='repayment',
        description="Govern The Order Of Groups For Each Payment Method")


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_new_feature_settings_order_payment_methods_by_groups, migrations.RunPython.noop),
    ]
