# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-03-07 08:20
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import WorkflowConst
from juloserver.julo.models import WorkflowStatusPath, Workflow
from juloserver.julo.statuses import ApplicationStatusCodes


def run(apps, schema_editor):
    j_starter = Workflow.objects.get(name=WorkflowConst.JULO_STARTER)

    query = {
        'workflow': j_starter,
        'status_previous': ApplicationStatusCodes.FORM_PARTIAL,
        'status_next': ApplicationStatusCodes.APPLICATION_FLAGGED_FOR_FRAUD
    }
    exists = WorkflowStatusPath.objects.filter(**query).exists()
    if not exists:
        WorkflowStatusPath.objects.create(**query)


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunPython(run, migrations.RunPython.noop),
    ]
