# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-03-13 08:17
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting


def run_me(apps, schema_editor):
    FeatureSetting.objects.create(
        feature_name='bank_validation',
        is_active=True,
        parameters={
            "similarity_threshold": 0.4
        },
        description='https://juloprojects.atlassian.net/browse/UND-331',
    )

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(run_me, migrations.RunPython.noop)
    ]
