# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-03-16 05:23
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import ChangeReason
from juloserver.julo.statuses import ApplicationStatusCodes


def add_change_reason_115(*args):
    ChangeReason.objects.get_or_create(
        reason='Manual flag for fraud suspicious',
        status_id=ApplicationStatusCodes.APPLICATION_FLAGGED_FOR_FRAUD_SUSPICIOUS
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_change_reason_115, migrations.RunPython.noop)
    ]
