# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-03-06 08:34
from __future__ import unicode_literals
from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


from django.db import migrations

def create_new_feature_hide_menu_crm(apps, schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.CRM_HIDE_MENU,
        is_active=True,
        parameters={
            "roles": [
            	"bo_sd_verifier",
            	"bo_data_verifier",
            ],
            "menu": [
            	"sd_tab"
            ],
        }
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_new_feature_hide_menu_crm, migrations.RunPython.noop)
    ]
