# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-03-13 08:16
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def add_is_enable_fraud_verification_paramter(*args):
    feature_setting = FeatureSetting.objects.filter(
        feature_name=FeatureNameConst.FRAUD_VELOCITY_MODEL_GEOHASH,
    ).last()
    if not feature_setting:
        return

    if feature_setting.parameters is None:
        feature_setting.parameters = {}

    feature_setting.parameters['is_enable_fraud_verification'] = False
    feature_setting.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_is_enable_fraud_verification_paramter, migrations.RunPython.noop)
    ]
