# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-03-13 09:12
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import WorkflowConst
from juloserver.julo.models import Workflow, WorkflowStatusNode


def create_workflow_status_node(apps, schema_editor):
    workflow = Workflow.objects.filter(name=WorkflowConst.JULO_STARTER).last()
    node = (133, "JuloStarter133Handler",)

    is_exist = WorkflowStatusNode.objects.filter(
        status_node=node[0],
        handler=node[1],
        workflow=workflow
    ).exists()

    if is_exist:
        return

    WorkflowStatusNode.objects.create(
        status_node=node[0],
        handler=node[1],
        workflow=workflow
    )


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            create_workflow_status_node,
            migrations.RunPython.noop
        ),
    ]
