# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-03-25 07:34
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.statuses import ApplicationStatusCodes
from juloserver.julo.utils import upload_file_to_oss
from juloserver.streamlined_communication.models import (InfoCardButtonProperty,
                                                         CardProperty,
                                                         InfoCardProperty,
                                                         StreamlinedMessage,
                                                         StreamlinedCommunication)
from juloserver.streamlined_communication.constant import CommunicationPlatform
from juloserver.julo.models import StatusLookup, Image
from django.conf import settings
from juloserver.streamlined_communication.constant import CardProperty as CardPropertyConst

# Setup values
R_BUTTON = 'R.BUTTON'
NAME_IMAGE = 'mini_pict_offer_to_j1.png'
NAME_BUTTON = 'button_background_offer_to_j1.png'
PRODUCT_NAME = 'jstarter'
DESCRIPTION_STREAM = 'retroload_julo_turbo_infocard_offer_j1'


class ImageNames(object):
    BG_107 = 'info-card/CARD_BACKGROUND_IMAGE_WEB190.png'
    SIDE_NAME_IMAGE = 'info-card/{}'.format(NAME_IMAGE)
    BUTTON = 'info-card/{}'.format(NAME_BUTTON)


def create_image(image_source_id, image_type, image_url):
    image = Image()
    image.image_source = image_source_id
    image.image_type = image_type
    image.url = image_url
    image.save()


def set_nonactive_for_old_infocard(_apps, _schema_editor):
    """
    To set non-active if infocard x107 is exists.
    """

    info_card_107 = StreamlinedCommunication.objects.filter(
        status_code=ApplicationStatusCodes.OFFER_REGULAR,
        is_active=True,
    ).last()
    if info_card_107:
        info_card_107.update_safely(is_active=False)


def retroload_infocard_julo_turbo_107_status(_apps, _schema_editor):

    # data infocard
    data_to_be_loaded = [
        {
            'status': ApplicationStatusCodes.OFFER_REGULAR,
            'additional_condition': CardPropertyConst.JULO_TURBO_OFFER_TO_REGULAR,
            'title': 'Pengajuan JULO Turbo Belum Berhasil',
            'content': 'Kamu masih bisa ajukan JULO Kredit Digital, kok.'
            		   ' Ajukan sekarang!',
            'button': ['Ajukan JULO Kredit Digital'],
            'button_name': [R_BUTTON],
            'click_to': ['to_upgrade_form'],
            'template_type': '1',
            'card_number': 1,
            'text_colour': '#ffffff',
            'title_colour': '#ffffff',
            'background_url': ImageNames.BG_107,
            'additional_images': [ImageNames.SIDE_NAME_IMAGE],
            'button_url': [ImageNames.BUTTON]
        },
    ]

    # select type card
    for data in data_to_be_loaded:
        button_1_properties = {'card_type': '1',
                               'title': data['title'],
                               'title_color': data['title_colour'],
                               'text_color': data['text_colour'],
                               'card_order_number': data['card_number']}

        button_2_properties = {'card_type': '2',
                               'title': data['title'],
                               'title_color': data['title_colour'],
                               'text_color': data['text_colour'],
                               'card_order_number': data['card_number']}

        button_3a_properties = {'card_type': '3a',
                                'card_destination': data['click_to'],
                                'title': data['title'],
                                'title_color': data['title_colour'],
                                'text_color': data['text_colour'],
                                'card_order_number': data['card_number']}

        button_3b_properties = {'card_type': '3b',
                                'title': data['title'],
                                'title_color': data['title_colour'],
                                'text_color': data['text_colour'],
                                'card_order_number': data['card_number']}

        if data['template_type'] == '1':
            info_card = InfoCardProperty.objects.create(**button_1_properties)
        elif data['template_type'] == '2':
            info_card = InfoCardProperty.objects.create(**button_2_properties)
        elif data['template_type'] == '3':
            info_card = InfoCardProperty.objects.create(**button_3b_properties)
        else:
            info_card = None

        button_info_card = dict()

        if data['button']:
            for idx, image_url in enumerate(data['button']):
                button_info_card['info_card_property'] = info_card
                button_info_card['text'] = data['button'][idx]
                button_info_card['button_name'] = data['button_name'][idx]
                button_info_card['action_type'] = CardProperty.APP_DEEPLINK
                button_info_card['destination'] = data['click_to'][idx]
                button_info_card['text_color'] = data['text_colour']

                button, _ = InfoCardButtonProperty.objects.get_or_create(**button_info_card)
                create_image(button.id, CardProperty.IMAGE_TYPE.button_background_image, data['button_url'][idx])

        data_streamlined_message = {'message_content': data['content'],
                                    'info_card_property': info_card}
        message = StreamlinedMessage.objects.create(**data_streamlined_message)
        status = StatusLookup.objects.filter(status_code=data['status']).last()
        data_for_streamlined_communication = {'status_code': status,
                                              'status': data['status'],
                                              'communication_platform': CommunicationPlatform.INFO_CARD,
                                              'message': message,
                                              'description': DESCRIPTION_STREAM,
                                              'is_active': True,
                                              'product': PRODUCT_NAME,
                                              'extra_conditions': data['additional_condition']}

        streamlined_communication = StreamlinedCommunication.objects.create(**data_for_streamlined_communication)

        # create image for background
        if data['background_url']:
            create_image(info_card.id, CardProperty.IMAGE_TYPE.card_background_image, data['background_url'])

        if data['additional_images']:
            additional_image_url = data['additional_images']
            additional_image_url = additional_image_url[0]
            create_image(info_card.id, CardProperty.IMAGE_TYPE.card_optional_image, str(additional_image_url))

    # upload image
    images_list = (NAME_IMAGE, NAME_BUTTON)
    for image_name in images_list:
        remote_path = 'info-card/{}'.format(image_name)
        upload_file_to_oss(
            settings.OSS_PUBLIC_ASSETS_BUCKET,
            settings.STATICFILES_DIRS[0] + '/images/info_card/{}'.format(image_name),
            remote_path
        )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(set_nonactive_for_old_infocard, migrations.RunPython.noop),
        migrations.RunPython(retroload_infocard_julo_turbo_107_status, migrations.RunPython.noop)
    ]
