# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-03-23 09:57
from __future__ import unicode_literals

from django.db import migrations

from juloserver.payment_point.constants import TransactionMethodCode
from juloserver.payment_point.models import TransactionMethod


def change_education_transaction_method_fe_display_name(_apps, _schema_editor):
    education_transaction_method = TransactionMethod.objects.get(
        id=TransactionMethodCode.EDUCATION.code
    )

    education_transaction_method.fe_display_name = 'Biaya Pendidikan'
    education_transaction_method.save()


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunPython(change_education_transaction_method_fe_display_name,
                             migrations.RunPython.noop),
    ]
