# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-03-21 15:50
from __future__ import unicode_literals
from juloserver.followthemoney.models import LenderApproval

from django.db import migrations

def update_lender_approval_expire_time(apps, schema_editor):
    LenderApproval.objects.all().update(
        expired_start_time='08:00:00',
        expired_end_time='18:00:00',
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(update_lender_approval_expire_time, migrations.RunPython.noop)
    ]
