# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-03-21 03:10
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst


def update_grab_defence_feature_setting(apps, schema_editor):
    FeatureSetting.objects.update_or_create(
        feature_name=FeatureNameConst.GRAB_DEFENCE_FRAUD_SCORE,
        defaults={
            'parameters': {'is_verdict_api_enabled': False},
            'is_active': True,
            'description': 'Grab Defence Integration fraud score feature',
        }
    )


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            update_grab_defence_feature_setting, migrations.RunPython.noop),
    ]
