# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-03-30 07:25
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def add_new_grab_intellix_call_feature_setting(apps, _schema_editor):
    data_to_be_created = {
        'feature_name': FeatureNameConst.GRAB_FILE_TRANSFER_CALL,
        'is_active': False,
        'parameters': {
            "populate_loan_schedule": "21:30",
            "populate_daily_txn_schedule": "21:30"
        },
        'category': 'grab_file_transfer',
        'description': 'This configuration is to set the schedule when we should trigger task tp populate grab file transfer'
    }
    FeatureSetting.objects.get_or_create(**data_to_be_created)


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_new_grab_intellix_call_feature_setting, migrations.RunPython.noop),
    ]
