# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-04-02 13:46
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.statuses import ApplicationStatusCodes
from juloserver.julo.utils import upload_file_to_oss
from juloserver.streamlined_communication.models import (InfoCardButtonProperty,
                                                         CardProperty,
                                                         InfoCardProperty,
                                                         StreamlinedMessage,
                                                         StreamlinedCommunication)
from juloserver.streamlined_communication.constant import CommunicationPlatform
from juloserver.julo.models import StatusLookup, Image
from django.conf import settings
from juloserver.streamlined_communication.constant import CardProperty as CardPropertyConst

# infocard type 2
NAME_BG_INFO_TEXT = 'bg_for_info_text.png'

# infocard type 1
NAME_BG_SUCCESS_UPGRADE = 'background_blue_and_square_white.png'
NAME_IMAGE_SUCCESS_UPGRADE = 'icon_people_and_money.png'
NAME_BUTTON = 'button_dark_blue.png'
R_BUTTON = 'R.BUTTON'

PRODUCT_NAME = 'jstarter'
DESCRIPTION_STREAM = 'retroload_julo_turbo_infocard'


class ImageNames(object):
    DIR = 'info-card'
    BG_INFO_TEXT = '{}/{}'.format(DIR, NAME_BG_INFO_TEXT)
    BG_SQUARE_WHITE = '{}/{}'.format(DIR, NAME_BG_SUCCESS_UPGRADE)

    SIDE_NAME_IMAGE = '{}/{}'.format(DIR, NAME_IMAGE_SUCCESS_UPGRADE)
    BUTTON = '{}/{}'.format(DIR, NAME_BUTTON)


def create_image(image_source_id, image_type, image_url):
    Image.objects.create(
        image_source=image_source_id,
        image_type=image_type,
        url=image_url
    )


def retroload_infocard_for_julo_turbo(_apps, _schema_editor):

    # data infocard when upgrade still in progress
    # application is J!
    data_to_be_loaded = [
        {
            'status': ApplicationStatusCodes.OFFER_ACCEPTED_BY_CUSTOMER,
            'additional_condition': CardPropertyConst.ACTIVATION_CALL_JTURBO_UPGRADE,
            'title': 'Proses Verifikasi Telepon 📞',
            'content': 'Pihak JULO akan segera menghubungimu untuk proses upgrade ke JULO Kredit Digital. '
                       'Pastikan nomor HP kamu aktif saat dihubungi, ya!',
            'button': [],
            'click_to': [],
            'template_type': '2',
            'card_number': 1,
            'text_colour': '#ffffff',
            'title_colour': '#ffffff',
            'background_url': ImageNames.BG_INFO_TEXT,
            'additional_images': [],
            'button_url': []
        },
        {
            'status': ApplicationStatusCodes.APPLICATION_DENIED,
            'additional_condition': CardPropertyConst.REJECTION_JTURBO_UPGRADE,
            'title': 'Permohonan Upgrade Gagal',
            'content': 'Kamu belum memenuhi kriteria yang ada dari analisa tim JULO. '
                       'Kamu bisa ajukan upgrade lagi dalam 2 minggu. '
                       'Tenang, kamu masih bisa menggunakan limit JULO Turbo',
            'button': [],
            'click_to': [],
            'template_type': '2',
            'card_number': 1,
            'text_colour': '#ffffff',
            'title_colour': '#ffffff',
            'background_url': ImageNames.BG_INFO_TEXT,
            'additional_images': [ImageNames.SIDE_NAME_IMAGE],
            'button_url': [ImageNames.BUTTON]
        },
        {
            'status': ApplicationStatusCodes.LOC_APPROVED,
            'additional_condition': CardPropertyConst.SUCCESS_JTURBO_UPGRADE,
            'title': 'Akunmu sudah Upgrade ke JULO Kredit Digital',
            'content': 'Yuk, rutin transaksi di JULO agar limitmu dapat meningkat!',
            'button': ['Pinjam Tunai'],
            'button_name': [R_BUTTON],
            'click_to': ['product_transfer_self'],
            'template_type': '1',
            'card_number': 1,
            'text_colour': '#ffffff',
            'title_colour': '#ffffff',
            'background_url': ImageNames.BG_SQUARE_WHITE,
            'additional_images': [ImageNames.SIDE_NAME_IMAGE],
            'button_url': [ImageNames.BUTTON]
        },
    ]

    # select type card
    for data in data_to_be_loaded:
        button_1_properties = {'card_type': '1',
                               'title': data['title'],
                               'title_color': data['title_colour'],
                               'text_color': data['text_colour'],
                               'card_order_number': data['card_number']}

        button_2_properties = {'card_type': '2',
                               'title': data['title'],
                               'title_color': data['title_colour'],
                               'text_color': data['text_colour'],
                               'card_order_number': data['card_number']}

        button_3a_properties = {'card_type': '3a',
                                'card_destination': data['click_to'],
                                'title': data['title'],
                                'title_color': data['title_colour'],
                                'text_color': data['text_colour'],
                                'card_order_number': data['card_number']}

        button_3b_properties = {'card_type': '3b',
                                'title': data['title'],
                                'title_color': data['title_colour'],
                                'text_color': data['text_colour'],
                                'card_order_number': data['card_number']}

        if data['template_type'] == '1':
            info_card = InfoCardProperty.objects.create(**button_1_properties)
        elif data['template_type'] == '2':
            info_card = InfoCardProperty.objects.create(**button_2_properties)
        elif data['template_type'] == '3':
            info_card = InfoCardProperty.objects.create(**button_3b_properties)
        else:
            info_card = None

        button_info_card = dict()

        if data['button']:
            for idx, image_url in enumerate(data['button']):
                button_info_card['info_card_property'] = info_card
                button_info_card['text'] = data['button'][idx]
                button_info_card['button_name'] = data['button_name'][idx]
                button_info_card['action_type'] = CardProperty.APP_DEEPLINK
                button_info_card['destination'] = data['click_to'][idx]
                button_info_card['text_color'] = data['text_colour']

                button, _ = InfoCardButtonProperty.objects.get_or_create(**button_info_card)
                create_image(button.id, CardProperty.IMAGE_TYPE.button_background_image, data['button_url'][idx])

        data_streamlined_message = {'message_content': data['content'],
                                    'info_card_property': info_card}
        message = StreamlinedMessage.objects.create(**data_streamlined_message)
        status = StatusLookup.objects.filter(status_code=data['status']).last()
        data_for_streamlined_communication = {'status_code': status,
                                              'status': data['status'],
                                              'communication_platform': CommunicationPlatform.INFO_CARD,
                                              'message': message,
                                              'description': DESCRIPTION_STREAM,
                                              'is_active': True,
                                              'product': PRODUCT_NAME,
                                              'extra_conditions': data['additional_condition']}

        streamlined_communication = StreamlinedCommunication.objects.create(**data_for_streamlined_communication)

        # create image for background
        if data['background_url']:
            create_image(info_card.id, CardProperty.IMAGE_TYPE.card_background_image, data['background_url'])

        if data['additional_images']:
            additional_image_url = data['additional_images']
            additional_image_url = additional_image_url[0]
            create_image(info_card.id, CardProperty.IMAGE_TYPE.card_optional_image, str(additional_image_url))

    # upload image
    images_list = (NAME_IMAGE_SUCCESS_UPGRADE, NAME_BG_INFO_TEXT, NAME_BG_SUCCESS_UPGRADE, NAME_BUTTON)
    for image_name in images_list:
        remote_path = 'info-card/{}'.format(image_name)
        upload_file_to_oss(
            settings.OSS_PUBLIC_ASSETS_BUCKET,
            settings.STATICFILES_DIRS[0] + '/images/info_card/{}'.format(image_name),
            remote_path
        )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(retroload_infocard_for_julo_turbo, migrations.RunPython.noop)
    ]
