# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-04-03 14:35
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting, FeatureNameConst


def execute(apps, schema_editor):
    is_exists = FeatureSetting.objects.filter(feature_name=FeatureNameConst.SESSION_LIMIT_FOR_INFOCARD).exists()
    if not is_exists:
        FeatureSetting.objects.create(
            feature_name=FeatureNameConst.SESSION_LIMIT_FOR_INFOCARD,
            is_active=True,
            category='application',
            description='To manage session limit daily for infocard',
            parameters={
                'session_limit_daily': 3
            }
        )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(execute, migrations.RunPython.noop),
    ]
