# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-04-03 09:10
from __future__ import unicode_literals

import datetime
from datetime import timedelta

from django.db import migrations

from juloserver.followthemoney.models import LenderCurrent, LenderApproval


def update_lender_approval_delay(apps, schema_editor):
    lender_currents = LenderCurrent.objects.filter(lender_name__in=('ska', 'ska2'))
    for lender in lender_currents:
        partner = lender.user.partner
        lender_approvals = LenderApproval.objects.filter(partner=partner)
        for lender_approval in lender_approvals:
            time_delay = lender_approval.delay
            updated_delay = datetime.datetime.combine(
                datetime.datetime.today(), time_delay) + timedelta(minutes=2)
            lender_approval.delay = updated_delay
            lender_approval.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(update_lender_approval_delay, migrations.RunPython.noop)
    ]
