# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-03-29 15:32
from __future__ import unicode_literals

from django.db import migrations

from juloserver.moengage.management.commands import bulk_update_moengage_for_va_attribute


def bulk_update_moengage_va(apps, _schema_editor):
    bulk_update_moengage_for_va_attribute.Command().handle()

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(bulk_update_moengage_va, migrations.RunPython.noop)
    ]
