# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-07-20 07:52
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst


def create_feature_settings_block_bni_va_auto_generation(apps, _schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.BLOCK_BNI_VA_AUTO_GENERATION,
        parameters={},
        is_active=True,
        category="repayment",
        description="Blocking BNI VA Auto Generation"
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_feature_settings_block_bni_va_auto_generation, migrations.RunPython.noop),
    ]
