# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-04-05 04:30
from __future__ import unicode_literals

from django.db import migrations, transaction

from juloserver.julo.models import ProductLine, LoanPurpose, ProductLineLoanPurpose
from juloserver.julo.product_lines import ProductLineCodes


def add_balance_consolidation_loan_purpose_with_product_line(apps, _schema_editor):
    product = ProductLine.objects.get_or_none(pk=ProductLineCodes.J1)
    if product:
        with transaction.atomic():
            loan_purpose = LoanPurpose.objects.create(purpose='Perpindahan Limit')
            ProductLineLoanPurpose.objects.create(
                product_line=product,
                loan_purpose=loan_purpose
            )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            add_balance_consolidation_loan_purpose_with_product_line, migrations.RunPython.noop),
    ]
