# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-04-04 10:06
from __future__ import unicode_literals

from django.db import migrations

from juloserver.merchant_financing.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def create_axiata_bulk_upload_options_setting(apps, _schema_editor):
    parameters = {
        'menus': {
            'Register': True,
            'Approval': True,
            'Disbursement': True,
            'Rejection': True,
            'Repayment': True
        }
    }

    FeatureSetting.objects.create(
        is_active=True,
        feature_name=FeatureNameConst.AXIATA_BULK_UPLOAD,
        parameters=parameters,
        category='axiata_bulk_upload',
        description='Show and hide axiata bulk upload options'
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_axiata_bulk_upload_options_setting,
                             migrations.RunPython.noop)
    ]
