# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-04-05 06:47
from __future__ import unicode_literals

from django.db import migrations

from juloserver.personal_data_verification.constants import FeatureNameConst

from juloserver.julo.models import FeatureSetting


def add_dukcapil_toggle_setting(apps, _schema_editor):
    FeatureSetting.objects.get_or_create(
        is_active=True,
        feature_name=FeatureNameConst.DUKCAPIL_BYPASS_TOGGLE,
        description="Configuration for DUKCAPIL bypassing toggle",
        parameters={'dukcapil_bypass': False}
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_dukcapil_toggle_setting, migrations.RunPython.noop),
    ]
