# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-04-14 09:36
from __future__ import unicode_literals

from django.db import migrations

from juloserver.dana.constants import DanaBasePath
from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def add_dana_massive_log_feature_settings(apps, schema_editor):
    feature_setting = FeatureSetting.objects.filter(
        feature_name=FeatureNameConst.DANA_MASSIVE_LOG,
    ).first()

    if not feature_setting:
        created_data = {
            'feature_name': FeatureNameConst.DANA_MASSIVE_LOG,
            'is_active': True,
            'parameters': {
                DanaBasePath.loan: True,
                DanaBasePath.repayment: True,
            },
            'category': 'partner',
            'description': 'Dana massive log for each function'
        }
        FeatureSetting.objects.create(**created_data)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_dana_massive_log_feature_settings, migrations.RunPython.noop),
    ]
