# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-04-17 04:31
from __future__ import unicode_literals

from django.db import migrations


from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def add_dana_pdf_password_feature_setting(apps, schema_editor):
    feature_setting = FeatureSetting.objects.filter(
        feature_name=FeatureNameConst.DANA_AGREEMENT_PASSWORD,
    ).first()

    if not feature_setting:
        created_data = {
            'feature_name': FeatureNameConst.DANA_AGREEMENT_PASSWORD,
            'is_active': False,
            'parameters': {},
            'category': 'partner',
            'description': 'Enable or disable dana agreement using password'
        }
        FeatureSetting.objects.create(**created_data)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_dana_pdf_password_feature_setting, migrations.RunPython.noop),
    ]
