# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-04-14 07:58
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting


def run(apps, schema_editor):
    setting = FeatureSetting.objects.filter(feature_name="second_check_notif_jstarter").last()
    params = setting.parameters
    params["dukcapil_true_heimdall_true_full_dv"] = {
        'body': 'Prosesnya sebentar banget, kok! Udah nggak sabar mau tau limit kamu, ya?',
        'title': 'Limitmu Sedang Dihitung, Nih!',
        'destination': 'julo_starter_second_check_ok_full_dv'
    }
    setting.update_safely(parameters=params)


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunPython(run, migrations.RunPython.noop)
    ]
