# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-05-06 06:09
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import ChangeReason, StatusLookup
from juloserver.julo_starter.constants import JuloStarter190RejectReason


def run(apps, schema_editor):
    status = StatusLookup.objects.filter(status_code=190).last()
    reason = JuloStarter190RejectReason.REJECT_DV

    exists = ChangeReason.objects.filter(
        reason=reason,
        status=status
    ).exists()
    if not exists:
        ChangeReason.objects.create(
            reason=reason,
            status=status
        )

    status = StatusLookup.objects.filter(status_code=190).last()
    reason = JuloStarter190RejectReason.REJECT_FRAUD

    exists = ChangeReason.objects.filter(
        reason=reason,
        status=status
    ).exists()
    if not exists:
        ChangeReason.objects.create(
            reason=reason,
            status=status
        )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(run, migrations.RunPython.noop),
    ]
