# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-05-05 08:52
from __future__ import unicode_literals

from django.db import migrations

from juloserver.balance_consolidation.constants import BalanceConsolidationFeatureName
from juloserver.julo.models import FeatureSetting


def create_balance_cons_feature_settings(apps, _schema_editor):
    parameters = {
        'token_expiry_days': 30
    }

    FeatureSetting.objects.create(
        feature_name=BalanceConsolidationFeatureName.BALANCE_CONS_TOKEN_CONFIG,
        is_active=True,
        description='Feature Setting to control Token config',
        parameters=parameters,
        category='balance_consolidation'
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_balance_cons_feature_settings, migrations.RunPython.noop)
    ]
