# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-05-22 10:41
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def update_fraud_velocity_model_geohash_setting(*args):
    setting = FeatureSetting.objects.get_or_none(
        feature_name=FeatureNameConst.FRAUD_VELOCITY_MODEL_GEOHASH,
    )
    if not setting:
        return

    setting.parameters['geohash8'] = {
        "flag_period_day": 21,
        "check_period_day": 7,
        "check_period_compare_day": 14,
        "threshold_rate_app_in_period": 2,
        "threshold_total_app_in_period": 6
    }

    setting.parameters['geohash9'] = {
        "flag_period_day": 21,
        "check_period_day": 14,
        "check_period_compare_day": 28,
        "threshold_rate_app_in_period": 3,
        "threshold_total_app_in_period": 10
    }
    setting.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(update_fraud_velocity_model_geohash_setting, migrations.RunPython.noop)
    ]
