# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-05-25 07:31
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst

def create_trigger_rescrape_and_force_logout_feature_setting(app, _schema_editor):
    parameters = {
        'rescrape' : True,
        'force_logout' : True,
    }

    FeatureSetting.objects.get_or_create(
        feature_name=FeatureNameConst.TRIGGER_RESCRAPE_AND_FORCE_LOGOUT,
        is_active=True,
        parameters=parameters,
        category='application',
        description='Turn on/off scheduler rescrape and force logout'
    )
class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_trigger_rescrape_and_force_logout_feature_setting, migrations.RunPython.noop),
    ]
