# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-05-14 15:20
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.constants import FeatureNameConst

def add_credit_matrix_repeat_setting(apps, schema_editor):
    FeatureSetting = apps.get_model("julo", "FeatureSetting")
    FeatureSetting.objects.get_or_create(
        is_active=False,
        feature_name=FeatureNameConst.CREDIT_MATRIX_REPEAT_SETTING,
        category="credit_matrix_repeat_setting",
        description="Enable Credit Matrix Repeat",
    )

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_credit_matrix_repeat_setting, migrations.RunPython.noop)
    ]
