# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-05-30 10:08
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def add_feature_setting_for_robocall_grab(app, _schema_editor):
    FeatureSetting.objects.get_or_create(
        is_active=True,
        feature_name=FeatureNameConst.GRAB_ROBOCALL_SETTING,
        parameters={
            "default": {"outstanding_amount": 5000000},
            "robocall_batch_size": 1000
        }
    )

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_feature_setting_for_robocall_grab, migrations.RunPython.noop),
    ]
