# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-06-02 08:24
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst, ExperimentConst
from juloserver.julo.models import FeatureSetting, ExperimentSetting


def run(app, schema_editor):
    exists = FeatureSetting.objects.filter(feature_name=FeatureNameConst.ACTIVATION_CALL_BYPASS).exists()
    if exists:
        return
    es = ExperimentSetting.objects.filter(code=ExperimentConst.ACTIVATION_CALL_BYPASS).last()
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.ACTIVATION_CALL_BYPASS,
        is_active=es.is_active,
        description=es.name,
        parameters=es.criteria
    )

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(run, migrations.RunPython.noop),

    ]
