# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-05-31 10:29
from __future__ import unicode_literals

from django.db import migrations

from django.conf import settings

from juloserver.julo.utils import get_oss_public_url

from juloserver.julo.models import MobileFeatureSetting
from juloserver.julo.constants import MobileFeatureNameConst


def insert_jstarter_rejection_page_message_feature_setting(apps, schema_editor):
    """
    Detail can be following this card:
    https://juloprojects.atlassian.net/browse/UND-1056
    """
    base_url = get_oss_public_url(settings.OSS_PUBLIC_ASSETS_BUCKET, 'julo-turbo/')
    if not MobileFeatureSetting.objects.filter(
        feature_name=MobileFeatureNameConst.JSTARTER_REJECTION_PAGE_MESSAGE
    ).exists():
        MobileFeatureSetting.objects.create(
            feature_name=MobileFeatureNameConst.JSTARTER_REJECTION_PAGE_MESSAGE,
            is_active=True,
            parameters={
                "reject_first_check": {
                    "title": "Yah, Form JULO Turbo Tidak Tersedia Untukmu",
                    "body": "Coba ajukan lagi 31 hari ke depan, ya!",
                    "button": "Kembali Ke Halaman Awal",
                    "image": base_url + "rejection-1.png"
                },
                "reject_second_check": {
                    "title": "Kamu Belum Bisa Membuat Akun JULO Turbo",
                    "body": "Kamu belum memenuhi kriteria. Coba buat dan ajukan lagi dalam 31 hari ke depan, ya!",
                    "button": "Kembali Ke Halaman Awal",
                    "image": base_url + "rejection-1.png"
                 },
                "offer_j1_first_check": {
                    "title": "Yah, Form JULO Turbo Tidak Tersedia Untukmu",
                    "body": "Tenang, kamu masih bisa coba ajukan JULO Kredit Digital, kok! Yuk, ajukan sekarang!",
                    "button": "Ajukan JULO Kredit Digital",
                    "image": base_url + "rejection-1.png"
                },
                "offer_j1_second_check" : {
                    "title": "Kamu Belum Bisa Membuat Akun JULO Turbo",
                    "body": "Tenang, kamu masih bisa coba ajukan JULO Kredit Digital, kok! Yuk, ajukan sekarang!",
                    "button": "Ajukan JULO Kredit Digital",
                    "image": base_url + "rejection-1.png"
                }
            }
        )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(insert_jstarter_rejection_page_message_feature_setting, migrations.RunPython.noop),
    ]
