# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-05-31 02:45
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def run(app, schema_editor):
    shopee_setting = FeatureSetting.objects.filter(
        feature_name=FeatureNameConst.SHOPEE_SCORING
    ).last()

    parameters = shopee_setting.parameters
    parameters['blacklist_reason_code'] = [100, 101, 102, 103, 104, 105, 106]

    shopee_setting.update_safely(parameters=parameters)


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunPython(run, migrations.RunPython.noop),
    ]
