# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-06-16 09:16
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting
from juloserver.autodebet.constants import FeatureNameConst


def create_config_insufficient_balance_turn_off(app, _schema_editor):
    parameters = {
        'BCA': 6,
    }

    FeatureSetting.objects.get_or_create(
        feature_name=FeatureNameConst.INSUFFICIENT_BALANCE_TURN_OFF,
        is_active=True,
        parameters=parameters,
        category='autodebet',
        description='Config autodebet to govern deduction failed in a row config'
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_config_insufficient_balance_turn_off,
                             migrations.RunPython.noop),
    ]
