# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-06-16 05:43
from __future__ import unicode_literals

from django.db import migrations

from juloserver.minisquad.constants import FeatureNameConst, IntelixTeam
from juloserver.julo.models import FeatureSetting


def create_feature_setting_for_handling_dialer_alert(apps, _schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.HANDLING_DIALER_ALERT,
        is_active=True,
        parameters=dict(
            current_bucket=IntelixTeam.CURRENT_BUCKET_V2,
            bucket_improved=IntelixTeam.ALL_BUCKET_IMPROVED
        ),
        category='collections',
        description='Data on parameters will sent alert to slack',
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            create_feature_setting_for_handling_dialer_alert, 
            migrations.RunPython.noop),
    ]
