# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-06-07 03:44
from __future__ import unicode_literals

from django.db import migrations
from juloserver.streamlined_communication.models import NeoBannerCard
from juloserver.julo.utils import upload_file_to_oss
from juloserver.julo.models import Image
from django.conf import settings


class ImageNames(object):
    BANNER_105 = 'neo-banner/JULO-System_Icon_24-01.jpg'
    BANNER_131 = 'neo-banner/JULO-System_Icon_24-02.jpg'
    BANNER_132 = 'neo-banner/JULO-System_Icon_24-03.jpg'
    BANNER_141 = 'neo-banner/JULO-System_Icon_24-01.jpg'
    EXTENDED_BANNER = 'neo-banner/In_App_Approval_Potential_Limit_Illustration.png'


def create_image(image_source_id, image_type, image_url):
    image = Image()
    image.image_source = image_source_id
    image.image_type = image_type
    image.url = image_url
    image.save()


def retroload_neobanner_j1(_apps, _schema_editor):

    # data infocard
    data_to_be_loaded = [
        {
            'statuses': '[105]',
            'product': 'J1',
            'template_card': 'B_INFO',
            'top_image': ImageNames.BANNER_105,
            'top_title': 'Udah Gak Sabar Pakai Limitmu, Ya?',
            'top_message': 'Cek berkala aplikasi JULO kamu untuk tahu apakah akunmu siap digunakan, oke?',
            'button_text': 'Akunmu sedang diverifikasi',
            'button_action': None,
            'extended_image': None,
            'extended_title': None,
            'extended_message': None,
            'extended_button_text': None,
            'extended_button_action': None,
        },
        {
            'statuses': '[131]',
            'product': 'J1',
            'template_card': 'B_BUTTON',
            'top_image': ImageNames.BANNER_131,
            'top_title': 'Yuk, Cek Data dan Upload Dokumenmu!',
            'top_message': 'Makin cepat kamu lengkapi, makin cepat juga kamu dapat limit, lho!',
            'button_text': 'Lengkapi Sekarang',
            'button_action': 'document_submission',
            'extended_image': ImageNames.EXTENDED_BANNER,
            'extended_title': 'Kalau udah di lengkapi, kamu bisa dapat limit hingga',
            'extended_message': 'Rp. 10.000.000',
            'extended_button_text': 'Selengkapnya',
            'extended_button_action': 'pontential_limit_desc',
        },
        {
            'statuses': '[132,134]',
            'product': 'J1',
            'template_card': 'B_INFO',
            'top_image': ImageNames.BANNER_132,
            'top_title': 'Santai, Datamu Lagi Diverifikasi',
            'top_message': 'Cek kembali status pengajuanmu maksimum dalam 1 hari kerja, ya!',
            'button_text': 'Akunmu sedang diverifikasi',
            'button_action': None,
            'extended_image': ImageNames.EXTENDED_BANNER,
            'extended_title': 'Pasti kamu hepi, limit yang bisa kamu dapatkan hingga',
            'extended_message': 'Rp. 10.000.000',
            'extended_button_text': 'Selengkapnya',
            'extended_button_action': 'pontential_limit_desc',
        },
        {
            'statuses': '[141]',
            'product': 'J1',
            'template_card': 'B_INFO',
            'top_image': ImageNames.BANNER_141,
            'top_title': 'Udah Gak Sabar Pakai Limitmu, Ya?',
            'top_message': 'Cek berkala aplikasi JULO kamu untuk tahu apakah akunmu siap digunakan, oke?',
            'button_text': 'Akunmu sedang diverifikasi',
            'button_action': None,
            'extended_image': ImageNames.EXTENDED_BANNER,
            'extended_title': 'Pasti kamu hepi, kamu bisa dapat limit hingga',
            'extended_message': 'Rp. 10.000.000',
            'extended_button_text': 'Selengkapnya',
            'extended_button_action': 'pontential_limit_desc',
        },
    ]

    # select type card
    for data in data_to_be_loaded:    
        neo_banner_card = NeoBannerCard.objects.create(**data)

        if data['top_image']:
            create_image(neo_banner_card.id, 'NEO_BANNER_TOP_BACKGROUND_IMAGE', data['top_image'])

        if data['extended_image']:
            create_image(neo_banner_card.id, 'NEO_BANNER_EXTENDED_BACKGROUND_IMAGE', data['extended_image'])


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(retroload_neobanner_j1, migrations.RunPython.noop)
    ]
