# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-06-08 09:59
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import (
    WorkflowStatusPath,
    WorkflowConst,
    Workflow
)


def execute(apps, schema_editor):

    workflow = Workflow.objects.filter(name=WorkflowConst.JULO_ONE).last()
    data_to_save = {
        'status_previous': 131,
        'status_next': 106,
        'type': 'detour',
        'is_active': True,
        'workflow': workflow,
    }
    is_exist = WorkflowStatusPath.objects.filter(**data_to_save).exists()
    if not is_exist:
        WorkflowStatusPath.objects.create(**data_to_save)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(execute, migrations.RunPython.noop)
    ]
