# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-06-06 09:17
from __future__ import unicode_literals

from django.db import migrations

from juloserver.followthemoney.models import LenderCurrent
from juloserver.followthemoney.services import generate_lender_signature
from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst


def create_new_certificate_bss(apps, schema_editor):
    lender = LenderCurrent.objects.get_or_none(lender_name='bss_channeling')
    if lender:
        generate_lender_signature(lender=lender, signature_key='lender')


def update_signature_key_configuration_bss(apps, schema_editor):
    feature_setting = FeatureSetting.objects.filter(
        feature_name=FeatureNameConst.SIGNATURE_KEY_CONFIGURATION).last()
    if not feature_setting:
        return

    lender = LenderCurrent.objects.get_or_none(lender_name='bss_channeling')
    if lender:
        feature_setting.parameters['users'][str(lender.user.id)] = 'lender'
        feature_setting.save()


def update_lender_info_bss(apps, schema_editor):
    lender = LenderCurrent.objects.get_or_none(lender_name='bss_channeling')
    lender.poc_name = 'Mike Bani Riza'
    lender.poc_position = 'Kepala Divisi FI'
    lender.lender_address = 'Gedung Sampoerna Strategic Square Nort Tower, lantai Mezzanine, Jl. Jend. Sudirman Kav 45-46 Jakarta Selatan'
    lender.company_name = 'PT Bank Sahabat Sampoerna'
    lender.license_number = 8120310252109
    lender.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(update_lender_info_bss, migrations.RunPython.noop),
        migrations.RunPython(create_new_certificate_bss, migrations.RunPython.noop),
        migrations.RunPython(update_signature_key_configuration_bss, migrations.RunPython.noop),
    ]
