# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-06-15 07:31
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import StatusLookup


def create_status_128(apps, schema_editor):
    StatusLookup.objects.get_or_create(
        status_code=StatusLookup.CUSTOMER_IGNORES_CALLS,
        status="Customer ignores calls",
        handler="JuloOne128Handler"
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_status_128, migrations.RunPython.noop),
    ]
