# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-01-09 02:21
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.personal_data_verification.constants import FeatureNameConst


def update_feature_dukcapil(apps, schema_editor):
    feature_setting = FeatureSetting.objects.get(
    	feature_name=FeatureNameConst.DUKCAPIL_VERIFICATION
    )
    if not feature_setting:
    	return

    parameters = feature_setting.parameters or {}
    if 'low_balance_quota_alert' not in parameters:
        parameters.update({
            "low_balance_quota_alert": 27000,
        })
    feature_setting.parameters = parameters
    feature_setting.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(update_feature_dukcapil, migrations.RunPython.noop)
    ]
