# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-07-13 06:43
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def add_holdout_shopee_config(apps, schema_editor):
    setting = FeatureSetting.objects.filter(
        feature_name=FeatureNameConst.SHOPEE_SCORING
    ).last()

    existing_parameters = setting.parameters
    new_parameters = {
        "holdout": {
            "percentage": 10,
            "per_requests": 10
        }
    }

    parameters = {**existing_parameters, **new_parameters}
    setting.update_safely(parameters=parameters)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_holdout_shopee_config, migrations.RunPython.noop),
    ]
