# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-07-21 09:15
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst


def add_liveness_detection_feature_setting(apps, schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.SMILE_LIVENESS_DETECTION,
        is_active=False,
        parameters={
            'skip_application_failed': True,
            'passive_threshold': 0.8,
            'smile_threshold': 1.0,
            'timeout_retry': 2,
            'timeout': 5,
            'retry': 3,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_liveness_detection_feature_setting, migrations.RunPython.noop)
    ]

