# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-07-20 04:33
from __future__ import unicode_literals

from django.db import migrations
from django.utils import timezone
from dateutil.relativedelta import relativedelta
from juloserver.julo.constants import ExperimentConst
from juloserver.julo.models import ExperimentSetting

def add_mahasiswa_binary_experiment(apps, schema_editor):
    current_date = timezone.localtime(timezone.now())
    ExperimentSetting.objects.create(
        is_active=False,
        code=ExperimentConst.JOB_TYPE_MAHASISWA_BINARY,
        name="Binary check mahasiswa job type",
        start_date=current_date,
        end_date=current_date + relativedelta(years=2),
        schedule="",
        action="",
        type="application",
        criteria={
            "application_id": "#last:0,2,4,6,8"
        }
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_mahasiswa_binary_experiment, migrations.RunPython.noop)
    ]
