# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-07-18 02:02
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import (
    FeatureSetting,
)
from juloserver.julo.constants import (
    FeatureNameConst,
)


def execute(apps, schema_editor):

    if not FeatureSetting.objects.filter(
        feature_name=FeatureNameConst.SPHINX_NO_BPJS_THRESHOLD
    ).exists():
        FeatureSetting.objects.create(
            feature_name=FeatureNameConst.SPHINX_NO_BPJS_THRESHOLD,
            is_active=False,
            category='application',
            description='Configuration for customer no BPJS',
            parameters={
                "high_score_operator": ">=",
                "high_score_threshold": 0.85,
                "medium_score_operator": ">",
                "medium_score_threshold": 0.8,
                "holdout": 50
            }
        )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(execute, migrations.RunPython.noop)
    ]
