# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-07-11 09:21
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting
from juloserver.early_limit_release.constants import FeatureNameConst


def add_new_early_limit_release_fs(apps, schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.EARLY_LIMIT_RELEASE_REPAYMENT_SIDE,
        is_active=False,
        parameters={},
        description='Setting to turn on/off early limit release feature in repayment side',
        category='early_limit_release'
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_new_early_limit_release_fs, migrations.RunPython.noop),
    ]
