# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-07-31 08:10
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import (
    Workflow, WorkflowStatusPath
)
from juloserver.julo.constants import WorkflowConst


def add_new_work_flow_for_axiata(apps, _schema_editor):
    workflow = Workflow.objects.get(
        name=WorkflowConst.MF_STANDARD_PRODUCT_WORKFLOW,
        desc="this is a workflow for merchant_financing web app",
        is_active=True,
        handler="PartnershipMfWebAppWorkflowHandler"
    )

    WorkflowStatusPath.objects.get_or_create(
        status_previous=0,
        status_next=100,
        type="happy",
        workflow=workflow
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_new_work_flow_for_axiata, migrations.RunPython.noop),
    ]
