# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-07-25 09:21
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import MobileFeatureSetting
from juloserver.payback.constants import MobileFeatureNameConst


def mobile_feature_settings_gopay_init_redirect_url(app, schema_editor):
    MobileFeatureSetting.objects.create(
        feature_name=MobileFeatureNameConst.GOPAY_INIT_REDIRECT_URL,
        is_active=True,
        parameters={"url": "https://www.julo.co.id/"}
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            mobile_feature_settings_gopay_init_redirect_url, migrations.RunPython.noop
        ),
    ]
