# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-07-26 04:43
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.payback.constants import FeatureSettingNameConst


def feature_settings_gopay_change_url(app, schema_editor):
    FeatureSetting.objects.get_or_create(
        feature_name=FeatureSettingNameConst.GOPAY_CHANGE_URL,
        is_active=False,
        description="gopay rediraction link",
        category="repayment",
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            feature_settings_gopay_change_url, migrations.RunPython.noop
        ),
    ]
