# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-08-11 10:09
from __future__ import unicode_literals

from django.db import migrations

from juloserver.autodebet.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def create_autodebet_and_whitelist_feature_mandiri(apps, _schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.AUTODEBET_MANDIRI,
        parameters={},
        is_active=False,
        category="repayment",
        description="Autodebet MANDIRI"
    )

    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.WHITELIST_AUTODEBET_MANDIRI,
        parameters={"applications": []},
        is_active=False,
        category="repayment",
        description="Whitelist application who can use Autodebet MANDIRI"
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_autodebet_and_whitelist_feature_mandiri,
                             migrations.RunPython.noop),
    ]
