# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-08-18 06:28
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def add_grab_payment_gateway_ratio(apps, schema_editor):
    FeatureSetting.objects.get_or_create(
        is_active=True,
        feature_name=FeatureNameConst.GRAB_PAYMENT_GATEWAY_RATIO,
        category="grab payment gateway",
        parameters={
            'xfers_ratio': '100%',
            'ac_ratio': '0%'
        },
        description="for grab payment gateway disbursement ratio")


class Migration(migrations.Migration):


    operations = [
        migrations.RunPython(add_grab_payment_gateway_ratio, migrations.RunPython.noop)
    ]
