# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-09-05 05:21
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def add_bca_inquiry_snap(apps, schema_editor):
    FeatureSetting.objects.get_or_create(
        feature_name=FeatureNameConst.BCA_INQUIRY_SNAP,
        is_active=False,
        description='This feature is to enable/disable bca inquiry with SNAP',
        category='account payment',
        parameters=''
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_bca_inquiry_snap, migrations.RunPython.noop),
    ]
