# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-09-01 08:13
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User
import random
import string

from juloserver.julo.models import Partner
from juloserver.api_token.models import ExpiryToken
from juloserver.integapiv1.constants import BCA_SNAP_PARTNER_NAME


def create_partner_bca_snap(apps, schema_editor):
    hash_password = make_password(
        ''.join([random.choice(string.hexdigits) for _ in range(12)])
    )
    user, _ = User.objects.get_or_create(
        username=BCA_SNAP_PARTNER_NAME,
        email='bca@example.com',
        defaults={'password': hash_password},
    )

    partner, _ = Partner.objects.get_or_create(
        user=user,
        name=BCA_SNAP_PARTNER_NAME,
        is_disbursement_to_distributor_bank_account=False,
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_partner_bca_snap, migrations.RunPython.noop),
    ]
