# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-08-31 02:32
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst


def update_nexmo_phone_number_fs(_apps, _schema_editor):
    robocall_setting = FeatureSetting.objects.filter(
        feature_name=FeatureNameConst.LOAN_PHONE_ROTATION_ROBOCALL,
    ).last()
    if robocall_setting:
        params = robocall_setting.parameters
        list_phone_numbers = (
            params['high_season']['phone_number_list'] + params['low_season']['phone_number_list']
        )
        robocall_setting.update_safely(
            parameters= {
                'list_phone_numbers': list_phone_numbers
            }
        )

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(update_nexmo_phone_number_fs, migrations.RunPython.noop)
    ]
