# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-09-11 04:31
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def add_feature_setting_for_high_risk_asn_tower_check(apps, _schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.HIGH_RISK_ASN_TOWER_CHECK,
        is_active=False,
        parameters={
            'mycroft_threshold_min': 0.1,
            'mycroft_threshold_max': 0.9,
        },
        category='fraud',
        description='This is setting to turn on or off high risk ASN check in handle_iti.'
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_feature_setting_for_high_risk_asn_tower_check, migrations.RunPython.noop),
    ]
