# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-08-25 05:00
from __future__ import unicode_literals

from django.contrib.auth.models import Group, User
from django.db import migrations

from juloserver.julo.models import (
    Customer,
    ProductProfile,
    ProductLine,
    ProductLookup,
    ProductLineLoanPurpose,
    Partner,
)

from juloserver.julo.product_lines import ProductLineCodes
from juloserver.portal.object.bulk_upload.constants import (
    MerchantFinancingCSVUploadPartner,
    MerchantFinancingCSVUploadPartnerDueDateType,
)

from django.conf import settings

class PaymentConst:
    PAYMENT_FREQUENCY = 'Monthly'

def add_product_line_efishery_jawara(apps, schema_editor):
    efishery_jawara_product_profile = ProductProfile.objects.filter(code=ProductLineCodes.EFISHERY_JAWARA).last()
    efishery_jawara_product_line = ProductLine.objects.filter(product_line_code=ProductLineCodes.EFISHERY_JAWARA).last()

    if efishery_jawara_product_profile:
        efishery_jawara_product_profile.update_safely(
            name=MerchantFinancingCSVUploadPartner.EFISHERY_JAWARA,
            code=ProductLineCodes.EFISHERY_JAWARA,
            min_amount=1000000,
            max_amount=1000000000,
            min_duration=1,
            max_duration=3,
            min_interest_rate=0.03,
            max_interest_rate=0.05,
            interest_rate_increment=0,
            payment_frequency=PaymentConst.PAYMENT_FREQUENCY,
            min_origination_fee=0,
            max_origination_fee=0,
            late_fee=0.05,
            cashback_initial=0,
            cashback_payment=0,
            debt_income_ratio=0.3,
            origination_fee_increment=0,
            is_active=True,
            is_initial=False,
            is_product_exclusive=False,
        )
    else:
        efishery_jawara_product_profile, _ = ProductProfile.objects.get_or_create(
            name=MerchantFinancingCSVUploadPartner.EFISHERY_JAWARA,
            code=ProductLineCodes.EFISHERY_JAWARA,
            min_amount=1000000,
            max_amount=1000000000,
            min_duration=1,
            max_duration=3,
            min_interest_rate=0.03,
            max_interest_rate=0.05,
            interest_rate_increment=0,
            payment_frequency=PaymentConst.PAYMENT_FREQUENCY,
            min_origination_fee=0,
            max_origination_fee=0,
            late_fee=0.05,
            cashback_initial=0,
            cashback_payment=0,
            debt_income_ratio=0.3,
            origination_fee_increment=0,
            is_active=True,
            is_initial=False,
            is_product_exclusive=False,
        )

    if efishery_jawara_product_line:
        efishery_jawara_product_line.update_safely(
            product_line_type=MerchantFinancingCSVUploadPartner.EFISHERY_JAWARA,
            min_amount=200000000,
            max_amount=1000000000,
            min_duration=30,
            max_duration=180,
            min_interest_rate=0.011,
            max_interest_rate=0.011,
            payment_frequency=PaymentConst.PAYMENT_FREQUENCY,
            product_profile=efishery_jawara_product_profile
        )
    else:
        efishery_jawara_product_line, _ = ProductLine.objects.get_or_create(
            product_line_code=ProductLineCodes.EFISHERY_JAWARA,
            product_line_type=MerchantFinancingCSVUploadPartner.EFISHERY_JAWARA,
            min_amount=200000000,
            max_amount=1000000000,
            min_duration=30,
            max_duration=180,
            min_interest_rate=0.011,
            max_interest_rate=0.011,
            payment_frequency=PaymentConst.PAYMENT_FREQUENCY,
            product_profile=efishery_jawara_product_profile
        )

    product_lookup = ProductLookup.objects.filter(
        product_line=efishery_jawara_product_line,
        product_profile=efishery_jawara_product_profile
    ).last()

    if product_lookup:
        product_lookup.update_safely(
            product_name="I.0025-O.0000-L.050-C1.000-C2.000-M",
            interest_rate=0.132,
            origination_fee_pct=0.015,
            late_fee_pct=0.05,
            cashback_initial_pct=0,
            cashback_payment_pct=0
        )
    else:
        ProductLookup.objects.get_or_create(
            product_line=efishery_jawara_product_line,
            product_profile=efishery_jawara_product_profile,
            product_name="I.0025-O.0000-L.050-C1.000-C2.000-M",
            interest_rate=0.132,
            origination_fee_pct=0.015,
            late_fee_pct=0.05,
            cashback_initial_pct=0,
            cashback_payment_pct=0
        )

    efishery_jawara_product_line_loan_purpose = ProductLineLoanPurpose.objects.filter(
        product_line=efishery_jawara_product_line
    ).last()
    if efishery_jawara_product_line_loan_purpose:
        efishery_jawara_product_line_loan_purpose.loan_purpose_id = 1
        efishery_jawara_product_line_loan_purpose.save()
    else:
        ProductLineLoanPurpose.objects.get_or_create(
            product_line=efishery_jawara_product_line,
            loan_purpose_id=1
        )


def create_partner_efishery_jawara(apps, schema_editor):
    group = Group.objects.get(name="julo_partners")

    user, created = User.objects.get_or_create(
        username=MerchantFinancingCSVUploadPartner.EFISHERY_JAWARA,
        defaults={
            'email': 'fikri.haekal1@fishlog.co.id',
        }
    )
    user.groups.add(group)

    if settings.ENVIRONMENT == 'prod':
        app_190_email_recipients = 'kabayan@efishery.com'
        disburse_email_recipients = "egi.septiar@efishery.com,james.salim@julofinance.com,ridwan.hilmy@efishery.com,emilia.mariss@efishery.com,galih.aulia@efishery.com"
    else:
        app_190_email_recipients = 'fujiatma.napitupulu@julofinance.com,jonathan.wirianto@julofinance.com'
        disburse_email_recipients = 'fujiatma.napitupulu@julofinance.com,jonathan.wirianto@julofinance.com'

    efishery_jawara_product_line = ProductLine.objects.filter(
        product_line_code=ProductLineCodes.EFISHERY_JAWARA
    ).last()

    partner, created = Partner.objects.get_or_create(
        user=user,
        defaults={
            'poc_email': 'lutfie.rismawan@efishery.com',
            'poc_phone': '',
            'poc_name': MerchantFinancingCSVUploadPartner.EFISHERY_JAWARA,
            'name': MerchantFinancingCSVUploadPartner.EFISHERY_JAWARA,
            'email': 'lutfie.rismawan@efishery.com',
            'company_name': MerchantFinancingCSVUploadPartner.EFISHERY_JAWARA,
            'is_active': True,
            'is_csv_upload_applicable': True,
            'partner_bank_account_number': '2818811999',
            'partner_bank_account_name': 'TEKNOLOGI UNTUK PEMBUDID',
            'partner_bank_name': 'BCA',
            'is_disbursement_to_partner_bank_account': True,
            'recipients_email_address_for_190_application': app_190_email_recipients,
            'recipients_email_address_for_bulk_disbursement': disburse_email_recipients,
            'sender_email_address_for_190_application': 'ops.efishery@julo.co.id',
            'sender_email_address_for_bulk_disbursement': 'ops.efishery@julo.co.id',
            'due_date_type': MerchantFinancingCSVUploadPartnerDueDateType.END_OF_TENOR,
            'product_line': efishery_jawara_product_line,
        }
    )

    if not created:
        partner.poc_email = 'lutfie.rismawan@efishery.com',
        partner.poc_phone = '',
        partner.poc_name = MerchantFinancingCSVUploadPartner.EFISHERY_JAWARA,
        partner.name = MerchantFinancingCSVUploadPartner.EFISHERY_JAWARA,
        partner.email = 'lutfie.rismawan@efishery.com',
        partner.company_name = MerchantFinancingCSVUploadPartner.EFISHERY_JAWARA,
        partner.is_active = True,
        partner.is_csv_upload_applicable = True,
        partner.partner_bank_account_number = '2021313108',
        partner.partner_bank_account_name = 'MULTIDAYA TEKNOLOGI NUSANTAR',
        partner.partner_bank_name = 'BNI',
        partner.is_disbursement_to_partner_bank_account = True,
        partner.recipients_email_address_for_190_application = app_190_email_recipients,
        partner.recipients_email_address_for_bulk_disbursement = disburse_email_recipients,
        partner.sender_email_address_for_190_application = 'ops.efishery@julo.co.id',
        partner.sender_email_address_for_bulk_disbursement = 'ops.efishery@julo.co.id',
        partner.due_date_type = MerchantFinancingCSVUploadPartnerDueDateType.END_OF_TENOR,
        partner.save()

    Customer.objects.create(user=user, email='lutfie.rismawan.efishery.jawara@efishery.com', phone=partner.phone)

    efishery_jawara_product_line = ProductLine.objects.filter(product_line_code=ProductLineCodes.EFISHERY_JAWARA).last()


class Migration(migrations.Migration):

    operations = [
        migrations.RunPython(add_product_line_efishery_jawara, migrations.RunPython.noop),
        migrations.RunPython(create_partner_efishery_jawara, migrations.RunPython.noop),
    ]
