# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-08-28 09:29
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst


def add_blacklisted_asn_feature_setting(apps, schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.BLACKLISTED_ASN,
        is_active=False,
        category='application_flow',
        parameters={}
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_blacklisted_asn_feature_setting, migrations.RunPython.noop)
    ]
