# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-09-13 10:43
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def add_fraud_blacklisted_company(*args):
    FeatureSetting.objects.get_or_create(
        feature_name=FeatureNameConst.FRAUD_BLACKLISTED_COMPANY,
        defaults={
            'category': 'fraud',
            'is_active': False,
            'description': 'Fraud Blacklisted Company feature for fraud binary check at x105',
        }
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_fraud_blacklisted_company, migrations.RunPython.noop),
    ]
