# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-09-21 17:21

from __future__ import unicode_literals

from django.db import migrations

from juloserver.streamlined_communication.models import NeoBannerCard


def retroload_neobanner_j1(_apps, _schema_editor):
    neo_banner = NeoBannerCard.objects.get(statuses='[121]')
    neo_banner.statuses = '[121, 115]'
    neo_banner.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(retroload_neobanner_j1, migrations.RunPython.noop)
    ]
