# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-09-25 09:00
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst


def add_dana_fdc_feature_setting(apps, schema_editor):

    feature_setting = FeatureSetting.objects.filter(
        feature_name=FeatureNameConst.DANA_FDC_RESULT_RETRY_CONFIGURATION,
    ).last()

    if not feature_setting:
        FeatureSetting.objects.create(
            feature_name=FeatureNameConst.DANA_FDC_RESULT_RETRY_CONFIGURATION,
            is_active=False,
            parameters={
                'retry_policy': {
                    'interval_retry_times': 1, # Hours
                    'timeout': 3, # Second
                    'max_retry': 3,
                }
            },
            category='partner',
            description='Enable or disable sent to Dana fdc result',
        )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_dana_fdc_feature_setting, migrations.RunPython.noop)
    ]
