# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-09-28 03:17
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import Workflow, WorkflowStatusPath


def add_workflow_path_x109_to_x133_julo_starter(apps, _schema_editor):

    workflow = Workflow.objects.get(
        name="JuloStarterWorkflow"
    )

    WorkflowStatusPath.objects.get_or_create(
        status_previous=109,
        status_next=133,
        workflow=workflow,
        type='unhappy')


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_workflow_path_x109_to_x133_julo_starter, migrations.RunPython.noop),
    ]
