# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-09-22 08:42
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting
from juloserver.minisquad.constants import FeatureNameConst

def add_dialing_order(apps, schema_editor):
    feature_group_mapping_config = FeatureSetting.objects.filter(
        feature_name=FeatureNameConst.AI_RUDDER_TASKS_STRATEGY_CONFIG).last()
    if not feature_group_mapping_config:
        return
    params = feature_group_mapping_config.parameters
    new_params = {}
    for key, bucket_config in params.items():
        bucket_config['dialingOrder'] = [
            "mobile_phone_2", "telp_perusahaan", "mobile_phone_1_2",
            "mobile_phone_2_2", "no_telp_pasangan", "mobile_phone_1_3",
            "mobile_phone_2_3", "no_telp_kerabat", "mobile_phone_1_4", "mobile_phone_2_4"
        ]
        new_params[key] = bucket_config
    feature_group_mapping_config.parameters = new_params
    feature_group_mapping_config.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_dialing_order, migrations.RunPython.noop)
    ]
