# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-10-05 10:12
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting
from juloserver.loan.constants import DEFAULT_LIST_SAVING_INFORMATION_DURATION


def rename_fs_config_other_platform_interest_and_add_duration_config(_apps, _schema_editor):
    old_feature_setting_name = 'other_platform_monthly_interest_rate'
    feature_setting = FeatureSetting.objects.get_or_none(feature_name=old_feature_setting_name)
    if feature_setting:
        # update new feature setting name
        feature_setting.feature_name = FeatureNameConst.SAVING_INFORMATION_CONFIGURATION

        # add config for list duration
        feature_setting.parameters['list_saving_information_duration'] = (
            DEFAULT_LIST_SAVING_INFORMATION_DURATION
        )

        feature_setting.description = 'Config other platform monthly interest rate & list duration'
        feature_setting.save()


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunPython(rename_fs_config_other_platform_interest_and_add_duration_config,
                             migrations.RunPython.noop),
    ]
