# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-10-09 06:48
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def create_time_limit_feature_setting_for_similar_and_fraud_face(apps, schema_editor):

    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.SIMILAR_AND_FRAUD_FACE_TIME_LIMIT,
        parameters={'pending_status_wait_time_limit_in_minutes': 30},
        is_active=False,
        description="Set time limit for similar and fraud face",
        category='similar and fraud face time limit config'
    )


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_time_limit_feature_setting_for_similar_and_fraud_face, migrations.RunPython.noop),
    ]
