# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-10-06 06:47
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def add_zero_interest_higher_provision_feature_setting(apps, _schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.ZERO_INTEREST_HIGHER_PROVISION,
        parameters={
            "condition": {
                "min_loan_amount": 30_000,
                "max_loan_amount": 1_000_000,
                "min_duration": 1,
                "max_duration": 3,
                "list_transaction_method_code": ["1"],
            },
            "whitelist": {
                "is_active": False,
                "list_customer_id": [],
            },
            "is_experiment_for_last_digit_customer_id_is_even": False
        },
        is_active=False,
        category="Loan",
        description="All configurations for zero interest higher provision",
    )


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            add_zero_interest_higher_provision_feature_setting,
            migrations.RunPython.noop
        ),
    ]
