# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-10-02 05:39
from __future__ import unicode_literals

from django.db import migrations

from juloserver.autodebet.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def add_slack_alert_feature_setting(apps, schema_editor):
    FeatureSetting.objects.get_or_create(
        is_active=True,
        feature_name=FeatureNameConst.MANDIRI_SLACK_ALERT_PAYMENT_NOTIFICATION,
        category="autodebet",
        parameters={},
        description="for turn on/off slack alert autodebet mandiri payment notification")


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_slack_alert_feature_setting,
                             migrations.RunPython.noop)
    ]
