# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-01-31 08:09
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import Group, User

from juloserver.application_flow.constants import PartnerNameConstant
from juloserver.julo.models import Partner
from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst


def create_smartfren_partner(apps, schema_editor):
    group = Group.objects.get(name="julo_partners")

    user = User.objects.create(
        username=PartnerNameConstant.SMARTFREN, email='smartfren@smartfren.com'
    )
    user.groups.add(group)

    Partner.objects.create(user=user,
                           poc_email='smartfren@smartfren.com',
                           poc_phone='+628111111111',
                           poc_name='Smartfren',
                           name=PartnerNameConstant.SMARTFREN,
                           email='cs@smartfren.com',
                           phone='628111111111',
                           type='referrer',
                           company_name='smartfren',
                           company_address='111 North Bridge Road #08-10 Peninsula Plaza',
                           business_type='Fintech Aggregator',
                           is_active=True
                           )

    feature_settings = FeatureSetting.objects.filter(
        feature_name=FeatureNameConst.LEAD_GEN_PARTNER_CREDIT_SCORE_GENERATION).first()

    partners = feature_settings.parameters['partners']
    if not PartnerNameConstant.SMARTFREN in partners:
        partners.append(PartnerNameConstant.SMARTFREN)
        feature_settings.parameters['partners'] = partners
        feature_settings.save()


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_smartfren_partner, migrations.RunPython.noop)
    ]
