# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-10-06 05:12
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import ProductLine, ProductLookup
from juloserver.julo.product_lines import ProductLineCodes

def add_new_product_lookup_for_agrari(apps, schema_editor):
    agrari_product_line = ProductLine.objects.filter(  # noqa: F821
        product_line_code=ProductLineCodes.AGRARI
    ).first()

    if agrari_product_line:
        ProductLookup.objects.get_or_create(
            product_line=agrari_product_line,
            product_profile=agrari_product_line.product_profile,
            product_name="I.00125-O.0000-L.050-C1.000-C2.000-M",
            interest_rate=0.1404,
            origination_fee_pct=0,
            late_fee_pct=0.05,
            cashback_initial_pct=0,
            cashback_payment_pct=0
        )


class Migration(migrations.Migration):

    operations = [
        migrations.RunPython(add_new_product_lookup_for_agrari, migrations.RunPython.noop),
    ]
