# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-10-04 08:46
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst


def create_fs_shopee_whitelist_scoring(app, _schema_editor):    

    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.SHOPEE_WHITELIST_SCORING,
        is_active=False,
        parameters={},
        category='account',
        description='Config disable Shopee whitelist scoring'
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_fs_shopee_whitelist_scoring, migrations.RunPython.noop),
    ]
