# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-10-05 14:08
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def create_feature_setting_dana_linking(apps, schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.DANA_LINKING,
        parameters={},
        is_active=False,
        category="repayment",
        description="DANA activation linking"
    )

    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.DANA_LINKING_WHITELIST,
        parameters={"application_id": []},
        is_active=False,
        category="repayment",
        description="Whitelist application who can use DANA"
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_feature_setting_dana_linking, migrations.RunPython.noop),
    ]
