# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2023-10-05 07:49
from __future__ import unicode_literals

from django.db import migrations
from juloserver.application_flow.models import ApplicationTag, ApplicationPathTagStatus
from juloserver.application_flow.services2 import AutoDebit


def add_application_tag_for_autodebet(apps, schema_editor):
    tag = AutoDebit.APPLICATION_TAG

    if ApplicationTag.objects.filter(application_tag=tag).exists():
        return

    ApplicationTag.objects.create(application_tag=tag, is_active=True)
    ApplicationPathTagStatus.objects.create(application_tag=tag, status=1, definition="success")
    ApplicationPathTagStatus.objects.create(application_tag=tag, status=-1, definition="pending")


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            add_application_tag_for_autodebet, migrations.RunPython.noop
        )
    ]
