# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-09-27 06:41
from __future__ import unicode_literals
import re
from django.db import migrations

from juloserver.julo.models import FeatureSetting
from juloserver.minisquad.constants import (
    FeatureNameConst,
    DialerSystemConst,
)
from juloserver.minisquad.services2.dialer_related import get_specific_bucket_list_for_constructing


def add_bucket_current_to_ai_rudder_feature_setting(apps, schema_editor):
    dpd_list = [-1, -3, -5]
    bulk_call_interval_config = {
        -1: 600,
        -3: 900,
        -5: 900,
    }
    feature_batching_threshold_group_config = FeatureSetting.objects.filter(
        feature_name=FeatureNameConst.AI_RUDDER_SEND_BATCHING_THRESHOLD).last()
    feature_slack_alert = FeatureSetting.objects.filter(
        feature_name=FeatureNameConst.AI_RUDDER_SEND_SLACK_ALERT).last()
    feature_group_config = FeatureSetting.objects.filter(
        feature_name=FeatureNameConst.AI_RUDDER_GROUP_NAME_CONFIG).last()
    feature_ai_rudder_tasks_config = FeatureSetting.objects.filter(
        feature_name=FeatureNameConst.AI_RUDDER_TASKS_STRATEGY_CONFIG).last()

    params_feature_group_config = feature_group_config.parameters
    params_threshold = feature_batching_threshold_group_config.parameters
    params_slack_alert = feature_slack_alert.parameters
    bucket_list = params_slack_alert['bucket_list']
    feature_ai_rudder_tasks_config_params = feature_ai_rudder_tasks_config.parameters
    b3_config = feature_ai_rudder_tasks_config_params[DialerSystemConst.DIALER_BUCKET_3]

    for dpd in dpd_list:
        params_threshold[DialerSystemConst.DIALER_T_MINUS.format(dpd)] = 5000
        params_threshold[DialerSystemConst.DIALER_JTURBO_T_MINUS.format(dpd)] = 5000
        bucket_list.append(DialerSystemConst.DIALER_T_MINUS.format(dpd))
        bucket_list.append(DialerSystemConst.DIALER_JTURBO_T_MINUS.format(dpd))
        params_feature_group_config[DialerSystemConst.DIALER_T_MINUS.format(dpd)] = "Group_Bucket Reminder"
        params_feature_group_config[DialerSystemConst.DIALER_JTURBO_T_MINUS.format(dpd)] = "Group_Bucket JTturbo"
        current_config = b3_config
        current_config['bulkCallInterval'] = bulk_call_interval_config[dpd]
        current_config['dialingOrder'] = ['mobile_phone_1_2']
        feature_ai_rudder_tasks_config_params[
            DialerSystemConst.DIALER_T_MINUS.format(dpd)] = current_config
        jturbo_config = b3_config
        jturbo_config['bulkCallInterval'] = 300
        feature_ai_rudder_tasks_config_params[DialerSystemConst.DIALER_JTURBO_T_MINUS.format(dpd)] = b3_config

    b2_list = get_specific_bucket_list_for_constructing(bucket_number=2)
    b2_list.remove(DialerSystemConst.DIALER_BUCKET_2)
    b2_list.remove(DialerSystemConst.DIALER_BUCKET_2_NC)
    b1_list = get_specific_bucket_list_for_constructing(bucket_number=1)
    b4_list, b4_special_bucket = get_specific_bucket_list_for_constructing(
        bucket_number=4, is_split_regular=True)
    bucket_for_config = b2_list + b1_list + b4_special_bucket
    pattern = r'_B(\d+)'
    jturbo_pattern = re.compile(r'JTURBO', re.IGNORECASE)
    for bucket_name in bucket_for_config:
        is_jturbo = bool(jturbo_pattern.search(bucket_name))
        match = re.search(pattern, bucket_name)
        number = match.group(1)
        group_name = "Group_Bucket{}".format(number)
        if is_jturbo:
            group_name = "Group_Bucket JTturbo"

        params_feature_group_config[bucket_name] = group_name
        feature_ai_rudder_tasks_config_params[bucket_name] = b3_config

    feature_batching_threshold_group_config.parameters = params_threshold
    feature_batching_threshold_group_config.save()
    params_slack_alert['bucket_list'] = bucket_list
    feature_slack_alert.parameters = params_slack_alert
    feature_slack_alert.save()
    feature_group_config.parameters = params_feature_group_config
    feature_group_config.save()

    feature_ai_rudder_tasks_config.parameters = feature_ai_rudder_tasks_config_params
    feature_ai_rudder_tasks_config.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_bucket_current_to_ai_rudder_feature_setting, migrations.RunPython.noop)
    ]
