# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-10-17 08:37
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import StatusLookup
from juloserver.julo.statuses import JuloOneCodes


def insert_account_deletion_status_lookup(apps, schema_editor):
    StatusLookup.objects.create(
        status_code=JuloOneCodes.ACCOUNT_DELETION_ON_REVIEW,
        status="Account Deletion on Review",
    )

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            insert_account_deletion_status_lookup, migrations.RunPython.noop),
    ]
