# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-10-20 07:45
from __future__ import unicode_literals

from django.db import migrations

from juloserver.dana.loan.crm.job_dana import DANA_JOB
from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def partnership_dana_job(apps, schema_editor):
    FeatureSetting.objects.get_or_create(
        is_active=True,
        feature_name=FeatureNameConst.DANA_JOB,
        category="partner",
        parameters={
            "job": DANA_JOB
        },
        description="Mapping Dana job data format to JULO’s format"
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(partnership_dana_job, migrations.RunPython.noop)
    ]
