# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-10-17 02:46
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting
from juloserver.otp.constants import SessionTokenAction, SessionTokenType


def update_feature_setting_for_otp_action_type(apps, schema_editor):
    feature_setting, created = FeatureSetting.objects.get_or_create(feature_name='otp_action_type')
    parameters = feature_setting.parameters or {}
    parameters.update({
        SessionTokenAction.ACCOUNT_DELETION_REQUEST: SessionTokenType.SHORT_LIVED
    })
    feature_setting.save()

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            update_feature_setting_for_otp_action_type, migrations.RunPython.noop),
    ]
