# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-10-16 11:23
from __future__ import unicode_literals

from django.db import migrations

from juloserver.dana.loan.crm.province_city_dana import DANA_PROVINCE, DANA_CITY
from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def partnership_dana_province_and_city(apps, schema_editor):
    FeatureSetting.objects.get_or_create(
        is_active=True,
        feature_name=FeatureNameConst.DANA_PROVINCE_AND_CITY,
        category="partner",
        parameters={
            "province": DANA_PROVINCE,
            "city": DANA_CITY
        },
        description="Mapping dana province and city"
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(partnership_dana_province_and_city, migrations.RunPython.noop)
    ]
