# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-10-26 05:20
from __future__ import unicode_literals

from django.db import migrations
from juloserver.minisquad.constants import DialerSystemConst, FeatureNameConst
from juloserver.julo.models import FeatureSetting


def update_feature_settings_grab_ai_rudder(apps, _schema_editor):
    grab = DialerSystemConst.GRAB
    feature_setting = FeatureSetting.objects.filter(feature_name=FeatureNameConst.AI_RUDDER_GROUP_NAME_CONFIG).last()
    if feature_setting:
        parameters = feature_setting.parameters
        parameters[grab] = 'Group_Grab_Bucket_2_90'

        feature_setting.update_safely(
            parameters=parameters
        )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(update_feature_settings_grab_ai_rudder, migrations.RunPython.noop),
    ]
