# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-10-24 08:59
from __future__ import unicode_literals

from django.db import migrations
from juloserver.application_flow.models import ApplicationPathTagStatus


def create_data(app, _schema_editor):
    job_orders = (
        "1_job_selected",
        "2_job_selected",
        "3_job_selected",
        "4_job_selected",
        "5_job_selected",
        "6_job_selected",
        "7_job_selected",
        "8_job_selected",
    )

    for job_order in job_orders:
        ApplicationPathTagStatus.objects.get_or_create(
            application_tag=job_order,
            status=0,
            definition=job_order,
        )

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_data, migrations.RunPython.noop),
    ]
