# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-10-23 04:19
from __future__ import unicode_literals

from django.db import migrations
from juloserver.minisquad.constants import FeatureNameConst
from juloserver.minisquad.constants import DialerSystemConst
from juloserver.julo.models import FeatureSetting


def add_slack_alert_feature_settings_dana_ai_rudder(apps, _schema_editor):
    dana_b_all = DialerSystemConst.DANA_B_ALL
    feature_setting = FeatureSetting.objects.filter(feature_name=FeatureNameConst.AI_RUDDER_SEND_SLACK_ALERT).last()
    if feature_setting:
        parameters = feature_setting.parameters
        bucket_list = parameters.get('bucket_list', [])

        bucket_list.append(dana_b_all)

        parameters['bucket_list'] = bucket_list

        feature_setting.update_safely(
            parameters=parameters
        )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_slack_alert_feature_settings_dana_ai_rudder, migrations.RunPython.noop),
    ]
