# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-09-12 09:35
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst

def create_dana_other_page_details_settings(apps, schema_editor):
    FeatureSetting.objects.create(
        is_active=True,
        feature_name=FeatureNameConst.DANA_OTHER_PAGE_URL,
        parameters={
            "dana_mini": "https://m.sandbox.dana.id/m/ipg?sourcePlatform=IPG&ott=",
            "dana_how_to_topup": "https://m.sandbox.dana.id/m/portal/topup?ott=",
            "dana_cs_centre": "https://m.sandbox.dana.id/m/ipg?sourcePlatform=IPG&ott=" 
        },
        category='repayment',
        description='Dana Other Page Urls'
    )

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_dana_other_page_details_settings, migrations.RunPython.noop)
    ]
