# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-10-29 18:01
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import WorkflowConst, ApplicationStatusCodes
from juloserver.julo.models import Workflow, WorkflowStatusNode, WorkflowStatusPath


def run(apps, _schema_editor):
    workflow = Workflow.objects.filter(name=WorkflowConst.JULO_ONE).last()

    WorkflowStatusPath.objects.get_or_create(
        status_previous=ApplicationStatusCodes.APPLICATION_DENIED,
        status_next=ApplicationStatusCodes.CUSTOMER_IGNORES_CALLS,
        type='detour',
        workflow=workflow
    )

    WorkflowStatusPath.objects.get_or_create(
        status_previous=ApplicationStatusCodes.CUSTOMER_IGNORES_CALLS,
        status_next=ApplicationStatusCodes.APPLICATION_DENIED,
        type='graveyard',
        workflow=workflow
    )

    WorkflowStatusNode.objects.get_or_create(
        status_node=ApplicationStatusCodes.APPLICATION_DENIED,
        handler='JuloOne135Handler',
        workflow=workflow
    )


class Migration(migrations.Migration):

    dependencies = [

    ]

    operations = [
        migrations.RunPython(run, migrations.RunPython.noop),
    ]
