# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-02-09 02:45
from __future__ import unicode_literals
from unicodedata import category

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst


def add_new_feature_autodebet_activation_pn_config(apps, _schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.AUTODEBET_ACTIVATION_PN_CONFIG,
        is_active=False,
        parameters={
            "title": "Autodebet Kamu Sudah Aktif!{}",
            "pn_body": "Dapatkan cashback jika autodebet-mu tanggal {} sebesar {} berhasil!",
            "pn_late_account_payment_body": "Karena autodebet kamu aktif setelah tagihan lewat dari jatuh tempo," \
                " tagihan tersebut bisa kamu bayarkan pakai metode pembayaran lain dulu, ya!",
        },
        category='repayment',
        description="Autodebet Activation PN Config"
    )


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_new_feature_autodebet_activation_pn_config,
                             migrations.RunPython.noop)
    ]
