# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-11-10 17:06
from __future__ import unicode_literals

from django.db import migrations

from juloserver.streamlined_communication.constant import CommunicationPlatform, CardProperty
from juloserver.streamlined_communication.models import StreamlinedMessage, StreamlinedCommunication


def populate_sms(apps, schema_editor):
    sms_list = [
        {
            'dpd': -7,
            'template_code': '{}_sms_cashbacknew_dpd_-7',
            'type': 'Payment Reminder',
            'time_sent': '14:0',
            'partner_selection_action': 'exclude',
            'partner_selection_list':'{4,19,20,24,10,9,21,12,17,22,23,27,45,28,25,11,26,41,42,29,30,31,32,33,34,35,36,37,38,39,40,43,44,1,53,56,61,63,46}',
            'message': 'Halo, byr tagihanmu {{sms_due_amount}} hari ini, dptkan cashback hingga 5%. Klik link di bwh utk bayar:{{sms_payment_details_url}}',
            'description': 'payment reminder for dpd -7 J1 customer',
            'parameter': '{sms_due_amount,sms_payment_details_url}'
        },
        {
            'dpd': -5,
            'template_code': '{}_sms_cashbacknew_dpd_-5',
            'type': 'Payment Reminder',
            'time_sent': '14:0',
            'partner_selection_action': 'exclude',
            'partner_selection_list': '{4,19,20,24,10,9,21,12,17,22,23,27,45,28,25,11,26,41,42,29,30,31,32,33,34,35,36,37,38,39,40,43,44,1,53,56,61,63,46}',
            'message': """Ayo, sgra byr tagihanmu {{sms_due_amount}} bln {{month}} lwt VA {{sms_primary_va_name}}, dptkan cashback hingga 5%

{{sms_payment_details_url}}.""",
            'description': 'payment reminder for dpd -5 J1 customer',
            'parameter': '{sms_due_amount,month,sms_primary_va_name,sms_payment_details_url}'
        },
        {
            'dpd': -3,
            'template_code': '{}_sms_cashbacknew_dpd_-3',
            'type': 'Payment Reminder',
            'time_sent': '14:0',
            'partner_selection_action': 'exclude',
            'partner_selection_list': '{4,19,20,24,10,9,21,12,17,22,23,27,45,28,25,11,26,41,42,29,30,31,32,33,34,35,36,37,38,39,40,43,44,1,53,56,58,60,61,62,63,55,46}',
            'message': """Msh ada ksmptn dpt cashback hingga 5%, byr tagihanmu {{sms_due_amount}} lwt VA {{sms_primary_va_name}} skrg.

{{sms_payment_details_url}}.""",
            'description': 'payment reminder for dpd -3 J1 customer',
            'parameter': '{sms_due_amount,sms_primary_va_name,sms_payment_details_url}'
        },
        {
            'dpd': -2,
            'template_code': '{}_sms_cashbacknew_dpd_-2',
            'type': 'Payment Reminder',
            'time_sent': '14:0',
            'partner_selection_action': 'exclude',
            'partner_selection_list': '{4,19,20,24,10,9,21,12,17,22,23,27,45,28,25,11,26,41,42,29,30,31,32,33,34,35,36,37,38,39,40,43,44,46,1,53,56,55,58,60,61,62,63}',
            'message': """Hari terakhir utk dpt cashback hingga 5%. Byr tagihanmu {{sms_due_amount}} lwt VA {{sms_primary_va_name}} skrg jg. 

{{sms_payment_details_url}}""",
            'description': 'payment reminder for dpd -2 J1 customer',
            'parameter': '{sms_due_amount,sms_primary_va_name,sms_payment_details_url}'
        },
        {
            'dpd': -1,
            'template_code': '{}_sms_cashbacknew_dpd_-1',
            'type': 'Payment Reminder',
            'time_sent': '14:0',
            'partner_selection_action': 'exclude',
            'partner_selection_list': '{4,19,20,24,10,9,21,12,17,22,23,27,45,28,25,11,26,41,42,29,30,31,32,33,34,35,36,37,38,39,40,43,44,1,53,56,58,60,61,62,63,55,46}',
            'message': """Halo, sgra byr tagihanmu {{sms_due_amount}} lwt VA {{sms_primary_va_name}}. Jgn sampai terkena denda.

{{sms_payment_details_url}}""",
            'description': 'payment reminder for dpd -1 J1 customer',
            'parameter': '{sms_due_amount,sms_primary_va_name,sms_payment_details_url}'
        },
        {
            'dpd': 0,
            'template_code': '{}_sms_cashbacknew_dpd_0',
            'type': 'Payment Reminder',
            'time_sent': '14:0',
            'partner_selection_action': 'exclude',
            'partner_selection_list': '{4,19,20,24,10,9,21,12,17,22,23,27,45,28,25,11,26,41,42,29,30,31,32,33,34,35,36,37,38,39,40,43,44,46,1,53,56,55,58,60,61,62,63}',
            'message': """Pinjaman Kamu jth tempo hr ini. Bayar cicilan Kamu skrg dan hindari biaya keterlambatan. Bayar: {{sms_payment_details_url}}""",
            'description': 'payment reminder for dpd 0 J1 customer',
            'parameter': '{sms_payment_details_url}'
        },
    ]
    products = ['j1']
    for template in sms_list:
        dpd = template['dpd']
        content = template['message']
        template_code = template['template_code']
        time_sent = template['time_sent']
        parameter = template['parameter']

        for product in products:
            message = StreamlinedMessage.objects.create(
                message_content=content,
                parameter=parameter
            )
            StreamlinedCommunication.objects.create(
                dpd=dpd,
                communication_platform=CommunicationPlatform.SMS,
                template_code=template_code.format(product),
                is_active=True,
                type=template['type'],
                time_sent=time_sent,
                message=message,
                is_automated=True,
                time_out_duration=3,
                product=product,
                partner_selection_action=template['partner_selection_action'],
                partner_selection_list=template['partner_selection_list'],
                description=template['description'],
                extra_conditions=CardProperty.CASHBACK_NEW_SCHEME_EXPERIMENT
            )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(populate_sms, migrations.RunPython.noop),
    ]
