# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-11-10 02:22
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def create_trust_guard_scoring_feature_setting(*args):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.TRUST_GUARD_SCORING,
        is_active=False,
        description='For turning on/off trust guard decision scoring',
        category='fraud',
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_trust_guard_scoring_feature_setting, migrations.RunPython.noop),
    ]
