# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-11-07 04:48
from __future__ import unicode_literals

from django.db import migrations

from juloserver.streamlined_communication.models import NeoInfoCard
from juloserver.julo.models import Image


def create_image(image_source_id, image_type, image_url):
    image = Image()
    image.image_source = image_source_id
    image.image_type = image_type
    image.url = image_url
    image.save()


def retroload_neo_info_card_j1(_apps, _schema_editor):
    data_to_be_loaded = [
        {
            'statuses': '[105_NO_SCORE,105_NOT_C_SCORE]',
            'product': 'J1',
            'image_url': 'neo-info-card/form-partial-infocard.jpg',
            'action_type': 'webpage',
            'action_destination': 'https://www.julo.co.id/blog/data-kamu-aman-dengan-JULO?in_app=true',
            'priority': 1,
            'is_active': True,
        },
        {
            'statuses': '[105_C_SCORE,133,135_REAPPLY,135_CANNOT_REAPPLY]',
            'product': 'J1',
            'image_url': 'neo-info-card/rejected-infocard.jpg',
            'action_type': 'webpage',
            'action_destination': 'https://www.julo.co.id/blog/data-kamu-aman-dengan-JULO?in_app=true',
            'priority': 1,
            'is_active': True,
        }
    ]

    for data in data_to_be_loaded:
        neo_banner_card = NeoInfoCard.objects.create(**data)

        if data['image_url']:
            create_image(neo_banner_card.id, 'NEO_INFO_CARD_IMAGE', data['image_url'])


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(retroload_neo_info_card_j1, migrations.RunPython.noop),
    ]
