# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-11-08 04:50
from __future__ import unicode_literals

from django.db import migrations
from django.utils import timezone
from bulk_update.helper import bulk_update

from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst
from juloserver.sales_ops.models import SalesOpsBucket
from juloserver.sales_ops.constants import BucketCode


def create_and_update_new_bucket_code(apps, _schema_editor):
    sales_ops_buckets = SalesOpsBucket.objects.all()
    bucket_name_list = []
    for bucket in sales_ops_buckets:
        bucket.name = ' '.join(bucket.code.split('_'))
        bucket.udate = timezone.localtime(timezone.now())
        bucket_name_list.append(bucket)
    bulk_update(bucket_name_list, update_fields=['description', 'udate'])

    SalesOpsBucket.objects.get_or_create(
        is_active=True,
        code=BucketCode.GRADUATION,
        description='Graduation bucket',
        name=BucketCode.GRADUATION,
        scores={'m_scores': [], 'r_scores': []}
    )


def add_graduation_bucket_fs(apps, _schema_editor):
    sales_ops_feature = FeatureSetting.objects.get_or_none(
        feature_name=FeatureNameConst.SALES_OPS
    )
    if sales_ops_feature:
        parameters = sales_ops_feature.parameters
        parameters['buckets'].append(
            {
                "code": BucketCode.GRADUATION,
                "description": "Graduation bucket",
                "is_active": True,
                "name": BucketCode.GRADUATION,
            }
        )
        sales_ops_feature.update_safely(parameters=parameters)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_and_update_new_bucket_code, migrations.RunPython.noop),
        migrations.RunPython(add_graduation_bucket_fs, migrations.RunPython.noop),
    ]
