# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-11-22 07:46
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def add_fraud_blacklisted_geohash5_feature(*args):
    FeatureSetting.objects.get_or_create(
        feature_name=FeatureNameConst.FRAUD_BLACKLISTED_GEOHASH5,
        defaults={
            'category': 'fraud',
            'is_active': False,
            'description': 'Fraud Block Geohash 5 feature for blocking application geohash 5',
        }
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_fraud_blacklisted_geohash5_feature, migrations.RunPython.noop),
    ]
