# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-11-16 04:43
from __future__ import unicode_literals

from django.db import migrations

from juloserver.graduation.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def add_new_fs_for_customer_suspend(apps, schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.CUSTOMER_SUSPEND,
        is_active=True,
        category='graduation',
        description='customer suspend',
        parameters={
            'redis_cache_ttl_hour': 3
        }
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_new_fs_for_customer_suspend, migrations.RunPython.noop)
    ]
