# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-11-21 06:29
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst


def update_shopee_whitelist_fs_with_good_fdc_bypass(app, _schema_editor):
    fs = FeatureSetting.objects.get_or_none(
        feature_name=FeatureNameConst.SHOPEE_WHITELIST_SCORING,
    )
    if fs:
        good_fdc_bypass = dict(
            is_active=True
        )
        fs.parameters.update(good_fdc_bypass=good_fdc_bypass)
        fs.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            update_shopee_whitelist_fs_with_good_fdc_bypass, migrations.RunPython.noop),
    ]
