# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-11-21 05:07
from __future__ import unicode_literals

from django.db import migrations

from juloserver.balance_consolidation.constants import BalanceConsolidationFeatureName, \
    BalanceConsolidationStatus
from juloserver.julo.models import FeatureSetting


def update_fs_for_balance_cons_crm_config(app, schema_editor):
    fs = FeatureSetting.objects.filter(
        feature_name=BalanceConsolidationFeatureName.BALANCE_CONS_CRM_CONFIG,
        category='balance_consolidation'
    ).last()
    if fs:
        fs.parameters['status_map_change_reason'][BalanceConsolidationStatus.CANCELLED] = [
            'App request to cancel',
            'Loan already paid off',
            'Other',
        ]
        fs.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(update_fs_for_balance_cons_crm_config, migrations.RunPython.noop)
    ]
