# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-11-17 09:51
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def insert_new_feature_setting_dana_block_loan_stuck_211_payment_consult(apps, schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.DANA_BLOCK_LOAN_STUCK_211_PAYMENT_CONSULT_TRAFFIC,
        is_active=True,
        category='dana_payment_consult',
        description='This configuration is used to turn off notification '
                    'dana loan stuck 211 payment consult if the feature active'
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            insert_new_feature_setting_dana_block_loan_stuck_211_payment_consult, migrations.RunPython.noop
        )
    ]
