# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-11-23 10:10
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def add_new_fs_for_customer_suspend(apps, schema_editor):
    fs = FeatureSetting.objects.get_or_none(
        feature_name=FeatureNameConst.FTM_CONFIGURATION,
        category='followthemoney',
    )
    if fs:
        fs.parameters.update(expired_loan_for_lenders=[
            'jtp', 'pascal', 'bss_channeling', 'jh', 'blue_finc_lender'])
        fs.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_new_fs_for_customer_suspend, migrations.RunPython.noop)
    ]
