# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-11-28 05:39
from __future__ import unicode_literals

from django.db import migrations
from juloserver.tokopedia.constants import TokoScoreConst
from juloserver.application_flow.models import (
    ApplicationTag,
    ApplicationPathTagStatus,
)


def execute(apps, schema_editor):
    tag_statuses = [
        [0, TokoScoreConst.KEY_NOT_PASSED],
        [1, TokoScoreConst.KEY_PASSED],
    ]
    tag = TokoScoreConst.TAG_NAME

    if not ApplicationTag.objects.filter(application_tag=tag).exists():
        ApplicationTag.objects.create(
            application_tag=tag,
            is_active=True
        )

        for tag_status in tag_statuses:
            ApplicationPathTagStatus.objects.create(
                application_tag=tag,
                status=tag_status[0],
                definition=tag_status[1]
            )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(execute, migrations.RunPython.noop),
    ]
