# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-12-05 05:51
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.constants import MobileFeatureNameConst
from juloserver.julo.models import MobileFeatureSetting
from juloserver.julo.models import Image


class ImageNames(object):
    url_icon_KTP = '/info-card/BOTTOMSHEET_KTP_ICON.png'
    url_icon_USIA = '/info-card/BOTTOMSHEET_USIA_ICON.png'
    url_icon_TINGGAL = '/info-card/BOTTOMSHEET_TINGGAL_ICON.png'
    url_icon_PENGHASILAN = '/info-card/BOTTOMSHEET_PENGHASILAN_ICON.png'


def create_image(image_source_id, image_type, image_url):
    image = Image()
    image.image_source = image_source_id
    image.image_type = image_type
    image.url = image_url
    image.save()


def run(apps, _schema_editor):
    mfs = MobileFeatureSetting.objects.create(
        is_active=True,
        feature_name=MobileFeatureNameConst.BOTTOMSHEET_CONTENT_PRODUCT_PICKER,
        parameters=[
            {
                'product': 'j1',
                'title': 'Registrasi JULO',
                'description': 'Pastikan kamu sudah menyiapkan dan memenuhi persyaratan di bawah, ya!',
                'button_text': 'Lanjutkan',
                'message': [
                    {
                        'message_icon_url': ImageNames.url_icon_KTP,
                        'message_text': 'KTP asli',
                    },
                    {
                        'message_icon_url': ImageNames.url_icon_USIA,
                        'message_text': 'Usia minimum 18 Tahun',
                    },
                    {
                        'message_icon_url': ImageNames.url_icon_TINGGAL,
                        'message_text': 'Tinggal di Indonesia',
                    },
                    {
                        'message_icon_url': ImageNames.url_icon_PENGHASILAN,
                        'message_text': 'Berpenghasilan minimal Rp2.500.000',
                    },
                ],
            },
            {
                'product': 'jturbo',
                'title': 'Registrasi JULO',
                'description': 'Proses registrasi JULO Turbo segera dimulai. Pastikan kamu sudah siapkan penuhi persyaratan di bawah, ya!',
                'button_text': 'Lanjutkan',
                'message': [
                    {
                        'message_icon_url': ImageNames.url_icon_KTP,
                        'message_text': 'KTP asli',
                    },
                    {
                        'message_icon_url': ImageNames.url_icon_USIA,
                        'message_text': 'Usia minimum 18 Tahun',
                    },
                    {
                        'message_icon_url': ImageNames.url_icon_TINGGAL,
                        'message_text': 'Tinggal di Indonesia',
                    },
                    {
                        'message_icon_url': ImageNames.url_icon_PENGHASILAN,
                        'message_text': 'Berpenghasilan minimal Rp2.500.000',
                    },
                ],
            },],
    )

    for image_name in dir(ImageNames):
        if not image_name.startswith('__'):
            image_url = getattr(ImageNames, image_name)
            create_image(mfs.id, 'MOBILE_FEATURE_SETTING_BOTTOMSHEET_ICON', image_url)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(run, migrations.RunPython.noop),
    ]
