# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-11-28 04:10
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.minisquad.constants import FeatureNameConst


def featue_setting_for_cashback_new_scheme(apps, schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.CASHBACK_NEW_SCHEME,
        is_active=True,
        category='account',
        description='cashback new scheme',
        parameters={
            'due_date': -2
        }
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            featue_setting_for_cashback_new_scheme, migrations.RunPython.noop
        )
    ]
