# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-11-27 17:05
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import HelpCenterItem

def update_help_center_item_tanpa_akses_ke_nomor_lama(apps, _schema_editor):
    HelpCenterItem.objects.filter(
        question='Tanpa Akses ke Nomor Lama',
    ).update(
        action_button='reset_phone_number'
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            update_help_center_item_tanpa_akses_ke_nomor_lama, migrations.RunPython.noop)
    ]
