# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-12-18 09:57
from __future__ import unicode_literals

from django.db import migrations

from juloserver.streamlined_communication.constant import CommunicationPlatform, CardProperty
from juloserver.streamlined_communication.models import StreamlinedMessage, StreamlinedCommunication


def populate_sms(apps, schema_editor):
    sms_list = [
        {
            'dpd': -5,
            'template_code': '{}_sms_dpd_robocall_-5',
            'type': 'Payment Reminder',
            'time_sent': '14:0',
            'partner_selection_action': 'exclude',
            'partner_selection_list': '{4,19,20,24,10,9,21,12,17,22,23,27,45,28,25,11,26,41,42,29,30,31,32,33,34,35,36,37,38,39,40,43,44,1,53,56,61,63,46}',
            'message': 'Kamu telah dihubungi JULO via telepon ttg detail tagihanmu. Yuk cek selengkapnya di {{sms_payment_details_url}} & bayar tagihanmu sekarang untuk raih cashback!',
            'description': 'payment reminder for dpd -5 J1 customer',
            'parameter': '{sms_payment_details_url}'
        },
        {
            'dpd': -3,
            'template_code': '{}_sms_dpd_robocall_-3',
            'type': 'Payment Reminder',
            'time_sent': '14:0',
            'partner_selection_action': 'exclude',
            'partner_selection_list': '{4,19,20,24,10,9,21,12,17,22,23,27,45,28,25,11,26,41,42,29,30,31,32,33,34,35,36,37,38,39,40,43,44,1,53,56,58,60,61,62,63,55,46}',
            'message': 'Kamu telah dihubungi JULO via telepon ttg detail tagihanmu. Yuk cek selengkapnya di {{sms_payment_details_url}} & bayar tagihanmu sekarang untuk raih cashback!',
            'description': 'payment reminder for dpd -3 J1 customer',
            'parameter': '{sms_payment_details_url}'
        },
    ]

    products = ['j1']
    for template in sms_list:
        dpd = template['dpd']
        content = template['message']
        template_code = template['template_code']
        time_sent = template['time_sent']
        parameter = template['parameter']

        for product in products:
            message = StreamlinedMessage.objects.create(
                message_content=content,
                parameter=parameter
            )
            StreamlinedCommunication.objects.create(
                dpd=dpd,
                communication_platform=CommunicationPlatform.SMS,
                template_code=template_code.format(product),
                is_active=True,
                type=template['type'],
                time_sent=time_sent,
                message=message,
                is_automated=False,
                time_out_duration=3,
                product=product,
                partner_selection_action=template['partner_selection_action'],
                partner_selection_list=template['partner_selection_list'],
                description=template['description'],
                extra_conditions=CardProperty.SMS_AFTER_ROBOCALL_EXPERIMENT
            )

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(populate_sms, migrations.RunPython.noop),
    ]
