# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-12-19 03:33
from __future__ import unicode_literals

from django.db import migrations


from juloserver.julo.models import ProductLookup
from juloserver.julo.product_lines import ProductLineCodes


def update_late_fee_pct_product_lookup_manual_process(apps, schema_editor):
    manual_process_product_line_codes = {
        ProductLineCodes.AXIATA_WEB,
        ProductLineCodes.EFISHERY,
        ProductLineCodes.EFISHERY_INTI_PLASMA,
        ProductLineCodes.EFISHERY_KABAYAN_LITE,
        ProductLineCodes.EFISHERY_JAWARA,
        ProductLineCodes.EFISHERY_KABAYAN_REGULER,
        ProductLineCodes.RABANDO,
        ProductLineCodes.KOPERASI_TUNAS,
        ProductLineCodes.KOPERASI_TUNAS_45,
        ProductLineCodes.AGRARI,
        ProductLineCodes.DAGANGAN,
        ProductLineCodes.FISHLOG,
    }
    product_lookup = ProductLookup.objects.filter(
        product_line__in=manual_process_product_line_codes)
    
    for pl in product_lookup:
        pl.late_fee_pct = 0.03
        pl.save()
        

class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunPython(update_late_fee_pct_product_lookup_manual_process)
    ]
