# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-12-08 08:40
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting

def create_new_feature_setting(apps, schema_editor):
    FeatureSetting.objects.get_or_create(
        is_active=False,
        feature_name=FeatureNameConst.LDDE_V2_SETTING,
        category="loan",
        parameters={
            'ldde_version': {
                'v1_last_digit_of_application_id': [1,2,3,4,5],
                'v2_last_digit_of_application_id': [6,7,8,9,0],
            }
        },
        description="configuration for j1 account selloff"
    )

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_new_feature_setting, migrations.RunPython.noop),
    ]
