# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-12-05 13:23
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst

from juloserver.julo.models import FeatureSetting


def add_feature_setting_for_risky_change_phone_activity(apps, _schema_editor):
    FeatureSetting.objects.get_or_create(
        is_active=False,
        feature_name=FeatureNameConst.RISKY_CHANGE_PHONE_ACTIVITY_CHECK,
        description="Configuration risky phone change activity check",
        parameters={}
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_feature_setting_for_risky_change_phone_activity, migrations.RunPython.noop),
    ]
