# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-12-18 07:15
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def update_customer_data_change_request_feature(*args):
    feature_setting = FeatureSetting.objects.get(
        feature_name=FeatureNameConst.CUSTOMER_DATA_CHANGE_REQUEST,
    )
    if feature_setting.parameters is None:
        feature_setting.parameters = {}
    feature_setting.parameters['payslip_income_multiplier'] = 1.3
    feature_setting.save(update_fields=['parameters'])


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(update_customer_data_change_request_feature, migrations.RunPython.noop),
    ]
