# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-12-12 08:33
from __future__ import unicode_literals

from django.db import migrations

from juloserver.streamlined_communication.constant import CommunicationPlatform
from juloserver.streamlined_communication.models import StreamlinedCommunicationParameterList


def add_new_parameter(apps, schema_editor):
    data_seeds = [
        StreamlinedCommunicationParameterList(
            parameter_name='{sms_month_due_date}',
            description='format = mmmm',
            platform=CommunicationPlatform.SMS,
            parameter_model_value={
                'accountpayment': 'model.due_date',
                'format_value': 'format_date({}, "MMMM", locale="id_ID")',
            }
        ),
        StreamlinedCommunicationParameterList(
            parameter_name='{pn_month_due_date}',
            description='format = mmmm',
            platform=CommunicationPlatform.PN,
            parameter_model_value={
                'accountpayment': 'model.due_date',
                'format_value': 'format_date({}, "MMMM", locale="id_ID")',
            }
        ),
        StreamlinedCommunicationParameterList(
            parameter_name='{email_month_due_date}',
            description='format = mmmm',
            platform=CommunicationPlatform.EMAIL,
            parameter_model_value={
                'accountpayment': 'model.due_date',
                'format_value': 'format_date({}, "MMMM", locale="id_ID")',
            }
        ),
        StreamlinedCommunicationParameterList(
            parameter_name='{card_month_due_date}',
            description='format = mmmm',
            platform=CommunicationPlatform.INFO_CARD,
            parameter_model_value={
                'accountpayment': 'model.due_date',
                'format_value': 'format_date({}, "MMMM", locale="id_ID")',
            }
        ),
        StreamlinedCommunicationParameterList(
            parameter_name='{robocall_month_due_date}',
            description='format = mmmm',
            platform=CommunicationPlatform.ROBOCALL,
            parameter_model_value={
                'accountpayment': 'model.due_date',
                'format_value': 'format_date({}, "MMMM", locale="id_ID")',
            }
        ),
    ]
    StreamlinedCommunicationParameterList.objects.bulk_create(data_seeds)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_new_parameter, migrations.RunPython.noop)
    ]

