# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-12-16 12:21
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import ExperimentSetting
from juloserver.julo.constants import ExperimentConst

def add_feature_setting(apps, schema_editor):
    ExperimentSetting.objects.create(
        is_active=False,
        code=ExperimentConst.DUKCAPIL_FR,
        name="Dukcapil Face Recognition",
        start_date="2023-12-18 00:00:00+00",
        end_date="2024-01-18 00:00:00+00",
        schedule="",
        action="",
        type="application",
        criteria={'score_threshold': 1}
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_feature_setting, migrations.RunPython.noop),
    ]
