# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-12-12 08:28
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.minisquad.constants import (
    FeatureNameConst,
    DialerSystemConst,
)


def add_grab_to_ai_rudder_feature_setting(apps, schema_editor):

    feature_ai_rudder_tasks_config = FeatureSetting.objects.filter(
        feature_name=FeatureNameConst.AI_RUDDER_TASKS_STRATEGY_CONFIG).last()
    if not feature_ai_rudder_tasks_config:
        return

    feature_ai_rudder_tasks_config_params = feature_ai_rudder_tasks_config.parameters
    grab_config = {
        "autoQA": "N",
        "acwTime": "20",
        "end_time": "20:00",
        "ringLimit": "0",
        "slotFactor": "",
        "qaConfigId": 142,
        "rest_times": [
            ["12:00", "13:00"]
        ],
        "resultStrategies": "on",
        "resultStrategiesConfig": [
            {
                "action": [
                    1,
                    2
                ],
                "dncDay": 1,
                "oper": "==",
                "title": "Level2",
                "value": "WPC"
            },
            {
                "action": [
                    1
                ],
                "oper": "==",
                "title": "Level2",
                "value": "ShortCall"
            }
        ],
        "start_time": "08:00",
        "dialingMode": "0",
        "maxLostRate": "5",
        "repeatTimes": "5",
        "callInterval": "0",
        "dialingOrder": ["mobile_phone_2","mobile_phone_1_2","mobile_phone_1_3", "mobile_phone_1_4"],
        "autoSlotFactor": "1",
        "bulkCallInterval": "300",
        "contactNumberInterval": "300"
    }
    feature_ai_rudder_tasks_config_params[DialerSystemConst.GRAB] = grab_config
    feature_ai_rudder_tasks_config.parameters = feature_ai_rudder_tasks_config_params
    feature_ai_rudder_tasks_config.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_grab_to_ai_rudder_feature_setting, migrations.RunPython.noop)
    ]
