# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-12-26 05:14
from __future__ import unicode_literals

from django.db import migrations

from juloserver.payback.models import DanaBillerStatus


def add_new_status_dana_biller(apps, schema_editor):
    statuses_data = [
        {'code': 30, 'is_success': False, 'message': 'Duplicate Transaction'},
        {'code': 30, 'is_success': False, 'message': 'General Error'}
    ]

    for data in statuses_data:
        DanaBillerStatus.objects.create(**data)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_new_status_dana_biller, migrations.RunPython.noop)
    ]
