# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-12-21 09:22
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting
from juloserver.minisquad.constants import FeatureNameConst


def add_qalimitlength_and_qalimitrate(apps, schema_editor):
    feature_group_mapping_config = FeatureSetting.objects.filter(
        feature_name=FeatureNameConst.AI_RUDDER_TASKS_STRATEGY_CONFIG).last()
    if not feature_group_mapping_config:
        return
    params = feature_group_mapping_config.parameters
    new_params = {}
    for key, bucket_config in params.items():
        bucket_config['qaLimitLength'] = 0
        bucket_config['qaLimitRate'] = 100
        new_params[key] = bucket_config
    feature_group_mapping_config.parameters = new_params
    feature_group_mapping_config.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_qalimitlength_and_qalimitrate, migrations.RunPython.noop)
    ]
