# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-12-20 19:16
from __future__ import unicode_literals

from django.db import migrations

from juloserver.streamlined_communication.models import NeoBannerCard, NeoInfoCard
from juloserver.julo.models import Image


class ImageNames(object):
    BANNER_135_CANNOT_REAPPLY_BANK_STATEMENT_AVAILABLE = 'neo-banner/JULO-System_Icon_24-06.jpg'


def create_image(image_source_id, image_type, image_url):
    image = Image()
    image.image_source = image_source_id
    image.image_type = image_type
    image.url = image_url
    image.save()


def retroload_neobanner_j1(_apps, _schema_editor):
    data_to_be_loaded = [
            {
                'statuses': '[135_CANNOT_REAPPLY_BANK_STATEMENT_AVAILABLE]',
                'product': 'J1',
                'template_card': 'B_BUTTON',
                'top_image': ImageNames.BANNER_135_CANNOT_REAPPLY_BANK_STATEMENT_AVAILABLE,
                'top_title': 'Yuk, Upload Rekening Koran Kamu!',
                'top_message': 'Biar pengajuanmu bisa diproses lebih cepat dan kesempatan disetujui lebih besar, oke?',
                'button_text': 'Upload Rekening Koran',
                'button_action_type': 'redirect',
                'button_action': None,
                'extended_image': None,
                'extended_title': None,
                'extended_message': None,
                'extended_button_text': None,
                'extended_button_action': None,
            },
    ]

    for data in data_to_be_loaded:
        neo_banner_card = NeoBannerCard.objects.create(**data)
        create_image(neo_banner_card.id, 'NEO_BANNER_TOP_BACKGROUND_IMAGE', data['top_image'])

    neo_banner_card = NeoBannerCard.objects.get(statuses='[105_C_SCORE, 133, 135_CANNOT_REAPPLY, 106_CANNOT_REAPPLY]')
    neo_banner_card.statuses = '[105_C_SCORE, 133, 135_CANNOT_REAPPLY_BANK_STATEMENT_UNAVAILABLE, 106_CANNOT_REAPPLY]'
    neo_banner_card.save()

    neo_info_card = NeoInfoCard.objects.get(statuses='[105_C_SCORE,133,135_REAPPLY,135_CANNOT_REAPPLY]')
    neo_info_card.statuses = '[105_C_SCORE,133,135_REAPPLY,135_CANNOT_REAPPLY_BANK_STATEMENT_AVAILABLE,135_CANNOT_REAPPLY_BANK_STATEMENT_UNAVAILABLE]'
    neo_info_card.save()

    neo_info_card = NeoInfoCard.objects.get(statuses='[105_C_SCORE,133,135_CANNOT_REAPPLY,106_CANNOT_REAPPLY]')
    neo_info_card.statuses = '[105_C_SCORE,133,135_CANNOT_REAPPLY_BANK_STATEMENT_AVAILABLE,135_CANNOT_REAPPLY_BANK_STATEMENT_UNAVAILABLE,106_CANNOT_REAPPLY]'
    neo_info_card.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(retroload_neobanner_j1, migrations.RunPython.noop)
    ]
