# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-12-21 07:59
from __future__ import unicode_literals

from django.db import migrations
from juloserver.application_flow.models import (
    ApplicationTag,
    ApplicationPathTagStatus,
)


def execute(apps, schema_editor):

    definition = 'success'
    tag_statuses = [
        [1, definition],
    ]
    tags = [
        'is_fail_heimdall_whitelisted_rescored',
        'is_no_fdc_whitelisted_rescored',
        'is_fail_mycroft_whitelisted_rescored',
    ]

    for tag in tags:
        if not ApplicationTag.objects.filter(application_tag=tag).exists():
            ApplicationTag.objects.create(
                application_tag=tag,
                is_active=True
            )

        for tag_status in tag_statuses:
            ApplicationPathTagStatus.objects.create(
                application_tag=tag,
                status=tag_status[0],
                definition=tag_status[1]
            )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(execute, migrations.RunPython.noop),
    ]
