# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-01-10 08:24
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import WorkflowStatusPath, Workflow
from juloserver.julo.constants import WorkflowConst, ApplicationStatusCodes


def run(apps, schema_editor):
    workflow = Workflow.objects.filter(name=WorkflowConst.JULO_ONE).last()
    if workflow:
        WorkflowStatusPath.objects.get_or_create(
            status_previous=ApplicationStatusCodes.MISSING_EMERGENCY_CONTACT,
            status_next=ApplicationStatusCodes.LOC_APPROVED,
            type="happy",
            workflow=workflow
        )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(run, migrations.RunPython.noop)
    ]
