# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-01-10 10:18
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting
from juloserver.loan.constants import LoanTaxConst
from juloserver.loan.models import LoanAdditionalFeeType
from juloserver.payment_point.constants import TransactionMethodCode

def create_feture_setting_for_loan_tax(apps, _schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.LOAN_TAX_CONFIG,
        parameters={
            "whitelist": {
                "is_active": False,
                "list_application_ids": []
            },
            "tax_percentage": 0.11,
            "product_line_codes": LoanTaxConst.DEFAULT_PRODUCT_LINE_CODES,
        },
        is_active=False,
        category="Loan",
        description="Configuration to set Tax for SEOJK purpose",
    )

    LoanAdditionalFeeType.objects.create(
        name=LoanTaxConst.ADDITIONAL_FEE_TYPE,
        notes=("Tax for loan, calculated from provision. This fee will ignore daily max fee rule")
    )


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunPython(create_feture_setting_for_loan_tax, migrations.RunPython.noop),
    ]
