# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-01-23 07:46
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst


def update_feature_setting_sending_recording(apps, _schema_editor):
    sending_recording_configuration = FeatureSetting.objects.filter(
        feature_name=FeatureNameConst.SENDING_RECORDING_CONFIGURATION
    ).last()
    if sending_recording_configuration:
        exists_parameters = sending_recording_configuration.parameters
        exists_parameters['recording_resources'] = ['SME', 'AiRudder']
        exists_parameters['recording_duration_type'] = 'gte'
        exists_parameters['recording_duration'] = [20]
        FeatureSetting.objects.filter(
            feature_name=FeatureNameConst.SENDING_RECORDING_CONFIGURATION
        ).update(parameters=exists_parameters, is_active=False)
    else:
        FeatureSetting.objects.create(
            feature_name=FeatureNameConst.SENDING_RECORDING_CONFIGURATION,
            is_active=False, category='collection',
            description='for determine recording file eligible for send to airudder',
            parameters={
                'buckets': [],
                'call_result_ids': [],
                'recording_duration': [20],
                'recording_resources': ['SME', 'AiRudder'],
                'recording_duration_type': 'gte'
            }
        )



class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            update_feature_setting_sending_recording, migrations.RunPython.noop),
    ]
