# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-01-22 03:51
from __future__ import unicode_literals

from django.db import migrations
from juloserver.followthemoney.models import LoanAgreementTemplate
from juloserver.followthemoney.constants import LoanAgreementType

def update_skrtp_for_loan_tax(apps, _schema_editor):
    templates = LoanAgreementTemplate.objects.filter(
        is_active=True, agreement_type=LoanAgreementType.SKRTP
    )
    for template in templates:
        title = "<b>PAJAK, BEA METERAI DAN BIAYA-BIAYA LAIN</b>"
        appended_content = """<li>Atas penggunaan Fasilitas Pendanaan ini, Anda akan
        dibebankan Pajak Pertambahan Nilai (PPN) yang dihitung dari Biaya Provisi,
        yaitu sebesar {{loan_tax_amount}}</li>
        """
        body = template.body

        start_idx = body.find(title)
        if start_idx:
            substr = body[start_idx:]
            end_idx = substr.find('</ol>')
            index = end_idx + start_idx
            body = body[:index] + appended_content + body[index:]
            template.body = body
            template.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(update_skrtp_for_loan_tax, migrations.RunPython.noop),
    ]
