# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-01-17 07:14
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def create_grab_defence_feature_parameter_feature_setting(*args):
    setting = FeatureSetting.objects.get_or_none(feature_name=FeatureNameConst.GRAB_DEFENCE_FRAUD_SCORE)
    setting.parameters['is_associated_entities_enabled'] = True
    setting.save(update_fields=['parameters'])


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_grab_defence_feature_parameter_feature_setting, migrations.RunPython.noop),
    ]
