# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-01-17 01:07
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.constants import FeatureNameConst

from juloserver.julo.models import FeatureSetting


def add_feature_setting_for_dana_seojk_rule(apps, _schema_editor):
    FeatureSetting.objects.get_or_create(
        is_active=False,
        feature_name=FeatureNameConst.DANA_SEOJK_RULE,
        category="dana",
        description="Setting to active and inactive SEOJK rule",
    )


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunPython(
            add_feature_setting_for_dana_seojk_rule, migrations.RunPython.noop
        )
    ]
