# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-01-18 07:19
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.statuses import LoanStatusCodes
from juloserver.julo.models import StatusLookup


def add_loan_invalidated_status_lookup(apps, _schema_editor):
    StatusLookup.objects.create(
        status_code=LoanStatusCodes.LOAN_INVALIDATED,
        status="Loan Invalidated"
    )


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_loan_invalidated_status_lookup, migrations.RunPython.noop),
    ]
