# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-07-15 10:43
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.constants import MobileFeatureNameConst
from juloserver.julo.models import MobileFeatureSetting


def add_new_feature_setting(apps, _schema_editor):
    created_data = {
        'feature_name': MobileFeatureNameConst.CLIK_INTEGRATION,
        'is_active': False,
        'parameters': {
            'swap_ins': {
            	'is_active': False,
            	'total_overdue': 1000000,
            	'score_raw': 500,
            	'pgood': 0.75,
            },
            'swap_outs': {
            	'is_active': False,
            	'total_overdue': 1000000,
            	'score_raw': 200,
            	'reporting_providers': 10,
            },
        },
    }
    MobileFeatureSetting.objects.create(**created_data)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_new_feature_setting, migrations.RunPython.noop),
    ]
