# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-01-29 04:47
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting

def add_dana_cashloan_registration_feature_setting(apps, schema_editor):
    feature_setting = FeatureSetting.objects.filter(
        feature_name=FeatureNameConst.DANA_CASH_LOAN_REGISTRATION_USER_CONFIG,
    ).exists()
    
    if not feature_setting:
        created_data = {
            'feature_name': FeatureNameConst.DANA_CASH_LOAN_REGISTRATION_USER_CONFIG,
            'is_active': True,
            'parameters': {},
            'category': 'partner',
            'description': 'Product Configuration to allowing Existing Dana Cicil User when Dana Cash Loan User hit account binding'
        }
        FeatureSetting.objects.create(**created_data)

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_dana_cashloan_registration_feature_setting, migrations.RunPython.noop),
    ]
