# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-01-25 12:38
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import StatusLookup

from juloserver.julo.statuses import ApplicationStatusCodes


def add_customer_deletion_application_statuses(apps, _schema_editor):
    if not StatusLookup.objects.filter(status_code=ApplicationStatusCodes.CUSTOMER_ON_DELETION).exists():
        StatusLookup.objects.create(
            status_code=ApplicationStatusCodes.CUSTOMER_ON_DELETION,
            status="Customer On Deletion",
        )
    
    if not StatusLookup.objects.filter(status_code=ApplicationStatusCodes.CUSTOMER_DELETED).exists():
        StatusLookup.objects.create(
            status_code=ApplicationStatusCodes.CUSTOMER_DELETED,
            status="Customer Deleted",
        )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_customer_deletion_application_statuses, migrations.RunPython.noop),
    ]
