# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-01-30 10:13
from __future__ import unicode_literals

from django.db import migrations

from juloserver.healthcare.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def add_feature_setting_healthcare_faq(apps, schema_editor):
    FeatureSetting.objects.update_or_create(
        feature_name=FeatureNameConst.HEALTHCARE_FAQ,
        defaults={
            'is_active': True,
            'parameters': [
                {
                    "title": "Bagaimana cara mengajukan nama rumah sakit baru jika tidak ada dalam daftar pencarian?",
                    "content": "1. Pada kolom pencarian, ketik nama rumah sakit, apotek, atau klinik yang kamu inginkan<br>"
                               "2. Klik <b>Tambah</b><br>"
                               "3. Isi informasi rumah sakit dan pasien yang diminta, lalu klik <b>Tambahkan</b><br>"
                               "4. Selesai! Rumah sakit tersebut akan muncul di daftar rumah sakit tujuanmu."
                },
                {
                    "title": "Apa saja contoh aplikasi kesehatan yang dimaksud di Biaya Kesehatan?",
                    "content": "Beberapa contoh aplikasi kesehatan yang bisa kamu bayar lewat Biaya Kesehatan adalah Halodoc, Alodokter, GoodDoctor, dll."
                },
                {
                    "title": "FAQ #2",
                    "content": "Ini jawaban untuk faq #2"
                },
                {
                    "title": "FAQ #3",
                    "content": "Ini jawaban untuk faq #3"
                },
            ],
        },
        is_active=True,
        description='FAQ for healthcare',
        category='healthcare'
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_feature_setting_healthcare_faq, migrations.RunPython.noop),
    ]
