# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-02-13 07:47
from __future__ import unicode_literals

from django.contrib.auth.models import Group, User
from django.db import migrations

from juloserver.julo.models import (
    Customer,
    ProductProfile,
    ProductLine,
    ProductLookup,
    ProductLineLoanPurpose,
    Partner,
)

from juloserver.julo.product_lines import ProductLineCodes
from juloserver.portal.object.bulk_upload.constants import (
    MerchantFinancingCSVUploadPartner,
    MerchantFinancingCSVUploadPartnerDueDateType,
)

from django.conf import settings


def add_product_line_gajigesa(apps, schema_editor):
    monthly_payment_frequency = 'Monthly'
    gajigesa_product_profile = ProductProfile.objects.filter(code=ProductLineCodes.GAJIGESA).last()
    gajigesa_product_line = ProductLine.objects.filter(product_line_code=ProductLineCodes.GAJIGESA).last()

    if gajigesa_product_profile:
        gajigesa_product_profile.update_safely(
            name=MerchantFinancingCSVUploadPartner.GAJIGESA,
            code=ProductLineCodes.GAJIGESA,
            min_amount=1000000,
            max_amount=2000000000,
            min_duration=1,
            max_duration=365,
            min_interest_rate=0.336,
            max_interest_rate=0.336,
            interest_rate_increment=0,
            payment_frequency=monthly_payment_frequency,
            min_origination_fee=0,
            max_origination_fee=0.002,
            late_fee=0.03,
            cashback_initial=0,
            cashback_payment=0,
            debt_income_ratio=0.3,
            origination_fee_increment=0,
            is_active=True,
            is_initial=False,
            is_product_exclusive=False,
        )
    else:
        gajigesa_product_profile, _ = ProductProfile.objects.get_or_create(
            name=MerchantFinancingCSVUploadPartner.GAJIGESA,
            code=ProductLineCodes.GAJIGESA,
            min_amount=1000000,
            max_amount=2000000000,
            min_duration=1,
            max_duration=365,
            min_interest_rate=0.336,
            max_interest_rate=0.336,
            interest_rate_increment=0,
            payment_frequency=monthly_payment_frequency,
            min_origination_fee=0,
            max_origination_fee=0.002,
            late_fee=0.03,
            cashback_initial=0,
            cashback_payment=0,
            debt_income_ratio=0.3,
            origination_fee_increment=0,
            is_active=True,
            is_initial=False,
            is_product_exclusive=False,
        )

    if gajigesa_product_line:
        gajigesa_product_line.update_safely(
            product_line_code=ProductLineCodes.GAJIGESA,
            product_line_type=MerchantFinancingCSVUploadPartner.GAJIGESA,
            min_amount=1000000,
            max_amount=2000000000,
            min_duration=1,
            max_duration=365,
            min_interest_rate=0.336,
            max_interest_rate=0.336,
            payment_frequency=monthly_payment_frequency,
            product_profile=gajigesa_product_profile
        )
    else:
        gajigesa_product_line, _ = ProductLine.objects.get_or_create(
            product_line_code=ProductLineCodes.GAJIGESA,
            product_line_type=MerchantFinancingCSVUploadPartner.GAJIGESA,
            min_amount=1000000,
            max_amount=2000000000,
            min_duration=1,
            max_duration=365,
            min_interest_rate=0.336,
            max_interest_rate=0.336,
            payment_frequency=monthly_payment_frequency,
            product_profile=gajigesa_product_profile
        )

    product_lookup = ProductLookup.objects.filter(
        product_line=gajigesa_product_line,
        product_profile=gajigesa_product_profile
    ).last()

    if product_lookup:
        product_lookup.update_safely(
            product_name="I.0336-O.002-L.003-C1.000-C2.000-M",
            interest_rate=0.336,
            origination_fee_pct=0.002,
            late_fee_pct=0.03,
            cashback_initial_pct=0,
            cashback_payment_pct=0
        )
    else:
        ProductLookup.objects.get_or_create(
            product_line=gajigesa_product_line,
            product_profile=gajigesa_product_profile,
            product_name="I.0336-O.002-L.003-C1.000-C2.000-M",
            interest_rate=0.336,
            origination_fee_pct=0.002,
            late_fee_pct=0.03,
            cashback_initial_pct=0,
            cashback_payment_pct=0
        )

    gajigesa_product_line_loan_purpose = ProductLineLoanPurpose.objects.filter(
        product_line=gajigesa_product_line
    ).last()
    if gajigesa_product_line_loan_purpose:
        gajigesa_product_line_loan_purpose.loan_purpose_id = 1
        gajigesa_product_line_loan_purpose.save()
    else:
        ProductLineLoanPurpose.objects.get_or_create(
            product_line=gajigesa_product_line,
            loan_purpose_id=1
        )


def create_partner_gajigesa(apps, schema_editor):
    group = Group.objects.get(name="julo_partners")

    user = User.objects.create(
        username=MerchantFinancingCSVUploadPartner.GAJIGESA,
        email='ahmad.mushthafa@julofinance.com',
    )
    user.groups.add(group)

    if settings.ENVIRONMENT == 'prod':
        app_190_email_recipients = 'ahmad.mushthafa@julofinance.com'
        disburse_email_recipients = 'ahmad.mushthafa@julofinance.com'
    else:
        app_190_email_recipients = 'arif.muflihudin@julofinance.com,rafika.solicha@julofinance.com'
        disburse_email_recipients = 'arif.muflihudin@julofinance.com,rafika.solicha@julofinance.com'

    gajigesa_product_line = ProductLine.objects.filter(
        product_line_code=ProductLineCodes.GAJIGESA
    ).last()

    partner = Partner.objects.create(
        user=user,
        poc_email='ahmad.mushthafa@julofinance.com',
        poc_phone='',
        poc_name=MerchantFinancingCSVUploadPartner.GAJIGESA,
        name=MerchantFinancingCSVUploadPartner.GAJIGESA,
        email='ahmad.mushthafa@julofinance.com',
        company_name=MerchantFinancingCSVUploadPartner.GAJIGESA,
        is_active=True,
        is_csv_upload_applicable=True,
        partner_bank_account_number='1220011719039',
        partner_bank_account_name='EASY MANAGEMENT SYSTEMS PT',
        partner_bank_name='BANK MANDIRI (PERSERO), Tbk',
        is_disbursement_to_partner_bank_account=True,
        recipients_email_address_for_190_application=app_190_email_recipients,
        recipients_email_address_for_bulk_disbursement=disburse_email_recipients,
        sender_email_address_for_190_application='ops.gajigesa@julo.co.id',
        sender_email_address_for_bulk_disbursement='ops.gajigesa@julo.co.id',
        due_date_type=MerchantFinancingCSVUploadPartnerDueDateType.END_OF_TENOR,
        product_line=gajigesa_product_line,
    )

    Customer.objects.create(user=user, email='ahmad.mushthafa@julofinance.com', phone=partner.phone)

    gajigesa_product_line = ProductLine.objects.filter(product_line_code=ProductLineCodes.GAJIGESA).last()


class Migration(migrations.Migration):

    operations = [
        migrations.RunPython(add_product_line_gajigesa, migrations.RunPython.noop),
        migrations.RunPython(create_partner_gajigesa, migrations.RunPython.noop),
    ]
