# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-11-20 07:04
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def add_cimb_to_bank_group(apps, _schema_editor):
    order_payment_method_feature_setting = FeatureSetting.objects.filter(
        feature_name=FeatureNameConst.ORDER_PAYMENT_METHODS_BY_GROUPS
    ).last()

    if not order_payment_method_feature_setting:
        return

    order_payment_method_feature_setting.parameters['bank_va_group'].append('bank cimb niaga')
    order_payment_method_feature_setting.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_cimb_to_bank_group, migrations.RunPython.noop),
    ]
