# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-12-19 04:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations

from juloserver.application_flow.models import ApplicationTag, ApplicationPathTagStatus
from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def add_is_goldfish_application_tag(apps, schema_editor):
    tag_data = ['is_goldfish']
    for tag in tag_data:
        ApplicationTag.objects.create(application_tag=tag)

    application_tag_data = [
        ['is_goldfish', 1, 'success'],
    ]
    for application_tag in application_tag_data:
        ApplicationPathTagStatus.objects.create(
            application_tag=application_tag[0],
            status=application_tag[1],
            definition=application_tag[2]
        )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(
            add_is_goldfish_application_tag,
            migrations.RunPython.noop
        ),
    ]
