# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-02-12 07:40
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import GlobalPaymentMethod
from juloserver.julo.banks import BankCodes


def insert_global_payment_method_cimb_va(apps, schema_editor):
    GlobalPaymentMethod.objects.create(
        feature_name='CIMB',
        payment_method_code=BankCodes.CIMB_NIAGA,
        is_active=True,
        payment_method_name='Bank CIMB Niaga',
        impacted_type='Primary and Backup'
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(insert_global_payment_method_cimb_va, migrations.RunPython.noop),
    ]
