# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-02-09 08:30
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting


def update_grab_defence_fraud_score_feature_setting_parameter(*args):
    feature_setting = FeatureSetting.objects.get_or_none(feature_name='grab_defence_fraud_score')
    if feature_setting:
        if not feature_setting.parameters:
            feature_setting.parameters = {}

        feature_setting.parameters['predict_event_trigger_delay_in_seconds'] = 20
        feature_setting.save(update_fields=['parameters'])


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            update_grab_defence_fraud_score_feature_setting_parameter,
            migrations.RunPython.noop,
        ),
    ]
