# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-02-15 03:14
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import VariableStorage
from juloserver.julo.constants import VariableStorageKeyConst
from django.utils import timezone
import roman

def add_variable_storage_for_warning_letter_number(apps, _schema_editor):
    data_to_be_created = {
        'variable_key': VariableStorageKeyConst.WARNING_LETTER_EXT_NUMBER,
        'is_active': True,
        'parameters': {
            'warning_letter_number': 1,
            'warning_letter_ext_number': "1/JTF/HLO/%s/%d" % (
                                            roman.toRoman(timezone.localtime(timezone.now()).month),
                                            timezone.localtime(timezone.now()).year,
                                        ),
            'month': timezone.localtime(timezone.now()).month,
            'year': timezone.localtime(timezone.now()).year,
        },
    }
    VariableStorage.objects.get_or_create(**data_to_be_created)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_variable_storage_for_warning_letter_number, migrations.RunPython.noop),
    ]
