# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-02-26 09:25
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import ProductLine, ProductLineCodes, FDCActiveLoanChecking
from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def retroload_product_line_for_fdc_active_loan_checking_table(apps, _schema_editor):
    product_line = ProductLine.objects.filter(product_line_code=ProductLineCodes.J1).last()
    if product_line:
        FDCActiveLoanChecking.objects.all().update(product_line=product_line)


def update_fdc_3PR_fs_for_product_lines(apps, _schema_editor):
    fs = FeatureSetting.objects.filter(
        feature_name=FeatureNameConst.CHECK_OTHER_ACTIVE_PLATFORMS_USING_FDC,
    ).last()
    if fs:
        fs.parameters['daily_checker_config'].update(
            applied_product_lines=[ProductLineCodes.J1, ProductLineCodes.JTURBO]
        )
        fs.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(retroload_product_line_for_fdc_active_loan_checking_table, migrations.RunPython.noop),
        migrations.RunPython(update_fdc_3PR_fs_for_product_lines, migrations.RunPython.noop)
    ]
