# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-02-19 03:59
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting
from juloserver.payback.constants import FeatureSettingNameConst


def add_feature_settings_change_cimb_va_credentials(apps, schema_editor):
    FeatureSetting.objects.get_or_create(
        feature_name=FeatureSettingNameConst.CHANGE_CIMB_VA_CREDENTIALS,
        parameters={
            'public_key': '''-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0+fmqDagX6vDWOhAWEh0
HIv6mrRdjXqIlNxOvxU52G7X/d0DZLDIXbQvpTYLBl3bGGu0p5zvzgrZjjkuAolX
m3I1dbyQHv3fZcC2Rw2P91DvytMaOB6kO6qfWbwuvT++mYt5zGYtHh21LFhFdlty
gebNS66kRCfH9F618acFH8y45/S34uHvawBkDaPciWtrBUSFF5QjGn6Mm/IEwW88
kegvfefvvNJkVN90wJ+cv+tHKdCYHPIf3d5mJ/uaPyXR+U/n+53p7cUbYF8nWzaz
Oho0apRRZ+xbGg2/Cw6LVCLpx/Y3H/nAiCfAm35g+Wlqt063h2mainmT+gcSKrL8
9QIDAQAB
-----END PUBLIC KEY-----'''
        },
        is_active=False,
        category='payback',
        description='change cimb va credentials',
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(
            add_feature_settings_change_cimb_va_credentials, migrations.RunPython.noop
        )
    ]
