# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-02-19 18:21
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import WorkflowStatusPath, Workflow
from juloserver.julo.constants import WorkflowConst


def run(apps, schema_editor):
    workflow = Workflow.objects.filter(name=WorkflowConst.JULO_ONE).last()
    paths = [
        (127, 131, "detour"),
        (128, 131, "detour"),
        (127, 115, "detour"),
        (128, 115, "detour"),
        (127, 128, "detour"),
        (127, 135, "graveyard"),
        (128, 135, "graveyard"),
        (127, 137, "graveyard"),
        (128, 137, "graveyard"),
        (127, 133, "graveyard"),
        (128, 133, "graveyard"),
        (127, 124, "happy"),
        (128, 124, "happy"),
    ]
    for path in paths:
        if WorkflowStatusPath.objects.filter(
            status_previous=path[0],
            status_next=path[1],
            workflow=workflow
        ).exists():
            continue

        WorkflowStatusPath.objects.create(
            workflow=workflow,
            status_previous=path[0],
            status_next=path[1],
            type=path[2],
            is_active=True,
            customer_accessible=False,
            agent_accessible=True
        )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(run, migrations.RunPython.noop),
    ]
