# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-02-27 07:41
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def swift_limit_drainer_feature_setting_for_jail_control(*args, **kwargs):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.SWIFT_LIMIT_DRAINER,
        is_active=False,
        category='fraud',
        parameters={
            'jail_days': 7
        },
        description='Swift Limit Drainer AntiFraud control.'
    )


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunPython(swift_limit_drainer_feature_setting_for_jail_control,
                             migrations.RunPython.noop)
    ]
