# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-03-04 08:40
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.channeling_loan.constants import (
    FeatureNameConst,
    ChannelingConst,
)


def update_risk_premium_on_channeling_loan_config(apps, _schema_editor):
    fs = FeatureSetting.objects.filter(feature_name=FeatureNameConst.CHANNELING_LOAN_CONFIG).last()
    if fs:
        parameters = fs.parameters
        for key in parameters.keys():
            risk_premium_percentage = 0
            if key == ChannelingConst.BSS:
                parameters[key]['general']['INTEREST_PERCENTAGE'] = 15
                risk_premium_percentage = 18
            parameters[key]['general']['RISK_PREMIUM_PERCENTAGE'] = risk_premium_percentage

        fs.parameters = parameters
        fs.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            update_risk_premium_on_channeling_loan_config, migrations.RunPython.noop
        ),
    ]
