# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-03-13 07:53
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.face_recognition.constants import FaceMatchingCheckConst
from juloserver.julo.constants import FeatureNameConst


def insert_new_feature_setting_face_matching_check(apps, schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.FACE_MATCHING_CHECK,
        is_active=False,
        description='Feature Settings for Face Matching Check',
        category='face recognition',
        parameters={
            FaceMatchingCheckConst.FeatureSetting.parameter_liveness_x_ktp: {
                "is_active": True,
                "logical_operator": ">=",
                "similarity_threshold": 99.0,
            },
            FaceMatchingCheckConst.FeatureSetting.parameter_liveness_x_selfie: {
                "is_active": True,
                "logical_operator": ">=",
                "similarity_threshold": 99.0,
            },
        },
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(
            insert_new_feature_setting_face_matching_check, migrations.RunPython.noop
        )
    ]
