# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-03-15 07:21
from __future__ import unicode_literals

from django.db import migrations
from juloserver.minisquad.constants import FeatureNameConst, AiRudder
from juloserver.julo.models import FeatureSetting


def add_dialer_autorecon_discrepancies_feature_setting(apps, _schema_editor):
    existing_feature_setting = FeatureSetting.objects.filter(
        feature_name='DIALER_DISCREPANCIES_THRESHOLD')
    feature_setting_data = {
        'feature_name': FeatureNameConst.DIALER_DISCREPANCIES,
        'is_active': True,
        'parameters': {
            'discrepancies_threshold': 0.1,
            'autorecon_method': AiRudder.SYNCHRONOUS_METHOD, # or asynchronous
            'autorecon': True,
        },
        'category': 'dialer',
        'description': 'Setting for adjusting discrepancies threshold'
    }
    if existing_feature_setting.exists():
        existing_feature_setting.update(**feature_setting_data)
        return
    FeatureSetting.objects.create(**feature_setting_data)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_dialer_autorecon_discrepancies_feature_setting, migrations.RunPython.noop),
    ]

