# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-03-25 04:13
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst


def add_feature_setting_cashback_dpd_pay_off(apps, _schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.CASHBACK_DPD_PAY_OFF,
        is_active=False,
        parameters={'days_past_due': 7},
        category='cashback task setting',
        description='Decides if the daily cashback task is run or not',
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(add_feature_setting_cashback_dpd_pay_off, migrations.RunPython.noop),
    ]
