# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-03-25 07:59
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst


def create_fs_for_holdout_users_from_bss_channeling(apps, _schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.HOLDOUT_USERS_FROM_BSS_CHANNELING,
        is_active=False,
        category="bss_channeling",
        description="exclude holdout users from BSS Channeling"
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_fs_for_holdout_users_from_bss_channeling, migrations.RunPython.noop),
    ]
