# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-03-29 08:33
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.product_lines import ProductLineCodes


def update_alert_for_stuck_loan(apps, _schema_editor):
    fs = FeatureSetting.objects.filter(feature_name=FeatureNameConst.ALERT_FOR_STUCK_LOAN).first()
    if fs:
        fs.parameters.update(
            product_line_applied=[ProductLineCodes.J1, ProductLineCodes.TURBO]
        )
        fs.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(update_alert_for_stuck_loan, migrations.RunPython.noop),
    ]
