# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-03-26 12:26
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst


def execute(apps, schema_editor):
    is_exists = FeatureSetting.objects.filter(feature_name=FeatureNameConst.PARTNER_ACCOUNTS_FORCE_LOGOUT).exists()
    if not is_exists:
        FeatureSetting.objects.create(
            feature_name=FeatureNameConst.PARTNER_ACCOUNTS_FORCE_LOGOUT,
            description='List of partners not allowed to reapply',
            category='application',
            is_active=False,
            parameters=[
                'Dagangan',
                'efishery jawara',
                'laku6',
                'fishlog',
                'icare',
                'sakalaguna',
                'BukuWarung',
                'aturduit',
                'efishery kabayan lite',
                'axiata',
                'gaji gesa',
                'doku',
                'efishery inti plasma',
                'efishery kabayan reguler',
                'koperasi tunas 45',
                'pasarnow',
                'grabfood',
                'efishery',
                'Rabando',
                'agrari',
                'koperasi tunas',
                'dummyserbada',
                'pede',
                'grab',
                'gojektsel',
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(execute, migrations.RunPython.noop),
    ]
