# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-04-04 09:27
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def grab_admin_fee_tiering_feature_setting(apps, _schema_editor):
    data_to_be_created = {
        'feature_name': FeatureNameConst.GRAB_ADMIN_FEE_TIERING,
        'is_active': False,
        'parameters': {
            "no_of_tiers": "3",
            "tiers": [
                {
                    "admin_fee": 35000,
                    "range": [
                        0,
                        1000000
                    ]
                },
                {
                    "admin_fee": 55000,
                    "range": [
                        1000001,
                        1500000
                    ]
                },
                {
                    "admin_fee": 75000,
                    "range": [
                        1500001,
                        100000000
                    ]
                }
            ]
        },
        'category': 'Grab_admin_fee_tiering',
        'description': 'This configuration is to set grab admin fee tiering'
    }
    FeatureSetting.objects.get_or_create(**data_to_be_created)


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunPython(grab_admin_fee_tiering_feature_setting, migrations.RunPython.noop),
    ]
