# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-05-06 09:35
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def run(apps, _schema_editor):
    if not FeatureSetting.objects.filter(feature_name=FeatureNameConst.TELCO_SCORE).exists():
        FeatureSetting.objects.create(
            feature_name=FeatureNameConst.TELCO_SCORE,
            parameters={
                "application_id": [1, 3, 5, 7, 9],
                "provider": {
                    "telkomsel": {
                        "is_active": True,
                        "swap_in_threshold": 750,
                        "swap_out_threshold": 550,
                        "prefixes": [
                            '0811',
                            '0812',
                            '0813',
                            '0821',
                            '0822',
                            '0823',
                            '0851',
                            '0852',
                            '0853',
                        ],
                    },
                    "indosat": {
                        "is_active": True,
                        "swap_in_threshold": 750,
                        "swap_out_threshold": 550,
                        "prefixes": [
                            '0814',
                            '0815',
                            '0816',
                            '0855',
                            '0856',
                            '0857',
                            '0858',
                        ],
                    },
                    "xl": {
                        "is_active": True,
                        "swap_in_threshold": 750,
                        "swap_out_threshold": 550,
                        "prefixes": [
                            '0877',
                            '0878',
                            '0817',
                            '0818',
                            '0819',
                        ],
                    },
                },
            },
            is_active=True,
            category='scoring',
            description="feature setting for Telco Score",
        )


class Migration(migrations.Migration):

    dependencies = []

    operations = [migrations.RunPython(run, migrations.RunPython.noop)]
