# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-12-19 04:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def add_grab_emergency_contact_feature_settings(apps, schema_editor):
    FeatureSetting.objects.update_or_create(
        feature_name=FeatureNameConst.GRAB_EMERGENCY_CONTACT,
        parameters={
            "opt_out_in_hour": 48,
            "sms_cron_send_time": 19
        },
        is_active=True,
        category="application",
        description="Grab Emergency Contact Consent Flow",
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            add_grab_emergency_contact_feature_settings,
            migrations.RunPython.noop
        ),
    ]
