# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-05-02 11:07
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def partnership_dana_monthly_income(apps, schema_editor):
    FeatureSetting.objects.get_or_create(
        is_active=True,
        feature_name=FeatureNameConst.DANA_MONTHLY_INCOME,
        category="dana",
        parameters={
            "belowrp1.000.000": 1000000,
            "dibawahrp1.000.000": 1000000,
            "rp1.000.000–rp2.000.000": 1500000,
            "rp2.000.000–rp3.000.000": 2500000,
            "rp3.000.000–rp5.000.000": 4000000,
            "rp5.000.000–rp10.000.000": 7500000,
            "rp10.000.000–rp20.000.000": 15000000,
            "rp20.000.000andabove": 20000000,
            "rp20.000.000dankeatas": 20000000,
        },
        description="Mapping dana income range to monthly income",
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [migrations.RunPython(partnership_dana_monthly_income, migrations.RunPython.noop)]
