# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-05-01 11:56
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst


def change_faspay_prohibit_va_payment_feature_name(apps, schema_editor):
    existing_feature = FeatureSetting.objects.filter(
        feature_name=FeatureNameConst.FASPAY_PROHIBIT_VA_PAYMENT
    )

    if existing_feature.exists():
        existing_feature = existing_feature.first()
        existing_feature.feature_name = FeatureNameConst.REPAYMENT_PROHIBIT_VA_PAYMENT
        existing_feature.description = "a list of payment methods that are prohibited for repayment"
        existing_feature.save()


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(
            change_faspay_prohibit_va_payment_feature_name, migrations.RunPython.noop
        ),
    ]
