# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-05-15 09:50
from __future__ import unicode_literals

from django.db import migrations
from juloserver.application_flow.models import (
    ApplicationTag,
    ApplicationPathTagStatus,
)


def execute(apps, schema_editor):
    tag_statuses = [
        [1, 'success'],
    ]
    tags = ['is_offline_activation', 'is_offline_activation_low_pgood']

    for tag in tags:
        if not ApplicationTag.objects.filter(application_tag=tag).exists():
            ApplicationTag.objects.create(application_tag=tag, is_active=True)

            for tag_status in tag_statuses:
                ApplicationPathTagStatus.objects.create(
                    application_tag=tag, status=tag_status[0], definition=tag_status[1]
                )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(execute, migrations.RunPython.noop),
    ]
