# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-05-11 13:24
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def add_feature_product_lock_bottom_sheet(apps, schema_editor):
    fs = FeatureSetting.objects.get_or_none(
        feature_name=FeatureNameConst.PRODUCT_LOCK_IN_APP_BOTTOM_SHEET,
    )
    if not fs:
        parameters = {
            "004_A": {
                "title": "Kamu Belum Bisa Transaksi",
                "body": "Kamu terdeteksi telat membayar tagihan di JULO dan aplikasi lainnya. \n"
                        "Lunasi tagihan di JULO dan aplikasi lainnya dan tunggu maks. "
                        "30 hari agar bisa mulai transaksi lagi, ya!",
                "button": "Mengerti",
            },
            "004_B": {
                "title": "Kamu Belum Bisa Transaksi",
                "body": "Kamu terdeteksi telat membayar pinjaman di aplikasi lain. \n"
                        "Kamu bisa mulai transaksi lagi di JULO maks. "
                        "14 hari setelah kamu lunasi tagihanmu yang lainnya, ya!",
                "button": "Mengerti",
            },
            "004_C": {
                "title": "Kamu Belum Bisa Transaksi",
                "body": "Kamu terdeteksi telat membayar tagihan di JULO dan aplikasi lainnya. \n"
                        "Kamu bisa mulai transaksi lagi di JULO maks. "
                        "30 hari setelah kamu lunasi tagihan di JULO dan aplikasi lainnya, ya!",
                "button": "Mengerti",
            },
            "004_D": {
                "title": "Kamu Belum Bisa Transaksi",
                "body": "Berdasarkan hasil tim analis JULO, kamu tidak dapat transaksi untuk "
                        "sementara waktu demi alasan keamanan. \n "
                        "Tapi tenang, JULO selalu melakukan peninjauan terhadap akunmu "
                        "secara berkala. Jika kamu masih punya tagihan baik di JULO atau "
                        "aplikasi lain, pastikan kamu selalu bayar tepat waktu, ya!",
                "button": "Mengerti"
            },
            "004_E": {
                "title": "Kamu Belum Bisa Transaksi Sekarang",
                "body": "Saat ini, akun kamu bisa transaksi setiap tanggal 15 hingga 21 di "
                        "setiap bulannya. \nJangan sampai terlewat dan pastikan kamu selalu bayar "
                        "tagihan tepat waktu untuk menjaga riwayat pembayaran yang baik, ya!",
                "button": "Mengerti"
            }
        }
        FeatureSetting.objects.create(
            feature_name=FeatureNameConst.PRODUCT_LOCK_IN_APP_BOTTOM_SHEET,
            category="loan",
            is_active=True,
            parameters=parameters
        )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_feature_product_lock_bottom_sheet, migrations.RunPython.noop),
    ]
