# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-05-13 03:16
from __future__ import unicode_literals

from django.db import migrations

from juloserver.early_limit_release.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def update_fs_early_limit_release_for_delay_call(apps, schema_editor):
    fs = FeatureSetting.objects.filter(
        feature_name=FeatureNameConst.EARLY_LIMIT_RELEASE,
    ).first()
    if fs:
        parameters = fs.parameters
        parameters['delay_seconds_call_from_repayment'] = 300
        fs.parameters = parameters
        fs.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            update_fs_early_limit_release_for_delay_call, migrations.RunPython.noop
        ),
    ]

