# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-05-12 15:37
from __future__ import unicode_literals
from django.db import migrations

from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst
from juloserver.credgenics.constants.feature_setting import (
    Parameter,
)


def add_feature_setting_for_credgenics_integration(apps, schema_editor):
    FeatureSetting.objects.get_or_create(
        feature_name=FeatureNameConst.CREDGENICS_INTEGRATION,
        category="credgenics",
        description="Credgenics Integration feature settings",
        is_active=False,
        parameters={
            Parameter.SEGMENTATION_REGEX: "",
            Parameter.N_PER_BATCH: 5000,
            Parameter.OSS_TTL_SECONDS: 86400,  # 24 hours
        },
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(
            add_feature_setting_for_credgenics_integration, migrations.RunPython.noop
        )
    ]
