# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-05-27 06:30
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting
from juloserver.loyalty.constants import FeatureNameConst


def init_feature_setting_for_loyalty(app, __schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.POINT_EXPIRE_REMINDER_CONFIGURATION,
        is_active=True,
        parameters={
            "reminder_days": 30,
            "point_usage_info": "Potongan berlaku di taginan cicilan terakhir sesuai jumlah "
                                "saldo cashback kamu",
            "point_expiry_info": "{} Poin kamu akan kedaluwersa pada {}"
        },
        category='loyalty',
        description='Feature Setting to configuration point reminder'
    )
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.POINT_CONVERT,
        is_active=True,
        parameters={
            "from_poit_to_rupiah": 1,
        },
        category='loyalty',
        description='Feature Setting to configuration point convert'
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            init_feature_setting_for_loyalty, migrations.RunPython.noop
        ),
    ]
