# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-05-25 17:55
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst


def add_feature_setting_for_autodebet_idfy(apps, schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.AUTODEBET_IDFY_CONFIG_ID,
        is_active=True,
        parameters={'config_id': '51d1b15f-71bf-4df2-a469-0fb2e1c82e12'},
        description='Config ID for IDfy Autodebet',
        category='IDFy',
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(
            add_feature_setting_for_autodebet_idfy,
            migrations.RunPython.noop,
        )
    ]
