# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-05-18 02:56
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def add_allowed_transaction_method_for_invalid_name_bank_feature_setting(apps, _schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.FAILED_BANK_NAME_VALIDATION_DURING_UNDERWRITING,
        parameters={"allowed_transaction_methods": ["1"]},
        is_active=False,
        category="NameBankValidation",
        description="Define what transaction method allowed for user that failed bank account validation during underwriting",
    )


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunPython(
            add_allowed_transaction_method_for_invalid_name_bank_feature_setting,
            migrations.RunPython.noop,
        ),
    ]
