# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-05-21 05:23
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst


def add_feature_setting_for_autodebit_idfy(apps, schema_editor):
    parameters = {
        "instructions": [
            "Kamera dan mikrofon HP kamu berfungsi dengan baik",
            "Kamu berada di area yang tidak terlalu berisik",
            "Informasi yang kamu berikan akurat, sesuai dengan data yang telah kamu kirim sebelumnya",
        ],
        "info": {
            "title": "Jam Operasional Video Call (WIB)",
            "message": "Senin-Minggu/Libur Nasional: 08:00-20:00",
        },
    }
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.AUTODEBIT_IDFY_INSTRUCTION_PAGE,
        is_active=True,
        description='Autodebit IDFy',
        category='IDFy',
        parameters=parameters,
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(
            add_feature_setting_for_autodebit_idfy,
            migrations.RunPython.noop,
        )
    ]
