# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-05-31 07:46
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting
from juloserver.customer_module.constants import AccountDeletionFeatureName
from juloserver.julo.product_lines import ProductLineCodes


def add_supported_product_line_deletion_feature_setting(apps, _schema_editor):
    FeatureSetting.objects.create(
        feature_name=AccountDeletionFeatureName.SUPPORTED_PRODUCT_LINE_DELETION,
        is_active=True,
        parameters={
            "supported_product_line": [
                None,
                ProductLineCodes.J1,
                ProductLineCodes.JTURBO,
                ProductLineCodes.MTL1,
                ProductLineCodes.MTL2,
                ProductLineCodes.CTL1,
                ProductLineCodes.CTL2,
                ProductLineCodes.STL1,
                ProductLineCodes.STL2,
                ProductLineCodes.LOC,
            ],
        },
        category='account_deletion',
        description='Feature setting for supported product line account deletion',
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(
            add_supported_product_line_deletion_feature_setting, migrations.RunPython.noop
        ),
    ]
