# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-06-04 03:55
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import Onboarding
from juloserver.julo.constants import OnboardingIdConst

JULO_360_IDS = [OnboardingIdConst.JULO_360_J1_ID, OnboardingIdConst.JULO_360_TURBO_ID]

JULO_360_DESCRIPTIONS = [
    'Julo 360 for J1',
    'Julo 360 for Julo Turbo',
]


def run(apps, _schema_editor):
    for id, description in zip(JULO_360_IDS, JULO_360_DESCRIPTIONS):
        Onboarding.objects.create(id=id, description=description, status=True)


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(run),
    ]
