# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-05-31 09:02
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting
from juloserver.loan.constants import DBRConst


def update_url_feture_setting_for_dbr(apps, _schema_editor):
    dbr_fs = FeatureSetting.objects.filter(
        feature_name=FeatureNameConst.DBR_RATIO_CONFIG,
    ).last()
    url = (
        settings.MISSION_WEB_URL + "/app/update_income/forms/?token=[token]"
        "&transaction_type_code=[transaction_type_code]&self_bank_account=[self_bank_account]"
    )
    dbr_fs.parameters['popup_banner'][DBRConst.ADDITIONAL_INFORMATION][DBRConst.LINK] = url
    dbr_fs.save()


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunPython(update_url_feture_setting_for_dbr, migrations.RunPython.noop),
    ]
