# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-06-06 23:02
from __future__ import unicode_literals

from django.db import migrations


def create_feature_settings_hsfbp_goldfish(apps, schema_editor):
    from juloserver.julo.models import FeatureSetting
    from juloserver.julo.constants import FeatureNameConst

    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.GOLDFISH_BYPASS,
        parameters={"customer_ids": [1, 2, 3, 4, 5, 6]},
        is_active=False,
        description="Configuration For High Score Full Bypass Goldfish",
        category="julo",
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(create_feature_settings_hsfbp_goldfish, migrations.RunPython.noop)
    ]
