# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-06-05 01:51
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import MobileFeatureSetting
from juloserver.julo.constants import MobileFeatureNameConst


def addana_consent_feature_mobile_setting(apps, schema_editor):
    MobileFeatureSetting.objects.create(
        feature_name=MobileFeatureNameConst.DANA_AUTODEBET_CONSENT,
        parameters={
            "alert_content": "Jika kamu mengaktifkan Autodebit pada tanggal yang sama saat jatuh tempo, maka tagihan baru terpotong di periode berikutnya",
            "tnc_content": [
                "Kami akan melakukan penarikan dana sesuai tagihan yang tertera, baik yang tertagih atau yang terlambat secara otomatis setiap bulan.",
                "Bila terjadi masalah, hubungi Customer Service JULO di <b>021 5091 9034</b> atau <b>021 5091 9035</b>",
            ],
            "tnc_redirect_url": "https://www.julo.co.id/terms-and-conditions",
        },
        is_active=True,
    )


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunPython(addana_consent_feature_mobile_setting),
    ]
