# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-06-18 15:25
from __future__ import unicode_literals

from django.db import migrations

from juloserver.grab.constants import GrabFeatureNameConst
from juloserver.grab.models import GrabFeatureSetting


def add_feature_setting_for_populating_airudder(app, _schema_editor):
    GrabFeatureSetting.objects.get_or_create(
        is_active=False,
        category="grab collection",
        description='grab airudder populating config',
        feature_name=GrabFeatureNameConst.GRAB_POPULATING_CONFIG,
        parameters=[
            {
                "rank": 1,
                "score": [{"min": 200, "max": 400}],
                "dpd": [{"min": 7, "max": 11}, {"min": 30, "max": 40}, {"min": 50, "max": 60}],
                "category": ["4W"],
            },
            {
                "rank": 2,
                "score": [{"min": 400, "max": 800}],
                "dpd": [{"min": 7, "max": 11}, {"min": 31, "max": 40}, {"min": 50, "max": 60}],
                "category": ["4W"],
            },
        ],
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(
            add_feature_setting_for_populating_airudder, migrations.RunPython.noop
        ),
    ]
