# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-06-11 06:30
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting
from juloserver.credgenics.constants.feature_setting import (
    Parameter,
    CommsType,
)


def update_credgenics_feature_settings_comms_exclusion_pds(apps, _schema_editor):
    feature_setting = FeatureSetting.objects.filter(
        feature_name=FeatureNameConst.CREDGENICS_INTEGRATION,
    ).last()
    if feature_setting:
        fs_params = feature_setting.parameters
        fs_params[Parameter.EXCLUDE_COMMS][CommsType.PDS] = False
        feature_setting.parameters = fs_params
        feature_setting.save(update_fields=['parameters'])


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(
            update_credgenics_feature_settings_comms_exclusion_pds, migrations.RunPython.noop
        )
    ]
