# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-06-17 12:08
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting
from juloserver.antifraud.constant.feature_setting import BinaryCheck, Holdout


def create_antifraud_binary_check_fs(apps, _schema_editor):
    FeatureSetting.objects.get_or_create(
        feature_name=FeatureNameConst.ANTIFRAUD_BINARY_CHECK,
        category="antifraud",
        description="Anti Fraud Binary Check feature settings",
        is_active=False,
        parameters={
            BinaryCheck.Parameter.HOLDOUT: {
                BinaryCheck.Parameter.Holdout.TYPE: Holdout.Type.INACTIVE,
                BinaryCheck.Parameter.Holdout.REGEX: "",
                BinaryCheck.Parameter.Holdout.PERCENTAGE: 100,
            },
        },
    )

    # holdout feature settings
    FeatureSetting.objects.get_or_create(
        feature_name='abc_blacklisted_company',
        category="antifraud",
        description="Feature Flag for antifraud binary check blacklisted company",
        is_active=False,
        parameters={
            BinaryCheck.Parameter.HOLDOUT: {
                BinaryCheck.Parameter.Holdout.TYPE: Holdout.Type.INACTIVE,
                BinaryCheck.Parameter.Holdout.REGEX: "",
                BinaryCheck.Parameter.Holdout.PERCENTAGE: 100,
            },
        },
    )

    FeatureSetting.objects.get_or_create(
        feature_name='abc_blacklisted_postal_code',
        category="antifraud",
        description="Feature Flag for antifraud binary check blacklisted postal code",
        is_active=False,
        parameters={
            BinaryCheck.Parameter.HOLDOUT: {
                BinaryCheck.Parameter.Holdout.TYPE: Holdout.Type.INACTIVE,
                BinaryCheck.Parameter.Holdout.REGEX: "",
                BinaryCheck.Parameter.Holdout.PERCENTAGE: 100,
            },
        },
    )

    FeatureSetting.objects.get_or_create(
        feature_name='abc_blacklisted_geohash5',
        category="antifraud",
        description="Feature Flag for antifraud binary check blacklisted geohash5",
        is_active=False,
        parameters={
            BinaryCheck.Parameter.HOLDOUT: {
                BinaryCheck.Parameter.Holdout.TYPE: Holdout.Type.INACTIVE,
                BinaryCheck.Parameter.Holdout.REGEX: "",
                BinaryCheck.Parameter.Holdout.PERCENTAGE: 100,
            },
        },
    )

    FeatureSetting.objects.get_or_create(
        feature_name='abc_blacklisted_asn',
        category="antifraud",
        description="Feature Flag for antifraud binary check blacklisted asn",
        is_active=False,
        parameters={
            BinaryCheck.Parameter.HOLDOUT: {
                BinaryCheck.Parameter.Holdout.TYPE: Holdout.Type.INACTIVE,
                BinaryCheck.Parameter.Holdout.REGEX: "",
                BinaryCheck.Parameter.Holdout.PERCENTAGE: 100,
            },
        },
    )

    FeatureSetting.objects.get_or_create(
        feature_name='abc_play_integrity_emulator',
        category="antifraud",
        description="Feature Flag for antifraud binary check play integrity emulator",
        is_active=False,
        parameters={
            BinaryCheck.Parameter.HOLDOUT: {
                BinaryCheck.Parameter.Holdout.TYPE: Holdout.Type.INACTIVE,
                BinaryCheck.Parameter.Holdout.REGEX: "",
                BinaryCheck.Parameter.Holdout.PERCENTAGE: 100,
            },
        },
    )

    FeatureSetting.objects.get_or_create(
        feature_name='abc_suspicious_apps',
        category="antifraud",
        description="Feature Flag for antifraud binary check suspicious apps",
        is_active=False,
        parameters={
            BinaryCheck.Parameter.HOLDOUT: {
                BinaryCheck.Parameter.Holdout.TYPE: Holdout.Type.INACTIVE,
                BinaryCheck.Parameter.Holdout.REGEX: "",
                BinaryCheck.Parameter.Holdout.PERCENTAGE: 100,
            },
        },
    )

    FeatureSetting.objects.get_or_create(
        feature_name='abc_close_kin_contact',
        category="antifraud",
        description="Feature Flag for antifraud binary check close kin contact",
        is_active=False,
        parameters={
            BinaryCheck.Parameter.HOLDOUT: {
                BinaryCheck.Parameter.Holdout.TYPE: Holdout.Type.INACTIVE,
                BinaryCheck.Parameter.Holdout.REGEX: "",
                BinaryCheck.Parameter.Holdout.PERCENTAGE: 100,
            },
        },
    )

    FeatureSetting.objects.get_or_create(
        feature_name='abc_gd_device_sharing_block',
        category="antifraud",
        description="Feature Flag for antifraud binary check gd device sharing block",
        is_active=False,
        parameters={
            BinaryCheck.Parameter.HOLDOUT: {
                BinaryCheck.Parameter.Holdout.TYPE: Holdout.Type.INACTIVE,
                BinaryCheck.Parameter.Holdout.REGEX: "",
                BinaryCheck.Parameter.Holdout.PERCENTAGE: 100,
            },
        },
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [migrations.RunPython(create_antifraud_binary_check_fs, migrations.RunPython.noop)]
