# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-07-03 08:03
from __future__ import unicode_literals

from django.db import migrations
from juloserver.streamlined_communication.models import NeoBannerCard
from juloserver.julo.models import WorkflowStatusPath, Workflow
from juloserver.julo.constants import WorkflowConst


def retroload_neobanner_j1(_apps, _schema_editor):
    neo_banner_card = NeoBannerCard.objects.get(statuses='[120]')
    neo_banner_card.statuses = '[120, 106_RESUBMIT]'
    neo_banner_card.save()


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(retroload_neobanner_j1, migrations.RunPython.noop),
    ]
