# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-06-27 15:21
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import WorkflowConst
from juloserver.julo.models import Workflow, WorkflowStatusPath


def update_julo_starter_config(apps, _schema_editor):
    julo_starter_config = FeatureSetting.objects.filter(feature_name='julo_starter_config').last()
    julo_starter_config.update_safely(parameters={"salary": 2500000, "dynamic_check": True})


def retroload_workflow_status_path(_apps, _schema_editor):
    workflow = Workflow.objects.filter(name=WorkflowConst.JULO_STARTER).last()
    if not WorkflowStatusPath.objects.filter(
        workflow=workflow, status_previous=109, status_next=135
    ).exists():
        WorkflowStatusPath.objects.create(
            workflow=workflow, status_previous=109, status_next=135, type="graveyard"
        )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(update_julo_starter_config, migrations.RunPython.noop),
        migrations.RunPython(retroload_workflow_status_path, migrations.RunPython.noop),
    ]
