# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-07-01 12:38
from __future__ import unicode_literals

from django.db import migrations

from juloserver.account.constants import AccountLockReason
from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst


def add_feature_product_lock_bottom_sheet(apps, schema_editor):
    fs = FeatureSetting.objects.get_or_none(
        feature_name=FeatureNameConst.PRODUCT_LOCK_IN_APP_BOTTOM_SHEET,
    )

    if not fs:
        return

    dpd_90 = {
        "body": "Sebelumnya terima kasih sudah lunasi tagihanmu, ya. Tapi, melihat riwayat pembayaran tagihanmu yang kurang baik, kamu tidak bisa bertransaksi lagi dengan alasan keamanan.",
        "title": "Maaf, Kamu Tidak Bisa Transaksi",
        "button": "Mengerti",
    }
    fs.parameters[AccountLockReason.INVALID_ACCOUNT_STATUS_A] = dpd_90
    fs.save()


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(add_feature_product_lock_bottom_sheet, migrations.RunPython.noop),
    ]
