# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-06-27 11:55
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def update_url_feture_setting_for_dbr(apps, _schema_editor):
    dbr_fs = FeatureSetting.objects.filter(
        feature_name=FeatureNameConst.DBR_RATIO_CONFIG,
    ).last()
    dbr_fs.parameters['blacklist'] = {"is_active": False}
    dbr_fs.save()


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunPython(update_url_feture_setting_for_dbr, migrations.RunPython.noop),
    ]
