# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-07-01 03:12
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting


def dukcapil_fr_threshold(apps, _schema_editor):
    parameters = {
        'turbo': {
            'is_active': True,
            'very_high': 9.5,
            'high': 8,
            'medium': 7,
        }
    }

    FeatureSetting.objects.create(
        feature_name='dukcapil_fr_threshold',
        parameters=parameters,
        is_active=True,
        description='dukcapil face recognition',
        category='underwriting',
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(dukcapil_fr_threshold, migrations.RunPython.noop),
    ]
