# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-07-03 04:23
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def create_feature_setting_for_pusdafil_lender_repayment_gdrive_process(apps, _schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.PUSDAFIL_LENDER_REPAYMENT_GDRIVE_PROCESS,
        is_active=True,
        parameters={'folder_id': '1qgmc4d9svLxTKInYojHcVNrLRAtEdQSB'},
        category='followthemoney',
        description='settings for pusdafil lender repayment detail process from google drive',
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(
            create_feature_setting_for_pusdafil_lender_repayment_gdrive_process,
            migrations.RunPython.noop,
        )
    ]
