# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-07-12 08:18
from __future__ import unicode_literals

from django.db import migrations
from juloserver.application_flow.models import ApplicationPathTagStatus

PATH_TAG_NAME = 'is_agent_assisted_submission'


def run(apps, _schema_editor):
    if not ApplicationPathTagStatus.objects.filter(
        application_tag=PATH_TAG_NAME,
    ).exists():
        ApplicationPathTagStatus.objects.create(
            application_tag=PATH_TAG_NAME, status=1, definition='success'
        )


class Migration(migrations.Migration):

    dependencies = []

    operations = [migrations.RunPython(run, migrations.RunPython.noop)]
