# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-07-17 06:25
from __future__ import unicode_literals

from django.db import migrations


def modify_dukcapil_threshold_j1(apps, schema_editor):
    from juloserver.julo.models import FeatureSetting

    setting = FeatureSetting.objects.filter(
        feature_name='dukcapil_fr_threshold',
    ).last()
    param = setting.parameters
    param["j1"] = {"is_active": True, "very_high": 9.5, "high": 5}
    setting.parameters = param
    setting.save()


class Migration(migrations.Migration):

    dependencies = []

    operations = [migrations.RunPython(modify_dukcapil_threshold_j1, migrations.RunPython.noop)]
