# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-07-23 04:08
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import Group, User

from juloserver.application_flow.constants import PartnerNameConstant
from juloserver.julo.models import Partner
from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst


def create_ioh_myim3_partner(apps, schema_editor):
    group = Group.objects.get(name="julo_partners")

    user = User.objects.create(
        username=PartnerNameConstant.IOH_MYIM3,
        email='albert.wijaya@ioh.co.id',
    )
    user.groups.add(group)

    Partner.objects.create(
        user=user,
        poc_email='albert.wijaya@ioh.co.id',
        poc_phone='+628111111111',
        poc_name='albert wijaya',
        name=PartnerNameConstant.IOH_MYIM3,
        email='albert.wijaya@ioh.co.id',
        phone='628111111111',
        type='referrer',
        company_name='IOH MyIM3',
        company_address='Jl. Kebon Sirih No. 51-53, Menteng, Jakarta Pusat, Jakarta',
        business_type='Fintech Aggregator',
        is_active=True,
    )

    feature_settings = FeatureSetting.objects.filter(
        feature_name=FeatureNameConst.LEAD_GEN_PARTNER_CREDIT_SCORE_GENERATION
    ).first()

    partners = feature_settings.parameters['partners']
    if not PartnerNameConstant.IOH_MYIM3 in partners:
        partners.append(PartnerNameConstant.IOH_MYIM3)
        feature_settings.parameters['partners'] = partners
        feature_settings.save()


class Migration(migrations.Migration):
    dependencies = []

    operations = [migrations.RunPython(create_ioh_myim3_partner, migrations.RunPython.noop)]
