# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-01-26 04:22
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.constants import MobileFeatureNameConst
from juloserver.julo.models import MobileFeatureSetting

def update_clik_integration_parameters(apps, schema_editor):
    mfs = MobileFeatureSetting.objects.filter(
        feature_name=MobileFeatureNameConst.CLIK_INTEGRATION,
    ).first()
    data = {'shadow_score': {'is_active': True}}
    if mfs:
        if 'shadow_score' not in mfs.parameters:
            mfs.parameters.update(data)

        mfs.save()

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(update_clik_integration_parameters, migrations.RunPython.noop),
    ]
