# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-07-17 12:25
from __future__ import unicode_literals

from django.db import migrations
from juloserver.autodebet.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def add_dana_reinquiry_feature(apps, schema_editor):
    reinquiry_feature = FeatureSetting.objects.get_or_none(
        feature_name=FeatureNameConst.AUTODEBET_RE_INQUIRY,
    )
    if not reinquiry_feature:
        reinquiry_feature = FeatureSetting.objects.create(
            feature_name=FeatureNameConst.AUTODEBET_RE_INQUIRY,
            is_active=False,
            category='repayment',
            description='autodebet_re_inquiry',
        )
    # ADD NEW DANA
    if not reinquiry_feature.parameters:
        reinquiry_feature.parameters = {}
    reinquiry_feature.parameters['DANA'] = {'minutes': 120}
    reinquiry_feature.save()


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(add_dana_reinquiry_feature, migrations.RunPython.noop),
    ]
