# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-06-18 15:25
from __future__ import unicode_literals

from django.db import migrations

from juloserver.grab.constants import GrabFeatureNameConst
from juloserver.grab.models import GrabFeatureSetting


def add_feature_setting_for_flow_blocker(app, _schema_editor):
    GrabFeatureSetting.objects.get_or_create(
        is_active=True,
        category="grab collection",
        description='grab flow blocker feature setting for CRS',
        feature_name=GrabFeatureNameConst.GRAB_CRS_FLOW_BLOCKER,
        parameters={
            "failed_crs": 24,
        },
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(add_feature_setting_for_flow_blocker, migrations.RunPython.noop),
    ]
