# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-07-15 06:57
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.minisquad.constants import FeatureNameConst


def featue_setting_for_cashback_new_scheme_adjustment(apps, schema_editor):
    """ "
    for cashback_counter_map, 'key' here as cashback counter
    and 'value' for cashback percentage
    """
    parameters = {'due_date': -3, 'cashback_counter_map': {1: 1, 2: 1, 3: 2, 4: 2, 5: 4}}
    filter_dict = dict(
        feature_name=FeatureNameConst.CASHBACK_NEW_SCHEME,
        is_active=True,
        category='account',
        description='cashback new scheme',
    )
    feature_setting = FeatureSetting.objects.filter(**filter_dict)
    if feature_setting:
        feature_setting.update(parameters=parameters)
    else:
        filter_dict.update(parameters=parameters)
        FeatureSetting.objects.create(**filter_dict)


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(
            featue_setting_for_cashback_new_scheme_adjustment, migrations.RunPython.noop
        )
    ]
