# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-08-01 10:00
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def add_feature_setting_sales_ops_revamp(apps, schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.SALES_OPS_REVAMP,
        is_active=False,
        parameters={
            "lineup_non_rpc_delay_day": 1,
            "lineup_non_rpc_final_delay_day": 1,
            "lineup_rpc_delay_day": 7,
            "lineup_delay_paid_collection_call_day": 7,
            "lineup_disbursement_restriction_call_day": 14,
            "lineup_payment_restriction_call_day": 3,
            "lineup_max_used_limit_percentage": 1,
            "lineup_min_available_days": 2,
            "lineup_min_available_limit": 300000,
            "lineup_refresh_day_of_the_month": 1,
            "max_call_per_user_per_month": 6,
            "lineup_non_rpc_delay_attempt_count": 7,
        },
        category='sales_ops',
        description='init fs for sales ops revamp'
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            add_feature_setting_sales_ops_revamp, migrations.RunPython.noop
        )
    ]
