# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-08-05 07:14
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst


def add_cde_fs(apps, _schema_editor):
    parameters = {}

    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.CREDIT_DECISION_ENGINE_CDE,
        parameters=parameters,
        is_active=False,
        description='Feature Setting for CDE',
        category='CDE',
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_cde_fs, migrations.RunPython.noop),
    ]
