# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-07-29 01:22
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.antifraud.constant.feature_setting import BinaryCheck, Holdout


def create_feature_settings_antifraud_telco_maid(apps, _schema_editor):
    feature_setting = FeatureSetting.objects.filter(
        feature_name='abc_telco_maid_location'
    )

    if not feature_setting.exists():
        FeatureSetting.objects.create(
            feature_name='abc_telco_maid_location',
            is_active=False,
            category="antifraud",
            description="Feature Flag for antifraud binary check telco maid location",
            parameters={
                BinaryCheck.Parameter.HOLDOUT: {
                    BinaryCheck.Parameter.Holdout.TYPE: Holdout.Type.INACTIVE,
                    BinaryCheck.Parameter.Holdout.REGEX: "",
                    BinaryCheck.Parameter.Holdout.PERCENTAGE: 100,
                },
            },
        )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(create_feature_settings_antifraud_telco_maid, migrations.RunPython.noop)
    ]
