# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-07-31 07:58
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.julo_financing.constants import JFinancingFeatureNameConst


def add_allowed_tenors_financing_product_feature_setting(apps, schema_editor):
    fs = FeatureSetting.objects.filter(
        feature_name=JFinancingFeatureNameConst.JULO_FINANCING_PRODUCT_CONFIGURATION
    ).first()
    if fs:
        allowed_durations = {'is_active': False, 'durations': [6]}
        fs.parameters['allowed_durations'] = allowed_durations
        fs.save()


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(add_allowed_tenors_financing_product_feature_setting),
    ]
