# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-08-02 05:51
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting
from juloserver.channeling_loan.constants import (
    FeatureNameConst as ChannelingFeatureNameConst,
    ChannelingLoanApprovalFileConst,
)


def add_process_approval_response_time_delay_config(apps, schema_editor):
    channeling_loan_fs = FeatureSetting.objects.filter(
        feature_name=ChannelingFeatureNameConst.CHANNELING_LOAN_CONFIG,
    ).last()
    if not channeling_loan_fs:
        return

    for channeling_type, _ in channeling_loan_fs.parameters.items():
        channeling_loan_fs.parameters[channeling_type]['process_approval_response'] = {
            'DELAY_MINS': ChannelingLoanApprovalFileConst.PROCESS_APPROVAL_FILE_DELAY_MINS
        }

    channeling_loan_fs.save()


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(
            add_process_approval_response_time_delay_config, migrations.RunPython.noop
        )
    ]
