# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-08-16 07:37
from __future__ import unicode_literals

from django.db import migrations
from juloserver.minisquad.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def adding_b6_in_feature_setting_ai_rudder_full_roll_out(apps, schema_editor):
    """
    adding new parameter for b6
    """
    params = (
        FeatureSetting.objects.filter(
            feature_name=FeatureNameConst.AI_RUDDER_FULL_ROLLOUT, is_active=True
        )
        .get()
        .parameters
    )
    params.update(eligible_recovery_bucket_number=[6.1])

    FeatureSetting.objects.filter(feature_name=FeatureNameConst.AI_RUDDER_FULL_ROLLOUT).update(
        parameters=params
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(
            adding_b6_in_feature_setting_ai_rudder_full_roll_out, migrations.RunPython.noop
        )
    ]
