# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-08-09 18:05
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting
from juloserver.minisquad.constants import FeatureNameConst


def add_feature_hour_threshold_airudder(apps, schema_editor):
    fs = FeatureSetting.objects.get_or_none(
        feature_name=FeatureNameConst.AIRUDDER_RECOMMENDED_TIMEOUT,
    )

    if not fs:
        return

    fs.parameters['recommended_hour_threshold'] = 20
    fs.save()


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(add_feature_hour_threshold_airudder, migrations.RunPython.noop),
    ]
