# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-08-14 07:15
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst
from juloserver.disbursement.constants import AyoconnectErrorCodes


def create_ayc_disbursement_config(apps, schema_editor):
    fs = FeatureSetting.objects.get_or_none(feature_name=FeatureNameConst.DISBURSEMENT_AUTO_RETRY)
    if fs:
        fs.parameters['ayc_configuration'] = {
            "error_code_types": {
                "all": AyoconnectErrorCodes.J1_DISBURSE_RETRY_ERROR_CODES,
                "force_switch_to_xfers": AyoconnectErrorCodes.J1_FORCE_SWITCH_TO_XFERS,
                "retry": list(
                    set(AyoconnectErrorCodes.J1_DISBURSE_RETRY_ERROR_CODES)
                    - set(AyoconnectErrorCodes.J1_FORCE_SWITCH_TO_XFERS)
                ),
            },
            "retry_config": {"delay_in_hours": 3, "max_retries": 3},
        }
        fs.save()


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(create_ayc_disbursement_config, migrations.RunPython.noop),
    ]
