# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-12-12 08:28
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.minisquad.constants import (
    FeatureNameConst,
    DialerSystemConst,
)


def add_b6_to_ai_rudder_feature_setting(apps, schema_editor):

    feature_ai_rudder_tasks_config = FeatureSetting.objects.filter(
        feature_name=FeatureNameConst.AI_RUDDER_TASKS_STRATEGY_CONFIG
    ).last()
    if not feature_ai_rudder_tasks_config:
        return

    feature_ai_rudder_tasks_config_params = feature_ai_rudder_tasks_config.parameters
    if not feature_ai_rudder_tasks_config_params:
        return

    b5_config = feature_ai_rudder_tasks_config_params[DialerSystemConst.DIALER_BUCKET_5]
    feature_ai_rudder_tasks_config_params[DialerSystemConst.DIALER_BUCKET_6_1] = b5_config
    feature_ai_rudder_tasks_config.parameters = feature_ai_rudder_tasks_config_params
    feature_ai_rudder_tasks_config.save()


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(add_b6_to_ai_rudder_feature_setting, migrations.RunPython.noop)
    ]
