# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-08-28 08:01
from __future__ import unicode_literals

from django.db import migrations

from juloserver.customer_module.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def create_feature_setting_cx_detokenize(apps, schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.CX_DETOKENIZE,
        is_active=False,
        parameters={},
        description='cx detokenize feature turn on/off',
        category='customer_module',
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(
            create_feature_setting_cx_detokenize,
            migrations.RunPython.noop,
        )
    ]
