# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-08-23 03:46
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.autodebet.constants import FeatureNameConst


def create_feature_setting_autodebet_bca_deactivate_warning(apps, schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.BCA_AUTODEBET_DEACTTIVATE_WARNING,
        parameters={
            "interval_days": 7,
            "title": "Gagal Nonaktifkan Autodebit BCA",
            "content": "Kamu baru saja aktifkan Autodebit BCA kurang dari {{interval_days}} hari yang lalu. Coba lagi mulai tanggal <b>{{date}}</b>, ya!",
        },
        is_active=True,
        category='autodebet',
        description='Autodebet BCA deactivate prohibit feature setting',
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(
            create_feature_setting_autodebet_bca_deactivate_warning, migrations.RunPython.noop
        )
    ]
