# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-08-26 05:47
from __future__ import unicode_literals

from django.db import migrations

from juloserver.autodebet.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def update_gopay_feature_setting(apps, schema_editor):
    gopay_fs = FeatureSetting.objects.filter(feature_name=FeatureNameConst.AUTODEBET_GOPAY).last()
    if not gopay_fs:
        return

    gopay_fs.parameters["retry_schedule"] = {
        "interval": 1,
        "interval_unit": "hour",
        "max_interval": 3,
    }

    gopay_fs.save()


class Migration(migrations.Migration):

    dependencies = []

    operations = [migrations.RunPython(update_gopay_feature_setting, migrations.RunPython.noop)]
