# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-08-23 04:41
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def add_loan_amount_default_fs(apps, schema_editor):
    parameters = {
        "whitelist": {"is_active": False, "customer_ids": []},
        "dbr_loan_amount_default": 2_000_000,
        "min_amount_threshold": 300_000,
    }
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.LOAN_AMOUNT_DEFAULT_CONFIG,
        is_active=False,
        parameters=parameters,
        category="loan",
        description="Config loan amount default for range amount api",
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(add_loan_amount_default_fs, migrations.RunPython.noop),
    ]
