# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-08-21 08:54
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst


def update_omnichannel_feature_setting_parameters(apps, schema_editor):

    fs = FeatureSetting.objects.filter(
        feature_name=FeatureNameConst.OMNICHANNEL_INTEGRATION,
    ).first()
    if not fs:
        return

    fs.parameters['is_full_rollout'] = False
    fs.save(
        update_fields=[
            'parameters',
        ]
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(
            update_omnichannel_feature_setting_parameters,
        ),
    ]
