# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-08-19 09:50
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting
from juloserver.loan.constants import LoanFeatureNameConst, OneClickRepeatConst


def add_feature_setting_one_click_repeat_params(apps, schema_editor):
    fs = FeatureSetting.objects.filter(
        feature_name=LoanFeatureNameConst.ONE_CLICK_REPEAT,
    ).last()
    if not fs:
        return

    fs.parameters['interval_day'] = OneClickRepeatConst.INTERVAL_DAY
    fs.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            add_feature_setting_one_click_repeat_params, migrations.RunPython.noop
        )
    ]
