# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-08-30 02:10
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting
from juloserver.minisquad.constants import FeatureNameConst


def add_feature_setting_collection_detokenize(apps, schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.COLLECTION_DETOKENIZE,
        is_active=False,
        parameters={},
        description='collection detokenize turn on/off',
        category='collection',
    )
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.DIALER_IN_BULK_DETOKENIZED_METHOD,
        is_active=True,
        parameters={'detokenize_row': 100},
        description='If active = True will detokenize with bulk method',
        category='collection',
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(
            add_feature_setting_collection_detokenize,
            migrations.RunPython.noop,
        )
    ]
