# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-08-28 03:55
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import WorkflowStatusPath, Workflow
from juloserver.julo.constants import WorkflowConst


def run(apps, _schema_editor):
    workflow = Workflow.objects.filter(name=WorkflowConst.JULO_ONE).last()
    if (
        workflow
        and not WorkflowStatusPath.objects.filter(
            status_previous=105, status_next=105, workflow=workflow
        ).exists()
    ):
        WorkflowStatusPath.objects.create(
            status_previous=105, status_next=105, type="happy", workflow=workflow
        )


class Migration(migrations.Migration):

    dependencies = []

    operations = [migrations.RunPython(run, migrations.RunPython.noop)]
