# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-08-21 09:18
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst

from juloserver.julo.models import FeatureSetting


def create_feature_settings_whitelist(apps, _schema_editor):
    parameters = {
        "va": [],
    }
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.WHITELIST_VA_BILL_AMOUNT_BCA,
        category="repayment",
        parameters=parameters,
        is_active=True,
        description="whitelist va to show bill amount",
    )


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunPython(create_feature_settings_whitelist, migrations.RunPython.noop)
    ]
