# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-09-02 09:33
from __future__ import unicode_literals

from django.db import migrations


from juloserver.partnership.constants import PartnershipFeatureNameConst
from juloserver.partnership.models import PartnershipFeatureSetting


def add_leadgen_standard_feature_setting_otp_config(apps, _schema_editor):
    PartnershipFeatureSetting.objects.get_or_create(
        is_active=True,
        feature_name=PartnershipFeatureNameConst.LEADGEN_OTP_SETTINGS,
        category="leadgen_standard",
        parameters={
            "email": {
                "otp_max_request": 3,
                "otp_max_validate": 3,
                "otp_resend_time": 60,
                "wait_time_seconds": 300,
                "otp_expired_time": 1440,
            },
            "mobile_phone_1": {
                "otp_max_request": 3,
                "otp_max_validate": 3,
                "otp_resend_time": 60,
                "wait_time_seconds": 300,
                "otp_expired_time": 1440,
            },
        },
        description="FeatureSettings to determine standard leadgen otp settings",
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(
            add_leadgen_standard_feature_setting_otp_config,
            migrations.RunPython.noop,
        ),
    ]
