# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-09-05 09:48
from __future__ import unicode_literals

from django.db import migrations
from juloserver.minisquad.constants import FeatureNameConst, DialerSystemConst
from juloserver.julo.models import FeatureSetting


def create_feature_setting(apps, _schema_editor):
    existing_feature_setting = FeatureSetting.objects.filter(
        feature_name=FeatureNameConst.BUCKET_FIELD_COLLECTION_EXCLUDED
    )
    feature_setting_data = {
        'feature_name': FeatureNameConst.BUCKET_FIELD_COLLECTION_EXCLUDED,
        'is_active': True,
        'parameters': {'buckets': [DialerSystemConst.DIALER_BUCKET_2]},
        'category': 'dialer',
        'description': 'Exclude account ids using data from ANA',
    }
    if existing_feature_setting.exists():
        existing_feature_setting.update(**feature_setting_data)
        return
    FeatureSetting.objects.create(**feature_setting_data)


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(create_feature_setting, migrations.RunPython.noop),
    ]
