# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-09-02 09:02
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting
from juloserver.antifraud.constant.feature_setting import GenericParameter


def insert_antifraud_gd_fs(apps, _schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.ANTIFRAUD_GRAB_DEFENCE,
        category="antifraud",
        description="Anti Fraud Grab Defence feature settings",
        is_active=False,
        parameters={
            GenericParameter.FEATURES: {
                "record_score": False,
            }
        },
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [migrations.RunPython(insert_antifraud_gd_fs, migrations.RunPython.noop)]
