# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-09-09 04:04
from __future__ import unicode_literals
from django.db import migrations
from juloserver.julo.models import SepulsaProduct
from juloserver.payment_point.constants import SepulsaProductCategory, SepulsaProductType


def add_sepulsa_product_list_instant_payment_for_dana(apps, _schema_editor):
    SepulsaProduct.objects.create(
        product_id='1213',
        product_name=SepulsaProductType.E_WALLET_OPEN_PAYMENT,
        product_label=SepulsaProductType.E_WALLET_OPEN_PAYMENT,
        product_desc=SepulsaProductType.E_WALLET_OPEN_PAYMENT,
        category=SepulsaProductCategory.DANA,
        type=SepulsaProductType.E_WALLET_OPEN_PAYMENT,
        is_active=True,
        is_not_blocked=False,
        partner_price=500,
        customer_price=550,
        customer_price_regular=500,
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [migrations.RunPython(
        add_sepulsa_product_list_instant_payment_for_dana, migrations.RunPython.noop)
    ]
