# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-09-09 09:51
from __future__ import unicode_literals

from django.db import migrations
from juloserver.application_flow.models import (
    ApplicationTag,
    ApplicationPathTagStatus,
)


def execute(apps, schema_editor):
    tag = 'is_waitlist'

    ApplicationTag.objects.create(application_tag=tag, is_active=True)
    ApplicationPathTagStatus.objects.create(
        application_tag=tag, status=1, definition='success'
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(execute, migrations.RunPython.noop),
    ]
