# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-09-12 08:04
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting
from juloserver.loan.constants import LoanFeatureNameConst
from juloserver.payment_point.constants import TransactionMethodCode


def add_fs_loan_tenure_recommendation(apps, schema_editor):
    params = {
        'experiment_config': {
            'is_active': False,
            'experiment_customer_id_last_digits': [],
        },
        'general_config': {
            'min_tenure': 4,
            'max_tenure': 10,
            'campaign_tag': "Paling Murah!",
            'transaction_methods': [
                TransactionMethodCode.SELF.code,
            ],
        },
    }

    FeatureSetting.objects.update_or_create(
        feature_name=LoanFeatureNameConst.LOAN_TENURE_RECOMMENDATION,
        defaults={
            'is_active': False,
            'category': 'loan',
            'description': 'Configurations Loan Tenure Recommendation',
            'parameters': params,
        },
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(
            code=add_fs_loan_tenure_recommendation,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
