# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-09-20 07:59
from __future__ import unicode_literals

from django.db import migrations

from juloserver.followthemoney.models import LenderCurrent


def update_pre_fund_flag_for_bni_channeling_lender(apps, schema_editor):
    bni_lender = LenderCurrent.objects.filter(lender_name="bni_channeling").last()
    if not bni_lender:
        return

    bni_lender.is_pre_fund_channeling_flow = True
    bni_lender.save()


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(
            update_pre_fund_flag_for_bni_channeling_lender, migrations.RunPython.noop
        ),
    ]
