# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-09-16 10:19
from __future__ import unicode_literals

from django.db import migrations


from juloserver.partnership.constants import PartnershipFeatureNameConst
from juloserver.partnership.models import PartnershipFeatureSetting


def add_feature_settings_partnership_liveness(apps, schema_editor):
    PartnershipFeatureSetting.objects.get_or_create(
        feature_name=PartnershipFeatureNameConst.LEADGEN_LIVENESS_SETTINGS,
        is_active=False,
        parameters={
            'smile': {
                'score_threshold': 1.0,
                'max_retry': 3,
            },
            'passive': {
                'score_threshold': 0.86,
                'max_retry': 3,
            },
        },
        description='partnership ledgen liveness settings',
        category='partnership',
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(
            add_feature_settings_partnership_liveness,
            migrations.RunPython.noop,
        )
    ]
