# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-09-12 17:52
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst


def update_omnichannel_fs(apps, _schema_editor):

    fs = FeatureSetting.objects.filter(
        feature_name=FeatureNameConst.OMNICHANNEL_INTEGRATION,
    ).last()
    if not fs:
        return

    fs.parameters["full_rollout_channels"] = []

    fs.save(update_fields=["parameters"])


class Migration(migrations.Migration):

    dependencies = []

    operations = [migrations.RunPython(update_omnichannel_fs, migrations.RunPython.noop)]
