# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-09-23 03:33
from __future__ import unicode_literals

from django.db import migrations

from juloserver.application_flow.constants import PartnerNameConstant
from juloserver.partnership.constants import PartnershipFeatureNameConst
from juloserver.partnership.models import PartnershipFeatureSetting


def add_merchant_financing_replenish_limit_feature_setting(apps, schema_editor):
    mf_replenish_feature_setting = PartnershipFeatureSetting.objects.filter(
        feature_name=PartnershipFeatureNameConst.MERCHANT_FINANCING_LIMIT_REPLENISHMENT,
    ).first()
    if mf_replenish_feature_setting:
        mf_replenish_feature_setting.parameters[PartnerNameConstant.AXIATA_WEB] = True
    else:
        PartnershipFeatureSetting.objects.create(
            feature_name=PartnershipFeatureNameConst.MERCHANT_FINANCING_LIMIT_REPLENISHMENT,
            is_active=True,
            parameters={PartnerNameConstant.AXIATA_WEB: True},
            description="Determine the limit will be replenish for each repayment if the partner name exists and with value True",
        )


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunPython(
            add_merchant_financing_replenish_limit_feature_setting,
            migrations.RunPython.noop,
        )
    ]
