# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-09-26 09:11
from __future__ import unicode_literals

from django.db import migrations

from juloserver.application_flow.constants import PartnerNameConstant
from juloserver.partnership.constants import PartnershipFeatureNameConst
from juloserver.partnership.models import PartnershipFeatureSetting


def create_leadgen_webapp_otp_partner(apps, schema_editor):
    PartnershipFeatureSetting.objects.create(
        feature_name=PartnershipFeatureNameConst.LEADGEN_PARTNER_WEBAPP_OTP_REGISTER,
        is_active=True,
        parameters={
            'partners': [
                PartnerNameConstant.CERMATI,
                PartnerNameConstant.IOH_MYIM3,
                PartnerNameConstant.IOH_BIMA_PLUS,
                PartnerNameConstant.SELLURY,
                PartnerNameConstant.SMARTFREN,
            ]
        },
        description='list of leadgen webapp partner that use OTP on register process',
        category='partnership',
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(create_leadgen_webapp_otp_partner, migrations.RunPython.noop)
    ]
