# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-09-24 06:59
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.channeling_loan.constants import (
    FeatureNameConst,
)
from juloserver.channeling_loan.constants.bni_constants import (
    BNI_DEFAULT_INTEREST,
)


def add_bni_channeling_loan_configuration(apps, _schema_editor):
    FeatureSetting.objects.update_or_create(
        feature_name=FeatureNameConst.BNI_INTEREST_CONFIG,
        defaults={
            "is_active": True,
            "description": "BNI interest config, separated from channeling_loan_config because they have custom interest based on tenor",
            "parameters": {"interest": BNI_DEFAULT_INTEREST},
        },
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(add_bni_channeling_loan_configuration, migrations.RunPython.noop),
    ]
