# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-09-25 07:11
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def add_mycroft_threshold_for_swift_limit_drainer_feature(*args, **kwargs):
    fs = FeatureSetting.objects.get(feature_name=FeatureNameConst.SWIFT_LIMIT_DRAINER)
    fs_parameters = fs.parameters
    fs_parameters['mycroft'] = 0.85
    fs.update_safely(parameters=fs_parameters)


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunPython(
            add_mycroft_threshold_for_swift_limit_drainer_feature, migrations.RunPython.noop
        )
    ]
