# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-09-23 14:35
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.minisquad.constants import FeatureNameConst


def add_feature_setting_to_merge_j1_and_jturbo_bucket(apps, schema_editor):
    params = (
        FeatureSetting.objects.filter(
            feature_name=FeatureNameConst.AI_RUDDER_FULL_ROLLOUT, is_active=True
        )
        .get()
        .parameters
    )
    params.update(bucket_numbers_to_merge=[1])
    FeatureSetting.objects.filter(feature_name=FeatureNameConst.AI_RUDDER_FULL_ROLLOUT).update(
        parameters=params
    )


class Migration(migrations.Migration):
    dependencies = []
    operations = [
        migrations.RunPython(
            add_feature_setting_to_merge_j1_and_jturbo_bucket, migrations.RunPython.noop
        )
    ]
