# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-10-13 15:00
from __future__ import unicode_literals

from django.db import migrations
from juloserver.loan.constants import LoanFeatureNameConst
from juloserver.julo.models import FeatureSetting


def create_feature_settings_qris_eligible_user(apps, _schema_editor):
    parameters = {
        'customer_ids': []
    }
    FeatureSetting.objects.create(
         feature_name=LoanFeatureNameConst.QRIS_WHITELIST_ELIGIBLE_USER,
         parameters=parameters,
         category='loan',
         is_active=True
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_feature_settings_qris_eligible_user, migrations.RunPython.noop)
    ]
