# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-10-14 04:47
from __future__ import unicode_literals

from django.db import migrations

from juloserver.account_payment.models import CRMCustomerDetail


def edit_processed_refinancing_eligible(apps, schema_editor):
    data = CRMCustomerDetail.objects.filter(
        attribute_name='Memenuhi Syarat Refinancing', section='Detail Pembayaran'
    ).last()
    if not data:
        return

    new_params = data.parameter_model_value
    new_params['models'] = {
        'accountpayment': 'model.account.id',
        'account': 'model.id',
    }
    new_params['function_path'] = 'juloserver.waiver.services.account_related'
    new_params['function_name'] = 'can_account_get_refinancing_bss'
    new_params['function'] = 'function_name(model_identifier)[0]'
    data.parameter_model_value = new_params
    data.save()


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(edit_processed_refinancing_eligible, migrations.RunPython.noop),
    ]
