# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-10-14 04:22
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import WorkflowConst
from juloserver.julo.models import Workflow, WorkflowStatusNode
from juloserver.julo.statuses import ApplicationStatusCodes


def add_j1_120_status_handler(apps, schema_editor):
    j1_workflow = Workflow.objects.filter(name=WorkflowConst.JULO_ONE).last()
    exists = WorkflowStatusNode.objects.filter(
        status_node=ApplicationStatusCodes.DOCUMENTS_SUBMITTED,
        handler='JuloOne120Handler',
        workflow=j1_workflow,
    ).exists()
    if exists:
        return

    WorkflowStatusNode.objects.create(
        status_node=ApplicationStatusCodes.DOCUMENTS_SUBMITTED,
        handler='JuloOne120Handler',
        workflow=j1_workflow,
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(add_j1_120_status_handler, migrations.RunPython.noop),
    ]
