# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-10-07 10:18
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def add_feature_setting_moengage_ewallet_balance(apps, schema_editor):
    feature_setting = FeatureSetting.objects.filter(
        feature_name=FeatureNameConst.MOENGAGE_EWALLET_BALANCE).last()
    if feature_setting:
        current_setting = feature_setting.parameters
        current_setting['ovo'] = {
                    "moengage_attribute": "latest_ovo_wallet_is_below_15k_or_20%",
                    "treshold_balance": 15000,
                    "treshold_percentage": 20,
                }
        feature_setting.update_safely(parameters=current_setting)


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunPython(
            add_feature_setting_moengage_ewallet_balance, migrations.RunPython.noop
        ),
    ]
