# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-10-10 05:00
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings
from juloserver.followthemoney.constants import LoanAgreementType
from juloserver.followthemoney.models import LoanAgreementTemplate


def update_qris_skrtp_default_template(apps, _schema_editor):
    template_dir = '/juloserver/julo/templates/loan_agreement/qris_skrtp.html'
    with open(settings.BASE_DIR + template_dir, "r") as file:
        basehtml = file.read()

    LoanAgreementTemplate.objects.create(
        agreement_type=LoanAgreementType.QRIS_SKRTP, body=basehtml, is_active=True
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(update_qris_skrtp_default_template, migrations.RunPython.noop)
    ]
