# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-10-07 05:57
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def create_fs_emulator_check_rate_limit(apps, _schema_editor):
    feature_setting = FeatureSetting.objects.get_or_none(
        feature_name=FeatureNameConst.ANTIFRAUD_RATE_LIMIT
    )
    if not feature_setting:
        return

    if feature_setting.parameters.get('emulator_check'):
        return

    config = {
        'is_active': False,
        'max_count': 2,
        'time_unit': 'Minutes',
    }
    feature_setting.parameters['emulator_check'] = config
    feature_setting.save()


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(create_fs_emulator_check_rate_limit,
                             migrations.RunPython.noop)
    ]
