# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-10-22 07:07
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.channeling_loan.constants import (
    FeatureNameConst,
    ChannelingConst,
)


def add_channeling_loan_config_cutoff(apps, _schema_editor):
    channeling_loan_configuration = FeatureSetting.objects.get_or_none(
        feature_name=FeatureNameConst.CHANNELING_LOAN_CONFIG
    )
    for key, value in channeling_loan_configuration.parameters.items():
        value['cutoff']['CHANNEL_AFTER_CUTOFF'] = False
        if key == ChannelingConst.FAMA:
            value['cutoff']['CHANNEL_AFTER_CUTOFF'] = True

    channeling_loan_configuration.save()


class Migration(migrations.Migration):

    dependencies = []

    operations = [migrations.RunPython(add_channeling_loan_config_cutoff)]
