# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-10-18 07:07
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def update_fs_fraud_face_similarity(apps, _schema_editor):
    feature_setting = FeatureSetting.objects.get_or_none(
        feature_name='face_similarity_threshold_x109_jturbo'
    )
    if not feature_setting:
        return

    if feature_setting.parameters.get('fraud_similarity_threshold'):
        return

    feature_setting.parameters['fraud_similarity_threshold'] = 0
    feature_setting.save()


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(update_fs_fraud_face_similarity,
                             migrations.RunPython.noop)
    ]
