# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-10-23 10:01
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.channeling_loan.constants import (
    FeatureNameConst,
    ChannelingConst,
)


def add_channeling_loan_config_cutoff_for_bni(apps, _schema_editor):
    channeling_loan_configuration = FeatureSetting.objects.get_or_none(
        feature_name=FeatureNameConst.CHANNELING_LOAN_CONFIG
    )
    if channeling_loan_configuration:
        channeling_loan_configuration.parameters[ChannelingConst.BNI]['cutoff'] = {
            'is_active': True,
            'INACTIVE_DAY': [],
            'INACTIVE_DATE': [],
            'CHANNEL_AFTER_CUTOFF': False,
            'OPENING_TIME': {'hour': 7, 'minute': 0, 'second': 0},
            'CUTOFF_TIME': {'hour': 16, 'minute': 0, 'second': 0},
            'LIMIT': 100,
        }

        channeling_loan_configuration.save()


class Migration(migrations.Migration):

    dependencies = []

    operations = [migrations.RunPython(add_channeling_loan_config_cutoff_for_bni)]
