# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-10-23 13:19
from __future__ import unicode_literals

from django.db import migrations

from juloserver.minisquad.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import EmailDeliveryAddress


def add_waiver_r4_promo_blast_feature_setting(apps, _schema_editor):
    parameters = {
        "campaign_name": "r4_promo_dpd181_oct_24",
        "templates": {
            "waiver_promo_dpd181_JH": {
                "template_name": "waiver_promo_dpd181_JH.html",
                "lender": "JH",
                "dpd": 181,
                "html": "<html lang='en'><head><meta charset='UTF-8'><meta name='viewport' content='width=device-width,initial-scale=1'><style>body{font-family:Arial,Helvetica,sans-serif;text-align:justify;font-size:12pt;line-height:1.5;letter-spacing:normal;word-spacing:normal;margin:0}#main{display:table}table{width:100%;text-align:justify;font-size:12pt;line-height:1.5;letter-spacing:normal;word-spacing:normal}table,td,th{border-collapse:collapse}td,th{padding-top:0;padding-bottom:10pt}.spacing{height:18pt}</style></head><body><table><tr><td>Kepada <strong>{{name_with_title}}</strong>,</td></tr><tr><td>Dengan hormat,</td></tr><tr><td>Kami dari KALD Law Office, selaku kuasa hukum dari Klien Kami, <b>Julo Holdings Pte. Ltd</b> ingin menginformasikan tunggakan tagihan Anda yang belum dilunasi. Untuk menyelesaikan permasalahan ini secara damai, dan untuk menghindari proses hukum dan <b>catatan buruk SLIK OJK</b> Anda, Klien Kami memberikan penawaran dengan <b>penghapusan denda dan bunga dan potongan pokok hingga 40%</b></td></tr><tr><td>Berikut adalah jumlah yang perlu Anda bayarkan setelah mendapat potongan, yakni:</td></tr><tr><td><s>{{due_amount}}</s><br><strong>{{discounted_due_amount}}</strong></td></tr><tr><td>Untuk mendapatkan penawaran ini dan informasi mengenai pembayaran bertahap, silahkan hubungi Klien Kami melalui:</td></tr><tr><td>Layanan Telepon: 021-5091-9036, 021-5091-9037, atau 021-3043-3660</td></tr><tr><td>Jika kami tidak menerima tanggapan Anda hingga tanggal <b>31 Oktober 2024</b>, kami akan menempuh langkah-langkah hukum untuk menagih jumlah yang terutang</td></tr><tr><td>Demikian pemberitahuan ini kami sampaikan. Atas perhatiannya, kami ucapkan terima kasih.</td></tr><tr><td>Salam,</td></tr><tr><td>KALD Law Office</td></tr></table></body></html>",
            },
            "waiver_promo_dpd181_JTP": {
                "template_name": "waiver_promo_dpd181_JH.html",
                "lender": "JTP",
                "dpd": 181,
                "html": "<html lang='en'><head><meta charset='UTF-8'><meta name='viewport' content='width=device-width,initial-scale=1'><style>body{font-family:Arial,Helvetica,sans-serif;text-align:justify;font-size:12pt;line-height:1.5;letter-spacing:normal;word-spacing:normal;margin:0}#main{display:table}table{width:100%;text-align:justify;font-size:12pt;line-height:1.5;letter-spacing:normal;word-spacing:normal}table,td,th{border-collapse:collapse}td,th{padding-top:0;padding-bottom:10pt}.spacing{height:18pt}</style></head><body><table><tr><td>Kepada <strong>{{name_with_title}}</strong>,</td></tr><tr><td>Dengan hormat,</td></tr><tr><td>Kami dari KALD Law Office, selaku kuasa hukum dari Klien Kami, <b>PT Julo Teknologi Perdana</b> ingin menginformasikan tunggakan tagihan Anda yang belum dilunasi. Untuk menyelesaikan permasalahan ini secara damai, dan untuk menghindari proses hukum dan <b>catatan buruk SLIK OJK</b> Anda, Klien Kami memberikan penawaran dengan <b>penghapusan denda dan bunga dan potongan pokok hingga 40%</b></td></tr><tr><td>Berikut adalah jumlah yang perlu Anda bayarkan setelah mendapat potongan, yakni:</td></tr><tr><td><s>{{due_amount}}</s><br><strong>{{discounted_due_amount}}</strong></td></tr><tr><td>Untuk mendapatkan penawaran ini dan informasi mengenai pembayaran bertahap, silahkan hubungi Klien Kami melalui:</td></tr><tr><td>Layanan Telepon: 021-5091-9036, 021-5091-9037, atau 021-3043-3660</td></tr><tr><td>Jika kami tidak menerima tanggapan Anda hingga tanggal <b>31 Oktober 2024</b>, kami akan menempuh langkah-langkah hukum untuk menagih jumlah yang terutang</td></tr><tr><td>Demikian pemberitahuan ini kami sampaikan. Atas perhatiannya, kami ucapkan terima kasih.</td></tr><tr><td>Salam,</td></tr><tr><td>KALD Law Office</td></tr></table></body></html>",
            },
            "waiver_promo_dpd181_JTPJH": {
                "template_name": "waiver_promo_dpd181_JTPJH.html",
                "lender": "JTPJH",
                "dpd": 181,
                "html": "<html lang='en'><head><meta charset='UTF-8'><meta name='viewport' content='width=device-width,initial-scale=1'><style>body{font-family:Arial,Helvetica,sans-serif;text-align:justify;font-size:12pt;line-height:1.5;letter-spacing:normal;word-spacing:normal;margin:0}#main{display:table}table{width:100%;text-align:justify;font-size:12pt;line-height:1.5;letter-spacing:normal;word-spacing:normal}table,td,th{border-collapse:collapse}td,th{padding-top:0;padding-bottom:10pt}.spacing{height:18pt}</style></head><body><table><tr><td>Kepada <strong>{{name_with_title}}</strong>,</td></tr><tr><td>Dengan hormat,</td></tr><tr><td>Kami dari KALD Law Office, selaku kuasa hukum dari Klien Kami, <b>PT Julo Teknologi Perdana dan Julo Holdings Pte. Ltd</b> ingin menginformasikan tunggakan tagihan Anda yang belum dilunasi. Untuk menyelesaikan permasalahan ini secara damai, dan untuk menghindari proses hukum dan <b>catatan buruk SLIK OJK</b> Anda, Klien Kami memberikan penawaran dengan <b>penghapusan denda dan bunga dan potongan pokok hingga 40%</b></td></tr><tr><td>Berikut adalah jumlah yang perlu Anda bayarkan setelah mendapat potongan, yakni:</td></tr><tr><td><s>{{due_amount}}</s><br><strong>{{discounted_due_amount}}</strong></td></tr><tr><td>Untuk mendapatkan penawaran ini dan informasi mengenai pembayaran bertahap, silahkan hubungi Klien Kami melalui:</td></tr><tr><td>Layanan Telepon: 021-5091-9036, 021-5091-9037, atau 021-3043-3660</td></tr><tr><td>Jika kami tidak menerima tanggapan Anda hingga tanggal <b>31 Oktober 2024</b>, kami akan menempuh langkah-langkah hukum untuk menagih jumlah yang terutang</td></tr><tr><td>Demikian pemberitahuan ini kami sampaikan. Atas perhatiannya, kami ucapkan terima kasih.</td></tr><tr><td>Salam,</td></tr><tr><td>KALD Law Office</td></tr></table></body></html>",
            },
            "waiver_promo_dpd271_JH": {
                "template_name": "waiver_promo_dpd271_JH.html",
                "lender": "JH",
                "dpd": 271,
                "html": "<html lang='en'><head><meta charset='UTF-8'><meta name='viewport' content='width=device-width,initial-scale=1'><style>body{font-family:Arial,Helvetica,sans-serif;text-align:justify;font-size:12pt;line-height:1.5;letter-spacing:normal;word-spacing:normal;margin:0}#main{display:table}table{width:100%;text-align:justify;font-size:12pt;line-height:1.5;letter-spacing:normal;word-spacing:normal}table,td,th{border-collapse:collapse}td,th{padding-top:0;padding-bottom:10pt}.spacing{height:18pt}</style></head><body><table><tr><td>Kepada <strong>{{name_with_title}}</strong>,</td></tr><tr><td>Dengan hormat,</td></tr><tr><td>Kami dari KALD Law Office, selaku kuasa hukum dari Klien Kami, <b>Julo Holdings Pte. Ltd</b> ingin menginformasikan tunggakan tagihan Anda yang belum dilunasi. Untuk menyelesaikan permasalahan ini secara damai, dan untuk menghindari proses hukum dan <b>catatan buruk SLIK OJK</b> Anda, Klien Kami memberikan penawaran dengan <b>penghapusan denda dan bunga dan potongan pokok hingga 50%</b></td></tr><tr><td>Berikut adalah jumlah yang perlu Anda bayarkan setelah mendapat potongan, yakni:</td></tr><tr><td><s>{{due_amount}}</s><br><strong>{{discounted_due_amount}}</strong></td></tr><tr><td>Untuk mendapatkan penawaran ini dan informasi mengenai pembayaran bertahap, silahkan hubungi Klien Kami melalui:</td></tr><tr><td>Layanan Telepon: 021-5091-9036, 021-5091-9037, atau 021-3043-3660</td></tr><tr><td>Jika kami tidak menerima tanggapan Anda hingga tanggal <b>31 Oktober 2024</b>, kami akan menempuh langkah-langkah hukum untuk menagih jumlah yang terutang</td></tr><tr><td>Demikian pemberitahuan ini kami sampaikan. Atas perhatiannya, kami ucapkan terima kasih.</td></tr><tr><td>Salam,</td></tr><tr><td>KALD Law Office</td></tr></table></body></html>",
            },
            "waiver_promo_dpd271_JTP": {
                "template_name": "waiver_promo_dpd271_JH.html",
                "lender": "JTP",
                "dpd": 271,
                "html": "<html lang='en'><head><meta charset='UTF-8'><meta name='viewport' content='width=device-width,initial-scale=1'><style>body{font-family:Arial,Helvetica,sans-serif;text-align:justify;font-size:12pt;line-height:1.5;letter-spacing:normal;word-spacing:normal;margin:0}#main{display:table}table{width:100%;text-align:justify;font-size:12pt;line-height:1.5;letter-spacing:normal;word-spacing:normal}table,td,th{border-collapse:collapse}td,th{padding-top:0;padding-bottom:10pt}.spacing{height:18pt}</style></head><body><table><tr><td>Kepada <strong>{{name_with_title}}</strong>,</td></tr><tr><td>Dengan hormat,</td></tr><tr><td>Kami dari KALD Law Office, selaku kuasa hukum dari Klien Kami, <b>PT Julo Teknologi Perdana</b> ingin menginformasikan tunggakan tagihan Anda yang belum dilunasi. Untuk menyelesaikan permasalahan ini secara damai, dan untuk menghindari proses hukum dan <b>catatan buruk SLIK OJK</b> Anda, Klien Kami memberikan penawaran dengan <b>penghapusan denda dan bunga dan potongan pokok hingga 50%</b></td></tr><tr><td>Berikut adalah jumlah yang perlu Anda bayarkan setelah mendapat potongan, yakni:</td></tr><tr><td><s>{{due_amount}}</s><br><strong>{{discounted_due_amount}}</strong></td></tr><tr><td>Untuk mendapatkan penawaran ini dan informasi mengenai pembayaran bertahap, silahkan hubungi Klien Kami melalui:</td></tr><tr><td>Layanan Telepon: 021-5091-9036, 021-5091-9037, atau 021-3043-3660</td></tr><tr><td>Jika kami tidak menerima tanggapan Anda hingga tanggal <b>31 Oktober 2024</b>, kami akan menempuh langkah-langkah hukum untuk menagih jumlah yang terutang</td></tr><tr><td>Demikian pemberitahuan ini kami sampaikan. Atas perhatiannya, kami ucapkan terima kasih.</td></tr><tr><td>Salam,</td></tr><tr><td>KALD Law Office</td></tr></table></body></html>",
            },
            "waiver_promo_dpd271_JTPJH": {
                "template_name": "waiver_promo_dpd271_JH.html",
                "lender": "JTPJH",
                "dpd": 271,
                "html": "<html lang='en'><head><meta charset='UTF-8'><meta name='viewport' content='width=device-width,initial-scale=1'><style>body{font-family:Arial,Helvetica,sans-serif;text-align:justify;font-size:12pt;line-height:1.5;letter-spacing:normal;word-spacing:normal;margin:0}#main{display:table}table{width:100%;text-align:justify;font-size:12pt;line-height:1.5;letter-spacing:normal;word-spacing:normal}table,td,th{border-collapse:collapse}td,th{padding-top:0;padding-bottom:10pt}.spacing{height:18pt}</style></head><body><table><tr><td>Kepada <strong>{{name_with_title}}</strong>,</td></tr><tr><td>Dengan hormat,</td></tr><tr><td>Kami dari KALD Law Office, selaku kuasa hukum dari Klien Kami, <b>PT Julo Teknologi Perdana dan Julo Holdings Pte. Ltd</b> ingin menginformasikan tunggakan tagihan Anda yang belum dilunasi. Untuk menyelesaikan permasalahan ini secara damai, dan untuk menghindari proses hukum dan <b>catatan buruk SLIK OJK</b> Anda, Klien Kami memberikan penawaran dengan <b>penghapusan denda dan bunga dan potongan pokok hingga 50%</b></td></tr><tr><td>Berikut adalah jumlah yang perlu Anda bayarkan setelah mendapat potongan, yakni:</td></tr><tr><td><s>{{due_amount}}</s><br><strong>{{discounted_due_amount}}</strong></td></tr><tr><td>Untuk mendapatkan penawaran ini dan informasi mengenai pembayaran bertahap, silahkan hubungi Klien Kami melalui:</td></tr><tr><td>Layanan Telepon: 021-5091-9036, 021-5091-9037, atau 021-3043-3660</td></tr><tr><td>Jika kami tidak menerima tanggapan Anda hingga tanggal <b>31 Oktober 2024</b>, kami akan menempuh langkah-langkah hukum untuk menagih jumlah yang terutang</td></tr><tr><td>Demikian pemberitahuan ini kami sampaikan. Atas perhatiannya, kami ucapkan terima kasih.</td></tr><tr><td>Salam,</td></tr><tr><td>KALD Law Office</td></tr></table></body></html>",
            },
        },
        "email_settings": {
            "api_key": "xxxxx",
            "email_from": EmailDeliveryAddress.LEGAL_THIRD_PARTY,
            "name_from": "KALD Law Office",
        },
        "validation_settings": {
            "lender": {"allowed_lender": ["jtp", "jh"], "is_lender_validation": True},
            "dpd": {
                "dpd_start": 181,
                # "dpd_end": 0,
                "is_dpd_validation": True,
            },
        },
    }
    data_to_be_created = {
        'feature_name': FeatureNameConst.WAIVER_R4_PROMO_BLAST,
        'is_active': True,
        'parameters': parameters,
        'category': 'collection',
        'description': 'This configuration for waiver r4 promo blast',
    }
    fs = FeatureSetting.objects.filter(feature_name=FeatureNameConst.WAIVER_R4_PROMO_BLAST)
    if not fs:
        FeatureSetting.objects.create(**data_to_be_created)


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(add_waiver_r4_promo_blast_feature_setting, migrations.RunPython.noop),
    ]
