# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-11-04 05:58
from __future__ import unicode_literals

from django.db import migrations

from juloserver.application_flow.constants import PartnerNameConstant
from juloserver.julo.models import FeatureSetting
from juloserver.personal_data_verification.constants import FeatureNameConst


def create_feature_settings_dukcapil_verification_leadgen(apps, _schema_editor):

    dukcapil_verification_parameters = {
        "low_balance_quota_alert": 42000,
        "method": "direct_v2",
        "minimum_checks_to_pass": 2,
    }
    FeatureSetting.objects.get_or_create(
        feature_name=FeatureNameConst.DUKCAPIL_VERIFICATION_LEADGEN,
        parameters={
            'bypass_by_product_line': [],
            PartnerNameConstant.CERMATI: dukcapil_verification_parameters,
            PartnerNameConstant.IOH_MYIM3: dukcapil_verification_parameters,
            PartnerNameConstant.IOH_BIMA_PLUS: dukcapil_verification_parameters,
            PartnerNameConstant.SELLURY: dukcapil_verification_parameters,
            PartnerNameConstant.SMARTFREN: dukcapil_verification_parameters,
        },
        is_active=True,
        description=FeatureNameConst.DUKCAPIL_VERIFICATION_LEADGEN,
        category='personal_data_verification',
    )

    FeatureSetting.objects.get_or_create(
        is_active=False,
        feature_name=FeatureNameConst.DUKCAPIL_BYPASS_TOGGLE_LEADGEN,
        description="Configuration for DUKCAPIL bypassing leadgen toggle",
        parameters={
            PartnerNameConstant.CERMATI: True,
            PartnerNameConstant.IOH_MYIM3: True,
            PartnerNameConstant.IOH_BIMA_PLUS: True,
            PartnerNameConstant.SELLURY: True,
            PartnerNameConstant.SMARTFREN: True,
        },
        category='personal_data_verification',
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(
            create_feature_settings_dukcapil_verification_leadgen, migrations.RunPython.noop
        )
    ]
