# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-11-04 09:43
from __future__ import unicode_literals

from django.db import migrations

from juloserver.sales_ops.constants import CustomerType
from juloserver.sales_ops_pds.models import AIRudderAgentGroupMapping


def create_sales_ops_pds_group_mapping(apps, _schema_editor):
    group_mapping_data = [
        ("sales_ops_a", CustomerType.FTC, "Team1_FTC"),
        ("sales_ops_a", CustomerType.REPEAT_OS, "Team1_RepeatOS"),
        ("sales_ops_a", CustomerType.REPEAT_NO_OS, "Team1_RepeatNO_OS"),
        ("sales_ops_b", CustomerType.FTC, "Team2_FTC"),
        ("sales_ops_b", CustomerType.REPEAT_OS, "Team2_RepeatOS"),
        ("sales_ops_b", CustomerType.REPEAT_NO_OS, "Team2_RepeatNO_OS"),
        ("sales_ops_c", CustomerType.FTC, "Team3_FTC"),
        ("sales_ops_c", CustomerType.REPEAT_OS, "Team3_RepeatOS"),
        ("sales_ops_c", CustomerType.REPEAT_NO_OS, "Team3_RepeatNO_OS"),
        ("sales_ops_d", CustomerType.FTC, "Team4_FTC"),
        ("sales_ops_d", CustomerType.REPEAT_OS, "Team4_RepeatOS"),
        ("sales_ops_d", CustomerType.REPEAT_NO_OS, "Team4_RepeatNO_OS"),
        ("sales_ops_e", CustomerType.FTC, "Team5_FTC"),
        ("sales_ops_e", CustomerType.REPEAT_OS, "Team5_RepeatOS"),
        ("sales_ops_e", CustomerType.REPEAT_NO_OS, "Team5_RepeatNO_OS"),
    ]

    create_data = []
    for data in group_mapping_data:
        create_data.append(
            AIRudderAgentGroupMapping(
                bucket_code=data[0], customer_type=data[1], agent_group_name=data[2]
            )
        )
    AIRudderAgentGroupMapping.objects.bulk_create(create_data)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_sales_ops_pds_group_mapping, migrations.RunPython.noop)
    ]
