# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-10-28 09:13
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def update_delay_fs_fraud_matching(apps, _schema_editor):
    feature_setting = FeatureSetting.objects.get_or_none(
        feature_name='face_matching_similarity_threshold_x109_jturbo'
    )
    if not feature_setting:
        return

    if feature_setting.parameters.get('delay'):
        return

    feature_setting.parameters['delay'] = 5
    feature_setting.save()


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(update_delay_fs_fraud_matching,
                             migrations.RunPython.noop)
    ]
