# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-11-05 12:47
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting


def operation(apps, schema_editor):
    fs_j1: FeatureSetting = FeatureSetting.objects.filter(
        feature_name='abc_close_kin_contact'
    ).last()
    if not fs_j1:
        return
    fs_j1.parameters['mycroft_score_threshold'] = 0.9
    fs_j1.category = 'antifraud'
    fs_j1.save(update_fields=['parameters', 'category'])

    FeatureSetting.objects.get_or_create(
        feature_name='abc_close_kin_contact_jturbo',
        category=fs_j1.category,
        description=fs_j1.description + ' (JTURBO)',
        is_active=False,
        parameters=fs_j1.parameters,
    )


class Migration(migrations.Migration):
    dependencies = []

    operations = [migrations.RunPython(operation, migrations.RunPython.noop)]
