# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-11-05 03:15
from __future__ import unicode_literals

from django.db import migrations
from django.utils import timezone
from dateutil.relativedelta import relativedelta
from juloserver.julo.models import ExperimentSetting
from juloserver.minisquad.constants import ExperimentConst


def create_bttc_experiment_for_b1(apps, schema_editor):
    criteria = {
        'bucket_eligible': [1],
        'next_range_map': {"A": "B", "B": "C", "C": "D"},
        'bttc_time_to_call': {"A": "08:00", "B": "10:00", "C": "13:00", "D": "16:00"},
        'delinquent_bucket_experiment_list': {
            'JULO_B1': {
                'bttc-B1-experiment1': {
                    'due_date_range': [4, 5, 6, 7, 16, 17, 18, 26, 27, 28],
                    'group_list': ['A', 'B', 'C', 'D'],
                    'ana_experiment_name': 'b1_experiment',
                },
                'bttc-B1-experiment2': {
                    'due_date_range': [8, 9, 10, 11, 19, 20, 21, 29, 30, 31],
                    'group_list': ['A', 'B', 'C', 'D'],
                    'ana_experiment_name': 'b1_experiment',
                },
                'bttc-B1-experiment3': {
                    'due_date_range': [1, 2, 3, 12, 13, 14, 15, 22, 23, 24, 25],
                    'group_list': ['A', 'B', 'C', 'D'],
                    'ana_experiment_name': 'b1_experiment',
                },
            }
        },
        'max_schedule_for_trigger_construct': {'JULO_B1': '04:15'},
    }
    now = timezone.localtime(timezone.now())
    ExperimentSetting.objects.create(
        is_active=False,
        code=ExperimentConst.DELINQUENT_BTTC_EXPERIMENT,
        name="Delinquent_BTTC_Experiment",
        start_date=now,
        end_date=now + relativedelta(days=15),
        schedule="",
        action="",
        type="collection",
        criteria=criteria,
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [migrations.RunPython(create_bttc_experiment_for_b1, migrations.RunPython.noop)]
