# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-11-05 09:45
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def add_mycroft_threshold_for_j1_and_jturbo(*args, **kwargs):
    fs = FeatureSetting.objects.get(feature_name=FeatureNameConst.SWIFT_LIMIT_DRAINER)
    fs_parameters = fs.parameters
    del fs_parameters['mycroft']
    fs_parameters['mycroft_j1'] = 0.85
    fs_parameters['mycroft_jturbo'] = 0.85
    fs.update_safely(parameters=fs_parameters)


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunPython(add_mycroft_threshold_for_j1_and_jturbo, migrations.RunPython.noop)
    ]
