# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-11-04 06:25
from __future__ import unicode_literals

from django.db import migrations

from juloserver.dana.constants import DanaProductType
from juloserver.minisquad.constants import DialerSystemConst
from juloserver.partnership.constants import PartnershipFeatureNameConst
from juloserver.partnership.models import PartnershipFeatureSetting


def add_feature_setting_partnership_dana_collection_bucket(apps, schema_editor):
    PartnershipFeatureSetting.objects.create(
        feature_name=PartnershipFeatureNameConst.PARTNERSHIP_DANA_COLLECTION_BUCKET_CONFIGURATION,
        is_active=True,
        parameters={
            "buckets": [
                {
                    "name": DialerSystemConst.DANA_BUCKET_CICIL,
                    "dpd": {"from": 6, "to": 30},
                    "product_id": DanaProductType.CICIL,
                },
                {
                    "name": DialerSystemConst.DANA_BUCKET_CASHLOAN,
                    "dpd": {"from": 0, "to": 30},
                    "product_id": DanaProductType.CASH_LOAN,
                },
                {
                    "name": DialerSystemConst.DANA_BUCKET_SIM,
                    "dpd": {"from": 31, "to": 60},
                    "product_id": "",
                },
                {
                    "name": DialerSystemConst.DANA_BUCKET_PEPPER,
                    "dpd": {"from": 61, "to": 90},
                    "product_id": "",
                },
                {
                    "name": DialerSystemConst.DANA_BUCKET_91_PLUS,
                    "dpd": {"from": 91, "to": 180},
                    "product_id": "",
                },
            ]
        },
        description='partnership dana collection bucket configuration',
        category='partnership',
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(
            add_feature_setting_partnership_dana_collection_bucket,
            migrations.RunPython.noop,
        )
    ]
