# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-11-18 08:41
from __future__ import unicode_literals

from django.db import migrations

from juloserver.streamlined_communication.models import StreamlinedCampaignDepartment


def add_streamlined_campaign_departments(apps, schema_editor):
    data = [
        {'name': 'Marketing', 'department_code': 'MKT'},
        {'name': 'Growth', 'department_code': 'GRO'},
        {'name': 'Products', 'department_code': 'PRO'},
        {'name': 'Collection', 'department_code': 'COL'},
    ]

    for entry in data:
        department_name = entry['name']
        department_code = entry['department_code']

        if not StreamlinedCampaignDepartment.objects.filter(
            department_code=department_code
        ).exists():
            StreamlinedCampaignDepartment.objects.create(
                name=department_name, department_code=department_code
            )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(add_streamlined_campaign_departments, migrations.RunPython.noop),
    ]
