# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-11-18 10:41
from __future__ import unicode_literals

from django.db import migrations

from juloserver.streamlined_communication.models import StreamlinedCampaignSquad


def add_streamlined_campaign_squads(apps, schema_editor):
    data = [
        {'name': 'Collection'},
        {'name': 'Communication'},
        {'name': 'Promotion'},
        {'name': 'Grab'},
    ]

    for entry in data:
        squad_name = entry['name']

        if not StreamlinedCampaignSquad.objects.filter(name=squad_name).exists():
            StreamlinedCampaignSquad.objects.create(
                name=squad_name,
            )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(add_streamlined_campaign_squads, migrations.RunPython.noop),
    ]
