# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-11-13 07:16
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def add_jaildays_for_fraud_block_account(*args, **kwargs):
    fs_swift = FeatureSetting.objects.get(feature_name=FeatureNameConst.SWIFT_LIMIT_DRAINER)
    fs_swift_parameters = fs_swift.parameters
    if 'jail_days_jturbo' in fs_swift_parameters:
        del fs_swift_parameters['jail_days_j1']
    if 'jail_days_jturbo' in fs_swift_parameters:
        del fs_swift_parameters['jail_days_jturbo']
    fs_swift.update_safely(parameters=fs_swift_parameters)

    fs_fraud_block = FeatureSetting.objects.get(
        feature_name=FeatureNameConst.FRAUD_BLOCK_ACCOUNT_FEATURE
    )
    fs_fraud_block_parameters = fs_fraud_block.parameters
    current_jail_days = fs_fraud_block_parameters['jail_days']
    fs_fraud_block_parameters['jail_days_j1'] = current_jail_days
    fs_fraud_block_parameters['jail_days_jturbo'] = current_jail_days
    fs_fraud_block.update_safely(parameters=fs_fraud_block_parameters)


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunPython(add_jaildays_for_fraud_block_account, migrations.RunPython.noop)
    ]
