# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-11-12 02:56
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting
from juloserver.sales_ops_pds.constants import (
    FeatureNameConst,
    SalesOpsPDSAlert,
    SalesOpsPDSTaskName,
)


def create_sales_ops_pds_fs(apps, _schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.SALES_OPS_PDS,
        category="sales_ops_pds",
        description="Turn on/off for Sales Ops PDS tasks",
        is_active=False,
        parameters={
            SalesOpsPDSTaskName.CREATE_TASK: False,
            SalesOpsPDSTaskName.DOWNLOAD_CALL_RESULT: False,
            SalesOpsPDSTaskName.DOWNLOAD_RECORDING_FILE: False
        }
    )


def create_sales_ops_pds_alert_fs(apps, _schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.SALES_OPS_PDS_ALERT,
        category="sales_ops_pds",
        description="Configurations for sending Sales Ops PDS notification via Slack",
        is_active=False,
        parameters={
            'message': '<!here> Creating PDS tasks on AIRudder report on *{date}*',
            'channel': SalesOpsPDSAlert.CHANNEL
        }
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_sales_ops_pds_fs, migrations.RunPython.noop),
        migrations.RunPython(create_sales_ops_pds_alert_fs, migrations.RunPython.noop)
    ]
