# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-11-22 04:15
from __future__ import unicode_literals

from django.db import migrations


from juloserver.account_payment.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def create_exclude_grab_from_update_payment_status_fs(apps, _schema_editor):
    FeatureSetting.objects.get_or_create(
        feature_name=FeatureNameConst.EXCLUDE_GRAB_FROM_UPDATE_PAYMENT_STATUS,
        category="repayment",
        description="exclude grab from task juloserver.account_payment."
        "tasks.scheduled_tasks.update_account_payment_status",
        is_active=False,
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(
            create_exclude_grab_from_update_payment_status_fs, migrations.RunPython.noop
        )
    ]
