# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-12-06 00:50
from __future__ import unicode_literals

from django.db import migrations

from juloserver.antifraud.constant.feature_setting import BinaryCheck, Holdout
from juloserver.julo.models import FeatureSetting


def create_feature_settings_antifraud_fraud_suspicious_app_jturbo(apps, _schema_editor):
    feature_setting = FeatureSetting.objects.filter(feature_name='abc_suspicious_apps_jturbo')

    if not feature_setting.exists():
        FeatureSetting.objects.create(
            feature_name='abc_suspicious_apps_jturbo',
            is_active=False,
            category="antifraud",
            description="Feature Flag for antifraud binary check suspicious apps jturbo",
            parameters={
                BinaryCheck.Parameter.HOLDOUT: {
                    BinaryCheck.Parameter.Holdout.TYPE: Holdout.Type.INACTIVE,
                    BinaryCheck.Parameter.Holdout.REGEX: "",
                    BinaryCheck.Parameter.Holdout.PERCENTAGE: 100,
                    BinaryCheck.Parameter.Holdout.PARTNER_IDS: [],
                },
            },
        )


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunPython(
            create_feature_settings_antifraud_fraud_suspicious_app_jturbo,
            migrations.RunPython.noop,
        )
    ]
