# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-12-06 06:02
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting
from juloserver.minisquad.constants import FeatureNameConst


def add_gdrive_config_for_physical_wl(apps, schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.PHYSICAL_WARNING_LETTER,
        is_active=True,
        description='This configuration for physical warning letter',
        category='collection',
        parameters={
            'physical_warning_letter': {
                'folder_id': '1X4A_R6EQ0FLAcAsBTK4yUhDOddwDBYwI',
                'filename': 'phisical_wl.csv',
                'queue': 'collection_high',
            },
        },
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(add_gdrive_config_for_physical_wl, migrations.RunPython.noop)
    ]
