# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-12-06 07:09
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.sales_ops_pds.constants import (
    FeatureNameConst,
    SalesOpsPDSTaskName,
    SalesOpsPDSDownloadConst
)


def add_query_limit_into_sales_ops_pds_fs(apps, _schema_editor):
    sales_ops_pds_fs = FeatureSetting.objects.filter(
        feature_name=FeatureNameConst.SALES_OPS_PDS
    ).last()
    if not sales_ops_pds_fs:
        return

    parameters = sales_ops_pds_fs.parameters
    parameters.update({
        SalesOpsPDSTaskName.DOWNLOAD_LIMIT: SalesOpsPDSDownloadConst.DEFAULT_DOWNLOAD_LIMIT
    })
    sales_ops_pds_fs.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            add_query_limit_into_sales_ops_pds_fs,
            migrations.RunPython.noop,
        )
    ]
