# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-12-06 03:00
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting

from juloserver.cfs.constants import CfsActionType, CfsActionId, EasyIncomeConstant
from juloserver.cfs.models import CfsAction


def init_mission_credit_card(apps, schema_editor):
    CfsAction.objects.create(
        id=CfsActionId.UPLOAD_CREDIT_CARD,
        action_code='upload_credit_card',
        title='Kredit card',
        display_order=15,
        is_active=True,
        action_type=CfsActionType.RECURRING,
        default_expiry=180,
        icon='https://julostatics.oss-ap-southeast-5.aliyuncs.com/cfs/icon_auto_debit.png',
        app_link='deeplink',
        first_occurrence_cashback_amount=100,
        repeat_occurrence_cashback_amount=100,
        is_need_agent_verify=True,
        app_version='8.39.0',
    )


def init_whitelist_credit_card(apps, schema_editor):
    FeatureSetting.objects.create(
        feature_name=EasyIncomeConstant.FEATURE_SETTING_WHITELIST_CREDIT_CARD,
        is_active=True,
        parameters={},
        description='whitelist credit card'
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(init_mission_credit_card, migrations.RunPython.noop),
        migrations.RunPython(init_whitelist_credit_card, migrations.RunPython.noop),
    ]
