# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-12-10 12:06
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import F
from juloserver.account_payment.models import CRMCustomerDetail


def add_risk_score_on_profil_pengguna(apps, schema_editor):
    # Step 1: Filter the items with sort_order >= 6 and update them
    sort_order_items = CRMCustomerDetail.objects.filter(
        section='Profil Pengguna', sort_order__gte=6
    )

    # Iterate through the items and update their sort_order by +1
    for item in sort_order_items:
        item.sort_order = F('sort_order') + 1
        item.save()

    risk_score_field = CRMCustomerDetail(
        section='Profil Pengguna',
        attribute_name='Risk Score',
        description="Risk score is a categorical string data",
        sort_order=6,  # As per the requirements, you want to set sort_order to 6
        parameter_model_value={
            'execution_mode': 'query',
            'models': {
                'accountpayment': 'model.get_all_loan_purpose_for_crm',
            },
            'default_value': '-',
            'dom': '<strong> {} </strong>',
        },
    )

    # Save the new item to the database
    risk_score_field.save()


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(add_risk_score_on_profil_pengguna, migrations.RunPython.noop),
    ]
