# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-12-10 02:22
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst


def execute(apps, schema_editor):

    is_exist = FeatureSetting.objects.filter(
        feature_name=FeatureNameConst.EXTERNAL_WARNING_LETTER
    ).exists()
    if not is_exist:
        FeatureSetting.objects.create(
            feature_name=FeatureNameConst.EXTERNAL_WARNING_LETTER,
            is_active=True,
            category='warning_letter',
            description='Configuration for external warning letter ',
            parameters={
                "HLO": {"is_active": False, "wl_version": 2, "wl_level": [3, 4, 5]},
                "KALD": {"is_active": True, "wl_version": 3, "wl_level": [3, 4, 5, 6]},
            },
        )


class Migration(migrations.Migration):

    dependencies = []

    operations = [migrations.RunPython(execute, migrations.RunPython.noop)]
