# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-12-19 06:40
from __future__ import unicode_literals

from django.db import migrations

from juloserver.channeling_loan.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def force_channeling(apps, schema_editor):
    parameters = {'FAMA': [10, 12]}
    FeatureSetting.objects.update_or_create(
        feature_name=FeatureNameConst.FORCE_CHANNELING,
        defaults={
            'is_active': True,
            'category': 'channeling_loan',
            'description': 'Feature Settings, Force Channeling',
            'parameters': parameters,
        },
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [migrations.RunPython(force_channeling, migrations.RunPython.noop)]
