# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-12-27 09:43
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.minisquad.constants import FeatureNameConst


def add_feature_setting_to_pass_other_number_to_pds(apps, schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.PASS_OTHER_NUMBER_TO_PDS,
        is_active=True,
        description='This configuration for passing other number to pds',
        category='collection',
        parameters={
            'max_phone_number': 3,
            'bucket_numbers': [3, 4],
        },
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(
            add_feature_setting_to_pass_other_number_to_pds, migrations.RunPython.noop
        )
    ]
