# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-01-14 13:36
from __future__ import unicode_literals

from django.db import migrations


from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import Partner, FeatureSetting
from juloserver.partnership.constants import PartnershipFlag
from juloserver.partnership.models import PartnershipFlowFlag


def add_leadgen_webapp_bank_validation_config(apps, schema_editor):
    feature_settings = FeatureSetting.objects.filter(
        feature_name=FeatureNameConst.LEAD_GEN_PARTNER_CREDIT_SCORE_GENERATION
    ).first()

    partners = feature_settings.parameters['partners']
    for partner_name in partners:
        partner = Partner.objects.get_or_none(name=partner_name)
        if not partner:
            continue

        PartnershipFlowFlag.objects.get_or_create(
            partner=partner,
            name=PartnershipFlag.PAYMENT_GATEWAY_SERVICE,
            configs={'payment_gateway_service': False},
        )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(add_leadgen_webapp_bank_validation_config, migrations.RunPython.noop)
    ]
