# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-01-13 03:41
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting
from juloserver.loan.constants import LoanFeatureNameConst


def add_qris_multiple_lender_setting(apps, schema_editor):
    parameters = {
        "out_of_balance_threshold": 500_000,
        "lender_names_ordered_by_priority": [
            'blue_finc_lender',
        ],
    }

    FeatureSetting.objects.update_or_create(
        feature_name=LoanFeatureNameConst.QRIS_MULTIPLE_LENDER,
        defaults={
            'is_active': False,
            'category': 'qris',
            'description': 'Configurations for QRIS multi-lender setting',
            'parameters': parameters,
        },
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(
            code=add_qris_multiple_lender_setting,
            reverse_code=migrations.RunPython.noop,
        )
    ]
