# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-01-08 05:25
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting

from juloserver.julo.constants import FeatureNameConst
from juloserver.payment_point.constants import TransactionMethodCode


def update_daily_disbursement_limit_fs(apps, _schema_editor):
    daily_disbursement_limit_fs = FeatureSetting.objects.get_or_none(
        feature_name=FeatureNameConst.DAILY_DISBURSEMENT_LIMIT
    )

    if daily_disbursement_limit_fs.parameters:
        daily_disbursement_limit_fs.parameters.update({"bscore": 0.8})
        daily_disbursement_limit_fs.parameters.update(
            {"transaction_method": TransactionMethodCode.all_code()}
        )

        daily_disbursement_limit_fs.save()


class Migration(migrations.Migration):
    dependencies = []

    operations = [migrations.RunPython(update_daily_disbursement_limit_fs)]
