# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-01-15 02:48
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def execute(apps, schema_editor):
	FeatureSetting.objects.get_or_create(
		is_active=False,
        feature_name=FeatureNameConst.ONBOARDING_BANK_VALIDATION_PG,
        category="onboarding_bank_validation_pg",
        description="Onboarding Validation Using PG Service"
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [migrations.RunPython(execute, migrations.RunPython.noop)]
