# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-01-20 05:01
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting
from juloserver.easy_income_upload.constants import FeatureNameConst


def create_feature_settings_easy_income_upload_file_size(apps, _schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.EASY_INCOME_UPLOAD_FILE_SIZE,
        parameters={
            'max_img_size': 2097152,
            'max_pdf_size': 25000000,
        },
        is_active=True,
        category="easy_income_upload",
        description="Easy Income Upload Image Size from Web"
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_feature_settings_easy_income_upload_file_size, migrations.RunPython.noop),
    ]
