# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-01-15 06:48
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting


def run(apps, schema_editor):
    fs = FeatureSetting.objects.filter(feature_name='dukcapil_fr_threshold').last()
    if not fs:
        FeatureSetting.objects.create(
            feature_name='dukcapil_fr_threshold',
            is_active=True,
            category='application',
            parameters={
                "j1": {
                    "high": 5,
                    "is_active": True,
                    "very_high": 9.5,
                    "timeout": 60,
                },
                "turbo": {"high": 8, "is_active": True, "medium": 7, "very_high": 9.6},
            },
            description='Dukcapil FR Scoring setting',
        )
    else:
        fs.update_safely(
            category='application',
            parameters={
                "j1": {
                    "high": 5,
                    "is_active": True,
                    "very_high": 9.5,
                    "timeout": 60,
                },
                "turbo": {"high": 8, "is_active": True, "medium": 7, "very_high": 9.6},
            },
            description='Dukcapil FR Scoring setting',
        )


class Migration(migrations.Migration):

    dependencies = []

    operations = [migrations.RunPython(run, migrations.RunPython.noop)]
