# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-01-20 08:21
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst


def update_antifraud_detokenization_timeout(apps, _schema_editor):
    feature_setting = FeatureSetting.objects.filter(
        feature_name=FeatureNameConst.ANTIFRAUD_PII_VAULT_DETOKENIZATION
    ).last()

    if feature_setting:
        feature_setting.parameters["detokenize_timeout_ms"] = 3000
        feature_setting.save()


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(update_antifraud_detokenization_timeout, migrations.RunPython.noop)
    ]
