# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-10-14 04:47
from __future__ import unicode_literals

from django.db import migrations

from juloserver.account_payment.models import CRMCustomerDetail


def edit_processed_refinancing_eligible(apps, schema_editor):
    data = CRMCustomerDetail.objects.filter(
        attribute_name='Memenuhi Syarat Refinancing', section='Detail Pembayaran'
    ).last()
    if not data:
        return

    new_params = data.parameter_model_value
    parameter_data = {
        "dom": {
        '-': '<strong> - </strong>',
        "true": """ 
        <table>
            <tr>
                <td rowspan="2"><strong>Ya</strong></td>
                <td style="padding:6px 6px 4px 4px">
                <button onclick="window.location.href = '/collection-offer-j1/?account_id=<<account_id>>'";
                style="border-color: rgb(102, 205, 246);
                color: rgb(102, 205, 246);
                background-color: white;
                border-radius: 10px;
                font-weight:bold;
                font-size: 12px; 
                cursor: pointer;">Collection Offer ></button>
                </td>
            </tr>
            <tr>
                <td style="padding:4px 6px 6px 4px">
                <button onclick="window.location.href = '/waiver/collection-offer-j1/?account_id=<<account_id>>'";
                  style="border-color: rgb(102, 205, 246);
                  color: rgb(102, 205, 246);
                  background-color: white;
                  border-radius: 10px;
                  font-weight:bold;
                  font-size: 12px;
                  cursor: pointer; width:100%;">Waiver Offer   ></button>
                </td>
            </tr>
        </table>""",
        "false": '<strong> Tidak </strong>',
        "no permission": '<strong> Ya </strong>'
                },
        "models": {"account": "model.id", "accountpayment": "model.account.id"},
        "function": "function_name(model_identifier,user)[0]",
        "default_value": "-",
        "function_name": "can_account_get_refinancing_centralized_crm",
        "function_path": "juloserver.waiver.services.account_related",
        "execution_mode": "execute_function",
    }
    data.parameter_model_value = parameter_data
    data.save()


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(edit_processed_refinancing_eligible, migrations.RunPython.noop),
    ]
