# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-01-28 06:17
from __future__ import unicode_literals

from django.db import migrations

from juloserver.partnership.constants import PartnershipFeatureNameConst
from juloserver.partnership.models import PartnershipFeatureSetting


def add_partnership_feature_setting_lender_by_partner(apps, schema_editor):
    PartnershipFeatureSetting.objects.create(
        feature_name=PartnershipFeatureNameConst.LENDER_MATCHMAKING_BY_PARTNER,
        is_active=True,
        parameters={
            'cardekho': 'Finsso',
        },
        category='partnership',
        description='partnership lender by partner config',
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(
            add_partnership_feature_setting_lender_by_partner,
            migrations.RunPython.noop,
        )
    ]
