# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-02-18 09:14
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureNameConst, FeatureSetting


def update_feature_setting_for_grab_payment_gateway_ratio(apps, schema_editor):
    try:
        feature_setting = FeatureSetting.objects.get(
            feature_name=FeatureNameConst.GRAB_PAYMENT_GATEWAY_RATIO
        )
        parameters = feature_setting.parameters or {}
        parameters.clear()
        parameters.update(
            {'doku_ratio': '0%', 'ac_ratio': '100%'},
        )
        feature_setting.save()
    except FeatureSetting.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(
            update_feature_setting_for_grab_payment_gateway_ratio, migrations.RunPython.noop
        ),
    ]
