# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-02-14 04:40
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.payment_gateway.constants import FeatureNameConst


def add_payment_gateway_fs(apps, _schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.PAYMENT_GATEWAY_RETRY_FAILED,
        is_active=True,
        parameters={'doku': {'failed_for_not_found_after_hour': 5}},
    )


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunPython(add_payment_gateway_fs, migrations.RunPython.noop),
    ]
