# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-02-17 09:23
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting
from juloserver.loan.constants import LoanFeatureNameConst
from juloserver.qris.services.feature_settings import QrisLoanEligibilitySetting


def add_minimum_loan_amount_setting_for_qris(app, schema_editor):
    new_params = {"min_requested_amount": QrisLoanEligibilitySetting.DEFAULT_MIN_LOAN_AMOUNT}

    fs = FeatureSetting.objects.filter(
        feature_name=LoanFeatureNameConst.QRIS_LOAN_ELIGIBILITY_SETTING,
    ).last()

    if fs:
        fs.parameters.update(new_params)
        fs.save()


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(
            code=add_minimum_loan_amount_setting_for_qris,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
