# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-02-11 08:30
from __future__ import unicode_literals

from django.db import migrations

from juloserver.channeling_loan.constants import FeatureNameConst, ChannelingConst
from juloserver.julo.models import FeatureSetting


def change_channeling_type_bss(apps, _schema_editor):
    fs = FeatureSetting.objects.filter(feature_name=FeatureNameConst.CHANNELING_LOAN_CONFIG).last()
    if fs:
        parameters = fs.parameters
        if parameters.get(ChannelingConst.BSS):
            parameters[ChannelingConst.BSS]['general'][
                'CHANNELING_TYPE'
            ] = ChannelingConst.MANUAL_CHANNELING_TYPE
        fs.parameters = parameters
        fs.save()


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunPython(change_channeling_type_bss, migrations.RunPython.noop),
    ]
