# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-02-13 02:20
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting
from juloserver.minisquad.constants import FeatureNameConst


def add_ineffective_phone_number_fs(apps, schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.INEFFECTIVE_PHONE_NUMBER_TO_PDS,
        is_active=True,
        description='This configuration for set ineffective phone number',
        category='collection',
        parameters=dict(
            consecutive_day=5,
            never_refresh=True,
            threshold_refresh_day=5,
            unreachable_hangup_ids=[4, 6, 7, 8, 9],
        ),
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [migrations.RunPython(add_ineffective_phone_number_fs, migrations.RunPython.noop)]
