# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-02-20 06:01
from __future__ import unicode_literals

from django.db import migrations

from juloserver.channeling_loan.models import DBSChannelingApplicationJob


def create_data_for_dbs_channeling_application_job(apps, schema_editor):
    data = [
        # ("job_industry", "job_description", is_exclude, "aml_risk_rating", "job_code", "job_industry_code")
        ("Admin / Finance / HR", "Admin", False, "Low", "06", "04"),
        ("Admin / Finance / HR", "Akuntan / Finance", False, "Medium", "06", "04"),
        ("Admin / Finance / HR", "HR", False, "Low", "06", "04"),
        ("Admin / Finance / HR", "Office Boy", False, "Low", "02", "04"),
        ("Admin / Finance / HR", "Sekretaris", False, "Low", "04", "04"),
        ("Admin / Finance / HR", "Lainnya", False, "Medium", "14", "04"),
        ("Design / Seni", "Design Grafis", False, "Low", "10", "01"),
        ("Design / Seni", "Pelukis", False, "Low", "10", "01"),
        ("Design / Seni", "Photographer", False, "Low", "09", "01"),
        ("Design / Seni", "Lainnya", True, "High", "14", "01"),
        ("Entertainment / Event", "DJ / Musisi", False, "Low", "10", "01"),
        ("Entertainment / Event", "Event Organizer", False, "Low", "14", "01"),
        ("Entertainment / Event", "Kameraman", False, "Low", "09", "01"),
        ("Entertainment / Event", "Penyanyi / Penari / Model", False, "Low", "10", "01"),
        ("Entertainment / Event", "Produser / Sutradara", False, "Low", "10", "01"),
        ("Entertainment / Event", "Lainnya", False, "Low", "14", "01"),
        ("Hukum / Security / Politik", "Anggota Pemerintahan", True, "High", "11", "08"),
        ("Hukum / Security / Politik", "Hakim / Jaksa / Pengacara", True, "High", "07", "08"),
        ("Hukum / Security / Politik", "Notaris", True, "High", "18", "08"),
        ("Hukum / Security / Politik", "Ormas", True, "High", "14", "08"),
        ("Hukum / Security / Politik", "Pemuka Agama", True, "High", "14", "08"),
        ("Hukum / Security / Politik", "Satpam", False, "Low", "14", "01"),
        ("Hukum / Security / Politik", "TNI / Polisi", True, "High", "08", "08"),
        ("Hukum / Security / Politik", "Lainnya", True, "High", "14", "08"),
        ("Kesehatan", "Apoteker", False, "Low", "03", "01"),
        ("Kesehatan", "Dokter", False, "Low", "17", "01"),
        ("Kesehatan", "Perawat", False, "Low", "03", "01"),
        ("Kesehatan", "Teknisi Laboratorium", False, "Low", "03", "01"),
        ("Kesehatan", "Lainnya", False, "Low", "03", "01"),
        ("Konstruksi / Real Estate", "Arsitek / Tehnik Sipil", False, "Low", "19", "06"),
        ("Konstruksi / Real Estate", "Interior Designer", False, "Low", "01", "06"),
        ("Konstruksi / Real Estate", "Mandor", False, "Low", "01", "06"),
        ("Konstruksi / Real Estate", "Pemborong", False, "Low", "01", "06"),
        ("Konstruksi / Real Estate", "Proyek Manager / Surveyor", False, "Low", "01", "06"),
        ("Konstruksi / Real Estate", "Real Estate Broker", True, "High", "03", "04"),
        ("Konstruksi / Real Estate", "Tukang Bangunan", False, "Low", "01", "06"),
        ("Konstruksi / Real Estate", "Lainnya", False, "Low", "01", "06"),
        ("Media", "Kameraman", False, "Low", "09", "01"),
        ("Media", "Penulis / Editor", False, "Low", "09", "01"),
        ("Media", "Wartawan", False, "Low", "09", "01"),
        ("Media", "Lainnya", False, "Low", "09", "01"),
        ("Pabrik / Gudang", "Buruh Pabrik / Gudang", False, "Low", "01", "02"),
        ("Pabrik / Gudang", "Kepala Pabrik / Gudang", False, "Low", "01", "02"),
        ("Pabrik / Gudang", "Teknisi Mesin", False, "Low", "01", "02"),
        ("Pabrik / Gudang", "Lainnya", False, "Low", "01", "02"),
        ("Pendidikan", "Dosen", False, "Low", "14", "01"),
        ("Pendidikan", "Guru", False, "Low", "14", "01"),
        ("Pendidikan", "Instruktur / Pembimbing Kursus", False, "Low", "14", "01"),
        ("Pendidikan", "Kepala Sekolah", False, "Low", "14", "01"),
        ("Pendidikan", "Tata Usaha", False, "Low", "14", "01"),
        ("Pendidikan", "Lainnya", False, "Low", "14", "01"),
        ("Perawatan Tubuh", "Fashion Designer", False, "Low", "14", "01"),
        ("Perawatan Tubuh", "Gym / Fitness", False, "Low", "13", "01"),
        ("Perawatan Tubuh", "Pelatih / Trainer", False, "Low", "13", "01"),
        ("Perawatan Tubuh", "Salon / Spa / Panti Pijat", False, "Low", "14", "01"),
        ("Perawatan Tubuh", "Lainnya", False, "Low", "14", "01"),
        ("Perbankan", "Back-office", False, "Low", "04", "04"),
        ("Perbankan", "Bank Teller", False, "Low", "04", "04"),
        ("Perbankan", "CS Bank", False, "Low", "04", "04"),
        ("Perbankan", "Credit Analyst", False, "Low", "04", "04"),
        ("Perbankan", "Kolektor", False, "Low", "22", "04"),
        ("Perbankan", "Resepsionis", False, "Low", "04", "04"),
        ("Perbankan", "Lainnya", False, "Medium", "04", "04"),
        ("Sales / Marketing", "Account Executive / Manager", False, "Low", "06", "03"),
        ("Sales / Marketing", "Salesman", False, "Low", "03", "03"),
        ("Sales / Marketing", "SPG", False, "Low", "03", "03"),
        ("Sales / Marketing", "Telemarketing", False, "Low", "03", "03"),
        ("Sales / Marketing", "Lainnya", False, "Low", "03", "03"),
        ("Service", "Customer Service", False, "Low", "04", "03"),
        ("Service", "Kasir", False, "Low", "04", "03"),
        ("Service", "Kebersihan", False, "Low", "02", "03"),
        ("Service", "Koki", False, "Low", "02", "03"),
        ("Service", "Pelayan / Pramuniaga", False, "Low", "02", "03"),
        ("Service", "Lainnya", False, "Medium", "14", "03"),
        ("Tehnik / Computer", "Engineer / Ahli Tehnik", False, "Low", "01", "03"),
        ("Tehnik / Computer", "Penulis Teknikal", False, "Low", "04", "03"),
        ("Tehnik / Computer", "Programmer / Developer", False, "Low", "04", "03"),
        ("Tehnik / Computer", "R&D / Ilmuwan / Peneliti", False, "Low", "14", "03"),
        ("Tehnik / Computer", "Warnet", False, "Low", "14", "03"),
        ("Tehnik / Computer", "Otomotif", False, "Low", "01", "03"),
        ("Tehnik / Computer", "Lainnya", False, "Low", "14", "03"),
        ("Transportasi", "Supir / Ojek", False, "Low", "01", "05"),
        ("Transportasi", "Agen Perjalanan", False, "Low", "01", "05"),
        ("Transportasi", "Kurir / Ekspedisi", False, "Low", "01", "05"),
        ("Transportasi", "Pelaut / Staff Kapal / Nahkoda Kapal", False, "Low", "12", "05"),
        ("Transportasi", "Pilot / Staff Penerbangan", False, "Low", "12", "05"),
        ("Transportasi", "Sewa Kendaraan", False, "Low", "02", "05"),
        ("Transportasi", "Masinis / Kereta Api", False, "Low", "01", "05"),
        ("Transportasi", "Lainnya", False, "Medium", "14", "05"),
        ("Staf Rumah Tangga", "Babysitter / Perawat", False, "Low", "14", "01"),
        ("Staf Rumah Tangga", "Pembantu Rumah Tangga", False, "Low", "14", "01"),
        ("Staf Rumah Tangga", "Supir", False, "Low", "01", "01"),
        ("Staf Rumah Tangga", "Tukang Kebun", False, "Low", "14", "01"),
        ("Staf Rumah Tangga", "Lainnya", False, "Low", "14", "01"),
        ("Perhotelan", "Customer Service", False, "Low", "02", "03"),
        ("Perhotelan", "Kebersihan", False, "Low", "02", "03"),
        ("Perhotelan", "Koki", False, "Low", "02", "03"),
        ("Perhotelan", "Room Service / Pelayan", False, "Low", "02", "03"),
        ("Perhotelan", "Lainnya", False, "Low", "02", "03"),
    ]

    DBSChannelingApplicationJob.objects.bulk_create(
        [
            DBSChannelingApplicationJob(
                job_industry=job_industry,
                job_description=job_description,
                is_exclude=is_exclude,
                aml_risk_rating=aml_risk_rating,
                job_code=job_code,
                job_industry_code=job_industry_code,
            )
            for job_industry, job_description, is_exclude, aml_risk_rating, job_code, job_industry_code in data
        ]
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(
            create_data_for_dbs_channeling_application_job, migrations.RunPython.noop
        ),
    ]
