# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-02-24 07:50
from __future__ import unicode_literals

from django.db import migrations

from juloserver.dana.constants import FeatureNameConst
from juloserver.partnership.models import PartnershipFeatureSetting


def add_feature_setting_cut_off_date_dana_collection(apps, schema_editor):
    feature_name = FeatureNameConst.DANA_AI_RUDDER_CUT_OFF_DATE
    fs = PartnershipFeatureSetting.objects.filter(feature_name=feature_name).last()
    if not fs:
        PartnershipFeatureSetting.objects.create(
            feature_name=FeatureNameConst.DANA_AI_RUDDER_CUT_OFF_DATE,
            is_active=False,
            parameters={"cut_off_date": "2"},
            description="Feature setting to setup cut off date dana collection for bucket assignment DPD 91+",
            category="Dana Collection",
        )


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunPython(
            add_feature_setting_cut_off_date_dana_collection,
            migrations.RunPython.noop,
        )
    ]
