# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-03-10 10:00
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def execute(apps, schema_editor):

    is_exists = FeatureSetting.objects.filter(feature_name=FeatureNameConst.ELIGIBLE_ENTRY_LEVEL_SWAPIN).exists()
    if not is_exists:
        FeatureSetting.objects.create(
            feature_name=FeatureNameConst.ELIGIBLE_ENTRY_LEVEL_SWAPIN,
            is_active=True,
            category='entry level',
            description='entry level swap in',
            parameters={},
        )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(execute, migrations.RunPython.noop),
    ]
