# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-03-11 09:31
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.referral.constants import FeatureNameConst


def create_feature_settings_top_referral_cashback(apps, _schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.TOP_REFERRAL_CASHBACKS,
        parameters={
            'message': '{customer_name} just got {amount} thousands cashback from referral!',
            'top_referral_cashbacks_limit': 20,
        },
        is_active=True,
        category="refferal",
        description="Config for message and top customer got referral cashbacks"
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_feature_settings_top_referral_cashback, migrations.RunPython.noop),
    ]
