# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-03-07 09:09
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting
from juloserver.otp.constants import FeatureSettingName


def create_otp_bypass_feature_setting(apps, schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureSettingName.OTP_BYPASS,
        parameters={},
        is_active=True,
        description='Active means otp will bypass when customer has successfully changed their PIN',
        category='otp',
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(create_otp_bypass_feature_setting),
    ]
