# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-03-06 17:18
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.account_payment.constants import FeatureNameConst


def run(apps, schema_editor):
    parameters = [
        {
            "title": "Mengapa Status Pembayaran Belum Berubah Setelah Saya Bayar Tagihan?",
            "content": 'Jika status pembayaran belum berubah, mungkin sistem JULO masih dalam proses validasi pembayaranmu. Jika dalam 1x24 jam belum berubah juga, kamu bisa klik tombol "Cek Ulang Status Pembayaran" di bawah ini, ya.',
            "type": "button",
            "order": 1,
        },
        {
            "title": "Mengapa saya masih mendapat tagihan setelah membayar lunas dengan BNI?",
            "content": "Jika kamu memilih metode pembayaran dengan BNI, kamu mungkin akan mendapat tagihan senilai Rp1 di bulan selanjutnya setelah tagihanmu lunas. Kamu abaikan saja tagihan tersebut, ya.",
            "type": "text",
            "order": 2,
        },
        {
            "title": "Bagaimana cara membayar tagihan dari bank yang belum tersedia di JULO?",
            "content": "Untuk melakukan pembayaran dengan bank pilihanmu yang saat ini belum tersedia di JULO, kamu dapat melakukan pembayaran dengan transfer VA melalui Bank Permata atau Mandiri. ",
            "type": "text",
            "order": 3,
        },
        {
            "title": "Jika saya mengaktifkan Autodebit di hari jatuh tempo tagihan, apakah tagihan saya di bulan itu langsung terdebit?",
            "content": "Jika kamu mengaktifkan fitur Autodebit di hari H jatuh tempo, fitur tersebut akan aktif untuk tagihan di bulan selanjutnya. Jadi, untuk tagihan di bulan ini, kamu masih perlu membayar secara manual, ya.",
            "type": "text",
            "order": 4,
        },
        {
            "title": "Apa saja pilihan pembayaran dengan fitur Autodebit?",
            "content": "Saat ini, kamu bisa menggunakan fitur Autodebit dengan BCA, BRI, dan GoPay. Nantinya, beberapa pembayaran lain juga akan tersedia untuk fitur Autodebit! ",
            "type": "text",
            "order": 5,
        },
        {
            "title": "Bagaimana jika saldo DANA saya tidak cukup di tanggal penarikan?",
            "content": "Mulai dari 4 Maret 2025, jika saldo DANA kamu kurang dari jumlah tagihan di tanggal penarikan, kami akan terus melakukan penarikan secara otomatis saat akun DANA kamu memiliki saldo lebih dari Rp 10 ribu dan/atau sesuai jumlah sisa tagihan. Proses ini dilakukan mulai dari H+1 (satu hari) sampai dengan H+10 (sepuluh hari) dari tanggal jatuh tempo.",
            "type": "text",
            "order": 6,
        },
    ]
    fs = FeatureSetting.objects.filter(feature_name=FeatureNameConst.REPAYMENT_FAQ_SETTING).last()
    if not fs:
        FeatureSetting.objects.create(
            feature_name=FeatureNameConst.REPAYMENT_FAQ_SETTING,
            is_active=True,
            category='account_payment',
            description='FAQ repayment contents',
            parameters=parameters,
        )
    else:
        fs.update_safely(parameters=parameters)


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(run, migrations.RunPython.noop),
    ]
