# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-03-04 08:26
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.minisquad.constants import FeatureNameConst


def add_ineffective_phone_on_task_configuration(apps, schema_editor):
    fs = FeatureSetting.objects.filter(
        feature_name=FeatureNameConst.AI_RUDDER_TASKS_STRATEGY_CONFIG
    ).last()
    if not fs:
        return

    parameters = fs.parameters
    for bucket_name, configuration in parameters.items():
        bucket_name_lower = bucket_name.lower()
        if 'grab' in bucket_name_lower or 'dana' in bucket_name_lower or 'b5' in bucket_name_lower:
            continue
        configuration.update(
            consecutive_days=5,
            is_ineffective_refresh=0,
            threshold_refresh_days=30,
            unreachable_hangup_ids=[4, 6, 7, 8, 9],
        )
        parameters.update({bucket_name: configuration})

    fs.parameters = parameters
    fs.save()


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(
            add_ineffective_phone_on_task_configuration, migrations.RunPython.noop
        ),
    ]
