# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-03-25 06:53
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting
from juloserver.streamlined_communication.models import AppDeepLink

vendor_autodebet_list = [
    ('bca_autodebet', 'BCA Autodebet'),
    ('bri_autodebet', 'BRI Autodebet'),
    ('mandiri_autodebet', 'Mandiri Autodebet'),
    ('bni_autodebet', 'BNI Autodebet'),
    ('ovo_autodebet', 'OVO Autodebet'),
]


def run(apps, schema_editor):
    for deeplink, label in vendor_autodebet_list:
        if not AppDeepLink.objects.filter(deeplink=deeplink).exists():
            AppDeepLink.objects.create(label=label, deeplink=deeplink)


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(run, migrations.RunPython.noop),
    ]
