# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-03-24 03:10
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.constants import FeatureNameConst

from juloserver.julo.models import FeatureSetting


def add_email_success_feature_setting(apps, _schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.EMAIL_PAYMENT_SUCCESS,
        parameters={
            'autodebet': {
                'dpd_start': 1,
                'dpd_end': 3,
            }
        },
        is_active=True,
        description="email payment success feature setting",
        category='repayment',
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(add_email_success_feature_setting, migrations.RunPython.noop),
    ]
