# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-03-26 07:13
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting
from juloserver.loan.constants import LoanFeatureNameConst


def add_is_hit_ana_to_ana_transaction_model_setting(apps, schema_editor):
    added_parameters = {
        "is_hitting_ana": False,
    }

    fs = FeatureSetting.objects.filter(
        feature_name=LoanFeatureNameConst.ANA_TRANSACTION_MODEL,
    ).last()

    if fs:
        fs.parameters.update(added_parameters)
        fs.save()


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(
            code=add_is_hit_ana_to_ana_transaction_model_setting,
            reverse_code=migrations.RunPython.noop,
        )
    ]
