# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-03-18 11:09
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.payment_gateway.constants import FeatureNameConst


def add_payment_gateway_fs(apps, _schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.PAYMENT_GATEWAY_CALLBACK_RETRY,
        is_active=True,
        parameters={'start_time': 24, 'end_time': 1},
    )


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunPython(add_payment_gateway_fs, migrations.RunPython.noop),
    ]
