# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-04-18 09:13
from __future__ import unicode_literals

from django.db import migrations


from juloserver.julo.models import FeatureSetting
from juloserver.loan.constants import LoanFeatureNameConst
from juloserver.loan.services.feature_settings import LockedProductPageSetting


def add_fs_locked_product_page(apps, schema_editor):
    params = {
        "locked_settings": {
            LockedProductPageSetting.MERCURY_LOCKED_SETTING: {
                "header_image_url": LockedProductPageSetting.DEFAULT_HEADER_IMAGE_URL,
                "locked_message": LockedProductPageSetting.MERCURY_LOCKED_MESSAGE,
            }
        },
        "default_header_image_url": LockedProductPageSetting.DEFAULT_HEADER_IMAGE_URL,
        "default_locked_message": LockedProductPageSetting.DEFAULT_LOCKED_MESSAGE,
    }

    FeatureSetting.objects.update_or_create(
        feature_name=LoanFeatureNameConst.LOCK_PRODUCT_PAGE,
        defaults={
            "is_active": True,
            "category": "loan",
            'description': 'Configs for lock product page',
            "parameters": params,
        },
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(
            code=add_fs_locked_product_page,
            reverse_code=migrations.RunPython.noop,
        )
    ]
