# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-04-09 05:46
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting

def change_parameters(apps, schema_editor):
    notify_dukcapil_asliri_remaining_balance_setting = FeatureSetting.objects.get_or_none(
        feature_name='notify_dukcapil_asliri_remaining_balance'
    )

    if notify_dukcapil_asliri_remaining_balance_setting:
        notify_dukcapil_asliri_remaining_balance_setting.parameters.update(
            {
                'default_threshold': 8000,
                'verify_biometric_basic': 30000
            }
        )
        notify_dukcapil_asliri_remaining_balance_setting.is_active = True
        notify_dukcapil_asliri_remaining_balance_setting.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(change_parameters)
    ]
