# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-04-11 02:56
from __future__ import unicode_literals

from django.db import migrations

from juloserver.application_flow.constants import PartnerNameConstant
from juloserver.julo.models import Partner
from juloserver.partnership.constants import PartnershipFlag
from juloserver.partnership.models import PartnershipFlowFlag


def add_dana_approval_user_config(apps, _schema_editor):
    partner = Partner.objects.filter(name=PartnerNameConstant.DANA).last()
    if partner:
        partnership_flow_flag, _ = PartnershipFlowFlag.objects.get_or_create(
            partner=partner, name=PartnershipFlag.APPROVAL_CONFIG
        )

        partnership_flow_flag.configs = {
            "verify_same_phone_number_with_existing_nik": {
                "days_threshold": 365,
                "x190_check": True,
                "is_active": True,
            }
        }

        partnership_flow_flag.save()


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunPython(add_dana_approval_user_config, migrations.RunPython.noop),
    ]
