# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-04-17 10:38
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting
from juloserver.channeling_loan.constants import FeatureNameConst


def set_mother_name_fullname_rac_checkbox_channeling_loan_configuration_fs(apps, schema_editor):
    all_channeling_loan_configuration_fs = FeatureSetting.objects.filter(
        feature_name=FeatureNameConst.CHANNELING_LOAN_CONFIG,
    ).last()

    for channeling_type, feature_setting in all_channeling_loan_configuration_fs.parameters.items():
        all_channeling_loan_configuration_fs.parameters[channeling_type]["rac"][
            "MOTHER_NAME_FULLNAME"
        ] = False

    all_channeling_loan_configuration_fs.save()


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunPython(
            set_mother_name_fullname_rac_checkbox_channeling_loan_configuration_fs,
            migrations.RunPython.noop,
        )
    ]
