# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-04-22 07:14
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.antifraud.constant.feature_setting import BinaryCheck, Holdout


def create_fs_abc_emulator_check_ios(apps, _schema_editor):
    feature_setting = FeatureSetting.objects.filter(
        feature_name='abc_emulator_check_ios'
    )

    if not feature_setting.exists():
        FeatureSetting.objects.create(
            feature_name='abc_emulator_check_ios',
            is_active=False,
            category="antifraud",
            description="Feature Flag for antifraud binary check emulator check ios",
            parameters={
                BinaryCheck.Parameter.HOLDOUT: {
                    BinaryCheck.Parameter.Holdout.TYPE: Holdout.Type.INACTIVE,
                    BinaryCheck.Parameter.Holdout.REGEX: "",
                    BinaryCheck.Parameter.Holdout.PERCENTAGE: 100,
                    BinaryCheck.Parameter.Holdout.PARTNER_IDS: [],
                }
            },
        )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(create_fs_abc_emulator_check_ios, migrations.RunPython.noop)
    ]
