# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-04-30 09:17
from __future__ import unicode_literals

from django.db import migrations


from juloserver.partnership.constants import PartnershipFeatureNameConst
from juloserver.partnership.models import PartnershipFeatureSetting


def add_feature_settings_resume_application_web_app_stuck_105(apps, schema_editor):
    PartnershipFeatureSetting.objects.get_or_create(
        feature_name=PartnershipFeatureNameConst.LEADGEN_WEBAPP_CONFIG_RESUME_STUCK_105,
        is_active=False,
        description='leadgen webapp config resume applicaton stuck 105',
        category='partnership',
    )


class Migration(migrations.Migration):

    dependencies = []
    operations = [
        migrations.RunPython(
            add_feature_settings_resume_application_web_app_stuck_105,
            migrations.RunPython.noop,
        )
    ]
