# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-05-08 04:23
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import MobileFeatureSetting
from juloserver.julo.constants import MobileFeatureNameConst
from juloserver.streamlined_communication.models import (
    StreamlinedCommunication,
    StreamlinedMessage,
    InfoCardProperty,
    InfoCardButtonProperty,
)
from django.db import transaction
from juloserver.julo.models import Image


def create_image(image_source_id, image_type, image_url):
    image = Image()
    image.image_source = image_source_id
    image.image_type = image_type
    image.url = image_url
    image.save()


def add_info_card_cashback_claim(apps, schema_editor):
    MobileFeatureSetting.objects.create(
        feature_name=MobileFeatureNameConst.BOTTOMSHEET_CONTENT_CASHBACK_CLAIM,
        is_active=True,
        parameters={
            "cashback_claim_congrats": {
                "title": "Selamat, Kamu Mendapatkan Cashback!",
                "message_image_url": "https://storage.googleapis.com/julo-campaign/collection/cashback_claim_eligible.png",
                "description_warn": "<b>Asik, kamu dapat cashback Rp{{cashback_amount}}</b>",
                "description": "<b>Klaim cashback-mu</b> sebelum kadaluwarsa lewat <b>email pembayaran berhasil,</b> ya!",
                "accept_button": "Buka Email Sekarang",
                "ignore_button": "Mengerti",
            },
            "cashback_claim_success": {
                "title": "Mantap, cashback-mu berhasil diklaim!",
                "message_image_url": "https://storage.googleapis.com/julo-campaign/collection/cashback_claim_claimed.png",
                "description": "Cashback <b>Rp{{cashback_amount}}</b> akan masuk ke dompet cashback-mu setelah pinjamanmu lunas, ya.",
                "accept_button": "Lihat Halaman Cashback",
                "ignore_button": "Mengerti",
            },
            "cashback_claim_expired": {
                "title": "Yah, Waktu Klaim Sudah Habis",
                "message_image_url": "https://storage.googleapis.com/julo-campaign/collection/cashback_claim_expired.png",
                "description": "Kamu tidak klaim cashback sebelum batas waktu berakhir. <br/>Tapi tenang aja, kamu akan dapat cashback tiap <b>bayr tagihan lebih awal.</b> Kami akan ingatkan untuk klaim, <b>langsung klaim segera,</b> ya!",
                "accept_button": "Kembali",
                "ignore_button": "",
            },
            "cashback_claim_claimed": {
                "title": "Cashback Sudah Kamu Klaim",
                "message_image_url": "https://storage.googleapis.com/julo-campaign/collection/cashback_claim_success.png",
                "description": "Kamu udah klaim cashback sebesar <b>Rp{{cashback_amount}}</b>. Cashback-nya akan masuk ke dompet cashback kamu setelah seluruh tagihanmu lunas, ya.",
                "accept_button": "Buka Email Sekarang",
                "ignore_button": "Mengerti",
            },
        },
    )
    infocard_data = {
        "streamlined_communication": {
            "status_code_id": None,
            "status": None,
            "dpd": None,
            "communication_platform": "INFO_CARD",
            "message_id": None,
            "description": None,
            "criteria": None,
            "template_code": "j1_cashback_claim",
            "moengage_template_code": None,
            "ptp": None,
            "is_active": True,
            "product": None,
            "type": None,
            "attempts": None,
            "time_sent": None,
            "call_hours": [],
            "function_name": [],
            "is_automated": True,
            "time_out_duration": 3,
            "heading_title": None,
            "subject": None,
            "pre_header": None,
            "exclude_risky_customer": False,
            "extra_conditions": 'CASHBACK_CLAIM',
            "dpd_lower": None,
            "dpd_upper": None,
            "until_paid": False,
            "expiration_option": None,
            "expiry_period": None,
            "expiry_period_unit": None,
            "show_in_web": False,
            "show_in_android": True,
            "partner_id": None,
            "partner_selection_list": [],
            "partner_selection_action": None,
        },
        "streamlined_message": {
            "message_content": "",
            "parameter": [None],
            "info_card_property_id": None,
        },
        "infocard_property": {
            "card_type": "1",
            "card_action": "webpage",
            "card_destination": "https://view.julo.co.id/coll/cashback-claim?token=",
            "card_order_number": 1,
            "title": "",
            "title_color": "#ffffff",
            "text_color": "#ffffff",
        },
        "infocard_button_property": [
            {
                "info_card_property_id": None,
                "button_name": "",
                "text": "",
                "text_color": "#ffffff",
                "action_type": "",
                "destination": "",
            }
        ],
        "image": [
            {
                "image_source": 111,
                "image_type": "CARD_BACKGROUND_IMAGE",
                "url": "info-card/cashback_claim_infocard.png",
                "thumbnail_url": "",
                "service": "oss",
                "image_status": 0,
                "image": "",
            },
        ],
    }
    with transaction.atomic():
        info_card_property = InfoCardProperty.objects.create(**infocard_data["infocard_property"])
        for button_property in infocard_data["infocard_button_property"]:
            button_property["info_card_property_id"] = info_card_property.id
            InfoCardButtonProperty.objects.create(**button_property)
        for image in infocard_data['image']:
            create_image(info_card_property.id, image['image_type'], image['url'])
        infocard_data["streamlined_message"]["info_card_property_id"] = info_card_property.id
        message = StreamlinedMessage.objects.create(**infocard_data["streamlined_message"])
        infocard_data["streamlined_communication"]["message_id"] = message.id
        StreamlinedCommunication.objects.create(**infocard_data["streamlined_communication"])


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunPython(
            add_info_card_cashback_claim,
            migrations.RunPython.noop,
        )
    ]
