# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-05-05 03:19
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst


def add_feature_setting_cashback_drawer_encouragement(apps, schema_editor):
    FeatureSetting.objects.get_or_create(
        feature_name=FeatureNameConst.CASHBACK_DRAWER_ENCOURAGEMENT,
        is_active=False,
        description="Cashback drawer encouragement Content and DPD setting",
        category='cashback',
        parameters={
            "image": {"image_id": None, "image_url": "", "image_type": ""},
            "dpd": [],
            "cta": None,
            "subtitle": "Masih bingung gunakan cashback untuk apa?<br>Buat ringankan kamu bayar tagihan aja! Yuk, gunakan sekarang!",
            "title": "Ayo, Gunakan Saldo Cashback-mu!",
        },
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(
            add_feature_setting_cashback_drawer_encouragement, migrations.RunPython.noop
        ),
    ]
