# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-05-23 09:43
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting
from juloserver.followthemoney.models import LenderCurrent


def run(apps, schema_editor):
    all_stg_lender_id = list(LenderCurrent.objects.order_by('-id').values_list('id', flat=True))

    # Get or create the instance
    feature_setting, created = FeatureSetting.objects.get_or_create(
        feature_name=FeatureNameConst.LENDER_ID_NOT_ELIGIBLE_FOR_PAYDATE_CHANGE,
        is_active=True,
        description='Lender of lender ids that is not eligible for paydate change',
        category='collection',
        parameters={
            'lender_ids': all_stg_lender_id,
        },
    )

    # If it wasn't created, update it
    if not created:
        feature_setting.is_active = True
        feature_setting.description = 'Lender of lender ids that is not eligible for paydate change'
        feature_setting.category = 'collection'
        feature_setting.parameters = {'lender_ids': all_stg_lender_id}
        feature_setting.save()


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(run, migrations.RunPython.noop),
    ]
