# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-05-19 10:00
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.antifraud.constant.feature_setting import BinaryCheck, Holdout
from juloserver.julo.constants import FeatureNameConst


def create_fs_abc_trust_guard_ios(apps, _schema_editor):
    feature_setting = FeatureSetting.objects.filter(
        feature_name=FeatureNameConst.ABC_TRUST_GUARD_IOS
    )

    if not feature_setting.exists():
        FeatureSetting.objects.create(
            feature_name=FeatureNameConst.ABC_TRUST_GUARD_IOS,
            is_active=False,
            category="antifraud",
            description="Feature Flag for antifraud binary check trust guard ios",
            parameters={
                BinaryCheck.Parameter.HOLDOUT: {
                    BinaryCheck.Parameter.Holdout.TYPE: Holdout.Type.INACTIVE,
                    BinaryCheck.Parameter.Holdout.REGEX: "",
                    BinaryCheck.Parameter.Holdout.PERCENTAGE: 100,
                    BinaryCheck.Parameter.Holdout.PARTNER_IDS: [],
                }
            },
        )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(create_fs_abc_trust_guard_ios, migrations.RunPython.noop)
    ]
