# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-05-20 04:08
from __future__ import unicode_literals

from django.db import migrations

from juloserver.partnership.constants import PartnershipFeatureNameConst
from juloserver.partnership.models import PartnershipFeatureSetting


def add_feature_settings_pg_service_enablement(apps, schema_editor):
    PartnershipFeatureSetting.objects.get_or_create(
        feature_name=PartnershipFeatureNameConst.MFSP_PG_SERVICE_ENABLEMENT,
        is_active=False,
        description='enablement mfsp disbursement using pg service',
        category='partnership',
    )


class Migration(migrations.Migration):

    dependencies = []
    operations = [
        migrations.RunPython(
            add_feature_settings_pg_service_enablement,
            migrations.RunPython.noop,
        )
    ]
