# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-05-23 02:40
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst, ApplicationStatusCodes
from juloserver.registration_flow.constants import StatusCrossDevices


def run(apps, schema_editor):

    setting = FeatureSetting.objects.filter(feature_name=FeatureNameConst.CROSS_OS_LOGIN).last()
    if not setting:
        return

    new_parameters = setting.parameters
    new_parameters.update(
        {
            StatusCrossDevices.KEY_EXPIRY_STATUS_CODE: [
                ApplicationStatusCodes.FORM_PARTIAL_EXPIRED,
                ApplicationStatusCodes.APPLICATION_DENIED,
                ApplicationStatusCodes.RESUBMISSION_REQUEST_ABANDONED,
                ApplicationStatusCodes.CUSTOMER_ON_DELETION,
                ApplicationStatusCodes.CUSTOMER_DELETED,
                ApplicationStatusCodes.APPLICATION_FLAGGED_FOR_FRAUD,
            ]
        }
    )
    setting.update_safely(parameters=new_parameters)


class Migration(migrations.Migration):

    dependencies = []

    operations = [migrations.RunPython(run, migrations.RunPython.noop)]
