# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-05-16 08:09
from __future__ import unicode_literals
from django.db import migrations

from juloserver.julo.constants import WorkflowConst
from juloserver.julo.models import (
    StatusLookup,
    Workflow,
    WorkflowStatusNode,
    WorkflowStatusPath,
)
from juloserver.julo.statuses import ApplicationStatusCodes


def ios_x124(*args):
    ios_workflow = Workflow.objects.get(name=WorkflowConst.JULO_ONE_IOS)

    WorkflowStatusNode.objects.get_or_create(
        status_node=ApplicationStatusCodes.VERIFICATION_CALLS_SUCCESSFUL,
        handler='JuloOneIOS124Handler',
        workflow=ios_workflow
    )

    paths = [
        (
            ApplicationStatusCodes.SCRAPED_DATA_VERIFIED,
            ApplicationStatusCodes.VERIFICATION_CALLS_SUCCESSFUL
        ),
        (
            ApplicationStatusCodes.VERIFICATION_CALLS_SUCCESSFUL,
            ApplicationStatusCodes.APPLICANT_CALLS_SUCCESSFUL
        ),
    ]

    for path in paths:
        query = {
            'workflow': ios_workflow,
            'status_previous': path[0],
            'status_next': path[1]
        }
        exists = WorkflowStatusPath.objects.filter(**query).exists()
        if not exists:
            WorkflowStatusPath.objects.create(**query)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(ios_x124, migrations.RunPython.noop),
    ]
