# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-05-19 04:44
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting
from juloserver.julo.constants import FeatureNameConst


def add_feature_setting_qris_landing_page(apps, schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.QRIS_LANDING_PAGE_CONFIG,
        parameters={
            "faq_link": "https://www.julo.co.id/faq/faq-julo-ponsel-plus",
            "banner_image_link": "https://julostatics.oss-ap-southeast-5.aliyuncs.com/qris_1/config_page/1080x480.png"
        },
        is_active=True,
        description='qris landing page config',
        category='qris'
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            add_feature_setting_qris_landing_page, migrations.RunPython.noop),
    ]
