# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-05-27 08:24
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting
from juloserver.loan.constants import LoanFeatureNameConst


def add_adjust_due_date_mapping_fs(app, schema_editor):
    parameters = {
        "auto_adjust_due_date_mapping": {
            '26': 1,
            '27': 1,
            '28': 1,
            '29': 2,
            '30': 2,
            '31': 2
        },
        "whitelist": {
            "is_active": False,
            "last_customer_digit": {'from': '00', 'to': '99'},
            "customer_ids": []
        }
    }
    FeatureSetting.objects.create(
        feature_name=LoanFeatureNameConst.AUTO_ADJUST_DUE_DATE,
        category="loan",
        description="Mapping for auto adjust due date on payment",
        is_active=False,
        parameters=parameters,
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            add_adjust_due_date_mapping_fs, migrations.RunPython.noop,
        ),
    ]
