# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-05-24 15:11
from __future__ import unicode_literals

from django.db import migrations
from juloserver.account.models import PaymentMethodMapping

mapping = [
    "Bank CIMB Niaga",
    "Autodebet BNI",
    "Gopay",
    "efishery",
    "fishlog",
    "Bank MAYBANK",
    "Doku",
    "DANA Biller",
    "DANA_MANUAL_USER",
    "GoPay Tokenization",
    "efishery kabayan lite",
    "Autodebet BCA",
    "Autodebet DANA",
    "Bank BNI",
    "gojektsel",
    "INDOMARET",
    "Autodebet GOPAY",
    "ALFAMART",
    "Autodebet MANDIRI",
    "Autodebet OVO",
    "Bank BRI",
    "Autodebet BRI",
    "PERMATA Bank",
    "efishery kabayan reguler",
    "gaji gesa",
    "OVO",
    "DANA",
    "OVO Tokenization",
    "OneKlik BCA",
    "Bank MANDIRI",
    "Bank BCA",
    "efishery jawara",
]


def add_base_payment_method_mapping(apps, schema_editor):
    for payment_method in mapping:
        PaymentMethodMapping.objects.create(
            payment_method_name=payment_method, visible_payment_method_name=payment_method
        )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(
            add_base_payment_method_mapping,
            migrations.RunPython.noop,
        )
    ]
