# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-06-10 06:55
from __future__ import unicode_literals

from django.db import migrations

from juloserver.dana.constants import DanaBucket
from juloserver.julo.models import FeatureSetting
from juloserver.minisquad.constants import FeatureNameConst


def update_dana_dialing_order(apps, schema_editor):
    feature_group_mapping_config = FeatureSetting.objects.filter(
        feature_name=FeatureNameConst.AI_RUDDER_TASKS_STRATEGY_CONFIG
    ).last()

    if not feature_group_mapping_config:
        return

    dana_bucket = DanaBucket.DANA_BUCKET_AIRUDDER
    params = feature_group_mapping_config.parameters
    strategy_config = params.get(dana_bucket, {})

    if not strategy_config:
        return

    timeframes = strategy_config.get("timeFrames", [])
    if not timeframes or not isinstance(timeframes, list):
        return

    updated_call_list = ["mobile_phone_1_2", "mobile_phone_1_3", "mobile_phone_1_4"]
    for timeframe in timeframes:
        if isinstance(timeframe, dict) and "callList" in timeframe:
            timeframe["callList"] = updated_call_list

    strategy_config["timeFrames"] = timeframes
    params[dana_bucket] = strategy_config
    feature_group_mapping_config.parameters = params
    feature_group_mapping_config.save()


class Migration(migrations.Migration):

    dependencies = []

    operations = [migrations.RunPython(update_dana_dialing_order, migrations.RunPython.noop)]
