# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-06-09 07:21
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def execute(apps, schema_editor):
    is_exist = FeatureSetting.objects.filter(
        feature_name=FeatureNameConst.IDFY_NFS_DEPENDENCY
    ).exists()
    if not is_exist:
        FeatureSetting.objects.create(
            feature_name=FeatureNameConst.IDFY_NFS_DEPENDENCY,
            category='application',
            is_active=False,
            description='Configuration for NFS dependency on IDFY callback',
            parameters={},
        )



class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(execute, migrations.RunPython.noop),
    ]
