# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-09-23 03:33
from __future__ import unicode_literals

from django.db import migrations

from juloserver.partnership.constants import PartnershipFeatureNameConst
from juloserver.partnership.models import PartnershipFeatureSetting


def add_dana_repayment_version_feature_setting(apps, schema_editor):
    dana_repayment_fs = PartnershipFeatureSetting.objects.filter(
        feature_name=PartnershipFeatureNameConst.DANA_REPAYMENT_VERSION,
    ).first()
    if not dana_repayment_fs:
        PartnershipFeatureSetting.objects.create(
            feature_name=PartnershipFeatureNameConst.DANA_REPAYMENT_VERSION,
            is_active=True,
            parameters={},
            description="Determine the version of repayment function",
        )


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunPython(
            add_dana_repayment_version_feature_setting,
            migrations.RunPython.noop,
        )
    ]
