# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-06-16 05:55
from __future__ import unicode_literals

from django.db import migrations
from juloserver.julo.constants import FeatureNameConst
from juloserver.julo.models import FeatureSetting


def execute(apps, schema_editor):
	FeatureSetting.objects.get_or_create(
		is_active=True,
        feature_name=FeatureNameConst.ORION_FDC_LIMIT_GENERATION,
        category="orion_fdc_limit_generation",
        description="Orion FDC Limit Generation"
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [migrations.RunPython(execute, migrations.RunPython.noop)]
