---

- name: Create the folder for the celery scripts
  file: path={{ celery_scripts_dir }}
        owner={{ celery_user }}
        group={{ celery_group }}
        mode=0774
        state=directory
  tags:
    - celery

- name: Create the {{ celery_worker_name }} script file
  template: src={{ celery_worker_template_file }}
            dest={{ celery_scripts_dir }}/{{ celery_worker_name }}_start
            owner={{ celery_user }}
            group={{ celery_group }}
            mode=0755
  tags:
    - celery

- name: Create the {{ celery2_worker_name }} script file
  template: src={{ celery2_worker_template_file }}
            dest={{ celery_scripts_dir }}/{{ celery2_worker_name }}_start
            owner={{ celery_user }}
            group={{ celery_group }}
            mode=0755
  tags:
    - celery

- name: Create the {{ celery_beat_name }} script file
  template: src={{ celery_beat_template_file }}
            dest={{ celery_scripts_dir }}/{{ celery_beat_name }}_start
            owner={{ celery_user }}
            group={{ celery_group }}
            mode=0755
  tags:
    - celery
