---

- include: copy_scripts.yml

- include: setup_supervisor.yml

- name: Check running applications managed by supervisor
  shell: supervisorctl status
  register: supervisor_applications
  tags:
    - celery
    - deploy

- name: Restart the {{ celery_worker_name }} app
  supervisorctl: name={{ celery_worker_name }} state=restarted
  when: supervisor_applications.stdout.find('{{ celery_worker_name }}') != -1
  tags:
    - celery
    - deploy

- name: Restart the {{ celery2_worker_name }} app
  supervisorctl: name={{ celery2_worker_name }} state=restarted
  when: supervisor_applications.stdout.find('{{ celery2_worker_name }}') != -1
  tags:
    - celery
    - deploy

- name: Restart the {{ celery_beat_name }} app
  supervisorctl: name={{ celery_beat_name }} state=restarted
  when: supervisor_applications.stdout.find('{{ celery_beat_name }}') != -1
  tags:
    - celery
    - deploy
