# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-09-02 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SdBpjsProfile',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='sd_bpjs_profile_id', primary_key=True, serialize=False)),
                ('birthday', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('kpj', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('real_name', models.TextField(blank=True, null=True)),
                ('identity_number', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('customer_id', models.BigIntegerField(blank=True, null=True)),
                ('application_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '"ana"."sd_bpjs_profile"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BpjsTask',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='bpjs_task_id', primary_key=True, serialize=False)),
                ('data_source', models.TextField(blank=True, null=True)),
                ('task_id', models.TextField(blank=True, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bpjs_task',
            },
        ),
        migrations.CreateModel(
            name='BpjsTaskEvent',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='bpjs_task_event_id', primary_key=True, serialize=False)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('bpjs_task', models.ForeignKey(db_column='bpjs_task_id', on_delete=django.db.models.deletion.DO_NOTHING, to='bpjs.BpjsTask')),
            ],
            options={
                'db_table': 'bpjs_task_event',
            },
        ),
    ]
