# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-07-31 11:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import juloserver.julo.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE promo_history ALTER COLUMN loan_id TYPE bigint;"
        ),
        migrations.RunSQL(
            "ALTER TABLE promo_history ALTER COLUMN customer_id TYPE bigint;"
        )
    ]
