# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-09-02 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecordUrl',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='call_record_url_id', primary_key=True, serialize=False)),
                ('conversation_uuid', models.CharField(max_length=100)),
                ('recording_uuid', models.CharField(max_length=100)),
                ('rec_start_time', models.DateTimeField(blank=True, null=True)),
                ('rec_end_time', models.DateTimeField(blank=True, null=True)),
                ('recording_url', models.CharField(max_length=200)),
                ('is_upload_to_oss', models.BooleanField(default=False)),
                ('oss_file_url', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'call_record_url',
            },
        ),
    ]
