# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-08-01 13:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE collection_agent_task ALTER COLUMN loan_id TYPE bigint;"
        ),
        migrations.RunSQL(
            "ALTER TABLE collection_agent_task ALTER COLUMN payment_id TYPE bigint;"
        )
    ]
