# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-09-02 08:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMBucketColor',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='crm_bucket_color_id', primary_key=True, serialize=False)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('content_color', models.CharField(blank=True, max_length=7, null=True)),
                ('color_name', models.CharField(blank=True, max_length=20, null=True)),
                ('display_text', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'ordering': ('display_text',),
                'db_table': 'crm_bucket_color',
            },
        ),
        migrations.CreateModel(
            name='CRMBucketStatusColor',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='crm_bucket_status_color_id', primary_key=True, serialize=False)),
                ('status_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.CRMBucketColor')),
            ],
            options={
                'ordering': ('status_code',),
                'db_table': 'crm_bucket_status_color',
            },
        ),
        migrations.CreateModel(
            name='CRMSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_select', models.CharField(blank=True, max_length=60, null=True)),
                ('role_default', models.CharField(blank=True, max_length=60, null=True)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'CRM Settings',
            },
        ),
    ]
