# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-09-02 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivyCustomerData',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='privy_customer_data_id', primary_key=True, serialize=False)),
                ('privy_id', models.CharField(blank=True, max_length=50, null=True)),
                ('privy_customer_token', models.CharField(max_length=100, unique=True)),
                ('privy_customer_status', models.CharField(blank=True, max_length=50, null=True)),
                ('reject_reason', models.CharField(blank=True, max_length=150, null=True)),
                ('customer', models.OneToOneField(db_column='customer_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Customer')),
            ],
            options={
                'db_table': 'privy_customer_data',
            },
        ),
        migrations.CreateModel(
            name='PrivyDocumentData',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='privy_document_data_id', primary_key=True, serialize=False)),
                ('privy_document_token', models.CharField(max_length=100, unique=True)),
                ('privy_document_status', models.CharField(blank=True, max_length=50, null=True)),
                ('privy_document_url', models.CharField(blank=True, max_length=100, null=True)),
                ('application_id', models.OneToOneField(db_column='application_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Application')),
                ('privy_customer', models.ForeignKey(db_column='privy_customer_data_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo_privyid.PrivyCustomerData')),
            ],
            options={
                'db_table': 'privy_document_data',
            },
        ),
    ]
