# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-09-02 08:34
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CootekConfiguration',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='cootek_configuration_id', primary_key=True, serialize=False)),
                ('strategy_name', models.CharField(default=None, max_length=200)),
                ('task_type', models.CharField(default=None, max_length=200, null=True)),
                ('criteria', models.CharField(blank=True, choices=[('Refinancing_Pending', 'Refinancing Pending (4)')], max_length=200, null=True)),
                ('dpd_condition', models.CharField(blank=True, choices=[('Exactly', 'Exactly on this dpd'), ('Range', 'Dpd range'), ('Less', 'Less than this dpd')], default='Exactly', max_length=200, null=True, verbose_name='called_at')),
                ('called_at', models.IntegerField(blank=True, null=True, verbose_name='From')),
                ('called_to', models.IntegerField(blank=True, null=True, verbose_name='To')),
                ('time_to_start', models.TimeField()),
                ('time_to_prepare', models.TimeField(blank=True, null=True)),
                ('time_to_query_result', models.TimeField(blank=True, null=True)),
                ('number_of_attempts', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=200)),
                ('tag_status', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=None, null=True, size=None)),
                ('from_previous_cootek_result', models.BooleanField(default=True)),
                ('product', models.CharField(default=None, max_length=10, null=True)),
                ('exclude_risky_customer', models.BooleanField(default=False, verbose_name='Exclude isrisky dpd- ?')),
                ('loan_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=None, null=True, size=None)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cootek_configuration',
            },
        ),
        migrations.CreateModel(
            name='CootekRobot',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='cootek_robot_id', primary_key=True, serialize=False)),
                ('robot_identifier', models.CharField(default=None, max_length=200, null=True)),
                ('robot_name', models.CharField(default=None, max_length=200, null=True)),
            ],
            options={
                'db_table': 'cootek_robot',
            },
        ),
        migrations.AddField(
            model_name='cootekconfiguration',
            name='cootek_robot',
            field=models.ForeignKey(blank=True, db_column='cootek_robot_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cootek.CootekRobot'),
        ),
    ]
