# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-12-11 09:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE commission_lookup ALTER COLUMN payment_id TYPE bigint;"
        )
    ]
