# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-06-25 07:05
from __future__ import unicode_literals

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import juloserver.julo.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            sql=r'CREATE INDEX "customer_email_upper_idx" ON "customer" (UPPER("email"));',
            reverse_sql=r'DROP INDEX "customer_email_upper_idx";'
        ),
    ]
