# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-09-18 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='partneroriginationdata',
            name='id',
            field=models.IntegerField(db_column='partner_origination_data_id', primary_key=True, serialize=False, verbose_name='partner origination data id'),
        ),
    ]
