# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-09-23 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='globalpaymentmethod',
            name='payment_method_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
