# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-09-17 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='productlookup',
            name='admin_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
