# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-09-23 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='streamlinedcommunication',
            name='pre_header',
            field=models.TextField(blank=True, null=True),
        ),
    ]
