# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-10-01 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='affordabilityhistory',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
