# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-10-06 10:29
from __future__ import unicode_literals

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccountCategory',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='bank_account_category_id', primary_key=True, serialize=False)),
                ('category', models.TextField()),
                ('parent_category', models.ForeignKey(db_column='parent_category_id', on_delete=django.db.models.deletion.DO_NOTHING, to='customer_module.BankAccountCategory')),
            ],
            options={
                'db_table': 'bank_account_category',
            },
        ),
        migrations.CreateModel(
            name='BankAccountDestination',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='bank_account_destination_id', primary_key=True, serialize=False)),
                ('account_number', models.TextField()),
                ('is_deleted', models.NullBooleanField()),
                ('bank', models.ForeignKey(db_column='bank_lookup_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.BankLookup')),
                ('bank_account_category', models.ForeignKey(db_column='bank_account_category_id', on_delete=django.db.models.deletion.DO_NOTHING, to='customer_module.BankAccountCategory')),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Customer')),
                ('name_bank_validation', models.ForeignKey(db_column='name_bank_validation_id', on_delete=django.db.models.deletion.DO_NOTHING, to='disbursement.NameBankValidation')),
            ],
            options={
                'db_table': 'bank_account_destination',
            },
        ),
        migrations.CreateModel(
            name='CustomerLimit',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='customer_limit_id', primary_key=True, serialize=False)),
                ('max_limit', models.BigIntegerField(default=0)),
                ('customer', models.OneToOneField(db_column='customer_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Customer')),
            ],
            options={
                'db_table': 'customer_limit',
            },
        ),
        migrations.CreateModel(
            name='CustomerLimitHistory',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='customer_limit_history_id', primary_key=True, serialize=False)),
                ('field_name', models.TextField()),
                ('value_old', models.BigIntegerField(blank=True, null=True)),
                ('value_new', models.BigIntegerField()),
                ('customer_limit', models.ForeignKey(db_column='customer_limit_id', on_delete=django.db.models.deletion.DO_NOTHING, to='customer_module.CustomerLimit')),
            ],
            options={
                'db_table': 'customer_limit_history',
            },
        ),
        migrations.CreateModel(
            name='CustomerStatusHistory',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='customer_status_history_id', primary_key=True, serialize=False)),
                ('change_reason', models.TextField()),
                ('changed_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Customer')),
                ('status_new', models.ForeignKey(db_column='status_new', on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_status_history_new', to='julo.StatusLookup')),
                ('status_old', models.ForeignKey(blank=True, db_column='status_old', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_status_history_old', to='julo.StatusLookup')),
            ],
            options={
                'db_table': 'customer_status_history',
            },
        ),
    ]
