# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-10-06 10:29
from __future__ import unicode_literals

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='account_id', primary_key=True, serialize=False)),
                ('cycle_day', models.IntegerField()),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='AccountLimit',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='account_limit_id', primary_key=True, serialize=False)),
                ('max_limit', models.BigIntegerField(default=0)),
                ('set_limit', models.BigIntegerField(default=0)),
                ('available_limit', models.BigIntegerField(default=0)),
                ('used_limit', models.BigIntegerField(default=0)),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.DO_NOTHING, to='account.Account')),
                ('latest_affordability_history', models.ForeignKey(db_column='latest_affordability_history_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.AffordabilityHistory')),
                ('latest_credit_score', models.ForeignKey(db_column='latest_credit_score_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.CreditScore')),
            ],
            options={
                'db_table': 'account_limit',
            },
        ),
        migrations.CreateModel(
            name='AccountLimitHistory',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='account_limit_history_id', primary_key=True, serialize=False)),
                ('field_name', models.TextField()),
                ('value_old', models.BigIntegerField(blank=True, null=True)),
                ('value_new', models.BigIntegerField()),
                ('account_limit', models.ForeignKey(db_column='account_limit_id', on_delete=django.db.models.deletion.DO_NOTHING, to='account.AccountLimit')),
                ('affordability_history', models.ForeignKey(db_column='affordability_history_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.AffordabilityHistory')),
                ('credit_score', models.ForeignKey(db_column='credit_score_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.CreditScore')),
            ],
            options={
                'db_table': 'account_limit_history',
            },
        ),
        migrations.CreateModel(
            name='AccountLookup',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='account_lookup_id', primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('payment_frequency', models.TextField()),
                ('partner', models.ForeignKey(db_column='partner_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Partner')),
                ('workflow', models.ForeignKey(db_column='workflow_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Workflow')),
            ],
            options={
                'db_table': 'account_lookup',
            },
        ),
        migrations.CreateModel(
            name='AccountStatusHistory',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='account_status_history_id', primary_key=True, serialize=False)),
                ('change_reason', models.TextField()),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.DO_NOTHING, to='account.Account')),
                ('changed_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('status_new', models.ForeignKey(db_column='status_new', on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_status_history_new', to='julo.StatusLookup')),
                ('status_old', models.ForeignKey(blank=True, db_column='status_old', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_status_history_old', to='julo.StatusLookup')),
            ],
            options={
                'db_table': 'account_status_history',
            },
        ),
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='account_transaction_id', primary_key=True, serialize=False)),
                ('transaction_date', models.DateTimeField()),
                ('accounting_date', models.DateTimeField()),
                ('transaction_amount', models.BigIntegerField()),
                ('transaction_type', models.TextField()),
                ('towards_principal', models.BigIntegerField()),
                ('towards_interest', models.BigIntegerField()),
                ('towards_latefee', models.BigIntegerField()),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.DO_NOTHING, to='account.Account')),
                ('disbursement', models.OneToOneField(db_column='disbursement_id', on_delete=django.db.models.deletion.DO_NOTHING, to='disbursement.Disbursement')),
                ('payback_transaction', models.OneToOneField(db_column='payback_transaction_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.PaybackTransaction')),
            ],
            options={
                'db_table': 'account_transaction',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='account_lookup',
            field=models.ForeignKey(db_column='account_lookup_id', on_delete=django.db.models.deletion.DO_NOTHING, to='account.AccountLookup'),
        ),
        migrations.AddField(
            model_name='account',
            name='customer',
            field=models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Customer'),
        ),
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.ForeignKey(db_column='status_code', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.StatusLookup'),
        ),
    ]
