# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-10-06 10:29
from __future__ import unicode_literals

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPayment',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='account_payment_id', primary_key=True, serialize=False)),
                ('due_date', models.DateField()),
                ('due_amount', models.BigIntegerField(default=0)),
                ('principal_amount', models.BigIntegerField(default=0)),
                ('interest_amount', models.BigIntegerField(default=0)),
                ('late_fee_amount', models.BigIntegerField(default=0)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('paid_amount', models.BigIntegerField(default=0)),
                ('paid_principal', models.BigIntegerField(default=0)),
                ('paid_interest', models.BigIntegerField(default=0)),
                ('paid_late_fee', models.BigIntegerField(default=0)),
                ('late_fee_applied', models.IntegerField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.DO_NOTHING, to='account.Account')),
                ('locked_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(db_column='status_code', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.StatusLookup')),
            ],
            options={
                'db_table': 'account_payment',
            },
        ),
        migrations.CreateModel(
            name='AccountPaymentLockHistory',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='account_payment_lock_history_id', primary_key=True, serialize=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('account_payment', models.ForeignKey(db_column='account_payment_id', on_delete=django.db.models.deletion.DO_NOTHING, to='account_payment.AccountPayment')),
                ('user_id', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_payment_lock_history',
            },
        ),
        migrations.CreateModel(
            name='AccountPaymentNote',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='account_payment_note_id', primary_key=True, serialize=False)),
                ('note_text', models.TextField()),
            ],
            options={
                'db_table': 'account_payment_note',
            },
        ),
        migrations.CreateModel(
            name='AccountPaymentStatusHistory',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='account_payment_status_history_id', primary_key=True, serialize=False)),
                ('change_reason', models.TextField()),
                ('account_payment', models.ForeignKey(db_column='account_payment_id', on_delete=django.db.models.deletion.DO_NOTHING, to='account_payment.AccountPayment')),
                ('changed_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('status_new', models.ForeignKey(db_column='status_new', on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_payment_status_history_new', to='julo.StatusLookup')),
                ('status_old', models.ForeignKey(blank=True, db_column='status_old', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_payment_status_history_old', to='julo.StatusLookup')),
            ],
            options={
                'db_table': 'account_payment_status_history',
            },
        ),
        migrations.AddField(
            model_name='accountpaymentnote',
            name='account_payment_status_history',
            field=models.ForeignKey(db_column='account_payment_status_history_id', on_delete=django.db.models.deletion.DO_NOTHING, to='account_payment.AccountPaymentStatusHistory'),
        ),
        migrations.AddField(
            model_name='accountpaymentnote',
            name='added_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
