# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-10-12 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='subbucket',
            name='sub_bucket',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
