# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-09-28 03:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RenameField(
            model_name='ocrimagetranscription',
            old_name='raw_confidence_score',
            new_name='raw_transcription_conf_scores'
        ),
        migrations.AddField(
            model_name='ocrimagetranscription',
            name='raw_transcription',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ocrimageobject',
            name='x_max',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ocrimageobject',
            name='x_min',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ocrimageobject',
            name='y_max',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ocrimageobject',
            name='y_min',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ocrimagetranscription',
            name='eligible',
            field=models.BooleanField(default=None),
        ),
    ]
