# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-10-14 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerSignatureMode',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='partner_signature_mode_id', primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('partner', models.ForeignKey(db_column='partner_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Partner')),
            ],
            options={
                'db_table': 'partner_signature_mode',
            },
        ),
        migrations.CreateModel(
            name='PartnerSignatureModeHistory',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='partner_signature_mode_history_id', primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('partner_signature_mode', models.ForeignKey(blank=True, db_column='partner_signature_mode_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.PartnerSignatureMode')),
            ],
            options={
                'db_table': 'partner_signature_mode_history',
            },
        ),
        migrations.AddField(
            model_name='signaturemethodhistory',
            name='partner_id',
            field=models.ForeignKey(blank=True, db_column='partner_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Partner'),
        ),
        migrations.AddField(
            model_name='signaturevendorlog',
            name='partner_id',
            field=models.ForeignKey(blank=True, db_column='partner_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Partner'),
        ),
    ]
