# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-10-15 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='emailhistory',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smshistory',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smshistory',
            name='message_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='smshistory',
            name='message_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smshistory',
            name='phone_number_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
