# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-10-15 11:10
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrimagetranscription',
            name='raw_transcription_conf_scores',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
