# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-10-15 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='address_same_as_ktp',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='applicationoriginal',
            name='address_same_as_ktp',
            field=models.NullBooleanField(),
        ),
    ]
