# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-10-13 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import juloserver.pn_delivery.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PNBlast',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('xid', models.UUIDField(db_column='pn_blast_xid', default=uuid.uuid4, editable=False)),
                ('schedule_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('pn_blast_id', models.AutoField(db_column='pn_blast_id', primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('name', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.TextField()),
                ('content', models.TextField()),
                ('data', models.FileField(blank=True, upload_to=juloserver.pn_delivery.models.get_pn_local_path)),
                ('remote_filepath', models.CharField(blank=True, max_length=200)),
                ('remote_bucket_name', models.CharField(blank=True, max_length=100)),
                ('redirect_page', models.IntegerField(db_column='pn_redirect_page_id')),
            ],
            options={
                'db_table': '"msg"."pn_blast"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PNBlastEvent',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(db_column='pn_blast_event_id', primary_key=True, serialize=False)),
                ('status', models.TextField()),
            ],
            options={
                'db_table': '"msg"."pn_blast_event"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PNDelivery',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('pn_delivery_id', models.AutoField(db_column='pn_delivery_id', primary_key=True, serialize=False)),
                ('pn_delivery_xid', models.UUIDField(db_column='pn_delivery_xid', default=uuid.uuid4, editable=False)),
                ('fcm_id', models.TextField()),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('status', models.TextField()),
                ('extra_data', models.BigIntegerField(default=0)),
                ('campaign_id', models.TextField(blank=True, null=True)),
                ('customer_id', models.TextField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '"msg"."pn_delivery"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PNDeliveryEvent',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(db_column='pn_delivery_event_id', primary_key=True, serialize=False)),
                ('status', models.TextField()),
            ],
            options={
                'db_table': '"msg"."pn_delivery_event"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PNTracks',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('application_id', models.BigIntegerField(db_column='application_id')),
                ('loan_status_code', models.IntegerField(blank=True, null=True)),
                ('payment_id', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': '"msg"."pn_tracks"',
                'managed': False,
            },
        ),
    ]
