# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-10-27 04:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentCreditMatrix',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='current_credit_matrix_id', primary_key=True, serialize=False)),
                ('transaction_type', models.TextField()),
                ('credit_matrix', models.ForeignKey(db_column='credit_matrix_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.CreditMatrix')),
            ],
            options={
                'db_table': 'current_credit_matrix',
            },
        ),
    ]
