# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-10-27 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='accountproperty',
            name='concurrency',
            field=models.BooleanField(default=False),
        ),
    ]
