# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-10-28 01:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='application',
            field=models.OneToOneField(blank=True, db_column='application_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Application'),
        ),
    ]
