# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-10-21 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='privydocumentdata',
            name='loan_id',
            field=models.OneToOneField(blank=True, db_column='loan_id', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Loan'),
        ),
        migrations.AlterField(
            model_name='privydocumentdata',
            name='application_id',
            field=models.OneToOneField(blank=True, db_column='application_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Application'),
        ),
    ]
