# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-10-26 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='cashbacktransfertransaction',
            name='fund_transfer_ts',
            field=models.DateTimeField(null=True),
        ),
    ]
