# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-10-12 04:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPin',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='customer_pin_id', primary_key=True, serialize=False)),
                ('last_failure_time', models.DateTimeField()),
                ('latest_failure_count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='pin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_pin',
            },
        ),
        migrations.CreateModel(
            name='CustomerPinAttempt',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='customer_pin_attempt_id', primary_key=True, serialize=False)),
                ('is_success', models.BooleanField()),
                ('attempt_count', models.IntegerField()),
                ('reason', models.CharField(max_length=50)),
                ('hashed_pin', models.CharField(max_length=128, verbose_name='password')),
                ('customer_pin', models.ForeignKey(db_column='customer_pin_id', on_delete=django.db.models.deletion.DO_NOTHING, to='pin.CustomerPin')),
            ],
            options={
                'db_table': 'customer_pin_attempt',
            },
        ),
        migrations.CreateModel(
            name='CustomerPinChange',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='customer_pin_change_id', primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('expired_time', models.DateTimeField()),
                ('status', models.CharField(max_length=100)),
                ('new_hashed_pin', models.CharField(blank=True, max_length=128, null=True, verbose_name='password')),
                ('change_source', models.CharField(max_length=100)),
                ('reset_key', models.CharField(max_length=50)),
                ('customer_pin', models.ForeignKey(db_column='customer_pin_id', on_delete=django.db.models.deletion.DO_NOTHING, to='pin.CustomerPin')),
            ],
            options={
                'db_table': 'customer_pin_change',
            },
        ),
        migrations.CreateModel(
            name='CustomerPinChangeHistory',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='customer_pin_change_history_id', primary_key=True, serialize=False)),
                ('new_status', models.CharField(max_length=100)),
                ('old_status', models.CharField(max_length=100)),
                ('customer_pin_change', models.ForeignKey(db_column='customer_pin_change_id', on_delete=django.db.models.deletion.DO_NOTHING, to='pin.CustomerPinChange')),
            ],
            options={
                'db_table': 'customer_pin_change_history',
            },
        ),
        migrations.CreateModel(
            name='CustomerPinReset',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='customer_pin_reset_id', primary_key=True, serialize=False)),
                ('old_failure_count', models.IntegerField()),
                ('reset_type', models.CharField(max_length=50)),
                ('customer_pin', models.ForeignKey(db_column='customer_pin_id', on_delete=django.db.models.deletion.DO_NOTHING, to='pin.CustomerPin')),
                ('reset_by', models.ForeignKey(blank=True, db_column='agent_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_pin_reset',
            },
        ),
    ]
