# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-11-13 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='ptp',
            name='account',
            field=models.ForeignKey(blank=True, db_column='account_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.Account'),
        ),
        migrations.AddField(
            model_name='ptp',
            name='account_payment',
            field=models.ForeignKey(blank=True, db_column='account_payment_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account_payment.AccountPayment'),
        ),
        migrations.AddField(
            model_name='skiptracehistory',
            name='account',
            field=models.ForeignKey(blank=True, db_column='account_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.Account'),
        ),
        migrations.AddField(
            model_name='skiptracehistory',
            name='account_payment',
            field=models.ForeignKey(blank=True, db_column='account_payment_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account_payment.AccountPayment'),
        ),
        migrations.AddField(
            model_name='skiptracehistory',
            name='account_payment_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.StatusLookup'),
        ),
        migrations.AddField(
            model_name='voicecallrecord',
            name='account_payment',
            field=models.ForeignKey(blank=True, db_column='account_payment_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account_payment.AccountPayment'),
        ),
    ]
