# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-11-12 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='streamlinedcommunication',
            name='dpd_lower',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='streamlinedcommunication',
            name='dpd_upper',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='streamlinedcommunication',
            name='until_paid',
            field=models.BooleanField(default=False),
        ),
    ]
