# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-11-23 05:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardbuckets',
            name='loan_213',
            field=models.IntegerField(default=0),
        )
    ]
