# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-11-30 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='streamlinedcommunication',
            name='extra_conditions',
            field=models.TextField(blank=True, choices=[('CUSTOMER_HAVE_HIGH_SCORE', 'only for people with high score'), ('CUSTOMER_HAVE_MEDIUM_SCORE', 'customer who have medium score'), ('CUSTOMER_HAVE_HIGH_C_SCORE', 'customer who have high C score'), ('CUSTOMER_HAVE_LOW_SCORE_OR_C', 'customer with low score / C'), ('ALL_106_EXPECT_PREVIOUS_EXPIRY_REASON', 'all 106 except previous expiry reason = negative payment history'), ('MOVE_TO_106_WITH_REASON_NEGATIVE_PAYMENT_HISTORY', 'move to 106 with reason = negative payment history'), ('ALREADY_ELIGIBLE_TO_REAPPLY', 'Already eligible to reapply'), ('MSG_TO_STAY_UNTIL_1ST_TRANSACTION', 'msg to stay until 1st transaction'), ('MTL_MIGRATION_CAN_REAPPLY', 'mtl customer can reapply to julo1'), ('MTL_MIGRATION_CAN_NOT_REAPPLY', 'mtl customer can not reapply to julo1')], default=None, null=True),
        ),
    ]
