# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-01-10 06:42
from __future__ import unicode_literals

from django.db import migrations, models
from juloserver.moengage.constants import MoengageTaskStatus
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoengageUpload',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='moengage_upload_id', primary_key=True,
                                        serialize=False)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('error', models.TextField(blank=True, null=True)),
                ('type', models.CharField(max_length=100)),
                ('retry_count', models.IntegerField(blank=True, null=True)),
                ('application', models.ForeignKey(blank=True, db_column='application_id', null=True,
                                                  on_delete=django.db.models.deletion.DO_NOTHING,
                                                  to='julo.Application')),
                ('loan', models.ForeignKey(blank=True, db_column='loan_id', null=True,
                                           on_delete=django.db.models.deletion.DO_NOTHING,
                                           to='julo.Loan')),
            ],
            options={
                'db_table': 'moengage_upload',
            },
        ),
        migrations.CreateModel(
            name='MoengageUploadBatch',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='moengage_upload_batch_id', primary_key=True,
                                        serialize=False)),
                ('status', models.CharField(default=b'pending', max_length=100)),
                ('error', models.TextField(blank=True, null=True)),
                ('type', models.CharField(max_length=100)),
                ('retry_count', models.IntegerField(blank=True, null=True)),
                ('data_count', models.IntegerField()),
            ],
            options={
                'db_table': 'moengage_upload_batch',
            },
        ),
        migrations.AddField(
            model_name='moengageupload',
            name='moengage_upload_batch',
            field=models.ForeignKey(blank=True, db_column='moengage_upload_batch_id', null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='moengage.MoengageUploadBatch'),
        ),
        migrations.AddField(
            model_name='moengageupload',
            name='payment',
            field=models.ForeignKey(blank=True, db_column='payment_id', null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='julo.Payment'),
        ),
        migrations.RunSQL(
            "ALTER TABLE moengage_upload ALTER COLUMN payment_id TYPE bigint;"),
        migrations.RunSQL(
            "ALTER TABLE moengage_upload ALTER COLUMN application_id TYPE bigint;"),
        migrations.RunSQL(
            "ALTER TABLE moengage_upload ALTER COLUMN loan_id TYPE bigint;"),
        migrations.RunSQL(
            "ALTER TABLE moengage_upload ALTER COLUMN moengage_upload_batch_id TYPE bigint;"),
    ]
