# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-12-10 05:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='lendertransactionmapping',
            name='sepulsa_transaction',
            field=models.ForeignKey(blank=True, db_column='sepulsa_transaction_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_point.SpendTransaction'),
        ),
    ]
