# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-12-11 00:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RemoveField(
            model_name='lendertransactionmapping',
            name='sepulsa_transaction',
        ),
        migrations.AddField(
            model_name='lendertransactionmapping',
            name='sepulsa_transaction',
            field=models.ForeignKey(blank=True, db_column='sepulsa_transaction_id', null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='sepulsa_transaction',
                                    to='julo.SepulsaTransaction'),
        ),
    ]
