# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-12-14 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RenameField(
            model_name='waiverrequest',
            old_name='unrounded_actual_principal_waiver_percentage',
            new_name='unrounded_requested_principal_waiver_percentage',
        ),
    ]
