# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-01-18 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultiplePaymentPTP',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='multiple_payment_ptp_id', primary_key=True, serialize=False)),
                ('sequence', models.IntegerField()),
                ('promised_payment_date', models.DateField()),
                ('promised_payment_amount', models.BigIntegerField()),
                ('paid_amount', models.BigIntegerField(default=0)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('remaining_amount', models.BigIntegerField()),
                ('is_fully_paid', models.BooleanField(default=False)),
                ('waiver_request', models.ForeignKey(blank=True, db_column='waiver_request_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loan_refinancing.WaiverRequest')),
            ],
            options={
                'db_table': 'multiple_payment_ptp',
            },
        ),
    ]
