# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-01-15 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='streamlinedcommunication',
            name='extra_conditions',
            field=models.TextField(blank=True, choices=[(b'CUSTOMER_HAVE_HIGH_SCORE', b'only for people with high score'), (b'CUSTOMER_HAVE_MEDIUM_SCORE', b'customer who have medium score'), (b'CUSTOMER_HAVE_HIGH_C_SCORE', b'customer who have high C score'), (b'CUSTOMER_HAVE_LOW_SCORE_OR_C', b'customer with low score / C'), (b'ALL_106_EXPECT_PREVIOUS_EXPIRY_REASON', b'all 106 except previous expiry reason = negative payment history'), (b'MOVE_TO_106_WITH_REASON_NEGATIVE_PAYMENT_HISTORY', b'move to 106 with reason = negative payment history'), (b'ALREADY_ELIGIBLE_TO_REAPPLY', b'Already eligible to reapply'), (b'MSG_TO_STAY_UNTIL_1ST_TRANSACTION', b'msg to stay until 1st transaction'), (b'MTL_MIGRATION_CAN_REAPPLY', b'mtl customer can reapply to julo1'), (b'MTL_MIGRATION_CAN_NOT_REAPPLY', b'mtl customer can not reapply to julo1'), (b'REUPLOAD_KTP_ONLY_INFOCARD', b'Privy reupload - KTP'), (b'REUPLOAD_SELFIE_ONLY_INFOCARD', b'Privy reupload - Selfie'), (b'REUPLOAD_SELFIE_WITH_KTP_INFOCARD', b'Privy reupload - Selfie with KTP'), (b'REUPLOAD_SIM_ONLY_INFOCARD', b'Privy reupload - SIM'), (b'REUPLOAD_KK_ONLY_INFOCARD', b'Privy reupload - KK'), (b'REUPLOAD_EKTP_ONLY_INFOCARD', b'Privy reupload - E-KTP'), (b'REUPLOAD_KTP_SELFIE_INFOCARD', b'Privy reupload - KTP and Selfie'), (b'REUPLOAD_KTP_KK_INFOCARD', b'Privy reupload - KTP and KK'), (b'REUPLOAD_KTP_SIM_INFOCARD', b'Privy reupload - KTP and SIM'), (b'REUPLOAD_SIM_SELFIE_INFOCARD', b'Privy reupload - SIM and Selfie'), (b'REUPLOAD_SIM_KK_INFOCARD', b'Privy reupload - KK and SIM'), (b'REUPLOAD_SELFIE_KK_INFOCARD', b'Privy reupload - KK and Selfie'), (b'REUPLOAD_PASSPORT_ONLY_INFOCARD', b'Privy reupload - Passport'), (b'REUPLOAD_SELFIE_WITH_PASSPORT_INFOCARD', b'Privy reupload - Selfie with Passport and Passport'), (b'REUPLOAD_SELFIE_PASSPORT_INFOCARD', b'Privy reupload - Passport and Selfie')], default=None, null=True),
        ),
    ]
