# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-01-11 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RenameField(
            model_name='grabloaninquiry',
            old_name='installment_amount',
            new_name='instalment_amount',
        ),
        migrations.AlterField(
            model_name='grabloandata',
            name='loan_id',
            field=models.BigIntegerField(blank=True, null=True)
        ),
    ]
