# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-01-14 22:44
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='accountlimit',
            name='latest_affordability_history',
            field=models.ForeignKey(blank=True, db_column='latest_affordability_history_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.AffordabilityHistory'),
        ),
        migrations.AlterField(
            model_name='accountlimit',
            name='latest_credit_score',
            field=models.ForeignKey(blank=True, db_column='latest_credit_score_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.CreditScore'),
        ),
    ]
