# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-01-11 02:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [

    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE grab_loan_data ALTER COLUMN loan_id TYPE bigint;"),
        migrations.RunSQL(
            "ALTER TABLE grab_customer_data ALTER COLUMN customer_id TYPE bigint;")
    ]
