# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-01-11 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='grabloandata',
            name='selected_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grabloandata',
            name='selected_instalment_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grabloandata',
            name='selected_interest',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RenameField(
            model_name='grabloaninquiry',
            old_name='installment_amount_plan',
            new_name='instalment_amount_plan',
        ),
        migrations.AlterField(
            model_name='grabloaninquiry',
            name='fee_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grabloaninquiry',
            name='fee_value_plan',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grabloaninquiry',
            name='installment_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grabloaninquiry',
            name='interest_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grabloaninquiry',
            name='interest_value_plan',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grabloaninquiry',
            name='loan_disbursement_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grabloaninquiry',
            name='loan_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grabloaninquiry',
            name='max_loan_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grabloaninquiry',
            name='min_loan_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grabloaninquiry',
            name='penalty_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grabloaninquiry',
            name='tenure_plan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grabloaninquiry',
            name='total_repayment_amount_plan',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
