# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-01-18 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from juloserver.account.models import AdditionalCustomerInfo, Account


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='additionalcustomerinfo',
            name='customer',
            field=models.ForeignKey(blank=True, db_column='customer_id', null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='julo.Customer'),
        ),
        migrations.RemoveField(
            model_name='additionalcustomerinfo',
            name='account',
        ),
        migrations.RemoveField(
            model_name='additionalcustomerinfo',
            name='application',
        ),
    ]
