# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-01-19 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='ocrprocess',
            name='status',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ocrimageautomlrequest',
            name='status',
            field=models.TextField(default=None, null=True),
        ),
    ]
