# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-01-23 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='axiatacustomerdata',
            name='date_of_establishment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='axiatacustomerdata',
            name='ktp_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='axiatacustomerdata',
            name='limit',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='axiatacustomerdata',
            name='merchant_score_grade',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='axiatacustomerdata',
            name='npwp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='axiatacustomerdata',
            name='partner_application_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='axiatacustomerdata',
            name='referral_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='axiatacustomerdata',
            name='selfie_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
