# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-02-03 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionMethod',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='transaction_method_id', primary_key=True, serialize=False)),
                ('method', models.TextField()),
                ('fe_product_code', models.IntegerField()),
                ('fe_display_name', models.TextField()),
                ('background_icon_url', models.TextField()),
                ('foreground_icon_url', models.TextField()),
                ('foreground_locked_icon_url', models.TextField()),
            ],
            options={
                'db_table': 'transaction_method',
            },
        ),
    ]
