# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-02-05 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionmethod',
            name='fe_product_code',
        ),
    ]
