# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-02-08 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RenameField(
            model_name='sepulsatransaction',
            old_name='meter_number',
            new_name='customer_number',
        ),
        migrations.AddField(
            model_name='sepulsaproduct',
            name='admin_fee',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sepulsaproduct',
            name='collection_fee',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sepulsaproduct',
            name='service_fee',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sepulsatransaction',
            name='admin_fee',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sepulsatransaction',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sepulsatransaction',
            name='collection_fee',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sepulsatransaction',
            name='customer_amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sepulsatransaction',
            name='paid_period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sepulsatransaction',
            name='partner_amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sepulsatransaction',
            name='service_fee',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
