# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-02-10 04:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentdisbursecontract',
            name='response',
        ),
    ]
