# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-02-03 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='application_id2',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
