# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-02-05 04:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionAssignmentHistory',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='collection_assignment_history_id', primary_key=True, serialize=False)),
                ('old_assignment_id', models.PositiveIntegerField(null=True)),
                ('new_assignment_id', models.PositiveIntegerField(null=True)),
                ('assignment_reason', models.TextField()),
                ('account_payment', juloserver.julocore.customized_psycopg2.models.BigForeignKey(blank=True, db_column='account_payment_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account_payment.AccountPayment')),
                ('new_assignment_content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_assignment_content_type_relation', to='contenttypes.ContentType')),
                ('old_assignment_content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_assignment_content_type_relation', to='contenttypes.ContentType')),
                ('payment', juloserver.julocore.customized_psycopg2.models.BigForeignKey(blank=True, db_column='payment_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Payment')),
            ],
            options={
                'db_table': 'collection_assignment_history',
            },
        ),
        migrations.AddField(
            model_name='collectionvendorassignmentextension',
            name='account_payment',
            field=models.ForeignKey(blank=True, db_column='account_payment_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account_payment.AccountPayment'),
        ),
        migrations.AddField(
            model_name='collectionvendorassignmenttransfer',
            name='account_payment',
            field=models.ForeignKey(blank=True, db_column='account_payment_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account_payment.AccountPayment'),
        ),
    ]
