# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-02-18 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='grabloaninquiry',
            name='weekly_instalment_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
