# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-02-18 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='grabloandata',
            name='auth_transaction_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
