# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-03-12 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='creditmatrix',
            name='transaction_type',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
