# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-03-25 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='ecommercebankconfiguration',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
