# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-03-18 03:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationPathTag',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='application_path_tag_id', primary_key=True, serialize=False)),
                ('application', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Application')),
            ],
            options={
                'db_table': 'application_path_tag',
            },
        ),
        migrations.CreateModel(
            name='ApplicationPathTagStatus',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='application_path_tag_status_id', primary_key=True, serialize=False)),
                ('application_tag', models.CharField(max_length=200)),
                ('status', models.IntegerField()),
                ('definition', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'application_path_tag_status',
            },
        ),
        migrations.CreateModel(
            name='ApplicationTag',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='application_tag_id', primary_key=True, serialize=False)),
                ('application_tag', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'application_tag',
            },
        ),
        migrations.AddField(
            model_name='applicationpathtag',
            name='application_path_tag_status',
            field=models.ForeignKey(db_column='application_path_tag_status_id', on_delete=django.db.models.deletion.DO_NOTHING, to='application_flow.ApplicationPathTagStatus'),
        ),
    ]
