# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-03-23 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='axiatarepaymentdata',
            name='partner_application_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
