# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-03-19 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='accountproperty',
            name='ever_refinanced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountproperty',
            name='refinancing_ongoing',
            field=models.BooleanField(default=False),
        ),
    ]
