# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-04-09 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RefinancingTenor',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='refinancing_tenor_id',
                                        primary_key=True, serialize=False)),
                ('additional_tenor', models.IntegerField(null=True)),
                ('loan', juloserver.julocore.customized_psycopg2.models.BigForeignKey(
                    db_column='loan_id', on_delete=django.db.models.deletion.DO_NOTHING,
                    to='julo.Loan')),
                ('loan_refinancing_request', models.ForeignKey(
                    db_column='loan_refinancing_request_id',
                    on_delete=django.db.models.deletion.CASCADE,
                    to='loan_refinancing.LoanRefinancingRequest')),
            ],
            options={
                'db_table': 'refinancing_tenor',
            },
        ),
    ]
