# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-03-30 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='emailhistory',
            name='campaign_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
