# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-04-05 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='customerpin',
            name='latest_unlocked_count',
            field=models.SmallIntegerField(default=0),
        ),
    ]
