# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-04-01 07:52
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkdisbursementrequest',
            name='loan_id',
        ),
        migrations.AddField(
            model_name='bulkdisbursementrequest',
            name='loan',
            field=juloserver.julocore.customized_psycopg2.models.BigForeignKey(db_column='loan_id', on_delete=django.db.models.deletion.CASCADE, to='julo.Loan'),
        ),
        migrations.AlterUniqueTogether(
            name='bulkdisbursementrequest',
            unique_together=set([('loan', 'bank_account_number')]),
        ),
    ]
