# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-03-31 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulkDisbursementRequest',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='bulk_disbursement_request_id', primary_key=True, serialize=False)),
                ('bank_account_number', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('disbursement_amount', models.IntegerField()),
                ('disbursement_status', models.CharField(max_length=50)),
                ('loan_amount', models.IntegerField()),
                ('name_bank_validation_id', models.IntegerField()),
                ('disbursement', models.ForeignKey(blank=True, db_column='disbursement_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='disbursement.Disbursement')),
                ('loan_id', models.OneToOneField(db_column='loan_id', on_delete=django.db.models.deletion.CASCADE, to='julo.Loan')),
                ('product_line_code', models.ForeignKey(db_column='product_line_code_id', on_delete=django.db.models.deletion.CASCADE, to='julo.ProductLine')),
            ],
            options={
                'db_table': 'bulk_disbursement_request',
            },
        ),
        migrations.CreateModel(
            name='BulkDisbursementSchedule',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='bulk_disbursement_schedule_id', primary_key=True, serialize=False)),
                ('crontab', models.CharField(default='* * * * *', max_length=50)),
                ('is_active', models.BooleanField()),
                ('product_line_code', models.ForeignKey(db_column='product_line_code_id', on_delete=django.db.models.deletion.CASCADE, to='julo.ProductLine')),
            ],
            options={
                'db_table': 'bulk_disbursement_schedule',
            },
        ),
    ]
