# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-04-14 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountFavorites',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='account_favorites_id', primary_key=True, serialize=False)),
                ('ranking', models.IntegerField()),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.DO_NOTHING, to='account.Account')),
                ('transaction_method', models.ForeignKey(db_column='transaction_method_id', on_delete=django.db.models.deletion.DO_NOTHING, to='payment_point.TransactionMethod')),
            ],
            options={
                'db_table': 'account_favorites',
            },
        ),
    ]
