# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-04-14 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='transaction_category_id', primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('fe_display_name', models.TextField()),
            ],
            options={
                'db_table': 'transaction_category',
            },
        ),
        migrations.AddField(
            model_name='transactionmethod',
            name='order_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionmethod',
            name='transaction_category',
            field=models.ForeignKey(blank=True, db_column='transaction_category_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payment_point.TransactionCategory'),
        ),
    ]
