# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-04-13 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkdisbursementrequest',
            name='disbursement_amount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='bulkdisbursementrequest',
            name='loan_amount',
            field=models.BigIntegerField(),
        ),
    ]
