# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-04-12 02:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RenameField(
            model_name='customerpin',
            old_name='latest_unlocked_count',
            new_name='latest_blocked_count',
        ),
    ]
