# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-04-26 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='streamlinedcommunication',
            name='expiration_option',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='streamlinedcommunication',
            name='expiry_period',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='streamlinedcommunication',
            name='expiry_period_unit',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]