# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-04-26 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RenameField(
            model_name='lendermanualrepaymenttracking',
            old_name='settled_amount',
            new_name='settlement_amount',
        ),
        migrations.RemoveField(
            model_name='lendermanualrepaymenttracking',
            name='lender_transaction',
        ),
        migrations.AddField(
            model_name='lendermanualrepaymenttracking',
            name='lender',
            field=models.ForeignKey(blank=True, db_column='lender_id', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='followthemoney.LenderCurrent'),
        ),
        migrations.AddField(
            model_name='lendermanualrepaymenttracking',
            name='lender_transaction_mapping',
            field=models.ForeignKey(blank=True, db_column='lender_transaction_mapping_id', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='followthemoney.LenderTransactionMapping'),
        ),
    ]
