# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-04-22 05:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerProperty',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='partner_property_id', primary_key=True, serialize=False)),
                ('partner_reference_id', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.DO_NOTHING, to='account.Account')),
                ('partner', models.ForeignKey(db_column='partner_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Partner')),
            ],
            options={
                'db_table': 'partner_property',
            },
        ),
        migrations.AlterUniqueTogether(
            name='partnerproperty',
            unique_together=set([('partner', 'account')]),
        ),
    ]
