# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-04-27 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmethod',
            name='order_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
