# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-05-11 06:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DokuQrisVoidTopUp',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='doku_qris_void_top_up_id', primary_key=True, serialize=False)),
                ('transaction_id', models.TextField(blank=True, null=True, unique=True)),
                ('amount', models.BigIntegerField(blank=True, null=True)),
                ('tracking_id', models.TextField(blank=True, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('response_message', models.TextField(blank=True, null=True)),
                ('response_code', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'doku_qris_void_top_up',
            },
        ),
        migrations.AlterField(
            model_name='dokuqristopup',
            name='doku_qris_transaction_payment',
            field=models.ForeignKey(db_column='doku_qris_transaction_payment_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='qris_topup', to='qris.DokuQrisTransactionPayment'),
        ),
        migrations.AddField(
            model_name='dokuqrisvoidtopup',
            name='doku_qris_top_up',
            field=models.OneToOneField(db_column='doku_qris_top_up_id', on_delete=django.db.models.deletion.DO_NOTHING, to='qris.DokuQrisTopUp'),
        ),
    ]
