# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-05-04 04:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LenderApprovalTransactionMethod',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='lender_approval_transaction_method_id', primary_key=True, serialize=False)),
                ('delay', models.TimeField()),
                ('lender_approval', models.ForeignKey(db_column='lender_approval_id', on_delete=django.db.models.deletion.DO_NOTHING, to='followthemoney.LenderApproval')),
                ('transaction_method', models.ForeignKey(db_column='transaction_method_id', on_delete=django.db.models.deletion.DO_NOTHING, to='payment_point.TransactionMethod')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
