# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-05-20 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.ProductLookup'),
        ),
    ]
