# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-05-23 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='intelixBlacklist',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='intelix_blacklist_id', primary_key=True, serialize=False)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('reason_for_removal', models.TextField()),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.DO_NOTHING, to='account.Account')),
                ('skiptrace', models.ForeignKey(blank=True, db_column='skiptrace_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Skiptrace')),
            ],
            options={
                'db_table': 'intelix_blacklist',
            },
        ),
    ]
