# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-05-27 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='streamlinedcommunicationparameterlist',
            name='is_ptp',
            field=models.BooleanField(default=False),
        ),
    ]
