# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-06-03 05:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotificationPermission',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='push_notification_permission_id', primary_key=True, serialize=False)),
                ('is_pn_permission', models.BooleanField(default=False)),
                ('is_do_not_disturb', models.BooleanField(default=False)),
                ('account', models.ForeignKey(db_column='account_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.Account')),
                ('customer', juloserver.julocore.customized_psycopg2.models.BigForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Customer')),
            ],
            options={
                'db_table': 'push_notification_permission',
            },
        ),
    ]
