# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-06-04 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='expirytoken',
            name='is_never_expire',
            field=models.BooleanField(default=False),
        ),
    ]
