# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-06-16 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='dokuqristransactionpayment',
            name='doku_qris_transaction_scan',
            field=models.ForeignKey(db_column='doku_qris_transaction_scan_id', on_delete=django.db.models.deletion.DO_NOTHING, to='qris.DokuQrisTransactionScan'),
        ),
    ]
