# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-06-06 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='customerwallethistory',
            name='cashback_earned',
            field=models.OneToOneField(blank=True, db_column='cashback_earned_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cashback.CashbackEarned'),
        ),
    ]
