# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-06-15 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanLenderHistory',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='loan_lender_history_id', primary_key=True, serialize=False)),
                ('lender', models.ForeignKey(blank=True, db_column='lender_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='followthemoney.LenderCurrent')),
                ('loan', models.ForeignKey(db_column='loan_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Loan')),
            ],
            options={
                'db_table': 'loan_lender_history',
            },
        ),
    ]
