# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-06-06 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashbackEarned',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='cashback_earned_id', primary_key=True, serialize=False)),
                ('current_balance', models.BigIntegerField()),
                ('expired_on_date', models.DateField()),
            ],
            options={
                'db_table': 'cashback_earned',
            },
        ),
    ]
