# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-06-22 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='otprequest',
            name='miscall_otp',
            field=models.OneToOneField(blank=True, db_column='miscall_otp_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='otp.MisCallOTP'),
        ),
        migrations.AddField(
            model_name='otprequest',
            name='otp_service_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='otprequest',
            name='retry_validate_count',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='otprequest',
            name='otp_token',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
