# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-07-06 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionRiskyCheck',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='transaction_risky_check_id', primary_key=True, serialize=False)),
                ('is_vpn_detected', models.NullBooleanField()),
            ],
            options={
                'db_table': 'transaction_risky_check',
            },
        ),
        migrations.CreateModel(
            name='TransactionRiskyDecision',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='transaction_risky_check_id', primary_key=True, serialize=False)),
                ('decision_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'transaction_risky_decision',
            },
        ),
        migrations.AddField(
            model_name='transactionriskycheck',
            name='decision',
            field=models.ForeignKey(blank=True, db_column='decision_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loan.TransactionRiskyDecision'),
        ),
        migrations.AddField(
            model_name='transactionriskycheck',
            name='loan',
            field=models.ForeignKey(blank=True, db_column='loan_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Loan'),
        ),
    ]
