# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-07-06 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='applicationriskycheck',
            name='is_vpn_detected',
            field=models.NullBooleanField(),
        ),
    ]
