# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-07-22 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='cootekconfiguration',
            name='is_exclude_b3_vendor',
            field=models.BooleanField(default=False, verbose_name='Exclude 50% sent to B3 vendor'),
        ),
    ]
