# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-07-21 14:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VPNDetection',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='vpn_detection_id', primary_key=True, serialize=False)),
                ('ip_address', models.TextField()),
                ('is_vpn_detected', models.NullBooleanField()),
                ('extra_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vpn_detection',
            },
        ),
    ]
