# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-07-27 04:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RemoveField(
            model_name='miscallotp',
            name='is_used',
        ),
    ]
