# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-07-27 08:42
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousFraudApps',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='suspicious_fraud_app_id', primary_key=True, serialize=False)),
                ('package_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), default=list, size=None)),
                ('transaction_risky_check', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'suspicious_fraud_apps',
            },
        ),
    ]
