# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-07-30 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='distributor',
            field=models.ForeignKey(blank=True, db_column='distributor_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='partnership.Distributor'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='limit',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='merchant',
            name='merchant_category',
            field=models.ForeignKey(blank=True, db_column='merchant_category_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='partnership.MerchantDistributorCategory'),
        ),
    ]
