# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-08-03 10:44
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporarysession',
            name='action_type',
        ),
        migrations.AddField(
            model_name='temporarysession',
            name='otp_request',
            field=juloserver.julocore.customized_psycopg2.models.BigForeignKey(blank=True, db_column='otp_request_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.OtpRequest'),
        ),
    ]
