# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-07-27 13:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='referralsystem',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referralsystem',
            name='referee_cashback_amount',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
