# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-08-02 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='external_distributor_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
