# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-08-05 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='recordingreport',
            name='l_channel_negative_score_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recordingreport',
            name='l_channel_sop_score_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recordingreport',
            name='r_channel_negative_score_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recordingreport',
            name='r_channel_sop_score_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
