# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-08-16 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='frontendview',
            name='label_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
