# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-08-24 14:21
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RenameField(
            model_name='highscorefullbypass',
            old_name='parameters',
            new_name='city',
        ),
        migrations.AddField(
            model_name='highscorefullbypass',
            name='job',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
