# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-08-18 05:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BonzaScoringResult',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='bonza_scoring_results_id', primary_key=True, serialize=False)),
                ('request_id', models.TextField(blank=True, null=True)),
                ('score', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('customer', juloserver.julocore.customized_psycopg2.models.BigForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Customer')),
                ('loan', juloserver.julocore.customized_psycopg2.models.BigForeignKey(db_column='loan_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Loan')),
            ],
            options={
                'db_table': 'bonza_scoring_results',
            },
        ),
    ]
