# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-08-16 04:26
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CfsAction',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.BigIntegerField(db_column='cfs_action_id', primary_key=True, serialize=False)),
                ('action_code', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('default_expiry', models.BigIntegerField(blank=True, null=True)),
                ('display_order', models.BigIntegerField(default=0)),
                ('icon', models.CharField(max_length=1000)),
                ('app_link', models.CharField(max_length=255)),
                ('first_occurrence_cashback_amount', models.BigIntegerField(blank=True, null=True)),
                ('repeat_occurrence_cashback_amount', models.BigIntegerField(blank=True, null=True)),
                ('is_need_agent_verify', models.BooleanField(default=False)),
                ('app_version', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='characters not allowed', regex='^[ -~]+$')])),
                ('action_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'cfs_action',
            },
        ),
        migrations.CreateModel(
            name='CfsActionAssignment',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='cfs_action_assignment_id', primary_key=True, serialize=False)),
                ('repeat_action_no', models.BigIntegerField()),
                ('progress_status', models.BigIntegerField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('cashback_amount', models.BigIntegerField(blank=True, null=True)),
                ('extra_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('action', models.ForeignKey(db_column='cfs_action_id', on_delete=django.db.models.deletion.DO_NOTHING, to='cfs.CfsAction')),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Customer')),
            ],
            options={
                'db_table': 'cfs_action_assignment',
            },
        ),
        migrations.CreateModel(
            name='CfsAssignmentVerification',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='verification_id', primary_key=True, serialize=False)),
                ('verify_status', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField(max_length=1000, null=True)),
                ('extra_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, db_column='account_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.Account')),
                ('agent', models.ForeignKey(blank=True, db_column='agent_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Agent')),
                ('cfs_action_assignment', models.ForeignKey(db_column='cfs_action_assignment_id', on_delete=django.db.models.deletion.DO_NOTHING, to='cfs.CfsActionAssignment')),
            ],
            options={
                'db_table': 'cfs_assignment_verification',
            },
        ),
    ]
