# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-09-01 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='bonzascoringresult',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
