# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-08-30 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardbuckets',
            name='app_132_grab',
            field=models.IntegerField(default=0),
        ),
    ]
