# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-08-26 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE payment_deposit ALTER COLUMN loan_id TYPE bigint;"),
    ]
