# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-09-03 06:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageMetadata',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='face_recommender_result_id', primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=500)),
                ('directory', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('file_modification_time', models.DateTimeField(blank=True, null=True)),
                ('file_access_time', models.DateTimeField(blank=True, null=True)),
                ('file_creation_time', models.DateTimeField(blank=True, null=True)),
                ('file_permission', models.CharField(blank=True, max_length=50, null=True)),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('file_type_extension', models.CharField(blank=True, max_length=50, null=True)),
                ('file_mime', models.CharField(blank=True, max_length=50, null=True)),
                ('exif_byte_order', models.CharField(blank=True, max_length=255, null=True)),
                ('gps_lat_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('gps_date', models.CharField(blank=True, max_length=255, null=True)),
                ('gps_timestamp', models.DateTimeField(blank=True, null=True)),
                ('gps_altitude', models.SmallIntegerField(blank=True, null=True)),
                ('gps_long_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('camera_model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('orientation', models.CharField(blank=True, max_length=50, null=True)),
                ('flash_status', models.NullBooleanField()),
                ('exif_version', models.CharField(blank=True, max_length=50, null=True)),
                ('camera_focal_length', models.FloatField(blank=True, null=True)),
                ('white_balance', models.CharField(blank=True, max_length=50, null=True)),
                ('exif_image_width', models.IntegerField(blank=True, null=True)),
                ('exif_image_height', models.IntegerField(blank=True, null=True)),
                ('sub_sec_time', models.IntegerField(blank=True, null=True)),
                ('original_timestamp', models.DateTimeField(blank=True, null=True)),
                ('sub_sec_time_original', models.IntegerField(blank=True, null=True)),
                ('sub_sec_time_digitized', models.IntegerField(blank=True, null=True)),
                ('make', models.CharField(blank=True, max_length=255, null=True)),
                ('jfif_version', models.CharField(blank=True, max_length=50, null=True)),
                ('resolution_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('x_res', models.IntegerField(blank=True, null=True)),
                ('y_res', models.IntegerField(blank=True, null=True)),
                ('image_width', models.IntegerField(blank=True, null=True)),
                ('image_height', models.IntegerField(blank=True, null=True)),
                ('encoding', models.CharField(blank=True, max_length=255, null=True)),
                ('bits_per_sample', models.IntegerField(blank=True, null=True)),
                ('color_components', models.IntegerField(blank=True, null=True)),
                ('ycbcrsub_sampling', models.CharField(blank=True, max_length=255, null=True)),
                ('image_size', models.CharField(blank=True, max_length=255, null=True)),
                ('megapixels', models.FloatField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('datetime_original', models.DateTimeField(blank=True, null=True)),
                ('gps_lat', models.CharField(blank=True, max_length=100, null=True)),
                ('gps_long', models.CharField(blank=True, max_length=100, null=True)),
                ('gps_position', models.CharField(blank=True, max_length=255, null=True)),
                ('bit_depth', models.SmallIntegerField(blank=True, null=True)),
                ('interlace', models.CharField(blank=True, max_length=255, null=True)),
                ('color_type', models.CharField(blank=True, max_length=255, null=True)),
                ('compression', models.CharField(blank=True, max_length=100, null=True)),
                ('filter', models.CharField(blank=True, max_length=255, null=True)),
                ('application', juloserver.julocore.customized_psycopg2.models.BigForeignKey(db_column='application_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Application')),
                ('image', juloserver.julocore.customized_psycopg2.models.BigForeignKey(db_column='image_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Image')),
            ],
            options={
                'db_table': 'image_metadata',
            },
        ),
    ]
