# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-09-15 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmulatorCheck',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='emulator_check_id', primary_key=True, serialize=False)),
                ('service_provider', models.CharField(blank=True, max_length=250)),
                ('timestamp_ms', models.DateTimeField(blank=True, null=True)),
                ('nonce', models.TextField(blank=True, null=True)),
                ('apk_package_name', models.TextField(blank=True, null=True)),
                ('apk_certificate_digest_sha_256', models.TextField(blank=True, null=True)),
                ('cts_profile_match', models.NullBooleanField()),
                ('basic_integrity', models.NullBooleanField()),
                ('evaluation_type', models.CharField(blank=True, max_length=250, null=True)),
                ('advice', models.TextField(blank=True, null=True)),
                ('error_msg', models.TextField(blank=True, null=True)),
                ('application', juloserver.julocore.customized_psycopg2.models.BigForeignKey(db_column='application_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Application')),
            ],
            options={
                'db_table': 'emulator_check',
            },
        ),
    ]
