# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-09-14 11:51
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CfsActionPoints',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.IntegerField(db_column='cfs_action_points_id', primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('multiplier', models.FloatField(blank=True, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('ceiling', models.IntegerField(blank=True, null=True)),
                ('default_expiry', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cfs_action_points',
            },
        ),
        migrations.CreateModel(
            name='CfsActionPointsAssignment',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='cfs_action_points_assignment_id', primary_key=True, serialize=False)),
                ('extra_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('points_changed', models.IntegerField(blank=True, null=True)),
                ('cfs_action_points', models.ForeignKey(db_column='cfs_action_points_id', on_delete=django.db.models.deletion.DO_NOTHING, to='cfs.CfsActionPoints')),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Customer')),
                ('loan', juloserver.julocore.customized_psycopg2.models.BigForeignKey(blank=True, db_column='loan_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Loan')),
                ('payment', juloserver.julocore.customized_psycopg2.models.BigForeignKey(blank=True, db_column='payment_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Payment')),
            ],
            options={
                'db_table': 'cfs_action_points_assignment',
            },
        ),
        migrations.CreateModel(
            name='TotalActionPointsHistory',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='total_action_points_history_id', primary_key=True, serialize=False)),
                ('partition_date', models.DateField()),
                ('old_point', models.IntegerField(blank=True, null=True)),
                ('new_point', models.IntegerField(blank=True, null=True)),
                ('change_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('cfs_action_point_assignment', models.ForeignKey(db_column='cfs_action_points_assignment_id', on_delete=django.db.models.deletion.DO_NOTHING, to='cfs.CfsActionPointsAssignment')),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Customer')),
            ],
            options={
                'db_table': 'total_action_points_history',
            },
        ),
    ]
