# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-09-16 04:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantBinaryCheck',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='merchant_binary_check_id', primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_sql_query', models.TextField()),
                ('operator', models.CharField(choices=[('GT', 'GREATER_THAN'), ('GTE', 'GREATER_THAN_EQUAL'), ('LT', 'LESS_THAN'), ('LTE', 'LESS_THAN_EQUAL'), ('EE', 'EQUALS')], default='EE', max_length=4)),
                ('cut_off_limit', models.FloatField()),
                ('binary_check_weight', models.FloatField(default=0.5)),
                ('partner', models.ForeignKey(db_column='partner_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Partner')),
            ],
            options={
                'db_table': 'merchant_binary_check',
            },
        ),
        migrations.AddField(
            model_name='merchant',
            name='business_rules_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
