# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-09-16 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='indexedface',
            name='latency',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
