# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-09-08 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackPromiseApp',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='callback_promise_id', primary_key=True, serialize=False)),
                ('bucket', models.TextField(blank=True, null=True)),
                ('selected_time_slot_start', models.TextField(blank=True, null=True)),
                ('selected_time_slot_end', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, db_column='account_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.Account')),
                ('account_payment', models.ForeignKey(blank=True, db_column='account_payment_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account_payment.AccountPayment')),
                ('skiptrace_history', models.ForeignKey(blank=True, db_column='skiptrace_history_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.SkiptraceHistory')),
            ],
            options={
                'db_table': 'callback_promise_app',
            },
        ),
    ]
