# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-09-22 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='awsrecogresponse',
            name='image_id',
            field=models.ForeignKey(blank=True, db_column='image_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Image'),
        ),
    ]
