# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-09-21 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdeposit',
            name='is_verified_code',
            field=models.BooleanField(default=False),
        ),
    ]
