# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-09-29 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPinVerify',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='customer_pin_verify_id', primary_key=True, serialize=False)),
                ('is_pin_used', models.BooleanField(default=None)),
                ('expiry_time', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Customer')),
                ('customer_pin', models.ForeignKey(db_column='customer_pin_id', on_delete=django.db.models.deletion.DO_NOTHING, to='pin.CustomerPin')),
            ],
            options={
                'db_table': 'customer_pin_verify',
            },
        ),
        migrations.CreateModel(
            name='CustomerPinVerifyHistory',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='customer_pin_verify_history_id', primary_key=True, serialize=False)),
                ('is_pin_used', models.BooleanField(default=None)),
                ('expiry_time', models.DateTimeField(blank=True, null=True)),
                ('customer_pin_verify', models.ForeignKey(db_column='customer_pin_verify_id', on_delete=django.db.models.deletion.DO_NOTHING, to='partnership.CustomerPinVerify')),
            ],
            options={
                'db_table': 'customer_pin_verify_history',
            },
        ),
    ]
