# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-09-20 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='distributor_xid',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
