# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-09-27 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='accountproperty',
            name='is_entry_level',
            field=models.BooleanField(default=False),
        ),
    ]
