# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-09-28 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemetadata',
            name='camera_focal_length',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imagemetadata',
            name='flash_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagemetadata',
            name='x_res',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imagemetadata',
            name='y_res',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
