# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-10-08 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='lendertransactionmapping',
            name='channeling_transaction',
            field=models.ForeignKey(blank=True, db_column='channeling_history_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channeling_transaction', to='channeling_loan.ChannelingLoanHistory'),
        ),
    ]
