# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-10-06 07:56
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='faq_item_id', primary_key=True, serialize=False)),
                ('type', models.TextField(choices=[('section', 'Section'), ('question', 'Question')], db_index=True, default='question')),
                ('title', models.TextField()),
                ('slug', models.SlugField()),
                ('rich_text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('order_priority', models.IntegerField(db_index=True, default=0)),
                ('visible', models.BooleanField(db_index=True, default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landing_page_api.FAQItem')),
            ],
            options={
                'db_table': 'landing_page_faq_item',
                'ordering': ('order_priority', 'cdate', 'visible'),
            },
        ),
    ]
