# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-10-14 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='salesopsaccountsegmenthistory',
            name='log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesopslineup',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesopslineup',
            name='id',
            field=models.AutoField(db_column='sales_ops_lineup_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='salesopslineup',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='salesopslineup',
            name='prioritization',
            field=models.SmallIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='salesopsrmscoring',
            name='id',
            field=models.AutoField(db_column='sales_ops_rm_scoring_id', primary_key=True, serialize=False),
        ),
    ]
