# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-10-15 06:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerreferral',
            name='cust_email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='partnerreferral',
            name='cust_nik',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='KTP has to be 16 numeric digits', regex='^[0-9]{16}$')]),
        ),
    ]
