# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-10-27 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='passivelivenessdetection',
            name='image',
            field=models.OneToOneField(blank=True, db_column='image_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Image'),
        ),
    ]
