# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-11-02 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorrecordingdetail',
            name='unique_call_id',
            field=models.TextField(unique=True),
        ),
    ]
