# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-11-01 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='reset_password_key',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
