# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-11-09 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOpsMScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.BigIntegerField(blank=True, null=True)),
                ('latest_account_limit_id', models.BigIntegerField(blank=True, null=True)),
                ('available_limit', models.BigIntegerField(default=0)),
                ('ranking', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'sales_ops_m_score',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalesOpsRScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.BigIntegerField(blank=True, null=True)),
                ('latest_active_dates', models.DateField(blank=True, null=True)),
                ('ranking', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'sales_ops_r_score',
                'managed': False,
            },
        ),
    ]
