# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-11-23 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='autodebetbenefitdetail',
            name='payment',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
