# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-11-16 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutodebetBenefitDetail',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='autodebet_benefit_detail_id', primary_key=True, serialize=False)),
                ('benefit_value', models.TextField(blank=True, null=True)),
                ('account_payment', models.ForeignKey(blank=True, db_column='account_payment_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account_payment.AccountPayment')),
            ],
            options={
                'db_table': 'autodebet_benefit_detail',
            },
        ),
        migrations.RemoveField(
            model_name='autodebetbenefit',
            name='account_payment',
        ),
        migrations.RemoveField(
            model_name='autodebetbenefit',
            name='benefit_config_value',
        ),
        migrations.RemoveField(
            model_name='autodebetbenefit',
            name='payment',
        ),
        migrations.AddField(
            model_name='autodebetbenefit',
            name='is_benefit_used',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='autodebetbenefit',
            name='account',
            field=models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.DO_NOTHING, to='account.Account', unique=True),
        ),
        migrations.AddField(
            model_name='autodebetbenefitdetail',
            name='autodebet_benefit',
            field=models.ForeignKey(db_column='autodebet_benefit_id', on_delete=django.db.models.deletion.DO_NOTHING, to='autodebet.AutodebetBenefit'),
        ),
        migrations.AddField(
            model_name='autodebetbenefitdetail',
            name='payment',
            field=models.ForeignKey(blank=True, db_column='payment_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Payment'),
        ),
    ]
