# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-11-22 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InitialFDCInquiryLoanData',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='initial_fdc_inquiry_loan_data_id', primary_key=True, serialize=False)),
                ('initial_outstanding_loan_count_x100', models.IntegerField(blank=True, null=True)),
                ('initial_outstanding_loan_amount_x100', models.BigIntegerField(blank=True, null=True)),
                ('fdc_inquiry', models.ForeignKey(db_column='fdc_inquiry_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.FDCInquiry')),
            ],
            options={
                'db_table': 'initial_fdc_inquiry_loan_data',
            },
        ),
    ]
