# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-11-26 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashbackOverpaidVerification',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='overpaid_case_id', primary_key=True, serialize=False)),
                ('overpaid_amount', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('application', juloserver.julocore.customized_psycopg2.models.BigForeignKey(db_column='application_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Application')),
                ('customer', juloserver.julocore.customized_psycopg2.models.BigForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Customer')),
                ('image', juloserver.julocore.customized_psycopg2.models.BigForeignKey(blank=True, db_column='image_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Image')),
                ('wallet_history', models.OneToOneField(db_column='wallet_history_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='overpaid_verification', to='julo.CustomerWalletHistory')),
            ],
            options={
                'db_table': 'cashback_overpaid_verification',
            },
        ),
        migrations.CreateModel(
            name='OverpaidVerifyingHistory',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='history_id', primary_key=True, serialize=False)),
                ('agent_note', models.CharField(blank=True, max_length=1000, null=True)),
                ('processed_status', models.CharField(max_length=100)),
                ('error_message', models.CharField(blank=True, max_length=1000, null=True)),
                ('agent', models.ForeignKey(db_column='agent_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Agent')),
                ('overpaid_verification', models.ForeignKey(db_column='overpaid_verification_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='overpaid_history', to='cashback.CashbackOverpaidVerification')),
                ('decision', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'overpaid_verifying_history',
            },
        ),
    ]
