# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-12-07 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MagicLinkHistory',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='magic_link_history_id', primary_key=True, serialize=False)),
                ('token', models.TextField()),
                ('status', models.TextField(default='unused')),
                ('expiry_time', models.DateTimeField()),
                ('email_history', models.ForeignKey(blank=True, db_column='email_history_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.EmailHistory')),
                ('sms_history', models.ForeignKey(blank=True, db_column='sms_history_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.SmsHistory')),
            ],
            options={
                'db_table': 'magic_link_history',
            },
        ),
    ]
