# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-12-01 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DukcapilAsliriBalance',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='dukcapil_asliri_balance_id', primary_key=True, serialize=False)),
                ('status', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('remaining_balance', models.IntegerField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dukcapil_asliri_balance',
            },
        ),
    ]
