# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-12-03 12:23
from __future__ import unicode_literals

import cuser.fields
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOpsLineupHistory',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', juloserver.julocore.customized_psycopg2.models.BigAutoField(db_column='sales_ops_lineup_history_id', primary_key=True, serialize=False)),
                ('old_values', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('new_values', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('changed_by', cuser.fields.CurrentUserField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lineup', models.ForeignKey(db_column='sales_ops_lineup_id', on_delete=django.db.models.deletion.DO_NOTHING, to='sales_ops.SalesOpsLineup')),
            ],
            options={
                'db_table': 'sales_ops_lineup_history',
            },
        ),
    ]
