# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-12-07 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelingLoanPayment',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='channeling_loan_payment_id', primary_key=True, serialize=False)),
                ('due_date', models.DateField(null=True)),
                ('due_amount', models.BigIntegerField()),
                ('principal_amount', models.BigIntegerField(default=0)),
                ('interest_amount', models.BigIntegerField(default=0)),
                ('paid_interest', models.BigIntegerField(blank=True, default=0)),
                ('paid_principal', models.BigIntegerField(blank=True, default=0)),
                ('payment', juloserver.julocore.customized_psycopg2.models.BigForeignKey(blank=True, db_column='payment_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Payment')),
            ],
            options={
                'db_table': 'channeling_loan_payment',
            },
        ),
    ]
