# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-12-05 06:43
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RenameField(
            model_name='activelivenessdetection',
            old_name='retry_count',
            new_name='attempt',
        ),
        migrations.AlterField(
            model_name='activelivenessdetection',
            name='application',
            field=juloserver.julocore.customized_psycopg2.models.BigForeignKey(db_column='application_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Application'),
        ),
    ]
