# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-12-23 04:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='merchantapplicationreapplyinterval',
            unique_together=set([('application_status', 'partner')]),
        ),
    ]
