# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-12-29 03:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeCheckAPILog',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', juloserver.julocore.customized_psycopg2.models.BigAutoField(db_column='income_check_api_log_id', primary_key=True, serialize=False)),
                ('api_type', models.TextField()),
                ('http_status_code', models.IntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(525)])),
                ('query_params', models.TextField()),
                ('request', models.TextField(blank=True, null=True)),
                ('response', models.TextField()),
                ('status', models.TextField()),
                ('latency', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'income_check_api_log',
            },
        ),
        migrations.CreateModel(
            name='IncomeCheckLog',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', juloserver.julocore.customized_psycopg2.models.BigAutoField(db_column='income_check_log_id', primary_key=True, serialize=False)),
                ('is_found', models.BooleanField()),
                ('status', models.TextField()),
                ('message', models.TextField(blank=True, null=True)),
                ('salary_amount', models.BigIntegerField(null=True)),
                ('currency', models.TextField()),
                ('service_provider', models.TextField()),
                ('application', juloserver.julocore.customized_psycopg2.models.BigForeignKey(blank=True, db_column='application_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Application')),
            ],
            options={
                'db_table': 'income_check_log',
            },
        ),
        migrations.AddField(
            model_name='incomecheckapilog',
            name='income_check_log',
            field=models.ForeignKey(blank=True, db_column='income_check_log_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='income_check.IncomeCheckLog'),
        ),
    ]
