# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-01-06 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import juloserver.julo.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadAsyncState',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='upload_async_state_id', primary_key=True, serialize=False)),
                ('task_status', models.CharField(max_length=50)),
                ('task_type', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('service', models.CharField(choices=[('s3', 's3'), ('oss', 'oss')], default='oss', max_length=50)),
                ('file', models.FileField(blank=True, db_column='internal_path', null=True, upload_to=juloserver.julo.models.upload_async_state_upload_to)),
                ('agent', models.ForeignKey(blank=True, db_column='agent_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Agent')),
            ],
            options={
                'db_table': 'upload_async_state',
            },
        ),
    ]
