# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-01-12 03:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationPathTagHistory',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', juloserver.julocore.customized_psycopg2.models.BigAutoField(db_column='application_path_tag_history_id', primary_key=True, serialize=False)),
                ('application_status_code', models.IntegerField()),
                ('tag_status', models.IntegerField()),
                ('application_path_tag', juloserver.julocore.customized_psycopg2.models.BigForeignKey(blank=True, db_column='application_path_tag_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application_flow.ApplicationPathTag')),
            ],
            options={
                'db_table': 'application_path_tag_history',
            },
        ),
    ]
