# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-01-04 06:34
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='streamlinedcommunication',
            name='partner_selection_action',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='streamlinedcommunication',
            name='partner_selection_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), default=list, size=None),
        ),
    ]
