# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-01-17 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    """
    Move these tables to `promo` subapp
    - promo_history
    - promo_code
    - waive_promo
    """
    dependencies = [
    ]

    state_operations = [
        migrations.RemoveField(
            model_name='promohistory',
            name='account',
        ),
        migrations.RemoveField(
            model_name='promohistory',
            name='account_payment',
        ),
        migrations.RemoveField(
            model_name='promohistory',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='promohistory',
            name='loan',
        ),
        migrations.RemoveField(
            model_name='promohistory',
            name='payment',
        ),
        migrations.DeleteModel(
            name='PromoHistory',
        ),

        migrations.RemoveField(
            model_name='waivepromo',
            name='loan',
        ),
        migrations.RemoveField(
            model_name='waivepromo',
            name='payment',
        ),
        migrations.DeleteModel(
            name='WaivePromo',
        ),

        migrations.DeleteModel(
            name='PromoCode',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
