# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-01-24 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='salesopslineup',
            name='inactive_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
