# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-01-19 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='autodebetaccount',
            name='bri_customer_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autodebetaccount',
            name='card_expiry',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autodebetaccount',
            name='linked_account_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autodebetaccount',
            name='linked_email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autodebetaccount',
            name='linked_mobile_phone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autodebetaccount',
            name='linked_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autodebetaccount',
            name='deleted_failed_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autodebetaccount',
            name='failed_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autodebetaccount',
            name='request_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autodebetaccount',
            name='verification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
