# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-01-20 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethodlookup',
            name='is_shown_mf',
            field=models.BooleanField(default=False),
        ),
    ]
