# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-01-21 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutodebetBRITransaction',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='autodebet_bri_transaction_id', primary_key=True, serialize=False)),
                ('bri_transaction_id', models.TextField(blank=True, null=True)),
                ('transaction_id', models.TextField(blank=True, null=True)),
                ('amount', models.BigIntegerField(blank=True, null=True)),
                ('status', models.TextField(blank=True, default='INITIAL', null=True)),
                ('created_ts', models.DateTimeField(blank=True, null=True)),
                ('updated_ts', models.DateTimeField(blank=True, null=True)),
                ('otp_mobile_number', models.TextField(blank=True, null=True)),
                ('otp_expiration_timestamp', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('required_action', models.TextField(blank=True, null=True)),
                ('account_payment', models.ForeignKey(db_column='account_payment_id', on_delete=django.db.models.deletion.DO_NOTHING, to='account_payment.AccountPayment')),
            ],
            options={
                'db_table': 'autodebet_bri_transaction',
            },
        ),
        migrations.CreateModel(
            name='AutodebetBRITransactionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('old_status', models.TextField(blank=True, null=True)),
                ('new_status', models.TextField(blank=True, null=True)),
                ('autodebet_bri_transaction', models.ForeignKey(db_column='autodebet_bri_transaction_id', on_delete=django.db.models.deletion.DO_NOTHING, to='autodebet.AutodebetBRITransaction')),
            ],
            options={
                'db_table': 'autodebet_bri_transaction_history',
            },
        ),
        migrations.AddField(
            model_name='autodebetaccount',
            name='payment_method_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autodebetbritransaction',
            name='autodebet_account',
            field=models.ForeignKey(db_column='autodebet_account_id', on_delete=django.db.models.deletion.DO_NOTHING, to='autodebet.AutodebetAccount'),
        ),
    ]
