# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-02-03 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='intelixblacklist',
            name='reason_for_removal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
