# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-02-08 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantHistoricalTransactionTask',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='merchant_historical_transaction_task_id', primary_key=True, serialize=False)),
                ('path', models.TextField(blank=True, null=True)),
                ('error_path', models.TextField(blank=True, null=True)),
                ('file_name', models.TextField(blank=True, null=True)),
                ('unique_id', models.BigIntegerField(unique=True)),
                ('application', juloserver.julocore.customized_psycopg2.models.BigForeignKey(db_column='application_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Application')),
            ],
            options={
                'db_table': 'merchant_historical_transaction_task',
            },
        ),
        migrations.CreateModel(
            name='MerchantHistoricalTransactionTaskStatus',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='merchant_historical_transaction_task_status_id', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('IN PROGRESS', 'IN PROGRESS'), ('VALID', 'VALID'), ('INVALID', 'INVALID')], max_length=20)),
                ('merchant_historical_transaction_task', models.OneToOneField(db_column='merchant_historical_transaction_task_id', on_delete=django.db.models.deletion.DO_NOTHING, to='merchant_financing.MerchantHistoricalTransactionTask')),
            ],
            options={
                'db_table': 'merchant_historical_transaction_task_status',
            },
        ),
    ]
