# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-02-10 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='merchanthistoricaltransaction',
            name='reference_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
