# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-02-13 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpinchange',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
