# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-02-16 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='channelingloanstatus',
            name='channeling_status',
            field=models.CharField(choices=[('eligible', 'eligible'), ('pending', 'pending'), ('process', 'process'), ('success', 'success'), ('reject', 'reject'), ('buyback', 'buyback')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='channelingloanstatushistory',
            name='new_status',
            field=models.CharField(choices=[('eligible', 'eligible'), ('pending', 'pending'), ('process', 'process'), ('success', 'success'), ('reject', 'reject'), ('buyback', 'buyback')], max_length=10),
        ),
        migrations.AlterField(
            model_name='channelingloanstatushistory',
            name='old_status',
            field=models.CharField(choices=[('eligible', 'eligible'), ('pending', 'pending'), ('process', 'process'), ('success', 'success'), ('reject', 'reject'), ('buyback', 'buyback')], max_length=10),
        ),
    ]
