# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-02-16 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='otprequest',
            name='partnership_customer_data',
            field=models.ForeignKey(blank=True, db_column='partnership_customer_data_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='partnership.PartnershipCustomerData'),
        ),
        migrations.AddField(
            model_name='smshistory',
            name='partnership_customer_data',
            field=models.ForeignKey(blank=True, db_column='partnership_customer_data_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='partnership.PartnershipCustomerData'),
        ),
        migrations.AlterField(
            model_name='otprequest',
            name='customer',
            field=models.ForeignKey(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Customer'),
        ),
    ]
