# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-02-18 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='partnershipapplicationdata',
            name='loan_purpose',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tujuan pinjaman'),
        ),
    ]
