# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-02-21 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='partnershipapplicationdata',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnershipapplicationdata',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnershipapplicationdata',
            name='web_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
