# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-02-16 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnershipCustomerDataOTP',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='partnership_customer_data_otp_id', primary_key=True, serialize=False)),
                ('otp_last_failure_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('otp_failure_count', models.IntegerField(default=0)),
                ('otp_latest_failure_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'partnership_customer_data_otp',
            },
        ),
        migrations.AddField(
            model_name='partnershipcustomerdata',
            name='partner',
            field=models.ForeignKey(db_column='partner_id', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Partner'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='partnershipcustomerdata',
            unique_together=set([('phone_number', 'partner', 'nik')]),
        ),
        migrations.AddField(
            model_name='partnershipcustomerdataotp',
            name='partnership_customer_data',
            field=models.OneToOneField(db_column='partnership_customer_data_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='partnership_customer_data_otp', to='partnership.PartnershipCustomerData'),
        ),
    ]
