# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-03-10 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='partnershipsessioninformation',
            name='customer_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
