# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-03-08 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='partnershipconfig',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnershipconfig',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
