# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-03-01 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnershipapilog',
            name='partnership_config',
        ),
        migrations.AddField(
            model_name='partnershipapilog',
            name='api_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnershipapilog',
            name='request_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
