# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-03-16 03:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RenameField(
            model_name='fdcinquiryloan',
            old_name='id_pinjaman',
            new_name='fdc_id',
        ),
        migrations.RenameField(
            model_name='fdcinquiryloan',
            old_name='syariah',
            new_name='pendanaan_syariah',
        ),
    ]
