# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-03-15 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardTransaction',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='credit_card_transaction_id', primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField()),
                ('fee', models.BigIntegerField()),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('reference_number', models.TextField()),
                ('bank_reference', models.TextField()),
                ('terminal_type', models.TextField()),
                ('terminal_id', models.TextField()),
                ('terminal_location', models.TextField()),
                ('merchant_id', models.TextField()),
                ('acquire_bank_code', models.TextField()),
                ('destination_bank_code', models.TextField(blank=True, null=True)),
                ('destination_account_number', models.TextField(blank=True, null=True)),
                ('destination_account_name', models.TextField(blank=True, null=True)),
                ('biller_code', models.TextField(blank=True, null=True)),
                ('biller_name', models.TextField(blank=True, null=True)),
                ('customer_id', models.TextField(blank=True, null=True)),
                ('hash_code', models.TextField(blank=True, null=True)),
                ('transaction_status', models.TextField(blank=True, null=True)),
                ('transaction_type', models.TextField(blank=True, null=True)),
                ('credit_card_application', models.ForeignKey(blank=True, db_column='credit_card_application_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='credit_card.CreditCardApplication')),
                ('loan', juloserver.julocore.customized_psycopg2.models.BigForeignKey(blank=True, db_column='loan_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Loan')),
            ],
            options={
                'db_table': 'credit_card_transaction',
            },
        ),
    ]
