# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-03-15 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='cfsassignmentverification',
            name='locked_by',
            field=models.ForeignKey(blank=True, db_column='locked_by_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cfs_assignment_verification_locked', to='julo.Agent'),
        ),
    ]
