# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-04-01 10:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='virtual_account',
            field=models.CharField(blank=True, db_index=True, max_length=50, validators=[django.core.validators.RegexValidator(message='Virtual account has to be numeric digits', regex='^[0-9]+$')]),
        ),
    ]
