# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-03-31 03:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_size',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Harus lebih besar atau sama dengan 1')]),
        ),
    ]
