# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-03-24 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaylaterTransactionDetails',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='paylater_transaction_details_id', primary_key=True, serialize=False)),
                ('merchant_name', models.CharField(max_length=255)),
                ('product_name', models.TextField(blank=True, null=True)),
                ('product_qty', models.IntegerField(default=0)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('product_price', models.FloatField(blank=True, null=True)),
                ('admin_fee', models.FloatField(blank=True, null=True)),
                ('delivery_fee', models.FloatField(blank=True, null=True)),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('application', juloserver.julocore.customized_psycopg2.models.BigForeignKey(blank=True, db_column='application_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Application')),
            ],
            options={
                'db_table': 'paylater_transaction_details',
            },
        ),
    ]
