# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-04-05 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='autodebetbenefit',
            name='pre_assigned_benefit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autodebetbenefit',
            name='benefit_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autodebetbenefit',
            name='benefit_value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
