# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-04-04 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='collectionhiseasoncampaignbanner',
            name='blog_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
