# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-04-18 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='reminderemailsetting',
            name='email_type',
            field=models.CharField(choices=[('REPAYMENT', 'Repayment'), ('OTHER', 'Other')], default='REPAYMENT', max_length=20, unique=True, verbose_name='Tipe Reminder'),
        ),
        migrations.AlterField(
            model_name='reminderemailsetting',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
