# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-05-10 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='ovorepaymenttransaction',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
