# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-05-12 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='sdbpjsprofilescrape',
            name='identity_number',
            field=models.TextField(),
        ),
    ]
