# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-05-11 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaqCheckout',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='faq_checkout_id', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order_priority', models.IntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'faq_checkout',
                'ordering': ('order_priority', 'visible'),
            },
        ),
    ]
