# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-05-23 04:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerLoanSimulations',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='partner_loan_simulation_id', primary_key=True, serialize=False)),
                ('interest_rate', models.FloatField(help_text='In percentage, if 2% should be 0.02')),
                ('tenure', models.IntegerField(help_text='In months')),
                ('is_active', models.BooleanField(default=True)),
                ('origination_rate', models.FloatField(help_text='In percentage, if 2% should be 0.02')),
                ('partner', models.ForeignKey(db_column='partner_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='loan_simulations', to='julo.Partner')),
            ],
            options={
                'db_table': 'partner_loan_simulations',
            },
        ),
    ]
