# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-05-27 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnershipUserOTPAction',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='partnership_user_otp_action_id', primary_key=True, serialize=False)),
                ('is_used', models.BooleanField(default=False)),
                ('action_logs', models.TextField(blank=True, null=True)),
                ('otp_request', models.OneToOneField(db_column='partner_otp_action_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='partner_otp_action', to='julo.OtpRequest')),
            ],
            options={
                'db_table': 'partnership_user_otp_action',
            },
        ),
    ]
