# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-05-20 06:50
from __future__ import unicode_literals

from django.db import migrations
import juloserver.julo.fields


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerreferral',
            name='cust_email',
            field=juloserver.julo.fields.EmailLowerCaseField(blank=True, db_index=True, max_length=254, null=True),
        ),
    ]
