# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-05-24 08:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcardapplication',
            name='unblock_eligibility',
        ),
    ]
