# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-06-07 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaylaterTransaction',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='paylater_transaction_id', primary_key=True, serialize=False)),
                ('partner_reference_id', models.TextField()),
                ('transaction_amount', models.FloatField()),
                ('kodepos', models.TextField(blank=True, null=True)),
                ('kabupaten', models.TextField(blank=True, null=True)),
                ('provinsi', models.TextField(blank=True, null=True)),
                ('paylater_transaction_xid', models.BigIntegerField(db_index=True, unique=True)),
            ],
            options={
                'db_table': 'paylater_transaction',
            },
        ),
        migrations.CreateModel(
            name='PaylaterTransactionStatus',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='paylater_transaction_status_id',
                                        primary_key=True, serialize=False)),
                ('transaction_status', models.CharField(choices=[('initiate', 'Initiated'),
                                                                 ('in_progress', 'In Progress'),
                                                                 ('success', 'Success'),
                                                                 ('cancel', 'Cancelled')],
                                                        default='initiate', max_length=50)),

                ('paylater_transaction', models.OneToOneField(db_column='paylater_transaction_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='paylater_transaction_status', to='partnership.PaylaterTransaction')),
            ],
            options={
                'db_table': 'paylater_transaction_status',
            },
        ),
        migrations.AlterField(
            model_name='paylatertransactiondetails',
            name='product_price',
            field=models.FloatField(),
        ),
        migrations.RemoveField(
            model_name='paylatertransactiondetails',
            name='admin_fee',
        ),
        migrations.RemoveField(
            model_name='paylatertransactiondetails',
            name='application',
        ),
        migrations.RemoveField(
            model_name='paylatertransactiondetails',
            name='delivery_fee',
        ),
        migrations.RemoveField(
            model_name='paylatertransactiondetails',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='paylatertransactiondetails',
            name='total_price',
        ),
    ]
