# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-06-09 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='totalactionpoints',
            name='point',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
