# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-06-07 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='paylatertransactiondetails',
            name='paylater_transaction',
            field=models.ForeignKey(db_column='paylater_transaction_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='paylater_transaction_details', to='partnership.PaylaterTransaction'),
        ),
    ]
