# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-06-08 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_source',
            field=models.BigIntegerField(db_column='document_source_id', db_index=True),
        ),
    ]
