# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-06-08 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerloansimulations',
            name='partner',
        ),
        migrations.AddField(
            model_name='partnerloansimulations',
            name='partnership_config',
            field=models.ForeignKey(blank=True, db_column='partnership_config_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='loan_simulations', to='partnership.PartnershipConfig'),
        ),
        migrations.AddField(
            model_name='partnershipconfig',
            name='is_show_interest_in_loan_simulations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnershipconfig',
            name='is_show_loan_simulations',
            field=models.BooleanField(default=False),
        ),
    ]
