# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-06-16 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreLoginCheckPaylater',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='pre_login_check_paylater_id', primary_key=True, serialize=False)),
                ('phone_number', models.TextField(db_index=True)),
                ('paylater_transaction', models.ForeignKey(db_column='paylater_transaction_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pre_login_check_paylaters', to='partnership.PaylaterTransaction')),
            ],
            options={
                'db_table': 'pre_login_check_paylater',
            },
        ),
        migrations.CreateModel(
            name='PreLoginCheckPaylaterAttempt',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='pre_login_check_paylater_attempt_id', primary_key=True, serialize=False)),
                ('attempt', models.IntegerField()),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('pre_login_check_paylater', models.OneToOneField(db_column='pre_login_check_paylater_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pre_login_check_paylater_attempt', to='partnership.PreLoginCheckPaylater')),
            ],
            options={
                'db_table': 'pre_login_check_paylater_attempt',
            },
        ),
    ]
