# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-06-23 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='partnershiprepaymentupload',
            name='account_payment_id',
            field=models.ForeignKey(db_column='account_payment_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account_payment.AccountPayment'),
        ),
        migrations.AlterField(
            model_name='partnershiprepaymentupload',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
