# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-06-15 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaylaterTransactionLoan',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='paylater_transaction_loan_id', primary_key=True, serialize=False)),
                ('loan', juloserver.julocore.customized_psycopg2.models.BigOneToOneField(blank=True, db_column='loan_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='paylater_transaction_loan', to='julo.Loan')),
                ('paylater_transaction', models.OneToOneField(db_column='paylater_transaction_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_loan', to='partnership.PaylaterTransaction')),
            ],
            options={
                'db_table': 'paylater_transaction_loan',
            },
        ),
    ]
