# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-06-30 07:20
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutrequest',
            name='receipt',
        ),
        migrations.AddField(
            model_name='checkoutrequest',
            name='receipt_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=None, null=True, size=None),
        ),
    ]
