# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-07-05 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='paylatertransaction',
            name='cart_amount',
            field=models.FloatField(default=0, help_text='This field should be filled based on TransactionDetails price * qty'),
        ),
    ]
