# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-07-11 04:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoengageCustomerInstallHistory',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', juloserver.julocore.customized_psycopg2.models.BigAutoField(db_column='moengage_customer_install_history_id', primary_key=True, serialize=False)),
                ('event_code', models.TextField()),
                ('campaign_code', models.TextField(blank=True, null=True)),
                ('event_time', models.DateTimeField()),
                ('application', juloserver.julocore.customized_psycopg2.models.BigForeignKey(blank=True, db_column='application_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Application')),
                ('customer', juloserver.julocore.customized_psycopg2.models.BigForeignKey(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Customer')),
            ],
            options={
                'db_table': 'moengage_customer_install_history',
            },
        ),
    ]
