# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-07-13 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='recipients',
            field=models.TextField(blank=True, help_text='please insert like this format: julo@julofinance.com, julo2@finance.com', null=True),
        ),
    ]
