# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-08-01 04:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RemoveField(
            model_name='ptp',
            name='ptp_paid_amount',
        ),
    ]
