# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-07-28 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import juloserver.employee_financing.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmImageWebForm',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='employee_financing_image_id', primary_key=True, serialize=False)),
                ('image_source', models.BigIntegerField(db_column='image_source', help_text='Id from Web Form Application')),
                ('service', models.CharField(choices=[('s3', 's3'), ('oss', 'oss')], default='oss', max_length=50)),
                ('url', models.CharField(max_length=200)),
                ('image_type', models.CharField(choices=[('ktp_self', 'KTP'), ('selfie', 'Selfie')], max_length=50)),
                ('image', models.ImageField(blank=True, db_column='internal_path', null=True, upload_to=juloserver.employee_financing.models.upload_to)),
            ],
            options={
                'db_table': 'employee_financing_web_form_image',
            },
        ),
        migrations.AddField(
            model_name='emfinancingwfapplication',
            name='couple_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='emfinancingwfapplication',
            name='couple_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
