# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-08-03 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='bonzascoringresult',
            name='is_first_loan',
            field=models.BooleanField(default=False),
        ),
    ]
