# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-08-12 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='partnershipconfig',
            name='historical_transaction_date_count',
            field=models.IntegerField(default=30, help_text='This field is use to check if there are historical transaction is found on the range of the current_date - {value} of this field. \nExample: 30 Aug and the value for this field is 30. So we will check if there are historical transaction from 1 Aug - 30 Aug'),
        ),
        migrations.AddField(
            model_name='partnershipconfig',
            name='historical_transaction_month_duration',
            field=models.IntegerField(default=6, help_text='This field is use to get the start date for the merchant historical transaction from the founded the end_date. \nExample: the latest transaction date found is 1 August and historical_transaction_month_duration = 6. Then we set the start date from 1 August to 6 months before that'),
        ),
    ]
