# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-08-22 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutrequest',
            name='cashback_transaction_id',
        ),
    ]
