# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-09-01 03:39
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models
from juloserver.followthemoney.models import LoanAgreementTemplate

def remove_none_lender_on_loan_agreement(apps, _schema_editor):
    LoanAgreementTemplate.objects.filter(lender__isnull=True).all().delete()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(remove_none_lender_on_loan_agreement, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='loanagreementtemplate',
            name='lender',
            field=models.ForeignKey(db_column='lender_id', on_delete=django.db.models.deletion.DO_NOTHING, to='followthemoney.LenderCurrent'),
        ),
    ]
