# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-09-08 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='accepted_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
