# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-09-02 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutrequest',
            name='checkout_amount',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
