# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-09-26 06:59
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LendeastDataMonthly',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='lendeast_data_monthly_id', primary_key=True, serialize=False)),
                ('data_date', models.DateField()),
                ('loan_status', models.TextField()),
                ('loan_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('loan', juloserver.julocore.customized_psycopg2.models.BigForeignKey(db_column='loan_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Loan')),
            ],
            options={
                'db_table': 'lendeast_data_monthly',
            },
        ),
    ]
