# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-10-12 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PdamOperator',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='pdam_operator_id', primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('description', models.TextField()),
                ('enabled', models.TextField()),
            ],
            options={
                'db_table': 'pdam_operator',
            },
        ),
    ]
