# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-10-12 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='partnerloanrequest',
            name='partner_origin_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
