# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-10-13 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='faqitem',
            name='show_security_faq_report_button',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faqsection',
            name='is_security_faq',
            field=models.BooleanField(default=False),
        ),
    ]
