# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-10-13 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='loginattempt',
            name='app_version',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
