# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-10-25 08:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='ptp',
            name='ptp_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.PTP'),
        ),
    ]
