# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-11-29 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PdCollectionModelResultExclude',
            fields=[
                ('id', models.AutoField(db_column='pd_collection_model_result_exclude_id', primary_key=True, serialize=False)),
                ('cdate', models.DateTimeField(auto_now=True)),
                ('model_version', models.TextField(blank=True, null=True)),
                ('prediction_before_call', models.FloatField(db_column='prediction_before_call')),
                ('prediction_after_call', models.FloatField(db_column='prediction_after_call')),
                ('due_amount', models.BigIntegerField()),
                ('range_from_due_date', models.TextField(blank=True, null=True)),
                ('excluded_from_bucket', models.BooleanField()),
                ('sort_method', models.TextField(blank=True, null=True)),
                ('sort_rank', models.IntegerField()),
                ('prediction_date', models.DateField(blank=True, db_column='predict_date', null=True)),
            ],
            options={
                'db_table': '"ana"."pd_collection_model_result_exclude"',
                'managed': False,
            },
        ),
    ]
