# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-12-07 06:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    state_operations = [
        migrations.AlterField(
            model_name='warningletterdata',
            name='shortened_url',
            field=models.ForeignKey(blank=True, db_column='shortened_url_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='urlshortener.ShortenedUrl'),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=state_operations
        )
    ]
