# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-12-14 04:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DanaApplicationReference',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', juloserver.julocore.customized_psycopg2.models.BigAutoField(db_column='dana_application_reference_id', primary_key=True, serialize=False)),
                ('partner_reference_no', models.TextField(db_index=True, help_text='This partnerReferenceNo from Dana', unique=True)),
                ('reference_no', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('application', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='dana_applications_reference', to='julo.Application')),
            ],
            options={
                'db_table': 'dana_application_reference',
            },
        ),
        migrations.CreateModel(
            name='DanaCustomerData',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', juloserver.julocore.customized_psycopg2.models.BigAutoField(db_column='dana_customer_id', primary_key=True, serialize=False)),
                ('dana_customer_identifier', models.TextField(help_text='This customerId payload from Dana', unique=True)),
                ('mobile_number', models.CharField(max_length=16)),
                ('nik', models.CharField(help_text='This cardId payload from Dana', max_length=16, validators=[django.core.validators.RegexValidator(message='characters not allowed', regex='^[ -~]+$'), django.core.validators.RegexValidator(message='KTP has to be 16 numeric digits', regex='^[0-9]{16}$')])),
                ('full_name', models.CharField(help_text='This cardName payload from Dana', max_length=255)),
                ('proposed_credit_limit', models.FloatField()),
                ('registration_time', models.DateTimeField()),
                ('selfie_image_url', models.TextField()),
                ('ktp_image_url', models.TextField()),
                ('credit_score', models.IntegerField(blank=True, null=True)),
                ('lender_product_id', models.IntegerField(blank=True, null=True)),
                ('app_id', models.IntegerField(blank=True, null=True)),
                ('account', juloserver.julocore.customized_psycopg2.models.BigOneToOneField(blank=True, db_column='account_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dana_customer_data', to='account.Account')),
                ('customer', juloserver.julocore.customized_psycopg2.models.BigForeignKey(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dana_customers_data', to='julo.Customer')),
                ('partner', models.ForeignKey(db_column='partner_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='dana_customers_data', to='julo.Partner')),
            ],
            options={
                'db_table': 'dana_customer_data',
            },
        ),
    ]
