# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-12-08 14:24
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FraudFlag',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', juloserver.julocore.customized_psycopg2.models.BigAutoField(db_column='fraud_flag_id', primary_key=True, serialize=False)),
                ('fraud_type', models.TextField(db_index=True)),
                ('flag_source_type', models.TextField()),
                ('flag_source_id', models.TextField(db_index=True)),
                ('trigger', models.TextField()),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fraud_flag',
            },
        ),
    ]
