# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-12-20 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionBucketInhouseVendor',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='collection_bucket_inhouse_vendor_id', primary_key=True, serialize=False)),
                ('bucket', models.TextField(blank=True, null=True)),
                ('vendor', models.BooleanField(default=False)),
                ('account_payment', models.ForeignKey(blank=True, db_column='account_payment_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account_payment.AccountPayment')),
            ],
            options={
                'db_table': 'collection_bucket_inhouse_vendor',
            },
        ),
    ]
