# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-12-20 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DanaLoanReference',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', juloserver.julocore.customized_psycopg2.models.BigAutoField(db_column='dana_loan_reference_id', primary_key=True, serialize=False)),
                ('partner_reference_no', models.TextField(db_index=True, help_text='This partnerReferenceNo from Dana', unique=True)),
                ('reference_no', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('loan', juloserver.julocore.customized_psycopg2.models.BigOneToOneField(db_column='loan_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Loan')),
            ],
            options={
                'db_table': 'dana_loan_reference',
            },
        ),
        migrations.CreateModel(
            name='DanaPaymentBill',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', juloserver.julocore.customized_psycopg2.models.BigAutoField(db_column='dana_payment_bill_id', primary_key=True, serialize=False)),
                ('bill_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('principal_amount', models.BigIntegerField()),
                ('interest_fee_amount', models.BigIntegerField()),
                ('late_fee_amount', models.BigIntegerField(default=0)),
                ('total_amount', models.BigIntegerField()),
                ('due_date', models.DateField()),
                ('payment', juloserver.julocore.customized_psycopg2.models.BigOneToOneField(db_column='payment_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Payment')),
            ],
            options={
                'db_table': 'dana_payment_bill',
            },
        ),
    ]
