# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-12-30 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='channelingeligibilitystatus',
            name='version',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='channelingeligibilitystatushistory',
            name='version',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='channelingloanstatus',
            name='channeling_interest_percentage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
