# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-12-29 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='partnershipconfig',
            name='order_validation',
            field=models.BooleanField(default=False, help_text='This only used for holding partner loan status to 211'),
        ),
    ]
