# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-01-03 03:11
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrabConstructedCollectionDialerTemporaryData',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='grab_construct_collection_id', primary_key=True, serialize=False)),
                ('application_id', models.BigIntegerField(blank=True, null=True)),
                ('customer_id', models.BigIntegerField(blank=True, null=True)),
                ('nama_customer', models.TextField(blank=True, null=True)),
                ('nama_perusahaan', models.TextField(blank=True, null=True)),
                ('posisi_karyawan', models.TextField(blank=True, null=True)),
                ('nama_pasangan', models.TextField(blank=True, null=True)),
                ('nama_kerabat', models.TextField(blank=True, null=True)),
                ('hubungan_kerabat', models.TextField(blank=True, null=True)),
                ('jenis_kelamin', models.TextField(blank=True, null=True)),
                ('tgl_lahir', models.TextField(blank=True, null=True)),
                ('tgl_gajian', models.TextField(blank=True, null=True)),
                ('tujuan_pinjaman', models.TextField(blank=True, null=True)),
                ('tanggal_jatuh_tempo', models.TextField(blank=True, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('kota', models.TextField(blank=True, null=True)),
                ('tipe_produk', models.TextField(blank=True, null=True)),
                ('partner_name', models.TextField(blank=True, null=True)),
                ('account_payment_id', models.BigIntegerField(blank=True, null=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('dpd', models.IntegerField(blank=True, null=True)),
                ('team', models.TextField(blank=True, null=True)),
                ('payment_id', models.BigIntegerField(blank=True, null=True)),
                ('loan_id', models.BigIntegerField(blank=True, null=True)),
                ('mobile_phone_1', models.TextField(blank=True, null=True)),
                ('mobile_phone_2', models.TextField(blank=True, null=True)),
                ('telp_perusahaan', models.TextField(blank=True, null=True)),
                ('angsuran', models.IntegerField(blank=True, null=True)),
                ('denda', models.IntegerField(blank=True, null=True)),
                ('outstanding', models.BigIntegerField(blank=True, null=True)),
                ('angsuran_ke', models.TextField(blank=True, null=True)),
                ('no_telp_pasangan', models.TextField(blank=True, null=True)),
                ('no_telp_kerabat', models.TextField(blank=True, null=True)),
                ('tgl_upload', models.TextField(blank=True, null=True)),
                ('va_bca', models.TextField(blank=True, null=True)),
                ('va_permata', models.TextField(blank=True, null=True)),
                ('va_maybank', models.TextField(blank=True, null=True)),
                ('va_alfamart', models.TextField(blank=True, null=True)),
                ('va_indomaret', models.TextField(blank=True, null=True)),
                ('campaign', models.TextField(blank=True, null=True)),
                ('jumlah_pinjaman', models.BigIntegerField(blank=True, null=True)),
                ('tenor', models.TextField(blank=True, null=True)),
                ('last_agent', models.TextField(blank=True, null=True)),
                ('last_call_status', models.TextField(blank=True, null=True)),
                ('customer_bucket_type', models.TextField(blank=True, null=True)),
                ('zip_code', models.TextField(blank=True, null=True)),
                ('disbursement_period', models.TextField(blank=True, null=True)),
                ('repeat_or_first_time', models.TextField(blank=True, null=True)),
                ('account_id', models.BigIntegerField(blank=True, null=True)),
                ('is_j1', models.NullBooleanField()),
                ('Autodebit', models.TextField(blank=True, null=True)),
                ('refinancing_status', models.TextField(blank=True, null=True)),
                ('activation_amount', models.TextField(blank=True, null=True)),
                ('program_expiry_date', models.TextField(blank=True, null=True)),
                ('promo_untuk_customer', models.TextField(blank=True, null=True)),
                ('last_pay_date', models.TextField(blank=True, null=True)),
                ('last_pay_amount', models.BigIntegerField(blank=True, null=True)),
                ('status_tagihan', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'grab_constructed_collection_dialer',
            },
        ),
    ]
