# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-01-09 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='grabloandata',
            name='early_write_off_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grabloandata',
            name='restructured_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
