# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-01-10 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrabCustomerReferralWhitelistHistory',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='grab_customer_referral_whitelist_history_id', primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Customer')),
            ],
            options={
                'db_table': 'grab_customer_referral_whitelist_history',
            },
        ),
        migrations.CreateModel(
            name='GrabReferralWhitelistProgram',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='grab_referral_whitelist_program_id', primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'grab_referral_whitelist_program',
            },
        ),
        migrations.AddField(
            model_name='grabcustomerreferralwhitelisthistory',
            name='grab_referral_whitelist_program',
            field=models.ForeignKey(blank=True, db_column='grab_referral_whitelist_program_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='grab.GrabReferralWhitelistProgram'),
        ),
    ]
