# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-01-10 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='danarepaymentreference',
            name='bill_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='danarepaymentreference',
            name='bill_status',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='danarepaymentreference',
            name='customer_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='danarepaymentreference',
            name='interest_fee_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='danarepaymentreference',
            name='late_fee_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='danarepaymentreference',
            name='principal_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='danarepaymentreference',
            name='total_repayment_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='danarepaymentreference',
            name='partner_reference_no',
            field=models.TextField(db_index=True, help_text='This partnerReferenceNo from Dana'),
        ),
    ]
