# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-01-11 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='traintransaction',
            name='admin_fee',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
