# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-01-25 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrabIntelixCScore',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='grab_intelix_c_score_id', primary_key=True, serialize=False)),
                ('loan_xid', models.BigIntegerField(blank=True, null=True)),
                ('grab_user_id', models.TextField(blank=True, null=True)),
                ('vehicle_type', models.TextField(blank=True, null=True)),
                ('cscore', models.IntegerField()),
                ('prediction_date', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Customer')),
            ],
            options={
                'db_table': 'grab_intelix_c_score',
            },
        ),
    ]
