# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-01-19 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GopayAccountLinkStatus',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='gopay_account_link_status_id', primary_key=True, serialize=False)),
                ('pay_account_id', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('registration_url_id', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, db_column='account_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.Account')),
            ],
            options={
                'db_table': 'gopay_account_link_status',
            },
        ),
        migrations.CreateModel(
            name='GopayCustomerBalance',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='gopay_customer_balance_id', primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False)),
                ('balance', models.BigIntegerField(default=0)),
                ('account', models.ForeignKey(blank=True, db_column='account_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.Account')),
                ('gopay_account', models.ForeignKey(blank=True, db_column='gopay_account_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payback.GopayAccountLinkStatus')),
            ],
            options={
                'db_table': 'gopay_customer_balance',
            },
        )
    ]
