# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-01-27 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingEligibilityChecking',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='onboarding_eligibility_checking_id', primary_key=True, serialize=False)),
                ('fdc_check', models.BigIntegerField(null=True)),
                ('bpjs_check', models.BigIntegerField(null=True)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Customer')),
            ],
            options={
                'db_table': 'onboarding_eligibility_checking',
            },
        ),
        migrations.AddField(
            model_name='fdcinquiry',
            name='customer',
            field=models.ForeignKey(db_column='customer_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Customer'),
        ),
        migrations.AlterField(
            model_name='fdcinquiry',
            name='application',
            field=models.ForeignKey(db_column='application_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Application'),
        ),
    ]
