# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-02-07 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmulatorCheckEligibilityLog',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', juloserver.julocore.customized_psycopg2.models.BigAutoField(db_column='emulator_check_eligibility_log_id', primary_key=True, serialize=False)),
                ('is_eligible', models.NullBooleanField()),
                ('application_status', models.IntegerField()),
                ('passed_binary_checks', models.NullBooleanField()),
                ('remarks', models.TextField()),
                ('application', juloserver.julocore.customized_psycopg2.models.BigForeignKey(db_column='application_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Application')),
            ],
            options={
                'db_table': 'emulator_check_eligibility_log',
            },
        ),
    ]
