# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-02-04 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DanaRepaymentReferenceHistory',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', juloserver.julocore.customized_psycopg2.models.BigAutoField(db_column='dana_repayment_reference_history_id', primary_key=True, serialize=False)),
                ('repaid_time', models.DateTimeField(blank=True, null=True)),
                ('bill_id', models.CharField(blank=True, max_length=64, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=64, null=True)),
                ('bill_status', models.CharField(blank=True, max_length=64, null=True)),
                ('principal_amount', models.BigIntegerField(default=0)),
                ('interest_fee_amount', models.BigIntegerField(default=0)),
                ('late_fee_amount', models.BigIntegerField(default=0)),
                ('total_repayment_amount', models.BigIntegerField(default=0)),
                ('repayment_reference', juloserver.julocore.customized_psycopg2.models.BigForeignKey(db_column='dana_repayment_reference_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='dana_repayment_reference_history', to='dana.DanaRepaymentReference')),
                ('upload_async_state', juloserver.julocore.customized_psycopg2.models.BigForeignKey(blank=True, db_column='upload_async_state_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.UploadAsyncState')),
            ],
            options={
                'db_table': 'dana_repayment_reference_history',
            },
        ),
    ]
