# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-02-01 07:28
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethodInstruction',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='payment_method_instruction_id', primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('content', ckeditor.fields.RichTextField()),
                ('is_active', models.BooleanField(default=False)),
                ('global_payment_method', models.ForeignKey(db_column='global_payment_method_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.GlobalPaymentMethod')),
            ],
            options={
                'db_table': 'payment_method_instruction',
            },
        ),
    ]
