# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-02-13 10:06
from __future__ import unicode_literals

from django.core.exceptions import FieldDoesNotExist
from django.db import migrations, models

from juloserver.julo.models import DashboardBuckets


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AddField(
            model_name='dashboardbuckets',
            name='app_121_jstarter',
            field=models.IntegerField(default=0),
        )
    ]
