# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-02-27 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingeligibilitychecking',
            name='bpjs_check',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='onboardingeligibilitychecking',
            name='dukcapil_check',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='onboardingeligibilitychecking',
            name='fdc_check',
            field=models.SmallIntegerField(null=True),
        ),
    ]
