# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-02-27 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingeligibilitychecking',
            name='application',
            field=juloserver.julocore.customized_psycopg2.models.BigForeignKey(blank=True, db_column='application_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Application'),
        ),
        migrations.AddField(
            model_name='onboardingeligibilitychecking',
            name='dukcapil_check',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='onboardingeligibilitychecking',
            name='dukcapil_response',
            field=models.ForeignKey(blank=True, db_column='dukcapil_response_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='personal_data_verification.DukcapilResponse'),
        ),
    ]
