# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-02-27 04:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingeligibilitychecking',
            name='bpjs_api_log',
            field=models.ForeignKey(db_column='bpjs_api_log_id', null=True, blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bpjs.BpjsAPILog'),
        ),
        migrations.AddField(
            model_name='onboardingeligibilitychecking',
            name='fdc_inquiry',
            field=models.ForeignKey(db_column='fdc_inquiry_id', null=True, blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.FDCInquiry'),
        ),
    ]
