# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-02-27 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='danaloanreference',
            name='amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='danaloanreference',
            name='credit_usage_mutation',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='danaloanreference',
            name='customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='danaloanreference',
            name='lender_product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='danaloanreference',
            name='merchant_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='danaloanreference',
            name='order_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='danaloanreference',
            name='trans_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
