# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-03-08 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='private_key_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='encrypted_private_key_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
