# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-03-08 06:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='key',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='key',
            name='is_latest',
        ),
    ]
