# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-03-10 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='cootekrobocall',
            name='time_to_end',
            field=models.TimeField(default=None, null=True),
        ),
    ]
