# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-03-28 03:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceConsolidation',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='balance_consolidation_id', primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('fullname', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='characters not allowed', regex='^[ -~]+$')])),
                ('loan_agreement_number', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='characters not allowed', regex='^[ -~]+$')])),
                ('loan_principal_amount', models.BigIntegerField()),
                ('loan_outstanding_amount', models.BigIntegerField()),
                ('disbursement_date', models.DateField()),
                ('due_date', models.DateField()),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_account_number', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Virtual account has to be numeric digits', regex='^[0-9]+$')])),
                ('name_in_bank', models.CharField(max_length=100)),
                ('customer', juloserver.julocore.customized_psycopg2.models.BigForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Customer')),
            ],
            options={
                'db_table': 'balance_consolidation',
            },
        ),
        migrations.CreateModel(
            name='BalanceConsolidationVerification',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='balance_consolidation_verification_id', primary_key=True, serialize=False)),
                ('validation_status', models.CharField(choices=[('on_review', 'on_review'), ('approved', 'approved'), ('rejected', 'rejected'), ('abandoned', 'abandoned')], max_length=50, validators=[django.core.validators.RegexValidator(message='characters not allowed', regex='^[ -~]+$')])),
                ('note', models.CharField(blank=True, max_length=1000, null=True)),
                ('agent', models.ForeignKey(blank=True, db_column='agent_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Agent')),
                ('balance_consolidation', models.OneToOneField(db_column='balance_consolidation_id', on_delete=django.db.models.deletion.DO_NOTHING, to='balance_consolidation.BalanceConsolidation')),
                ('loan', models.OneToOneField(blank=True, db_column='loan_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Loan')),
                ('locked_by', models.ForeignKey(blank=True, db_column='locked_by_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='balance_consolidation_verification_locked', to='julo.Agent')),
                ('name_bank_validation', models.OneToOneField(blank=True, db_column='name_bank_validation_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='disbursement.NameBankValidation')),
            ],
            options={
                'db_table': 'balance_consolidation_verification',
            },
        ),
        migrations.CreateModel(
            name='BalanceConsolidationVerificationHistory',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='balance_consolidation_verification_history_id', primary_key=True, serialize=False)),
                ('field_name', models.TextField()),
                ('value_old', models.TextField(blank=True, null=True)),
                ('value_new', models.TextField()),
                ('agent', models.ForeignKey(db_column='agent_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Agent')),
                ('balance_consolidation_verification', models.ForeignKey(db_column='balance_consolidation_verification_id', on_delete=django.db.models.deletion.DO_NOTHING, to='balance_consolidation.BalanceConsolidationVerification')),
            ],
            options={
                'db_table': 'balance_consolidation_verification_history',
            },
        ),
        migrations.CreateModel(
            name='Fintech',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='fintech_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'fintech',
            },
        ),
        migrations.AddField(
            model_name='balanceconsolidation',
            name='fintech',
            field=models.ForeignKey(db_column='fintech_id', on_delete=django.db.models.deletion.DO_NOTHING, to='balance_consolidation.Fintech'),
        ),
        migrations.AddField(
            model_name='balanceconsolidation',
            name='loan_agreement_document',
            field=models.ForeignKey(db_column='document_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Document'),
        ),
    ]
