# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-03-21 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrabDefencePredictRawResult',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', juloserver.julocore.customized_psycopg2.models.BigAutoField(db_column='grab_defence_predict_raw_result_id', primary_key=True, serialize=False)),
                ('raw_response', models.TextField()),
                ('response_time', models.PositiveIntegerField(blank=True, null=True)),
                ('response_code', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('grab_defence_verdict_result', juloserver.julocore.customized_psycopg2.models.BigForeignKey(blank=True, db_column='grab_defence_verdict_result_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fraud_score.GrabDefenceVerdictResult')),
            ],
            options={
                'db_table': 'grab_defence_predict_raw_result',
            },
        ),
    ]
