# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-04-01 03:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AxiataTemporaryData',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='axiata_temporary_data_id', primary_key=True, serialize=False)),
                ('acceptance_date', models.DateTimeField(blank=True, null=True)),
                ('partner_application_date', models.DateTimeField(blank=True, null=True)),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('disbursement_date', models.DateTimeField(blank=True, null=True)),
                ('disbursement_time', models.TimeField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True)),
                ('first_payment_date', models.DateField(blank=True, null=True)),
                ('partner_score_grade', models.CharField(default='A', max_length=50)),
                ('insurance_fee', models.BigIntegerField(default=0)),
                ('funder', models.CharField(default='ADCI', max_length=50)),
                ('partner_product_line', models.CharField(default='ISCF', max_length=50)),
                ('fullname', models.CharField(blank=True, max_length=100, null=True)),
                ('ktp', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='characters not allowed', regex='^[ -~]+$'), django.core.validators.RegexValidator(message='KTP has to be 16 numeric digits', regex='^[0-9]{16}$')])),
                ('brand_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('company_registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('business_category', models.CharField(blank=True, max_length=100, null=True)),
                ('type_of_business', models.CharField(blank=True, default='Perorangan', max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=50, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('address_street_num', models.TextField(blank=True, null=True)),
                ('shops_number', models.CharField(default='1', max_length=50)),
                ('distributor', models.CharField(blank=True, max_length=50, null=True)),
                ('partner_id', models.CharField(blank=True, default='', max_length=10)),
                ('interest_rate', models.FloatField(default=0)),
                ('loan_amount', models.BigIntegerField(default=0)),
                ('loan_duration', models.IntegerField(default=0)),
                ('loan_duration_unit', models.CharField(default='Days', max_length=50)),
                ('monthly_installment', models.FloatField(default=0)),
                ('final_monthly_installment', models.FloatField(default=0)),
                ('reject_reason', models.TextField(blank=True, null=True)),
                ('origination_fee', models.FloatField(blank=True, null=True)),
                ('admin_fee', models.IntegerField(default=0)),
                ('invoice_id', models.CharField(default=0, max_length=50)),
                ('partner_application_id', models.TextField(blank=True, null=True)),
                ('ktp_image', models.TextField(blank=True, null=True)),
                ('selfie_image', models.TextField(blank=True, null=True)),
                ('address_provinsi', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='characters not allowed', regex='^[ -~]+$')])),
                ('address_kabupaten', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='characters not allowed', regex='^[ -~]+$')])),
                ('address_kecamatan', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='characters not allowed', regex='^[ -~]+$')])),
                ('address_kelurahan', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='characters not allowed', regex='^[ -~]+$')])),
                ('address_kodepos', models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator(message='characters not allowed', regex='^[ -~]+$'), django.core.validators.RegexValidator(message='Kode pos has to be 5 numeric digits', regex='^[0-9]{5}$')])),
                ('loan_purpose', models.CharField(default='Modal usaha', max_length=100, verbose_name='Tujuan pinjaman')),
                ('is_uploaded', models.BooleanField(default=False)),
                ('application', models.ForeignKey(blank=True, db_column='application_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Application')),
            ],
            options={
                'db_table': 'axiata_temporary_data',
            },
        ),
        migrations.AddField(
            model_name='axiatacustomerdata',
            name='address_kabupaten',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='characters not allowed', regex='^[ -~]+$')]),
        ),
        migrations.AddField(
            model_name='axiatacustomerdata',
            name='address_kecamatan',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='characters not allowed', regex='^[ -~]+$')]),
        ),
        migrations.AddField(
            model_name='axiatacustomerdata',
            name='address_kelurahan',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='characters not allowed', regex='^[ -~]+$')]),
        ),
        migrations.AddField(
            model_name='axiatacustomerdata',
            name='address_kodepos',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator(message='characters not allowed', regex='^[ -~]+$'), django.core.validators.RegexValidator(message='Kode pos has to be 5 numeric digits', regex='^[0-9]{5}$')]),
        ),
        migrations.AddField(
            model_name='axiatacustomerdata',
            name='address_provinsi',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='characters not allowed', regex='^[ -~]+$')]),
        ),
        migrations.AddField(
            model_name='axiatacustomerdata',
            name='loan_purpose',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tujuan pinjaman'),
        ),
        migrations.AlterField(
            model_name='axiatacustomerdata',
            name='acceptance_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='axiatacustomerdata',
            name='disbursement_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='axiatacustomerdata',
            name='disbursement_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='axiatacustomerdata',
            name='partner_application_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='axiatatemporarydata',
            name='axiata_customer_data',
            field=models.OneToOneField(blank=True, db_column='axiata_customer_data_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sdk.AxiataCustomerData'),
        ),
    ]
