# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-04-03 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='axiatatemporarydata',
            name='acceptance_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='axiatatemporarydata',
            name='disbursement_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='axiatatemporarydata',
            name='disbursement_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='axiatatemporarydata',
            name='partner_application_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
