# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-04-03 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='axiatatemporarydata',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
