# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-03-30 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='ovorepaymenttransaction',
            name='is_checkout_experience',
            field=models.NullBooleanField(),
        ),
    ]
