# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-04-06 11:18
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='balanceconsolidationverification',
            name='account_limit_histories',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
