# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-04-27 04:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    state_operations = [
        migrations.RemoveField(
            model_name='juloshoptransaction',
            name='https_image_url',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[], state_operations=state_operations
        )
    ]
