# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-04-25 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegisterHistory',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='student_register_history_id', primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField()),
                ('new_value', models.TextField()),
                ('new_student_register', models.ForeignKey(blank=True, db_column='new_student_register_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='new_student_register', to='education.StudentRegister')),
                ('old_student_register', models.ForeignKey(blank=True, db_column='old_student_register_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='old_student_register', to='education.StudentRegister')),
            ],
            options={
                'db_table': 'student_register_history',
            },
        ),
    ]
