# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-05-11 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DanaLoanReferenceStatus',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', juloserver.julocore.customized_psycopg2.models.BigAutoField(db_column='dana_loan_status_id', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('success', 'Success'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='success', max_length=50)),
                ('dana_loan_reference', juloserver.julocore.customized_psycopg2.models.BigOneToOneField(db_column='dana_loan_reference_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='dana_loan_status', to='dana.DanaLoanReference')),
            ],
            options={
                'db_table': 'dana_loan_reference_status',
            },
        ),
    ]
