# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-05-03 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='danapaymentbill',
            name='deducted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='danapaymentbill',
            name='deposit_deducted',
            field=models.NullBooleanField(),
        ),
    ]
