# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-05-11 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationNameBankValidationChange',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='application_name_bank_validation_change_id', primary_key=True, serialize=False)),
                ('old_name_bank_validation_id', models.BigIntegerField()),
                ('new_name_bank_validation_id', models.BigIntegerField()),
                ('application', juloserver.julocore.customized_psycopg2.models.BigForeignKey(db_column='application_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Application')),
            ],
            options={
                'db_table': 'application_name_bank_validation_change',
            },
        ),
    ]
