# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-05-09 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='smshistory',
            name='tsp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
