# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-05-25 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousDomain',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='suspicious_domain_id', primary_key=True, serialize=False)),
                ('email_domain', models.TextField()),
                ('reason', models.TextField()),
            ],
            options={
                'db_table': 'suspicious_domain',
            },
        ),
    ]
