# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-05-17 04:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditMatrixRepeat',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='credit_matrix_repeat_id', primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('customer_segment', models.CharField(blank=True, db_index=True, default=None, max_length=50, null=True)),
                ('provision', models.FloatField()),
                ('max_tenure', models.IntegerField(blank=True, null=True)),
                ('min_tenure', models.IntegerField(blank=True, null=True)),
                ('interest', models.FloatField()),
                ('repeat_level', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('total_utilization_rate', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('aging', models.IntegerField(blank=True, default=None, null=True)),
                ('fdc_status', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('version', models.IntegerField(default=1)),
                ('product_line', models.ForeignKey(db_column='product_line_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.ProductLine')),
                ('transaction_method', models.ForeignKey(db_column='transaction_method_id', on_delete=django.db.models.deletion.DO_NOTHING, to='payment_point.TransactionMethod')),
            ],
            options={
                'db_table': 'credit_matrix_repeat',
            },
        ),
        migrations.CreateModel(
            name='CreditMatrixRepeatLoan',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', juloserver.julocore.customized_psycopg2.models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('credit_matrix_repeat', models.ForeignKey(db_column='credit_matrix_repeat_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.CreditMatrixRepeat')),
                ('loan', juloserver.julocore.customized_psycopg2.models.BigForeignKey(db_column='loan_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Loan', unique=True)),
            ],
            options={
                'db_table': 'credit_matrix_repeat_loan',
            },
        ),
    ]
