# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-05-23 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='shopeescoring',
            name='is_passed',
            field=models.NullBooleanField(),
        ),
    ]
