# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-05-24 04:33
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NPSSurvey',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='nps_survey_id', primary_key=True, serialize=False)),
                ('is_access_survey', models.NullBooleanField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0, message='Harus lebih besar atau sama dengan 0'), django.core.validators.MaxValueValidator(10, message='Harus lebih kecil atau sama dengan 10')])),
                ('phone', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('android_id', models.TextField()),
                ('customer', juloserver.julocore.customized_psycopg2.models.BigForeignKey(db_column='customer_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Customer')),
                ('user', models.ForeignKey(db_column='user_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nps_survey',
            },
        ),
    ]
