# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-05-22 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MycroftResult',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='mycroft_result_id', primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('result', models.BooleanField()),
                ('application', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Application')),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Customer')),
            ],
            options={
                'db_table': 'mycroft_result',
            },
        ),
        migrations.CreateModel(
            name='MycroftThreshold',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='mycroft_threshold_id', primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('logical_operator', models.CharField(choices=[('<=', '<='), ('<', '<'), ('>=', '>='), ('>', '>')], max_length=2)),
                ('is_active', models.BooleanField()),
            ],
            options={
                'db_table': 'mycroft_threshold',
            },
        ),
        migrations.AddField(
            model_name='mycroftresult',
            name='mycroft_threshold',
            field=models.ForeignKey(db_column='mycroft_threshold_id', on_delete=django.db.models.deletion.DO_NOTHING, to='application_flow.MycroftThreshold'),
        ),
    ]
