# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-05-31 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnershipUserSession',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='session_id', primary_key=True, serialize=False)),
                ('application_xid', models.TextField(blank=True, null=True)),
                ('paylater_transaction_xid', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('checkout initiated', 'checkout initiated'), ('creating pin', 'creating pin'), ('long form application', 'long form application'), ('application submission', 'application submission'), ('only email/phone number match', 'only email/phone number match'), ('toggle switched on', 'toggle switched on'), ('toggle switched off', 'toggle switched off'), ('login screen', 'login screen'), ('verify otp', 'verify otp'), ('linking completed', 'linking completed'), ('insufficient balance', 'insufficient balance'), ('select duration', 'select duration'), ('transaction summary', 'transaction summary'), ('successful transaction', 'successful transaction'), ('cancelled transaction', 'cancelled transaction')], max_length=100, null=True)),
                ('partner_reference_id', models.TextField()),
                ('partner', models.ForeignKey(db_column='partner_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Partner')),
            ],
            options={
                'db_table': 'partnership_user_session',
            },
        ),
        migrations.CreateModel(
            name='PartnershipUserSessionHistoryDetails',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='partner_session_history_id', primary_key=True, serialize=False)),
                ('status_old', models.CharField(blank=True, choices=[('checkout initiated', 'checkout initiated'), ('creating pin', 'creating pin'), ('long form application', 'long form application'), ('application submission', 'application submission'), ('only email/phone number match', 'only email/phone number match'), ('toggle switched on', 'toggle switched on'), ('toggle switched off', 'toggle switched off'), ('login screen', 'login screen'), ('verify otp', 'verify otp'), ('linking completed', 'linking completed'), ('insufficient balance', 'insufficient balance'), ('select duration', 'select duration'), ('transaction summary', 'transaction summary'), ('successful transaction', 'successful transaction'), ('cancelled transaction', 'cancelled transaction')], max_length=100, null=True)),
                ('status_new', models.CharField(blank=True, choices=[('checkout initiated', 'checkout initiated'), ('creating pin', 'creating pin'), ('long form application', 'long form application'), ('application submission', 'application submission'), ('only email/phone number match', 'only email/phone number match'), ('toggle switched on', 'toggle switched on'), ('toggle switched off', 'toggle switched off'), ('login screen', 'login screen'), ('verify otp', 'verify otp'), ('linking completed', 'linking completed'), ('insufficient balance', 'insufficient balance'), ('select duration', 'select duration'), ('transaction summary', 'transaction summary'), ('successful transaction', 'successful transaction'), ('cancelled transaction', 'cancelled transaction')], max_length=100, null=True)),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='partnership_user_session_history_details', to='partnership.PartnershipUserSession')),
            ],
            options={
                'db_table': 'partnership_user_session_history_details',
            },
        ),
    ]
