# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-06-13 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='calllogpocairudderpds',
            name='call_id',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
