# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-06-23 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='transactionriskycheck',
            name='is_web_location_blocked',
            field=models.NullBooleanField(),
        ),
    ]
