# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-06-21 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProductivityV2',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('type', models.TextField(blank=True, null=True)),
                ('agent_name', models.TextField(blank=True, db_column='agent', null=True)),
                ('local_time_convert', models.DateTimeField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'agent_productivity_v2',
            },
        ),
    ]
