# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-06-21 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='partnershipcustomerdata',
            name='account',
            field=juloserver.julocore.customized_psycopg2.models.BigOneToOneField(blank=True, db_column='account_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='partnership_customer_data', to='account.Account'),
        ),
        migrations.AddField(
            model_name='partnershipcustomerdata',
            name='application',
            field=juloserver.julocore.customized_psycopg2.models.BigOneToOneField(blank=True, db_column='application_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='partnership_customer_data', to='julo.Application'),
        ),
        migrations.AlterField(
            model_name='partnershipcustomerdata',
            name='email_otp_status',
            field=models.CharField(blank=True, choices=[('UNVERIFIED', 'Unverified Email'), ('VERIFIED', 'Verified Email')], default='UNVERIFIED', help_text='this field using for LinkAja', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='partnershipcustomerdata',
            name='last_j1_application_status',
            field=models.CharField(blank=True, help_text='this field using for LinkAja', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='partnershipcustomerdata',
            name='otp_status',
            field=models.CharField(blank=True, choices=[('UNVERIFIED', 'Unverified Phone Number'), ('VERIFIED', 'Verified Phone Number')], default='UNVERIFIED', help_text='this field using for LinkAja', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='partnershipcustomerdata',
            name='token',
            field=models.TextField(blank=True, db_index=True, help_text='this field using for LinkAja', null=True),
        ),
    ]
