# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-06-22 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GopayAutodebetTransaction',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='gopay_autodebet_transaction_id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('subscription_id', models.TextField(blank=True, null=True)),
                ('transaction_id', models.TextField(blank=True, null=True)),
                ('external_transaction_id', models.TextField(blank=True, null=True)),
                ('amount', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('status_desc', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Customer')),
                ('gopay_account', models.ForeignKey(blank=True, db_column='gopay_account_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payback.GopayAccountLinkStatus')),
            ],
            options={
                'db_table': 'gopay_autodebet_transaction',
            },
        ),
    ]
