# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-06-26 08:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SepulsaPaymentPointInquireTracking',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='sepulsa_payment_point_inquire_tracking_id', primary_key=True, serialize=False)),
                ('price', models.BigIntegerField()),
                ('identity_number', models.CharField(max_length=100)),
                ('other_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.DO_NOTHING, to='account.Account')),
                ('sepulsa_product', models.ForeignKey(db_column='sepulsa_product_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.SepulsaProduct')),
                ('sepulsa_transaction', models.ForeignKey(blank=True, db_column='sepulsa_transaction_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.SepulsaTransaction')),
                ('transaction_method', models.ForeignKey(db_column='transaction_method_id', on_delete=django.db.models.deletion.DO_NOTHING, to='payment_point.TransactionMethod')),
            ],
            options={
                'db_table': 'sepulsa_payment_point_inquire_tracking',
            },
        ),
        migrations.RunSQL("ALTER TABLE sepulsa_payment_point_inquire_tracking ALTER COLUMN sepulsa_payment_point_inquire_tracking_id TYPE bigint;"),
    ]
