# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-06-29 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='channelingloanhistory',
            name='date_valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='channelingloanhistory',
            name='date_valid_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
