# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-07-05 07:48
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [

        migrations.AddField(
            model_name='partnershipapplicationdata',
            name='reject_reason',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
