# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-07-06 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='gopayautodebettransaction',
            name='retry_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        )
    ]
