# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-07-17 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='earlyreleaseloanmapping',
            name='is_auto',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='earlyreleaseloanmapping',
            name='experiment',
            field=models.ForeignKey(blank=True, db_column='experiment_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='early_limit_release.EarlyReleaseExperiment'),
        ),
        migrations.AlterField(
            model_name='earlyreleaseloanmapping',
            name='loan',
            field=juloserver.julocore.customized_psycopg2.models.BigForeignKey(db_column='loan_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Loan', unique=True),
        ),
    ]
