# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-08-07 01:44
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FDCDeliveryStatistic',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='fdc_delivery_statistic_id', primary_key=True, serialize=False)),
                ('statistic_loan_generated_at', models.DateTimeField(blank=True, null=True)),
                ('statistic_file_generated_at', models.DateTimeField(blank=True, null=True)),
                ('status_file', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('status_loan', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('quality_loan', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fdc_delivery_statistic',
            },
        ),
    ]
