# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-08-03 07:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOpsBucket',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='sales_ops_bucket_id', primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('scores', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'sales_ops_bucket',
            },
        ),
        migrations.CreateModel(
            name='SalesOpsVendor',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='sales_ops_vendor_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'sales_ops_vendor',
            },
        ),
        migrations.CreateModel(
            name='SalesOpsVendorBucketMapping',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='sales_ops_vendor_bucket_mapping_id', primary_key=True, serialize=False)),
                ('ratio', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('bucket', models.ForeignKey(db_column='sales_ops_bucket_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='vendor_mappings', to='sales_ops.SalesOpsBucket')),
                ('vendor', models.ForeignKey(db_column='sales_ops_vendor_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='bucket_mappings', to='sales_ops.SalesOpsVendor')),
            ],
            options={
                'db_table': 'sales_ops_vendor_bucket_mapping',
            },
        ),
        migrations.AlterUniqueTogether(
            name='salesopsvendorbucketmapping',
            unique_together=set([('vendor', 'bucket')]),
        ),
    ]
