# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-08-07 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='fdcdeliverytemp',
            name='agunan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fdcdeliverytemp',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fdcdeliverytemp',
            name='nama_penjamin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fdcdeliverytemp',
            name='no_agunan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fdcdeliverytemp',
            name='no_hp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fdcdeliverytemp',
            name='tgl_agunan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
