# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-08-23 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='earlyreleasechecking',
            name='checking_type',
            field=models.CharField(choices=[('experimentation', 'Experimentation'), ('paid_on_time', 'Paid on time'), ('pre_requisite', 'Pre-requisite'), ('regular', 'Regular'), ('repeat', 'Repeat'), ('fdc', 'fdc'), ('used_limit', 'Used limit'), ('loan_duration', 'Loan duration')], max_length=255),
        ),
    ]
