# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-08-21 06:57
from __future__ import unicode_literals

from django.db import migrations
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='danaloanreferenceinsufficienthistory',
            name='id',
            field=juloserver.julocore.customized_psycopg2.models.BigAutoField(db_column='dana_loan_reference_insufficient_history_id', primary_key=True, serialize=False),
        ),
    ]
