# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-08-16 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdfyVideoCall',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='idfy_video_call_id', primary_key=True, serialize=False)),
                ('reference_id', models.CharField(blank=True, db_column='reference_id', max_length=50, null=True)),
                ('profile_id', models.CharField(blank=True, db_column='profile_id', max_length=100, null=True)),
                ('performed_video_call_by', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('status_tasks', models.CharField(blank=True, max_length=50, null=True)),
                ('reviewer_action', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='application', to='julo.Application')),
            ],
            options={
                'db_table': 'idfy_video_call',
            },
        ),
    ]
