# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-09-13 03:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutodebetMandiriAccount',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='autodebet_mandiri_account_id', primary_key=True, serialize=False)),
                ('charge_token', models.TextField(blank=True, null=True)),
                ('bank_card_token', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('autodebet_account', models.ForeignKey(db_column='autodebet_account_id', on_delete=django.db.models.deletion.DO_NOTHING, to='autodebet.AutodebetAccount')),
            ],
            options={
                'db_table': 'autodebet_mandiri_account',
            },
        ),
        migrations.CreateModel(
            name='AutodebetMandiriTransaction',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='autodebet_mandiri_transaction_id', primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('original_reference_no', models.TextField(blank=True, null=True, db_index=True)),
                ('original_partner_reference_no', models.TextField(blank=True, null=True, db_index=True)),
                ('account_payment', models.ForeignKey(blank=True, db_column='account_payment_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account_payment.AccountPayment')),
                ('autodebet_mandiri_account', models.ForeignKey(db_column='autodebet_mandiri_account_id', on_delete=django.db.models.deletion.DO_NOTHING, to='autodebet.AutodebetMandiriAccount')),
            ],
            options={
                'db_table': 'autodebet_mandiri_transaction',
            },
        ),
    ]
