# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-09-25 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='autodebetmandiriaccount',
            name='journey_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
