# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-09-29 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
