# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-10-04 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgatewaycustomerdata',
            name='beneficiary_request_retry_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
