# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-10-05 11:49
from __future__ import unicode_literals

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeletionRequest',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='account_deletion_request_id', primary_key=True, serialize=False)),
                ('request_status', models.CharField(max_length=20)),
                ('reason', models.TextField()),
                ('detail_reason', models.TextField(null=True)),
                ('verdict_reason', models.TextField(null=True)),
                ('verdict_date', models.DateTimeField(null=True)),
                ('agent', models.ForeignKey(db_column='agent_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('customer', juloserver.julocore.customized_psycopg2.models.BigForeignKey(db_column='customer_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Customer')),
            ],
            options={
                'db_table': 'account_deletion_request',
            },
        ),
    ]
