# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-10-11 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DanaCallLogPocAiRudderPds',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='dana_call_log_poc_airudder_pds_id', primary_key=True, serialize=False)),
                ('call_log_type', models.TextField(blank=True, null=True)),
                ('task_id', models.TextField(blank=True, null=True)),
                ('task_name', models.TextField(blank=True, null=True)),
                ('group_name', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('phone_number', models.TextField(blank=True, null=True)),
                ('call_id', models.TextField(blank=True, db_index=True, null=True)),
                ('contact_name', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('info_1', models.TextField(blank=True, null=True)),
                ('info_2', models.TextField(blank=True, null=True)),
                ('info_3', models.TextField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('main_number', models.TextField(blank=True, null=True)),
                ('phone_tag', models.TextField(blank=True, null=True)),
                ('private_data', models.TextField(blank=True, null=True)),
                ('hangup_reason', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('recording_link', models.TextField(blank=True, null=True)),
                ('nth_call', models.IntegerField(blank=True, null=True)),
                ('talk_remarks', models.TextField(blank=True, null=True)),
                ('dana_skiptrace_history', models.ForeignKey(db_column='dana_skiptrace_history_id', on_delete=django.db.models.deletion.DO_NOTHING, to='dana.DanaSkiptraceHistory')),
            ],
            options={
                'db_table': 'dana_call_log_poc_airudder_pds',
            },
        ),
    ]
