# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-10-25 04:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDataChangeRequest',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', juloserver.julocore.customized_psycopg2.models.BigAutoField(db_column='customer_data_change_request_id', primary_key=True, serialize=False)),
                ('source', models.TextField()),
                ('status', models.TextField()),
                ('app_version', models.TextField(blank=True, null=True)),
                ('android_id', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('job_type', models.TextField(blank=True, null=True)),
                ('job_industry', models.TextField(blank=True, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('company_name', models.TextField(blank=True, null=True)),
                ('company_phone_number', models.TextField(blank=True, null=True)),
                ('payday', models.IntegerField(blank=True, null=True)),
                ('monthly_income', models.BigIntegerField(blank=True, null=True)),
                ('monthly_expenses', models.BigIntegerField(blank=True, null=True)),
                ('monthly_housing_cost', models.BigIntegerField(blank=True, null=True)),
                ('total_current_debt', models.BigIntegerField(blank=True, null=True)),
                ('address', models.ForeignKey(blank=True, db_column='address_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_data_change_request_address', to='account.Address')),
                ('address_transfer_certificate_image', models.ForeignKey(blank=True, db_column='address_transfer_certificate_image_id', db_constraint=False, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_transfer_certificate_image_change_request', to='julo.Image')),
                ('application', juloserver.julocore.customized_psycopg2.models.BigForeignKey(db_column='application_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Application')),
                ('company_proof_image', models.ForeignKey(blank=True, db_column='company_proof_image_id', db_constraint=False, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_proof_image_change_request', to='julo.Image')),
                ('customer', juloserver.julocore.customized_psycopg2.models.BigForeignKey(db_column='customer_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Customer')),
                ('paystub_image', models.ForeignKey(blank=True, db_column='paystub_image_id', db_constraint=False, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paystub_image_change_request', to='julo.Image')),
            ],
            options={
                'db_table': 'customer_data_change_request',
            },
        ),
    ]
