# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-10-18 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PdChurnModelResult',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', juloserver.julocore.customized_psycopg2.models.BigAutoField(db_column='pd_churn_model_result_id', primary_key=True, serialize=False)),
                ('predict_date', models.DateField()),
                ('customer_id', models.BigIntegerField()),
                ('model_version', models.CharField(max_length=50)),
                ('pchurn', models.FloatField()),
                ('experiment_group', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"ana"."pd_churn_model_result"',
                'managed': False,
            },
        ),
    ]
