# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-10-24 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgatewaycustomerdata',
            name='phone_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
