# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-10-26 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgatewayapilog',
            name='beneficiary_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentgatewayapilogarchival',
            name='beneficiary_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
