# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-11-09 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='experimentgroup',
            name='source',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
