# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-11-08 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='salesopsbucket',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
