# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-11-03 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrabCallLogPocAiRudderPds',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', juloserver.julocore.customized_psycopg2.models.BigAutoField(
                    db_column='grab_call_log_poc_airudder_pds_id',
                    primary_key=True, serialize=False)),
                ('call_log_type', models.CharField(blank=True, max_length=100, null=True)),
                ('task_id', models.CharField(blank=True, max_length=200, null=True)),
                ('task_name', models.CharField(blank=True, max_length=200, null=True)),
                ('group_name', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('call_id', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('info_1', models.TextField(blank=True, null=True)),
                ('info_2', models.TextField(blank=True, null=True)),
                ('info_3', models.TextField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('main_number', models.CharField(blank=True, max_length=30, null=True)),
                ('phone_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('private_data', models.CharField(blank=True, max_length=200, null=True)),
                ('hangup_reason', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('recording_link', models.TextField(blank=True, null=True)),
                ('nth_call', models.IntegerField(blank=True, null=True)),
                ('talk_remarks', models.TextField(blank=True, null=True)),
                ('grab_skiptrace_history', models.ForeignKey(db_column='grab_skiptrace_history_id', on_delete=django.db.models.deletion.DO_NOTHING, to='grab.GrabSkiptraceHistory')),
            ],
            options={
                'db_table': 'grab_call_log_poc_airudder_pds',
            },
        ),
    ]
