# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-11-21 04:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='inapprating',
            name='csat_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inapprating',
            name='csat_score',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='Rating harus lebih besar atau sama dengan 0'), django.core.validators.MaxValueValidator(5, message='Rating harus lebih kecil atau sama dengan 5')]),
        ),
        migrations.AddField(
            model_name='inapprating',
            name='form_type',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inapprating',
            name='source',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inapprating',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
