# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-11-20 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='fdcoutdatedloan',
            name='application',
            field=models.ForeignKey(blank=True, db_column='application_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Application'),
        ),
        migrations.AlterField(
            model_name='fdcoutdatedloan',
            name='customer',
            field=models.ForeignKey(db_column='customer_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Customer'),
        ),
    ]
