# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-11-15 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='applicationriskycheck',
            name='is_early_warning_leverage_bank',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='applicationriskycheck',
            name='is_window_dressing_leverage_bank',
            field=models.NullBooleanField(default=None),
        ),
    ]
