# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-11-20 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='cfsassignmentverification',
            name='monthly_income',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
