# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-11-17 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOpsGraduation',
            fields=[
                ('account_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('last_graduation_date', models.DateField(blank=True, null=True)),
                ('limit_amount_increased', models.BigIntegerField(default=0)),
                ('ranking', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'sales_ops_graduation',
                'managed': False,
            },
        ),
    ]
