# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-11-20 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanJuloCare',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='loan_julo_care_id', primary_key=True, serialize=False)),
                ('insurance_premium', models.BigIntegerField()),
                ('policy_id', models.CharField(blank=True, max_length=100, null=True)),
                ('policy_number', models.CharField(blank=True, max_length=100, null=True)),
                ('policy_product_code', models.CharField(blank=True, max_length=100, null=True)),
                ('quotation_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(max_length=100)),
                ('document_url', models.TextField(blank=True, null=True)),
                ('document_filename', models.TextField(blank=True, null=True)),
                ('document_type', models.CharField(blank=True, max_length=100, null=True)),
                ('document_alias', models.CharField(blank=True, max_length=100, null=True)),
                ('loan', juloserver.julocore.customized_psycopg2.models.BigOneToOneField(db_column='loan_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Loan')),
            ],
            options={
                'db_table': 'loan_julo_care',
            },
        ),
    ]
