# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-11-27 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='lenderloanledger',
            name='tag_type',
            field=models.CharField(blank=True, choices=[('initial_tag', 'initial_tag'), ('replenishment_tag', 'replenishment_tag'), ('released_by_90dpd', 'released_by_90dpd'), ('released_by_lender', 'released_by_lender'), ('released_by_paid_off', 'released_by_paid_off'), ('released_by_refinancing', 'released_by_refinancing'), ('released_by_repayment', 'released_by_repayment'), ('released_by_cancellation', 'released_by_cancellation'), ('released_by_facility_limit', 'released_by_facility_limit')], max_length=50, null=True),
        ),
    ]
