# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-11-28 11:18
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinscoreApiRawResult',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', juloserver.julocore.customized_psycopg2.models.BigAutoField(db_column='finscore_api_raw_result_id', primary_key=True, serialize=False)),
                ('http_code', models.IntegerField()),
                ('response_json', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
            options={
                'db_table': 'finscore_api_raw_result',
            },
        ),
        migrations.CreateModel(
            name='FinscoreApiRequest',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', juloserver.julocore.customized_psycopg2.models.BigAutoField(db_column='finscore_api_request_id', primary_key=True, serialize=False)),
                ('device_id', models.TextField(null=True)),
                ('application', juloserver.julocore.customized_psycopg2.models.BigForeignKey(db_column='application_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Application')),
            ],
            options={
                'db_table': 'finscore_api_request',
            },
        ),
        migrations.CreateModel(
            name='FinscoreApiResult',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', juloserver.julocore.customized_psycopg2.models.BigAutoField(db_column='finscore_api_result_id', primary_key=True, serialize=False)),
                ('request_duration', models.DurationField(blank=True, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('reason_code', models.IntegerField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('finscore_api_request', juloserver.julocore.customized_psycopg2.models.BigForeignKey(db_column='finscore_api_request_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='fraud_score.FinscoreApiRequest')),
            ],
            options={
                'db_table': 'finscore_api_result',
            },
        ),
        migrations.AddField(
            model_name='finscoreapirawresult',
            name='finscore_api_request',
            field=juloserver.julocore.customized_psycopg2.models.BigForeignKey(db_column='finscore_api_request_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='fraud_score.FinscoreApiRequest'),
        ),
    ]
