# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-12-07 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingeligibilitychecking',
            name='fdc_inquiry',
            field=models.ForeignKey(blank=True, db_column='fdc_inquiry_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.FDCInquiry'),
        ),
    ]
