# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-11-22 19:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='helpcenteritem',
            name='action_button',
            field=models.CharField(blank=True, choices=[('unknown', None), ('reset_phone_number', 'reset_phone_number')], max_length=50, null=True),
        ),
    ]