# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-11-27 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='account_payment_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
