# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-12-05 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaqFeature',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='faq_feature_id', primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order_priority', models.IntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('section_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'faq_feature',
                'ordering': ('section_name', 'order_priority'),
            },
        ),
    ]
