# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-12-12 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='danabillerorder',
            name='order_id',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
