# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-12-15 08:08
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceconsolidationverification',
            name='account_limit_histories',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
