# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-12-15 08:22
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCycleDayHistory',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='account_cycle_day_history_id', primary_key=True, serialize=False)),
                ('latest_flag', models.BooleanField(default=True)),
                ('old_cycle_day', models.IntegerField()),
                ('new_cycle_day', models.IntegerField()),
                ('reason', models.CharField(blank=True, max_length=50, null=True)),
                ('parameters', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.DO_NOTHING, to='account.Account')),
                ('application', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Application')),
            ],
            options={
                'db_table': 'account_cycle_day_history',
            },
        ),
    ]
