# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-12-13 07:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterModelTable(
            name='sbdailyospproductlender',
            table='"ana"."daily_osp_product_lender"',
        ),
    ]
