# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-12-20 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='salesopslineup',
            name='latest_rpc_agent_assignment',
            field=models.OneToOneField(blank=True, db_column='latest_rpc_agent_assignment_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='latest_rpc_agent_assignment', to='sales_ops.SalesOpsAgentAssignment'),
        ),
        migrations.AlterField(
            model_name='salesopslineup',
            name='latest_agent_assignment',
            field=models.OneToOneField(blank=True, db_column='latest_agent_assignment_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='latest_agent_assignment', to='sales_ops.SalesOpsAgentAssignment'),
        ),
    ]
