# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-12-21 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='neobannercard',
            name='button_action_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
