# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-01-15 05:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanAdditionalFee',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='loan_additional_fee_id', primary_key=True, serialize=False)),
                ('fee_amount', models.BigIntegerField()),
            ],
            options={
                'db_table': 'loan_additional_fee',
            },
        ),
        migrations.CreateModel(
            name='LoanAdditionalFeeType',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='fee_type_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'loan_additional_fee_type',
            },
        ),
        migrations.AddField(
            model_name='loanadditionalfee',
            name='fee_type',
            field=models.ForeignKey(db_column='fee_type_id', on_delete=django.db.models.deletion.DO_NOTHING, to='loan.LoanAdditionalFeeType'),
        ),
        migrations.AddField(
            model_name='loanadditionalfee',
            name='loan',
            field=juloserver.julocore.customized_psycopg2.models.BigForeignKey(db_column='loan_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Loan'),
        ),
    ]
