# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-01-17 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='customergraduationfailure',
            name='skipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='downgradecustomerhistory',
            name='customer_graduation_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
