# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-01-23 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoengageOsmSubscriber',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', juloserver.julocore.customized_psycopg2.models.BigAutoField(db_column='moengage_osm_subscriber_id', primary_key=True, serialize=False)),
                ('moengage_user_id', models.TextField(blank=True, null=True)),
                ('first_name', models.TextField()),
                ('email', models.TextField(db_index=True)),
                ('phone_number', models.TextField(db_index=True)),
            ],
            options={
                'db_table': 'moengage_osm_subscriber',
            },
        ),
    ]
