# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-01-18 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    IMPORTANT NOTE:
    The following migration operations should be executed manually by the database team.
    Do not run these automatically. Insert to migration db first before deployment.
    """
    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_kin_approved',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='kin_consent_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='applicationoriginal',
            name='is_kin_approved',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationoriginal',
            name='kin_consent_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
