# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-01-31 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='grabskiptracehistory',
            name='external_task_identifier',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
