# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-01-30 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthcarePlatform',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='healthcare_platform_id', primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('city', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'healthcare_platform',
            },
        ),
        migrations.CreateModel(
            name='HealthcareUser',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='healthcare_user_id', primary_key=True, serialize=False)),
                ('fullname', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.PROTECT, to='account.Account')),
                ('bank_account_destination', models.ForeignKey(db_column='bank_account_destination_id', on_delete=django.db.models.deletion.PROTECT, to='customer_module.BankAccountDestination')),
                ('healthcare_platform', models.ForeignKey(db_column='healthcare_platform_id', on_delete=django.db.models.deletion.PROTECT, to='healthcare.HealthcarePlatform')),
            ],
            options={
                'db_table': 'healthcare_user',
            },
        ),
        migrations.AlterUniqueTogether(
            name='healthcareplatform',
            unique_together=set([('name', 'city')]),
        ),
    ]
