# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-02-02 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='danarepaymentreference',
            name='credit_usage_mutation',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='danarepaymentreference',
            name='lender_product_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='danarepaymentreference',
            name='repayment_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
