# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-01-30 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='loanadjustedrate',
            name='adjusted_first_month_interest_rate',
            field=models.FloatField(blank=True, help_text='available case where simple fee > max fee', null=True),
        ),
    ]
