# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-01-30 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicCheck',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', juloserver.julocore.customized_psycopg2.models.BigAutoField(db_column='dynamic_check_id', primary_key=True, serialize=False)),
                ('application_id', models.BigIntegerField(db_index=True)),
                ('is_okay', models.BooleanField()),
                ('is_holdout', models.BooleanField()),
            ],
            options={
                'db_table': '"ana"."dynamic_check"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DynamicCheckLookup',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', juloserver.julocore.customized_psycopg2.models.BigAutoField(db_column='dynamic_check_lookup_id', primary_key=True, serialize=False)),
                ('check_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'db_table': '"ana"."dynamic_check_lookup"',
                'managed': False,
            },
        ),
    ]
