# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-02-01 10:58
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='entrylevellimitconfiguration',
            name='enabled_trx_method',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14], size=None),
        ),
    ]
