# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-01-28 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSegmentationComms',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', juloserver.julocore.customized_psycopg2.models.BigAutoField(db_column='customer_segmentation_comms_id', primary_key=True, serialize=False)),
                ('customer_id', models.BigIntegerField(db_index=True)),
                ('customer_segment', models.CharField(max_length=200)),
                ('schema_amount', models.CharField(max_length=200)),
                ('default_monthly_installment', models.CharField(max_length=200)),
                ('np_monthly_installment', models.CharField(max_length=200)),
                ('np_provision_amount', models.CharField(max_length=200)),
                ('np_monthly_interest_amount', models.CharField(max_length=200)),
                ('promo_code_churn', models.CharField(max_length=200)),
                ('is_np_lower', models.CharField(max_length=200)),
                ('is_create_loan', models.CharField(max_length=200)),
                ('customer_segment_group', models.CharField(max_length=200)),
                ('churn_group', models.CharField(max_length=200)),
            ],
            options={
                'db_table': '"ana"."customer_segmentation_comms"',
                'managed': False,
            },
        ),
    ]
