# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-02-19 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='danacustomerdata',
            name='dialer_vendor',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
