# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-02-21 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanLenderTaggingDpdTemp',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', juloserver.julocore.customized_psycopg2.models.BigAutoField(db_column='loan_lender_tagging_loan_dpd_id', primary_key=True, serialize=False)),
                ('loan_dpd', models.IntegerField(db_index=True)),
                ('loan', juloserver.julocore.customized_psycopg2.models.BigForeignKey(blank=True, db_column='loan_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Loan')),
            ],
            options={
                'db_table': 'loan_lender_tagging_loan_dpd_temp',
            },
        ),
    ]
