# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-02-22 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentsetting',
            name='action',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]