# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-02-22 07:23
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PiiVaultEvent',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', juloserver.julocore.customized_psycopg2.models.BigAutoField(db_column='pii_vault_event_id', primary_key=True, serialize=False)),
                ('vault_xid', models.TextField(max_length=125)),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField()),
                ('status', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pii_vault_event',
                'managed': False,
            },
        ),
    ]
