# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-02-19 06:26
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='danadialertemporarydata',
            name='is_active',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='danadialertemporarydata',
            name='jumlah_pinjaman',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='danadialertemporarydata',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='danadialertemporarydata',
            name='total_denda',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='danadialertemporarydata',
            name='total_due_amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='danadialertemporarydata',
            name='total_outstanding',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='danadialertemporarydata',
            name='total_angsuran_per_bulan',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
