# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-02-29 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrabPromoCode',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('promo_code', models.CharField(db_index=True, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, null=True, max_length=75)),
                ('description', models.TextField(blank=True, null=True)),
                ('active_date', models.DateField()),
                ('expire_date', models.DateField()),
            ],
            options={
                'db_table': 'grab_promo_code',
            },
        ),
        migrations.CreateModel(
            name='GrabLoanPromoCode',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id',
                 juloserver.julocore.customized_psycopg2.models.BigAutoField(db_column='grab_loan_promo_code_id',
                                                                             primary_key=True, serialize=False)),
                ('loan_id', models.CharField(blank=True, max_length=20, null=True)),
                ('promo_code', models.ForeignKey(db_column='promo_code', on_delete=django.db.models.deletion.DO_NOTHING,
                                                 to='grab.GrabPromoCode')),
                ('grab_loan_data_id', models.CharField(blank=True, max_length=25, null=True)),
                ('status', models.CharField(choices=[('initiated', 'initiated'), ('applied', 'applied')],
                                            default='initiated', max_length=25)),
            ],
            options={
                'db_table': 'grab_loan_promo_code',
            },
        ),
    ]
