# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-02-28 04:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address_detail',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='address_kabupaten',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='address_kecamatan',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='address_kelurahan',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='address_kodepos',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='address_provinsi',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='address_street_num',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='app_version',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='application_company',
            field=models.ForeignKey(blank=True, db_column='company_id', db_constraint=False, db_index=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_financing.Company'),
        ),
        migrations.AddField(
            model_name='customer',
            name='application_is_deleted',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='customer',
            name='application_merchant',
            field=models.ForeignKey(blank=True, db_column='merchant_id', db_constraint=False, db_index=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_customer', to='merchant_financing.Merchant'),
        ),
        migrations.AddField(
            model_name='customer',
            name='application_number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='application_status',
            field=models.ForeignKey(blank=True, db_column='application_status_code', db_constraint=False, db_index=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='julo.StatusLookup'),
        ),
        migrations.AddField(
            model_name='customer',
            name='bank_account_number',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='bank_name',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='birth_place',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='bss_eligible',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='customer',
            name='close_kin_mobile_phone',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='close_kin_name',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='close_kin_relationship',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='company_name',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='company_phone_number',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='current_application_id',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='current_application_xid',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='current_device',
            field=models.ForeignKey(blank=True, db_column='device_id', db_constraint=False, db_index=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_customer', to='julo.Device'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_assisted_selfie',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_courtesy_call',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_document_submitted',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_fdc_risky',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_term_accepted',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_verification_agreed',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='customer',
            name='job_description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='job_industry',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='job_start',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='job_type',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='kin_mobile_phone',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='kin_name',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='kin_relationship',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_education',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='loan_purpose',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='loan_purpose_desc',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='marital_status',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='marketing_source',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='mobile_phone_2',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='monthly_expenses',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='monthly_housing_cost',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='monthly_income',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='name_bank_validation',
            field=models.ForeignKey(blank=True, db_column='name_bank_validation_id', db_constraint=False, db_index=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='disbursement.NameBankValidation'),
        ),
        migrations.AddField(
            model_name='customer',
            name='name_in_bank',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='onboarding',
            field=models.ForeignKey(blank=True, db_column='onboarding_id', db_constraint=False, db_index=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='julo.Onboarding'),
        ),
        migrations.AddField(
            model_name='customer',
            name='partner',
            field=models.ForeignKey(blank=True, db_column='partner_id', db_constraint=False, db_index=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='julo.Partner'),
        ),
        migrations.AddField(
            model_name='customer',
            name='payday',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='product_line',
            field=models.ForeignKey(blank=True, db_column='product_line_code', db_constraint=False, db_index=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='julo.ProductLine'),
        ),
        migrations.AddField(
            model_name='customer',
            name='referral_code',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='spouse_mobile_phone',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='spouse_name',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='teaser_loan_amount',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_current_debt',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='web_version',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='workflow',
            field=models.ForeignKey(blank=True, db_column='workflow_id', db_constraint=False, db_index=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='julo.Workflow'),
        ),
    ]
