# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-03-07 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='limitvaliditytimer',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='limitvaliditytimer',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='limitvaliditytimer',
            name='upload_url',
            field=models.TextField(default=''),
        ),
    ]
