# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-03-01 11:56
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BureauDeviceIntelligence',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', juloserver.julocore.customized_psycopg2.models.BigAutoField(db_column='bureau_device_intelligence_id', primary_key=True, serialize=False)),
                ('raw_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('status', models.TextField(blank=True, null=True)),
                ('errors', models.TextField(blank=True, null=True)),
                ('session_id', models.TextField()),
                ('application', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Application')),
            ],
            options={
                'db_table': 'bureau_device_intelligence',
            },
        ),
        migrations.CreateModel(
            name='BureauEmailAttributes',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', juloserver.julocore.customized_psycopg2.models.BigAutoField(db_column='bureau_email_attributes_id', primary_key=True, serialize=False)),
                ('raw_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('status', models.TextField(blank=True, null=True)),
                ('errors', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Application')),
            ],
            options={
                'db_table': 'bureau_email_attributes',
            },
        ),
        migrations.CreateModel(
            name='BureauEmailSocial',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', juloserver.julocore.customized_psycopg2.models.BigAutoField(db_column='bureau_email_social_id', primary_key=True, serialize=False)),
                ('raw_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('status', models.TextField(blank=True, null=True)),
                ('errors', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Application')),
            ],
            options={
                'db_table': 'bureau_email_social',
            },
        ),
        migrations.CreateModel(
            name='BureauMobileIntelligence',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', juloserver.julocore.customized_psycopg2.models.BigAutoField(db_column='bureau_mobile_intelligence_id', primary_key=True, serialize=False)),
                ('raw_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('status', models.TextField(blank=True, null=True)),
                ('errors', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Application')),
            ],
            options={
                'db_table': 'bureau_mobile_intelligence',
            },
        ),
        migrations.CreateModel(
            name='BureauPhoneSocial',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', juloserver.julocore.customized_psycopg2.models.BigAutoField(db_column='bureau_phone_social_id', primary_key=True, serialize=False)),
                ('raw_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('status', models.TextField(blank=True, null=True)),
                ('errors', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Application')),
            ],
            options={
                'db_table': 'bureau_phone_social',
            },
        ),
    ]
