# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-03-07 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AddField(
            model_name='streamlinedcommunicationsegment',
            name='csv_file_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='streamlinedcommunicationsegment',
            name='segment_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
