# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-03-18 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='pointearning',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pointhistory',
            name='change_reason',
            field=models.CharField(choices=[('daily_checking', 'daily_checking'), ('bonus_checking', 'bonus_checking'), ('expired', 'expired')], max_length=255),
        ),
    ]
