# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-03-18 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='missionconfig',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missionconfig',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='missionconfig',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='missionprogress',
            name='recurring_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='missionprogress',
            name='status',
            field=models.CharField(choices=[('started', 'started'), ('in_progress', 'in_progress'), ('completed', 'completed'), ('claimed', 'claimed'), ('expired', 'expired')], max_length=255),
        ),
    ]
