# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-03-28 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AddField(
            model_name='facematchingcheck',
            name='is_agent_verified',
            field=models.BooleanField(default=False),
        ),
    ]
