# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-04-09 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AddField(
            model_name='accountgtlhistory',
            name='change_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
