# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-04-02 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AddField(
            model_name='otplesshistory',
            name='error_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='otplesshistory',
            name='error_message',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
