# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-04-08 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AddField(
            model_name='loanjulocare',
            name='device_brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanjulocare',
            name='device_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanjulocare',
            name='os_version',
            field=models.IntegerField(null=True),
        ),
    ]
