# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-04-04 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='PerfiosInstitutionLookup',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.AutoField(
                        db_column='perfios_institution_lookup_id', primary_key=True, serialize=False
                    ),
                ),
                ('perfios_institution_id', models.IntegerField()),
                ('perfios_institution_name', models.CharField(max_length=200)),
                ('bank_name', models.CharField(db_index=True, max_length=200)),
            ],
            options={
                'db_table': 'perfios_institution_lookup',
                'managed': False,
            },
        ),
    ]
