# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-04-08 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AddField(
            model_name='danaapplicationreference',
            name='creditor_check_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
