# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-04-04 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AddField(
            model_name='otprequest',
            name='whatsapp_xid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
