# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-04-22 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='missionconfig',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('transaction', 'Transaction'), ('referral', 'Referral')], default='general', max_length=255),
        ),
        migrations.AlterField(
            model_name='missioncriteria',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('transaction', 'Transaction'), ('referral', 'Referral')], default='general', max_length=255),
        ),
        migrations.AlterField(
            model_name='missioncriteria',
            name='type',
            field=models.CharField(choices=[('target_user', 'Target User'), ('utilization_rate', 'Utilization Rate'), ('transaction_method', 'Transaction Method'), ('tenor', 'Tenor'), ('minimum_loan_amount', 'Minimum Loan Amount')], max_length=255),
        ),
        migrations.AlterField(
            model_name='missionreward',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('transaction', 'Transaction'), ('referral', 'Referral')], default='general', max_length=255),
        ),
    ]
