# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-04-15 04:45
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissionConfigCriteria',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='mission_config_criteria_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'mission_config_criteria',
            },
        ),
        migrations.CreateModel(
            name='MissionCriteria',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='mission_criteria_id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(choices=[('general', 'general'), ('transaction', 'transaction'), ('referral', 'referral')], default='general', max_length=255)),
                ('type', models.CharField(choices=[('target_user', 'Target User'), ('utilization_rate', 'Utilization Rate'), ('transaction_method', 'Transaction Method'), ('tenor', 'Tenor'), ('minimum_loan_amount', 'Minimum Loan Amount')], max_length=255)),
                ('value', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'mission_criteria',
            },
        ),
        migrations.CreateModel(
            name='MissionProgressHistory',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='mission_progress_history_id', primary_key=True, serialize=False)),
                ('field', models.CharField(max_length=255)),
                ('old_value', models.CharField(blank=True, max_length=255, null=True)),
                ('new_value', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mission_progress_history',
            },
        ),
        migrations.CreateModel(
            name='MissionReward',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='mission_reward_id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(choices=[('general', 'general'), ('transaction', 'transaction'), ('referral', 'referral')], default='general', max_length=255)),
                ('type', models.CharField(choices=[('fixed', 'Fixed'), ('percentage', 'Percentage')], max_length=255)),
                ('value', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'mission_reward',
            },
        ),
        migrations.RenameField(
            model_name='missionconfig',
            old_name='max_recurring',
            new_name='target_recurring',
        ),
        migrations.RemoveField(
            model_name='missionconfig',
            name='reference_id',
        ),
        migrations.RemoveField(
            model_name='missionconfig',
            name='reference_type',
        ),
        migrations.RemoveField(
            model_name='missionconfig',
            name='reward_points',
        ),
        migrations.RemoveField(
            model_name='missionconfig',
            name='target_user',
        ),
        migrations.AddField(
            model_name='missionconfig',
            name='category',
            field=models.CharField(choices=[('general', 'general'), ('transaction', 'transaction'), ('referral', 'referral')], default='general', max_length=255),
        ),
        migrations.AlterField(
            model_name='loyaltypoint',
            name='customer',
            field=models.OneToOneField(db_column='customer_id', on_delete=django.db.models.deletion.DO_NOTHING, to='julo.Customer'),
        ),
        migrations.AddField(
            model_name='missionconfigcriteria',
            name='config',
            field=models.ForeignKey(db_column='mission_config_id', on_delete=django.db.models.deletion.DO_NOTHING, to='loyalty.MissionConfig'),
        ),
        migrations.AddField(
            model_name='missionconfigcriteria',
            name='criteria',
            field=models.ForeignKey(db_column='mission_criteria_id', on_delete=django.db.models.deletion.DO_NOTHING, to='loyalty.MissionCriteria'),
        ),
        migrations.AddField(
            model_name='missionconfig',
            name='criteria',
            field=models.ManyToManyField(related_name='mission_configs', through='loyalty.MissionConfigCriteria', to='loyalty.MissionCriteria'),
        ),
        migrations.AddField(
            model_name='missionconfig',
            name='reward',
            field=models.ForeignKey(blank=True, db_column='mission_reward_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loyalty.MissionReward'),
        ),
    ]
