# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-04-17 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='autodebetaccount',
            name='is_force_unbind',
            field=models.BooleanField(default=False),
        ),
    ]
