# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-04-23 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AddField(
            model_name='channelingloanstatus',
            name='admin_fee',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
