# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-05-03 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AddField(
            model_name='axiatacustomerdata',
            name='email_tokenized',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='axiatacustomerdata',
            name='fullname_tokenized',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='axiatacustomerdata',
            name='ktp_tokenized',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='axiatacustomerdata',
            name='phone_number_tokenized',
            field=models.TextField(blank=True, null=True),
        ),
    ]
