# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-05-02 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='RiskCallLogPocAiRudderPds',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('call_log_type', models.TextField(blank=True, null=True)),
                ('task_id', models.TextField(blank=True, null=True)),
                ('task_name', models.TextField(blank=True, null=True)),
                ('group_name', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('phone_number', models.TextField(blank=True, null=True)),
                ('call_id', models.TextField(blank=True, db_index=True, null=True)),
                ('contact_name', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('info_1', models.TextField(blank=True, null=True)),
                ('info_2', models.TextField(blank=True, null=True)),
                ('info_3', models.TextField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('main_number', models.TextField(blank=True, null=True)),
                ('phone_tag', models.TextField(blank=True, null=True)),
                ('private_data', models.TextField(blank=True, null=True)),
                ('hangup_reason', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('recording_link', models.TextField(blank=True, null=True)),
                ('nth_call', models.IntegerField(blank=True, null=True)),
                ('talk_remarks', models.TextField(blank=True, null=True)),
                (
                    'skiptrace_history',
                    models.ForeignKey(
                        db_column='skiptrace_history_id',
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='minisquad.CollectionRiskSkiptraceHistory',
                    ),
                ),
            ],
            options={
                'db_table': 'risk_call_log_poc_airudder_pds',
            },
        ),
        migrations.CreateModel(
            name='RiskHangupReasonPDS',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.AutoField(
                        db_column='hangup_reason_pds_id', primary_key=True, serialize=False
                    ),
                ),
                ('hangup_reason', models.IntegerField(db_column='hangup_reason_id')),
                ('reason', models.TextField()),
                (
                    'skiptrace_history',
                    models.ForeignKey(
                        blank=True,
                        db_column='collection_risk_skiptrace_history_id',
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='minisquad.CollectionRiskSkiptraceHistory',
                    ),
                ),
            ],
            options={
                'db_table': 'risk_hangup_reason_pds',
            },
        ),
    ]
