# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-05-05 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RenameField(
            model_name='bankstatementsubmitbalance',
            old_name='average_eom_balance',
            new_name='eom_balance',
        ),
        migrations.RemoveField(
            model_name='bankstatementsubmitbalance',
            name='minimum_eom_balance',
        ),
    ]
