# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-04-25 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='FraudBlacklistedEmergencyContact',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.AutoField(
                        db_column='fraud_blacklisted_emergency_contacts_id',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('reason', models.TextField()),
                ('date_added_ts', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fraud_blacklisted_emergency_contacts',
            },
        ),
    ]
