# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-05-28 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointearning',
            name='point_history',
        ),
        migrations.AddField(
            model_name='pointearning',
            name='point_history_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
