# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-05-21 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AlterModelOptions(
            name='repaymentrecalllog',
            options={'managed': False},
        ),
    ]
