# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-05-21 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='blacklistedfraudster',
            name='customer_id',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='blacklistedfraudster',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blacklistedfraudster',
            name='type',
            field=models.CharField(blank=True, choices=[('Blacklist', 'Blacklist'), ('Whitelist', 'Whitelist')], default='Blacklist', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='blacklistedfraudster',
            name='updated_by_user_id',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
