# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-05-24 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='missionprogress',
            unique_together=set([('customer', 'mission_config', 'repeat_number', 'recurring_number')]),
        ),
    ]
