# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-05-30 10:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AlterModelOptions(
            name='bnivirtualaccountsuffix',
            options={'managed': False},
        ),
    ]
