# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-06-06 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='securitywhitelist',
            name='updated_by_user_id',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
