# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-06-06 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AddField(
            model_name='collectioncalendarsevent',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectioncalendarsevent',
            name='is_ptp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collectioncalendarsevent',
            name='total_participants',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
