# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-06-04 03:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesopsaccountsegmenthistory',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='salesopsautodialeractivity',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='salesopslineuphistory',
            options={'managed': False},
        ),
    ]
