# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-06-06 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RemoveField(
            model_name='grabapilog',
            name='application',
        ),
        migrations.RemoveField(
            model_name='grabapilog',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='grabapilog',
            name='grab_customer_data',
        ),
        migrations.RemoveField(
            model_name='grabapilog',
            name='loan',
        ),
        migrations.RemoveField(
            model_name='grabcalllogpocairudderpds',
            name='grab_skiptrace_history',
        ),
        migrations.RemoveField(
            model_name='grabpaymentdata',
            name='account_payment',
        ),
        migrations.RemoveField(
            model_name='grabpaymentdata',
            name='loan',
        ),
        migrations.RemoveField(
            model_name='grabpaymentdata',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='grabpaymentdata',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='grabpaymentdata',
            name='ptp_robocall_template',
        ),
        migrations.RemoveField(
            model_name='grabtransactions',
            name='grab_api_log',
        ),
        migrations.RemoveField(
            model_name='grabtransactions',
            name='loan',
        ),
        migrations.AddField(
            model_name='grabapilog',
            name='application_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='grabapilog',
            name='customer_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='grabapilog',
            name='grab_customer_data_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='grabapilog',
            name='loan_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='grabcalllogpocairudderpds',
            name='grab_skiptrace_history_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='grabpaymentdata',
            name='account_payment_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='grabpaymentdata',
            name='loan_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='grabpaymentdata',
            name='payment_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='grabpaymentdata',
            name='ptp_robocall_template_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='grabtransactions',
            name='grab_api_log_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='grabtransactions',
            name='loan_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.RemoveField(
            model_name='grabpaybacktransaction',
            name='grab_txn',
        ),
        migrations.AddField(
            model_name='grabpaybacktransaction',
            name='grab_txn_id',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.RemoveField(
            model_name='grabcollectiondialertemporarydata',
            name='account_payment',
        ),
        migrations.RemoveField(
            model_name='grabcollectiondialertemporarydata',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='grabcollectiondialertemporarydata',
            name='loan',
        ),
        migrations.RemoveField(
            model_name='grabcollectiondialertemporarydata',
            name='payment',
        ),
        migrations.AddField(
            model_name='grabcollectiondialertemporarydata',
            name='account_payment_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grabcollectiondialertemporarydata',
            name='customer_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grabcollectiondialertemporarydata',
            name='loan_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grabcollectiondialertemporarydata',
            name='payment_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grabpaymentdata',
            name='payment_status_code',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
