# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-06-05 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='OcrKtpMetaData',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    juloserver.julocore.customized_psycopg2.models.BigAutoField(
                        db_column='ocr_ktp_meta_data_id', primary_key=True, serialize=False
                    ),
                ),
                ('application_id', models.BigIntegerField(db_column='application_id')),
                ('ocr_ktp_result_id', models.BigIntegerField(db_column='ocr_ktp_result_id')),
                (
                    'request_id',
                    models.CharField(blank=True, db_column='request_id', max_length=150, null=True),
                ),
                ('fill_rate', models.FloatField(blank=True, null=True)),
                ('vendor_fill_rate', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ocr_ktp_meta_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OcrKtpMetaDataAttribute',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    juloserver.julocore.customized_psycopg2.models.BigAutoField(
                        db_column='ocr_ktp_meta_data_attribute_id',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'attribute_name',
                    models.CharField(
                        blank=True, db_column='attribute_name', max_length=150, null=True
                    ),
                ),
            ],
            options={
                'db_table': 'ocr_ktp_meta_data_attribute',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OcrKtpMetaDataValue',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    juloserver.julocore.customized_psycopg2.models.BigAutoField(
                        db_column='ocr_ktp_meta_data_value_id', primary_key=True, serialize=False
                    ),
                ),
                (
                    'threshold_value',
                    models.BigIntegerField(blank=True, db_column='threshold_value', null=True),
                ),
                (
                    'confidence_value',
                    models.BigIntegerField(blank=True, db_column='confidence_value', null=True),
                ),
                ('existed_in_raw', models.BooleanField(default=False)),
                ('threshold_passed', models.BooleanField(default=False)),
                (
                    'ocr_ktp_meta_data',
                    juloserver.julocore.customized_psycopg2.models.BigForeignKey(
                        db_column='ocr_ktp_meta_data_id',
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='application_form.OcrKtpMetaData',
                    ),
                ),
                (
                    'ocr_ktp_meta_data_attribute',
                    juloserver.julocore.customized_psycopg2.models.BigForeignKey(
                        db_column='ocr_ktp_meta_data_attribute_id',
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='application_form.OcrKtpMetaDataAttribute',
                    ),
                ),
            ],
            options={
                'db_table': 'ocr_ktp_meta_data_value',
                'managed': False,
            },
        ),
    ]
