# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-06-02 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AddField(
            model_name='partnershipapplicationdata',
            name='close_kin_mobile_phone_tokenized',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnershipapplicationdata',
            name='close_kin_name_tokenized',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnershipapplicationdata',
            name='kin_mobile_phone_tokenized',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnershipapplicationdata',
            name='kin_name_tokenized',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnershipapplicationdata',
            name='spouse_mobile_phone_tokenized',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnershipapplicationdata',
            name='spouse_name_tokenized',
            field=models.TextField(blank=True, null=True),
        ),
    ]
