# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-06-19 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ChannelingLoanSendFileTracking',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.AutoField(
                        db_column='channeling_loan_send_file_tracking_id',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('channeling_type', models.CharField(max_length=10)),
                ('action_type', models.CharField(max_length=20)),
                ('created_by_user_id', models.BigIntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'channeling_loan_send_file_tracking',
            },
        ),
        migrations.AlterIndexTogether(
            name='channelingloansendfiletracking',
            index_together=set([('channeling_type', 'action_type')]),
        ),
    ]
