# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-06-10 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklistedfraudster',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='blacklistedfraudster',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='blacklistedfraudster',
            name='type',
        ),
    ]
