# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-06-10 08:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklistcustomer',
            name='is_active',
        ),
    ]
