# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-06-10 09:46
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AddField(
            model_name='streamlinedcommunication',
            name='slik_notification_properties',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=None, null=True
            ),
        ),
    ]

