# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-06-21 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AddField(
            model_name='partnershipapplicationdata',
            name='business_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
