# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-06-17 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AddField(
            model_name='axiatacustomerdata',
            name='kin_mobile_phone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='axiatacustomerdata',
            name='kin_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
