# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-06-24 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='fraudfacerecommenderresult',
            name='email_tokenized',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fraudfacerecommenderresult',
            name='full_name_tokenized',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fraudfacerecommenderresult',
            name='nik_tokenized',
            field=models.TextField(blank=True, null=True),
        ),
    ]
