# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-06-24 05:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AlterModelOptions(
            name='sentcreditinformation',
            options={'managed': False},
        ),
    ]
