# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-06-28 07:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AddField(
            model_name='customerremoval',
            name='product_line',
            field=models.ForeignKey(
                blank=True,
                db_column='product_line_code',
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='julo.ProductLine',
            ),
        ),
        migrations.AlterField(
            model_name='customerremoval',
            name='user',
            field=juloserver.julocore.customized_psycopg2.models.BigForeignKey(
                db_column='user_id',
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
