# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-07-01 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GAAppActivity',
            fields=[
                ('id', models.AutoField(db_column='ga_app_activity_id', primary_key=True, serialize=False)),
                ('cdate', models.DateTimeField(auto_now=True)),
                ('customer_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('event_name', models.TextField(blank=True, null=True)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('ga_batch_download_task_id', models.IntegerField(blank=True, null=True)),
                ('app_version', models.TextField(blank=True, null=True)),
                ('device_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '"ana"."ga_app_activity"',
                'managed': False,
            },
        ),
    ]
