# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-06-27 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RenameField(
            model_name='facematchingcheck',
            old_name='face_matching_check_id',
            new_name='id',
        ),
    ]
