# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-06-25 03:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fraudblacklistedasn',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='fraudblacklistedcompany',
            options={'managed': False, 'verbose_name_plural': 'Fraud Blacklisted Companies'},
        ),
        migrations.AlterModelOptions(
            name='fraudblacklistedgeohash5',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='fraudblacklistedpostalcode',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='fraudhighriskasn',
            options={'managed': False, 'verbose_name_plural': 'High Risk ASN'},
        ),
    ]
