# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-07-04 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AddField(
            model_name='emfinancingwfaccesstoken',
            name='email_tokenized',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emfinancingwfaccesstoken',
            name='name_tokenized',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emfinancingwfapplication',
            name='couple_name_tokenized',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emfinancingwfapplication',
            name='couple_phone_number_tokenized',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emfinancingwfapplication',
            name='email_tokenized',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emfinancingwfapplication',
            name='mother_name_tokenized',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emfinancingwfapplication',
            name='mother_phone_number_tokenized',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emfinancingwfapplication',
            name='name_tokenized',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emfinancingwfapplication',
            name='nik_tokenized',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emfinancingwfapplication',
            name='phone_number_tokenized',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emfinancingwfdisbursement',
            name='nik_tokenized',
            field=models.TextField(blank=True, null=True),
        ),
    ]
