# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-07-04 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AddField(
            model_name='danadialertemporarydata',
            name='mobile_number_tokenized',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='danadialertemporarydata',
            name='nama_customer_tokenized',
            field=models.TextField(blank=True, null=True),
        ),
    ]
