# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-07-04 06:32
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='JFinancingCategory',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.AutoField(
                        db_column='j_financing_category_id', primary_key=True, serialize=False
                    ),
                ),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'j_financing_category',
            },
        ),
        migrations.CreateModel(
            name='JFinancingCheckout',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.AutoField(
                        db_column='j_financing_checkout_id', primary_key=True, serialize=False
                    ),
                ),
                ('price', models.PositiveIntegerField()),
                ('loan_duration', models.SmallIntegerField()),
                ('additional_info', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                (
                    'customer',
                    juloserver.julocore.customized_psycopg2.models.BigForeignKey(
                        db_column='customer_id',
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='j_financing_checkouts',
                        to='julo.Customer',
                    ),
                ),
            ],
            options={
                'db_table': 'j_financing_checkout',
            },
        ),
        migrations.CreateModel(
            name='JFinancingProduct',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.AutoField(
                        db_column='j_financing_product_id', primary_key=True, serialize=False
                    ),
                ),
                ('price', models.PositiveIntegerField()),
                ('display_installment_price', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('quantity', models.SmallIntegerField(default=0)),
                (
                    'j_financing_category',
                    models.ForeignKey(
                        db_column='j_financing_category_id',
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='financing_products',
                        to='julo_financing.JFinancingCategory',
                    ),
                ),
            ],
            options={
                'db_table': 'j_financing_product',
            },
        ),
        migrations.CreateModel(
            name='JFinancingProductHistory',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.AutoField(
                        db_column='j_financing_product_history_id',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('field_name', models.CharField(max_length=50)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField()),
                (
                    'agent',
                    models.ForeignKey(
                        blank=True,
                        db_column='agent_id',
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='julo.Agent',
                    ),
                ),
                (
                    'j_financing_product',
                    models.ForeignKey(
                        db_column='j_financing_product_id',
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='histories',
                        to='julo_financing.JFinancingProduct',
                    ),
                ),
            ],
            options={
                'db_table': 'j_financing_product_history',
            },
        ),
        migrations.CreateModel(
            name='JFinancingVerification',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.AutoField(
                        db_column='j_financing_verification_id', primary_key=True, serialize=False
                    ),
                ),
                (
                    'validation_status',
                    models.CharField(
                        choices=[
                            ('order_confirmed', 'order_confirmed'),
                            ('in_process', 'in_process'),
                            ('order_on_delivery', 'order_on_delivery'),
                            ('order_completed', 'order_completed'),
                            ('order_cancelled', 'order_cancelled'),
                        ],
                        default='order_confirmed',
                        max_length=50,
                    ),
                ),
                ('note', models.TextField(blank=True, null=True)),
                (
                    'j_financing_checkout',
                    models.OneToOneField(
                        db_column='j_financing_checkout_id',
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='verification',
                        to='julo_financing.JFinancingCheckout',
                    ),
                ),
                (
                    'loan',
                    juloserver.julocore.customized_psycopg2.models.BigOneToOneField(
                        blank=True,
                        db_column='loan_id',
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='j_financing_verification',
                        to='julo.Loan',
                    ),
                ),
                (
                    'locked_by',
                    models.ForeignKey(
                        blank=True,
                        db_column='locked_by_id',
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='j_financing_verifications',
                        to='julo.Agent',
                    ),
                ),
            ],
            options={
                'db_table': 'j_financing_verification',
            },
        ),
        migrations.CreateModel(
            name='JFinancingVerificationHistory',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.AutoField(
                        db_column='verification_history_id', primary_key=True, serialize=False
                    ),
                ),
                ('field_name', models.CharField(max_length=50)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField()),
                ('change_reason', models.CharField(blank=True, max_length=100, null=True)),
                (
                    'agent',
                    models.ForeignKey(
                        blank=True,
                        db_column='agent_id',
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='julo.Agent',
                    ),
                ),
                (
                    'j_financing_verification',
                    models.ForeignKey(
                        db_column='j_financing_verification_id',
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='histories',
                        to='julo_financing.JFinancingVerification',
                    ),
                ),
            ],
            options={
                'db_table': 'j_financing_verification_history',
            },
        ),
        migrations.AddField(
            model_name='jfinancingcheckout',
            name='j_financing_product',
            field=models.ForeignKey(
                db_column='j_financing_product_id',
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='financing_checkouts',
                to='julo_financing.JFinancingProduct',
            ),
        ),
        migrations.AddField(
            model_name='jfinancingcheckout',
            name='signature_image',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='julo.Image',
            ),
        ),
    ]
