# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-07-24 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='grabskiptracehistory',
            name='spoke_with_tokenized',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grabskiptracehistory',
            name='agent_name_tokenized',
            field=models.TextField(blank=True, null=True),
        ),
    ]
