# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-07-15 08:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelingLoanWriteOff',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    juloserver.julocore.customized_psycopg2.models.BigAutoField(
                        db_column='loan_write_off_id', primary_key=True, serialize=False
                    ),
                ),
                ('is_write_off', models.BooleanField(default=True)),
                ('channeling_type', models.CharField(db_index=True, max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                (
                    'document',
                    models.ForeignKey(
                        blank=True,
                        db_column='document_id',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='julo.Document',
                    ),
                ),
                (
                    'loan',
                    juloserver.julocore.customized_psycopg2.models.BigForeignKey(
                        blank=True,
                        db_column='loan_id',
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='julo.Loan',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        db_column='user_id',
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'channeling_loan_write_off',
            },
        ),
    ]
