# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-07-18 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='balanceconsolidation',
            name='email_tokenized',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='balanceconsolidation',
            name='fullname_tokenized',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='balanceconsolidation',
            name='name_in_bank_tokenized',
            field=models.TextField(blank=True, null=True),
        ),
    ]
