# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-07-15 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AddField(
            model_name='fdcdeliverytemp',
            name='pendapatan',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
