# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-07-25 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='studentregister',
            name='student_fullname_tokenized',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
