# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-07-22 08:36
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='grabpromocode',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grabpromocode',
            name='rule',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, 'New User'), (2, 'Existing User With Outstanding'), (3, 'Existing User Without Outstanding')]), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='grabpromocode',
            name='blog_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
