# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-07-15 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='InAppSurveyTriggeredAnswer',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.AutoField(
                        db_column='inapp_survey_triggered_answer_id',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                'db_table': 'inapp_survey_triggered_answer',
                'managed': False,
            },
        ),
    ]
