# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-07-19 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AddField(
            model_name='fdcdeliverytemp',
            name='email_tokenized',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fdcdeliverytemp',
            name='nama_borrower_tokenized',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fdcdeliverytemp',
            name='nama_penjamin_tokenized',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fdcdeliverytemp',
            name='no_hp_tokenized',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fdcdeliverytemp',
            name='no_identitas_tokenized',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fdcdeliverytemp',
            name='no_npwp_tokenized',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fdcinquiry',
            name='email_tokenized',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fdcinquiry',
            name='mobile_phone_tokenized',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fdcinquiry',
            name='nik_tokenized',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fdcinquiryloan',
            name='email_tokenized',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fdcinquiryloan',
            name='nama_borrower_tokenized',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fdcinquiryloan',
            name='nama_penjamin_tokenized',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fdcinquiryloan',
            name='no_hp_tokenized',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fdcinquiryloan',
            name='no_identitas_tokenized',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fdcinquiryloan',
            name='no_npwp_tokenized',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
