# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-07-15 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AddField(
            model_name='partnerorigin',
            name='email_tokenized',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnerorigin',
            name='phone_number_tokenized',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnershipsessioninformation',
            name='phone_number_tokenized',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prelogincheckpaylater',
            name='phone_number_tokenized',
            field=models.TextField(blank=True, null=True),
        ),
    ]
