# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-07-30 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='FraudTelcoMaidTemporaryBlock',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.AutoField(
                        db_column='fraud_telco_maid_temporary_block_id',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'account',
                    models.ForeignKey(
                        blank=True,
                        db_column='account_id',
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='account.Account',
                    ),
                ),
            ],
            options={
                'db_table': 'fraud_telco_maid_temporary_block',
            },
        ),
    ]
