# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-08-01 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AlterField(
            model_name='danaloanreference',
            name='beneficiary_bank_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='danaloanreference',
            name='beneficiary_bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='danaloanreference',
            name='disbursement_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
