# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-07-30 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AddField(
            model_name='blacklistedfraudster',
            name='phone_number_tokenized',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
