# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-07-30 01:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaidResult',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', juloserver.julocore.customized_psycopg2.models.BigAutoField(db_column='maid_result_id', primary_key=True, serialize=False)),
                ('application_id', models.BigIntegerField(db_index=True)),
                ('loan_id', models.BigIntegerField(db_index=True)),
                ('day_lat', models.FloatField(blank=True, null=True)),
                ('day_long', models.FloatField(blank=True, null=True)),
                ('night_lat', models.FloatField(blank=True, null=True)),
                ('night_long', models.FloatField(blank=True, null=True)),
                ('most_seen_lat', models.FloatField(blank=True, null=True)),
                ('most_seen_long', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'maid_result',
            },
        ),
        migrations.CreateModel(
            name='TelcoLocationResult',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', juloserver.julocore.customized_psycopg2.models.BigAutoField(db_column='telco_location_result_id', primary_key=True, serialize=False)),
                ('application_id', models.BigIntegerField(db_index=True)),
                ('loan_id', models.BigIntegerField(db_index=True)),
                ('vendor', models.CharField(max_length=100)),
                ('tsp', models.CharField(max_length=100)),
                ('cell_tower_ranking', models.IntegerField(blank=True, null=True)),
                ('cell_tower_density', models.CharField(blank=True, max_length=100, null=True)),
                ('location_type', models.CharField(blank=True, max_length=100, null=True)),
                ('dist_min', models.FloatField(blank=True, null=True)),
                ('dist_max', models.FloatField(blank=True, null=True)),
                ('input_lat', models.CharField(blank=True, max_length=100, null=True)),
                ('input_long', models.CharField(blank=True, max_length=100, null=True)),
                ('location_confidence', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'telco_location_result',
            },
        ),
    ]
