# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-08-07 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AddField(
            model_name='jfinancingcheckout',
            name='courier_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jfinancingcheckout',
            name='courier_tracking_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
