# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-08-18 04:24
from __future__ import unicode_literals

from django.db import migrations, models
import juloserver.partnership.models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='PartnershipDocument',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.AutoField(
                        db_column='partnership_document_id', primary_key=True, serialize=False
                    ),
                ),
                (
                    'document_source',
                    models.BigIntegerField(db_column='document_source_id', db_index=True),
                ),
                ('url', models.CharField(help_text='url path to the file S3/OSS', max_length=200)),
                (
                    'service',
                    models.CharField(
                        choices=[('s3', 's3'), ('oss', 'oss')], default='oss', max_length=50
                    ),
                ),
                ('document_type', models.CharField(max_length=50)),
                ('filename', models.CharField(blank=True, max_length=200, null=True)),
                (
                    'file',
                    models.FileField(
                        blank=True,
                        db_column='internal_path',
                        help_text='path to the file before uploaded to S3/OSS',
                        null=True,
                        upload_to=juloserver.partnership.models.upload_to,
                    ),
                ),
                (
                    'document_status',
                    models.IntegerField(
                        blank=True,
                        choices=[(-1, 'Deleted'), (0, 'Current'), (1, 'Resubmission Required')],
                        default=0,
                        null=True,
                    ),
                ),
            ],
            options={
                'db_table': 'partnership_document',
                'managed': False,
            },
        ),
    ]
