# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-08-16 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AddField(
            model_name='aaiblacklistlog',
            name='request_string_tokenized',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autodialercallresult',
            name='phone_number_tokenized',
            field=models.TextField(blank=True, null=True),
        ),
    ]
