# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-08-15 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='AutodebetDeactivationSurveyAnswer',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.AutoField(
                        db_column='autodebet_deactivation_survey_answer_id',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('answer', models.TextField(blank=True, null=True)),
                ('order', models.SmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'autodebet_deactivation_survey_answer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AutodebetDeactivationSurveyQuestion',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.AutoField(
                        db_column='autodebet_deactivation_survey_question_id',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('question', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'autodebet_deactivation_survey_question',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AutodebetDeactivationSurveyUserAnswer',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.AutoField(
                        db_column='autodebet_deactivation_survey_user_answer_id',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('account_id', models.BigIntegerField()),
                ('autodebet_account_id', models.BigIntegerField()),
                ('question', models.TextField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'autodebet_deactivation_survey_user_answer',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='autodebetdeactivationsurveyanswer',
            name='question',
            field=models.ForeignKey(
                db_column='autodebet_deactivation_survey_question_id',
                on_delete=models.deletion.DO_NOTHING,
                related_name='answers',
                to='autodebet.AutodebetDeactivationSurveyQuestion',
            ),
        ),
    ]
