# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-08-28 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='AgentAssistedWebToken',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.AutoField(db_column='web_token_id', primary_key=True, serialize=False),
                ),
                (
                    'session_token',
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ('is_active', models.BooleanField(default=False)),
                ('expire_time', models.DateTimeField(blank=True, null=True)),
                ('application_id', models.BigIntegerField(db_column='application_id')),
            ],
            options={
                'db_table': 'agent_assisted_web_token',
                'managed': False,
            },
        ),
    ]
