# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-08-23 08:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AlterModelOptions(
            name='tokoscoreresult',
            options={'managed': False},
        ),
    ]
