# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-08-21 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AlterField(
            model_name='channelingeligibilitystatus',
            name='channeling_type',
            field=models.CharField(
                choices=[
                    ('BSS', 'BSS'),
                    ('BJB', 'BJB'),
                    ('FAMA', 'FAMA'),
                    ('BCAD', 'BCAD'),
                    ('PERMATA', 'PERMATA'),
                    ('DBS', 'DBS'),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name='channelingloanpayment',
            name='channeling_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('BSS', 'BSS'),
                    ('BJB', 'BJB'),
                    ('FAMA', 'FAMA'),
                    ('BCAD', 'BCAD'),
                    ('PERMATA', 'PERMATA'),
                    ('DBS', 'DBS'),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='channelingloanstatus',
            name='channeling_type',
            field=models.CharField(
                choices=[
                    ('BSS', 'BSS'),
                    ('BJB', 'BJB'),
                    ('FAMA', 'FAMA'),
                    ('BCAD', 'BCAD'),
                    ('PERMATA', 'PERMATA'),
                    ('DBS', 'DBS'),
                ],
                max_length=10,
            ),
        ),
    ]
