# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-09-18 05:31
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnderwritingRunner',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='underwriting_runner_id', primary_key=True, serialize=False)),
                ('application_xid', models.IntegerField(db_index=True)),
                ('decision_id', models.CharField(blank=True, max_length=50, null=True)),
                ('http_status_code', models.IntegerField()),
                ('error', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('status_code', models.IntegerField()),
                ('status_code_history', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=50, null=True)),
                ('credit_status', models.CharField(blank=True, max_length=50, null=True)),
                ('credit_score', models.FloatField()),
                ('credit_limit', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'underwriting_runner',
                'managed': False,
            },
        ),
    ]
