# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-09-20 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AddField(
            model_name='qrisuserstate',
            name='master_agreement_id',
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text='id from master agreement processing',
                null=True,
            ),
        ),
    ]
