# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-09-17 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='B2ExcludeFieldCollection',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.AutoField(
                        db_column='b2_exclude_field_collection_id',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('account_payment_id', models.BigIntegerField(blank=True, null=True)),
                ('account_id', models.IntegerField(blank=True, null=True)),
                ('assignment_date', models.DateField(blank=True, null=True)),
                ('dab_dpd', models.TextField(blank=True, null=True)),
                ('dab_bucket', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '"ana"."b2_exclude_field_collection"',
                'managed': False,
            },
        ),
    ]
