# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-09-11 08:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AddField(
            model_name='partnershipdistributor',
            name='created_by_user_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
