# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-09-12 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AddField(
            model_name='omnichannelcustomersync',
            name='is_rollout_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='omnichannelcustomersync',
            name='is_rollout_one_way_robocall',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='omnichannelcustomersync',
            name='is_rollout_pds',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='omnichannelcustomersync',
            name='is_rollout_pn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='omnichannelcustomersync',
            name='is_rollout_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='omnichannelcustomersync',
            name='is_rollout_two_way_robocall',
            field=models.BooleanField(default=False),
        ),
    ]
