# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-09-25 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='FraudBlacklistData',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.AutoField(
                        db_column='fraud_blacklist_data_id', primary_key=True, serialize=False
                    ),
                ),
                ('type', models.IntegerField(choices=[(1, 'bank_account'), (2, 'phone_number')])),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'fraud_blacklist_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FraudBlock',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.AutoField(db_column='fraud_block_id', primary_key=True, serialize=False),
                ),
                ('source', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'fraud_block',
                'managed': False,
            },
        ),
    ]
