# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-10-03 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AlterField(
            model_name='fraudblockaccount',
            name='is_need_action',
            field=models.BooleanField(default=True),
        ),
    ]
