# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-10-08 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criteriacontrollist',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='promocode',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='promocodeagentmapping',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='promocodebenefit',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='promocodecriteria',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='promocodeusage',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='promopage',
            options={'managed': False},
        ),
    ]
