# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-10-21 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AddField(
            model_name='waiverrecommendation',
            name='total_installments',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
