# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-10-22 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='channelingpaymentevent',
            name='adjusted_interest',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='channelingpaymentevent',
            name='adjusted_principal',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
