# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-10-23 07:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AlterModelOptions(
            name='bankstatementsubmitbalance',
            options={'managed': False},
        ),
    ]
