# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-10-29 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AddField(
            model_name='activelivenessdetection',
            name='video_injection',
            field=models.TextField(blank=True, null=True),
        ),
    ]
