# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-11-01 03:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AlterModelOptions(
            name='oneklikbcaaccount',
            options={'managed': False},
        ),
    ]
