# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-10-30 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceconsolidationdelinquentfdcchecking',
            name='invalid_fdc_inquiry_loan_id',
            field=models.BigIntegerField(),
        ),
    ]
