# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-11-14 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOpsLineupAIRudderData',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', juloserver.julocore.customized_psycopg2.models.BigAutoField(db_column='sales_ops_lineup_airudder_data_id', primary_key=True, serialize=False)),
                ('bucket_code', models.TextField()),
                ('mobile_phone_1', models.TextField()),
                ('gender', models.TextField()),
                ('fullname', models.TextField()),
                ('available_limit', models.BigIntegerField()),
                ('set_limit', models.BigIntegerField()),
                ('customer_type', models.TextField()),
                ('application_history_x190_cdate', models.DateTimeField(blank=True, null=True)),
                ('latest_loan_fund_transfer_ts', models.DateTimeField(blank=True, null=True)),
                ('is_12m_user', models.TextField(blank=True, null=True)),
                ('is_high_value_user', models.TextField(blank=True, null=True)),
                ('kode_voucher', models.TextField(blank=True, null=True)),
                ('scheme', models.TextField(blank=True, null=True)),
                ('biaya_admin_sebelumnya', models.FloatField(blank=True, null=True)),
                ('biaya_admin_baru', models.FloatField(blank=True, null=True)),
                ('bunga_cicilan_sebelumnya', models.FloatField(blank=True, null=True)),
                ('bunga_cicilan_baru', models.FloatField(blank=True, null=True)),
                ('r_score', models.IntegerField()),
                ('m_score', models.IntegerField()),
                ('latest_active_dates', models.DateField(blank=True, null=True)),
                ('customer_id', models.BigIntegerField()),
                ('application_id', models.BigIntegerField()),
                ('account_id', models.BigIntegerField()),
                ('data_date', models.DateField(blank=True, null=True)),
                ('partition_date', models.DateField(blank=True, null=True)),
                ('customer_segment', models.TextField(blank=True, null=True)),
                ('schema_amount', models.TextField(blank=True, null=True)),
                ('schema_loan_duration', models.IntegerField(blank=True, null=True)),
                ('cicilan_per_bulan_sebelumnya', models.TextField(blank=True, null=True)),
                ('cicilan_per_bulan_baru', models.TextField(blank=True, null=True)),
                ('saving_overall_after_np', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '"ana"."sales_ops_lineup_airudder_data"',
                'managed': False,
            },
        ),
    ]
