# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-11-21 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AddField(
            model_name='cootekconfiguration',
            name='julo_gold',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
