# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-11-29 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='OvoWalletAccount',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    juloserver.julocore.customized_psycopg2.models.BigAutoField(
                        db_column='ovo_wallet_account_id', primary_key=True, serialize=False
                    ),
                ),
                (
                    'account_id',
                    models.BigIntegerField(blank=True, db_column='account_id', null=True),
                ),
                ('status', models.CharField(max_length=30)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('access_token_expiry_time', models.DateTimeField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('refresh_token_expiry_time', models.DateTimeField(blank=True, null=True)),
                ('balance', models.BigIntegerField(blank=True, null=True)),
                ('auth_code', models.TextField(blank=True, null=True)),
                ('phone_number', models.TextField(blank=True, null=True)),
                ('phone_number_tokenized', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ovo_wallet_account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OvoWalletBalanceHistory',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    juloserver.julocore.customized_psycopg2.models.BigAutoField(
                        db_column='ovo_wallet_balance_history_id', primary_key=True, serialize=False
                    ),
                ),
                ('balance', models.BigIntegerField(blank=True, null=True)),
                (
                    'ovo_wallet_account',
                    models.ForeignKey(
                        db_column='ovo_wallet_account_id',
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='ovo.OvoWalletAccount',
                    ),
                ),
            ],
            options={
                'db_table': 'ovo_wallet_balance_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OvoWalletTransaction',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    juloserver.julocore.customized_psycopg2.models.BigAutoField(
                        db_column='ovo_wallet_transaction_id', primary_key=True, serialize=False
                    ),
                ),
                ('account_payment_id', models.BigIntegerField(blank=True, null=True)),
                ('partner_reference_no', models.TextField(db_index=True, unique=True)),
                ('reference_no', models.TextField(blank=True, null=True)),
                ('amount', models.BigIntegerField()),
                ('status', models.CharField(max_length=30)),
                ('status_code', models.CharField(max_length=10)),
                ('status_description', models.TextField(blank=True, null=True)),
                ('vendor', models.TextField(blank=True, null=True)),
                (
                    'ovo_wallet_account',
                    models.ForeignKey(
                        db_column='ovo_wallet_account_id',
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='ovo.OvoWalletAccount',
                    ),
                ),
            ],
            options={
                'db_table': 'ovo_wallet_transaction',
                'managed': False,
            },
        ),
    ]
