# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-12-02 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AddField(
            model_name='streamlinedcommunication',
            name='julo_gold_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
