# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2024-12-15 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AddField(
            model_name='pushnotificationpermission',
            name='feature_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
