# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-01-07 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='AnaPartnershipNullPartner',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.AutoField(
                        db_column='partnership_null_partner_id', primary_key=True, serialize=False
                    ),
                ),
                ('application_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('supposed_partner_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '"ana"."partnership_null_partner"',
                'managed': False,
            },
        ),
    ]
