# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-01-16 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='SkiptraceStats',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    juloserver.julocore.customized_psycopg2.models.BigAutoField(
                        db_column='skiptrace_stats_id', primary_key=True, serialize=False
                    ),
                ),
                (
                    'skiptrace',
                    juloserver.julocore.customized_psycopg2.models.BigOneToOneField(
                        db_column='skiptrace_id',
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='skiptracestats',
                        to='julo.Skiptrace',
                    ),
                ),
                (
                    'skiptrace_history',
                    juloserver.julocore.customized_psycopg2.models.BigForeignKey(
                        blank=True,
                        db_column='skiptrace_history_id',
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='julo.SkiptraceHistory',
                    ),
                ),
                ('last_rpc_ts', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.IntegerField(default=0)),
                ('rpc_count', models.IntegerField(default=0)),
                ('rpc_rate', models.FloatField(blank=True, default=0, null=True)),
                ('calculation_start_date', models.DateField(blank=True, null=True)),
                ('calculation_end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'skiptrace_stats',
            },
        ),
    ]
