# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-02-03 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AddField(
            model_name='addressgeolocation',
            name='address_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addressgeolocation',
            name='address_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
