# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-02-06 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AddField(
            model_name='namebankvalidation',
            name='bank',
            field=models.ForeignKey(
                db_column='bank_id',
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='julo.Bank',
            ),
        ),
    ]
