# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-01-31 06:24
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AddField(
            model_name='collectioncohortcampaignemailtemplate',
            name='additional_email_blast_dates',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.DateTimeField(), blank=True, default=list, size=None
            ),
        ),
    ]
