# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-02-05 01:54
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AddField(
            model_name='creditmatrixrepeat',
            name='show_tenure',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), default=list, size=None
            ),
        ),
    ]
