# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-02-14 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='airudderpayloadtemp',
            name='fdc_details',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
