# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-02-18 03:32
from __future__ import unicode_literals

from django.db import migrations, models
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='CollectionIneffectivePhoneNumber',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                (
                    'collection_ineffective_phone_number_id',
                    juloserver.julocore.customized_psycopg2.models.BigAutoField(
                        db_column='collection_ineffective_phone_number_id',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('last_unreachable_date', models.DateField(blank=True, null=True)),
                ('skiptrace_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('ineffective_days', models.IntegerField(default=0)),
                ('flag_as_unreachable_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'collection_ineffective_phone_number',
                'managed': False,
            },
        ),
    ]
