# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-02-19 06:25
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AddField(
            model_name='danaloanreference',
            name='installment_config',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
