# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-02-18 04:42
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EarlyReleaseCheckingHistoryV2',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', juloserver.julocore.customized_psycopg2.models.BigAutoField(db_column='checking_history_id', primary_key=True, serialize=False)),
                ('value_old', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('value_new', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
            options={
                'db_table': 'early_release_checking_history_v2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EarlyReleaseCheckingV2',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', juloserver.julocore.customized_psycopg2.models.BigAutoField(db_column='checking_id', primary_key=True, serialize=False)),
                ('checking_result', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('payment_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'early_release_checking_v2',
                'managed': False,
            },
        ),
    ]
