# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-03-10 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='is_religious_holiday',
            field=models.NullBooleanField(default=False),
        ),
    ]
