# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-03-04 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QrisFunnelLastLog',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='qris_funnel_last_log_id', primary_key=True, serialize=False)),
                ('customer_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('visit_lending_page_date', models.DateField(blank=True, null=True)),
                ('open_master_agreement_date', models.DateField(blank=True, null=True)),
                ('read_master_agreement_date', models.DateField(blank=True, null=True)),
                ('sign_master_agreement_date', models.DateField(blank=True, null=True)),
                ('input_pin_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': '"ana"."qris_funnel_last_log"',
                'managed': False,
            },
        ),
    ]
