# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-03-13 03:41
from __future__ import unicode_literals

from django.db import migrations

from juloserver.julo.models import FeatureSetting
from juloserver.minisquad.constants import FeatureNameConst, DialerSystemConst


def insert_data(apps, schema_editor):
    FeatureSetting.objects.create(
        feature_name=FeatureNameConst.MANUAL_DC_AGENT_ASSIGNMENT,
        category='collection',
        description='Manual desk coll agent assignment feature setting',
        parameters={
            DialerSystemConst.DIALER_BUCKET_2: {'bucket_number': 2, 'agent_list': []},
        },
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [migrations.RunPython(insert_data)]
