# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-03-20 08:40
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='TransactionModelCustomer',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    juloserver.julocore.customized_psycopg2.models.BigAutoField(
                        db_column='transaction_model_customer_id', primary_key=True, serialize=False
                    ),
                ),
                ('customer_id', models.BigIntegerField(db_index=True, unique=True)),
                ('is_mercury', models.BooleanField(default=False)),
                (
                    'allowed_loan_duration',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(
                            validators=[django.core.validators.MinValueValidator(1)]
                        ),
                        size=None,
                    ),
                ),
                (
                    'max_cashloan_amount',
                    models.IntegerField(help_text='max cashloan limit received from ana'),
                ),
            ],
            options={
                'db_table': 'transaction_model_customer',
            },
        ),
        migrations.CreateModel(
            name='TransactionModelCustomerAnaHistory',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    juloserver.julocore.customized_psycopg2.models.BigAutoField(
                        db_column='transaction_model_customer_ana_history_id',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('customer_id', models.BigIntegerField(db_index=True)),
                ('ana_response', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'transaction_model_customer_ana_history',
            },
        ),
        migrations.CreateModel(
            name='TransactionModelCustomerHistory',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    juloserver.julocore.customized_psycopg2.models.BigAutoField(
                        db_column='transaction_model_customer_history_id',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('field_name', models.TextField()),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField()),
                (
                    'transaction_model_customer',
                    juloserver.julocore.customized_psycopg2.models.BigForeignKey(
                        db_column='transaction_model_customer_id',
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='histories',
                        to='loan.TransactionModelCustomer',
                    ),
                ),
            ],
            options={
                'db_table': 'transaction_model_customer_history',
            },
        ),
        migrations.CreateModel(
            name='TransactionModelCustomerLoan',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    juloserver.julocore.customized_psycopg2.models.BigAutoField(
                        db_column='transaction_model_customer_loan_id',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('loan_id', models.BigIntegerField(db_index=True)),
                ('transaction_model_data', django.contrib.postgres.fields.jsonb.JSONField()),
                (
                    'transaction_model_customer',
                    juloserver.julocore.customized_psycopg2.models.BigForeignKey(
                        db_column='transaction_model_customer_id',
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='loans',
                        to='loan.TransactionModelCustomer',
                    ),
                ),
            ],
            options={
                'db_table': 'transaction_model_customer_loan',
            },
        ),
        migrations.AlterIndexTogether(
            name='transactionmodelcustomerloan',
            index_together=set([('loan_id', 'transaction_model_customer')]),
        ),
    ]
