# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-03-25 10:52
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='SuggestedAnswer',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.AutoField(
                        db_column='suggested_answer_id', primary_key=True, serialize=False
                    ),
                ),
                ('survey_answer_ids', models.CharField(max_length=100)),
                ('suggested_answer', ckeditor.fields.RichTextField()),
            ],
            options={
                'db_table': 'suggested_answers',
                'managed': False,
            },
        ),
    ]
