# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-03-27 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='SuggestedAnswerFeedback',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.AutoField(db_column='feedback_id', primary_key=True, serialize=False),
                ),
                ('survey_answer_ids', models.CharField(max_length=100)),
                ('customer_id', models.BigIntegerField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True)),
                ('is_helpful', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'suggested_answer_feedback',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SuggestedAnswerUserLog',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='log_id', primary_key=True, serialize=False)),
                ('survey_answer_ids', models.CharField(max_length=100)),
                ('customer_id', models.BigIntegerField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'suggested_answers_user_log',
                'managed': False,
            },
        ),
    ]
