# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-04-16 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='CollectionSkiptraceEventHistory',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    juloserver.julocore.customized_psycopg2.models.BigAutoField(
                        db_column='collection_skiptrace_event_history_id',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('event_date', models.DateField(blank=True, null=True)),
                ('skiptrace_id', models.BigIntegerField(blank=True, null=True)),
                ('customer_id', models.BigIntegerField(blank=True, null=True)),
                ('unreachable_days', models.IntegerField(blank=True, null=True)),
                ('event_name', models.TextField(blank=True, null=True)),
                ('bucket_number', models.IntegerField(blank=True, null=True)),
                ('consecutive_config_days', models.IntegerField(blank=True, null=True)),
                ('refresh_config_days', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'collection_skiptrace_event_history',
                'managed': False,
            },
        ),
    ]
