# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-04-21 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='FAMAChannelingRepaymentApproval',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.AutoField(
                        db_column='fama_channeling_repayment_approval_id',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('loan_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('account_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('interest_amount', models.BigIntegerField(blank=True, null=True)),
                ('principal_amount', models.BigIntegerField(blank=True, null=True)),
                ('installment_amount', models.BigIntegerField(blank=True, null=True)),
                ('payment_amount', models.BigIntegerField(blank=True, null=True)),
                ('term_payment', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fama_channeling_repayment_approval',
            },
        ),
        migrations.AddField(
            model_name='famachannelingrepaymentapproval',
            name='channeling_loan_approval_file',
            field=models.ForeignKey(
                blank=True,
                db_column='channeling_loan_approval_file_id',
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='channeling_loan.ChannelingLoanApprovalFile',
            ),
        ),
        migrations.AddField(
            model_name='channelingloanapprovalfile',
            name='is_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
