# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-04-22 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmulatorCheckIOS',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', juloserver.julocore.customized_psycopg2.models.BigAutoField(db_column='emulator_check_ios_id', primary_key=True, serialize=False)),
                ('application_id', models.BigIntegerField()),
                ('is_emulator', models.BooleanField()),
            ],
            options={
                'db_table': 'emulator_check_ios',
            },
        ),
    ]
