# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-04-21 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ConsentWithdrawalRequest',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='request_id', primary_key=True, serialize=False)),
                ('customer_id', models.BigIntegerField(blank=True, null=True)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('requested', 'Requested'),
                            ('approved', 'Approved'),
                            ('cancelled', 'Cancelled'),
                            ('rejected', 'Rejected'),
                            ('regranted', 'Regranted'),
                        ],
                        default='requested',
                        max_length=20,
                    ),
                ),
                ('reason', models.TextField(blank=True, null=True)),
                ('detail_reason', models.TextField(blank=True, null=True)),
                ('action_date', models.DateTimeField(null=True)),
                ('action_by', models.BigIntegerField(blank=True, null=True)),
                ('admin_reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'consent_withdrawal_request',
                'managed': False,
            },
        ),
    ]
