# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-04-30 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='famachannelingrepaymentapproval',
            name='account_id',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='famachannelingrepaymentapproval',
            name='account_no',
            field=models.TextField(blank=True, null=True),
        ),
    ]
