# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-05-07 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AddField(
            model_name='trustguardapirequest',
            name='device_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
