# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-05-05 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AddField(
            model_name='partnershipcustomerdata',
            name='customer_id_old',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
