# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-05-12 04:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanTransactionDetail',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', juloserver.julocore.customized_psycopg2.models.BigAutoField(db_column='loan_transaction_detail_id', primary_key=True, serialize=False)),
                ('loan_id', models.BigIntegerField(db_index=True)),
                ('detail', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'loan_transaction_detail',
                'managed': False,
            },
        ),
    ]
