# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-05-15 02:33
from __future__ import unicode_literals

from django.db import migrations, models
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='KangtauUploadedCustomerList',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    juloserver.julocore.customized_psycopg2.models.BigAutoField(
                        db_column='kangtau_customer_list_id', primary_key=True, serialize=False
                    ),
                ),
                ('loan_id', models.BigIntegerField()),
                ('agent_unique_id', models.TextField(blank=True, null=True)),
                ('name', models.TextField()),
                ('phone_number', models.TextField()),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('due_date', models.DateField()),
                ('bucket', models.TextField(db_index=True)),
                ('dpd', models.IntegerField(db_index=True)),
                ('customer_form_id', models.TextField(db_index=True)),
                ('customer_form_name', models.TextField(db_index=True)),
            ],
            options={
                'verbose_name': 'Kangtau Uploaded Customer List',
                'verbose_name_plural': 'Kangtau Uploaded Customer Lists',
                'db_table': 'kangtau_uploaded_customer_list',
                'managed': False,
            },
        ),
    ]
