# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-05-19 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AlterIndexTogether(
            name='smshistory',
            index_together=set([('to_mobile_phone', 'cdate', 'status')]),
        ),
    ]
