# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-06-03 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import juloserver.customer_module.models
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='WebConsentWithdrawalRequest',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    juloserver.julocore.customized_psycopg2.models.BigAutoField(
                        db_column='consent_withdrawal_request_web_id',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('full_name', models.TextField(blank=True, max_length=100, null=True)),
                ('nik', models.TextField(blank=True, max_length=16, null=True)),
                ('email', models.TextField(blank=True, max_length=254, null=True)),
                ('phone', models.TextField(blank=True, max_length=50, null=True)),
                (
                    'reason',
                    models.TextField(
                        blank=True,
                        choices=[
                            ('pengajuan_ditolak', 'Pengajuan Ditolak'),
                            ('keamanan_data', 'Keamanan Data'),
                            ('limit_rendah', 'Limit Rendah'),
                            ('lainnya', 'Lainnya'),
                        ],
                        null=True,
                    ),
                ),
                ('reason_detail', models.TextField(blank=True, null=True)),
                ('customer_id', models.BigIntegerField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True)),
                ('full_name_tokenized', models.TextField(blank=True, null=True)),
                ('nik_tokenized', models.TextField(blank=True, null=True)),
                ('email_tokenized', models.TextField(blank=True, null=True)),
                ('phone_tokenized', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'consent_withdrawal_request_web',
                'managed': False,
            },
        ),
    ]
