# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-06-02 06:44
from __future__ import unicode_literals

from django.db import migrations, models
import juloserver.julocore.customized_psycopg2.models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='DanaLenderSettlementFile',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    juloserver.julocore.customized_psycopg2.models.BigAutoField(
                        db_column='dana_lender_settlement_file_id',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('partner_id', models.CharField(blank=True, max_length=255, null=True)),
                ('lender_product_id', models.CharField(blank=True, max_length=255, null=True)),
                (
                    'partner_reference_no',
                    models.TextField(
                        blank=True,
                        db_index=True,
                        help_text='This partnerReferenceNo from Dana',
                        null=True,
                    ),
                ),
                ('txn_type', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('bill_id', models.CharField(blank=True, max_length=64, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('period_no', models.CharField(blank=True, max_length=64, null=True)),
                ('credit_usage_mutation', models.BigIntegerField(blank=True, null=True)),
                ('principal_amount', models.BigIntegerField(blank=True, null=True)),
                ('interest_fee_amount', models.BigIntegerField(blank=True, null=True)),
                ('late_fee_amount', models.BigIntegerField(blank=True, null=True)),
                ('total_amount', models.BigIntegerField(blank=True, null=True)),
                ('paid_principal_amount', models.BigIntegerField(blank=True, null=True)),
                ('paid_interest_fee_amount', models.BigIntegerField(blank=True, null=True)),
                ('paid_late_fee_amount', models.BigIntegerField(blank=True, null=True)),
                ('total_paid_amount', models.BigIntegerField(blank=True, null=True)),
                ('trans_time', models.DateTimeField(blank=True, null=True)),
                ('is_partial_refund', models.BooleanField()),
                ('fail_code', models.CharField(blank=True, max_length=255, null=True)),
                ('original_order_amount', models.BigIntegerField(blank=True, null=True)),
                (
                    'original_partner_reference_no',
                    models.TextField(
                        blank=True, help_text='This originalPartnerReferenceNo from Dana', null=True
                    ),
                ),
                ('txn_id', models.TextField(blank=True, null=True)),
                ('waived_principal_amount', models.BigIntegerField(blank=True, null=True)),
                ('waived_interest_fee_amount', models.BigIntegerField(blank=True, null=True)),
                ('waived_late_fee_amount', models.BigIntegerField(blank=True, null=True)),
                ('total_waived_amount', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dana_lender_settlement_file',
                'managed': False,
            },
        ),
    ]
