# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-05-30 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AlterField(
            model_name='qrispartnerlinkage',
            name='status',
            field=models.CharField(
                choices=[
                    ('requested', 'requested'),
                    ('success', 'success'),
                    ('failed', 'failed'),
                    ('ignored', 'ignored'),
                    ('inactive', 'inactive'),
                    ('register_form', 'register_form'),
                ],
                default='requested',
                max_length=50,
            ),
        ),
    ]
