# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-05-25 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ChannelingLoanThresholdBypassCheckHistory',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.AutoField(
                        db_column='channeling_loan_threshold_bypass_check_history_id',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('loan_id', models.BigIntegerField()),
                ('lender_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'channeling_loan_threshold_bypass_check_history',
            },
        ),
    ]
