# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2025-06-05 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelingBScore',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='channeling_bscore_id', primary_key=True, serialize=False)),
                ('predict_date', models.DateField(blank=True, null=True)),
                ('customer_id', models.BigIntegerField(blank=True, null=True)),
                ('channeling_type', models.CharField(blank=True, max_length=50, null=True)),
                ('model_version', models.CharField(blank=True, max_length=100, null=True)),
                ('pgood', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': '"ana"."channeling_bscore"',
                'managed': False,
            },
        ),
    ]
