# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-09-05 10:42
from __future__ import unicode_literals

from django.db import migrations


def add_payments_method_lookup_gopay(apps, schema_editor):
    PaymentMethodLookup = apps.get_model("julo", "PaymentMethodLookup")
    method_lookup = PaymentMethodLookup.objects.filter(name='GoPay').first()
    base_url = 'https://www.julo.co.id/images/payment_methods/'

    if method_lookup:
        method_lookup.name = 'Gopay'
        method_lookup.save()
    else:
        PaymentMethodLookup.objects.create(
            code='1002',
            name='Gopay',
            bank_virtual_name='',
            image_logo_url=base_url+'gopay/gopay.png',
            image_background_url=base_url+'gopay/background_gopay.png')


class Migration(migrations.Migration):

    dependencies = [
        ('payback', '0004_add_waive_principal'),
    ]

    operations = [
        migrations.RunPython(add_payments_method_lookup_gopay, migrations.RunPython.noop),
    ]
