# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-23 07:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRoleDefult',
            new_name='UserRoleDefault',
        ),
    ]
