JOB_INDUSTRY_LIST = [
    ('Admin / Finance / HR', 'Admin / Finance / HR'),
    ('Design / Seni', 'Design / Seni'),
    ('Entertainment / Event', 'Entertainment / Event'),
    ('Hukum / Security / Politik', 'Hukum / Security / Politik'),
    ('Kesehatan', 'Kesehatan'),
    ('Konstruksi / Real Estate', 'Konstruksi / Real Estate'),
    ('Media', 'Media'),
    ('Pabrik / Gudang', 'Pabrik / Gudang'),
    ('Pendidikan', 'Pendidikan'),
    ('Perawatan Tubuh', 'Perawatan Tubuh'),
    ('Perbankan', 'Perbankan'),
    ('Sales / Marketing', 'Sales / Marketing'),
    ('Service', 'Service'),
    ('Tehnik / Computer', 'Tehnik / Computer'),
    ('Transportasi', 'Transportasi'),
    ('Staf Rumah Tangga', 'Staf Rumah Tangga'),
    ('Perhotelan', 'Perhotelan')
]

JOB_DESC_LIST = [
    ('Admin', 'Admin'),
    ('Akuntan / Finance', 'Akuntan / Finance'),
    ('HR', 'HR'),
    ('Office Boy', 'Office Boy'),
    ('Sekretaris', 'Sekretaris'),
    ('Lainnya', 'Lainnya'),
    ('Design Grafis', 'Design Grafis'),
    ('Pelukis', 'Pelukis'),
    ('Photographer', 'Photographer'),
    ('DJ / Musisi', 'DJ / Musisi'),
    ('Event Organizer', 'Event Organizer'),
    ('Kameraman', 'Kameraman'),
    ('Penyanyi / Penari / Model', 'Penyanyi / Penari / Model'),
    ('Produser / Sutradara', 'Produser / Sutradara'),
    ('Anggota Pemerintahan', 'Anggota Pemerintahan'),
    ('Hakim / Jaksa / Pengacara', 'Hakim / Jaksa / Pengacara'),
    ('Notaris', 'Notaris'),
    ('Ormas', 'Ormas'),
    ('Pemuka Agama', 'Pemuka Agama'),
    ('Satpam', 'Satpam'),
    ('TNI / Polisi', 'TNI / Polisi'),
    ('Apoteker', 'Apoteker'),
    ('Dokter', 'Dokter'),
    ('Perawat', 'Perawat'),
    ('Teknisi Laboratorium', 'Teknisi Laboratorium'),
    ('Arsitek / Tehnik Sipil', 'Arsitek / Tehnik Sipil'),
    ('Interior Designer', 'Interior Designer'),
    ('Mandor', 'Mandor'),
    ('Pemborong', 'Pemborong'),
    ('Proyek Manager / Surveyor', 'Proyek Manager / Surveyor'),
    ('Real Estate Broker', 'Real Estate Broker'),
    ('Tukang Bangunan', 'Tukang Bangunan'),
    ('Penulis / Editor', 'Penulis / Editor'),
    ('Wartawan', 'Wartawan'),
    ('Buruh Pabrik / Gudang', 'Buruh Pabrik / Gudang'),
    ('Kepala Pabrik / Gudang', 'Kepala Pabrik / Gudang'),
    ('Teknisi Mesin', 'Teknisi Mesin'),
    ('Dosen', 'Dosen'),
    ('Guru', 'Guru'),
    ('Instruktur / Pembimbing Kursus', 'Instruktur / Pembimbing Kursus'),
    ('Kepala Sekolah', 'Kepala Sekolah'),
    ('Tata Usaha', 'Tata Usaha'),
    ('Fashion Designer', 'Fashion Designer'),
    ('Gym / Fitness', 'Gym / Fitness'),
    ('Pelatih / Trainer', 'Pelatih / Trainer'),
    ('Salon / Spa / Panti Pijat', 'Salon / Spa / Panti Pijat'),
    ('Back-office', 'Back-office'),
    ('Bank Teller', 'Bank Teller'),
    ('CS Bank', 'CS Bank'),
    ('Credit Analyst', 'Credit Analyst'),
    ('Kolektor', 'Kolektor'),
    ('Resepsionis', 'Resepsionis'),
    ('Account Executive / Manager', 'Account Executive / Manager'),
    ('Salesman', 'Salesman'),
    ('SPG', 'SPG'),
    ('Telemarketing', 'Telemarketing'),
    ('Customer Service', 'Customer Service'),
    ('Kasir', 'Kasir'),
    ('Kebersihan', 'Kebersihan'),
    ('Koki', 'Koki'),
    ('Pelayan / Pramuniaga', 'Pelayan / Pramuniaga'),
    ('Engineer / Ahli Tehnik', 'Engineer / Ahli Tehnik'),
    ('Penulis Teknikal', 'Penulis Teknikal'),
    ('Programmer / Developer', 'Programmer / Developer'),
    ('R&D / Ilmuwan / Peneliti', 'R&D / Ilmuwan / Peneliti'),
    ('Warnet', 'Warnet'),
    ('Otomotif', 'Otomotif'),
    ('Supir / Ojek', 'Supir / Ojek'),
    ('Agen Perjalanan', 'Agen Perjalanan'),
    ('Kurir / Ekspedisi', 'Kurir / Ekspedisi'),
    ('Pelaut / Staff Kapal / Nahkoda Kapal', 'Pelaut / Staff Kapal / Nahkoda Kapal'),
    ('Pilot / Staff Penerbangan', 'Pilot / Staff Penerbangan'),
    ('Sewa Kendaraan', 'Sewa Kendaraan'),
    ('Masinis / Kereta Api', 'Masinis / Kereta Api'),
    ('Babysitter / Perawat', 'Babysitter / Perawat'),
    ('Pembantu Rumah Tangga', 'Pembantu Rumah Tangga'),
    ('Supir', 'Supir'),
    ('Tukang Kebun', 'Tukang Kebun'),
    ('Room Service / Pelayan', 'Room Service / Pelayan')
]


JOB_MAPPING = {
    'Hukum / Security / Politik': [
        'Anggota Pemerintahan',
        'Hakim / Jaksa / Pengacara',
        'Notaris',
        'Ormas',
        'Pemuka Agama',
        'Satpam',
        'TNI / Polisi',
        'Lainnya',
        'All'
    ],
    'Staf Rumah Tangga': [
        'Babysitter / Perawat',
        'Pembantu Rumah Tangga',
        'Supir',
        'Tukang Kebun',
        'Lainnya',
        'All'
    ],
    'Design / Seni': [
        'Design Grafis',
        'Pelukis',
        'Photographer',
        'Lainnya',
        'All'
    ],
    'Service': [
        'Customer Service',
        'Kasir',
        'Kebersihan',
        'Koki',
        'Pelayan / Pramuniaga',
        'Lainnya',
        'All'
    ],
    'Media': [
        'Kameraman',
        'Penulis / Editor',
        'Wartawan',
        'Lainnya',
        'All'
    ],
    'Tehnik / Computer': [
        'Engineer / Ahli Tehnik',
        'Penulis Teknikal',
        'Programmer / Developer',
        'R&D / Ilmuwan / Peneliti',
        'Warnet',
        'Otomotif',
        'Lainnya',
        'All'
    ],
    'Kesehatan': [
        'Apoteker',
        'Dokter',
        'Perawat',
        'Teknisi Laboratorium',
        'Lainnya',
        'All'
    ],
    'Transportasi': [
        'Supir / Ojek',
        'Agen Perjalanan',
        'Kurir / Ekspedisi',
        'Pelaut / Staff Kapal / Nahkoda Kapal',
        'Pilot / Staff Penerbangan',
        'Sewa Kendaraan',
        'Masinis / Kereta Api',
        'Lainnya',
        'All'
    ],
    'Perawatan Tubuh': [
        'Fashion Designer',
        'Gym / Fitness',
        'Pelatih / Trainer',
        'Salon / Spa / Panti Pijat',
        'Lainnya',
        'All'
    ],
    'Sales / Marketing': [
        'Account Executive / Manager',
        'Salesman',
        'SPG',
        'Telemarketing',
        'Lainnya',
        'All'
    ],
    'Pabrik / Gudang': [
        'Buruh Pabrik / Gudang',
        'Kepala Pabrik / Gudang',
        'Teknisi Mesin',
        'Lainnya',
        'All'
    ],
    'Konstruksi / Real Estate': [
        'Arsitek / Tehnik Sipil',
        'Interior Designer',
        'Mandor',
        'Pemborong',
        'Proyek Manager / Surveyor',
        'Real Estate Broker',
        'Tukang Bangunan',
        'Lainnya',
        'All'
    ],
    'Pendidikan': [
        'Dosen',
        'Guru',
        'Instruktur / Pembimbing Kursus',
        'Kepala Sekolah',
        'Tata Usaha',
        'Lainnya',
        'All'
    ],
    'Entertainment / Event': [
        'DJ / Musisi',
        'Event Organizer',
        'Kameraman',
        'Penyanyi / Penari / Model',
        'Produser / Sutradara',
        'Lainnya',
        'All'
    ],
    'Perbankan': [
        'Back-office',
        'Bank Teller',
        'CS Bank',
        'Credit Analyst',
        'Kolektor',
        'Resepsionis',
        'Lainnya',
        'All'
    ],
    'Perhotelan': [
        'Customer Service',
        'Kebersihan',
        'Koki',
        'Room Service / Pelayan',
        'Lainnya',
        'All'
    ],
    'Admin / Finance / HR': [
        'Admin',
        'Akuntan / Finance',
        'HR',
        'Office Boy',
        'Sekretaris',
        'Lainnya',
        'All'
    ]
}


JOB_TYPE = [
    ('Pegawai swasta', 'Pegawai swasta'),
    ('Pegawai negeri', 'Pegawai negeri'),
    ('Pengusaha', 'Pengusaha'),
    ('Freelance', 'Freelance'),
    ('Pekerja rumah tangga', 'Pekerja rumah tangga'),
    ('Lainnya', 'Lainnya'),
    ('Staf rumah tangga', 'Staf rumah tangga'),
    ('Ibu rumah tangga', 'Ibu rumah tangga'),
    ('Mahasiswa', 'Mahasiswa'),
    ('Tidak bekerja', 'Tidak bekerja')
]


PROVINCE = [
    ('Gorontalo', 'Gorontalo'),
    ('Lampung', 'Lampung'),
    ('DI Yogyakarta', 'DI Yogyakarta'),
    ('Kalimantan Selatan', 'Kalimantan Selatan'),
    ('Riau', 'Riau'),
    ('DKI Jakarta', 'DKI Jakarta'),
    ('Jawa Timur', 'Jawa Timur'),
    ('Kalimantan Timur', 'Kalimantan Timur'),
    ('Kalimantan Utara', 'Kalimantan Utara'),
    ('Nanggroe Aceh Darussalam (NAD)', 'Nanggroe Aceh Darussalam (NAD)'),
    ('Kalimantan Tengah', 'Kalimantan Tengah'),
    ('Jambi', 'Jambi'),
    ('Kalimantan Barat', 'Kalimantan Barat'),
    ('Maluku', 'Maluku'),
    ('Bali', 'Bali'),
    ('Nusa Tenggara Barat (NTB)', 'Nusa Tenggara Barat (NTB)'),
    ('Sulawesi Tengah', 'Sulawesi Tengah'),
    ('Sumatera Barat', 'Sumatera Barat'),
    ('Bangka Belitung', 'Bangka Belitung'),
    ('Sumatera Selatan', 'Sumatera Selatan'),
    ('Jawa Barat', 'Jawa Barat'),
    ('Banten', 'Banten'),
    ('Kepulauan Riau', 'Kepulauan Riau'),
    ('Maluku Utara', 'Maluku Utara'),
    ('Sumatera Utara', 'Sumatera Utara'),
    ('Bengkulu', 'Bengkulu'),
    ('Papua', 'Papua'),
    ('Nusa Tenggara Timur (NTT)', 'Nusa Tenggara Timur (NTT)'),
    ('Sulawesi Selatan', 'Sulawesi Selatan'),
    ('Jawa Tengah', 'Jawa Tengah'),
    ('Sulawesi Tenggara', 'Sulawesi Tenggara'),
    ('Papua Barat', 'Papua Barat'),
    ('Sulawesi Utara', 'Sulawesi Utara'),
    ('Sulawesi Barat', 'Sulawesi Barat'),
]

ACTION = [
    ('No Bypass', 'No Bypass'),
    ('Reject 105', 'Reject 105'),
]
